### ISSUE TITLE
[Tooltip] tooltip is not triggered when tooltip covers trigger

### ISSUE THREAD

**Issue by bengeorge** [radix-ui/primitives#1001]
## Bug report

Tooltip is not triggered when tooltip covers trigger.

### Current Behavior

When you have a tooltip that covers a trigger, it is possible to end up hovering over a trigger and no tooltip displayed.

I tried using `pointerEvent: "none",` on the tooltip content, but that didn't seem to work.

### Expected behavior

When focusing on a trigger after a tooltip is hidden, it should show always show the tooltip.

### Reproducible example

https://codesandbox.io/s/dazzling-haze-4z9r5?file=/App.js

In the example sandbox:

1. Start with mouse off both buttons and no tooltip showing
1. Hover on button 1, wait untill tooltip is shown
1. Quickly move mouse onto button 2

The image below shows an icon hovered (red) and no tooltip.

![image](https://user-images.githubusercontent.com/6659128/143385473-80145b7c-f37c-4f25-96ec-a74873e3d2db.png)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     radix-ui/react-tooltip    |   0.1.1      |
| React            | n/a     |     17.0.2    |
| Browser          |     Chrome    |      96.0.4664.45    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    Windows     |    10     |

**Comment by bengeorge** [comment]
Is it because `onMouseEnter` is not being fired on the trigger as the mouse passes through the tooltip content ?

**Comment by jjenzz** [comment]
Thanks @bengeorge,

I tried this on crossbrowsertesting.com and it initially seemed to work okay:

https://user-images.githubusercontent.com/175330/143451983-408f62ff-db23-4557-bd55-b8142e839151.mp4

However, there does appear to be some edge-cases where I can catch it and it won't appear but I'm not certain what the variables are here:

https://user-images.githubusercontent.com/175330/143452343-e3e1db81-c480-42fb-ba23-2f8f5f04235b.mp4

I'll be taking a look at `Tooltip` stuff over the next week among other bits to improve React 18 support so I'll keep this in mind while doing those bits and hopefully come up with something to solve this.
