### ISSUE TITLE
[Tooltip] Trigger assumes type="button"

### ISSUE THREAD

**Issue by ericmatthys** [radix-ui/primitives#1010]
### Current Behavior

https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.tsx#L192

The `TooltipTrigger` assumes a button, but I think it's also common to use tooltips with links. If `asChild={true}` is used with an `<a>` child, then the anchor ends up as `<a type="button" ...>`.

### Expected behavior

I'd expect to be able to use an `<a>` child without it receiving `type="button"`.

### Reproducible example

https://codesandbox.io/s/tooltip-trigger-type-kepl8

### Suggested solution

It may not make sense to pass the `type` attribute through when using `asChild={true}`.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  tooltip       |  0.1.1       |
| React            | n/a     |  17.0.2       |
| Browser          |  n/a       |  n/a       |
| Assistive tech   |  n/a       |   n/a      |
| Node             | n/a     | n/a        |
| npm/yarn         |  n/a       |  n/a       |
| Operating System |  n/a       | n/a        |

**Comment by ericmatthys** [comment]
Potentially a duplicate of https://github.com/radix-ui/primitives/issues/993

**Comment by seedy** [comment]
@ericmatthys I permit myself to add that anchor elements also have a `type` attribute which has a totally different meaning than button `type`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-type

**Comment by benoitgrelard** [comment]
Thanks for nothing this @seedy! I didn't personally know about that, it's looking more and more like we should restrain from adding the `type` attribute alltogether and leave that to users.

**Comment by jjenzz** [comment]
>  it's looking more and more like we should restrain from adding the `type` attribute alltogether and leave that to users.

Yep, think I'll just go ahead and do this as I have a spare minute.
