### ISSUE TITLE
[Slot] Triggers a warning in dev mode about keys

### ISSUE THREAD

**Issue by dbismut** [radix-ui/primitives#1013]
### Current Behavior

Current warning is shown in the console:

```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Slot`.
```

### Reproducible example

https://codesandbox.io/s/jolly-cdn-5wor8

(don't mind the tailwind classes)

### Suggested solution

I think the problem lies in here, no `key` attribute seems to appear:

https://github.com/radix-ui/primitives/blob/e9f43ed94b53a0c07279fddbe7371bd54a53cfd4/packages/react/slot/src/Slot.tsx#L17-L28

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      tooltip   |     0.1.1    |
| React            | n/a     |    17.0.2     |

**Comment by jjenzz** [comment]
Thanks for the report. A release candidate (`@next`) for the components has been published that fixes this :+1:

**Comment by jjenzz** [comment]
@davincios would you mind raising a new bug with a reproduction of your issue please? when trying to repro the original report with the latest version i don't see any slot warnings https://codesandbox.io/s/jovial-murdock-2dc221

**Comment by StanlyLife** [comment]
receiving the same error:

![image](https://user-images.githubusercontent.com/13099896/217850503-f5018135-1aa6-40b0-b158-c2d6caaffde8.png)


code:

```tsx
function RemoveUserButton() {
    return (
        <AD.Trigger asChild>
            <Button>
                <FontAwesomeIcon icon={['fas', 'x']} />
            </Button>
        </AD.Trigger>
    );
}
```

```tsx
export function ManageUsersForRoleGridGridColumnDefinitionsCellRenderer(param: ICellRendererParams<Demo>) {
    return (
        <div className={styles['demo']}>
            <Alert
                action={DemoAction()}
                description='placeholde text for demo'
                title={`placeholder text for demo`}
            >
                <RemoveUserButton />
            </Alert>
        </div>
    );
}
```

**Comment by joaom00** [comment]
Hey @StanlyLife, are you using `React.forwardRef` in your `Button` component?

**Comment by StanlyLife** [comment]
> Hey @StanlyLife, are you using `React.forwardRef` in your `Button` component?

Here is my button:

```tsx
export type buttonTypes = 'button' | 'reset' | 'submit' | undefined;

export function Button({
    variant = '',
    children = '',
    className = '',
    type = 'button',
    onClick,
    ...other
}: {
    variant?: string;
    children?: any;
    className?: string;
    onClick?: () => void;
    type?: buttonTypes;
}) {
    return (
        <button {...other} className={`DEMO ${variant} ${className}`} onClick={onClick} ref={null} type={type}>
            {children}
        </button>
    );
}
```

**Comment by joaom00** [comment]
Yep, you should use `React.forwardRef` and spread all props to it, something like:

```jsx
const Button = React.forwardRef<HTMLButtonElement, YourButtonProps>((props, forwardedRef) => {
  return <button {...props} ref={forwardedRef} />
})
```

**Comment by StanlyLife** [comment]
This worked great, thank you!
How come the error complains about the Slotclone component?

**Comment by benoitgrelard** [comment]
Because `asChild`'s implementation relies on our `Slot` utility (which uses `SlotClone`).
