### ISSUE TITLE
[Accordion] Documentation does not explicitly showcase that `defaultValue` must be an array when type is multiple

### ISSUE THREAD

**Issue by jacobmendoza** [radix-ui/primitives#1014]
### Relevant Radix Component(s)

Accordion

### Description

I have been doubting if this would make sense for you and also if it would fall for you in the category of documentation or bug/improvement. Even that in hindsight the error is pretty evident, it can be considerably confusing for someone trying out the components for the first time, without Typescript, as the minified stack trace of the error is not really helpful.

The example for "[multiple items open at the same time](https://www.radix-ui.com/docs/primitives/components/accordion#multiple-items-open-at-the-same-time)" does not showcase an example of the defaultValue property given as an array, information that you would have at compile time if you use Typescript, but remains completely hidden if you don't. It is true that it appears perfectly well in the API Reference.

One naive reader of the documentation, copying and pasting parts of examples could end up with:

```
<Accordion type="multiple" defaultValue="item-1">
  <AccordionItem value="item-1">
    <AccordionTrigger>Option 1</AccordionTrigger>
    <AccordionContent>Yes. It adheres to the WAI-ARAI design pattern.</AccordionContent>
  </AccordionItem>
  <AccordionItem value="item-2">
    <AccordionTrigger>Option 2</AccordionTrigger>
    <AccordionContent>Yes. It adheres to the WAI-ARAI design pattern.</AccordionContent>
  </AccordionItem>
</Accordion>
```

That fails with:

```
TypeError: o.filter is not a function
...
...
```

Not sure what you're opinion will be on this. Again, feels trivial in hindsight, but not so evident in the heat of the moment when literally everything that you're doing is new. For beginners like myself trying out this component for the first time, these three different options would have made a difference:

1. Make the example more explicit by adding one defaultValue as an example that is an array `(defaultValue={[...]})`.
2. Detect that the type is not correct and throw a custom error.
3. Make the code more robust and wrap the value in the array if it isn't one?.

Thanks for all the amazing work made here.

**Comment by benoitgrelard** [comment]
Hi @jacobmendoza,

I believe we have recently added some proptypes specifically for this so the error you get now should be a lot more obvious.

https://github.com/radix-ui/primitives/pull/979/files

You can try this using the latest release candidate of this component: https://www.npmjs.com/package/@radix-ui/react-accordion/v/0.1.2-rc.5

I'll close the issue but let me know if we haven't addressed it enough for you.
