### ISSUE TITLE
[Presence] `onAnimationEnd` doesn't fire on close

### ISSUE THREAD

**Issue by dmwin72015** [radix-ui/primitives#1020]
## Question
I want to execute some functions at the end of the animation.  How do i know the animation is over!

Is there something like `afterClose`  props
thanks!!!

**Comment by jjenzz** [comment]
Hi @dmwin72015 👋

You should be able to use [any of React's supported events](https://reactjs.org/docs/events.html#supported-events) on our parts but it looks like `onAnimationEnd` isn't firing on close 🤔

I'll convert this to a bug for us to investigate. Thanks for raising!

**Comment by dmwin72015** [comment]
> You should be able to use [any of React's supported events](https://reactjs.org/docs/events.html#supported-events) on our parts but it looks like `onAnimationEnd` [isn't firing on close](https://codesandbox.io/s/staging-smoke-ssxiq?file=/App.js) 🤔
> 
> Seems to be a bug in `Presence` somewhere. Thanks for raising! I'll rename the ticket and we'll take a look when we can.

thanks!

**Comment by gadishimwe** [comment]
For someone looking for a workaround while we're waiting for https://github.com/radix-ui/primitives/pull/1849 to be merged, you can use `onAnimationEndCapture` instead. It's working fine for me.
