### ISSUE TITLE
Uncaught SyntaxError: The requested module '/_snowpack/pkg/react.v17.0.2.js' does not provide an export named 'useId'

### ISSUE THREAD

**Issue by polRk** [radix-ui/primitives#1023]
### Current Behavior

Try to use label component from radix-ui library
### Expected behavior
It works
### Reproducible example

No

### Suggested solution

I do not know

### Additional context

```
        "@snowpack/plugin-dotenv": "^2.1.0",
        "@snowpack/plugin-postcss": "^1.4.3",
        "@snowpack/plugin-react-refresh": "^2.5.0",
        "@snowpack/plugin-typescript": "^1.2.1",
        "@snowpack/web-test-runner-plugin": "^0.2.2",
        "@types/snowpack-env": "^2.3.3",
        "snowpack": "^3.3.7",
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-label       |  0.1.2       |
| React            | n/a     |  17.0.2       |
| Browser          |         |  Chrome       |
| Assistive tech   |         |         |
| Node             | n/a     |  v16.13.1       |
| npm/yarn         |         |         |
| Operating System |   MacOS      |  Mont       |

**Comment by fzembow** [comment]
I don't know much about the code but I suspect the reason is similar to https://github.com/radix-ui/primitives/issues/1026 ... `react-id` started exporting a `useId` instead of `IdProvider`, perhaps the reporter here has some components that depend on `0.1.2` but he still has `0.1.1` of `react-id` installed.

**Comment by polRk** [comment]
Why did you let this happen? 
https://github.com/radix-ui/primitives/blob/55a422c5830a52d9f050369412a7dc8cf6e44786/packages/react/id/src/id.tsx#L4

**Comment by benoitgrelard** [comment]
> Why did you let this happen?
> 
> https://github.com/radix-ui/primitives/blob/55a422c5830a52d9f050369412a7dc8cf6e44786/packages/react/id/src/id.tsx#L4

We do this to support both React 17 and React 18, so if `React.useId` doesn't exist, we fallback to something else.

I can't really understand why you're getting this error though 🤔 
`React.useId` in 17 should be `undefined`, therefore falling back to our `() => undefined`.

It's as if it's trying to transform it into an import or something…

Do you have a reproduction of this somewhere we could take a look at?
