### ISSUE TITLE
0.1.2 of @radix-ui/react-id no longer exports IdProvider

### ISSUE THREAD

**Issue by fzembow** [radix-ui/primitives#1026]
Hi! Lovely library. Thank you - started using it on small new projects.

### Current Behavior

If I install with `yarn add @radix-ui/react-id@0.1.2` and then import:

```tsx
import { IdProvider } from '@radix-ui/react-id';
```
... IdProvider is no longer exported.

TS will complain: 

```
Module '"@radix-ui/react-id"' has no exported member 'IdProvider'.ts(2305)
```

I was using this in a Next.js app, and the problem first manifest itself as:

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

... since I was wrapping my whole app with this and it was returning undefined.

### Expected behavior

The following should work, particularly since it's encouraged in [the documentation on server-side-rendering](https://www.radix-ui.com/docs/primitives/overview/server-side-rendering).

```tsx
import { IdProvider } from '@radix-ui/react-id';
```

### Suggested solution

Re-export it? Or make a major version change if you're removing an existing export.

### Your environment

yarn 1.22.17

**Comment by reesscot** [comment]
+1, we are experiencing this as well.

**Comment by benoitgrelard** [comment]
Sorry about that, we are in the process of doing a new release but the docs aren't quite out yet, that's why we haven't officially announced yet.

The release docs will highlight the breaking changes as they always do.
The reason it's not a new "major" version is because we are still in the `0.1.x` range as we are in beta.

Bare with us, it should all be out properly tomorrow.

**Comment by ericclemmons** [comment]
Thanks for the quick response @benoitgrelard .

And we totally understand that `0.x.x` ranges are outside of semver :)

**Comment by benoitgrelard** [comment]
@ericclemmons thanks.
Worth reiterating perhaps, but we do recommend to pin the versions to avoid these kind of suprises whilst we're not yet in final v1.

In the meantime, you can already see here ahead of time [the upcoming release notes](https://github.com/radix-ui/website/pull/296/files) as well as [the related docs changes](https://github.com/radix-ui/website/pull/295).

**Comment by StephenHaney** [comment]
Apologies for the broken builds!

To help others avoid this, we're going to publish a new patch with an empty IdProvider that `console.warns` a deprecation link to the docs. We're also working on getting to semver. In the meantime, as Benoit says, we recommend pinning versions until the Primitives hit 1.0.

---

More info on the actual change: Once you're using React 18, primitives use the new `useId` hook automatically 🎉 While using older versions of React, Radix components will now re-render during client hydration. So the `IdProvider` is no longer necessary.

Thanks for the report and understanding!

**Comment by jjenzz** [comment]
The `IdProvider` has been released with the warnings mentioned above. https://github.com/radix-ui/primitives/pull/1037

**Comment by kyle-mccarthy** [comment]
Is it possible to not log the warning in production? It looks like it is getting sent to sentry on every page load. 

React 18 is still in beta, not all libraries are updated to work with it yet and some companies can't or aren't comfortable with running beta software.

**Comment by StephenHaney** [comment]
Hey Kyle - that's a good idea, we will remove the log in prod. That said, if you're using primitives that are logging the warning, you should be able to remove the IdProvider now, even if you're not using React 18 yet.

**Comment by kyle-mccarthy** [comment]
@StephenHaney ah I understand now, I thought the options were either use IdProvider or use React 18. Thanks for clarifying that, I appreciate it!
