### ISSUE TITLE
No matching version found for @radix-ui/react-id@0.1.3.

### ISSUE THREAD

**Issue by mattdaly** [radix-ui/primitives#1029]
## Bug report

The package `@radix-ui/react-id` does not have a published `latest` release for `0.1.3`. I see a recent release (~1 hour) introduced this, so a fix is probably already in the works but raising it here for visibility.

```
npm ERR! notarget No matching version found for @radix-ui/react-id@0.1.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Current Behavior

The result is that install fails when installing dependant packages. For example our package.json has `react-popover` as a dependency, and our ci builds have begun failing. `react-popover` is published as `0.1.3` on the `latest` tag, but `react-id` only has an `0.1.3-rc.1` on the `next` tag, so the install fails.

```js
{ 
    "dependencies": {
        "@radix-ui/react-popover": "^0.1.1"
     }
}
```

Fixing the version of `react-popover` of course fixes this temporarily.

**Comment by benoitgrelard** [comment]
Yeah it seems there are some issues with the npm regsitry, so some packages weren't published properly.
We've contacted them on their support page as well as on twitter.
Sorry about that.

**Comment by mattdaly** [comment]
Ah yes I just saw on @jjenzz twitter as well, thanks for the response and I will keep an eye on the releases. Thanks for the great work 🤘

**Comment by mattdaly** [comment]
This is now resolved, so I shall close it.
