### ISSUE TITLE
[DropdownMenu] `ReferenceError: DOMRect is not defined` when doing a `jest` + `react testing library` test

### ISSUE THREAD

**Issue by ItzaMi** [radix-ui/primitives#1036]
### Current Behavior

I'm almost positive that it's I who is doing something wrong but it's my first time using `radix-ui` and doing tests for it (this is probably not even an issue with `radix-ui` but rather with `jest` or `react testing library`)

I'm currently testing a `UserBadge` that has a `DropdownMenu` inside and I'm using `jest` and `react testing library` to run tests on it.

I'm using a `data-testid` attached to `DropdownMenu.Trigger` to find it and I'm trying to to run a `click` `userEvent` on it so that I can interact with it.
From this I'm getting an `Error: Uncaught [ReferenceError: DOMRect is not defined]` and I'm not sure how to tackle it

### Expected behavior

I'm not really sure what I'm expecting but by giving a `data-testid` to my `DropdownMenu.Trigger` (and seeing that my test is finding it in the document), I'm expecting to be able to run a `click` event on it and then click on one of the `DropdownMenu.Item`

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-ui-dropdown-menu-testing-9i2z9?file=/src/components/UserBadge/index.tsx)

### Suggested solution

_Nothing comes to mind_

### Additional context

_Nothing to add_

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `@radix-ui/react-dropdown-menu`    |     `^0.1.3`    |
| React            | n/a     |    `17.0.2`     |
| Browser          |    Chrome     |    Version 96.0.4664.55 (Official Build) (arm64)     |
| Assistive tech   |     -    |      -   |
| Node             | n/a     |     `v14.18.1`    |
| npm/yarn         |   `yarn`      |     `1.22.17`    |
| Operating System |    macOS Big Sur     |      `11.2.3`   |

**Comment by benoitgrelard** [comment]
Hi @ItzaMi you are most likely NOT doing anything wrong 🙂

The test environment (jsdom in particular) isn't a full representation of the real DOM/js engine.
So sometimes certain APIs aren't there and you have to mock them.

Have a look at this comment here: https://github.com/radix-ui/primitives/issues/420#issuecomment-771615182

I will close for now as we have answered this above, but feel free to re-open if I haven't addressed your issues or you can't find what you need already in previously closed issues.
