### ISSUE TITLE
Tooltip visibility changes in 0.1.5

### ISSUE THREAD

**Issue by zslabs** [radix-ui/primitives#1038]
### Current Behavior

Adjacent tooltip triggers reset the visibility timeout between hovers; forcing users to wait

https://user-images.githubusercontent.com/1018402/145914923-745eb5ac-721f-42bf-8549-5ba4151b1feb.mov

### Expected behavior

In `0.1.1` I felt the UX was more intuitive

https://user-images.githubusercontent.com/1018402/145915014-a6229103-5ac0-4cf0-ad3e-953f2cf260e8.mov

### Reproducible example

N/A

### Suggested solution

Visibility logic is restored to `0.1.1` behavior

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Tooltip     |    (0.1.1 vs 0.1.5)      |
| React            | n/a     |    17.0.2     |
| Browser          |    Firefox     |    95.0     |
| Assistive tech   |     N/A    |         |
| Node             |  N/A     |         |
| npm/yarn         |    yarn     |     1.22.15    |
| Operating System |   Mac OS      |         |

**Comment by benoitgrelard** [comment]
Are you wrapping your app with the new `TooltipProvider`?

**Comment by zslabs** [comment]
@benoitgrelard Ah! I didn't go into detail from the changelog as that line item sounded optional, but that makes sense. Thanks!
