### ISSUE TITLE
[Accordion] Closing an element causes all other elements to close momentarily

### ISSUE THREAD

**Issue by axelhzf** [radix-ui/primitives#1040]
### Current Behavior

https://user-images.githubusercontent.com/175627/145973966-2489181c-1f0f-43b8-9000-de8335ca67d5.mp4

The first time that an element is closed, it causes all the other elements to close momentarily. After the initial close, the rest of the open or close actions work properly.

### Expected behavior

The first time the element is closed should work like the other ones

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/lucid-noyce-59nhm?file=/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-accordion       |  0.1.4        |
| React            | n/a     |  17.0.2        |
| Browser          |   Chrome      |  96.0.4664.93     |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | macOs        |  12.0.1        |

**Comment by benoitgrelard** [comment]
Hey @axelhzf, thanks or reporting this.
That's a bizarre one haha.
It seems to only happen when `value` is controlled AND all items are expanded 🤔

**Comment by anudeepreddy** [comment]
Hi, 

I would like to work on this issue. I have observed that this behavior is observed because of `animation: 0s ease 0s 1 normal none running none; ` being injected in styles. The first render has these styles for AccordionContent but consecutive renders doesn't have that style. Can someone point me to how that particular style is being injected?

**Comment by jjenzz** [comment]
@anudeepreddy Oh gosh I'm so sorry! We were already working on it and have just merged a fix. Apologies for jumping in there 🙈

**Comment by axelhzf** [comment]
Thank you for the fix @jjenzz
