### ISSUE TITLE
[Switch] Can't pass a ref to the underlying input element

### ISSUE THREAD

**Issue by davbrito** [radix-ui/primitives#1045]
## Feature request
The input element should be accesible through a ref prop for use in libraries like react-hook-form that accesses the value of the native element directly.

### Overview

A `inputRef` prop in the `Switch.Root` to access the input element.

### Examples in other libraries

The MUI library exposes the input element ref [through the `inputRef` prop](https://mui.com/api/switch/#props) 
![image](https://user-images.githubusercontent.com/39559632/146058923-3ef8ce7f-700c-4b50-9d55-f31e73657009.png)

[https://mui.com/api/switch/#props](https://mui.com/api/switch/#props)

### Who does this impact? Who is this for?

Everyone using react-hook-form, so they don't have to use a Controller for using this component. Or people who want to access the input element for any other purpose.

### Additional context

https://react-hook-form.com/api

**Comment by benoitgrelard** [comment]
Hi @davbrito,

The fact that there's an `input` is just an implementation detail for form event handling so it shouldn't really be needed to achieve compatibility with other libs.

I believe we have already answered this in a similar discussion here: https://github.com/radix-ui/primitives/discussions/874

Let us know if this addresses your concerns.

**Comment by davbrito** [comment]
The controlled input approach doesn't serve to my use case where i have a set of switches representing an array of items.

Here is a codesandbox with an example where you can see the expected behavior with native checkboxes. 
https://codesandbox.io/s/delicate-cache-x1532?file=/src/App.js

**Comment by jjenzz** [comment]
@davbrito The link that @benoitgrelard provided walks through how to do this with react-hook-form. You need to use their `Controller`.

Here's an example with `Switch` https://codesandbox.io/s/romantic-marco-y8vog?file=/src/App.js

**Comment by davbrito** [comment]
> @davbrito The link that @benoitgrelard provided walks through how to do this with react-hook-form. You need to use their `Controller`.
> 
> Here's an example with `Switch` https://codesandbox.io/s/romantic-marco-y8vog?file=/src/App.js

That way I would end up messing up the state of the form if for example I reorder, add or remove items.

**Comment by jjenzz** [comment]
> That way I would end up messing up the state of the form if for example I reorder, add or remove items.

I'm not sure what you mean here... do you have an example of the issue that re-ordering creates?
