### ISSUE TITLE
[ScrollArea] Add `Presence` to `ScrollThumb`

### ISSUE THREAD

**Issue by tawhidurrahman** [radix-ui/primitives#1050]
## Feature request
`Thumb` component's unmounting state of `Scroll Area` primitives to be animatable with stitches.

### Overview
I tried to animate the `opacity` of `Thumb` component's unmount state with stitches but couldn't. So one of your maintainers suggested me to add an issue.

```
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
const ScrollAreaScrollbar = styled(ScrollAreaPrimitive.Scrollbar, {});

const show = keyframes({ '0%': { opacity: 0 }, '100%': { opacity: 1 } });

const fade = keyframes({ '100%': { opacity: 1 }, '0%': { opacity: 0 } });

export const ScrollAreaThumb = styled(ScrollAreaPrimitive.Thumb, {
  flex: 1,
  borderRadius: 6,
  backgroundColor: '#aaa',
  position: 'relative',
  [`${ScrollAreaScrollbar}[data-state="visible"] &`]: {
    animation: `${show} .2s forwards linear`,
  },

  //I want something like this

  [`${ScrollAreaScrollbar}[data-state="hidden"] &`]: {
    animation: `${fade} .2s forwards linear`,
  },
});
```

### Examples in other libraries
Checkout the thumb animation here. They are using `perfect-scrollbar`.

[https://demos.creative-tim.com/black-dashboard-pro-react/?_ga=2.257667595.1079478053.1638938139-485400365.1601043380#/admin/dashboard](url)

### Who does this impact? Who is this for?
Anyone specially me who want a beautiful smooth scrollbar.

**Comment by jjenzz** [comment]
@tawhidurrahman I know I requested this ticket because I forgot to add `Presence` to the thumb but, in case it helps your use-case, you can animate the whole scrollbar instead https://codesandbox.io/s/laughing-darwin-9sdcd?file=/src/App.js

**Comment by tawhidurrahman** [comment]
That'll do for now. Thank you. But whenever you can please try to add this feature.
