### ISSUE TITLE
[DropdownMenu] Clicking on trigger when menu is open and `modal={false}` closes then immediately reopens menu

### ISSUE THREAD

**Issue by mrdavidjcole** [radix-ui/primitives#1059]
_Happy New Year, Radix! 🎉_

### Current Behavior

If you set `modal={true}` on `DropdownMenu.Root`, clicking on the trigger when the menu is open will close but then immediately reopen the menu.

![CleanShot 2022-01-01 at 13 15 59](https://user-images.githubusercontent.com/752729/147857395-e934329b-49e1-4f1b-a448-4c6796cac2cb.gif)

### Expected behavior

Clicking on the trigger should only ever close or open the menu (not both in quick succession), regardless of whether `modal={true}` or `modal={false}`.

![CleanShot 2022-01-01 at 13 24 20](https://user-images.githubusercontent.com/752729/147857558-eeaad909-eaf6-4ee8-b3bc-0560a5678a70.gif)

### Reproducible example

https://codesandbox.io/s/radix-dropdown-menu-modal-double-trigger-bug-un41f?file=/App.js

### Suggested solution

I'm not sure.

### Additional context

I found that this behavior is introduced in `0.1.2-rc.7`. It does not happen on `0.1.2-rc.6`.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-dropdown-menu    |    0.1.4 (but bug introduced in 0.1.2-rc.7)     |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |     Version 97.0.4692.56 (Official Build) beta (arm64)    |
| Assistive tech   |     none    |         |
| Node             | n/a     |     10.20.1    |
| npm/yarn         |    whichever codesandbox uses by default     |     unknown    |
| Operating System |     macOS    |    12.1     |

**Comment by andy-hook** [comment]
Thanks for reporting @mrdavidjcole and for digging deeper to narrow down the regression. Looks an `onClick` addition we made recently is causing this. Will raise a fix when we next have a moment.

**Comment by narciso-dev** [comment]
+1

**Comment by jjenzz** [comment]
A fix is available in `0.1.5-rc.8`
