### ISSUE TITLE
[Dialog] framer-motion exit animations for Portals require `forceMount` prop on descendants.

### ISSUE THREAD

**Issue by heyitsarpit** [radix-ui/primitives#1061]
This bug report is inspired by discussion #1058, identified by @jjenzz 

### Current Behavior

Current way to enable exit animations with framer-motion is:
- wrap the `Portal` in `AnimatePresence`
- Make it a controlled component
- place `forceMount` prop on `<Portal />` as well as `<Overlay />` and `<Content />`.

### Expected behavior

`forceMount` prop should only be required on `<Portal />` and not it's direct descendants.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-dialog    |    0.1.5     |
| React            | n/a     |    17.0.2     |
| framer-motion            | n/a     |     5.5.5     |
| Browser          |     Firefox    |    95      |
| Assistive tech   |    not used     |         |
| Node             | n/a     |     v16.13.0   |
| npm/yarn         |    yarn     |      1.22.17   |
| Operating System |    macOS(Apple Silicon)     |   Big Sur 11.6.2     |

**Comment by AnishDe12020** [comment]
Looking forward to this being fixed.

**Comment by benoitgrelard** [comment]
Hey @heyitsarpit I know you've moved away to CSS animation, but just letting you know anyway that this is now available in the latest rc: 0.1.8-rc.1

**Comment by heyitsarpit** [comment]
> Hey @heyitsarpit I know you've moved away to CSS animation, but just letting you know anyway that this is now available in the latest rc: 0.1.8-rc.1

thanks! i found some other bugs in framer-motion, unrelated to primitives, so will stick with css animations for this usecase of mine.

**Comment by benoitgrelard** [comment]
No worries, we do love the simplicity of using CSS animations too here 🙂
