### ISSUE TITLE
[DropdownMenu] Open on trigger-hover

### ISSUE THREAD

**Issue by rejas** [radix-ui/primitives#1067]
### Overview
Currently it seems that only clicking on the DropdownMenu.Trigger opens the Dropdownmenu. 

I would like already open it when hovering over the trigger.

### Who does this impact? Who is this for?

This is for myself and would help me implement a menubar where the dropdown is the 2nd level that pops up when I hover over the 1st level menu items.

**Comment by benoitgrelard** [comment]
Hi @rejas,

If I understand correctly, based on what you are mentioning it sounds like you are using the wrong component for the job and what you are after is components to build a menu bar (like on top of any app, or in MacOS top menu bar).

`MenuBar` is a component we are planning to work on soon, which is basically a different composition of `Menu` (similar to what we do with `DropdownMenu` and `ContextMenu`). When we release it, it will work exactly like MacOS menu bar, so initial menu would open on click, but then you could hover to another one to open the next.

**Comment by rejas** [comment]
Yes, you are right, it's a menubar, but since I saw that this is not (yet) implemented, I hoped I could use the DropdownMenu.

But isnt "open on hover" something the Dropdown Menu could offer regardless?

**Comment by benoitgrelard** [comment]
> Yes, you are right, it's a menubar, but since I saw that this is not (yet) implemented, I hoped I could use the DropdownMenu.

Yeah, it's one of the ones that's next on our list.

> But isnt "open on hover" something the Dropdown Menu could offer regardless?

Potentially, but there are a few things that would need to be considered for that to work correctly, so we'd have to rethink pointer handling a bit.

**Comment by jjenzz** [comment]
@rejas Our components have a controlled API specifically so you can customise things like this: https://codesandbox.io/s/solitary-fog-ueqpb?file=/src/App.js

@benoitgrelard Interesting that I had to add `pointerEvents: 'auto'` to the trigger there. I wonder if we should be doing that internally?

**Comment by benoitgrelard** [comment]
> @benoitgrelard Interesting that I had to add `pointerEvents: 'auto'` to the trigger there. I wonder if we should be doing that internally?

It makes sense because of the dismissable layer. But that's what I mean though, the minute we'd want to allow hover as part of the API I think there's a lot more to it, similar constraints that we have on HoverCard and Tooltip that work with hover interactions, like implementing delays to prevent opening instantly, etc.

**Comment by rejas** [comment]
Thanks for the help, I solved it indeed with the controlled api part of your library. Will close this issue now since it isnt really a feature the lib needs as I see now.
Thanks again for your work!

**Comment by gabrielmlinassi** [comment]
@jjenzz When there's a gap between the trigger and the content, it closes the dropdown when moving the mouse to the content. Is there a way to fix it?

**Comment by jjenzz** [comment]
@gabrielmlinassi are you using the `sideOffset` prop? everything is working correctly here https://codesandbox.io/p/sandbox/eloquent-hertz-9sd9hw?file=%2FApp.jsx%3A25%2C77
