### ISSUE TITLE
[Tooltip] Multiple tooltips stay on screen when the tooltip has an exit animation

### ISSUE THREAD

**Issue by hipstersmoothie** [radix-ui/primitives#1071]
### Current Behavior

My tooltips have an exit animation with a delay. When mousing between the tooltips they both stay on screen for a period

https://user-images.githubusercontent.com/1192452/148426104-2acd7d6b-d48f-432f-8443-65d0a9db9954.mp4

### Expected behavior

First tooltip is hidden as the second tooltip is shown

### Reproducible example

https://codesandbox.io/s/runtime-forest-gcexu?file=/App.js

### Suggested solution

Immediately hide the previous tooltip if a second on is moused over, or provide a prop to do so

**Comment by benoitgrelard** [comment]
Hi @hipstersmoothie,

Thanks for raising this up.
I will close it as duplicate as we already have an issue about this specifically: #1068 

Thanks!
