### ISSUE TITLE
[Accordion] Close animation flickering in React 18

### ISSUE THREAD

**Issue by tomkuehl** [radix-ui/primitives#1074]
## Bug report

The Accordion close animation flickers when rendered using the upcoming concurrent mode for React. (ReactDOM.createRoot)

### Current Behavior

https://user-images.githubusercontent.com/14299145/148775476-a662ac9d-ada1-4068-b3a3-fa33d576a677.mp4

### Expected behavior

It shouldn't flicker when a closing animation is set and the accordion finished the closing animation.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/hungry-chatterjee-k5q7k)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-accordion     |     0.1.5 (bug also exists in latest rc)    |
| React            | n/a     |     18.0.0-rc.0    |
| Browser          |   Chrome     |     97.0.4692.71    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |     macOS (M1)    |    12.1     |

**Comment by dlehmhus** [comment]
I'm encountering the same flickering issue with the [@radix-ui/react-collapsible](https://www.radix-ui.com/docs/primitives/components/collapsible) component.

**Comment by benoitgrelard** [comment]
@dlehmhus, yeah that would make sense as `Accordion` is built on top of `Collapsible`.

**Comment by devianllert** [comment]
@jjenzz 
Encountering the same flickering issue with the [@radix-ui/react-dialog](https://www.radix-ui.com/docs/primitives/components/dialog) component.
It seems like all components that supports animations (Presence) have this issue (only with react@18.0.0, react@17.0.2 works fine).  Adding `animation-fill-mode: forwards` fixes that issue but it feels like a hack.

**Comment by benoitgrelard** [comment]
Hi, at the moment this is the solution, but we do agree that it kinda feels like a patch rather than an actual solution.
We will try and look into it more when we have some time.

**Comment by rickyzhangca** [comment]
still happens today with radix collapsible, once `hidden` is set on the content it repeats the close animation

**Comment by andypandy-tappit** [comment]
Came across this thread while investigating why my accordion element kept flickering closed and open while using drag and drop functionality.
![accordion_animation_flicker](https://github.com/radix-ui/primitives/assets/153526083/b7dedbcd-92f3-46dc-bba9-b0aa97f09ad7)

Seems like it's probably related. I'm using react 18.2.0 with react-beautiful-dnd. The gif attached is with `animation-fill-mode: forwards` specified but the flickering is still occurring. Removing animations solves the flickering

**Comment by pavlo976** [comment]
I encountered the same problem as above. Adding forwards nothing changes.

**Comment by a-hariti** [comment]
> I encountered the same problem as above. Adding forwards nothing changes.

+1

**Comment by pavlo976** [comment]
@andypandy-tappit 
It seems moving className prop to children solves this problem
### Old solution:
```js
const CollapsibleContent = React.forwardRef<
	React.ElementRef<typeof CollapsiblePrimitive.CollapsibleContent>,
	React.ComponentPropsWithoutRef<typeof CollapsiblePrimitive.CollapsibleContent>
>(({ className, ...props }, ref) => (
	<CollapsiblePrimitive.CollapsibleContent
		ref={ref}
		className={cn('overflow-hidden data-[state=open]:animate-collapsible-down data-[state=closed]:animate-collapsible-up', className)}
		{...props}
	/>
));
```
### New solution: 
```js
const CollapsibleContent = forwardRef<
	ElementRef<typeof CollapsiblePrimitive.Content>,
	ComponentPropsWithoutRef<typeof CollapsiblePrimitive.Content>
>(({ className, children, ...props }, ref) => (
	<CollapsiblePrimitive.Content
		ref={ref}
		className="overflow-hidden text-sm data-[state=closed]:animate-collapsible-up data-[state=open]:animate-collapsible-down"
		{...props}>
		<div className={cn("pb-4 pt-0", className)}>{children}</div>
	</CollapsiblePrimitive.Content>
))
```
Tailwind configuration animation and keyframes remain the same as before:
```js
keyframes: {
	'collapsible-down': {
		from: { height: '0' },
		to: { height: 'var(--radix-collapsible-content-height)' },
	},
	'collapsible-up': {
		from: { height: 'var(--radix-collapsible-content-height)' },
		to: { height: '0' },
	},
},
animation: {
	'collapsible-down': 'collapsible-down 0.2s ease-out',
	'collapsible-up': 'collapsible-up 0.2s ease-out',
},
```

**Comment by Onurfesci** [comment]
None of these solved the issue for me, it's still flickering on close. Has anyone found a solution to this?

**Comment by miloscript** [comment]
```
      keyframes: {
        "accordion-down": {
          from: {
            maxHeight: "0",
          },
          to: {
            maxHeight: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            maxHeight: "var(--radix-accordion-content-height)",
          },
          to: {
            maxHeight: "0",
          },
        },
```

using maxHeight will solve the issue
