### ISSUE TITLE
Clicking an AccordionTrigger within a `<form>` triggers the form submission

### ISSUE THREAD

**Issue by acc-nicholas** [radix-ui/primitives#1084]
### Current Behavior
Clicking a trigger submits the form because button `type` is `submit` by default in browsers. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

### Expected behavior
Clicking a trigger should probably not submit the form and should just open/close the accordion panel.

### Reproducible example

[Repro Example](https://codesandbox.io/s/solitary-moon-yzrcy?file=/src/App.tsx)

### Suggested solution
Defaulting the `type` attribute to `button` on the AccordionTrigger would probably solve the issue. This might apply to other trigger primitives as well.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Accordion     | 0.1.5        |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by slavanga** [comment]
@jjenzz I just ran into this issue with the Tooltip component inside a form triggering a submit.
What's the special reason why `type=button` isn't used for the Tooltip?

**Comment by jjenzz** [comment]
i can't recall now exactly, do you @benoitgrelard? perhaps it had something to do with the fact that tooltips wrap actionable things, and radix likely wouldn't want to control what your _action_ is. however, i'm not sure why consumers couldn't set `type="submit"` explicitly when that is the requirement.

**Comment by slavanga** [comment]
@jjenzz @benoitgrelard this is not about setting `type="submit"`, but preventing the tooltip trigger from becoming a form submit button. 

The tooltip trigger button currently has no explicit type. When nested inside a `<form>` browsers will implicitly assume `type="submit"`, which will trigger a form submit.

**Comment by jjenzz** [comment]
@slavanga yes, i understood that... i was proposing that maybe radix could set `type="button"` by default on the tooltip trigger and consumers could set it to "submit" explicitly when that is their requirement.

the same can be said in reverse tho—if you don't want your tooltip button to submit then add `type="button"` to the trigger. the bigger question tho is why all other comps are `type="button"` by default except for tooltip.

**Comment by slavanga** [comment]
@jjenzz ok, thanks for clarifying.

overriding works, but it would be optimal if all triggers had the same button type if possible.

**Comment by benoitgrelard** [comment]
Some background: https://github.com/radix-ui/primitives/pull/1011

https://github.com/radix-ui/primitives/pull/1011#pullrequestreview-822604542
> Trying to rationalise it, I feel like Tooltip.Trigger is the only trigger whose functionality isn't entirely relying on a click/pointerdown action. That makes me think that all the other triggers where we do type="button" have no business being replaced with other HTML elements as it wouldn't really be semantic anymore.

**Comment by jjenzz** [comment]
oh looks, like we explained further in the code:

![Screenshot 2023-04-26 at 14 18 23](https://user-images.githubusercontent.com/175330/234587449-3ff4e486-4e9d-4e51-ad1f-364ddbf0c1fb.png)

does that help @slavanga ? if someone did `<Tooltip.Trigger asChild><a href="">foo</a></Tooltip.Trigger>` then the type attribute would be telling the browser that the MIME type for the linked resource is "button" which is invalid.

**Comment by benoitgrelard** [comment]
Yep, it's just that generally tooltip can be added to a lot more types, even `input`, so we wouldn't want `input type="button"` either.

**Comment by slavanga** [comment]
@jjenzz @benoitgrelard thank you both for the explanations. that makes perfect sense.
maybe this info should be added to the tooltip docs.

**Comment by goleary** [comment]
Just spent longer than I'd like debugging an issue caused by the tooltip triggering a form. +1 for adding something in the docs about this.
