### ISSUE TITLE
[DropdownMenu] If menu is positioned over trigger it dismisses immediately

### ISSUE THREAD

**Issue by hipstersmoothie** [radix-ui/primitives#1089]
### Current Behavior

Use sideOffset to position content over trigger

### Expected behavior

Content doesn't immediately hide

### Reproducible example

https://codesandbox.io/s/peaceful-rosalind-tstmy?file=/src/App.tsx

### Suggested solution

Move to onPointerUp from onPointerDown

**Comment by benoitgrelard** [comment]
Hi @hipstersmoothie,

That is correct, however, given the pattern `DropdownMenu` is used for, the content should never be positioned over the trigger. It looks to me like you're trying to shoehorn this into a custom select of sorts, in which case it would be wrong from a functionality and accessibility point of view as they are 2 completely different patterns.

**Comment by hipstersmoothie** [comment]
Would you be open to a PR to change the onPointerUp to onPointerDown  dropdownmenu? While in my case I am in fact using it like a select (can't wait til you all release yours). But this bug presents itself if you at all position the menu over the button.

here I'm just slightly overlaying the content on the button. If I happen to click in the place where the menu appears it instantly goes away

https://user-images.githubusercontent.com/1192452/149810360-d8abdd71-081e-4a89-a2a3-1c1d5175366b.mp4

**Comment by benoitgrelard** [comment]
The event has to stay `onPointerUp` to allow certain behaviour and allow better accessibility.
That said, what you are after is something we are handling in the new `Select` so I am hopeful we will eventually be able to bring that to `DropdownMenu` as well.

**Comment by hipstersmoothie** [comment]
Is there any ETA for the Select? Got a lot of places where I could use that! Also FYI the dropdown-menu docs mention typeahead support, but there are no examples of how to do it

**Comment by benoitgrelard** [comment]
No specific ETA yet, but we are definitely towards the end of it, roughly if we don't encounter major issues, I'd say ~1 month, something like that, but don't quote me on it 😀

> Also FYI the dropdown-menu docs mention typeahead support, but there are no examples of how to do it

What we call typeahead support might not be what you expect, in this case (and same as native select, all our menus and our future `Select`) it's about being able to focus an item by typing the start of its label. Typing the first letter repeatedly will cycle through items that start with that letter, and typing the beginning of the word will jump to it.
