### ISSUE TITLE
[DropdownMenu] If Child of Trigger isn't interactive element focus doesn't get returned

### ISSUE THREAD

**Issue by hipstersmoothie** [radix-ui/primitives#1093]
### Current Behavior

Return focus doesn't work with wrapper around interactive component in a dropdown trigger

### Expected behavior

the focus returns to the trigger of the dropdown

### Reproducible example

https://codesandbox.io/s/kdbbq?module=App.js&file=/App.js

### Suggested solution

The problem here is that it focuses on the triggerRef instead of the html element that did the triggering. I see in other internal component you store the value of activeElement that initiated the trigger. If we returned focus to that it would work and would make Trigger content more flexible

**Comment by benoitgrelard** [comment]
Hi @hipstersmoothie,

I'm not sure I follow the issue. Looking at the sandbox I see no issue, I click the trigger and then when closing focus is returned to it.

Can you help me understand a bit better what you mean?

**Comment by hipstersmoothie** [comment]
Oops forgot to save the sandbox with my changes. I wrapped the `IconButton` in a `Box` and now the focus return breaks

https://codesandbox.io/s/fast-shape-47mv2?file=/App.js

**Comment by benoitgrelard** [comment]
Ah gotcha, makes sense.
Yeah, the trigger element definitely need to be an interactive element.
But the problem really is the usage of `asChild` here. `asChild` clones the "direct" child, so in this case the `Box`.

So you will want to avoid having your tree this way around:

```tsx
<DropdownMenu.Trigger asChild>
  <Box>
    <IconButton>
```

But rather have it like that if you really need that `Box`:

```tsx
<Box>
  <DropdownMenu.Trigger asChild>
    <IconButton>
```

Hope that makes sense, I'll close the issue for now, but feel free to keep discussing here!

**Comment by hipstersmoothie** [comment]
It makes sense that the trigger needs to have an interactive child. What doesn't make sense to me is why the dropdown menu isn't managing it's return focus via active element instead. I see other places in the codebase where this is the case and would remedy this situation. Using the trigger ref directly is pretty brittle compared to the activeElement. And if this isn't something you all are willing to change tt should at least be detailed in the docs since users of Radix could easily get into this situation.

**Comment by jjenzz** [comment]
Returning to the `triggerRef` is correct because that is the element that will have the `aria-controls` and other attributes required for accessibility. 

The `document.activeElement` approach is incorrect because if focus is inside the dropdown, and someone programatically calls `setOpen(false)` then it will try to return focus to the thing inside the dropdown which will have been unmounted, and is not the trigger.

**Comment by hipstersmoothie** [comment]
Ah that's a good point. I think this should be mentioned in the trigger docs since a user could easily break this interaction if they don't know the proper structure for the components. Thanks all for you quick responses!

**Comment by jjenzz** [comment]
> I think this should be mentioned in the trigger docs since a user could easily break this interaction if they don't know the proper structure for the components

The proper structure for the components is documented in the [anatomy section](https://www.radix-ui.com/docs/primitives/components/dropdown-menu#anatomy).

Would you mind helping me understand what it is you would like us to improve there so we can create a docs ticket?

**Comment by hipstersmoothie** [comment]
Where the trigger is listed is what I think could be improved:

```tsx
<DropdownMenu.Trigger />
```

Not sure how to fit it in the docs perfectly but if there was something along the lines of 

```tsx
<DropdownMenu.Trigger asChild>
   {/* When overriding the trigger you must use a component that can receive focus and has focus styling. Otherwise you will break the accessibility of this pattern */}
<DropdownMenu.Trigger>
```

While the `asChild` docs do tell you how to use `asChild` they don't mention the explicit parent-child relationship the content needs to be in to not break the experience for keyboard users.

**Comment by jjenzz** [comment]
I agree it would be good to call out this stuff but perhaps we can add a broader message the the `asChild` section:

> Using the `asChild` prop to change the underlying node type can impact the accessibility and functionality that we provide. 
>
> If you decide to change the node rendered by Radix then it is up to you to ensure the correct accessibility and functionality that isn't already handled by your chosen node type.

@benoitgrelard @andy-hook thoughts?

**Comment by benoitgrelard** [comment]
Yeah that sounds good to me as it would apply to all cases.
