### ISSUE TITLE
[Dialog] aria-describedby included when no description

### ISSUE THREAD

**Issue by bengeorge** [radix-ui/primitives#1094]
### Current Behavior

When no `DialogPrimitiv.Description` and no `aria-describedby` on `Dialog.Content` there is a `aria-describedby`attribute is on the dialog root.

![image](https://user-images.githubusercontent.com/6659128/149730205-6be2787a-6ee1-410f-9816-a20ef8c22c8e.png)
![image](https://user-images.githubusercontent.com/6659128/149730251-090477cf-f2de-4c86-adaf-ab7867700669.png)

### Expected behavior

No `aria-describedby`attribute on dialog root.

### Reproducible example

[No description CodeSandbox Template](https://codesandbox.io/s/jolly-alex-iq1b3)

Or you can just open the CodeSandbox from https://www.radix-ui.com/docs/primitives/components/dialog and delete the `DialogPrimitiv.Description`.

### Additional context

It appears `aria-describedby` is optional.

[Dialog roles](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_roles_states_props)

> Optionally, the aria-describedby property is set on the element with the dialog role to indicate which element or elements in the dialog contain content that describes the primary purpose or message of the dialog.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    dialog     |  0.1.5       |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hey @bengeorge 
Thanks for raising this!
It's probably because we always generate the id regardless, and have assumed the description is used.
We'll get that fixed!

Thanks!

**Comment by luisorbaiceta** [comment]
Can I work on this?
