### ISSUE TITLE
[Dropdown][AlertDialog][Dialog] Focus behavior is broken when AlertDialog/Dialog is used inside a Dropdown

### ISSUE THREAD

**Issue by hugobdev** [radix-ui/primitives#1096]
### Current Behavior

When a `AlertDialog` or `Dialog` is inside a `Dropdown`, tabbing between focusable elements is broken. The last focusable element seems to be focused and you can only tab through the first and last elements.

![CleanShot 2022-01-17 at 08 37 46](https://user-images.githubusercontent.com/4073936/149763340-9c660648-9b26-4847-b4c7-4fc18e9595e9.gif)

### Expected behavior

1. The first focusable element inside `<Dialog.Content>` or `<AlertDialog.Content>` should be focused when it opens
2. Tabbing through all focusable elements should work
3. Focus should be trapped to `.Content`

### Reproducible example

[Here's a CodeSandbox reproducing this issue.](https://codesandbox.io/s/gracious-snyder-i230o?file=/src/App.js)

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Additional context

I've adapted this example from [Jenna's solution](https://twitter.com/jjenzz/status/1478375014474960897) for a [tweet I made a few weeks ago](https://twitter.com/triangulo_dev/status/1478366865428819970).

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-alert-dialog, @radix-ui/react-dialog, @radix-ui/react-dropdown-menu        |  0.1.5, 0.1.5, and 0.1.4       |
| React            | n/a     |  17.0.2       |
| Browser          |  Chrome       |  97.0.4692.71       |
| Browser          |  Firefox Developer Edition       |  96.0b10       |
| Browser          |  Firefox Developer Edition       |  97.0b4      |
| Browser          |  Safari       |  15.1 (17612.2.9.1.20)      |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  macOS       |  12.0.1 (21A559)       |

**Comment by heyitsarpit** [comment]
Hitting this same issue after I built a form inside the dialog that's triggered by `<Dropdown.Item>`, In my case the entire tab would hang when I clicked on an input, I mitigated that by using `<DropDown.Root modal={false}>` but I still can't use the tab button to focus on elements.

**Comment by jjenzz** [comment]
This fix is available in `0.1.5-rc.6`
