### ISSUE TITLE
[DropdownMenu] Toggle trigger from content breaks dropdown position

### ISSUE THREAD

**Issue by ZorGleH** [radix-ui/primitives#1102]
## Bug report

Thanks for your work! Radix primitives is awesome and I'm going to use it in a lot of my components. However, there is a usecase where it doesn't work as I expected.

### Current Behavior

When hiding the trigger from inside the dropdown content, the menu stays visible but moves to a wrong position.

https://user-images.githubusercontent.com/301781/150309766-997f69b3-98c9-47e7-8fe6-8bd81ec3d19e.mov

### Expected behavior

The dropdown menu should hide when the trigger disappears.

### Reproducible example

[Radix DropdownMenu wrong position](https://codesandbox.io/s/radix-dropdownmenu-wrong-position-1q1vy)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dropdown-menu | latest |
| React            | n/a     | latest        |
| Browser          | Google Chrome | Version 97.0.4692.71 (Build officiel) (x86_64) |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | macOS Monterey       | 12.1        |

**Comment by benoitgrelard** [comment]
Hi @ZorGleH,

I'm not sure what the intention is behind this, but to me this is not a bug but rather appears to be a use-case issue.

> The dropdown menu should hide when the trigger disappears.

There is no reason for the trigger to disappear by itself. If what you're after is to say that the `DropdownMenu` alltogether is gone, then you should do just that, unmount the whole component, rather than just the trigger and you'll see that then the menu will also unmount.

```diff
+{triggerVisible && (
<DropdownMenuPrimitive.Root>
-  {triggerVisible && (
    <DropdownMenuPrimitive.Trigger asChild>
      <button>Toggle dropdown</button>
    </DropdownMenuPrimitive.Trigger>
-  )}

  <StyledContent sideOffset={5}>
    <button
      onClick={() => {
        setTriggerVisible(!triggerVisible);
      }}
    >
      Toggle trigger
    </button>
  </StyledContent>
</DropdownMenuPrimitive.Root>
+)}
```

What is happening here is because you are unmounting JUST the trigger, so the `DropdownMenu` instance still exists but now doesn't have a trigger (which doesn't make sense from the pattern/accessibility point of view anyway), so it doesn't know how to position the `Content` anymore, hence why it now appears on the top/left corner.

It would be great to understand what your use case is to want to unmount like you do here, or whether it's just a contrived example, because it seems strange at a glance to want to do that.

I hope that helps!

**Comment by ZorGleH** [comment]
Thanks for your help!

I solved a part of my use-case by using Popover and DropdownMenu together (see https://codesandbox.io/s/crazy-saha-gr44q). Now when you click on "Trigger" then "Toggle dropdown" then "Some action", the dropdown doesn't close, which is what I wanted.

Is there a way that when the trigger is clicked and the dropdown is closed, it opens the dropdown, but when then trigger is clicked again, the dropdown stays open, and closes only when clicked outside?

**Comment by benoitgrelard** [comment]
> I solved a part of my use-case by using Popover and DropdownMenu together (see https://codesandbox.io/s/crazy-saha-gr44q). Now when you click on "Trigger" then "Toggle dropdown" then "Some action", the dropdown doesn't close, which is what I wanted.

You can't just put a random button inside `Dropdown.Content` though, that won't be accessible. It has to be an item.

> Is there a way that when the trigger is clicked and the dropdown is closed, it opens the dropdown, but when then trigger is clicked again, the dropdown stays open, and closes only when clicked outside?

Between this and the comment above, I feel like I'm just not understanding what you're trying to achieve.
Would you mind detailing what you are actually trying to achieve? Then we should be able to help properly.

**Comment by ZorGleH** [comment]
Here is what I'm trying to achieve. It currently works with Reakit (see screenshot below), but I'd like to totally replace it with Radix.
Once you click on the title row, which is the trigger for the toolbar, the toolbar shows. When you click on another part of the row, the toolbar stays visible, which I don't know how to achieve with Radix, because clicking on the row toggles the toolbar.

https://user-images.githubusercontent.com/301781/150957865-17fb4ea2-fa6b-428e-938c-492259bc3b1c.mov

**Comment by benoitgrelard** [comment]
Thanks for the video, a lot easier to understand 🙂

Ok, so this seems quite complex in terms of accessibility, especially given the fact that the toolbar shows when focusing in the row, not sure what pattern that would be alltogether.

If we assume that the white background bar is inside a popover, then what you're trying to achieve is possible by using the `onInteractOutside` handler and preventing the default behaviour if the event happened in the "row".

Something like:

```tsx
onInteractOutside={event => {
  if (rowRef.current.contains(event.target)) {
    event.preventDefault();
  }
}}
```

This will prevent the popover from closing if the outside interaction happened in the row.

However, holistically, I think your interactions go beyond some of our primitives, and you will probably have to test overall accessibility yourself as it's a very complex pattern.

Another issue I see here the fact that you're trying to use `DropdownMenu` as a `Select` (that text selection I see in the video). This should be a `Select` as it's retaining the selected value. `DropdownMenu` and `Select` are completely different patterns in terms of accessibility.

I hope that was helpful to you.

**Comment by ZorGleH** [comment]
Thanks for the clue. I managed to do what I wanted and it works perfectly!

For the Select thing, I hope this primitive will be implemented soon.

**Comment by benoitgrelard** [comment]
> Thanks for the clue. I managed to do what I wanted and it works perfectly!

Great!

> For the Select thing, I hope this primitive will be implemented soon.

Yes, it will come out soon, working on finishing it off as we speak.
