### ISSUE TITLE
[DropdownMenu] won't close when using `Link` in Next.js

### ISSUE THREAD

**Issue by d3v4nt** [radix-ui/primitives#1105]
## Bug report
Dropdown is not closing itself when clicking an item within when using it inside of NextJs `_app.js`.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-drop-forked-52r24)

**Comment by hugobdev** [comment]
@d3v4nt I had a similar issue with `react-location`'s `Link` component. It looks like it will close correctly if you pass the `ref` properly to the component.

This is an issue with Next's Link component not properly passing the `ref` down to the rendered element.

I don't think this is Radix's business, although a mention in the docs would be appreciated as many people are using Next.

Resources to fix `ref` passing:
- https://stackoverflow.com/questions/65854159/correct-way-to-use-ref-with-next-js-for-a-link-and-an-a
- https://blog.logrocket.com/dealing-with-links-in-next-js/#:~:text=Here%20is%20how%20a%20wrapped%20version%20of%20Link%20is%20going%20to%20work%3A

**Comment by rayjasson98** [comment]
Here's an example of passing an `<a>` element wrapped by `forwardRef` to the Next's `<Link>` component:
```ts
  const AnchorWithRef = forwardRef<HTMLAnchorElement, { name: string }>(
    function AnchorWithRef({ name }, forwardedRef) {
      return <a ref={forwardedRef}>{name}</a>;
    }
  );

  return (
    <DropdownMenu.Item>
      <Link href={href} passHref>
        <AnchorWithRef name={name} />
      </Link>
    </DropdownMenu.Item>
  );
```

**Comment by gabrielmlinassi** [comment]
Another possible solution:

```jsx
 const router = useRouter();
  const [isOpen, setOpen] = useState(false);

  useEffect(() => {
    const closeMenu = () => setOpen(false);
    router.events.on("routeChangeStart", closeMenu);
    return () => router.events.off("routeChangeStart", closeMenu);
  }, [router.events]);

  return (
   <DropdownMenu.Root open={isOpen} onOpenChange={setOpen}>
      <DropdownMenu.Content>
          <DropdownMenu.Item>
            <NextLink href={item.href}>
              <a>{item.label}</a>
            </NextLink>
          </DropdownMenu.Item>
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
```

**Comment by Garwend** [comment]
You could also use it **asChild**. In this example I'm using [shadcn ui](https://ui.shadcn.com/) which is built with Radix UI so this solution should work.

```javascript
import Link from "next/link";
import { User } from "lucide-react";

import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";

export default function Menu() {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Avatar className="h-8 w-8 cursor-pointer">
          <AvatarImage src="" />
          <AvatarFallback>CN</AvatarFallback>
        </Avatar>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem asChild>
          <Link href="/profile">
            <User className="mr-2 h-4 w-4" /> Profile
          </Link>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

```

**Comment by CanRau** [comment]
This is fantastic, thanks a lot for reminding me of `asChild` @Garwend 👏🏼 🙏🏼

**Comment by Nemidas7734** [comment]
**asChild** worked for me. Thanks a lot 🙏🏼

**Comment by thomasflensted** [comment]
asChild did it for me too! By the easiest, cleanest and simplest solution here.

**Comment by benoitgrelard** [comment]
> asChild did it for me too! By far the easiest, cleanest and simplest solution here.

`asChild` is the intended way to achieve this.

**Comment by evgeniy9286** [comment]
'use client'

import React from 'react';
import Link from 'next/link';
import { links } from "@/constants/appdata";
import { usePathname} from 'next/navigation';
import { useState, useEffect } from 'react';

const Header = () => {
  const pathname = usePathname();
  
  const [isMenu, setIsMenu] = useState(false);
  const closeMenu = () => {
    setIsMenu(!setIsMenu);
  };

    useEffect(() => {
       if (document) {
        document.body.style.overflow = isMenu ? 'hidden' : 'auto';
      }
    }, [isMenu]);
  
  
  return (
    <div className='fixed top-0 right-0 left-0 bg-white shadow-lg h-16 flex justify-between items-center md:px-8 z-50'>     
        <Link className='px-6 md:px-0' href='/'>
          <h1 className='text-third-color font-bold text-2xl'>Car Rental</h1>
      </Link>
      <div className='md:hidden flex flex-col gap-1 cursor-pointer mr-6'
      onClick={()=>setIsMenu(!isMenu)}>
        <div className='w-5 h-0.5 bg-black'></div>
        <div className='w-5 h-0.5 bg-black'></div>
        <div className='w-5 h-0.5 bg-black'></div>
      </div> 
      <div className={` ${isMenu ? "h-[41vh] shadow-lg flex flex-col items-center gap-5 absolute top-16 w-full md:shadow-none" : "hidden md:block md:items-center md:shadow-none"} gap-5 md:h-16 md:flex md:flex-row md:static bg-white md:w-auto md:py-0 px-6 md:px-0 text-center z-50`}>
          {links?.map((link) => (
            <div key={link.link}>
             <Link className={`${pathname === link.link ? "text-third-color" : "text-gray-400"}`} href={link.link} exact={link.exact} onClick={closeMenu}>
                <span>{link.text}</span>
              </Link>
            </div>
          ))}
      </div>
    </div>   
  )
};

export default Header;

**Comment by evgeniy9286** [comment]
'use client'

import React from 'react';
import Link from 'next/link';
import { links } from "@/constants/appdata";
import { usePathname} from 'next/navigation';
import { useState, useEffect } from 'react';

const Header = () => {
  const pathname = usePathname();  
  const [isMenu, setIsMenu] = useState(false);
  const closeMenu = () => {
    setIsMenu(!setIsMenu);
  };
    useEffect(() => {
       if (document) {
        document.body.style.overflow = isMenu ? 'hidden' : 'auto';
      }
    }, [isMenu]);
  return (
    <div className='fixed top-0 right-0 left-0 bg-white shadow-lg h-16 flex justify-between items-center md:px-8 z-50'>     
        <Link className='px-6 md:px-0' href='/'>
          <h1 className='text-third-color font-bold text-2xl'>Text</h1>
      </Link>
      <div className='md:hidden flex flex-col gap-1 cursor-pointer mr-6'
      onClick={()=>setIsMenu(!isMenu)}>
        <div className='w-5 h-0.5 bg-black'></div>
        <div className='w-5 h-0.5 bg-black'></div>
        <div className='w-5 h-0.5 bg-black'></div>
      </div> 
      <div className={` ${isMenu ? "h-[41vh] shadow-lg flex flex-col items-center gap-5 absolute top-16 w-full md:shadow-none" : "hidden md:block md:items-center md:shadow-none"} gap-5 md:h-16 md:flex md:flex-row md:static bg-white md:w-auto md:py-0 px-6 md:px-0 text-center z-50`}>
          {links?.map((link) => (
            <div key={link.link}>
             <Link className={`${pathname === link.link ? "text-third-color" : "text-gray-400"}`} href={link.link} exact={link.exact} onClick={closeMenu}>
                <span>{link.text}</span>
              </Link>
            </div>
          ))}
      </div>
    </div>   
  )
};
export default Header;

**Comment by evgeniy9286** [comment]
'use client'

import React from 'react';
import Link from 'next/link';
import { links } from "@/constants/appdata";
import { usePathname} from 'next/navigation';
import { useState, useEffect } from 'react';

const Header = () => {
  const pathname = usePathname();  
  const [isMenu, setIsMenu] = useState(false);
  const closeMenu = () => {
    setIsMenu(!setIsMenu);
  };
    useEffect(() => {
       if (document) {
        document.body.style.overflow = isMenu ? 'hidden' : 'auto';
      }
    }, [isMenu]);
  return (
    <div className='fixed top-0 right-0 left-0 bg-white shadow-lg h-16 flex justify-between items-center md:px-8 z-50'>     
        <Link className='px-6 md:px-0' href='/'>
          <h1 className='text-third-color font-bold text-2xl'>Text</h1>
      </Link>
      <div className='md:hidden flex flex-col gap-1 cursor-pointer mr-6'
      onClick={()=>setIsMenu(!isMenu)}>
        <div className='w-5 h-0.5 bg-black'></div>
        <div className='w-5 h-0.5 bg-black'></div>
        <div className='w-5 h-0.5 bg-black'></div>
      </div> 
      <div className={` ${isMenu ? "h-[41vh] shadow-lg flex flex-col items-center gap-5 absolute top-16 w-full md:shadow-none" : "hidden md:block md:items-center md:shadow-none"} gap-5 md:h-16 md:flex md:flex-row md:static bg-white md:w-auto md:py-0 px-6 md:px-0 text-center z-50`}>
          {links?.map((link) => (
            <div key={link.link}>
             <Link className={`${pathname === link.link ? "text-third-color" : "text-gray-400"}`} href={link.link} exact={link.exact} onClick={closeMenu}>
                <span>{link.text}</span>
              </Link>
            </div>
          ))}
      </div>
    </div>   
  )
};
export default Header;

**Comment by syed-afzal60** [comment]
`isChild` is not working when you have a `div` inside `DropdownMenuItem`

**Comment by staciax** [comment]
> ```js
> I
> ```

asChild it's work thanks 👍

**Comment by staciax** [comment]
`isChild` it's work thanks 👍
