### ISSUE TITLE
[Tooltip] Not triggering on hover

### ISSUE THREAD

**Issue by badsyntax** [radix-ui/primitives#1121]
### Current Behavior

The tooltip is not triggered when hovering over the trigger. 

### Expected behavior

The tooltip should show on hover.

### Reproducible example

https://www.radix-ui.com/docs/primitives/components/tooltip

### Your environment

I'm not sure of the current version deployed to https://www.radix-ui.com/docs/primitives/components/tooltip

I have not tried the latest versions locally, I've only noticed this issue on the docs site.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hey Richard, not sure if I'm missing something here or if it's a specific browser, but it does show on hover for me.
There's a delay, maybe you're not waiting long enough?
If not, do you have more details?

**Comment by badsyntax** [comment]
There's a delay. Closing.

**Comment by badsyntax** [comment]
@benoitgrelard Apologies, didn't see your reply before i posted. Yes it's just the delay, no problems!
