### ISSUE TITLE
On mount, Menu adds 3 event listeners which can be expensive

### ISSUE THREAD

**Issue by dwilt** [radix-ui/primitives#1139]
## Question

@benoitgrelard I know we've talked about menus before haha. Anyway, we are doing more stress testing with our application in 6x slowdown and we noticed that there are numerous `pointermove` events firing in the dev tools:

![image](https://user-images.githubusercontent.com/1065539/152654932-3b6982d0-a333-4e90-97d4-0447ccd3d3b1.png)

I've tracked it down to when the [`Menu` component mounts](https://github.com/radix-ui/primitives/blob/58486382a2afa83e9727d49f2fae857335be6d0f/packages/react/menu/src/Menu.tsx#L106), it adds **3** event listeners to the document _for each instance of a menu_:

![2022-02-05 13 52 23](https://user-images.githubusercontent.com/1065539/152654966-dbf221a6-adfa-4564-844d-5663a74884ad.gif)

I can see that the callbacks for these are just so that you can assign a value to `isUsingKeyboardRef` which is being used in a few places to apply focus if the user is currently using their keyboard.. This seems like a pretty hefty perf trade-off just to handle some focus states for a keyboard user. Any thoughts? In our application, we have lots of interactions where users are dragging items and if there are a lot of these menus on the page, with 6x slowdown, they can really clog up the main thread and result in a janky experience for the user dragging.

Just _one_ of these `pointermove` events on 6x slowdown is almost **10ms**:
![image](https://user-images.githubusercontent.com/1065539/152655259-9e7f9a75-209b-49de-9707-44af9a07fc46.png)

Have you ever heard of the [idle-until-urgent pattern](https://philipwalton.com/articles/idle-until-urgent/) before? It's a pattern used by Google for handling expensive performance operations and might be something you could utilize in this case?

**Comment by benoitgrelard** [comment]
Hi there, it's extremely unlikely that the source of your performance issues would be to do with a couple event listeners really. Especially given that these specific ones you point out, do not even update state, so do not cause re-renders (they are only updating a ref).

**Comment by Crockery** [comment]
Is there any compelling reason for this ref to be managed on a per-menu basis, and not as a global value accessible to menus? The cost of an individual handler is minimal, I agree, but it the extent to which it's a performance issue increases with the number of menus on the page and the speed of the computer rendering them.

**Comment by AlabasterAxe** [comment]
Just to add my two cents here, these handlers are causing significant overhead for us when handling keydown and pointerdown events. I looked and our app has almost 700 keydown listeners. All but 13 of those listeners are from Radix Menu. I'm looking into if there are simple ways we can reduce the number of menus but I agree with @Crockery that it seems like this can be something that can be provided once for all components that need this information.

I've attached a profile so you can see for yourself that this is having a material negative impact on the handling of these events.

Let me know if you would like me to open another issue.
