### ISSUE TITLE
How about let `sideOffset` in `DropDown` using string?

### ISSUE THREAD

**Issue by PeterlitsZo** [radix-ui/primitives#1144]
### Overview

When we using `<DropdownMenu.Content sideOffset={12}>`, the `sideOffset` can only be a number. But we want to using `rem` but not only using `px`.

After reading source... I cannot find where to parse `sideOffset`, I have no idea how to change it...

**Comment by benoitgrelard** [comment]
Hi @PeterlitsZo,

It's all in the `popper` implementation and all the calculations are pixel based so trying to use `rem` would never work.
This is why the type is number, because they have to be pixel values.

I will close the issue but feel free to keep discussing.

**Comment by jjenzz** [comment]
You can create a utility to calculate the correct pixel value for this prop based on your projects root font-size.

```jsx
const rem = (rootSize) => {
  return (rem) => rem * rootSize;
}

export default rem(16);
```

```jsx
import rem from './rem'

export default () => {
  <DropdownMenu.Root>
    <DropdownMenu.Trigger>Open</DropdownMenu.Trigger> 
    <DropdownMenu.Content sideOffset={rem(2)}>
      <DropdownMenu.Item>Item</DropdownMenu.Item>
      <DropdownMenu.Item>Item</DropdownMenu.Item>
    </DropdownMenu.Content>  
  <DropdownMenu.Root>
}
```

**Comment by PeterlitsZo** [comment]
Thanks.
