### ISSUE TITLE
[Presence] onAnimationEnd doesn't fire for consumers

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#1150]
https://codesandbox.io/s/recursing-mountain-oj7hh?file=/src/App.tsx

### Discussed in https://github.com/radix-ui/primitives/discussions/1149

<div type='discussions-op-text'>

<sup>Originally posted by **emadabdulrahim** February 11, 2022</sup>
How can I wait for Popover animation to end without having to use setTimeout etc?</div>

**Comment by benoitgrelard** [comment]
Duplicate of #1020
