### ISSUE TITLE
Dialog.Close used in documentation. Should be Dialog.Cancel

### ISSUE THREAD

**Issue by DanielBailey-web** [radix-ui/primitives#1152]
### Relevant Radix Component(s)

Dialog

The anatomy: https://www.radix-ui.com/docs/primitives/components/dialog#anatomy
``` 
import * as Dialog from '@radix-ui/react-dialog';

export default () => (
  <Dialog.Root>
    <Dialog.Trigger />
    <Dialog.Portal>
      <Dialog.Overlay />
      <Dialog.Content>
        <Dialog.Title />
        <Dialog.Description />
        <Dialog.Close />
      </Dialog.Content>
    </Dialog.Portal>
  </Dialog.Root>
);
```
`Dialog.Close` does not exist in 0.1.5 instead it should be `Dialog.Cancel`

The code sandbox also appears to say this. Is this a feature from an older version or something?

**Comment by benoitgrelard** [comment]
I think you are confusing `Dialog` and `AlertDialog`.
`Dialog` has `Dialog.Close`, `AlertDialog` has `AlertDialog.Cancel` and `AlertDialog.Action`.

**Comment by DanielBailey-web** [comment]
@benoitgrelard Ahhh, you made me realize that vscode auto imported the wrong dialog haha. Thanks
