### ISSUE TITLE
[Tooltip] Dynamically styling Remix's `<NavLink>` is broken

### ISSUE THREAD

**Issue by hollandThomas** [radix-ui/primitives#1158]
#### Bugged version

Given the following code, featuring Remix's [\<NavLink\>](https://remix.run/docs/en/v1/api/remix#navlink)

```tsx
import { NavLink } from 'remix';
import * as Tooltip from '@radix-ui/react-tooltip';

type ListItemProps = { to: string; src: string; tooltip: string };
const ListItem: React.FC<ListItemProps> = ({ to, src, tooltip }) => (
  <li>
    <Tooltip.Root>
      <Tooltip.Trigger asChild>
        <NavLink
          to={to}
          className={({ isActive }) =>
            'block rounded-md p-4 transition-colors hover:bg-gray-100 ' +
            (isActive && 'bg-gray-100')
          }
        >
          <img src={src} className="h-6 w-6 text-gray-100" />
        </NavLink>
      </Tooltip.Trigger>
      <Tooltip.Content
        side="right"
        className="rounded-md bg-white px-4 py-2 shadow-lg"
      >
        <Tooltip.Arrow className=" fill-white" />
        {tooltip}
      </Tooltip.Content>
    </Tooltip.Root>
  </li>
);
```

it renders this HTML, e.g. it does not evaluate the expression given for `className` and instead renders it verbatim:

```html
<li>
  <a
    data-state="closed"
    aria-current="page"
    class="({ isActive }) => "block rounded-md p-4 transition-colors hover:bg-gray-100 " + (isActive && "bg-gray-100") active" href="/some/path"
>
  <img src="/path/to/icon.svg" class="h-6 w-6 text-gray-100">
</a>
```

#### Bug-free version

This code works as expected:

```typescript
type ListItemProps = { to: string; src: string; tooltip: string };
const ListItem: React.FC<ListItemProps> = ({ to, src, tooltip }) => (
  <li>
    <NavLink
      to={to}
      className={({ isActive }) =>
        'block rounded-md p-4 transition-colors hover:bg-gray-100 ' +
        (isActive && 'bg-gray-100')
      }
    >
      <img src={src} className="h-6 w-6 text-gray-100" />
    </NavLink>
  </li>
);
```

### Expected behavior

The given `className` expression is evaluated correctly.

### Reproducible example

[CodeSandbo](https://codesandbox.io/s/loving-frost-2pr7g?file=/app/routes/index.jsx)

### Suggested solution

Not sure. I'm not even sure if this is a Radix or a Remix bug. That's why I [cross-posted an issue over there](https://github.com/remix-run/remix/issues/1966). Feel free to close this if this is not related to Radix.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `@radix-ui/react-tooltip`    |      `0.1.6`   |
| Remix            |      |      `1.1.3`, express server template   |
| Browser          |   Chrome, Firefox, Safari (any browser, really)       |        |
| Assistive tech   |     n/a    |         |
| Node             |      |  `16.13.2`       |
| npm/yarn         |    npm     |  `8.1.2`       |
| Operating System |   macOS      | `11.6.1`        |

**Comment by benoitgrelard** [comment]
I believe this is a Radix issue rather than a Remix one.
Looking at it briefly, my money would be on the way our `Slot` component  composes `className`.

```tsx
} else if (propName === 'className') {
  overrideProps[propName] = [slotPropValue, childPropValue].filter(Boolean).join(' ');
}
```

However, I don't know if it would make sense for us to consider that `className` could ever be a function it's non-standard and it looks like Remix here is abusing the standard `className` API a bit thus making it incompatible.

I'm not that familiar with Remix, but from what I can see Remix's `NavLink` is basically React router's `NavLink` which in turn is React router `Link`. I wonder if they support something like an `as` prop so you could flip the composition around and instead of doing:

```tsx
<Tooltip.Trigger asChild>
  <NavLink
    to={to}
    // className="block rounded-md p-4 transition-colors hover:bg-gray-100"
    className={({ isActive }) =>
      "block rounded-md p-4 transition-colors hover:bg-gray-100 " +
      (isActive && "bg-gray-100")
    }
  >
    {tooltip}
  </NavLink>
</Tooltip.Trigger>
```

you'd do something like:

```
<NavLink
  as={Tooltip.Trigger}
  to={to}
  // className="block rounded-md p-4 transition-colors hover:bg-gray-100"
  className={({ isActive }) =>
    "block rounded-md p-4 transition-colors hover:bg-gray-100 " +
    (isActive && "bg-gray-100")
  }
>
  {tooltip}
</NavLink>
```

**Comment by hollandThomas** [comment]
Thanks for the quick response!

> However, I don't know if it would make sense for us to consider that className could ever be a function it's non-standard and it looks like Remix here is abusing the standard className API a bit thus making it incompatible.

In principal, I would agree that supporting non-standard behavior is tedious. The [React typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts#L1818) indeed seem to confirm that it's supposed to be a `string | undefined`.

Seen from a practical standpoint however, React Router is a vital library in the React ecosystem — it's probably the most installed third party library for React. Reverting its decision to support functions for `className` would be a breaking change for the entire ecosystem. They [only just introduced that change](https://reactrouter.com/docs/en/v6/api#navlink) with v6.
Further, Remix pairs incredibly well with Radix IMO. The fact that Radix renders hidden standard inputs next to its custom implementation is a godsend in combination with Remix's `<Form>` API. Not least because of that, I suppose that wrapping a Remix-`<NavLink>` with a Radix-`<Tooltip>` is a common scenario. As far as I can tell, supporting this would _not_ be a breaking change for Radix and would instead be beneficial for the ecosystem at large.

---

I just skimmed over [NavLink's source](https://github.com/remix-run/remix/blob/main/packages/remix-react/components.tsx#L435). It does not seem to support an `as` prop. But even if, wouldn't that make the `<NavLink>` render as `<button>`? That'd be semantically wrong for navigation links, unfortunately.

**Comment by hollandThomas** [comment]
Hey @benoitgrelard, thanks for taking your time and acting so quickly. Really appreciate that ❤️

> At this stage I think I am keen to stay away from modifying our lib to suit non-standard DOM attributes.

I respect that decision. The idea of wrapping `NavLink` didn't occur to me. Since that meets the requirements, I'm fine with closing this.

Thanks again!

**Comment by a-eid** [comment]
wrap your navlink is a react fragment 


```tsx
   <Tooltip.Trigger asChild>
    <>
      <NavLink
        to={to}
        className={({ isActive }) =>
          "block rounded-md p-4 transition-colors hover:bg-gray-100 " + (isActive && "bg-gray-100")
        }
      >
        <img src={src} className="h-6 w-6 text-gray-100" />
      </NavLink>
    </>
  </Tooltip.Trigger>;
```
