### ISSUE TITLE
[DropdownMenu] Trigger re-opens menu when mouse click is released when modal={false}

### ISSUE THREAD

**Issue by ericmatthys** [radix-ui/primitives#1160]
### Current Behavior

1. Open the menu by clicking the trigger
2. Click the trigger again to close it, delaying the mouse down and the mouse up
3. The menu will close on the mouse down and re-open on the mouse up

### Expected behavior

1. Second click closes the menu and it stays closed

### Reproducible example

https://codesandbox.io/s/condescending-orla-frb7r4

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dropdown-menu     |    0.1.4     |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |     99    |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |         |
| npm/yarn         |   n/a      |         |
| Operating System |    macOS     |    12.1     |

**Comment by jjenzz** [comment]
This was fixed previously and is available in one of the latest release candidates. You can see it working in the latest release candidate here: https://codesandbox.io/s/heuristic-sid-zn4c72?file=/App.js

We will hopefully be releasing 0.1.5 in the coming weeks if you'd prefer to wait for that though.
