### ISSUE TITLE
Redundant div if pass the asChild={false} parameter explicitly to DropdownMenuTriggerItem

### ISSUE THREAD

**Issue by KelvinOm** [radix-ui/primitives#1168]
### Current Behavior
If pass the `asChild={false}` parameter explicitly to `DropdownMenuTriggerItem` then there is a redundant `div` which breaks the layout.

### Expected behavior
Redundant div does not appear

### Reproducible example
Line 184
[CodeSandbox Template](https://codesandbox.io/s/heuristic-ganguly-oz8f6k?file=/App.js:5324-5331)

**Comment by jjenzz** [comment]
I don't see an `asChild={false}` in your codesandbox. Did you forget to save?

Regardless, `asChild={false}` will render the `DropdownMenuTriggerItem` element (a `div`) which is correct because by passing `false` to `asChild` you are asking it to render its own element instead of yours.

**Comment by jjenzz** [comment]
Ooooh I have updated the sandbox myself and can see the issue you describe. That is **weird**. Thanks for the report. We'll look into it 👍

**Comment by KelvinOm** [comment]
> Did you forget to save?

It looks like that. Sorry. Updated the description and saved.

**Comment by jjenzz** [comment]
Ah, this was inadvertently fixed by `0.1.5-rc.15` [here](https://github.com/radix-ui/primitives/pull/1157).

Upgrading to latest release candidate should solve it for you but we will also be doing a proper release in the coming weeks if you'd prefer to wait.

**Comment by KelvinOm** [comment]
Thanks. I will be waiting for the release.
