### ISSUE TITLE
[DropdownMenuItem] Weird behaviour when added text field to filter dropdown items

### ISSUE THREAD

**Issue by mszymczakowski** [radix-ui/primitives#1175]
### Current Behavior

https://user-images.githubusercontent.com/2932563/155231382-6e6cfbc8-1d8a-4e47-92bb-60fc07925302.mov

### Expected behavior

Search field should not blur when filtering dropdown with `DropdownMenuItem` components.

### Reproducible example

[GitHub repository](https://github.com/mszymczakowski/radix-ui-dropdown-issue)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-dropdown-menu | 0.1.4 |
| React            | n/a     | 17.0.2 |
| Browser          | Chrome | 98.0.4758.80  |
| Assistive tech   | from package.json | <pre>"dependencies": {<br>  "@heroicons/react": "^1.0.5",<br>  "@radix-ui/react-dropdown-menu": "^0.1.4",<br>  "next": "12.1.0",<br>  "react": "17.0.2",<br>  "react-dom": "17.0.2"<br>},<br>"devDependencies": {<br>  "@types/node": "17.0.19",<br>  "@types/react": "17.0.39",<br>  "autoprefixer": "^10.4.2",<br>  "eslint": "8.9.0",<br>  "eslint-config-next": "12.1.0",<br>  "postcss": "^8.4.6",<br>  "tailwindcss": "^3.0.23",<br>  "typescript": "4.5.5"<br>}</pre> |
| Node             | n/a     | v14.17.0 |
| npm/yarn         | yarn | 1.22.10 |
| Operating System | macOS | 12.0.1 |

**Comment by mszymczakowski** [comment]
@benoitgrelard is there any way to override keyboard accessibility events? So I could stop execution if the search field is focused 🤔

**Comment by benoitgrelard** [comment]
You can try using `event.preventDefault` in places to override some of our business logic. But obviously you then become tied to our implementation and need to make sure everything remains accessible.
