### ISSUE TITLE
Tooltip and HoverCard will-change property

### ISSUE THREAD

**Issue by phoenixVS** [radix-ui/primitives#1181]
How to remove will-change: transform css prop from data-radix-popper-content-wrapper?
It wraps my HoverCardPrimitive.Content or TooltipPrimitive.Content and i cannot get access to it :'(

I need to apply backdrop-blur and it is not working because of this prop

```
<HoverCardPrimitive.Root {...rest}>
      <HoverCardPrimitive.Trigger asChild={asChild} className={className}>
        {children}
      </HoverCardPrimitive.Trigger>
      <HoverCardPrimitive.Content
        portalled
        side="right"
        sideOffset={5}
        align="start"
        alignOffset={-10}
        className={classNames(
          "rounded-[.625rem]",
          "w-[18rem] bg-brand-darklight/30 backdrop-blur-md",
          "py-5 px-5",
          "text-white"
        )}
        style={{
          willChange: "auto",
        }}
      >
        {content}
        <HoverCardPrimitive.Arrow
          offset={13}
          width={15}
          height={8}
          className="fill-brand-darklight/30"
        />
      </HoverCardPrimitive.Content>
    </HoverCardPrimitive.Root>
```

I really appreciate if you help (:

**Comment by benoitgrelard** [comment]
Hey @phoenixVS,

If you don't need it to be portalled, here's a workaround you could use to target that element:

- set `portalled` to `false` on `HoverCardPrimitive.Content`
- wrap the entire `HoverCard` tree in a span with a class (say it's called `.hack`)
- then add these styles to target the element you want:
```css
.hack [data-radix-popper-content-wrapper] {
  will-change: auto;
}
```

In the future, we will offer a bit more control over the portal (like we've done recently with `Dialog`), so you should be able to override styles a bit more easily.

Hope that helps 👍

**Comment by jjenzz** [comment]
I'm thinking we should remove this from the primitive as `will-change` should be a last resort added by product when a performance issue is realised.

> **Warning**: `will-change` is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.
> https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

Thoughts? I can whack a PR up if we agree.

**Comment by benoitgrelard** [comment]
We can definitely look into removing it but let's keep it out of the current release because I don't think it's wise do send this out quickly, we need to test if it doesn't have any impact as this code is quite old and I can't remember if there was a reason I added it or not 😀

**Comment by jjenzz** [comment]
Oh for sure didn't mean include it in this release. I just think it's a worthwhile change for whenever.

**Comment by Jonnotie** [comment]
Yes, please remove it or allow us to change it. I have a backdrop filter on my tooltip and it gets removed because of the `will-change` property.

**Comment by phoenixVS** [comment]
Probably should be some hint in docs about it

Thanks for help! :)

**Comment by outdoteth** [comment]
any update on this?
