### ISSUE TITLE
Primitives wrapped in `styled-components` leak props to DOM

### ISSUE THREAD

**Issue by acc-nicholas** [radix-ui/primitives#1201]
### Current Behavior
Component props are being leaked to the DOM.
![image](https://user-images.githubusercontent.com/50001189/155822658-14049bd2-2cc9-4318-aa9a-81a10bd3e14e.png)

### Expected behavior
Props should not leak to the DOM.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/admiring-wilbur-0eprq9?file=/src/App.tsx)

### Additional context
`styled-components` has a whitelist of HTML attributes that it allows to pass through from the component to the actual DOM. But this isn't working it seems when i wrap a radix primitive.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/label-react, @radix-ui/tooltip (maybe all primitives)    | latest        |
| React            | n/a     |         |
| Browser          |   chrome      |     latest    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi @acc-nicholas,

I don't think this has anything to do with Radix.
It seems here you are telling TS that `StyledLabel` can take a `foo` prop when in reality it can't because `Label` doesn't accept a `foo` prop.

So in reality if you expanded what `styled-components` does when wrapping a component, you would have to pull out that prop to avoid it ending up in the DOM.

Here's what I mean: https://codesandbox.io/s/mystifying-water-xp8i28

**Comment by penx** [comment]
There are a couple of options for managing what styled-components passes to the DOM:

[transient props](https://styled-components.com/docs/api#transient-props)
[shouldForwardProp](https://styled-components.com/docs/api#shouldforwardprop)

I think there's another option but it escapes me... @jjenzz do you remember :D ?

**Comment by acc-nicholas** [comment]
Hey @benoitgrelard and @penx thanks for the responses!

I updated the example with a more exact match to what i'm actually trying to do: https://codesandbox.io/s/admiring-wilbur-0eprq9?file=/src/App.tsx. I'm trying to extend the `Label` interface with a new prop. But that prop is leaking to the DOM. Its not clear to me how to prevent that. 

I really dont know if it has to do with Radix or with Styled-components, but in the updated example the styled html label works as expected (no leak) even though it has `foo` prop.

`transient` props are for props that name matches html attributes, like `id` or `width`. So you use `$width` instead so that your prop doesn't leak to the DOM.

`shouldForwardProp` i dont think is applicable here either.

Open to any ideas/suggestions.

**Comment by benoitgrelard** [comment]
Since presumably you want that prop to do something specific, you need to pull it out to avoid it being spread onto the DOM, given that `Label` from radix won't understand that prop, there's no magic there really, so:

```tsx
const StyledRadixLabel = styled(RadixLabel)<LabelProps>``;
const Label = ({ foo = "bar", ...props }: LabelProps) => {
  // do something with `foo`
  return (
    <StyledRadixLabel {...props} />
  );
}
```

**Comment by acc-nicholas** [comment]
I actually need `foo` in the styled block:
const StyledRadixLabel = styled(RadixLabel)<LabelProps>`
  // do something with foo
`;

**Comment by benoitgrelard** [comment]
Then I think the suggestion above to use transient props (prefixed with `$`) or `shouldForwardProp` are the correct answer.

**Comment by acc-nicholas** [comment]
That does seem to fix the problem and after re-reading transient props is its intended use:

> If you want to prevent props meant to be consumed by styled components from being passed to the underlying React node or rendered to the DOM element, you can prefix the prop name with a dollar sign ($), turning it into a transient prop.

So basically, if you pass `Label` or any Radix primitive unexpected props, they will render those props to the DOM. You can work around this in my case by using styled-components' transient props.

Thanks for the help @benoitgrelard !

**Comment by acc-nicholas** [comment]
Yeah, styled-components has the same problem. IIRC they have a big whitelist for html attributes that they pass through, which seems like a nightmare to implement and maintain. I wouldn't expect Radix to do the same.
