### ISSUE TITLE
Using collapsible package independently causes type error

### ISSUE THREAD

**Issue by bisfun-hatfes** [radix-ui/primitives#1206]
## Bug report

Installing `@radix-ui/react-collapsible` exclusively results in a typing error when trying to use the default example. Components are still functional if the type error is ignored.

`Root` and `Content` are showing: `Property 'children' does not exist on type 'IntrinsicAttributes & CollapsibleProps & RefAttributes<HTMLDivElement>'`

Looks similar to the issue from https://github.com/radix-ui/primitives/pull/924. When I add `@radix-ui/react-primitive` to my `package.json` the error goes away. It does look like primitive is a dependency of collapsible though, so I'm not sure exactly what's going on.

Thanks in advance!

### Current Behavior
Type error when trying to use components from collapsible.

### Expected behavior
Collapsible should work when installed independently of other radix packages.

### Reproducible example
https://codesandbox.io/s/practical-kirch-dqi9xr?file=/src/App.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     collapsible    |    0.1.5     |
| React            | n/a     |    17.0.1     |
| npm/yarn         |     yarn    |    1.22.17     |
| Operating System |    mac     |     monterey    |

**Comment by andy-hook** [comment]
> Let me know if you're unable to reproduce!

I'm unable reproduce both in the codesandbox example and a local typescript project.

Which package manager are you using? are you seeing this during a typecheck? or is the error only visible in your editor/ide?

**Comment by bisfun-hatfes** [comment]
It ended up being a problem with my `paths` declaration in `tsconfig.json`.

Thanks for the reply and apologies for the invalid issue!

**Comment by egorpavlikhin** [comment]
I've run into the same issue with Popover, Slider, and Tabs components, where installing `@radix-ui/react-primitive` fixed the issue. I believe this occurs when peer dependencies are set to not automatically install.
