### ISSUE TITLE
Tooltip arrow not positioned properly when trigger is near edge of viewport

### ISSUE THREAD

**Issue by danielpickett** [radix-ui/primitives#1208]
### Current Behavior

When the tooltip's trigger is near the edge of the viewport, the arrow is no longer centered on the trigger. Instead it jumps over to the corner of the tooltip content.

![image](https://user-images.githubusercontent.com/11799835/155900715-60689040-22b6-4162-89cb-b4618b337c18.png)

### Expected behavior

The arrow should stay centered on the tooltip target.

### Reproducible example

This is reproducible in your current documentation site, by simply unticking the `justify-content: centered` property in the Styles Inspector, and narrowing the window until the sidebar disappears and the page margins become very small.

![image](https://user-images.githubusercontent.com/11799835/155987093-bff01e6c-6db8-4c9c-a920-dbbb68a3e28a.png)

I was also able to quickly reproduce it by cloning your example codesandbox and changing the styles there. I also added various amounts of padding to the main container div, showing that it happens even when the trigger button is near, but not completely in contact with the side of the viewport. The issue occurs any time the distance from the center of the tooltip trigger to the edge of the viewport is less than half the width of the tooltip content.

Here's my fork of your example codesandbox from the docs: https://codesandbox.io/s/silly-tess-d8jlfu?file=/styles.css:278-326

### Suggested solution

Not sure. I'll look into this if the time becomes available to me. I really like Radix so far, but given my deadlines I may just have to swap it out for a tooltip that works out-of-the-box.

### Additional context

None

### Your environment

| Software                      | Name(s) | Version |
| --------------------- | --------- | ------- |
| Radix Package(s) |         |  see codesanbox link       |
| React            | n/a     |     see codesanbox link      |
| Browser          |      Chrome   |       98.0.4758.102 (Official Build) (x86_64)  |
| Assistive tech   |         |         |
| Node             | n/a     |    see codesanbox link       |
| npm/yarn         |         |     see codesanbox link      |
| Operating System |      macOS Big Sur   |    11.6.3 (20G415)    |

### Keywords
radix, tooltip arrow, position, positioning, alignment, not aligned, misaligned

**Comment by owaiskhan3** [comment]
paste this in your css file hope it will resolve your issue

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
body {
  font-family: system-ui;
  width: 100vw;
  height: 100vh;
  background-image: linear-gradient(
    330deg,
    hsl(272, 53%, 50%) 0%,
    hsl(226, 68%, 56%) 100%
    );
    /* position: relative; */
  display: flex;
  align-items: flex-start;
  /* justify-content: start; */
  padding: 2rem;
}
body > div {
  padding-top: 120px;
  position: absolute; 
  left: 45px;
}
svg {
  display: block;
}

**Comment by danielpickett** [comment]
Thanks for your attention to this issue, @owaiskhan3. Unfortunately, your solution just absolutely positions the container of the trigger button, and nudges it away from left edge. The point of the tooltip is that it should position itself properly no matter where the trigger button is placed within the viewport. So adjusting the position of the trigger button is not a scalable solution.

**Comment by benoitgrelard** [comment]
@danielpickett There is an `offset` prop on `Tooltip.Arrow` which is to be used for that exact situation.
It is us to you to decide what you want that gap to be.

**Comment by danielpickett** [comment]
Thanks for the quick response @benoitgrelard. It's very much appreciated. It does look like this will solved my problem, and hopefully others can find this issue if they run into the same misunderstanding as I did.

I will say, this seems like it will require more legwork than I would have expected. If I want to make sure the arrow stays centered under the trigger button, then I need this `offset` prop on the Tooltip.Arrow to be dynamically calculated based on the width of the trigger button. This would mean maintaining a ref on the trigger button and taking measurements of its width to calculate the offset. And if the content of the trigger button can change after mount, I may even need a resize observer on the trigger button to update that width measurement. 

I'm probably over-engineering it in my head. Is this how you typically handle it? Or do you have some tricks or shortcuts to get this centered with less overhead?

**Comment by benoitgrelard** [comment]
I think it's largely a design decision really and that "need" mostly only comes with an `IconButton` (square ratio) rather than a regular text button.

As in, this type of button and alignment is fine:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1539897/156014691-d38e4fda-983c-4853-8003-0df99d596905.png">

This is just the way our `popper` functionality currently works with regards to arrow positioning, but we could improve it in the future. But that's how things stands right now.

✌️

**Comment by latin-1** [comment]
![image](https://user-images.githubusercontent.com/44946699/163544470-7b1b246d-1663-4767-92a9-1e57a7099ec8.png)

I think the arrow should point to the center of the trigger (with `align="center"`, which is the default value) even if it's near the edge of the viewport. The screenshot above is borrowed from floating-ui (f.k.a. popper.js), which handles arrow position much better.
