### ISSUE TITLE
[Toast] Toast doesn't play nice with Framer Motion

### ISSUE THREAD

**Issue by JuanM04** [radix-ui/primitives#1211]
### Current Behavior

When using the new Toast with Framer Motion, it does some wierd animation. I suppose it's because the Toast element appears in the document root for a few seconds and then it's moved inside the `<Toast.Viewport />`.

https://user-images.githubusercontent.com/16712703/156083401-bcb0ca14-c2b1-41db-9e85-f543a642dcb8.mp4

### Reproducible example

<details>
  <summary>This is my exact setup. It's a global zustand store that adds and removes notifications. I had it working with divs and I tried to migrate it to Radix</summary>

```tsx
import {
  CheckCircleIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  XCircleIcon,
} from '@heroicons/react/outline'
import { XIcon } from '@heroicons/react/solid'
import * as Toast from '@radix-ui/react-toast'
import clsx from 'clsx'
import { AnimatePresence, motion } from 'framer-motion'
import { nanoid } from 'nanoid'
import { Except, Merge } from 'type-fest'
import createStore from 'zustand'

import { Spinner } from '@/components/Spinner'

import { NormalizedError } from './normalizedError'

export interface Notification {
  id: string
  type: 'loading' | 'success' | 'warning' | 'error' | 'info'
  title: string
  body?: string
  timeout: number
  preventClose?: boolean
}

interface NotifyStore {
  notifications: Notification[]
  notify: (data: Merge<Except<Notification, 'id'>, { timeout?: number | null }>) => string
  closeNotification: (id: string) => void
}

const useStore = createStore<NotifyStore>(set => ({
  notifications: [],
  notify: data => {
    const id = nanoid()

    set(state => ({
      notifications: [
        {
          ...data,
          id,
          timeout:
            typeof data.timeout === 'number'
              ? data.timeout
              : data.timeout === null
              ? Infinity
              : data.type === 'loading'
              ? Infinity
              : 5000,
          preventClose: data.preventClose ?? data.type === 'loading',
        },
        ...state.notifications,
      ],
    }))

    return id
  },
  closeNotification: (id: string) =>
    set(({ notifications }) => {
      const i = notifications.findIndex(item => item.id === id)
      if (i === -1) return { notifications }

      return {
        notifications: [...notifications.slice(0, i), ...notifications.slice(i + 1)],
      }
    }),
}))

export const notify = (...args: Parameters<NotifyStore['notify']>) =>
  useStore.getState().notify(...args)

export const notifyUnexpectedError = (input: unknown) => {
  const error = NormalizedError.from(input)
  error.log()
  notify({ type: 'error', title: 'Hubo un error', body: error.toString(), timeout: null })
}

export const closeNotification = (...args: Parameters<NotifyStore['closeNotification']>) =>
  useStore.getState().closeNotification(...args)

export function NotifyProvider() {
  const { notifications, closeNotification } = useStore()

  return (
    <Toast.Provider>
      <AnimatePresence>
        {notifications.map(notification => (
          <Toast.Root
            asChild
            forceMount
            open
            onOpenChange={open => {
              if (open === false && notification.preventClose !== true) {
                closeNotification(notification.id)
              }
            }}
            duration={notification.timeout}
            key={notification.id}
          >
            <motion.li
              layoutId={notification.id}
              className={clsx(
                'mt-4 flex w-96 items-start justify-between rounded-md p-4 shadow-lg',
                notification.type === 'info'
                  ? 'bg-blue-500 text-white'
                  : notification.type === 'success'
                  ? 'bg-green-500 text-white'
                  : notification.type === 'warning'
                  ? 'bg-yellow-500 text-black'
                  : notification.type === 'error'
                  ? 'bg-red-500 text-white'
                  : notification.type === 'loading'
                  ? 'bg-gray-500 text-white'
                  : null
              )}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1, transition: { duration: 0.1, ease: 'easeOut' } }}
              exit={{ opacity: 0, scale: 0.95, transition: { duration: 0.1, ease: 'easeOut' } }}
              transition={{ duration: 0.2, ease: 'easeOut' }}
            >
              <div>
                {notification.type === 'info' ? (
                  <InformationCircleIcon className="h-5 w-5" />
                ) : notification.type === 'success' ? (
                  <CheckCircleIcon className="h-5 w-5" />
                ) : notification.type === 'warning' ? (
                  <ExclamationCircleIcon className="h-5 w-5" />
                ) : notification.type === 'error' ? (
                  <XCircleIcon className="h-5 w-5" />
                ) : (
                  <Spinner className="h-5 w-5" />
                )}
              </div>
              <div className="grow pl-2 pr-4 text-sm">
                <Toast.Title className="font-medium">{notification.title}</Toast.Title>
                {notification.body && (
                  <Toast.Description>
                    {notification.body.split('\n').map((text, i) => (
                      <p key={i} className="mt-1">
                        {text}
                      </p>
                    ))}
                  </Toast.Description>
                )}
              </div>
              {!notification.preventClose && (
                <Toast.Close>
                  <XIcon className="h-5 w-5 opacity-90 transition hover:opacity-100" />
                </Toast.Close>
              )}
            </motion.li>
          </Toast.Root>
        ))}
      </AnimatePresence>

      <Toast.Viewport className="fixed top-4 right-8 z-20 flex flex-col" />
    </Toast.Provider>
  )
}
```

</details>

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | `@radix-ui/react-toast` | 0.1.1 |
| React            | n/a     | 18.0.0-rc.0 |
| Browser          | Brave | 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit) |
| Assistive tech   |         |         |
| Node             | n/a     | 16.14.0 |
| npm/yarn         | pnpm | 6.32.2 |
| Operating System | Fedora Linux | 35 |

**Comment by jjenzz** [comment]
Can you provide a codesandbox with your framer-motion implementation please? It looks like you've told it to animate from that position.

Here's a working example https://codesandbox.io/s/friendly-galileo-2wt11o?file=/src/App.js

**Comment by jjenzz** [comment]
@JuanM04 I'd suggest double checking your `framer-motion` settings because I can see you are using `layoutId` on `motion.li` which is adding `translate3d` styles to the toast.

**Comment by JuanM04** [comment]
I need the `layoutId`. The idea is that the user can see multiple toasts at the same time, and framer motion handles the positioning (hence the `translate3d`). The only anomaly I've found is that, as you can see in the video, the Toast appears for a few seconds in the root `<body>` and then moves inside the `<Toast.Viewport />`

**Comment by jjenzz** [comment]
@JuanM04 The toast that appears in the body is separate. It does not receive any props (so no styles).

**Comment by JuanM04** [comment]
The visual glitch happens exactly when that other Toast disappears. Could it be a ref mismatch or something like that?

**Comment by jjenzz** [comment]
This is the toast that is added to the body (no props or refs) https://github.com/radix-ui/primitives/blob/main/packages/react/toast/src/Toast.tsx#L408

This is the toast that renders in the viewport https://github.com/radix-ui/primitives/blob/main/packages/react/toast/src/Toast.tsx#L427

@benoitgrelard @andy-hook I wonder if this might have something to do with `Presence`. Perhaps moving `React.createPortal` around `Presence` might help.

**Comment by JuanM04** [comment]
> Here's a sandbox instead of a stackblitz: https://codesandbox.io/s/delicate-snow-e4c5g6?file=/src/App.js

Try wrapping the notification map with the AnimatePresence:

```diff
- {[...notifications].map((_, id) => (
-   <AnimatePresence key={id}>
+ <AnimatePresence>
+   {[...notifications].map((_, id) => (
```

**Comment by jjenzz** [comment]
Yes, seems the issue is there either way.

**Comment by hipstersmoothie** [comment]
I'm also having trouble animation the toasts but I'm using react-spring to animate the full list. Since it seems like toasts get placed in the Viewport outside of react I can't easily use react-spring's use-transition to animate their entrances/exits all together:

- Slide new toast in on top of old toasts
- When a toast is dismissed animated all the toasts moving down

**Comment by hipstersmoothie** [comment]
Update: was able to get individual toasts to animation but the group animation is still hard to accomplish

https://user-images.githubusercontent.com/1192452/156640684-1a78ee66-ef55-40d4-a9c8-599ae10f5ce1.mp4

**Comment by andy-hook** [comment]
> The toast that appears in the body is separate. It does not receive any props (so no styles). It is added and then instantly removed from the DOM after 1 second (for SRs only).

The `Announce` implementation does look to be the problem, `motion.xx` is passed as child when composing with `asChild` so this along with it's id and associated props get rendered in both places, seems that this causes framer-motion to try to interpolate between the two layout positions.

I was considering ways to flatten children within `Announce`, but then I figured it might be simpler to move the announce functionality back into `ToastImpl` and avoid the duplicate components entirely.

I did some tests on my side and it seems to work fine (providing we continue to defer child render to next tick) @jjenzz you have quite a bit of experience with NVDA and announcements, do you recall any accessibility gotchas?

**Comment by jjenzz** [comment]
i did originally have the announce inside the toast and moved it out due to issues i cannot recall. BUT, things changed a lot over time so they might not be issues anymore. i'd suggest testing heavily in NVDA as that is where i had a lot of "stuttering" issues (toasts being read aloud twice).

if you create a pr with your solution, i can help to test to see if my muscle memory recalls a certain test case.

**Comment by andy-hook** [comment]
> i can help to test to see if my muscle memory recalls a certain test case.

You're the best, i'm working on an improvement to solve this and https://github.com/radix-ui/primitives/issues/1322 will tag you when I raise 🙏
