### ISSUE TITLE
Option to change order props are merged in `<Slot />` 

### ISSUE THREAD

**Issue by charkour** [radix-ui/primitives#1216]
First, thank you for this awesome package! The API and docs are amazing.

## Feature request
Allow [`<Slot />`](https://github.com/radix-ui/primitives/blob/main/packages/react/slot/src/Slot.tsx) to receive a prop that changes the merge order in the [`mergeProps` function](https://github.com/radix-ui/primitives/blob/4ee9d362fcd5e32edbce9f43f1d41f1bf1a015c1/packages/react/slot/src/Slot.tsx#L79). There are cases where the merge order matters, for example, with event handlers. I can provide a code sandbox if you would like.

### Overview

New Slot API:
```tsx
<Slot reverseMerge onClick={handleClick}>
```

This would change the implementation of [`mergeProps`](https://github.com/radix-ui/primitives/blob/4ee9d362fcd5e32edbce9f43f1d41f1bf1a015c1/packages/react/slot/src/Slot.tsx#L79). There are a couple of different ways to accommodate this change. Either, we could switch the order the arguments are passed in [SlotClone](https://github.com/radix-ui/primitives/blob/4ee9d362fcd5e32edbce9f43f1d41f1bf1a015c1/packages/react/slot/src/Slot.tsx#L53), pass a third argument to `mergeProps`, or make `mergeProps` accept an arbitrary amount of prop objects like the package below. I would prefer this option.

### Examples in other libraries
[merge-props](https://github.com/andrewbranch/merge-props). They merge props based on order passed to the merge function and take an arbitrary number of prop objects. I would install this package to my team's project, but since `Slot` from Radix provides this behavior, I don't want to install two nearly-redundant packages.

### Who does this impact? Who is this for?

This is for advanced users and my team at work.

Would be willing to make the PR if this feature request is approved. My current workaround is merging the component props in a specific order by hand. Thanks!

**Comment by jjenzz** [comment]
I haven't looked into this but off the top of my head, i think it is the current order on purpose to allow `event.preventDefault` to work so not sure they can be re-ordered.

if you call `event.preventDefault()` in a child handler, it should prevent the one slotted onto it.

**Comment by charkour** [comment]
Hey, thanks for the quick reply! 

I am a little bit confused by your response since the `<Slot />` component doesn't call `preventDefault` on events. It is possible that other components in this library depend on the behavior you mentioned, but the feature request does not change default behavior.

My feature request is to change the order that merged callbacks are executed. This does not relate to preventing event defaults.

Thanks again! I can propose a PR so you can see specifically what features would be great for people using the `<Slot />` component as a way to merge props.

**Comment by jjenzz** [comment]
> I am a little bit confused by your response since the `<Slot />` component doesn't call `preventDefault` on events.

Imagine this scenario:

```jsx
<DropdownMenu.Trigger asChild>
  <button onPointerDown={event => event.preventDefault()}></button>
</DropdownMenu.Trigger>
```

The *consumer's* code there should prevent the `onPointerDown` handler that slots onto button from `DropdownMenu.Trigger`'s implementation.

This is how DOM events work too... the consumer handler is always evaluated first so that the browser knows whether there was an attempt to prevent it:

```jsx
// html
<button onmousedown="handleMouseDown(event)"></button>

// javascript
function handleMouseDown(event) {
  event.preventDefault()
}
```

In this example, the browser will call `handleMouseDown` first and the check if consumer prevented the browser's handler for this event. If they did, it would prevent the button from receiving focus which is what the browser handler does if mouse down is not prevented.

**Comment by charkour** [comment]
Hi @jjenzz, 

Thanks for the great response. I don't know as much about the DOM as you do, so I apologize for my ignorance. 

With my use case, I was using [Next/Link](https://nextjs.org/docs/api-reference/next/link) from Next.js and needed to merge their link behavior with custom logic, and wanted to do that with Slot. Their implementation sometimes causes issues with the order of how click handlers are called, but since this seems like an edge case, it makes sense not to modify Radix to support handler "anti-patterns".

Thanks again.
