### ISSUE TITLE
[Select] Touch Issue with select component (Firefox)

### ISSUE THREAD

**Issue by DanielBailey-web** [radix-ui/primitives#1221]
### Current Behavior

When using mobile touch emulator on Firefox the select menu does switch to the new option on first touch. 

I would assume that this could cause a problem in some mobile browser. But I am not sure that it does. At the very least it is annoying .

### Expected behavior

Select the option when selecting and option in the select menu

### Reproducible example
The example on the radix ui exhibits this behavior. You must be in mobile view on Firefox with touch simulation turned on.
[CodeSandbox Template](https://www.radix-ui.com/docs/primitives/components/select)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |  Firefox      |       Firefox@97.0|
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |       happens on Windows and Linux Ubuntu  |

**Comment by benoitgrelard** [comment]
I'm not sure what you mean, this is what I see:

https://user-images.githubusercontent.com/1539897/160611256-1912d5ed-0140-4241-8ad8-4b773277546e.mov

**Comment by DanielBailey-web** [comment]
@benoitgrelard On chrome you do not have to click the *option* twice. It selects the option on first touch. Notice in your screen capture you have to click on pineapple / courgette twice. on the first click it focuses it and then on the second click it selects it.

**Comment by benoitgrelard** [comment]
Have you tested on firefox on a real device? Could it potentially be a quirk of the emulation?

**Comment by equal-matt** [comment]
I can confirm that this is an issue on my phone (Pixel 2, Firefox 100.2).

It appears just as @benoitgrelard 's screengrab shows; two presseses need to select the option, with the first highlighting the option you've selected.

**Comment by DanielBailey-web** [comment]
@equal-matt Thanks for confirming, I totally forgot to do it.

**Comment by benoitgrelard** [comment]
Hi @equal-matt, @DanielBailey-web, we have recently made some fixes to some underlying logic which I suspect may be related to this `Select` issue. Would either of you be able to test the latest Select rc on a mobile device with Firefox?

The easiest way will be to:
- go to this page: https://www.radix-ui.com/docs/primitives/components/select
- click on the codesandbox icon in the bottom right corner of the demo at the top of the page
- update the version of Select to the latest rc ([0.1.2-rc.28](https://www.npmjs.com/package/@radix-ui/react-select/v/0.1.2-rc.28) at the time I'm writing this, so needs to be this or higher)

Let me know what you observe,

Thanks 🙏

**Comment by equal-matt** [comment]
@benoitgrelard Just tested it and it's back to normal on `0.1.2-rc.28`. 🎉 

FYI if things like this come up again it's actually quite hard to edit CodeSandbox on mobile - it would be really helpful to fork and send a link to an environment that's set up already.

**Comment by benoitgrelard** [comment]
Thanks for confirming! I will close the issue.

> FYI if things like this come up again it's actually quite hard to edit CodeSandbox on mobile - it would be really helpful to fork and send a link to an environment that's set up already.

Thanks also for noting this, I didn't think about it but will definitely consider it for next time.

**Comment by benoitgrelard** [comment]
Closed via #1401
