### ISSUE TITLE
[Select] Underlying native `select` has wrong default value

### ISSUE THREAD

**Issue by frgarciames** [radix-ui/primitives#1223]
### Current Behavior

When you set defaultValue in Select component, hidden html select has first option as value instead of defaultValue. So, when you submit uncontrolled form with defaultValue form sends first option of the select as value.
This happens too when you select currently selected option, It sets first option as value.

### Expected behavior

Hidden html select should have defaultValue as value if you do not change the selected option, and if you select the currently selected option, it should not change value.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/select-radix-wrong-value-gl0i4w?file=/App.js)

**Comment by benoitgrelard** [comment]
Hey @frgarciames, I can confirm the issue on my side.
