### ISSUE TITLE
Wrong type for forceMount prop on DropdownMenu.Content

### ISSUE THREAD

**Issue by s-yadav** [radix-ui/primitives#1237]
## Bug report
Looks like type for forceMount is given as `true`  instead of `boolean`. Which breaks passing condition on this prop. Is this intentional?
```
<DropdownMenu.Content forceMount={a === b} /> // this give type error `Type 'boolean' is not assignable to type 'true'.`
```

https://github.com/radix-ui/primitives/blob/main/packages/react/menu/src/Menu.tsx#L238

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by jjenzz** [comment]
https://github.com/radix-ui/primitives/pull/1060#issuecomment-1004742028

**Comment by s-yadav** [comment]
Got it.
