### ISSUE TITLE
Tooltip doesn't appear when the trigger is an input wrapped in a forwardRef

### ISSUE THREAD

**Issue by moroshko** [radix-ui/primitives#1240]
### Current Behavior

Here is a simplified example where an `<input>` is wrapped in a component that uses a `forwardRef`.
I can't get the tooltip to appear. What am I missing?

```js
const InputWrapper = forwardRef(({ children }, ref) => {
  return <div ref={ref}>{children}</div>;
});

export default function App() {
  return (
    <div className="App">
      <Tooltip.Root delayDuration={0}>
        <Tooltip.Trigger asChild>
          <InputWrapper>
            <input type="text" />
          </InputWrapper>
        </Tooltip.Trigger>
        <Tooltip.Content>Glad to see you!</Tooltip.Content>
      </Tooltip.Root>
    </div>
  );
}

```

### Expected behavior

The tooltip should appear.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/radix-input-tooltip-forked-0bo22n)

**Comment by jjenzz** [comment]
you need to spread props onto the `div` too otherwise tooltip cannot bind events to it.

**Comment by moroshko** [comment]
Thanks @jjenzz, makes sense! Might be worth adding a note about this to the docs.

**Comment by jjenzz** [comment]
@moroshko agreed, a few people have tripped up on this, cc: @benoitgrelard @andy-hook

**Comment by benoitgrelard** [comment]
This might be a contrived example, but what is the need for the extra wrapper rather than attaching the tooltip to the input itself?

> a few people have tripped up on this

I think that's a more general issue around `asChild`, we need a page to document `asChild` in more details I think.

**Comment by e792971419** [comment]
Actually, I do not get what should I do. Could you give me a successful case?

**Comment by e792971419** [comment]
> you need to spread props onto the `div` too otherwise tooltip cannot bind events to it.

Actually, I do not get what should I do. Could you give me a successful case?
