### ISSUE TITLE
Ability to stop click propagation when items are clicked in a dropdown menu

### ISSUE THREAD

**Issue by johno** [radix-ui/primitives#1242]
## Feature request

I _think_ this is a feature request, unless I'm somehow missing this behavior somewhere.

### Overview

I'd like to be able to stop click propagation from a dropdown menu. I'm currently attempting to use a dropdown menu inside a tree view that has folders that can be expanded and collapsed. When the dropdown menu is interacted with, the click event propagates to the node and causes the expand/collapse.

AFAICT there isn't a straightforward way to stop this behavior since it would break internal event handling with the dropdown menu itself. Am I missing something here?

https://user-images.githubusercontent.com/1424573/158223912-3cb954a5-2feb-4488-9ab3-3ebd8b41df96.mp4

### Who does this impact? Who is this for?

This would be a way for users to turn off propagation of click events when the menu might live in other interactive elements, like an accordion or expandable file tree. This shouldn't impact users unless they want to turn on the functionality.

### Additional context

[A CodeSandbox illustrating the issue](https://codesandbox.io/s/bold-hawking-0n3lss?file=/App.js)

Steps to repro:
1. Open up dropdown
2. Click any menu item
3. See the propagated text

**Comment by jjenzz** [comment]
This is happening because React events propagate through portals. To prevent it, you can add `event.stopPropagation()` in the events you want to prevent from bubbling. In your case:

```jsx
<DropdownMenu.Item onClick={event => event.stopPropagation()} />
```

**Comment by johno** [comment]
Ahhhh, yeah I was trying to override the `onSelect` and then tried to override the `onClick` of the `DropdownMenu.Content`. Didn't realize I could do it that way, so simple. Thank you!

**Comment by bartol-komadina** [comment]
For anyone trying to stop the propagation of keyboard events:
```
<DropdownMenu.Trigger onKeyUp={(event) => event.stopPropagation()} />
<DropdownMenu.Item onKeyUp={(event) => event.stopPropagation()} />
```
This prevents propagation of CustomEvent which is fired on `RadixDropdownMenu.Item` and `DropdownMenu.Trigger` keyUp. In my case I had a keyUp event on a parent component which I didn't want to be triggered. Using `event.preventDefault()` in `<DropdownMenu.Item onSelect={(event)=> event.preventDefault()}` works too but stops the dropdown from closing on item select.
