### ISSUE TITLE
Context Menu Not Triggering when Canvas in Tree

### ISSUE THREAD

**Issue by rob-gordon** [radix-ui/primitives#1243]
### Current Behavior

For some reason the context menu does not display when the click is originated in a canvas. I made a small codesandbox to illustrate the problem I'm having. You can see that the `contextmenu` event is bubbling up, so it feels like it should render the Context Menu; however, that's not the case. 

https://user-images.githubusercontent.com/159949/158238302-deb7c930-dbd9-4fd2-887e-4e680b598911.mov

### Expected behavior

The context menu renders.

### Reproducible example

[👨‍💻 CodeSandbox](https://codesandbox.io/s/wonderful-bell-0gvq5f?file=/src/App.js)

### Suggested solution

I'm not sure. I tried to debug but wasn't able to discover the root cause. In https://github.com/radix-ui/primitives/issues/766 it's proposed that maybe the Context Menu may become a controlled component in the future. That's a potential fix, but I would rather figure out the root cause.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |       0.1.6  |
| React            | n/a     |       17  |
| Browser          |         |    Chrome     |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |    Mac OSX     |

**Comment by benoitgrelard** [comment]
Yeah it looks like they're preventing `contextmenu` on their side, so you may be better off raising an issue over there.
