### ISSUE TITLE
[Select] asChild breaks `SelectContent` positioning

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#1244]
The `SelectContent` has a `SelectContentContextProvider` that wraps its `children` inside the primitive part, therefore, positioning is breaking because `asChild` is replacing the provider.

The children need to be wrapped in `Slottable` or the provider needs to be moved to wrap the primitive.

https://codesandbox.io/s/crimson-meadow-65bzrl?file=/App.js

**Comment by JeromeIllgner** [comment]
Hey @jjenzz, awesome work on the quick turn around on the patch. Do you have any idea what a temporary fix could be in the mean-time?

**Comment by JeromeIllgner** [comment]
For anyone that comes across this: It seems that the work-around for the time being is simply setting a default value. Not sure what the options are when you don't want a default value.

**Comment by jjenzz** [comment]
@JeromeIllgner 

> For anyone that comes across this: It seems that the work-around for the time being is simply setting a default value. Not sure what the options are when you don't want a default value.

This sounds like a separate issue to the one this one resolves. Your issue sounds related to these #1235 #1231.
