### ISSUE TITLE
[Select] <Select.Content /> is not positioned over the tigger until a value is selected when rendering a mapped list of <Select.Item>s 

### ISSUE THREAD

**Issue by sohcfst** [radix-ui/primitives#1259]
### Current Behavior

`<Select.Content />` is not positioned over the tigger until a value is selected

### Expected behavior

`<Select.Content />`'s initial position should be over the trigger

### Reproducible example

[Edited version of radix doc's codesandbox example](https://codesandbox.io/s/hopeful-rumple-l43qnc)

### Suggested solution

I'm not sure ): I wish I knew more about CSS

### Your environment
Codesandbox

Everything in the codesandbox
| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by jjenzz** [comment]
there are already a couple of issues/proposals relating to this https://github.com/radix-ui/primitives/issues/1231  https://github.com/radix-ui/primitives/issues/1235

suggest closing as a duplicate 🙏

**Comment by sohcfst** [comment]
@jjenzz got it! thank you

sorry for the delay - i need to manage my notifications better
