### ISSUE TITLE
[Label] Data attributes for disabled, checked

### ISSUE THREAD

**Issue by penx** [radix-ui/primitives#1262]
### Overview

Given a LabelPrimitive.Root and an associated Radio or Checkbox, e.g.

```tsx
const Label = styled(LabelPrimitive.Root)({})

<Label>
  <CheckboxPrimitive.Root />
  <div>Some Text</div>
</Label>
```

Append `data-disabled` and `data-checked` (or `data-state`) to the Label, so that styles can be applied to the outer label element depending on whether the inner input is disabled or checked.

```tsx
const Label = styled(LabelPrimitive.Root)({
  '&[data-state="checked"]' : {borderColor: 'black'},
  '&[data-disabled="true"]' : {opacity: 0.3 }, 
})

<Label>
  <CheckboxPrimitive.Root />
  <div>Some Text</div>
</Label>
```

**Comment by jjenzz** [comment]
if you are adding `disabled` prop to the radio/checkbox, why not just add it manually to the label yourself also? the comps can be controlled for the `checked` case.

**Comment by penx** [comment]
> if you are adding disabled prop to the radio/checkbox, why not just add it manually to the label yourself also?

I was trying to avoid exposing an API from our DS that would require users to do this, but it's pretty minor so fair enough.

> the comps can be controlled for the checked case

At the moment our DS is in storybook and uncontrolled. Yes when they are used outside storybook they will likely be controlled I could add a `checked` property to the label.


Both of the above are minor, but something I figured would result in a cleaner API and something that others could benefit from too - but feel free to close if you disagree or it would be too hard or hacky to implement.

**Comment by jjenzz** [comment]
i'm not convinced this should belong in radix because a label cannot be checked. it's not really a functional label concern. also, if you are passing props up from within a child, you'd need to use `React.useEffect / React.useLayoutEffect` which means it would not have the necessary styling when server-side rendered.

the request sounds specific to your product's **design requirements** which is why radix provides controllable apis, so you can wrap the radix parts and provide the api your product needs. 

the extra steps don't need to be pushed onto the consumer like you describe if you do something like the following, but again, you'll have the SSR issues:

```jsx
const DesignSystemLabelContext = React.createContext();

const DesignSystemLabel = (props) => {
  const [attrs, setAttrs] = React.useState({});
  return (
    <DesignSystemLabelContext.Provider value={setAttrs}>
      <RadixLabel {...props} {...attrs} />
    </DesignSystemLabelContext.Provider>
  );
}

const DesignSystemCheckbox = (props) => {
  const setLabelAttrs = React.useContext(DesignSystemLabelContext);
  const { checked: checkedProp, defaultChecked, onCheckedChange, ...rest } = props;
  const [checked = checkedProp, setChecked] = React.useState(defaultChecked);
  const isControlled = checkedProp !== undefined;

  React.useEffect(() => {
    setLabelAttrs({ 
      'data-state': checked ? 'checked' : 'unchecked',
      'data-disabled': disabled ? "" : undefined,
    });
  }, [props.disabled, checked]);

  return (
    <RadixCheckbox 
      {...rest}
      checked={checked} 
      onCheckedChange={checked => {
        if (!isControlled) setChecked(checked);
        props.onCheckedChange?.(checked);
      }}
    />
  );
}
```

**Comment by jjenzz** [comment]
I would have thought that would be invalid markup because the radio item renders a `button`. you can probably get rid of the `label` tho and just put the text there because a button is automatically labelled by the text within it.
