### ISSUE TITLE
[Dialog] Expected clickable elements behind overlay not to trigger on clickOutside in mobile mode.

### ISSUE THREAD

**Issue by einaralex** [radix-ui/primitives#1263]
## Bug report

When using a portalled dialog, I was expecting elements not to be clickable underneath the overlay.

I was having trouble fixing it until I set the body to be:

```<body style={{ pointerEvents: 'auto' }}>```

Now it works like I anticipated.

### Current Behavior

Clicking elements under a Dialog.Overlay are triggered.

### Expected behavior

Elements under a Dialog.Overlay should not be clickable until Dialog is closed.

### Reproducible example

[Official Dialog sample](https://www.radix-ui.com/docs/primitives/components/dialog)

1. Click 'Edit profile'
2. Click 'Show Code' underneath overlay.
3. Observe that button was clicked and now says 'Hide code'

### Suggested solution

Not sure, but something is messing with pointerEvents on the body which is causing this.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    react-dialog     |      0.1.7   |
| React            | n/a     |   17.0.2      |
| Browser          |     Chrome    |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi @einaralex,

I'm having trouble following what you are talking about.
Would you be able to describe the issue you are seeing a bit more?

Thanks

**Comment by einaralex** [comment]
Hey @benoitgrelard. 
So when you have a dialog open, there is an overlay over the rest of the UI around the Dialog, usually styled to be slightly greyed out.
When clicking the overlay (clickOutside), the usual behaviour is that the dialog will close.
So let's say we have an open dialog, I click outside to close it, I expect no other actions to happen, only the dialog to close. But if there is a clickable button/element behind the overlay where I clicked, that will get triggered as well.

I noticed that this is **only reproducible with the onTouch (mobile mode)**, onClick seems to work correctly.

https://thumbs.gfycat.com/MildHeavyKookaburra-mobile.mp4

**Comment by benoitgrelard** [comment]
Hi @einaralex,

Thanks for providing this.
That would explain why I couldn't see it on Chrome desktop.
So it only happens on touch devices?

**Comment by einaralex** [comment]
Yeah seems that way, tried it on my mobile, happens there, also in responsive mode on Chrome dev tools.

**Comment by benoitgrelard** [comment]
I can confirm this is still an issue in `main` in any condition (animation or not) but is linked to touch as per the issue.
Looking into it.

**Comment by menachem1** [comment]
seems like a solution is to wrap the overlay in a `DialogPrimitive.Close` and set  `onClick={(e) => e.stopPropagation()}` 
```JS
<DialogPrimitive.Close onClick={(e) => e.stopPropagation()}>
<DialogOverlay />
</DialogPrimitive.Close>
```

**Comment by zachkaigler** [comment]
> it seems like the issue still happens when the DialogTrigger is on a clickable component then when you dismiss the dialog by clicking the overlay the component gets triggered.

Running into this problem myself - I tried your solution with the `DialogPrimitive.Close` wrapper that stops the event from bubbling, but it doesn't seem to solve the issue consistently (weirdly though sometimes it does?) Curious if you ended up noticing these inconsistencies yourself or if there's been any other movement here?

**Comment by zachkaigler** [comment]
> it seems like the issue still happens when the DialogTrigger is on a clickable component then when you dismiss the dialog by clicking the overlay the component gets triggered.

@eternity4318  Running into this problem myself - I tried your solution with the `DialogPrimitive.Close` wrapper that stops the event from bubbling, but it doesn't seem to solve the issue consistently (weirdly though sometimes it does?) Curious if you ended up noticing these inconsistencies yourself or if there's been any other movement here?

**Comment by eternity4318** [comment]
Sorry I haven't been in the codebase for a while. I don't remember.

**Comment by weebao** [comment]
Having this problem right now too

**Comment by daviliano2** [comment]
I am also having this issue although my setup might be a bit unique. Our company project is a react app in an electron wrapper. This runs in a panel PC with a touch screen with debian. The solution for me is the following:
1 - create a custom hook:
```
 function useSuppressNextClick() {
  // Arm a one-off capture listener to swallow the next click
  return React.useCallback(() => {
    const handler = (e: MouseEvent) => {
      e.stopPropagation()
      e.preventDefault()
    }
    // capture: true → intercept before anything else
    // once: true → auto-remove after first call
    window.addEventListener('click', handler, { capture: true, once: true })

    // Safety: if no click happens at all, make sure it's gone
    const timeout = window.setTimeout(() => {
      window.removeEventListener('click', handler, true)
    }, 250)

    return () => clearTimeout(timeout)
  }, [])
} 
```
2 - prevent all defaults in the dialog content and capture the click outside the modal with the hook, then use the callback inside `requestAnimationFrame` to close the modal, it has to be a controlled component:
```
const suppressNextClick = useSuppressNextClick()
...
...
<Dialog.Content
        onInteractOutside={(e) => {
          e.preventDefault()
        }}
        onPointerDownOutside={(e) => {
          // 1) Don’t let Radix close right now
          e.preventDefault()
          // 2) Kill the upcoming synthetic click
          suppressNextClick()
          // 3) Close on the next frame so unmount happens *after* we armed the buster
          requestAnimationFrame(() => {
            if (handleClose) {
              handleClose()
            }
          })
        }}
        onOpenAutoFocus={(e) => {
          e.preventDefault()
        }}
      >
        {children}
      </Dialog.Content>
```
After many hours trying many different potential solutions I resorted to have a long conversation with chatGPT which I am not a fan of and it pointed me in this direction. I was surprised that it worked since I've never had to use before `requestAnimationFrame` so I thought it was making up garbage magical functions.

I hope this helps anybody that is still having issues on touch screens
