### ISSUE TITLE
[HoverCard] Isolate X/Y axis collisions for Hover Card

### ISSUE THREAD

**Issue by zkSoju** [radix-ui/primitives#1264]
### Overview

When using a hover card it would be nice to have more flexibility to control X/Y axis collisions separately. Horizontal collision in some cases is needed and vertically not so much and vice versa.

**Comment by benoitgrelard** [comment]
Hi @zkSoju,

Generally, collisions should be handled automatically and I can't see any reason why you wouldn't need to handle them on one axis rather than all.

I will close the issue as this is unlikely to be a priority for us, but I'm happy to keep discussing here.

✌️
