### ISSUE TITLE
[Accordion] Initial animation missing in Firefox and Safari

### ISSUE THREAD

**Issue by te-online** [radix-ui/primitives#1265]
### Current Behavior

Accordion elements only animate correctly on the 2nd open in Firefox and Safari. It's a bit subtle to see on the example page, but if you put longer text into the accordion elements it is a lot more noticeable.

https://user-images.githubusercontent.com/4127167/159681799-dbf90a1b-5527-481b-9727-e1d3ee993d3d.mov

### Expected behavior

Accordion elements animate smoothly on 1st open, same as in Chrome.

### Reproducible example

[CodeSandbox (clone of the original example with more text)](https://codesandbox.io/s/flamboyant-rain-mdil3w)

### Suggested solution

I don't really know what's causing this, unfortunately. But I think that maybe the `[data-state="open"]` attribute is applied before computation of the final height of the element is finished.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Accordion     |  0.1.6       |
| React            | n/a     |  17.0.2       |
| Browser          |  Firefox       |     98.0.1    |
| Browser          |  Safari       |     15.4  |
| Operating System |    macOS & Window     |   n/a      |

**Comment by nemdo** [comment]
I have the exact same issue.

Issue present on:
- iOS Safari
- iOS Chrome
- iOS Firefox
- iOS Ecosia
- every other iOS browser?
- Desktop Firefox

Not present on:
- Desktop Chrome

This is the second Radix UI component I'm trying (after the Dialog) and both have UX issues that make them unusable in production. Of course, this is open-source and I'm grateful for your incredible work, but do you think that this issue will be patched soon or should I go with another library? Thank you in advance.

**Comment by andy-hook** [comment]
Hey @nemdo it's on our radar to be addressed but I can’t promise when we'll be able to get a patch out.

> both have UX issues that make them unusable in production

What other problems have you encountered? feel free to raise issues you've encountered.

**Comment by benjaminleonard** [comment]
I don't imagine this is a proper fix, but I can get it working in Safari with the following:

```
  const [mount, setMount] = useState(true)

  useEffect(() => {
    setMount(false)
  }, [])
```

and then `<Accordion.Content forceMount={mount}`>

**Comment by benoitgrelard** [comment]
@benjaminleonard, unfortunately probably not as `forceMount` is meant to be used only for JS animation support, and can't be dynamic either.

**Comment by inje-hottestlab** [comment]
Hi, I couldn't wait until the next release came out, so I solved it in the following way.
I checked that it works well on Safari and Firefox.

```jsx
import {
    useLayoutEffect,
    useState,
    type PropsWithChildren,
} from 'react';
import * as CollapsiblePrimitive from '@radix-ui/react-collapsible';

function Collapsible(props: PropsWithChildren) {
    const [forceMount, setForceMount] = useState<true | undefined>(true);

    useLayoutEffect(() => {
        setForceMount(undefined);
    }, []);

    return (
        <CollapsiblePrimitive.Root>
            <CollapsiblePrimitive.Trigger>
                ...
            </CollapsiblePrimitive.Trigger>

            <CollapsiblePrimitive.Content forceMount={forceMount}>
                {props.children}
            </CollapsiblePrimitive.Content>
        </CollapsiblePrimitive.Root>
    );
}
```
