### ISSUE TITLE
[Tooltip] `Tooltip.Arrow` can have a gap when zooming

### ISSUE THREAD

**Issue by acc-nicholas** [radix-ui/primitives#1275]
### Current Behavior
At various zoom levels, there is a gap between the tooltip arrow and the tooltip content.
![image](https://user-images.githubusercontent.com/50001189/160208615-1e761a39-3203-430c-a94b-c143be26f45d.png)

### Expected behavior

There should be no gap.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/pjg1gh?module=App.js&file=/App.js) open the sandbox example in a new window and zoom in/out.

### Suggested solution

It seems like a rounding issue between the `bottom: 100%` of the arrow and the px rounding of the arrow size itself.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Tooltip or use-size     |     0.1.7    |
| React            | n/a     |         |
| Browser          |    Chrome     |     99.0.4844.51    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    MacOS  Big Sur   |    11.6.3     |

**Comment by benoitgrelard** [comment]
Hi @acc-nicholas,

This looks like it's a general sub-pixel rasterization issue at certain zoom levels.
This isn't something we would solve at the library level and if it's an issue for you, you could always solve it by nudging your arrow 1px down if you wanted to.
