### ISSUE TITLE
[Dialog] Expose Dialog context

### ISSUE THREAD

**Issue by lesha1201** [radix-ui/primitives#1281]
### Overview

Expose Dialog context so it's possible to use it in components inside DialogProvider.

### Who does this impact? Who is this for?

I want to create a custom Dialog Content component which turns off `onPointerDownOutside` behaviour and adds click listener on Overlay which closes Dialog so Dialog isn't closed when clicking Overlay's scrollbar (https://github.com/radix-ui/primitives/issues/1280).

**Raw example:**

```jsx
export function DialogContent(props) {
  const context = useDialogContext(CONTENT_NAME, props.__scopeDialog);

  const onPointerDownOutside = useCallback(event => {
    event.preventDefault();
  }, []);

  const onClickOverlay = useCallback(
    event => {
      // ...implementation
      context.onOpenChange(false);
    },
    [context.onOpenChange],
  );

  return (
    <DialogPortal>
      <DialogOverlay onClick={onClickOverlay}>
        <BaseDialogContent
          {...props}
          onPointerDownOutside={onPointerDownOutside}
        >
          {children}
        </BaseDialogContent>
      </DialogOverlay>
    </DialogPortal>
  );
}
```

**Comment by jjenzz** [comment]
there is an `onPointerDownOutside` event on `Dialog.Content` that you can prevent if wish to prevent clicking outside from closing https://www.radix-ui.com/docs/primitives/components/dialog#content

**Comment by jjenzz** [comment]
the components have a controlled api for this (`open` and `onOpenChange` props) so you can achieve this as follows:

```jsx
import { useControlledState } from 'use-controlled-state';

const CustomContext = React.createContext();

export function Dialog(props) {
  const [open = props.defaultOpen, setOpen] = useControlledState(props.open, props.onOpenChange);
  const contextValue = React.useMemo(() => ({ open, onOpenChange: setOpen }), [open, setOpen]);
  return (
    <CustomContext.Provider value={contextValue}>
      <Dialog {...props} open={open} onOpenChange={setOpen} />
    </CustomContext.Provider>
  );
}

export function DialogContent(props) {
  const context = React.useContext(CustomContext);

  const onPointerDownOutside = useCallback(event => {
    event.preventDefault();
  }, []);

  const onClickOverlay = useCallback(
    event => {
      // ...implementation
      context.onOpenChange(false);
    },
    [context.onOpenChange],
  );

  return (
    <DialogPortal>
      <DialogOverlay onClick={onClickOverlay}>
        <BaseDialogContent
          {...props}
          onPointerDownOutside={onPointerDownOutside}
        >
          {children}
        </BaseDialogContent>
      </DialogOverlay>
    </DialogPortal>
  );
}
```

I think that `use-controlled-state` package incorrectly switches between controlled/controlled though so might be worth searching for something that knows how to handle this appropriately or use the radix `use-controllable-state` package.

**Comment by lesha1201** [comment]
@jjenzz Thank you for the example.

I don't like that it introduces one more context and state. Would it be easier and better just to expose `useDialogContext` hook?

**Comment by jjenzz** [comment]
> I don't like that it introduces one more context and state. 

curious why?

> Wouldn't it be easier and better just to expose `useDialogContext` hook?

primitives purposefully have a small api surface to minimise testing overhead and reduce consumer exposure to breaking changes. at the moment, the context api can be modified at will by the radix team without worrying about introducing breaking changes to consumers. for example, an `onOpenChange` method exists today but there's no guarantee it would tomorrow.

ideally you would build your own apis instead of piggy-backing off of radix's internals so the current api provides the tools to achieve the api your product needs.

**Comment by lesha1201** [comment]
@jjenzz From primitive, I expect it to be as much customizable as possible and one of the keys is having access to its internal context. That way it would cover a lot of use-cases (e.g. ability to add lazy-rendering to Dialog.Portal or any other components). It's impossible to predict many use-cases but from primitive I expect it to be a minimal building block for building more complex components that covers user's use-cases.

I understand that users still can wrap it in their own context and sync it with the internal context but I think it unnecessary complicates everything.

Dialog already exposes `createDialogScope` which I think is something internal and it's not documented anywhere. It could be the same for `useDialogContext`.

Anyway thank you for the quick replies. I'm going to introduce my own context and wrap in it Dialog for my use-cases. I think it can be closed then.

**Comment by jjenzz** [comment]
> I understand that users still can wrap it in their own context and sync it with the internal context but I think it unnecessary complicates everything.

if the available props do not provide enough for you to create your customisations in a way that you consider appropriate, then by all means, keep this open as a request to improve the DX **somehow**. exposing context isn't the only solution.

> Dialog already exposes `createDialogScope` which I think is something internal and it's not documented anywhere. It could be the same for `useDialogContext`.

that is reluctantly exposed for [scoping](https://github.com/radix-ui/primitives/discussions/1091). if it wasn't for this issue it wouldn't be exposed at all. we [created an RFC for the react team](https://github.com/facebook/react/issues/23287) to request that they consider solving this as part of the framework instead.

> Anyway thank you for the quick replies. I'm going to introduce my own context and wrap in it Dialog for my use-cases. I think it can be closed then.

i still think it would be helpful to raise a bug for the team about your scrollbar case. that is likely an a11y issue that the team should fix.

**Comment by lesha1201** [comment]
@jjenzz,

> my pleasure. i still think it would be helpful to raise a separate bug for the team about your scrollbar case tho. that is likely an a11y issue that the team should fix as part of the primitive.

There is already an issue on Github for that https://github.com/radix-ui/primitives/issues/1280

> keep this open as a request to improve the DX somehow.

I'm reopening the issue then but feel free to close it when you want.

**Comment by benoitgrelard** [comment]
Hi @lesha1201,

I'll close this issue and we'll take a look at #1280
