### ISSUE TITLE
[Toast] Viewport TS error when adding children and `asChild`

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#1284]
## Bug report

the toast viewport has removed the `children` prop from its types.

### Current Behavior

i get a TS error If `asChild` is used and children are added.

### Expected behavior

no TS error when `asChild` is used.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/hopeful-minsky-yfi08l?file=/src/App.tsx)

### Suggested solution

perhaps the simplest solution for now is just to allow children. I don't think there was a strong enough reason why i prevented this.

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Yeah I agree with this. I'll do a quick PR.
