### ISSUE TITLE
FocusScope appears to be causing issues with Cypress tests

### ISSUE THREAD

**Issue by SimeonC** [radix-ui/primitives#1288]
### Current Behavior

When running tests in cypress and the window is not focused, the FocusScope component of the Dialog causes mis-typing. I have realised that this doesn't occur when running headless, or when the browser is focussed so it might not be an issue worth fixing. But it did take me a very long time to figure this out so I thought I'd post in case someone else is facing the same issue.

https://user-images.githubusercontent.com/1085899/160962357-6b6d9c4a-5155-4d4b-af64-70554deb36bb.mp4

### Expected behavior

Cypress should work fine when typing in modals.

### Reproducible example

1. clone and install from https://github.com/SimeonC/cypress-test-tiny/tree/type-clear-bug

2. run `npm test` to launch cypress.

3. Launch `spec.js`

4. Open `spec.js` in editor of choice, edit and save the file to trigger a cypress rerun - do not focus the cypress window. If the window is focussed it passes.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | @radix-ui/react-dialog | 0.1.7 |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by SimeonC** [comment]
Hi @benoitgrelard. `FocusScope` was just my guess - maybe more accurate to say it's the modal dialog implementation.

You're right that if the fields are empty it works, but for my case that's not an option as we are editing a record in a field so not only a blank form, but editing previously saved content also has to be supported.

My workaround now is to make sure I run the tests with the window focused or in headless mode which doesn't have the issue.

**Comment by benoitgrelard** [comment]
Unfortunately this may be browser based behaviour and not something we have control over.
We call `.focus()` and `.select()` in the inputs when autofocusing.

That said, the initial one seems to work correctly as I can see in the video, so perhaps it's when you focus your second input, you need to make sure you select the text too to ensure you override it, seeing as the browser might not do it for you when the window is unfocused.

**Comment by benoitgrelard** [comment]
>  I have realised that this doesn't occur when running headless, or when the browser is focussed so it might not be an issue worth fixing.

As you've pointed out, this isn't really an issue with the library but rather specific test conditions/environment.
Therefore, we'll close the issue.
