### ISSUE TITLE
[Select] Parent element loses focus-within when select is opened

### ISSUE THREAD

**Issue by peerjollux** [radix-ui/primitives#1291]
## Bug report
When the Select component is opened, the ancestors of the component loses :focus-within. It's caused because Select.Content is rendered in a portal. 

### Current Behavior & Expected behavior
In the following screen recording (and example below) the behaviour of the native select and radix Select are demonstrated. 
https://cln.sh/hduluW

### Reproducible example

[Example](https://codesandbox.io/s/busy-easley-ccjnf5?file=/src/App.tsx:0-1721)

### Suggested solution
It's a tricky problem, since I understand why Select.Content is rendered in a portal. I'm not really sure what the best solution would be.

| Software                 | Name(s)               | Version   |
| Radix Package(s)   | Radix-select        | 0.1.1        |
| React                       | N/A                       |                |
| Browser                   | Chrome               |                 |

**Comment by benoitgrelard** [comment]
Hi @peerjollux,

Exactly as you mention, it's not really a bug, but instead does make sense given the position in the DOM.
Do you have a real use case for this or are you just pointing out the quirk?

**Comment by peerjollux** [comment]
You are right, I wasn't really sure which issue type to choose. I picked bug since I was in the understanding Radix would like to mimic the behaviour of native elements.

Anyhow, yes we actually do have a real use case for this. That also how I found out about the quirk. I created a sandbox example to show our use case. As you can see we use the `:focus-within` pseudo class to show/hide a tip next to our input fields. 

https://codesandbox.io/s/mystifying-cray-82dhhv?file=/src/App.tsx

**Comment by benoitgrelard** [comment]
Hi @peerjollux,

Thanks for providing your use case.

Showing a tip this way will be inaccessible. You should use the `Tooltip` primitive for that so make it accessible.
Incidentally it will also resolve your issue.

Separately, if you what you were trying to achieve was closer to your first example above, ie. purely for styling reasons, you could control the `Select` using the `open` and `onOpenChange` props and do something like this:

```tsx
const [open, setOpen] = React.useState(false);
…
<div className="container" data-state={open ? 'select-open' : undefined}>
  <Select open={open} onOpenChange={onOpenChange}>
    …
  </Select>
</div>
```

```css
.container:focus-within, .container[data-state="select-open"] {
  background-color: tomato;
}
```
