### ISSUE TITLE
Avatar be a DropdownMenu.Trigger

### ISSUE THREAD

**Issue by igortullio** [radix-ui/primitives#1295]
### Overview

If possible use the Avatar component as DropdownMenu.Trigger.

### Who does this impact? Who is this for?

Enable to use Avatar as a Dropdown, like to open user menus. This is for all users.

**Comment by jjenzz** [comment]
this is possible by composing the two primitives https://codesandbox.io/s/priceless-hermann-z78qsg?file=/src/App.js
