### ISSUE TITLE
[Select] Item focus thrashing when rendered within `Dialog` / `FocusScope` based primitive

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/primitives#1296]
### Current Behavior

When using `Select@0.1.1` with `Dialog <= 0.1.5` the two primitives appear to fight for focus control when mouse moving though items, this will eventually cause a browser hang though is much more pronounced in FireFox.

### Expected behavior

Item should be the sole recipient of focus providing the pointer is moving over it.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/objective-brattain-u0gpvp?file=/src/App.js)

### Suggested solution

No solution yet, though an observed fix is to update `Dialog` or other `DismissableLayer` based components to latest version

**Comment by benoitgrelard** [comment]
This is the same issue as #1088 with `DismissableLayer`.
Instead of trying to solve the issue, we should rather improve DX to surface it via an error/warning and give a potential resolution (ie. update the latest).
