### ISSUE TITLE
[Select] Inability to stop Escape keyDown propagation

### ISSUE THREAD

**Issue by suevalov** [radix-ui/primitives#1299]
## Bug report

If there's a keydown handler defined above select component, there's no way to prevent event propagation when Escape is pressed but keep closing the select as expected.

See reproducible  [CodeSandbox example](https://codesandbox.io/s/zealous-http-637vsc?file=/App.js:3109-3733)

### Current Behavior

The only way to prevent event propagation is to define

```jsx
<Box onKeyDown={(e) => {
   if (e.key === "Escape") {
      console.log("this should not be called");
   }
}}>
  <Select>
    ...
    <SelectContent
       onKeyDown={(e) => {
          if (e.key === "Escape") {
            // propagation stopped and Box onKeyDown is not called
            // but Select is not closed either
            e.stopPropagation();
          }
        }}
    />
    ...
  </Select>
</Box>
```

but it breaks "close select when Esc is pressed" fuctionality. 

### Expected behavior

I can prevent Box onKeyDown event from being called, but still keep closing Select when Esc is pressed.

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/zealous-http-637vsc?file=/App.js:3109-3733)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-select       |  0.1.1      |
| React            | n/a     |  17.x        |
| Browser          |         |   Chrome      |

**Comment by jjenzz** [comment]
> there's no way to prevent event propagation when Escape is pressed but keep closing the select as expected.

that's correct because the escape key listener for close functionality is on the `document` because the content shouldn't require focus to be closed via escape keypress.  therefore, if you stop propagation you are preventing the event from reaching the document.

**Comment by suevalov** [comment]
@jjenzz thanks for explanation

We have global shortcuts in our application (👋🏼  from Linear) and the listeners are also set on the `document`. In many cases "Esc" closes the current view and goes to a previous one, so when the select is opened - we want to close the select but prevent all other global "Esc" handler from being called.

One of the solutions is to prevent propagation and programmatically call `context.onOpenChange(false)`, but right now there's no way to get context in application's code. I think it wouldn't hurt to export `useSelectContext`. What do you think?

**Comment by benoitgrelard** [comment]
Hi @suevalov (and 👋 Linear!)

Here are a couple ideas I can think of:
- You could control the `Select` and  set `open` to false when you want to force it then.
- Another thing you could do potentially could be to add a generic attribute to things you want to ignore and add a condition in your global shortcut handler to discard events originating from such targets.

**Comment by suevalov** [comment]
@benoitgrelard these are good ideas, thanks for sharing. I'll explore these possibilities

**Comment by suevalov** [comment]
So, I solved the problem with a generic attribute that I added to SelectContent and SelectOption components, this an event is targeted from these elements it gets skipped in a global shortcut handler.

So, the new Select is coming to Linear. We already use Tabs component and more to come. Thanks for an amazing library.

**Comment by benoitgrelard** [comment]
Thanks for the love ♥️

**Comment by MESSELMIyahya** [comment]
Hello see this 

![image](https://github.com/user-attachments/assets/93da7685-0700-43e2-9ba6-915d7d3c385a)

Add this prop :
```ts
 onEscapeKeyDown={(e) => {
      e.preventDefault();
  }}
```
