### ISSUE TITLE
[Select] Content does not line up with trigger when styled with padding

### ISSUE THREAD

**Issue by WDeenik** [radix-ui/primitives#1312]
### Current Behavior

When adding padding to the SelectContent, the content is misaligned by the same amount with the trigger.

### Expected behavior

The content opens up perfectly aligned to the trigger, just like when SelectContent doesn't have any padding

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/thirsty-dan-bjgu2k)

### Suggested solution

I see the code should take padding in account, but somehow it doesn't happen in practice. Does it get styling from the wrong element? Or maybe it retrieves the styling at the wrong moment? https://github.com/radix-ui/primitives/blob/main/packages/react/select/src/Select.tsx#L460

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   react-select      |     0.1.1    |
| React            | n/a     |    18.1.0     |
| Browser          |     Chrome    |    99.0.4844.84     |
| Assistive tech   |    n/a     |   n/a      |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    MacOS     |         |

**Comment by benoitgrelard** [comment]
Hi @WDeenik,

Thanks for reporting this.
Hmm, that is strange as I am sure I took care of this case and as you point out we do take it into account in the calculations.
I will need to investigate to figure out what happened.

**Comment by WDeenik** [comment]
Looking into the code and the structure it seems like `itemOffset` contains the offsetTop to the wrapping div of the items, not the offset to the content. However, the calculation of `contentTopToItemMiddle` seems to assume it is the offset to the top of the content element. It needs to add the top padding there https://github.com/radix-ui/primitives/blob/main/packages/react/select/src/Select.tsx#L470

**Comment by benoitgrelard** [comment]
> Looking into the code and the structure it seems like `itemOffset` contains the offsetTop to the wrapping div of the items, not the offset to the content. However, the calculation of `contentTopToItemMiddle` seems to assume it is the offset to the top of the content element. It needs to add the top padding there https://github.com/radix-ui/primitives/blob/main/packages/react/select/src/Select.tsx#L470

Haha snap, I found the issue, I think we omitted this when we changed the position algorithm.

Thanks again!

**Comment by WDeenik** [comment]
Thanks for the quick fix! 🙌  😄

**Comment by benoitgrelard** [comment]
That's now available in the latest rc: [0.1.2-rc.2](https://www.npmjs.com/package/@radix-ui/react-select/v/0.1.2-rc.2)
