### ISSUE TITLE
[Select] How to implement a searchable Select ?

### ISSUE THREAD

**Issue by MaximeConan** [radix-ui/primitives#1334]
## Question

Hello to all,

I would like to migrate my select component from `react-select` to `@radix-ui/select`. 

However I feel that the ability to easily integrate a search function does not seem to be available in the existing implementation of the component.

Has anyone looked into this yet? Or is there another primitive I haven't seen that would do the trick?

Thanks in advance, and thanks for the great work from the Radix team!

**Comment by VilfredSikker** [comment]
It has typeahead and functionality like the native select. If you want a visible search field you would have to make a custom implementation as far as I know.

**Comment by benoitgrelard** [comment]
Hey @MaximeConan, what you are suggesting here is a Combobox, I've added a ticket for us to track and for people to show interest. #1342

**Comment by MaximeConan** [comment]
Exactly, thanks @benoitgrelard !
