### ISSUE TITLE
Radio group can't unset

### ISSUE THREAD

**Issue by aungbobotun** [radix-ui/primitives#1336]
### Current Behavior

https://user-images.githubusercontent.com/97866786/164419926-339c74c9-3f58-43a4-8a6f-53b352a2624e.mp4

### Expected behavior

https://user-images.githubusercontent.com/97866786/164420015-401f9f1d-2b5c-464d-9a5c-c4dc0cd9334d.mp4

A user accidentally clicked the **Gender** and then decide not to give info. He should be able to unset the radio by clicking on the select item again. (Gender is optional input)

### Suggested solution

This can't be even handled with a controlled component too because `onValueChange` is not triggered when the selected radio item is clicked. **So the main problem is `onValueChange`  not  triggered when clicking on the selected item.**

### Additional context

It affects the user experience so much. The only way he can unset the value is by only reloading and enter the input from the beginning.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-radio-group      |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by jjenzz** [comment]
radios follow the same pattern as native `<input type="radio" />` which cannot be unselected https://codepen.io/jjenzz/pen/GRyeeKq

**Comment by aungbobotun** [comment]
But for a react-controlled component, the state should be handled by the programmer regardless of the WAI-ARIA behavior.  I think that is also one of the reasons why people love component libraries like React & Vue (Logic controls the UI completely). I think you guys are handling with `onChange` dom event. My behavior needs to toggle the state `onClick` dom event. I will close this issue.

Thank you.

**Comment by xixixao** [comment]
This is implementable via custom onClick handler.
