### ISSUE TITLE
Dialog title warning not displaying

### ISSUE THREAD

**Issue by hugotiger** [radix-ui/primitives#1348]
### Current Behavior
No warning is displayed when not passing rendering any dialog title

### Expected behavior
From my understanding not supplying a title to the dialog should render an error in development mode

### Reproducible example
https://codesandbox.io/s/radix-ui-dialog-missing-title-warning-jz14vc?file=/src/App.tsx

### Suggested solution
Not sure. From my (small) investigation in the PR (#1098) that introduced this warning I can't really see any problems

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-dialog    |    0.1.7     |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by hugotiger** [comment]
I suddenly got the warning, but can't reproduce it. No code changes in between so I figure something's out of sync. Hopefully it can help troubleshooting.

Also let me know if I can be of any help. I'd be glad to contribute to this package 😄

**Comment by benoitgrelard** [comment]
Hi @hugotiger, yeah we're aware of it, it's because our builds are minified so the checks are compiled away.
We're working on a solution here: #1332 so I'll close your issue now.

**Comment by hugotiger** [comment]
Awesome! Thanks for the explanation @benoitgrelard 👍
