### ISSUE TITLE
[Select] at page bottom with few items shows content at wrong position

### ISSUE THREAD

**Issue by Sanster** [radix-ui/primitives#1350]
### Current Behavior

react-elect at page bottom with few items shows select content at wrong position

<img width="225" alt="image" src="https://user-images.githubusercontent.com/3998421/165770289-f0b59ba8-b4ab-4877-b97d-c95087dd712d.png">

https://user-images.githubusercontent.com/3998421/165771940-d2041266-3781-424b-b8f8-cb7524a7635d.mov

### Expected behavior

<img width="209" alt="image" src="https://user-images.githubusercontent.com/3998421/165770428-a8aba7f9-15b2-4f55-95cf-01701c186c0e.png">

### Reproducible example

https://codesandbox.io/s/select-at-bottom-v41ehi

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   react-select      |    0.1.1     |
| React            | n/a     |    17.0.2     |
| Browser          |     chrome    |    98.0.4758.109     |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |     npm    |         |
| Operating System |    macOS     |   12.0.1 (21A559)      |

**Comment by benoitgrelard** [comment]
Hey @Sanster,

Thanks for reporting this, I can confirm the issue is present on our side.
I'll take a look at what's going on.

**Comment by andy-hook** [comment]
Noticed this doesn't occur when there are enough items to trigger content overflow.

**Comment by benoitgrelard** [comment]
Addressed here: #1355
