### ISSUE TITLE
useSize package crashes ResizeObserver in iOS 12

### ISSUE THREAD

**Issue by matheusrufinos** [radix-ui/primitives#1353]
### Current Behavior

When using Checkbox / Radio on iOS 12/13 (and older browser versions) because it uses [useSize](https://github.com/radix-ui/primitives/blob/main/packages/react/use-size/src/useSize.tsx) which implements `ResizeObserver`.

Because it is a "recent" implementation, older browsers, especially Safari in iOS 12, do not support ResizeObserver, causing a blank page when using Checkbox/Radio.
Some cases with Android 10 were also detected.

Reference: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#browser_compatibility

![Captura de Tela 2022-04-28 às 16 13 22](https://user-images.githubusercontent.com/38802787/165829326-87861415-75d9-4cc9-b887-ea4e157cd3de.png)
![Captura de Tela 2022-04-28 às 16 12 48](https://user-images.githubusercontent.com/38802787/165829318-b8e86193-8050-461f-9221-1785550a3e78.png)

### Expected behavior

That the page does not break and the user with older versions of devices/browsers can use the site normally.

### Suggested solution

Maybe implement a polyfill for ResizeObserver, like for example:
https://www.npmjs.com/package/@juggle/resize-observer

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-radio-group     |   0.1.15      |
| Radix Package(s) |   @radix-ui/react-checkbox    |   0.1.15      |
| React            | n/a     |    17.0.2     |
| Browser          |   Safari     |  12/13       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi @matheusrufinos we do not support these older versions.
Here's our support matrix:

```
browsers: 'Chrome >= 74, Safari >= 13.1, iOS >= 13.3, Firefox >= 78, Edge >= 79',
```
