### ISSUE TITLE
DropdownMenu - Non-portalled positioning broken when parent is position relative

### ISSUE THREAD

**Issue by mrudowski** [radix-ui/primitives#1365]
### Current Behavior

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/45997056/166314546-80d496b7-5b39-4d29-a626-178541eccd4e.png">

### Expected behavior

It should work despite the parent relative position

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/quizzical-shape-bwzqfg?file=/src/App.jsx)

### PS

I fall in love in "headless" libraries. Thank you!

**Comment by benoitgrelard** [comment]
Hi @mrudowski,

Thanks for reporting this.
We are already aware of it and are tracking it here: #370 so I'll close this as duplicate.

**Comment by mrudowski** [comment]
Oh, I'm sorry - I miss it... I even miss the last comment from the one I copy title from https://github.com/radix-ui/primitives/issues/1253 :(

**Comment by benoitgrelard** [comment]
No problem!
