### ISSUE TITLE
ToggleGroup.Item `asChild` does not work for custom components missing ref forwarding

### ISSUE THREAD

**Issue by charkour** [radix-ui/primitives#1369]
## Bug report
Using ToggleGroup.Item and padding a custom component will result in a TypeError when focusing to ToggleGroup with the keyboard.

`TypeError: Cannot read properties of null (reading 'focus')`

### Current Behavior

Here is a [stackblitz](https://stackblitz.com/edit/nextjs-sgsxsv?file=pages/index.js) with the issue. Using tab to focus the first ToggleGroup works fine, but the second ToggleGroup results in a TypeError. All ToggleGroup.Item components use the `asChild` prop. The first group has a `<button />` element as the child, and the second group items have a custom component as a child.

https://user-images.githubusercontent.com/33156025/166530302-29947a41-70c8-431d-8f48-61d60a8a41ae.mov

### Expected behavior

I would like to be able to use custom components as children to the ToggleGroup.Item component with the `asChild` prop.

### Reproducible example

[stackblitz](https://stackblitz.com/edit/nextjs-sgsxsv?file=pages/index.js). In the repro, I use the `Styled` in the component names to represent custom components that are likely to be used in a production application. Yes, they are missing custom styles, but this is the same component hierarchy used in prod apps. Thanks for understanding!

### Suggested solution

Haven't looked too deeply into the source code surrounding this issue. Right now the only workaround is to not use `asChild`.

### Additional context

N/A. Please request if needed. Happy to help.

### Your environment

Local env. Different from stackblitz. Issue is in both envs.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    react-toggle-group     |     0.1.5    |
| React            | n/a     |   17.0.2     |
| Browser          |    Chrome     |    100.0.4896.127     |
| Assistive tech   |     n/a    |         |
| Node             | n/a     |         |
| npm/yarn         |     npm    |    8.1.3     |
| Operating System |    macOS Monterey    |  12.3.1       |

Thanks for the awesome work!

**Comment by charkour** [comment]
Alright, I looked at the source code for [@radix-ui/react-collection](https://github.com/radix-ui/primitives/blob/main/packages/react/collection/src/Collection.tsx), and found that adding refForwarding is needed to solve my initial issue.

I've updated the [stackblitz](https://stackblitz.com/edit/nextjs-sgsxsv?file=pages/index.js) to include the reforwarding. This isn't a bug with the code, but the documentation I believe. What's the best way to update the documentation? Probably on the components that use roving focus. I'd be willing to make a PR. Thanks!

**Comment by benoitgrelard** [comment]
Hi @charkour,

It looks like you resolved your issue.
It's always a good idea with any leaf react component to forward all props and forward ref as they should act transparently like any native element.

With regards to the docs, we are tracking this here: https://github.com/radix-ui/website/issues/269. We're planning to create a dedicated page for `asChild` where we'll explain more about why you need to forward props/ref (which isn't different from using `as` prop btw).

Worth pointing out also, `asChild` is a replacement for `as`, so it's a bit strange to create your own `As` and use them both together.

**Comment by charkour** [comment]
Hi @benoitgrelard,

Thanks for the quick reply. The issue you linked I think would have helped me debug the issue. I'll be sure to ref forward when using the `asChild` prop. 

One thing to note about how my team is using the components: we use `asChild` in this context to simplify the DOM tree and we use the `as` prop to programmatically set the semantic element of the custom react component that is a child of the Radix component. We do this because we want to re-use the logic defined in the custom react component, but change the semantic meaning depending on the context it is used in. Is this an incorrect way to use the library? Seems like a clean solution for my team. 

Thanks for all the great work!

**Comment by benoitgrelard** [comment]
`asChild` can be used to change the semantic element too.
I guess it's probably a preference thing, effectively you want this:

```tsx
<StyledItem As={MyStyledButton}>One</StyledItem>
```

over this:

```tsx
<ToggleGroup.Item asChild>
  <MyStyledButton>One</MyStyledButton>
</ToggleGroup.Item>
```

They both work, I'm just not sure how much the extra abstraction is warranted.
With the extra `StyledItem`, it's an extra component you need to remember to forward props/ref.

Perhaps this is also a contrived example and in reality your `StyledItem` is more than what I see here too.

✌️

**Comment by charkour** [comment]
Thanks! I see what you're saying. And yes, my team right now prefers to use that first API. We'll see how the other one fairs.

Thanks again for taking the time to thoroughly review this non-issue. Cheers!
