### ISSUE TITLE
[Announce] Error -`document is not defined` when using with Next.js (SSR context.)

### ISSUE THREAD

**Issue by heyitsarpit** [radix-ui/primitives#1371]
### Current Behavior

When using `Announce` in Next.js SSR. I get the error `document is not defined`.

### Expected behavior

The component should render on the server and not throw any errors.

### Suggested solution

`ownerDocumentRef` is initialized with `document`
https://github.com/radix-ui/primitives/blob/8b012b7e1eab0033b73031d47051e92a816bd103/packages/react/announce/src/Announce.tsx#L102

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-announce    |     0.1.4    |
| React            | n/a     |     17.0.2    |
| Browser          |     Firefox    |     Firefox    |
| Assistive tech   |    n/a     |     n/a   |
| Node             | n/a     |     16.13.0    |
| npm/yarn         |   pnpm      |   6.24.4      |
| Operating System |    macOS     |     11    |

**Comment by benoitgrelard** [comment]
Hey @heyitsarpit,

We have been talking about deprecating it as part of the next release because it isn't used at all internally and isn't really a good fit with our model of having components more geared towards use-cases.

May I ask what you are using the component for?

🙏

**Comment by heyitsarpit** [comment]
@benoitgrelard, I used it for notifications and error announcements, I only used since Radix has it, otherwise I would not have considered the accessibility of these components. If it's being removed, that's not much of an issue for me.

**Comment by benoitgrelard** [comment]
Yeah so this is where more dedicated components might make more sense. For example we have `Toast`: https://www.radix-ui.com/docs/primitives/components/toast.

Would that cover your use-case?

**Comment by heyitsarpit** [comment]
>  For example we have Toast: 
A toast is not the most appropriate component for my use case.

For e.g. a warning box that pops in when some input parameters are off, and we need to be closer to input, so they're hierarchically close together. (I observed the error for a  different component, that was server rendered.)

<img width="331" alt="Screenshot 2022-05-20 at 5 51 32 PM" src="https://user-images.githubusercontent.com/18533307/169527310-0b401a65-3e31-409c-9d02-de01c6c431d7.png">

**Comment by benoitgrelard** [comment]
Yep, this is something we've discussed, that's more like form errors.
So on the same vain, it's likely we would create form primitives and we'd have `Form.Error` or something like that, which would handle the accessibility.

**Comment by benoitgrelard** [comment]
Closing down as we have now deprecated this package as discussed previously.
