### ISSUE TITLE
[Select] Hydration failed when controlling the value of the Trigger

### ISSUE THREAD

**Issue by iammola** [radix-ui/primitives#1377]
## Bug report
I wanted to control the value in the trigger, so I passed my value to the `Select.Value` as the docs say.
I load it in my browser and it flashes the controlled and the default content and then only the controlled one.
It reports a hydration mismatch as the UI changes on the client.

https://user-images.githubusercontent.com/55806855/167153439-69479ffa-1362-424a-acf4-d95c18b0b6c0.mov

### Expected behavior
I expect the Select Trigger to show only the content I pass to it without the Hydration error

### Reproducible example

[StackBlitz Editor](https://stackblitz.com/edit/nextjs-kcxu2x)

### Additional context

The value changes on first load. It's initialized with an empty string and on the client it's set to something else. When It changes, it shows the content of the selected item and the value it's meant to show in the trigger.

### Your environment

| Software         | Name(s)                | Version       |
| ---------------- | ---------------------- | ------------- |
| Radix Package(s) | @radix-ui/react-select | 0.1.1         |
| React            | n/a                    | 18.1.0        |
| Browser          | Chrome                 | 101.0.4951.54 |
| Assistive tech   | n/a                    |               |
| Node             | n/a                    | 18.0.0        |
| npm/yarn         | pnpm                   | 7.0.0         |
| Operating System | MacOS                  | 12.3.1        |

**Comment by andy-hook** [comment]
> It's initialized with an empty string and on the client it's set to something else

> Hydration failed because the initial UI does not match what was rendered on the server.

Looks expected given the fork in your `setState` call, is there a reason this needs to differ on the client?

**Comment by iammola** [comment]
> Looks expected given the fork in your `setState` call, is there a reason this needs to differ on the client?

Yeah, I try to get the user's locale, so I use `navigator.language` which is only available in the browser, so I just use an empty string and then set the state when I can access it.

I tried to reproduce my code without it being too complex, so I decided to use the football players.

**Comment by iammola** [comment]
I used an initial state that wasn't an empty string, and this time I don't get the hydration error, but the default trigger content still flashes.

https://user-images.githubusercontent.com/55806855/167230610-5ca450f9-6cdd-4517-985a-d7e6d6c35e63.mov

**Comment by andy-hook** [comment]
> Yeah, I'm trying to get the user's selected language. I'm using the browser's `navigator.language`.

Gotcha, to avoid server/client mismatch warnings you need to provide a deterministic initial value and update from `navigator` inside an effect:

https://stackblitz.com/edit/nextjs-kcxu2x-fy66me?file=pages%2Findex.jsx,styles%2Fglobals.css,pages%2Fapp.jsx

> but the default trigger content still flashes.

I’m not sure what’s happening without looking at the code, my hunch is your render logic is not right as it’s flickering between a `key` and `value` which seems incorrect given the object map in your original code.

Hopefully my example helps, as this doesn’t look like a problem with `Select` I’m going to close the issue. Feel free to follow up if you still have questions though!
