### ISSUE TITLE
[Popover] Feature request: expose usePopoverContext

### ISSUE THREAD

**Issue by bel0v** [radix-ui/primitives#1380]
Hi! I've got a use case when I need to trigger onOpenToggle() not with the provided `<Close />` button, but after some other user action within the popover.
If I understand it correctly, the easiest way would be to use the method from Popover's context, but unfortunately it's not exposed. Currently what I came up with is forcing Popover's re-render into closed state, which is meh.
Otherwise please point me to the right direction how can I achieve this with current API.

Thanks!

**Comment by benoitgrelard** [comment]
Hi @bel0v, the controlled API is perfect for these kind of use cases.
You can control the `Popover` by using the `open` and `onOpenChange` props just like you control any React form element for example. This will let you update that set from anywhere.
