### ISSUE TITLE
[Select] Render testing

### ISSUE THREAD

**Issue by DimaKelek** [radix-ui/primitives#1382]
## Bug report

When i try to test render of select component in attempting to using userEvent.click from @testing-library/user-event on Trigger i get -> TypeError: e.target.releasePointerCapture is not a function although the component works correctly when you start the project.

### Current Behavior

<img width="1184" alt="Screenshot 2022-05-10 at 10 38 09" src="https://user-images.githubusercontent.com/82117691/167575497-6876ba2b-b6a5-4e0a-8d18-bf80635e0dc8.png">

<img width="767" alt="Screenshot 2022-05-10 at 10 56 27" src="https://user-images.githubusercontent.com/82117691/167578290-d7d9bece-f5bd-4da2-9a60-084f9628305a.png">

### Expected behavior

Content should be render

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/select | 0.1.1 |
| React            | n/a     | 17.0.2|
| Browser          | Chrome | latest |
| Node             | n/a     | 16.13.2 |
| npm/yarn         | yarn | 1.22.17 |
| Operating System | macOS | monterey 12.3.1 |

**Comment by andy-hook** [comment]
You'll need to mock a few things as `jsdom` doesn't support several browser apis used in `Select` 

```ts
// setupTests.ts

// JSDOM doesn't implement PointerEvent so we need to mock our own implementation
// Default to mouse left click interaction
// https://github.com/radix-ui/primitives/issues/1207
// https://github.com/jsdom/jsdom/pull/2666
class MockPointerEvent extends Event {
  button: number;
  ctrlKey: boolean;
  pointerType: string;

  constructor(type: string, props: PointerEventInit) {
    super(type, props);
    this.button = props.button || 0;
    this.ctrlKey = props.ctrlKey || false;
    this.pointerType = props.pointerType || 'mouse';
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
window.PointerEvent = MockPointerEvent as any;
window.HTMLElement.prototype.scrollIntoView = jest.fn();
window.HTMLElement.prototype.releasePointerCapture = jest.fn();
```

You'll likely need most of the above depending on your setup. We plan to add more help to docs in the future but below are some additional threads you may find helpful:

https://github.com/radix-ui/website/issues/370

Hope this helps, i'm going to close this issue but feel free to follow up if you still have trouble.
