### ISSUE TITLE
Why should the `DialogPrimitive.Trigger` be part of the `Dialog`?

### ISSUE THREAD

**Issue by abhic91** [radix-ui/primitives#1383]
In the example here: https://codesandbox.io/s/496vvo?module=App.js&file=/App.js

```
<Dialog>
    <DialogTrigger asChild>
      <Button size="large">Edit profile</Button>
    </DialogTrigger>
    <DialogContent >
   ...
```

Why is the button to open the modal inside the actual dialog? I know there's a `open` prop to the root component, but that means stuff like `DialogPrimitive.DialogClose`, press `esc` key to close won't work and I have to do it myself.

I think there should be a different way to trigger the dialog and stuff like `esc` to close should still work

**Comment by benoitgrelard** [comment]
> Why is the button to open the modal inside the actual dialog? 

Hi @abhic91, this is necessary so that it can access the context provided by `Dialog.Root`.

> I know there's a open prop to the root component, but that means stuff like DialogPrimitive.DialogClose, press esc key to close won't work and I have to do it myself.

You don't have to do it yourself no. You just need to make sure to also wire the change handler. So if you want to control the dialog, you wire both `open` and `onOpenChange` props.

**Comment by abhic91** [comment]
@benoitgrelard  OK. Sorry for creating this. Should've checked the options more thoroughly.

**Comment by benoitgrelard** [comment]
No problem!
