### ISSUE TITLE
Height animation doesn't work for nested accordions

### ISSUE THREAD

**Issue by Temzasse** [radix-ui/primitives#1395]
### Current Behavior

By adding a nested accordion within another accordion the height is not animated correctly and the nested accordion is clipped by the content element.

### Expected behavior

In this [demo](https://codesandbox.io/s/vkwlb?file=/src/App.js) the height animations work as expected, however it is much older version of the accordion component.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/bold-water-s8ebf6?file=/App.js)

### Suggested solution

Maybe the `--radix-accordion-content-height` CSS variable can be kept in sync with the content height by using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-accordion     |   0.1.6      |
| React            | n/a     |    17.0.2     |
| Browser          |     Chrome    |     101     |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   macOS Monterey      |     12.3     |

**Comment by andy-hook** [comment]
Hey @Temzasse , this was fixed in https://codesandbox.io/s/cool-brook-m7sznz, if you use the [latest RC](https://www.npmjs.com/package/@radix-ui/react-accordion/v/0.1.7-rc.17) and remove `forwards` from the animation they should work as expected:

https://codesandbox.io/s/cool-brook-m7sznz
