### ISSUE TITLE
[Dialog] After dismissing the dialog on mobile, the next touch event is invalidated

### ISSUE THREAD

**Issue by just-learning-1** [radix-ui/primitives#1398]
### Reproducible example AND behavior explanation

I created a page which reproduces and explains the problem here: https://just-learning-1.github.io/minimal-repros/radix-dialog-mobile-eats-first-pointer-event-after-dismiss

### Suggested solution

Please help me understand what I'm doing wrong :-(

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog | 0.1.7 |
| React            | n/a     | 17.0.2  |
| Browser          | mobile OR enable Touch Emulation  |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | Mac, iOS, Android  |         |

**Comment by just-learning-1** [comment]
Assuming it's easier, I'm copying the steps I wrote in the page to here:

### Issue: Radix Dialog on Mobile eats first pointer event after dismiss

1. View the source code for this page [here](https://github.com/just-learning-1/minimal-repros/blob/master/src/pages/radix-dialog-mobile-eats-first-pointer-event-after-dismiss.page.jsx)
2. Open this page in a mobile browser or in Firefox with Touch Emulation enabled
3. Tap the following button to open the Radix UI Dialog: `#1: First tap after dismiss is eaten` (see [page](https://just-learning-1.github.io/minimal-repros/radix-dialog-mobile-eats-first-pointer-event-after-dismiss) for actual button)
4. After dismissing the dialog, try tapping the same (or a different) button again
5. **Result:** The first tap after dismissing the dialog is stolen!
6. **Investigation:** I discovered the following is still set on the body tag after dismiss until the next tap is received:
`<body style="pointer-events: none;">`
7. **However!** If I change the implementation of DialogContent from this:

```js
// from this page
<Dialog>
  <DialogTrigger asChild>
    <button type="button">
      Tap Me, then Tap Me Again after dismissing the dialog
    </button>
  </DialogTrigger>
  <DialogContent>
    Now dismiss this dialog, then try tapping the earlier button again
  </DialogContent>
</Dialog>

// from Dialog.jsx
export const DialogContent = React.forwardRef(({ children, ...props }, forwardedRef) => (
  <DialogContentContainer {...props} ref={forwardedRef}>
    <DialogHeaderBar>
      <CloseButton aria-label="close" asChild>
        <button type="button">
          Dismiss
        </button>
      </CloseButton>
    </DialogHeaderBar>
    <DialogContentBody>
      {children}
    </DialogContentBody>
  </DialogContentContainer>
))
```

To this:

```js
// from this page
<Dialog>
  <DialogTrigger asChild>
    <button type="button">
      Here is a second button whose pointer event also gets eaten
    </button>
  </DialogTrigger>
  <DialogPrimitive.Content style={{ /* ... */ }}>
    <DialogPrimitive.Close asChild>
      <button type="button">Dismiss</button>
    </DialogPrimitive.Close>
    Now dismiss this dialog, then try tapping the earlier button again
    </DialogPrimitive.Content>
</Dialog>
```

Like so: `#2: Stolen tap is fixed! But I do not understand why` (see [page](https://just-learning-1.github.io/minimal-repros/radix-dialog-mobile-eats-first-pointer-event-after-dismiss) for actual button)
8. The problem goes away! The first tap after dismiss is not invalidated.
9. Only difference is the second version swaps a `React.forwardRef` styled version of the Dialog Content element with the `DialogPrimitive.Content` element directly
10. The curious thing is, the implementation of the first dialog is modeled almost identically to the **Radix UI Design System Dialog**. Compare the two Dialog implementations:
    - [radix-ui/design-system/.../Dialog.tsx](https://github.com/radix-ui/design-system/blob/master/components/Dialog.tsx)
    - [just-learning-1/minimal-repros/.../Dialog.jsx](https://github.com/just-learning-1/minimal-repros/blob/master/src/base/Dialog.jsx)
11. I am new to coding, and I cannot for the life of me figure out why this is happening :(

**Comment by just-learning-1** [comment]
After further investigation, I think it must be linked to the **exit animation** I added to the dialog.

If I comment out just the exit animation of the dialog, as I do in the code snippet below, the `style="pointer-events: none;"` attribute gets properly removed from the `<body>` tag after the dialog dismisses:

```js
// Dialog.jsx
const slideIn = keyframes({
  from: { transform: 'translate3d(0%,100%,0)' },
  to: { transform: 'translate3d(0%,0%,0)' },
})
const slideOut = keyframes({
  from: { transform: 'translate3d(0%,0%,0)' },
  to: { transform: 'translate3d(0%,100%,0)' },
})
const slideInDesktop = keyframes({
  from: { transform: 'translate3d(-50%,50%,0)' },
  to: { transform: 'translate3d(-50%,-50%,0)' },
})
const slideOutDesktop = keyframes({
  from: { transform: 'translate3d(-50%,-50%,0)' },
  to: { transform: 'translate3d(-50%,50%,0)' },
})
const DialogContentContainer = styled(DialogPrimitive.Content, {
  backgroundColor: '#ffffff',
  borderRadius: '0px',
  boxShadow: 'hsl(187 22% 7% / 35%) 0px 10px 38px -10px,'
             + 'hsl(187 22% 7% / 20%) 0px 10px 20px -15px',
  height: '100vh',
  left: '0%',
  maxWidth: '100vw',
  minWidth: '200px',
  position: 'fixed',
  top: '0%',
  width: '100%',
  zIndex: '101',
  '&:focus': { outline: 'none' },
  '&[data-state="open"]': {
    animation: `${slideIn} 500ms cubic-bezier(0.22, 1, 0.36, 1),`
               + `${fadeIn} 500ms cubic-bezier(0.22, 1, 0.36, 1)`,
  },
  // '&[data-state="closed"]': {
  //   animation: `${slideOut} 500ms cubic-bezier(0.22, 1, 0.36, 1),`
  //              + `${fadeOut} 300ms cubic-bezier(0.22, 1, 0.36, 1)`,
  // },
  willChange: 'transform',

  '@desktop': {
    borderRadius: '12px',
    height: 'auto',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    maxWidth: '85vw',
    width: '75%',
    '&[data-state="open"]': {
      animation: `${slideInDesktop} 500ms cubic-bezier(0.22, 1, 0.36, 1),`
                + `${fadeIn} 500ms cubic-bezier(0.22, 1, 0.36, 1)`,
    },
    // '&[data-state="closed"]': {
    //   animation: `${slideOutDesktop} 500ms cubic-bezier(0.22, 1, 0.36, 1),`
    //             + `${fadeOut} 300ms cubic-bezier(0.22, 1, 0.36, 1)`,
    // },
  },
})
```

Am I adding the exit animation incorrectly? Or is this indeed a bug where adding an exit animation to the Dialog causes the issue?

**Comment by benoitgrelard** [comment]
Hi @just-learning-1,

You are correct this is a bug and it's already tracked here #1241 so I'll close yours as a duplicate.
I am actually working a fix at the moment so it shouldn't be too long.
