### ISSUE TITLE
[Dropdown] Position fixed parent makes the container render too far away from the trigger

### ISSUE THREAD

**Issue by RodolfoSarkisRocha** [radix-ui/primitives#1402]
### Current Behavior

When inside a `position: fixed` parent, the container of the dropdown goes a little bit too much away from the trigger as seen on the screenshot.

![image](https://user-images.githubusercontent.com/55035047/168656222-3d752dac-460c-4672-8102-d8962948261f.png)

### Expected behavior

The container should be right below the trigger, since no offset property is set.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-dropdown-menu | 0.1.6 |
| React            | n/a     | 16.9.1 |
| Browser          | Google Chrome | 101.0.4951.41 (Official Build) (64-bit) |

**Comment by benoitgrelard** [comment]
Hi @RodolfoSarkisRocha, we are aware of the issue and are already tracking it here: #370, #781.
I will close this one as a duplicate.

✌️

**Comment by RodolfoSarkisRocha** [comment]
Oh, sorry about that and thanks for the awesome job!
