### ISSUE TITLE
[DropdownMenu] Escape key exits fullscreen on Firefox & Safari

### ISSUE THREAD

**Issue by cpmsmith** [radix-ui/primitives#1420]
### Current Behavior

* Enter fullscreen mode
* Open dropdown menu
* Press escape
* Menu closes and browser exits fullscreen mode

### Expected behavior

Menu closes, browser remains in fullscreen mode

### Reproducible example

Reproducible on the [basic demo](https://www.radix-ui.com/docs/primitives/components/dropdown-menu) on Radix's site, or [this CodeSandbox](https://codesandbox.io/s/confident-goldstine-ctqfd4?file=/src/App.tsx)

### Suggested solution

Presumably, `preventDefault` isn't being called somewhere when it should be.

### Additional context

This works in Chrome, and is definitely possible—it works correctly in other libraries, e.g. [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/Menu.html). Also, Dropdown Menu is the first component on which I noticed this, but it affects many components: Alert Dialog, Context Menu, Dialog, Navigation Menu, Popover, Select, and Tooltip. I'm guessing that means the issue actually lies in DismissableLayer.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | `react-dropdown-menu` | 0.1.6 |
| React            |      | 17.0.1 |
| Browser          | Firefox | 100.0.2 |
|  | Safari | 15.4 |
| Node             |      | ? |
| npm/yarn         |         | ? |
| Operating System | macOS | 12.3.1 |

<small>Note: I'm not sure what version of npm/Node CodeSandbox is using, but I don't think it's relevant. </small>

**Comment by benoitgrelard** [comment]
Hi @cpmsmith,

Thanks for reporting this. This is interesting!
The reason is works on Chrome is because `Escape` isn't the shortcut there so that makes sense.

We'll take a look!

✌️
