### ISSUE TITLE
Tree-shaking is broken in "next" release

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#1428]
https://github.com/radix-ui/primitives/discussions/1424

Following the above discussion, I was doing some testing around tree-shaking and it looks like the `@latest` is able to tree-shake a bit, but the `@next` isn't so we must have broken something.

I suspect perhaps it's got something to do to the parcel upgrade.

**Comment by andy-hook** [comment]
Might be worth entertaining a spike on parcel alternative if this ends up looking tricky to resolve at the tooling level (similar to https://github.com/radix-ui/primitives/pull/1332)

**Comment by benoitgrelard** [comment]
After some research, determined this is likely a change in Parcel2.
Opened an issue there: https://github.com/parcel-bundler/parcel/issues/8216

This section of the docs seems to suggest perhaps it isn't supported: https://parceljs.org/features/scope-hoisting/#side-effects

> However, if export * had been used instead, this would not be true because Parcel would not know what exports are available.

This comment also potentially hints at it: https://github.com/parcel-bundler/parcel/issues/4565#issuecomment-625504838
