### ISSUE TITLE
Tabs: Add `forceMount` prop

### ISSUE THREAD

**Issue by hipstersmoothie** [radix-ui/primitives#1442]
## Feature request

With https://github.com/radix-ui/primitives/pull/1346 animation support for tabs was implemented but the `forceMount` prop was not. For full animation support `forceMount` is needed

**Comment by andy-hook** [comment]
This was subsequently added in https://github.com/radix-ui/primitives/pull/1414, might need to bump your RC version if you don't have access to it.
