### ISSUE TITLE
Sub menus no longer close by pressing left arrow key (0.1.7-rc*)

### ISSUE THREAD

**Issue by farskid** [radix-ui/primitives#1443]
### Current Behavior

When using the context menu using a mouse, hovering over an item that contains a sub menu opens the sub menu, but looks like the focus is trapped inside the sub menu. Because of that, the main items in the context menu longer can be hovered, and the sub menu doesn't close when the mouse pointer leaves the sub menu.

When using the context menu using the keyboard, pressing the right key on an item that contains a sub menu opens the sub menu, but pressing the left arrow key no longer closes the sub menu.

### Expected behavior

Sub menus should close when the mouse pointer leaves the sub menu or by pressing the left arrow key.

### Reproducible example

[Reproduced in this sandbox](https://codesandbox.io/s/test-context-menu-vxt57j?file=/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     react-context-menu    |  0.1.7-rc.33       |
| React            | n/a    |   18.2.0      |
| Browser          |   Chrome      |   latest      |
| Operating System |     macOS    |    latest     |

**Comment by andy-hook** [comment]
Hi @farskid , this is due [to the move to explicit parts](https://github.com/radix-ui/primitives/pull/1394), submenus must now be created using `ContextMenu.Sub`, `ContextMenu.SubTrigger` and `ContextMenu.SubContent`:

https://github.com/radix-ui/primitives/pull/1396/files#diff-16ad50f846f67269b32899b8c81c31e6f8023362290917e6ad176a96e8410559R90-R113

Updating your sandbox to use `SubContent` solves the issue:

https://codesandbox.io/s/test-context-menu-forked-vzk2n4?file=/App.js

Though I'm wondering if there is something we could do to make this clearer, do you feel that needing to provide `SubContent` was less obvious when updating the other parts?

**Comment by farskid** [comment]
Thank you for explaining the reason @andy-hook 👍
