### ISSUE TITLE
[ContextMenu] Accidental focus theft from within Menu

### ISSUE THREAD

**Issue by Andarist** [radix-ui/primitives#1446]
### Current Behavior

It's an unfortunate race condition~ between a handler like:
```
onSelect={() => {
  inputRef.current.focus()
}}
```
and the "focus trap" that is set up in the ContextMenu through this `focusout` handler:
https://github.com/radix-ui/primitives/blob/285aa0837f2405a05e983fc8fffd55f4cc368b5e/packages/react/focus-scope/src/FocusScope.tsx#L87-L92

I'm not sure if there is actually any way to solve this problem on your side because you can't remove those listeners before my code tries to call `inputRef.current.focus`. However, maybe a documentation for this should be added somewhere? It would be nice if some FAQ/gotchas could be found in the docs.

### Expected behavior

It would be nice if this gotcha would be documented somewhere.

However, I still believe that there is some issue in the code that you have here - I just don't have a concrete, real-life, repro case for this...

I think that because a custom event is involved here we often end up causing double render - one comes from the custom event that is wrapped with `flushSync` and one can be created **afterwards** when you conditionally close the menu. This is actually closer to the original case that I have found in my code because an effect that was focusing the input was flushed before you were removing the mentioned `focusout` handler but I think that using an effect there was a problem in our code and that this particular focus call should just be called directly from the `onSelect` handler - so I'm not sharing that as a compelling example for the "broken" behavior.

The Radix code I'm talking about is here:
https://github.com/radix-ui/primitives/blob/285aa0837f2405a05e983fc8fffd55f4cc368b5e/packages/react/menu/src/Menu.tsx#L599-L611

Notice how `dispatchDiscreteCustomEvent(...)` and `rootContext.onClose()` are not "wrapped" together and thus they will end up creating 2 renders.

### Reproducible example

[CodeSandbox repro](https://codesandbox.io/s/interesting-fire-t0onwu?file=/src/App.js:1643-2047)

**Comment by benoitgrelard** [comment]
Hey @Andarist,

Yeah this all makes sense given item selection is what will cause the menu to close, subsequently moving focus.
This is the way we generally recommend handling this:

https://codesandbox.io/s/contextmenu-custom-focus-on-action-28e6cl?file=/src/App.js

What's really nice about it is that it ties in the need to prevent default to the custom focus need in one fell swoop.

**Comment by Andarist** [comment]
> What's really nice about it is that it ties in the need to prevent default to the custom focus need in one fell swoop.

Hm, it's nice that it eliminates potential timing issues as much as possible here. OTOH, it introduces a little bit more boilerplate to the code (we need to introduce and manage the `focusRef`).

**Comment by benoitgrelard** [comment]
We are going to stick with what we have as we prefer the explicit nature of it.
Thanks for raising though @Andarist, we always appreciate your contributions 🙏

**Comment by Andarist** [comment]
Note that [the proposed solution](https://codesandbox.io/s/contextmenu-custom-focus-on-action-28e6cl?file=/src/App.js) gets hard to implement when you split your items and context menu between components.

We have a `ContextMenu` component that wraps your stuff and it accepts menu options as children. So the `onSelect` actions are defined in the component that renders that `ContextMenu`. That component can implement your suggestion but it would be nice if we could implement something in the `ContextMenu` itself. This becomes challenging though because there is no clear way to relate the menu option's action that comes from the parent with the `onCloseAutoFocus` handler living in the `ContextMenu`.

**Comment by Andarist** [comment]
We have yet another issue caused by this. This time we need to call `.focus()` from within a React effect that gets called from within the `flushSync` that you apply over custom event dispatches. It's very hard to coordinate the place in which `.focus()` is called with the `ContextMenu` and, currently, I have no idea how to do this properly. The problem is that the element that I want to focus on is far away in React/DOM tree + it doesn't exist at the time that `onSelect` gets called.

I guess I could use a singleton module and "track" the "context" of responding to `onSelect` by assigning a flag in `onSelect` and resetting it in `onCloseAutoFocus` but that's on top of tracking a focus ref and a bunch of other things (+ it would be using a singleton module which I feel that it could be avoided here).

I'm not sure what's the best solution here - but the proposed workaround feels a little bit brittle and complex. I wonder if we could try to revisit this issue.

**Comment by BrianHung** [comment]
Ran into this issue when I use a context menu to create a new item that should be focused on mount. Old item is being focused instead as it was the last focused item.

**Comment by danielmarcano** [comment]
Just ran into this issue. Had encountered the proposed solution mentioned here as a response to other closed issues, but thought it was actually too verbose and indeed hard to apply when we have separate menu and item components, as mentioned by @Andarist, which is exactly my case.

In that case, I guess I will use the good-old `setTimeout` trick, which is working for me, and leave a comment pointing to this closed issue.

```ts
setTimeout(() => input.current.focus(), 1);
```

Awesome library, although I think there should be a way to support this focus use-case, as it is pretty common.
