### ISSUE TITLE
[NavigationMenu] Flickering in React 18

### ISSUE THREAD

**Issue by sannajammeh** [radix-ui/primitives#1451]
### Current Behavior

Flickering randomly in Next.js using React 18 and regular standalone React 18. Can't seem to constantly reproduce it, but it happens quite frequent

https://user-images.githubusercontent.com/50969683/172441164-362d2217-f8f5-43ff-b1f7-dc313b325beb.mp4

Here is when it happens:
React 18 createRoot: Flickers on tab change, mouse exit viewport
React 18 legacy: No flicker
React 18 With animation-fill-mode = forwards: No Flicker on changing menus
React 18 With animation-fill-mode = forwards (Viewport): Flickers

### Expected behavior

Shouldn't flicker at all.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/jolly-johnson-9t92ws?file=/index.js)

### Additional context

Possibly related to: #1074 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-navigation-menu  | ^0.1.2 |
| React            | n/a  | 18.1.0 |
| Browser          | Chrome  | 101 |
| Assistive tech   |         |         |
| Node             | n/a     | 17 |
| npm/yarn         | pnpm  | 7  |
| Operating System | Windows | 10  |

**Comment by sannajammeh** [comment]
There is also this double flickering when the mouse leaves, also in React 18 only.
https://user-images.githubusercontent.com/50969683/172444314-7955f0ec-9cb9-457d-a85e-5442b4b4c8dc.mp4

**Comment by benoitgrelard** [comment]
Hey @sannajammeh, we have fixed a host of React 18 issues already but haven't published stable versions yet.
Can you try your demos with the latest release candidate instead?

**Comment by sannajammeh** [comment]
Just did! Works without an issue. Thanks for the response!

**Comment by Crocsx** [comment]
@benoitgrelard Sorry to bump a closed issue, just wondering if you have a planned schedule for react 18 fixes. We have a few issue in our app that are resolved by the RC, but we not confident in using it in production without changelogs.

**Comment by benoitgrelard** [comment]
Hi @Crocsx,

The release is imminent now: https://github.com/radix-ui/primitives/milestone/1 so the RCs can be considered as stable as they will be the ones promoted to `latest`.

In terms of the changelog, you can see it here on the preview for the docs: https://radix-website-git-release.modulz-deploys.com/
