### ISSUE TITLE
Tooltip is misplaced in Chrome extension's content scripts

### ISSUE THREAD

**Issue by yudai-nkt** [radix-ui/primitives#1454]
### Current Behavior

Tooltip is incorrectly positioned against its trigger when it is used in a Chrome extension's content scripts.

![スクリーンショット 2022-06-08 23 15 55](https://user-images.githubusercontent.com/13291527/172639567-2136d6c5-03d7-4c6f-ab6d-97b86431cf21.png)

Source code for the content script shown in the above:

```tsx
import * as RadixTooltip from "@radix-ui/react-tooltip";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

const tooltip = document.createElement("div");
tooltip.id = "tooltip";
document.body.append(tooltip);

const App = () => (
  <RadixTooltip.Root open>
    <RadixTooltip.Trigger>Trigger</RadixTooltip.Trigger>
    <RadixTooltip.Content>Content</RadixTooltip.Content>
  </RadixTooltip.Root>
);

createRoot(tooltip).render(
  <StrictMode>
    <App />
  </StrictMode>
);
```

### Expected behavior

Tooltip should be placed in the default location because neither `side`, `sideOffset`, `align`, nor `alignOffset` is specified.

### Reproducible example

CodeSandbox won't help because this problem is about Chrome extension. If I succeed in reproducing this as a normal web app, I'll update this issue and provide a CodeSandbox link.

Meanwhile, I prepared a repository for reproduction: https://github.com/yudai-nkt/radix-tooltip-repro. Please follow the reproduction steps below:

1. Clone the repository and build the extension

```console
git clone git@github.com:yudai-nkt/radix-tooltip-repro.git
cd radix-tooltip-repro
npm ci
npm run build
```

2. Install the extension (this is explained [here](https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked) as well)
    - Go to chrome://extensions and enable developer mode in the top-right corner.
    - Click the "Load Unpacked" in the top-left and select the `dist` directory we built in the previous step.

3. Visit https://example.com/, and you will see the misplaced tooltip.

### Suggested solution

I'm afraid but I have no idea.

### Additional context

- The same problem happens with `@radix-ui/react-popper` (cf. `react-popper` branch of my reproduction), so the `getPlacementData` function in `@radix-ui/popper` might be the cause of this issue. This is what I have investigated so far.
- #367 and #370 might be related, but I'm not sure if they really are.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | `@radix-ui/react-tooltip` | `0.1.8-rc.39` |
| React            | n/a     | `18.1.0` |
| Browser          | Google Chrome | 102.0.5005.61 |
| Assistive tech   | n/a |         |
| Node             | n/a     | v16.13.1 |
| npm/yarn         | npm | 8.1.2 |
| Operating System | macOS | 10.14.6 |

**Comment by yudai-nkt** [comment]
> the new release candidate in which the tooltip isn't portalled by default as you now need to wrap the `Content` in a new `Portal` part.

This explains why setting `portalled` props to the `Content` component gives a compile error contrary to the documentation (and now I found [a preview](https://radix-website-git-release-portal-parts.modulz-deploys.com/docs/primitives/components/tooltip#portal)).

Your suggestion now fixes my problem. Thanks, @benoitgrelard!

**Comment by trankhacvy** [comment]
@yudai-nkt I got the same issue with `@radix-ui/react-dialog`. How do you resolve your issue?

**Comment by yudai-nkt** [comment]
@trankhacvy as you can see in this thread my issue was caused by a breaking change in RC. Yours is unlikely to be related to this, so you can [ask for a help](https://github.com/radix-ui/primitives/discussions/new?category=help) in Discussions with a minimal reproduction (or open an new issue if you believe it's a Radix's bug)
