### ISSUE TITLE
[DropdownMenu] DropdownMenu doesn't locate properly.

### ISSUE THREAD

**Issue by f312213213** [radix-ui/primitives#1464]
### Current Behavior
I'm using dropdown menu for my i18n options. However, in big screen the menu doesn't located properly by default.
![Screen Shot 2022-06-11 at 12 53 38](https://user-images.githubusercontent.com/71749524/173173206-cb15e960-8552-4aa2-a017-aad8093f2e12.png)

### Expected behavior
I think the menu should locate like this by default. (I'm now using tailwind class 'sm:-top-8' to fix this)
![Screen Shot 2022-06-11 at 12 55 47](https://user-images.githubusercontent.com/71749524/173173277-d3a48dcb-2b15-4abf-9c2e-d966bb5e04fc.png)

### Suggested solution

Maybe add some css like -top-8?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    react-dropdown-menu     |   0.1.6      |
| React            | n/a     |     18.1.0    |
| Browser          |     Microsoft Edge |   100.0.1185.29      |
| Assistive tech   |     TailwindCSS    |     3.0.24    |
| npm/yarn         |     npm    |   8.6.0      |
| Operating System |     MacOS Monterey    |     12.3.1    |

**Comment by LexSwed** [comment]
Adding simple reproduction in Codesandbox would help, there aren't other reported issues regarding the popup positioning: [Radix Dropdown Codesandbox](https://codesandbox.io/s/0h9ctf?module=App.js)

**Comment by benoitgrelard** [comment]
Hi @f312213213,

As @LexSwed suggested, it would be great if you could add a simple reproduction sandbox for us to look at.
It's very difficult to gauge what issues are when people show us things from their apps, even with code, as there could be all sorts of things affecting the result.

The easiest way to get to a diagnosis and a potential resolution is to provide a sandbox with a simple reproduction.

✌️

**Comment by brandonwie** [comment]
I had the same issue, checking out parent div's size or padding could be useful.
