### ISSUE TITLE
[Dropdown] Animation on closed state has a weird effect

### ISSUE THREAD

**Issue by jvidalv** [radix-ui/primitives#1466]
### Current Behavior

This is a NextJs 12 project using React 18. This weird animation effect on `data-state="closed"` only happens on production, It doesn't happen on localhost while developing, and seems random, sometimes it happens sometimes does not:

https://user-images.githubusercontent.com/27777508/173364464-658f434e-cc63-41e0-9230-9136fa9079af.mov

### Expected behavior

To not have this weird effect. This is how it looks on localhost:

https://user-images.githubusercontent.com/27777508/173364098-724c6704-b946-4852-9c2d-f1e44fd0b188.mov

### Reproducible example
```js
const fadeOutTop = keyframes({
  from: {
    opacity: 1
  },
  to: {
    opacity: 0,
    transform: 'translateY(-8px)'
  }
})

```

```js
 '&[data-state="closed"]': {
          animation: `${fadeOutBottom} 100ms`
        }
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   react-dropdown-menu      |      0.1.6   |
| React            |      |   18.1.0       |
| Browser          |    Chrome     |    102.0.5005.115     |
| NextJs         |         |    12.1.6     |
| Operating System |     Mac   |         |

**Comment by benoitgrelard** [comment]
Hi @jvidalv,

This looks like one of the React 18 issues we have already fixed.
We haven't released public versions yet, but if you try upgrading to the latest release candidate, it should be gone.
Let me know and once you've tested and we can close accordingly.

**Comment by jvidalv** [comment]
Hi @benoitgrelard, yep the latest version seems to have this fixed!

Thanks!

**Comment by benoitgrelard** [comment]
Cool, I'll close the issue then.
