### ISSUE TITLE
Using `Tooltip` with `Slottable` doesn't work as expected

### ISSUE THREAD

**Issue by umpox** [radix-ui/primitives#1475]
### Current Behavior

I am using `Slottable` to try to pass target `children` to the Tooltip `Trigger` component, whilst also having a second child within the trigger.

The second child is the Tooltip content, which is just to work towards WCAG 2.1 compliance by not hiding the tooltip on tooltip mouseover.

This doesn't seem to work as expected, this is what I understand to be required:
1. Component to be used `asChild` spreads props
2. Component to be used `asChild` component uses `forwardRef`
3. Component to be used `asChild` uses `children` to render something

That last point was unexpected, to see an example of it, please check the CodeSandbox below.

### Expected behavior

I would expect I can use `Slottable` for this purpose. Everything works fine, it just has this odd requirement that `children` is used within the `asChild` component internals.

Please let me know if this is discouraged behavior!

### Reproducible example

https://codesandbox.io/s/quizzical-bush-o692hf?file=/src/App.tsx

### Suggested solution

I would assume we shouldn't need to do anything with `children` here, these seems to be buged.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   `react-tooltip`      |     `0.1.8-rc.43`    |
| Radix Package(s) |       `react-slot`  |      ` 0.1.3-rc.38`   |
| React            | n/a     |    `17.0.2`     |
| Browser          |   Chrome      |     `102.0.5005.61 (Official Build) (arm64)`    |
| Assistive tech   |     n/a    |         |
| Node             | n/a     |         |
| npm/yarn         |     yarn    |   `1.22.18`      |
| Operating System |    MacOS Monterey     |     `12.2.1 `    |

**Comment by benoitgrelard** [comment]
Hi @umpox,

Thanks for creating this issue.

There is no issue with `asChild` and it's rather expected given the specific implementation here.

Because you are rendering the `Tooltip.Content` inside `Tooltip.Trigger` (I understand you're trying to get around the other issue we're working on) then, if you're trigger doesn't render `children` it will never render `Tooltip.Content`, hence why no tooltip.

I will close the issue but feel free to keep discussing here if you want.

✌️

**Comment by umpox** [comment]
Thanks for the quick reply @benoitgrelard! Should I still expect this constraint if I'm using a portal? I found it odd because I had to force my component to render `children`, but as far as I could tell, the Tooltip wasn't actually putting anything inside `children`

**Comment by umpox** [comment]
Also, any other tips to work around the WCAG 2.1 compliance would be appreciated! (Or any idea of when you think you'll implement this yourselves)

**Comment by benoitgrelard** [comment]
> Should I still expect this constraint if I'm using a portal?

This isn't a constraint no, if you update your demo and move the content outside the trigger in your tooltip abstraction, you'll see that your example with `asChild` and harcoded children works fine.

> Also, any other tips to work around the WCAG 2.1 compliance would be appreciated! (Or any idea of when you think you'll implement this yourselves)

We're working on it as we speak, so I'd just wait, the v1 release is imminent now, next week or so.
