### ISSUE TITLE
[Select] Limiting height of Select Viewport breaks scrolling

### ISSUE THREAD

**Issue by OlegWock** [radix-ui/primitives#1495]
### Current Behavior
If you limit `max-height` of select viewport and add a bunch of items to that select, when you try to scroll list down (by hovering arrow) -- viewport jumps to the bottom of the screen

Sandbox: https://codesandbox.io/s/sad-noyce-dfjril?file=/App.js
It's same example you have in docs, but with `maxHeight: 200` on line 39

### Expected behavior

I'd expect just usual scrolling, if it's possible

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/sad-noyce-dfjril?file=/App.js)

### Suggested solution

As far as I understand  this happens because of this line https://github.com/radix-ui/primitives/blob/main/packages/react/select/src/Select.tsx#L901

Which shifts viewport to the bottom of screen

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-select | 0.1.1 |
| React            | n/a     |  18.2.0 |
| Browser          |  Chrome (Brave) | 103 |
| Assistive tech   | none  |         |
| Node             | n/a     |  16.13.0 |
| npm/yarn         |  yarn |  1.22.17  |
| Operating System | Mac os  | 12.4 |

**Comment by benoitgrelard** [comment]
Hi @OlegWock, this isn't currently supported as positioning is currently not really customisable.
See #1247 for discussions around improving positioning customisation.
