### ISSUE TITLE
Allow `RemoveScroll` to be disabled in `Select` component

### ISSUE THREAD

**Issue by neilff** [radix-ui/primitives#1496]
## Feature request

We're curious if you'd consider allowing the `RemoveScroll` component to be disabled within the `Select` component. 

### Overview

Our users have reported that it causes confusing behavior by removing the scroll bar. I'm curious what the reasoning was for this component to be used? I might be missing a larger a11y issue that I haven't considered here. 

I noticed that the `RemoveScroll` API exposes an `enabled` prop (as well as a `removeScrollBar ` prop) of which might allow this to be toggled: https://github.com/theKashey/react-remove-scroll#usage

### Examples in other libraries

N/A

### Who does this impact? Who is this for?

All users

**Comment by neilff** [comment]
I might have misinterpreted how this works, let me dive in a bit deeper and I'll reopen after I better understand how this comes together 😅

**Comment by neilff** [comment]
I attempted to quickly expose this prop in a PR but realized there is more work required to fix the positioning issue that arises 🤔 

![Screen Cast 2022-06-30 at 8 42 19 AM](https://user-images.githubusercontent.com/3271978/176679705-9f699044-d203-47da-9699-c21e6574d246.gif)

Regardless, I'm curious to understand if there is a reasoning to not go down this path, otherwise I can try to piece something together.

**Comment by benoitgrelard** [comment]
Hi @neilff, the component currently only supports modal mode (as opposed to others like Popover which supports both modal/non-modal).

Modal mode means no interaction outside the layer, and that includes scrolling.

The main reason for not supporting both yet in Select is the complexity of the positioning combined with outside scroll support. The plan is to support non-modal mode (which subsequently would allow scrolling outside) but the select would close when you do so (we do this with tooltips too).

**Comment by maurocolella** [comment]
Hi @benoitgrelard . This was closed as completed on Jul 1, 2022, but I am unclear on how to enable or implement non-modal mode.

The desired effect for me is to keep the scrollbar visible, and just close the modal once the user wheels away, or scrolls away somehow.

**Comment by joaom00** [comment]
Hi @maurocolella, 

that is not implemented yet. Hopefully, will be addressed by #2253. However, that PR only adds the non modal mode to the `popper` position.

**Comment by maurocolella** [comment]
Thank you for your reply @joaom00 . It seems reasonable to limit it to the `popper` position (this is how I am using the component).

In the meantime, I will simply override the implementation with a detailed comment (remove the `RemoveScroll` wrapper for my own purpose).

**Comment by FanManutd** [comment]
It helped me:

```
useEffect(() => {
    if (shown) {
      document.body.style.setProperty('overflow-y', 'auto', 'important');
    } else {
      document.body.style.removeProperty('overflow-y');
    }
  }, [shown]);
```

**Comment by Railly** [comment]
If you're using `scrollbar-gutter: stable;`, you can add this bunch of css to get rid of the shift.

```css
  html body[data-scroll-locked] {
    --removed-body-scroll-bar-size: 0 !important;
    margin-right: 0 !important;
  } 
```

**Comment by ColeBlender** [comment]
I have my select in a modal so when I click the select it disables the modal. I just want clicking the select to have no effect on the modal. Can this be done with the current library?

**Comment by CodingAleCR** [comment]
Why is this closed if the issue is still happening and the MR for modal stuff isn't merged?

**Comment by danny-avila** [comment]
> Why is this closed if the issue is still happening and the MR for modal stuff isn't merged?

Wondering the same

**Comment by QuocThuanTruong** [comment]
This issue is really annoying :(

**Comment by VietNguyenR** [comment]
Sorry for digging an old thread but better than asking a duplicate question, any new update related to this?

**Comment by penderuk** [comment]
> Thank you for your reply @joaom00 . It seems reasonable to limit it to the `popper` position (this is how I am using the component).
> 
> In the meantime, I will simply override the implementation with a detailed comment (remove the `RemoveScroll` wrapper for my own purpose).

@maurocolella were you able to override the implementation? I tried to remove RemoveScroll from the package's index.js file and create a patch, but didn't work for me.

**Comment by SindelarPetr** [comment]
Have anyone been able to solve this?

I literally gave 2 users the app to see how they use it and both had an issue with this.

**Comment by zegie** [comment]
I'm using this one on two projects and it's working

`html {
		margin: 0;
		padding: 0;
		padding-right: calc(0 - var(--removed-body-scroll-bar-size)) !important;

	}`
	
_No need to create variable for --removed-body-scroll-bar-size_

**Comment by kyle-kettler** [comment]
Why is this issue closed? It is still a problem and something that should be fixed.

**Comment by jmulquin** [comment]
I was having this issue as well, added a MutationObserver inside the component itself to remove it. Kludgy as hell but it works well enough.

`useEffect(() => {
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === 'attributes' && 
            mutation.attributeName === 'data-scroll-locked' && 
            document.body.getAttribute('data-scroll-locked') === '1') {
          document.body.removeAttribute('data-scroll-locked')
        }
      })
    })

    observer.observe(document.body, {
      attributes: true,
      attributeFilter: ['data-scroll-locked']
    })

    return () => observer.disconnect()
  }, [])`

**Comment by roshchyna** [comment]
This hook helped me remove `data-scroll-locked` from the body, and this solution works directly with Radix Select’s `SelectPrimitive.Root`.  I have a scroll on the page, while select is open 

```
  useLayoutEffect(() => {
    if (!modal) {
      return;
    }
    const TYPE_LIST = ['wheel', 'scroll', 'touchmove'];

    const unlockHandlers = () => {
      TYPE_LIST.forEach((type) =>
        window.addEventListener(type, (e) => e.stopImmediatePropagation(), { capture: true, passive: false }),
      );
    };

    unlockHandlers();
    const mo = new MutationObserver(unlockHandlers);
    mo.observe(document.body, { attributes: true, attributeFilter: ['data-scroll-locked'] });

    return () => mo.disconnect();
  }, [modal]);
```

The whole code

```
const Select = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Root> & SelectProps
>(({ modal = true, ...props }) => {
  // Disable Radix scroll-lock by swallowing wheel/scroll/touchmove events
  useLayoutEffect(() => {
    if (!modal) {
      return;
    }
    const TYPE_LIST = ['wheel', 'scroll', 'touchmove'];

    const unlockHandlers = () => {
      TYPE_LIST.forEach((type) =>
        window.addEventListener(type, (e) => e.stopImmediatePropagation(), { capture: true, passive: false }),
      );
    };

    unlockHandlers();
    const mo = new MutationObserver(unlockHandlers);
    mo.observe(document.body, { attributes: true, attributeFilter: ['data-scroll-locked'] });

    return () => mo.disconnect();
  }, [modal]);

  return (
    <SelectPrimitive.Root
      // Disabling pointer-events is a forced measure because radix-select does not accept modal={false},
      // unlike DropdownMenu, Popover, Dialog and AlertDialog.
      onOpenChange={(open) => {
        if (open && !modal) {
          requestAnimationFrame(() => {
            document.body.style.setProperty('pointer-events', 'initial', 'important');
          });
        }
      }}
      {...props}
    />
  );
});
```

**Comment by Matthematic** [comment]
@roshchyna Your effect is not implemented properly. 

- Every mutation on document.body will add *more* event listeners without removing the old ones, which is a memory leak.
- unlockHandlers should only be adding the listeners if data-scroll-locked was added, but yours adds them even if the attribute was removed.

Even if those were fixed, people should keep in mind that this solution works by using capture phase to prevent those events from reaching any other listeners, which could also include your own listeners!

**Comment by daniloccangucu** [comment]
Railly's solution didn't work for all my use cases but this did:

```
html body[data-scroll-locked] {
  overflow-y: auto !important;
}
```

Hope it works for you!

**Comment by arturhaddad** [comment]
I had a problem with the Dialog, which blocked scrolling inside the Dialog content and I had to do a trick to be able to:
- keep using the `modal={true}`
- display the overlay
- and keep the scroll enabled only inside the modal

I wrapped the scrollable content within `<RemoveScroll>` using the `shards` property:

```
import * as RadixDialog from '@radix-ui/react-dialog';
import { RemoveScroll } from 'react-remove-scroll';
import { useRef } from 'react';

export default function Dialog({ open, onOpenChange, children, trigger, title }) {
  const scrollableRef = useRef(null);

  return (
    <RadixDialog.Root open={open} onOpenChange={onOpenChange} modal={true}>
      {trigger && <RadixDialog.Trigger asChild>{trigger}</RadixDialog.Trigger>}
      <RadixDialog.Portal>
        <RadixDialog.Overlay />
        <RadixDialog.Content>
          {title && <RadixDialog.Title>{title}</RadixDialog.Title>}

          {/* Using RemoveScroll with shards allows scrolling the content, with modal mode and overlay active */}
          <RemoveScroll shards={[scrollableRef]}>
            <div ref={scrollableRef}>{children}</div>
          </RemoveScroll>

        </RadixDialog.Content>
      </RadixDialog.Portal>
    </RadixDialog.Root>
  );
}

```

**Comment by alexsapps** [comment]
> If you're using `scrollbar-gutter: stable;`, you can add this bunch of css to get rid of the shift.
> 
>   html body[data-scroll-locked] {
>     --removed-body-scroll-bar-size: 0 !important;
>     margin-right: 0 !important;
>   }

I tried adding scrollbar-gutter: stable to body but that didn't work -- I had to add it to html:

```
html {
  scrollbar-gutter: stable;
}
html body[data-scroll-locked] {
  --removed-body-scroll-bar-size: 0 !important;
  margin-right: 0 !important;
}
```

**Comment by alexsapps** [comment]
@benoitgrelard would it be possible to reopen? :)

[> Why is this closed if the issue is still happening and the MR for modal stuff isn't merged?
](https://github.com/radix-ui/primitives/issues/1496#issuecomment-2081223215)

**Comment by rokanjan** [comment]
For anyone still looking, I was able to fix this with a slightly different override: 

```
[data-scroll-locked][data-scroll-locked] {
    overflow-y: scroll !important;
    margin-right: 0 !important;
}
```
