### ISSUE TITLE
Mouse and Keyboard events prevented in nested Portals

### ISSUE THREAD

**Issue by cdeutsch** [radix-ui/primitives#1497]
### Current Behavior

I have a Select (which uses a Portal) inside a Dialog (also using a Portal).

I can't select items in the Select using the mouse or keyboard.

I've run into similar issues with mouse events not working with 3rd party Selects using Portals while trying to debug.

### Expected behavior

Be able to select a value.

### Reproducible example

https://codesandbox.io/s/angry-mestorf-n8vix3?file=/App.js

### Suggested solution

Not sure. Could be related to #1088

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dialog      |   0.1.8-rc.48      |
| Radix Package(s) |   @radix-ui/react-select      |   0.1.2-rc.50      |
| React            | n/a     |    latest     |
| Browser          |     Chrome    |   102.0.5005.115      |
| Operating System |   Mac      |     12.4    |

**Comment by benoitgrelard** [comment]
Hey @cdeutsch, how is it different?
It is the same but bare bones without styles. I wanted to show that there isn't a clash between these 2 packages.

> FWIW, our team/product has decided not to use Radix after a month of trying to replace our existing components with it.

Sorry to hear you didn't find it useful, it might be nice to know what brought you to the decision, so we can learn from it potentially.

**Comment by cdeutsch** [comment]
> It is the same but bare bones without styles. I wanted to show that there isn't a clash between these 2 packages.

Your example is `Dialog -> Select`. 
Mine is `Dialog -> Dialog -> Select` (nested Dialog)

> it might be nice to know what brought you to the decision

Primarily tab trapping issues like this and #1498

Prior to Radix we'd been burned a few times by `focus-trap-react` when it came to nested UI. 

We were hoping Radix would be a more hands off solution (which it is when it works), but so far our hacked together `focus-trap-react` code has been a better UX when it comes to multi-level nesting.

**Comment by cdeutsch** [comment]
I updated your example to be closer in structure.
https://codesandbox.io/s/select-within-dialog-forked-iqpumv?file=/src/App.js

Seems like the issue only happens if I use `@radix-ui/react-dialog@0.17` and `@radix-ui/react-select@0.1.2-rc.50`

If I upgrade to `@radix-ui/react-dialog@0.18.x` it goes away so likely #1088?

**Comment by benoitgrelard** [comment]
> Primarily tab trapping issues like this and https://github.com/radix-ui/primitives/issues/1498

> Prior to Radix we'd been burned a few times by focus-trap-react when it came to nested UI.

> We were hoping Radix would be a more hands off solution (which it is when it works), but so far our hacked together focus-trap-react code has been a better UX when it comes to multi-level nesting and elements being removed (https://github.com/radix-ui/primitives/issues/1498)

I have been looking at that issue, I think I'll have a fix for it soon.

> Seems like the issue only happens if I use @radix-ui/react-dialog@0.17 and @radix-ui/react-select@0.1.2-rc.50 (make sure to use the keyboard to see it not working)

> If I upgrade to @radix-ui/react-dialog@0.18.x it goes away so likely https://github.com/radix-ui/primitives/issues/1088?

When I checked your original sandbox, I think you were using the latest rc for both no? That's what confused me, at least your description says so still now. But yeah, #1088 is the issue here because if you use very different versions, they'll get a different context for the layering hence not be able to communicate correctly.
