### ISSUE TITLE
Focus trap lost when you click an item and remove it

### ISSUE THREAD

**Issue by cdeutsch** [radix-ui/primitives#1498]
### Current Behavior

If you click an item and remove it, the focus gets set to the browser's Url bar.

When you tab back into the body content, you can tab to elements that are behind the focus trap.

### Expected behavior

Focus shouldn't go to the Url bar after removing an item.

If it does, you should return to the focus trap instead of elements outside it.

### Reproducible example

Code:
https://codesandbox.io/s/hardcore-stitch-ne0g0n?file=/App.js

Easier to reproduce fullscreen:
https://ne0g0n.csb.app/

### Additional context

Previously I've been using `focus-trap-react` and it didn't have the same issue. Focus doesn't go to the Url bar when items are removed, and if you manually focus the Url bar, you will return to the tab trap straight away.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dialog      |   0.1.8-rc.48      |
| Radix Package(s) |   @radix-ui/react-select      |   0.1.2-rc.50      |
| React            | n/a     |    latest     |
| Browser          |     Chrome    |   102.0.5005.115      |
| Operating System |   Mac      |     12.4    |

**Comment by cdeutsch** [comment]
> Not sure how they handle it, because document.activeElement shows that it's on body but a press on "tab" will continue tabbing normally to the next control (after the deleted one):

Is that true in a Dialog as well?

**Comment by benoitgrelard** [comment]
This is an example in `Dialog`.

**Comment by benoitgrelard** [comment]
We handle everything when the dialog is unmounted so I think ultimately this is a product responsibility.
If in your specific app, you unmount something that has focus inside that Dialog, then you should redirect the focus to the next logical place in your dialog.

**Comment by cdeutsch** [comment]
> We handle everything when the dialog is unmounted so I think ultimately this is a product responsibility.

FWIW `focus-trap-react` doesn't have the same issue, and doesn't expect you to do anything special.

I think the real issue with Radix is not the dialog losing focus, but that it allows focus to resume "behind" the dialog. That just shouldn't be possible if it was actually trapped.

**Comment by jjenzz** [comment]
@benoitgrelard could the focus trap do something like [the following](https://codesandbox.io/s/purple-framework-jrvdit?file=/App.js) to solve this?

```jsx
document.addEventListener('focusout', (event) => {
  if (event.relatedTarget === null) container.focus();
})
```

**Comment by benoitgrelard** [comment]
@jjenzz from my previous comment here: https://github.com/radix-ui/primitives/issues/1498#issuecomment-1177874105

> This actually looks like a bug in Chrome, as Firefox and Safari don't raise a focusout event when the element that has focus gets deleted.

So looks like in theory it might work because even though `focusout` is only raised by Chrome in these cases (when deleting the focused element) the next tab keeps it inside magically in the other browsers (I have no idea how they do that).

However, I remember trying exactly what you did here from within `FocusScope` but had issues with distinguishing that case from other cases where `relatedTarget` is also `null`.

I'll give it another spin soon.

**Comment by benoitgrelard** [comment]
Reopening, will see if we can do what's above.

**Comment by enkot** [comment]
Hey @benoitgrelard 
As you already mentioned and I think it is correct - this is a product responsibility. 
Solution with `MutationObserver` creates another problem: 
https://github.com/radix-vue/radix-vue/issues/518

This is Vue example :) but it has exactly the same logic and 99% RadixUI also has this problem.

Similar issue in RadixUI - https://github.com/radix-ui/primitives/issues/2436

**Comment by hipstersmoothie** [comment]
I'm experiencing this exact issue

**Comment by hipstersmoothie** [comment]
I've tested the fix for the linked radix-vue` PR and it seems to work
