### ISSUE TITLE
[Select] Expose `Portal` part like in `Dialog`

### ISSUE THREAD

**Issue by ChristophLabacher** [radix-ui/primitives#1502]
There have been several improvements made to expose the `Portal` used by components to allow for more control over the layering: #1302 #1303 #1304 #1305 #1306

This would also be great for the `Select` component.

---

PS: Thanks for building this great library, it is greatly appreciated!

**Comment by benoitgrelard** [comment]
Hi @ChristophLabacher,

Thanks for the kind words. This has also been done for `Select` already as part of #1459.
