### ISSUE TITLE
[Toast] UI to indicate how much time until close it

### ISSUE THREAD

**Issue by erickriva** [radix-ui/primitives#1520]
### Overview

Would be great if there was a decreasing progress bar to indicate how much time is missing to close the Toast.

### Examples in other libraries

[React Toastify](https://github.com/fkhadra/react-toastify)

### Who does this impact? Who is this for?

It impacts all users.

### Additional context

Toasts sometimes can be tedious to look, it looks like they never be gone 😅
Would be nice to see a decreasing bar to tell users how much to wait to close (the user can close it by its own, but it's good to have a feedback without interacting with it)

**Comment by andy-hook** [comment]
Related https://github.com/radix-ui/primitives/issues/1453

**Comment by benoitgrelard** [comment]
This looks like something we're unlikely to do no? As in provide the actual components for it.
I think if we execute on #1453 then it's something people can build themselves on top?

**Comment by andy-hook** [comment]
> I think if we execute on https://github.com/radix-ui/primitives/issues/1453 then it's something people can build themselves on top?

Yeah it’s arguable, though if it’s a common need then providing parts that hook into the internal duration might be a nice DX.

**Comment by benoitgrelard** [comment]
The reason is this seems highly opinionated UI, it could be a bar, it could be a pie timer, it could be just numbers, etc. Not sure this fits what we usually offer.

**Comment by andy-hook** [comment]
That's fair, we can cover this with a docs example after the resume/pause props have been added
