### ISSUE TITLE
[Tooltip] Keep tooltip open when trigger is activated 

### ISSUE THREAD

**Issue by dannyhkim** [radix-ui/primitives#1524]
### Overview
I'm trying to implement a tooltip using Radix that stays open when activating the trigger, but can't think of or find a way to do it.

### Additional context
https://github.com/radix-ui/primitives/issues/1077
I tried following the suggestions here but they did not work. I'm assuming some of the props like `onPointerDownOutside` are no longer supported for the Tooltip?

**Comment by benoitgrelard** [comment]
Hey @dannyhkim,

That prop is still supported, it hasn't changed.
You can see the story we have for this behaviour in our code:
https://github.com/radix-ui/primitives/blob/768bc53149aa1f432b5e630b99589237f6333364/packages/react/tooltip/src/Tooltip.stories.tsx#L617-L643

and here it is running in our latest storybook build from `main`: https://601857eb614bae0021c9b9dd-adxkvgwszr.chromatic.com/?path=/story/components-tooltip--keep-open-on-activation

I will close the issue as it all seems to be working fine.

**Comment by dannyhkim** [comment]
<img width="744" alt="Screen Shot 2022-07-13 at 12 19 13 PM" src="https://user-images.githubusercontent.com/43249425/178782482-63f8a2de-b902-42de-bfd2-78a4dc3d3438.png">
It says the prop `onPointerDownOutside` does not exist on type 'IntrinsicAttributes & TooltipContentProps & RefAttributes<HTMLDivElement>'

**Comment by dannyhkim** [comment]
Hi @benoitgrelard, here is a link to the [sandbox](https://codesandbox.io/s/magical-fog-jd8r5b?file=/src/Tooltip.tsx).
Thanks

**Comment by benoitgrelard** [comment]
Ah I see, you're using the latest stable which doesn't yet have that prop.
This is a change we made recently to enable such use-case as the one you are trying to achieve.
You can upgrade to the latest rc for now until we release v1 probably next week.

**Comment by charliematters** [comment]
Sorry to comment on a closed issue, but is there a way to get this to work with `submit` buttons? 

In react-router (and Remix I suppose), forms are used for things which don't always result in navigation, so we'd need to submit a form whilst still showing the tooltip

**Comment by kdawgwilk** [comment]
Any tips on an example where the trigger is not just plain text but rather some other component?  The example appears to only work with plain text.  I am using a `span` inside the trigger and was unable to get the tooltip to stay open

**Comment by klingat** [comment]
To anyone coming here in 2025! None of these solutions worked for me with the latest version of the tooltip primitive (v1.2.4). 
I found this PR from April 2025 that closes the tooltip when `onPointerDown` of the tooltip is triggered: https://github.com/radix-ui/primitives/pull/3380

That means to keep the tooltip open on activation of the trigger, I had to prevent default and stop propagation on the onPointerDown event (as well as the onClick).

```js
<TooltipPrimitive.Trigger
  onClick={(e) => {
    e.preventDefault()
    e.stopPropagation()
  }}
  onPointerDown={(e) => {
    e.preventDefault()
    e.stopPropagation()
  }}
  {...}
>
{...}
</TooltipPrimitive.Trigger>
```

**Comment by alythobani** [comment]
Thanks for posting that @klingat ! 

In case it's useful to anyone else, I also programmatically `.focus()` the trigger element in the events. Otherwise as [mentioned](https://github.com/radix-ui/primitives/issues/1077#issuecomment-1011522011) in #1077, `e.preventDefault()` also prevents the trigger from removing focus like it normally would.

Although this does result in a visible focus state on click, which may not be desired (and could be avoided with `.focus({focusVisible: false})`, but that's experimental and  [not widely available in browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#browser_compatibility)). So I also added a prop to my tooltip component to only prevent default and auto-focus when desired.

```tsx
import { Content, Root, Trigger } from "@radix-ui/react-tooltip";
import { memo, useCallback, useRef } from "react";

export type TriggerActivationOptions =
  | {
      keepTooltipOpen: false;
    }
  | {
      keepTooltipOpen: true;
      focusTrigger: boolean;
    };

export const Tooltip = memo(function Tooltip({
  children,
  ...
  triggerActivationOptions = { keepTooltipOpen: false },
}: {
  children: React.ReactNode;
  ...
  triggerActivationOptions?: TriggerActivationOptions | undefined;
}): JSX.Element {
  const triggerRef = useRef<HTMLButtonElement>(null);
  /** Avoiding the tooltip disappearing when the trigger is activated:
  https://github.com/radix-ui/primitives/issues/1524#issuecomment-2831317898 */
  const onTriggerActivation = useCallback(
    (e: React.UIEvent<HTMLButtonElement>) => {
      if (!triggerActivationOptions.keepTooltipOpen) return;
      e.preventDefault();
      e.stopPropagation();
      if (triggerActivationOptions.focusTrigger) {
        // @ts-expect-error - focusVisible is an experimental option
        triggerRef.current?.focus({ focusVisible: false });
      }
    },
    [triggerActivationOptions]
  );
  return (
    <Root delayDuration={delayDuration}>
      <Trigger
        ref={triggerRef}
        asChild
        onClick={onTriggerActivation}
        onPointerDown={onTriggerActivation}
      >
        {children}
      </Trigger>
      <Content ... >{tooltipContent}</Content>
    </Root>
  );
});

```

**Comment by PabloL007** [comment]
> To anyone coming here in 2025! None of these solutions worked for me with the latest version of the tooltip primitive (v1.2.4). I found this PR from April 2025 that closes the tooltip when `onPointerDown` of the tooltip is triggered: [#3380](https://github.com/radix-ui/primitives/pull/3380)
> 
> That means to keep the tooltip open on activation of the trigger, I had to prevent default and stop propagation on the onPointerDown event (as well as the onClick).
> 
> <TooltipPrimitive.Trigger
>   onClick={(e) => {
>     e.preventDefault()
>     e.stopPropagation()
>   }}
>   onPointerDown={(e) => {
>     e.preventDefault()
>     e.stopPropagation()
>   }}
>   {...}
> >
> {...}
> </TooltipPrimitive.Trigger>

Can confirm this still works with v1.5.0, thanks!
