### ISSUE TITLE
[NavigationMenu] Menu closed with Esc immediately reopens on mouse move

### ISSUE THREAD

**Issue by vladmoroz** [radix-ui/primitives#1529]
## Bug report

When you close NavigationMenu with Esc, moving the mouse opens it again, which defeats the purpose of being able to close the menu like this in the first place.

It should stay closed until the next time you hover in; similarly to how it works when you close it via a mouse click and move the mouse.

### Reproducible example

https://www.radix-ui.com/docs/primitives/components/navigation-menu

**Comment by andy-hook** [comment]
Indeed it should, for posterity:

https://user-images.githubusercontent.com/11708259/178768788-b34c7304-e237-4ec1-be24-20e5fedfa570.mp4
