### ISSUE TITLE
TooltipProvider is required in 1.8 rc

### ISSUE THREAD

**Issue by troncoso** [radix-ui/primitives#1538]
### Current Behavior

In react-tooltip v0.1.8-rc.49, `<TooltipProvider>` is required in order to use the component with the "Custom APIs".

<img width="1792" alt="Screen Shot 2022-07-19 at 14 12 45" src="https://user-images.githubusercontent.com/1711448/179823137-28a641f8-ae16-4293-a79b-e5f1345548a3.png">

### Expected behavior

In react-tooltip v0.1.7, ([as shown by the docs](https://www.radix-ui.com/docs/primitives/components/tooltip#custom-apis)), `<TooltipProvider>` is not required to use this component when using the "Custom APIs", which is how I am using it. Everything works fine this way. I can see that `<Tooltip.Provder>` was [added in v0.1.6](https://www.radix-ui.com/docs/primitives/overview/releases#december-13-2021), so I don't see why this would work in 0.1.7 and not 0.1.8.

### Code

```typescript
import { Root, TooltipTrigger, TooltipArrow, TooltipContent } from '@radix-ui/react-tooltip';
import tw from 'tailwind-styled-components';

interface TooltipProps {
	/**
	 * Text to display in the tooltip
	 */
	content: string;
	/**
	 * Element which will trigger the tooltip
	 */
	children: React.ReactNode
	/**
	 *  Display the arrow element alongside the tooltip
	 */
	showArrow: boolean;
}

const StyledContent = tw(TooltipContent)`
	rounded-md
	px-3
	py-2
	shadow-lg
	bg-white
`;

const StyledArrow = tw(TooltipArrow)`
	fill-white
`;

/**
 * A tooltip that displays information related to an element when the mouse hovers over it.
 */
export const Tooltip = ({
	content,
	showArrow,
	children,
}: TooltipProps) => (
	<Root>
		<TooltipTrigger asChild>
			<div>{children}</div>
		</TooltipTrigger>
		{ content && (
			<StyledContent data-testid="tooltipContent" side="top" align="center">
				{content}
				{ showArrow && (
					<StyledArrow
						offset={5}
						width={25}
						height={10}
					/>
				) }
			</StyledContent>
		)}
	</Root>
);
```

Note, I tried removing the `tailwind-style-components` stuff and it didn't fix anything.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-tooltip        |  0.1.8-rc.49       |
| React            | n/a     | 18.2.0        |
| Browser          | Chrome        | 103.0.5060.114        |
| Assistive tech   |         |         |
| Node             | n/a     | v18.2.0        |
| npm/yarn         | npm        | 8.9.0        |
| Operating System | MacOS Monterey       | 12.4        |

**Comment by benoitgrelard** [comment]
It will be indeed required in the next version, you can see the changelog for it here: https://radix-website-git-release.modulz-deploys.com/docs/primitives/overview/releases.

You are using release candidates, so changes like these might occur without notice.
