### ISSUE TITLE
[Dropdown] Expose Portal part like in Dialog

### ISSUE THREAD

**Issue by adam-lynch** [radix-ui/primitives#1542]
### Overview

There have been several improvements made to expose the `Portal` used by components to allow for more control over the layering: https://github.com/radix-ui/primitives/issues/1302 https://github.com/radix-ui/primitives/issues/1303 https://github.com/radix-ui/primitives/issues/1304 https://github.com/radix-ui/primitives/issues/1305 https://github.com/radix-ui/primitives/issues/1306 https://github.com/radix-ui/primitives/pull/1459.

This would also be great for the `Dropdown` component.

### Who does this impact? Who is this for?

I imagine a lot of people probably. I need it for some shadow DOM usage which I guess is more advanced, but I'm sure you've introduced `Portal` to components like this before for other reasons; e.g. `z-index` / styling.

### Additional context

For me specifically, I want to use this component in my browser extension which mounts React inside a custom element's shadow DOM root (in third-party pages). The dropdown content being appended to the body is bad for two reasons:

1. It leaks more elements into the DOM outside of my container.
2. It doesn't get styled correctly because my styles are encapsulated inside the custom element.

**Comment by adam-lynch** [comment]
Where in the source does it choose / append to `document.body`? For now, I could work around this by editing my `node_modules` using patch-package. I don't mind if it'll affect all Radix components globally.

**Comment by benoitgrelard** [comment]
Hi @adam-lynch,

The work to expose Portal to DropdownMenu has already been done.
In fact you linked to the closed issue already: #1303.

Note: this is in release candidates for now, v1 is going out imminently (should be tomorrow).

**Comment by adam-lynch** [comment]
Ah OK I copied the text from #1459. Great, thanks! Saves me from hacking stuff
