### ISSUE TITLE
[Dialog] Closing with Escape while focused on conditionally rendered element breaks global key bindings

### ISSUE THREAD

**Issue by cheslip** [radix-ui/primitives#1546]
### Current Behavior

If a focusable element within a Dialog is rendered conditionally, and that element is focused when hitting Escape, the dialog closes as expected but keyboard handlers stop working.

### Expected behavior

Once the dialog closes all keyboard event handler should be restored.

### Reproducible example

https://codesandbox.io/s/elastic-tree-7nbp8i?file=/src/App.js

### Additional context

Key handlers are restored after clicking anywhere inside the document.

### Your environment

See Codesandbox

**Comment by andy-hook** [comment]
Hi @cheslip, the issue is due to focus not being returned to the trigger when the dialog is closed, this means key events are unable to bubble from an element. This can be solved by using the `Trigger` part provided by dialog as it will handle such behaviour and other accessibility concerns for you automatically.

https://codesandbox.io/s/happy-williams-7pdclr?file=/src/App.js

**Comment by cheslip** [comment]
Thanks @andy-hook! One follow-up question: Is there a way to do this without a Trigger? My use case is the dialog is opening from a command palette, which disappears after the option is selected. 

Also, it appears my problem only happens in Chrome. Safari works the way I'd expect.

**Comment by andy-hook** [comment]
> Also, it appears my problem only happens in Chrome. Safari works the way I'd expect.

Sounds a lot like this [related issue](https://github.com/radix-ui/primitives/issues/1498#issuecomment-1177874105). Essentially this comes down to how the browser handles complete loss of the actively focused element when not given an alternative on removal.

In cases where you can't use the trigger then focus redirection needs to be handled manually, this is most important for keyboard accessibility but also solves this particular issue. For a command palette you'd want to return focus to the previously focused element prior to the palette being opened.

Here's a quick example showing how this is restored on `body`, though the same could apply to buttons and other controls:

https://codesandbox.io/s/silent-water-urqtg4?file=/src/App.js

**Comment by cheslip** [comment]
Thank you - that works!
