### ISSUE TITLE
[Select] Content positioning is off when parent is animated into view

### ISSUE THREAD

**Issue by la55u** [radix-ui/primitives#1557]
### Current Behavior

If there is animation set on the parent component of Select, when clicking the Select trigger, the content does not show up. You can inspect the element and adjust it's max height manually to make it visible.

### Expected behavior

Select show behave the same way in both cases.

### Reproducible example

1. Click toggle, click the Select trigger --> Select content opens (OK)
2. uncomment the animation at line 22.
3. Click toggle, click the Select trigger --> Select content doesn't show up (NOT OK)

https://codesandbox.io/s/goofy-feistel-cqgggv?file=/App.js

### Your environment

Firefox Developer Edition 103.0b9 (64-bit)

**Comment by benoitgrelard** [comment]
I think it's due to the `forwards` on the animation, if you remove it, it works fine.

**Comment by la55u** [comment]
my bad, thank you.
