### ISSUE TITLE
[Label] role label is not valid

### ISSUE THREAD

**Issue by catherinep-acc** [radix-ui/primitives#1558]
### Current Behavior

`Label` is a `span` that is given a role of `label`, which is not a valid aria role.
![Screen Shot 2022-07-22 at 3 18 50 PM](https://user-images.githubusercontent.com/95252324/180577065-2939ec57-b5ed-439e-9f69-72bac2d2111a.png)

### Expected behavior

`Label` has the appropriate semantic role. Since the HTML element `label` does not have a corresponding aria role, I would expect `Label` to be a `label` and not a `span`.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/gracious-platform-eqeqjx)

### Suggested solution

Use HTML `label` rather than `span`.

### Additional context

[MDN list of aria roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles)
[MDN label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     react-label    |     0.1.5    |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by andy-hook** [comment]
Hey @catherinep-acc, this has been mentioned a few times now in other related issues, you can find more context on our current stance here https://github.com/radix-ui/primitives/issues/1310#issuecomment-1090158481
