### ISSUE TITLE
[RovingFocusGroup] Allow opt-out of focus first behavior in menu primitive

### ISSUE THREAD

**Issue by luisorbaiceta** [radix-ui/primitives#1564]
## Feature request

There are certain behaviors described in the WAI-ARIA spec that need this. I just came across one working in the `Menubar` component.

![image](https://user-images.githubusercontent.com/44276180/180664886-9d6aa494-65ba-4e26-80c9-12a66915d613.png)

[Link to page](https://www.w3.org/WAI/ARIA/apg/example-index/menubar/menubar-editor.html#top)

**Comment by luisorbaiceta** [comment]
The focus first behavior occurs [here](https://github.com/radix-ui/primitives/blob/8f75e5be679b9c269638bddf532a166d80edecb4/packages/react/roving-focus/src/RovingFocusGroup.tsx#L172)

**Comment by jjenzz** [comment]
if my memory serves me correctly, there is an `onEntryFocus` event that can be prevented for this?

**Comment by luisorbaiceta** [comment]
You're right! Thanks!
