### ISSUE TITLE
[DropdownMenu] Tab press should focus next focusable element outside DropdownMenu

### ISSUE THREAD

**Issue by luisorbaiceta** [radix-ui/primitives#1565]
## Bug report

To meet WAI-ARIA requirements tab press inside the DropdownMenu should focus the next focusable element outside it

### Current Behavior

Nothing happens

### Expected behavior

Focus next focusable element outside the primitive

**Comment by jjenzz** [comment]
i'm assuming you are referring to a non-modal dropdown menu but I am curious which WAI ARIA requirements say this? everything i had found suggested what Radix has is correct regarding non-modal content.

**Comment by jjenzz** [comment]
found it !

![image](https://user-images.githubusercontent.com/175330/180768550-d8e66365-d1fb-4f46-bfa0-cb6101019f97.png)

https://w3c.github.io/aria-practices/#keyboard-interaction-12

**Comment by luisorbaiceta** [comment]
That's it! 😉

**Comment by benoitgrelard** [comment]
Isn't this a duplicate of #1308

**Comment by luisorbaiceta** [comment]
Whether the menu is modal or non-modal, Tab press gets hijacked [here](https://github.com/radix-ui/primitives/blob/8f75e5be679b9c269638bddf532a166d80edecb4/packages/react/menu/src/Menu.tsx#L508) and prevents default behavior

**Comment by benoitgrelard** [comment]
Yeah that's because we had decided that menus aren't tabbable so we did it in there. But regardless, I still think it's a duplicate no?

**Comment by luisorbaiceta** [comment]
duplicate of #1308
