### ISSUE TITLE
[DropdownMenu] dropdown menu scrolls on hover

### ISSUE THREAD

**Issue by misha-erm** [radix-ui/primitives#1566]
### Current Behavior
When I hover last/first visible item in dropdown menu content it autoscrolls to some random element

https://user-images.githubusercontent.com/8783498/180736094-2052435d-9f1d-4ae8-aa4d-2096701515fc.mov

### Expected behavior

DropdownMenu.Content should not scroll on item hover

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/nice-chihiro-d8hvq6?file=/App.js)

### Additional context

Keyboard navigation feels a bit awkward too. Seems like it tries to keep focused element in the center of the list and those jumps are bit weird

Seems to be reproducible on both versions 0.1.6 and 1.0.0

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dropdown-menu      |     1.0.0    |
| React            | n/a     |     16.14    |
| Browser          |    Brave     |     [Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (x86_64)](https://brave.com/latest/)    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   MacOs      |     12.4    |

**Comment by andy-hook** [comment]
Hey @MikeYermolayev curious on your use case for an overflow scroll on the dropdown? unlike [Select](https://www.radix-ui.com/docs/primitives/components/select) dropdown menu doesn't have first class support for it.

**Comment by MikeYermolayev** [comment]
Right now I can imagine 3 cases where we use dropdowns and the list can get long enough:
1. language selector in code editor block. Here it should be definitely replaced with Select, thank you. Somehow we missed existence of radix select component 😅
2. 'Add block' dropdown menu. Currently it doesn't have a lot of blocks but it definitely will one day so we should restrict max-height for this one. For example Notion's 'add block' menu has a plenty of items
<img width="562" alt="image" src="https://user-images.githubusercontent.com/8783498/181271635-5d944b1e-9937-47fe-a5bf-7ef11221dd69.png">
3. We have a concept of automations and custom actions/buttons, so the list of actions in that case can get long enough
<img width="441" alt="image" src="https://user-images.githubusercontent.com/8783498/181272389-23776f8e-2674-4246-87e4-d252816386d6.png">

**Comment by andy-hook** [comment]
Thanks for that @MikeYermolayev, makes sense and sounds sensible. Looks like the main jank is related to browser scroll behaviour when focus is changing. We should look into how to improve this for `dropdown` as we have for `select`

**Comment by clearly-outsane** [comment]
What if you use a radix scroll area instead?

**Comment by hipstersmoothie** [comment]
The sub menu scrolling with the trigger is also a problem IMO

**Comment by MikeYermolayev** [comment]
Just want to share one more case where I faced this problem again...

The issue becomes more critical when the dropdown is placed above the trigger because first interaction with the menu causes ui jumps

https://github.com/radix-ui/primitives/assets/8783498/9e0f541d-87b0-4ab5-8524-5cc7f86ba070

**Comment by nina-loet** [comment]
Any progress on this bug? I am experiencing this as well and would love to know if a fix is planned.

**Comment by cpmsmith** [comment]
@nina-loet I've got a PR open which fixes it (https://github.com/radix-ui/primitives/pull/2451), but it looks like Radix haven't been reviewing incoming PRs lately.

**Comment by mjvandenberg** [comment]
I am also experiencing some difficulties because of this current behaviour. Any progress? Would love to see a fix for this issue.

**Comment by pozdena** [comment]
We need this as well. Hopefully the fix PR can be reviewed soon!
