### ISSUE TITLE
[Popper] Animated scale not considered in position on mount

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/primitives#1567]
When a popper trigger/reference is rendered inside a scaled animated parent the resulting position does not account for this.

https://codesandbox.io/s/spring-bash-4wzz3o?file=/App.js

**Comment by benoitgrelard** [comment]
Possibly fixed by #2092, will check manually.

**Comment by lauri865** [comment]
See below – didn't have this issue in previous versions:
https://github.com/radix-ui/primitives/assets/3652743/a9cd69b9-1333-4767-bc83-ba46e4259838
