### ISSUE TITLE
[Dialog, DropdownMenu] Option to disable body margin on Dialog & Dropdown menu.

### ISSUE THREAD

**Issue by sannajammeh** [radix-ui/primitives#1572]
### Overview

The CSS selector scrollbar-gutter: stable has landed at 74.09% availability. Using this in conjunction with Dialog or DropdownMenu causes a conflict because it adds additional padding when it's already been added by the browser natively. Currently, this is causing exactly what `scrollbar-gutter` solves, a layout shift in our apps.

The layout shift is caused when the dialog is open. The body receives this style: `margin-right: 17px !important;`. I would like a property on the Dialog to disable this margin style as it's impossible to get around. Global CSS rules with !important are overwritten because of CSS' cascading nature. 

Something like this should be great 
```tsx
<Dialog.Root nativeScrollbarGutter> // No gutter will be added automatically as it already exists
...
</Dialog.Root>
```

### Who does this impact? Who is this for?

Anyone using scrollbar-gutter: stable to remove layout shifts when navigating pages.

### Additional context

Ultimately this is just more control for the library consumer and will future-proof Dialog and DropdownMenu when scrollbar-gutter eventually becomes supported enough.

This also allows for granular control, if native gutters are not supported we can use `window.matchMedia` to fallback to `nativeScrollbarGutter={false}`

**Comment by sannajammeh** [comment]
Managed to get around it with. I'm okay with working on a PR for this if you think this feature would be a good addition.

```scss
@supports (scrollbar-gutter: stable) {
  html body {
    margin-left: 0 !important;
  }
}
```

**Comment by andy-hook** [comment]
Hey @sannajammeh, I'd consider this responsibility of the `remove-scroll` library first and foremost, I know the author has been thinking about this too and [shares a similar perspective](https://github.com/theKashey/react-remove-scroll-bar/issues/33#issuecomment-1193227365)

With that in mind it's not likely something we'd shim in over the top, rather we'd adopt this downstream or modify / alter our dependency entirely.

So for now your workaround is the best option.

**Comment by sannajammeh** [comment]
Thanks for the info! Closing this 👍

**Comment by ryparker** [comment]
Could we add this to the docs? It seems like a common problem for users who display the scroll bar on every page to reduce CLS. 

For example
```css
html {
	overflow-y: show;
}
```
