### ISSUE TITLE
[Tooltip] Does not open/close on mobile devices (iOS)

### ISSUE THREAD

**Issue by dimamarkus** [radix-ui/primitives#1573]
### Current Behavior

The tooltip component does not open/close on iOS Safari. It works in mobile emulation mode in Chrome Dev tools but not on the actual device. Tapping the trigger does not open any tooltip. 

### Expected behavior

The tooltip should open and close when the trigger is tapped. (Ideally, all primitives would behave on mobile as they do on desktop.)

### Reproducible example

[The Radix Documentation](https://www.radix-ui.com/docs/primitives/components/tooltip)

### Your environment

Since this issue can be recreated on your documentation page, i figure you already have environment details.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-tooltip       |       1.0  |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |     iOS  |  15.5        |

**Comment by andy-hook** [comment]
Hi @dimamarkus, thanks for raising but this is [by design](https://github.com/radix-ui/primitives/issues/955#issuecomment-960610209).

**Comment by darkdx** [comment]
@andy-hook Excuse me, would like to ask, how to solve the problem of using and displaying Tootip on mobile terminal.

**Comment by darkdx** [comment]
"Closes when the trigger is activated or when pressing escape." Or can I turn this feature off? @andy-hook

**Comment by rcbxd** [comment]
I've found a way to make it work perfectly for my needs, which are:
- Keep the same hover functionality on desktop.
- Do not enable on-click on desktop.
- Enable on-click on mobile.

@matstyler solution worked, but it felt a bit hacky and did not allow me to customize the Trigger like I wanted.

First, create a context which we are going to use all across the `Root` component tree:

```typescript

// tooltip-trigger-context.tsx
'use client';

import { createContext } from 'react';

type TooltipTriggerContextType = {
  open: boolean;
  setOpen: React.Dispatch<React.SetStateAction<boolean>>;
};

export const TooltipTriggerContext = createContext<TooltipTriggerContextType>({
  open: false,
  setOpen: () => {}, // eslint-disable-line
});
```

Then, utilize your context starting from the root:

```tsx
const TooltipRoot: React.FC<TooltipPrimitive.TooltipProps> = ({ children, ...props }) => {
  const [open, setOpen] = React.useState<boolean>(props.defaultOpen ?? false);

  // we only want to enable the "click to open" functionality on mobile
  const { isMd } = useTwBreakpoint('md');

  return (
    <TooltipPrimitive.Root
      delayDuration={isMd ? props.delayDuration : 0}
      onOpenChange={(e) => {
        setOpen(e);
      }}
      open={open}
    >
      <TooltipTriggerContext.Provider value={{ open, setOpen }}>
        {children}
      </TooltipTriggerContext.Provider>
    </TooltipPrimitive.Root>
  );
};
```

And update your `Trigger` component as well:

```tsx
const TooltipTrigger = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Trigger>
>(({ children, ...props }, ref) => {
  const { setOpen } = React.useContext(TooltipTriggerContext);

  return (
    <TooltipPrimitive.Trigger
      ref={ref}
      {...props}
      onClick={(e) => {
        e.preventDefault();
        setOpen(true);
      }}
    >
      {children}
    </TooltipPrimitive.Trigger>
  );
});

```

**Comment by chrispollock** [comment]
> ```
>   const { isMd } = useTwBreakpoint('md');
> ```

Just as an improvement suggestion, I don't know what your hook here is referencing but if it is using a media query you should consider using [`hover`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) instead. Not all devices below an arbitrary breakpoint are touch devices and same goes the other way

**Comment by suitux** [comment]
Still happening today

**Comment by mikker** [comment]
FWIW, here's mine that checks for `:hover` support instead of TW breakpoint:

```js
export default function useHasHover() {
  try {
    return matchMedia('(hover: hover)').matches
  } catch {
    // Assume that if browser too old to support matchMedia it's likely not a touch device
    return true
  }
}
```

Thank you providing your solution @askorupskyy 🙌

**Comment by GunnarHolwerda** [comment]
Leveraging what everyone else has provided here, I'm providing my updated `tooltip.tsx` for ShadCN which adds a new prop to the `Tooltip` component for `supportMobileTap` when this is set, it will enable tapping the tooltip to show it. It defaults to false, to preserve the normal tooltip behavior (because I didn't want this globally in my app, just in a few specific spots).

I also made sure that it would preserve the existing `onClick` behavior of `TooltipTrigger` along with passing the prop from `Tooltip` in the context recommended by @askorupskyy, except I liked the hook provided by @mikker more.

Anyways, hopefully this helps any of you who find this and want this behavior. Totally makes sense that Radix doesn't support this out of the box, but for those that want to enable this here it is enabled via prop.

```typescript
'use client';

import { cn } from '@/lib/utils';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import * as React from 'react';

function useHasHover() {
  try {
    return matchMedia('(hover: hover)').matches;
  } catch {
    // Assume that if browser too old to support matchMedia it's likely not a touch device
    return true;
  }
}

type TooltipTriggerContextType = {
  supportMobileTap: boolean;
  open: boolean;
  setOpen: React.Dispatch<React.SetStateAction<boolean>>;
};

const TooltipTriggerContext = React.createContext<TooltipTriggerContextType>({
  supportMobileTap: false,
  open: false,
  setOpen: () => {},
});

const TooltipProvider = TooltipPrimitive.Provider;

const Tooltip: React.FC<
  TooltipPrimitive.TooltipProps & { supportMobileTap?: boolean }
> = ({ children, ...props }) => {
  const [open, setOpen] = React.useState<boolean>(props.defaultOpen ?? false);
  const hasHover = useHasHover();

  return (
    <TooltipPrimitive.Root
      delayDuration={
        !hasHover && props.supportMobileTap ? 0 : props.delayDuration
      }
      onOpenChange={setOpen}
      open={open}
    >
      <TooltipTriggerContext.Provider
        value={{
          open,
          setOpen,
          supportMobileTap: props.supportMobileTap ?? false,
        }}
      >
        {children}
      </TooltipTriggerContext.Provider>
    </TooltipPrimitive.Root>
  );
};
Tooltip.displayName = TooltipPrimitive.Root.displayName;

const TooltipTrigger = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Trigger>
>(({ children, ...props }, ref) => {
  const hasHover = useHasHover();
  const { setOpen, supportMobileTap } = React.useContext(TooltipTriggerContext);

  const { onClick: onClickProp } = props;

  const onClick = React.useCallback(
    (e: React.MouseEvent<HTMLButtonElement>) => {
      if (!hasHover && supportMobileTap) {
        e.preventDefault();
        setOpen(true);
      } else {
        onClickProp?.(e);
      }
    },
    [setOpen, hasHover, supportMobileTap, onClickProp],
  );

  return (
    <TooltipPrimitive.Trigger ref={ref} {...props} onClick={onClick}>
      {children}
    </TooltipPrimitive.Trigger>
  );
});
TooltipTrigger.displayName = TooltipPrimitive.Trigger.displayName;

const TooltipContent = React.forwardRef<
  React.ElementRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <TooltipPrimitive.Content
    ref={ref}
    sideOffset={sideOffset}
    className={cn(
      'z-50 overflow-hidden rounded-md bg-zinc-900 px-3 py-1.5 text-xs text-zinc-50 animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 dark:bg-zinc-50 dark:text-zinc-900',
      className,
    )}
    {...props}
  />
));
TooltipContent.displayName = TooltipPrimitive.Content.displayName;

export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger };
```

The `cn` function I import here is the classic tailwindMerge and clsx combo

```typescript

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

```
