### ISSUE TITLE
[Tooltip] not opens on iOS

### ISSUE THREAD

**Issue by felixmosh** [radix-ui/primitives#1589]
### Current Behavior

When clicking on the tooltip on iOS it doesn't open.

https://user-images.githubusercontent.com/9304194/182359641-7cf87392-36b2-4ba2-aaa9-8b1e1bc71718.mov

### Expected behavior

It should open when clicking on the tooltip

### Reproducible example
The default example, https://5mdzvl.csb.app/

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      Tooltip   |  1.0.0        |
| React            | n/a     |     16.8    |
| Browser          |         |     Safari    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |     iOS 13    |

**Comment by benoitgrelard** [comment]
This is by design, see https://github.com/radix-ui/primitives/issues/1573#issuecomment-1195120523 and subsequent discussions.
