### ISSUE TITLE
[Select] Cannot use duplicate items value

### ISSUE THREAD

**Issue by carlosriveroib** [radix-ui/primitives#1591]
### Current Behavior

In `Select` component you cannot use two or more items with the same `value`. For example, I'm creating a select with country codes for phone numbers. Canada and USA use the same country code (+1). When you click on Canada or USA both are selected and both values are displayed.

If you put the `Select` inside a `form` you get console.log error messages saying you are duplicating the key, even if you try to use your own key.

### Expected behavior

I'd expect that it's possible to use more than one item with the same value, and display the correct label. I think this is a common use case.

### Reproducible example

Don't forget to change `const Box = styled("div", {});` to `const Box = styled("form", {});` to try form console.log message aswell
https://codesandbox.io/s/billowing-worker-7uk7o1?file=/App.js

### Suggested solution

I think creating a custom key composing `value` + `customId` and get the value from data-value field? I could take this bug if you wish. It would be a pleasure to help with this

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-select | 1.0.0 |
| React            | n/a     | 18.2.0 |
| Browser          | Brave | 1.41.100 |
| Node             | n/a     | 16.15.1 |
| npm/yarn         | yarn | 1.22.19 |
| MacOs | M1 Pro | macOS Monterey 12.5 |

**Comment by benoitgrelard** [comment]
Hi @carlosriveroib,

Values have to be unique because the selection is unique. It doesn't make sense to be able to have duplicate values, otherwise it is impossible to know which item to show as selected when controlled.

You can also see the same issues with a native select (impossible to pick USA):

```tsx
<select value={value} onChange={event => setValue(event.target.value)}>
    <option value="+1">Canada</option>
    <option value="+1">USA</option>
    <option value="+34">Spain</option>
</select>
```

**Comment by carlosriveroib** [comment]
thank you for your answer
