### ISSUE TITLE
[Select][Dialog] - console error 'cannot calculate scrollbar size because it is removed'

### ISSUE THREAD

**Issue by adrian-asimov** [radix-ui/primitives#1593]
### Current Behavior

When the select dropdown is open inside a Dialog a console error shows up `react-remove-scroll-bar: cannot calculate scrollbar size because it is removed (overflow:hidden on body` [link](https://github.com/theKashey/react-remove-scroll-bar/blob/3dd80e28c92b8aac025e41f4258ff926cdc88af9/src/utils.ts#L25)

### Expected behavior

Console error should not appear

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/blissful-marco-2cw1r5?file=/src/dialog.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dialog, @radix-ui/react-select      | 1.0.0  , 1.0.0      |
| React            | n/a     | 18.2.0        |
| Browser          |   Chrome      |   Version 103.0.5060.134 (Official Build) (arm64)      |

**Comment by benoitgrelard** [comment]
Hi @adrian-asimov, this is just a dev warning from the 3rd party library we use internally `react-remove-scroll`, you can safely ignore it or raise an issue with them.
