### ISSUE TITLE
Support a Popover that would overflow the container

### ISSUE THREAD

**Issue by paul-sachs** [radix-ui/primitives#1596]
### Overview

Currently if you have a popover that would overflow the container, it get's clipped off, without a chance to provide a scroll bar instead.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/11449728/182714943-66788750-52fc-44be-8723-3613dc3e6380.png">

### Examples in other libraries

FloatingUI provides an easy middleware to handle [this](https://floating-ui.com/docs/size) use case.

### Who does this impact? Who is this for?

Mostly advanced users will benefit from it. Anyone building a reusable set of components (specifically selects) can leverage this functionality.

**Comment by KevinEdry** [comment]
Would love to see this issue resolved; this is currently hurting our popover capabilities using this lib.

**Comment by sachi097** [comment]
I am facing this issue. Content in the popover is clipped without providing scroll bar.

@paul-sachs how did you fix this?

**Comment by paul-sachs** [comment]
@sachi097 I added the following css to my `RadixPopover.Content` element:

```tsx
const Content = styled(RadixPopover.Content, {
  maxHeight: "calc(var(--radix-popover-content-available-height) - 50px)",
})
```

In my case, I wanted to reduce it by 50px so it doesn't run up against the edge of the window but you can do it a variety of ways.

**Comment by sachi097** [comment]
@paul-sachs  I am using ShadCn any idea how can I fix it?

**Comment by sachi097** [comment]
Before max-height
![Screenshot 2024-09-12 at 12 42 10](https://github.com/user-attachments/assets/0dacf0e4-45c0-4c8d-86d1-4a468794d4d5)

After applying max-height

![Screenshot 2024-09-12 at 12 42 34](https://github.com/user-attachments/assets/c331f18b-24b1-4379-9830-5fa0caaa9e48)

Is there any way to restrict the content within Popover content and get a scrollbar?

**Comment by paul-sachs** [comment]
You'll need some additional css like 'overflow: hidden' but that starts getting very specific to your use case. I'd suggest reading up on how overflow works: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

**Comment by sachi097** [comment]
@paul-sachs  Thank you for all suggestions.

I could fix it with adding below css on PopoverContent of ShadCn
```
<PopoverContent side="top" className="w-96" style={{ maxHeight: "calc(var(--radix-popover-content-available-height))", overflow: "auto" }} >
```

This provides scrollbar that can be used to scroll through content.

![Screenshot 2024-09-12 at 12 58 11](https://github.com/user-attachments/assets/ac106800-2901-4891-9f90-e3c1fe064458)

**Comment by somias** [comment]
@sachi097 Thanks! This one worked for me too.
