### ISSUE TITLE
[Dialog] When using open attribute to control dialog state, accessibility is broken

### ISSUE THREAD

**Issue by djalmaaraujo** [radix-ui/primitives#1599]
### Current Behavior

I would like to demonstrate a problem we face when using Dialog. For many reasons, you might want to close the dialog without using the `<DialogPrimitive.Close asChild>` approach. You need to close later, calling a method.

The only way you can do this is by controlling the `open` state of the dialog from the outside. The problem with this is that you lose all the default close behavior from the dialog and have to code all other things to make the dialog accessible again, like ESC key, auto close when clicking outside, `<DialogPrimitive.Close asChild>`, etc.

### Expected behavior

The expected behavior is to keep consistency when opening a dialog and keep the `<DialogPrimitive.Close>` working along with the ESC key, or at least provide a way to export a method on the content to control the dialog behavior while keeping the internal state of `open` intact.

### Reproducible example

[Example with the Dialog sample](https://codesandbox.io/s/crimson-frost-6gb2zi?file=/App.js)

### Suggested solution

I suggest we somehow export a method to control the state of the dialog open/close, the same way you can use the `DialogPrimitive.Close`.

I might be wrong, but what if we expose the `onOpenToggle()` https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L37 as a method with a proper name?

### Additional context

Related discussion: https://github.com/radix-ui/primitives/discussions/1361

### Your environment

N/A

**Comment by benoitgrelard** [comment]
Ah sorry, just saw your discussion before the issue, I've answered there already: https://github.com/radix-ui/primitives/discussions/1361#discussioncomment-3336817

I will close the issue but let me know if you need a bit more explanation.
