### ISSUE TITLE
Slider Thumb primitives not working in Preact

### ISSUE THREAD

**Issue by nikuda** [radix-ui/primitives#1601]
### Current Behavior

Thumb components are not shown, and not receiving any updates pass the initial inline style applied:

```
element.style {
    transform: var(--radix-slider-thumb-transform);
    position: absolute;
    left: calc(0% + 0px);
}
```

![Screen Shot 2022-08-08 at 12 43 56 pm](https://user-images.githubusercontent.com/723683/183328224-53833e76-5947-4911-87fa-20678a39b816.png)

If the nested span's css is modified from `display: none` to `display: block` the element is rendered on left edge and still doesn't move despite the white line being draggable on both ends.

![Screen Shot 2022-08-08 at 12 49 37 pm](https://user-images.githubusercontent.com/723683/183328675-1fdd3526-7f9c-4b56-ac13-2038a7aad4ee.png)

### Expected behavior

For slider thumbs to be attached to end of white line and to move along with them.

![Screen Shot 2022-08-08 at 12 54 02 pm](https://user-images.githubusercontent.com/723683/183329125-866cf3ae-6aec-4e42-b8d6-1ccf9b408799.png)

### Reproducible example

https://stackblitz.com/edit/nextjs-preact-webpack5-pjoxwh

### Additional context

With Preact `v10.10.1` [release](https://github.com/preactjs/preact/releases) Slider component no longer hangs the whole app, and for most past it works except for the Thumb components as described above.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  `@radix-ui/react-slider`       | `1.0.0`         |
| React            | n/a     |  n/a       |
| Preact            | n/a     | `10.10.1`        |
| Browser          |  Chrome       | `91.0`        |
| Assistive tech   |         |         |
| Node             | n/a     |  `16.14.2`       |
| npm/yarn         | `yarn`        | `1.22.10`        |
| Operating System | MacOs / Linux        |         |

**Comment by nikuda** [comment]
Not a problem @andy-hook. Raised the issue in preact repo https://github.com/preactjs/preact/issues/3666. 

There's a fair bit of cross-over between Preact and Radix UI: lightweight, focused libraries. It would be good to have some kind of compatibility suite once the issues are ironed out.

**Comment by andy-hook** [comment]
Thanks @nikuda 

> Would you be open to having some kind of compatibility suite once the issues are ironed out

Honestly unlikely, creating style agnostic, a11y enhanced primitives just for the React target is challenging enough at the best of times. If React decides to move away from a synthetic event system in the future then parity may increase and make this easier though.
