### ISSUE TITLE
[Select] Opt-out focus trap for select

### ISSUE THREAD

**Issue by aminick** [radix-ui/primitives#1602]
I realized when `SelectContent` is shown, a global focus trap is applied to prevent any parent scolling.
Is there any way to opt-out that? I want to achive a more *traditional* UX, which is scollable parent and also with auto popover flippping.

I guess another topic it's about the design decisition towards the Select component, at least from the example, the UX behavior is very different from what i've seen from other libraries, such as [HeadlessUI's Select](https://headlessui.com/react/listbox), or React Select, wheres the `SelectContent` is almost always beneath the `SelectTrigger`

**Comment by andy-hook** [comment]
Hey @aminick, not currently, the original UX intent for the Radix select was to mimic the well considered MacOS experience as much as possible, though I understand why folk would like more flexibility here depending on the design.

With that in mind i'm going to close this issue as I think it's already well represented by https://github.com/radix-ui/primitives/issues/1247
