### ISSUE TITLE
[Dialog] iOS 12 virtual keyboard cannot close if an input is on a Dialog

### ISSUE THREAD

**Issue by dalhaan** [radix-ui/primitives#1609]
### Current Behavior

On iOS 12 Safari, when an input is on a dialog, the virtual keyboard cannot close when pressing the 'done' button.

The keyboard closes then immediately reopens.

### Expected behavior

The virtual keyboard will be able to close when pressing the 'done' button.

### Reproducible example

https://codesandbox.io/s/6778de?module=App.js

### Suggested solution

I'm not 100% sure but it seems like the dialog is refocussing the input. The strange thing is it only happen on old iOS versions (<=12).

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Dialog     |    1.0.0     |
| React            | n/a     |     17.0.2    |
| Browser          |     Safari iOS    |   12      |
| Assistive tech   |    n/a     |    n/a     |
| Node             | n/a     |    16.14.0     |
| npm/yarn         |     yarn    |    1.22.18     |
| Operating System |    MacOS     |     12.3    |

**Comment by andy-hook** [comment]
Hey @dalhaan, we don't actively support this older version.
Here's our support matrix:

```
browsers: 'Chrome >= 74, Safari >= 13.1, iOS >= 13.3, Firefox >= 78, Edge >= 79',
```

**Comment by dalhaan** [comment]
No worries! Thanks for the quick response.

**Comment by emroot** [comment]
@andy-hook this seems to keep happening on newer devices with chrome on iOS. I have an iPhone 13 pro on iOS 16+. 
If you open the example @dalhaan sent, the keyboard doesn't close on chrome iOS when pressing "Done". 
When you press "Done" it selects the whole text in the input. Not sure why this is happening.

**Comment by emroot** [comment]
You can try this one too: https://www.radix-ui.com/docs/primitives/components/dialog

**Comment by benoitgrelard** [comment]
@emroot it is not supposed to close the dialog when pressing "Done" on the iOS virtual keyboard. It is supposed to close when pressing the "Saves Changes" button in the UI.

Pressing "Done" on the iOS virtual keyboard, just hides it.

**Comment by emroot** [comment]
Right that’s what I’m saying when you press done in chrome on iOS it doesn’t close the virtual keyboard. Never mentioned closing the dialog.

**Comment by emroot** [comment]
Here’s a demo. I keep pressing done and the keyboard doesn’t hide. It keeps refocusing on my input
https://user-images.githubusercontent.com/110190/210414611-6cbc2d3b-6706-416e-8b7d-80e865c9f792.MOV

**Comment by benoitgrelard** [comment]
Weird, I don't have this issue on iOS safari, aren't all browsers webkit on iOS?

**Comment by emroot** [comment]
Right it’s only on chrome somehow.

**Comment by emroot** [comment]
@benoitgrelard should I open a separate issue for this? curious if you have any idea why this happening
