### ISSUE TITLE
[Popper][Tooltip] TooltipContent doesn't follow trigger

### ISSUE THREAD

**Issue by hoop71** [radix-ui/primitives#1612]
### Current Behavior

It appears that `fontFamilies` can impact how the `<Tooltip />` works.

https://www.loom.com/share/a3cd16ed914f4887ac82e7a285616b16

// Fonts that break
Arial :x:
Serif :x:
Monospace :x:
sans-serif :x:

// Fonts that work
Cursive :white_check_mark: 
Fantasy :white_check_mark:

### Expected behavior

Tooltip tracks trigger regardless of font used.

### Reproducible example

[Slider  + Tooltip (forked) - CodeSandbox](https://codesandbox.io/s/slider-tooltip-forked-8ck3h1?file=/App.js)

[Reference from Discord](https://discord.com/channels/752614004387610674/803656530259738674/946696605850017832)

### Additional context

Implementing this for a custom library following the Discord example above. Went through tons of permutations on what's happening but it feels like the `fontFamily` is the culprit for whatever reason. Might have been introduced with this update? 

https://github.com/radix-ui/primitives/blob/main/packages/react/popper/src/Popper.tsx#L260

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-tooltip / react-slider       | latest - 1.0.x        |
| React            | n/a     |   18.3.0next      |
| Browser          |   Chrome && FireFox      |   104.0.5112.79 / 99.0.1     |
| Assistive tech   |   n/a      |  n/a        |
| Node             | n/a     |         |
| npm/yarn         |         |         |

**Comment by andy-hook** [comment]
Hey @hoop71 , thanks for raising. Seems the new popper logic isn’t updating unless the physical dimensions of the floating element change or we resize the window. That would explain why differing fonts are having an impact, you can see this in action at the extremes of the slider when string length changes.  

Here’s the same example with forced re-mount via updating key:

https://codesandbox.io/s/slider-tooltip-forked-uwghu3?file=/App.js

We should investigate, I imagine there is crossover with https://github.com/radix-ui/primitives/issues/1567

**Comment by benoitgrelard** [comment]
Hey @hoop71,

When #2092 merges, you'll be able to pass a new option for cases like this when the optimized positioning isn't enough and you want the position to always update (rAF-based).

**Comment by hoop71** [comment]
@benoitgrelard Love this. Thanks for the work here! ❤️ Radix

**Comment by benoitgrelard** [comment]
You can use the RC already if you want btw 🙂
