### ISSUE TITLE
[Radix Tooltip 1.0.0] collisionPadding and arrowPadding not recognized as props

### ISSUE THREAD

**Issue by dannyhkim** [radix-ui/primitives#1613]
### Current Behavior
On the first hover of a tooltip, I get warnings saying that React does not recognize the `collisionPadding` prop on a DOM element. React does not recognize the `arrowPadding` prop on a DOM element.

<img width="409" alt="Screen Shot 2022-08-11 at 12 36 32 PM" src="https://user-images.githubusercontent.com/43249425/184185294-51631de7-e7bd-4192-a6df-179fa1ca9a10.png">
<img width="414" alt="Screen Shot 2022-08-11 at 12 36 52 PM" src="https://user-images.githubusercontent.com/43249425/184185463-de92f95d-6568-4392-bb2f-ba9d407ac6b3.png">

### Expected behavior
Should not expect these errors to be occurring. 

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |@radix-ui/react-tooltip| 1.0.0 |
| React            | n/a     |  17.0.2       |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by andy-hook** [comment]
Hey @dannyhkim would you be able to provide a reproduction of this issue in a code sandbox? the one attached to your description appears to be the blank template.

Thanks!

**Comment by andy-hook** [comment]
I'm going to close this for now, please follow up with a repro if you're still having problems.
