### ISSUE TITLE
[New Primitive] `MultiSelect`

### ISSUE THREAD

**Issue by rafaell-lycan** [radix-ui/primitives#1614]
### Overview

I'd love to see a new primitive that works as a multi-select component where it could extend the functionality of the Select itself by allowing multi-selection and displaying the information accordingly. 

![image](https://user-images.githubusercontent.com/1516450/184315353-45063765-bb07-4226-bc37-8a3f365afe19.png)
![image](https://user-images.githubusercontent.com/1516450/184315531-560c4150-2f92-46ee-a8db-bd947b7c5883.png)

### Examples in other libraries

Good examples would be the good old [jQuery Chosen](https://harvesthq.github.io/chosen/) or something already on the React ecosystem such as [React Select](https://react-select.com/home).

### Who does this impact? Who is this for?

Anyone who wants to build custom/complex forms which is quite a lot of people.

At this point, the only available solution is [React Select](https://react-select.com/home) is the only viable option out there giving the research my team and I were doing over the past few weeks due to the lack of support of the current Select primitive.

### Additional context

It would be nice to see Select at least supporting multi-selection somehow.

**Comment by norman-ags** [comment]
I think this is more like Combobox since it has that `input` element.

**Comment by jlarmstrongiv** [comment]
Reminds me of https://www.downshift-js.com/use-multiple-selection/

**Comment by andy-hook** [comment]
> I think this is more like Combobox since it has that `input` element.

I agree, this would be covered by https://github.com/radix-ui/primitives/issues/1342

**Comment by sersavan** [comment]
I've assembled one using shadcn/radix-ui primitives
Try it: https://shadcn-multi-select-component.vercel.app/

**Comment by johirhaquedipok** [comment]
I think you are talking about this one. 
https://ariakit.org/examples/combobox-radix
Using just the necessary Ariakit components to build a [Combobox](https://ariakit.org/components/combobox) with [Radix UI⁠](https://radix-ui.com/). For projects already using Radix UI and looking for autocomplete, autosuggest and search features.
