### ISSUE TITLE
[Popover]: Hydration error when popover is open by default of forceMount is used

### ISSUE THREAD

**Issue by Haberkamp** [radix-ui/primitives#1618]
### Current Behavior

When either the `open` prop of the popover root component is true or the portal component has been force mounted next.js will show an hydration error. 

### Expected behavior

The hydration error should not be there.

### Reproducible example

GitHub repository: https://github.com/Haberkamp/nextjs-radix-popover

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/popover      |    1.0.0    |
| React            | n/a     |    18.2.0     |
| Browser          |    n/a     |    n/a     |
| Assistive tech   |     n/a    |   n/a      |
| Node             | n/a     |     16.14.0    |
| npm/yarn         |   yarn      |   1.22.19      |
| Operating System |     MacOS    |  12.5       |

**Comment by andy-hook** [comment]
Hi @Haberkamp , thanks for raising. This is a known issue and being tracked in https://github.com/radix-ui/primitives/issues/1386

A workaround is to wrap your app in an element and pass the node reference to `portal` [using the `container` prop](https://www.radix-ui.com/docs/primitives/components/popover#portal).
