### ISSUE TITLE
[DropdownMenu] pressing Enter on Trigger opens anchor link on Firefox

### ISSUE THREAD

**Issue by giubatt** [radix-ui/primitives#1622]
### Current Behavior

On Firefox, if you have a dropdown where the first `DropdownMenu.Item` with `asChild` and the child is an `a` tag, when navigating with the keyboard and focusing on the `DropdownMenu.Trigger` and pressing Enter the anchor tag link is triggered as if it was clicked/selected.

### Expected behavior

When pressing Space with the `Trigger` focused it only opens the dropdown, as expected. On Chrome both keys only open the dropdown
On Firefox this should work the same way.

### Reproducible example

I forked the menu example from the docs to illustrate, the only thing I changed is adding `asChild` to the first dropdown item, and adding a `<a>` around it with an `href`
https://codesandbox.io/s/patient-http-il6epv?file=/App.js

### Suggested solution

This should work as in Chrome, both the Space and Enter keys should only open the dropdown and not trigger any interactions with any items inside

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     DropdownMenu    |   v1.0.0      |
| React            | n/a     |      18   |
| Browser          |    Firefox     |     103.0.2    |
| Operating System |     Manjaro    |    Latest     |

**Comment by jjenzz** [comment]
related https://github.com/radix-ui/primitives/issues/1268

**Comment by giubatt** [comment]
I managed to apparently fix this locally, but it would be nice if I didn't need to do this as it feels kinda hacky, this is what I did with the `Trigger` component: 

```tsx
import { forwardRef, useImperativeHandle, useRef } from "react"
import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu"

const Trigger = forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Trigger>,
  React.ComponentProps<typeof DropdownMenuPrimitive.Trigger>
>(function Trigger({ ...props }, ref) {
  const innerRef = useRef<HTMLButtonElement>(null)
  useImperativeHandle<
    HTMLButtonElement | null,
    HTMLButtonElement | null
  >(ref, () => innerRef.current)

  return (
    <DropdownMenuPrimitive.Trigger
      {...props}
      ref={innerRef}
      onKeyDownCapture={(event) => {
        if (event.key === "Enter") {
          event.preventDefault()
          innerRef.current?.dispatchEvent(
            new KeyboardEvent(event.type, { key: " ", bubbles: true })
          )
        }
      }}
    />
  )
})
```

Basically if it's an `Enter` keyDown event, I instead prevent default and send a `Spacebar` keyDown event to the element, which currently has the same behaviour but without the bug on firefox
![image](https://user-images.githubusercontent.com/12552164/185924734-978142dc-ee02-44fa-8f88-730af87b973b.png)

**Comment by benoitgrelard** [comment]
This has now been fixed and is available in latest rc.
