### ISSUE TITLE
[NavigationMenu] Creating a SEO friendly NavigationMenu with submenus using forceMount is impossible, because content is not being applied data-state correctly.

### ISSUE THREAD

**Issue by joriregter** [radix-ui/primitives#1623]
### Current Behavior

Creating a SEO friendly NavigationMenu with submenus using forceMount is impossible at this moment, due to the fact that data-state is not applied to the Content component correctly. In other words, setting forceMount on both Content and Viewport makes sure the content is mounted at all times, making the submenus crawlable. However, when hovering on menu items with a sub menu, the active sub menu's Content component does not get a data-state property, which means you can't apply active menu styling in any way.

### Expected behavior

The active sub menu's Content component should get a data-state property indicating if it's opened or closed when using forceMount on Content and Viewport.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/bold-stitch-y646ze?file=/src/App.tsx)

### Suggested solution

Set the data-state property on Content components at all times.

### Additional context

None

### Your environment

Latest Navigation Menu package, the rest doesn't impact bug, see CodeSandbox.

**Comment by joriregter** [comment]
Linked to #1273.

**Comment by andy-hook** [comment]
Hey @joriregter this is definitely a pain point at the moment, we're exploring additional mounting options / apis for the primitives in general which should alleviate these issues in the future.

For now this looks well represented by https://github.com/radix-ui/primitives/issues/1273 so I'm going to close in favour.
