### ISSUE TITLE
Add warning about ref forwarding for HoverCard's Trigger

### ISSUE THREAD

**Issue by justasam** [radix-ui/primitives#1628]
## Documentation

Add a warning near `HoverCard.Trigger` `asChild` description: `the supplied element should have ref forwarding when asChild={true}`. 

Motivation for this: we were using a custom `Link` component which did not have ref forwarding and the `Tooltip` did not work correctly. The errors were not very clear and it took some detective work to resolve. Although it might seem obvious, I think warning would prevent at least some of these cases 😅 

### Relevant Radix Component(s)

`HoverCard.Trigger`

**Comment by benoitgrelard** [comment]
Hi @justasam,

Unfortunately AFAIK there isn't much we can do here to warn users who use `asChild` whilst being able to prevent this warning if they have used `forwardRef` as I don't think we can determinate this.

AFAIK React is the only one that knows that, hence why they do output a dev warning when a `ref` is tentatively attached to a functional component (a non ref-forwarding component).

I will close the issue as I don't think this is possible, and hopefully in the future React removes the whole ref dance (they've been indicating this for a few years now).

Please let me know though if you can think of a way.

✌️

**Comment by justasam** [comment]
Hey @benoitgrelard, I was referring more to adding the warning to the [documentation itself](https://www.radix-ui.com/docs/primitives/components/hover-card#trigger), rather than warnings in code. Although now that I am thinking about it, it would be a very niche thing, so maybe it's not worth it 🤷 

Thanks for taking your time to respond regardless 🙇‍♂️

**Comment by benoitgrelard** [comment]
Ah gotcha, in which case we are planning to do this with a dedicated page on `asChild` https://github.com/radix-ui/website/issues/269
