### ISSUE TITLE
When closing a dialog with multiple triggers wrong trigger get focus

### ISSUE THREAD

**Issue by augustskare** [radix-ui/primitives#1629]
### Current Behavior

When using more than one trigger for a dialog the last trigger is always focused when the dialog is closed. 

### Expected behavior

The trigger that triggers the opening of the dialog should be focused.

### Reproducible example

[CodeSandbox example with multiple triggers](https://codesandbox.io/s/dazzling-albattani-z16jhp)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-dialog    |   1.0.0      |
| React            | n/a     |    17.0.2     |
| Browser          |    Firefox    |    104.0b10     |
| Assistive tech   |    n/a     |    n/a     |
| Node             | n/a     |    16.15.0     |
| npm/yarn         |    npm     |    8.5.5     |
| Operating System |     macOS    |    12.4     |

**Comment by benoitgrelard** [comment]
Hi @augustskare,

This isn't a feature we support so the behaviour is expected.

If you want to have the same dialog that can be opened from a few different places, we recommend making a re-usable component rather than trying to re-use the same instance.

**Comment by augustskare** [comment]
Ok, thanks for the clarification! 😊
