### ISSUE TITLE
[Slider] onMouseDown and onMouseUp events are not fired

### ISSUE THREAD

**Issue by Bailig** [radix-ui/primitives#1640]
### Current Behavior

the `onMouseDown` and  `onMouseUp` does not fire. I'm not very sure if it's by design.

```
const SliderDemo = () => (
  <form>
    <StyledSlider
      onMouseDown={() => console.log("onMouseDown")}
      onMouseUp={() => console.log("onMouseUp")}
    >
      <StyledTrack>
        <StyledRange />
      </StyledTrack>
      <StyledThumb />
    </StyledSlider>
  </form>
);
```

### Expected behavior

When clicking on the element, fire the `onMouseDown` before `onValueChange` and fire the `onMouseUp` after last `onValueChange`.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-ui-slider-5x7l3o?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-slider    |    1.0.0     |
| React            | n/a     |     18.2.0    |
| Browser          |    Chrome     |    104.0.5112.101 (Official Build) (x86_64)     |
| Assistive tech   |         |         |
| Node             | n/a     |     16.14.2    |
| npm/yarn         |    pnpm     |    7.9.5     |
| Operating System |    macOS     |    11.5.2     |

**Comment by paperstick** [comment]
Hi, @Bailig,

You can use `onPointerDown` and `onPointerUp`, which will be triggered for both mouse and pointer events, and suit all your needs.

**Comment by benoitgrelard** [comment]
Hi @Bailig, I wouldn't say it's "by design" but more of a consequence of an implementation detail.

Essentially this is due to this:

https://github.com/radix-ui/primitives/blob/83a8c13bf66f3d9f17d77caeb187a69eb146930b/packages/react/slider/src/Slider.tsx#L383-L384

@jjenzz do you think there would be other ways around it? I don't think so at first glance…

The suggestion from @paperstick makes sense otherwise.

**Comment by Bailig** [comment]
Hi @paperstick, Thanks! It works perfectly.

Hi @benoitgrelard, maybe worth mentioning in the doc? I think onMouseDown and onMouseUp are pretty commonly used events.

**Comment by benoitgrelard** [comment]
@Bailig I've added an issue in the docs for us to add a mention of that.
