### ISSUE TITLE
Select default value not SSR

### ISSUE THREAD

**Issue by glenarama** [radix-ui/primitives#1642]
### Current Behavior

When using a default value on the Select the select trigger is rendered empty on the server, and is dynamically propagated on page load. This causes a layout shifting issue on page load. 
If I use an html select, the default value is in place upon page load.

```
    <Select.Root defaultValue="two">
```

### Reproducible example

The storybook example replicates this if used in a next.js app - you will not see this issue within storybook as it seem to load components dynamically anyway.

**Comment by benoitgrelard** [comment]
Hi @glenarama,

That is expected as server side, it cannot know what the options are. If you need SSR to work, we recommend you control the displayed value yourself as per this example: https://www.radix-ui.com/docs/primitives/components/select#controlling-the-value-displayed-in-the-trigger

**Comment by tgds** [comment]
> Hi @glenarama,
> 
> That is expected as server side, it cannot know what the options are. If you need SSR to work, we recommend you control the displayed value yourself as per this example: https://www.radix-ui.com/docs/primitives/components/select#controlling-the-value-displayed-in-the-trigger

Hi @benoitgrelard. I'm sorry, but I don't think I follow. Can you expand on what you mean by saying that we cannot know what the options are on the server side? That doesn't seem true to me.

**Comment by peteruithoven** [comment]
I've experienced the same issue in Next.js, only found this issue after making a simple example of this issue:
https://stackblitz.com/edit/stackblitz-starters-4hvrei?description=The%20React%20framework%20for%20production&file=app%2Fpage.tsx,tailwind.config.ts,app%2FSelectDemo.tsx,app%2Flayout.tsx&title=Next.js%20Starter

https://github.com/radix-ui/primitives/assets/523210/a42375e4-4841-4897-94e0-713b4ce7638a

Based on @benoitgrelard suggestion and the following docs I added to the example a SSR ready Select where I control the label that's shown.  
https://www.radix-ui.com/primitives/docs/components/select#controlling-the-value-displayed-in-the-trigger

Just to make this issue and solution easier to find:
- Flash without default label
- Flash of no default value
- Label only filled in client side
