### ISSUE TITLE
Avatar component doesn't render image in jest

### ISSUE THREAD

**Issue by ming2024** [radix-ui/primitives#1645]
### Current Behavior

Avatar component is working fine in DOM, it rendered an image but failed in test

### Expected behavior

should render an image in jest

<img width="415" alt="image" src="https://user-images.githubusercontent.com/111698568/188449646-721a7af3-ba2b-406b-8524-635888983b68.png">

### Reproducible example
https://github.com/ming2024/avatar-radix-testing

https://github.com/ming2024/avatar-radix-testing/blob/main/src/AvatarRadix.test.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |        ^1.0.0 | 
| React            | n/a     |         ^18.2.0|
| Node             | n/a     |         v16.15.1|
| npm/yarn         |         |         8.11.0|
| Operating System |         |         mac|

**Comment by andy-hook** [comment]
@ming2024 Avatar doesn't render an image element until the resource has loaded which is what jest is reporting in your debug call.

You need to mock the load event, though I'd suggest forgoing this type of test as it's already covered by the library. If however you need to do this for other reasons [check out the test file](https://github.com/radix-ui/primitives/blob/8f75e5be679b9c269638bddf532a166d80edecb4/packages/react/avatar/src/Avatar.test.tsx#L34-L43) for more info on this approach.
