### ISSUE TITLE
The sub content is shifting right and can’t be clicked

### ISSUE THREAD

**Issue by Yusifdhrgam1999** [radix-ui/primitives#1646]
The sub content is shifting right and can’t be clicked Because its disappear so i need to fix the shifting please.
The code to see it
When you click the click me to play in the top-left of the video you can see it
https://codesandbox.io/s/cool-meninsky-ze7szz?file=/Selectseasons.js

**Comment by benoitgrelard** [comment]
It seems you are rendering a `SubContent` within a `SubContent`. That's where your issue is coming from.
