### ISSUE TITLE
App crash on safari < 13

### ISSUE THREAD

**Issue by nmhieu1896** [radix-ui/primitives#1648]
I dont know whether this is a bug or not. But ResizeObserver in react-use-size is not supported in safari 12. Is there any workaround for this ?

**Comment by andy-hook** [comment]
@nmhieu1896 You'll need to bundle your [own polyfill](https://www.npmjs.com/package/resize-observer-polyfill) as we don't support this browser, Radix compatibility is as follows:

``Chrome >= 74, Safari >= 13.1, iOS >= 13.3, Firefox >= 78, Edge >= 79``

Hope this helps!

**Comment by benoitgrelard** [comment]
Hey @nmhieu1896 we do not support Safari 12.

Here's our browserslist for reference:

https://github.com/radix-ui/primitives/blob/8f75e5be679b9c269638bddf532a166d80edecb4/babel.config.js#L30

If you wanted to make things work on older versions you would have to look at adding polyfills.

**Comment by nmhieu1896** [comment]
Thank you for your quick responses. So I will workaround by this:
`if (
  typeof document !== 'undefined' &&
  typeof window.ResizeObserver === 'undefined'
) {
  window.ResizeObserver = function () {
    return {
      observe() {},
      unobserve() {},
    };
  };
}`

**Comment by benoitgrelard** [comment]
That's not a correct polyfill though, just an empty implementation, meaning that measurements won't be available if you do that. You'll have to use a polyfill like the one @andy-hook linked to.

**Comment by nmhieu1896** [comment]
> That's not a correct polyfill though, just an empty implementation, meaning that measurements won't be available if you do that. You'll have to use a polyfill like the one @andy-hook linked to.

Ah, I see, dont know why I missed that part. Thank you!!!
