### ISSUE TITLE
Slider - option to change value when finished sliding/dragging

### ISSUE THREAD

**Issue by dungle-scrubs** [radix-ui/primitives#1650]
## Feature request

The ability to fire `onValueChange` when finished dragging the slider.

### Examples in other libraries

React Aria has a prop called `onChangeEnd` in addition to `onChange`

### Who does this impact? Who is this for?

I think this would be helpful for anyone depending on the situation.

### Additional context

For me, I'm using `Slider` for a price filter using Algolia. Currently, it's fetching new filtered records too rapidly and I'd like it to only do it once when finished dragging.

Cheers

**Comment by benoitgrelard** [comment]
Already covered by #903
