### ISSUE TITLE
[POPOVER] Content Position with Custom Trigger Components

### ISSUE THREAD

**Issue by joao99jobs** [radix-ui/primitives#1661]
## Question

Hi!

I'm trying to work with the Popover component but I'm having a problem when I want the trigger to be a custom component.
When I put it on a button directly inside the Trigger, the Popover positioning works normally (I think it can identify the component type and calculate the position, that's a guess)
But when I place a button via props, it can't identify where the Popover should be placed.

I made an example to demonstrate...
https://codesandbox.io/s/thirsty-dawn-dt5itk?file=/App.js

Could you show me the best way? Thanks!!!

**Comment by andy-hook** [comment]
Hey @joao99jobs , for custom components to compose correctly you need to forward `props` and `ref` to the returned element.

https://codesandbox.io/s/recursing-germain-8c896m?file=/App.js

Hope this helps!
