### ISSUE TITLE
[Dialog] position relative to the body breaks layout

### ISSUE THREAD

**Issue by robvadi** [radix-ui/primitives#1662]
### Current Behavior

- The `dialog` it's adding a `position: relative !important` to the `body` tag.

### Expected behavior

- Don't add `position: relative !important` to the `body` tag.

Maybe this `position: relative !important` it's added for solve something else? at the moment when I manually remove it don't see that affects anything, maybe somebody have the answer of this.

### Suggested solution

- Remove `position: relative !important` of the `body` tag, this will avoid content `behind` the dialog breaks.

Because the `dialog` box it's already set to `position: fixed` there is no need to add `position: relative` to it's parent, as the specs of a fixed element describes:

> The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to the initial [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) established by the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport)

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dialog     |   latest      |
| React            |     |    18     |
| Browser          |   Chrome - Firefox - Safari     |    latest    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   OSX      |    latest      |

**Comment by benoitgrelard** [comment]
> Maybe this position: relative !important it's added for solve something else?

You are bang on here. This is added by a 3rd party lib which prevents scrolling (`react-remove-scroll`) so we don't have control over it at this point unfortunately.

I will close the issue as it isn't something we can change right now, however please do comment with your issue and maybe a sandbox so we can offer potential suggestions/workarounds.

**Comment by remainstheday** [comment]
This is a serious issue for me! Does anyone have a workaround? Seems like Radix could at least add an extra prop to disable the `position: relative !important;` functionality.
