### ISSUE TITLE
Mismatched ID on on server side render app even with react 18

### ISSUE THREAD

**Issue by sharmapukar217** [radix-ui/primitives#1684]
I'm using radix ui for my project using react 18 for ssr(rakkas js). As per the documentation, it should work without any error but I'm getting Warning: Prop `aria-controls` did not match. Server: "radix-:R2lq:" Client: "radix-:Rle:"

**Comment by andy-hook** [comment]
@sharmapukar217 Would you be able to provide a minimal repro via CSB or cloneable project?

**Comment by sharmapukar217** [comment]
Oh that's solved now. I was going to close this issue. For details [check rakkas js](https://github.com/rakkasjs/rakkasjs/issues/55)

**Comment by MrDigii** [comment]
Hi, I am using the latest Nextjs 13 Version (13.4.12) with React 18.2.0. It's a clean Nextjs project with the new app directory and Tailwind. If I'm using any of the radix-ui primitives I getting the warning from @radix-ui/react-slot:
```
Warning: Prop `aria-controls` did not match. Server:
```

Project: https://github.com/MrDigii/musify

Any ideas?

**Comment by joaom00** [comment]
@MrDigii Seems to be an issue on the Next.js side https://github.com/vercel/next.js/pull/53216. You can try install the canary version `next@canary`

**Comment by MrDigii** [comment]
@joaom00 Oh thank you, now it works 🥇

**Comment by Princekrampah** [comment]
@joaom00 Thanks, this worked for me too.
