### ISSUE TITLE
[ContextMenu] Scroll to top when on absolute container

### ISSUE THREAD

**Issue by cabello** [radix-ui/primitives#1688]
### Current Behavior

I have a context menu inside an absolute container, this container is powered by react-window (long virtual lists).

When I use Portal (attach to document.body) it doesn't show up. 
When I don't use a portal it shows up for items before scroll but for items that require scrolling down it **scrolls to top** when I right click and not show the menu.

### Expected behavior

Not to scroll to the top and show the menu there.

### Reproducible example

https://user-images.githubusercontent.com/60936/192516916-043eb7d6-ed6a-45be-ae8e-4142d12dd074.mp4

### Suggested solution

I suspect this could be popper configuration issue, we have a few poppers given tooltips and menus in our app.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-context-menu     |    1.0.0     |
| React            | n/a     |   17      |
| Browser          |  Chrome       |  105       |
| Assistive tech   |         |         |
| Node             | n/a     |  16.14.0       |
| npm/yarn         | yarn        |    1.22.19     |
| Operating System |   macOS     |   12.6      |

**Comment by benoitgrelard** [comment]
Hey @cabello,

You report using version  `1.7.0` of `@radix-ui/react-context-menu` which I don't think exists.
If you're using an older version from `1.0.0` then it's likely by upgrading your issue would be fixed.
If you are indeed using `1.0.0` then it would be very helpful if you could provide a reproduction in a codesandbox.

Thanks!

**Comment by cabello** [comment]
Hi @benoitgrelard , it was a typo 🙈 I am using 1.0.0.

**Comment by benoitgrelard** [comment]
In this case, a reproduction would be great because at first glance, there's no reason why it shouldn't work in your scenario.
