### ISSUE TITLE
[Tooltip] Shouldn't open if trigger is clicked **before** the tooltip opens

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#1691]
## Bug report

Originally from Discord: https://discord.com/channels/752614004387610674/1024287951485677579/1024566578873913384

**Comment by AlbertoTonegari** [comment]
This change in **Tooltip.tsx** fixes the issue with the tooltip:

`onClick={composeEventHandlers(props.onClick, (event) => {
            // keyboard click will occur under different conditions for different node
            // types so we use `onClick` instead of `onKeyDown` to respect that
            const isKeyboardClick = event.detail === 0;
            const mouseClick = event.detail === 1; // new code

            if (isKeyboardClick) context.onClose();
            if (mouseClick) context.onClose(); // new code
          })}`
          
Here is the link to the sendbox wha:
https://codesandbox.io/s/compassionate-tree-mwwv65?file=/Tooltip.js:2772-2787

**Comment by benoitgrelard** [comment]
That isn't a fix though, because this is breaking the very same behaviour for keyboard.
Self note for later: The fix is likely to be to mark an interaction in `onEscapeKeydown` on `DismissableLayer` and use that to prevent opening in such case.

**Comment by benoitgrelard** [comment]
Actually, sorry I didn't realise you were handling both cases.
I think you're right because technically we don't just "close" in `onClose` we cancel the timer too, so that means any click could be considered an interaction (not just keyboard click) therefore, negating the extra close onEscapeKeydown.

Do you want to submit a PR @AlbertoTonegari?

**Comment by AlbertoTonegari** [comment]
Sounds good. Yes, I can submit a PR for this issue.
Thanks, @benoitgrelard !

**Comment by AlbertoTonegari** [comment]
Here is the [PR](https://github.com/radix-ui/primitives/pull/1693).

**Comment by sam-potter** [comment]
I'm still seeing this issue in `1.0.2`?

And it's still currently an issue in the example docs page: https://www.radix-ui.com/docs/primitives/components/tooltip

**Comment by sam-potter** [comment]
Appreciate the response (and this great library), I apologise I've misread this issue.

I believed the intended behaviour to be that the tooltip content  _should always_ open when hovering over the trigger, and that clicking the trigger before content appears _shouldn't_ prevent the content from opening.

I now see that's not the case. I'm curious why it was decided that clicking the trigger cancelling opening the content was the optimal UX? Should there be an option to disable this?

**Comment by benoitgrelard** [comment]
> I believed the intended behaviour to be that the tooltip content should always open when hovering over the trigger, and that clicking the trigger before content appears shouldn't prevent the content from opening.

Interesting haha, yeah originally it had the behaviour you are asking and the original issue was asking exactly for the opposite.

> I now see that's not the case. I'm curious why it was decided that clicking the trigger cancelling opening the content was the optimal UX? Should there be an option to disable this?

Tooltips are "tips about tools", ie. they are little tidbits of info for the tool is going to do when you activate it. With that in mind, you can see how in a given UI, a new user might hover over tools to check what they do the first few times. But at the same time, you can see how someone who's been using the UI for a really long time, it might get annoying to see the tooltip pop-out everytime you click on a button.

Ultimately that is why we decided this was a better default.

**Comment by sam-potter** [comment]
> Tooltips are "tips about tools", ie. they are little tidbits of info for the tool is going to do when you activate it. With that in mind, you can see how in a given UI, a new user might hover over tools to check what they do the first few times. But at the same time, you can see how someone who's been using the UI for a really long time, it might get annoying to see the tooltip pop-out everytime you click on a button.

This makes complete sense and is certainly a much better UX for it to not open.

> I believed the intended behaviour to be that the tooltip content _should always_ open when hovering over the trigger, and that clicking the trigger before content appears _shouldn't_ prevent the content from opening.

The use case I had in mind is similar to how Stripe use tooltips, i.e. the trigger is literally for the tooltip and tooltip only. Essentially, clicking the trigger has no impact on the opening _or_ closing of the content. How would you suggest implementing this behaviour?

![image](https://user-images.githubusercontent.com/15123145/206573048-e5c7e286-4f99-456b-aca5-333e1dede4ba.png)

**Comment by benoitgrelard** [comment]
Could you point me to the page where you took that screenshot?

**Comment by sam-potter** [comment]
It's on [Stripe's dashboard](https://dashboard.stripe.com/), unfortunately couldn't find an example on their public site

**Comment by benoitgrelard** [comment]
Right, my guess is that it's not accessible to keyboard/screenreader users.
Generally what I would recommend for this if there is no action, then it's a `Popover` which you open on click and is accessible for keyboard/screenreaders.

**Comment by sam-potter** [comment]
Okay great, thanks for the help!
