### ISSUE TITLE
[Switch] Pass back the `event` with `onCheckedChange`

### ISSUE THREAD

**Issue by cchaos** [radix-ui/primitives#1697]
### Overview

Is it possible to pass back the `event` as the second parameter of `onCheckedChange`?

### Who does this impact? Who is this for?

I'm switching some of our own internals to Radix as the headless portions for an internal component library and our engineers needs access to the event for parity.

### Additional context

Thank you! 😄

**Comment by benoitgrelard** [comment]
Hey @cchaos this isn't something we will provide as this is an implementation detail and the change event might not even exist (when rendered outside a form).

You should be able to interact with our API regardless but let us know if you have a specific use-case in mind where it's causing issues.

Some further related reading too: #734

**Comment by cchaos** [comment]
Thanks @benoitgrelard though that referenced issue doesn't have a solution that works for us. Instead we ended up using a combination of `checked` and `onClick` with our own `onChange` method. For those looking for a solution, this (mostly) worked for us except for the mis-match in event types I can't seem to fix:


```tsx
export const Switch: FunctionComponent<Props> = ({
  checked,
  onChange,
}) => {
  const [isChecked, setIsChecked] = useState(checked)

  const changeHandler = (event: MouseEventHandler<HTMLButtonElement>) => {
    onChange(!isChecked, event)
    setIsChecked(!isChecked)
  }

  const switchNode = (
    <Switch.Root
      checked={checked}
      onClick={changeHandler}
    >
      <Switch.Thumb />
    </Switch.Root>
  )
}
```

TBF, I still don't really understand the need for the `event` either and I couldn't really find instance of people using it, just mostly that I didn't want to break current instances JIC.
