### ISSUE TITLE
[AlertDialog] Buttons doesn't work with component

### ISSUE THREAD

**Issue by BrunoAwdd** [radix-ui/primitives#1722]
I'm trying to place my custom buttons. It's not worth retyping my classes every time I use a button, so I left them in a component function.

When I use my component as a child, the button doesn't open the Dialog. If you copy the exact HTML code and use it as a child, the problem disappears.

Any suggestion?

**Comment by benoitgrelard** [comment]
Are you using the `asChild` prop?

**Comment by BrunoAwdd** [comment]
Thanks.

I changed my code to:

```
interface ButtonProps {
  children: React.ReactNode;
  [x: string]: any;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(({ children, props }: ButtonProps, ref) => {
  return (
    <button {...props} ref={ref}>
      {children}
    </button>
  );
});

export default Button;
```

And I still getting: "Uncaught TypeError: Cannot read properties of undefined (reading 'defaultPrevented')"

what am i doing wrong?

**Comment by benoitgrelard** [comment]
The way you've written it, you're saying there's a prop called `props`.
You need to gather them doing `...props` instead.

So with what you have:

- either do `{ children, ...props }`
- or just do `(props: ButtonProps, ref)` and `<button {...props} ref={ref} />`

**Comment by andy-hook** [comment]
Just for absolute clarity, here's an [example](https://codesandbox.io/s/aschild-prop-ref-forwarding-yxr8ys?file=/src/App.tsx) of what @benoitgrelard is describing.

I'm going to close this now as that should satisfy your original query, hope this helps.
