### ISSUE TITLE
[AlertDialog] Latest release of react-alert-dialog broke functionality for children react-dropdown-menu.

### ISSUE THREAD

**Issue by ben-hapip** [radix-ui/primitives#1726]
## Bug report

With the release of 1.0.2 of react-alert-dialog, it has since broken one of the buttons on our app. The layout is a modal using react-alert-dialog and in that there is a menu to select options, which uses react-dropdown-menu. I'll attach gifs below. Here is the structure of the component

Modal component:
```
    <Modal>
       <Menu isModal={false}>
               {children}
       </Menu>
    </Modal>
```

Modal is react-alert-dialog in this case and Menu is the react-dropdown-menu

Before update:

![before](https://user-images.githubusercontent.com/17172000/196282097-1332a473-0fd5-4848-8f4b-ace4f07cbb4d.gif)

After update:
![UpdatedPackage](https://user-images.githubusercontent.com/17172000/196282111-2d29aa48-9a16-4c67-9645-fb86b69c0245.gif)

The update to the package makes this button now unusable :(

Any help would be greatly appreciated! I did notice this is only happening when the modal prop for the Root component of react-dropdown-menu is false...e.g. ```<Root modal={false} />```

**Comment by benoitgrelard** [comment]
Hey @ben-hapip,

Out of the gate, I can't think of any of the changes in this release that would cause this.

- Have you updated both packages to the latest versions?
- Which versions are you coming from?

**Comment by ben-hapip** [comment]
You're a legend @benoitgrelard. Just needed to update react-dropdown-menu to latest version! Thanks for the help
