### ISSUE TITLE
Primitive initial dom render loading issues

### ISSUE THREAD

**Issue by Mbensler** [radix-ui/primitives#1736]
### Current Behavior

Radix Navigation Menu and Popover are behaving weird on the initial dom load. The navigation menu renders vertically for a split second and then correctly goes horizontal. However this looks weird and ugly as none of the css has been applied. I've tried the exact same example in the docs, and it gives me the exact same behaviour.

Popovers are also moving weirdly on the initial load.

### Expected behavior

I expect the navigation menu to render horizontally on the initial dom load, and not vertically for a split second.

### Suggested solution

The menu would need to load correctly on the initial render.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   Navigation Menu, Popover      |    1.1.1 , 1.0.2    |
| React            | n/a     |     18.2    |
| Browser          |    All browsers     |     Newest versions    |
| Assistive tech   |         |         |
| Node             | n/a     |    16.18.0     |
| npm/yarn         |   8.19.2      |   1.22.19      |
| Operating System |   Windows      |     11    |

**Comment by andy-hook** [comment]
@Mbensler Seems like an issue with SSR rendering and your styling configuration rather than Radix specifically, what’s your stack?

**Comment by andy-hook** [comment]
Could you provide a sandbox code sample matching your configuration or an example github repro? I'm not familiar with styling custom components with chakra but it seems like the SSG step is not pre-rendering your styles, rather they are being hydrated by the bundle only.

**Comment by Mbensler** [comment]
I got it working by following the stitches SSR documentation: https://stitches.dev/docs/server-side-rendering
Even though I use SSG the SSR method works, and it seems it's necessary to have for Radix primitives to be pre-rendered.

**Comment by andy-hook** [comment]
Ah I didn't realise you were also using stitches here. Generally the pre-rendering of markup / styles will be similar whether it's static generation (SSG) or a server side response (SSR). To be clear though, stitches isn't required for Radix, you could use any css-in-js, tailwind or plain css solution.

But as you say, regardless of the library, most css-in-js will provide a method to make sure styles are applied prior to hydration, i'm happy you resolved it for Stitches in this case 👍

**Comment by Mbensler** [comment]
Hello again, I'm experiencing a related issue with the navigation menu.

Liked mentioned before I am using Stitches and this time with the provided example at: https://www.radix-ui.com/docs/primitives/components/navigation-menu

I have copy pasted the code from the navigation menu demo from the link above.

My stitches SSR config looks like this: 

```js
import { createStitches, keyframes } from '@stitches/react';
import * as PopoverPrimitive from '@radix-ui/react-popover';
export const { styled, getCssText } = createStitches({
  theme: {
    colors: {},
    space: {},
    fontSizes: {},
    fonts: {},
    fontWeights: {},
    lineHeights: {},
    letterSpacings: {},
    sizes: {},
    borderWidths: {},
    borderStyles: {},
    radii: {},
    shadows: {},
    zIndices: {},
    transitions: {},
  },
});
```

That SSR code is what solved my previous problem. However it seems there is something wrong with the SSR/SSG rendering.

I have attached a video showing my problem.

https://user-images.githubusercontent.com/3165204/197991814-78695196-24c7-4e37-aa27-d187489f8406.mp4

I have no idea how to solve this. I feel like I've tried everything.

**Comment by andy-hook** [comment]
@Mbensler Can you provide a minimal github repo with a matching configuration that demonstrates this problem?

**Comment by Mbensler** [comment]
Hello sorry for the late response. I've made a quick and dirty demo displaying the error.

Github repo can be found here: https://github.com/Mbensler/primitiveSSRdemoError
Demo can be found here: https://testdemo-ten.vercel.app//

Let me know if you need any additional details. Thanks in advance.

**Comment by andy-hook** [comment]
@Mbensler Your components should be consuming methods from the instance returned by `createStitches`. In your case you need to [update the destructure to include `keyframes` from `createStitches`](https://github.com/Mbensler/primitiveSSRdemoError/blob/e79f85a26ef2b17afc4087cf03f0b7f8a9994a53/stitches.config.ts#L8) rather than `@stitches/react`.

You also have a mixture of responsibilities here, I recommend moving all components out of `stitches.config` and making it only responsible for setting up the stitches configuration and exposing the methods which the components should be consuming.

Here is a simplified example repo showing the menu functioning correctly after a `build` and `serve`.

https://github.com/andy-hook/primitiveSSRdemoError

I recommend [joining the Stitches channel](https://discord.com/invite/H4eG3Mk) on our discord if you haven't already, the community are very good at providing guidance on best practice and styling architecture.

I'm going to close this issue now but I hope this helps 🙏 .
