### ISSUE TITLE
Alert dialog should dismiss when click on background overlay

### ISSUE THREAD

**Issue by clacladev** [radix-ui/primitives#1738]
### Overview

Alert and Dialogs should be aligned in UX when the user clicks on the background overlay. Alert should dismiss like Dialog does.

### Examples in other libraries

Radix-UI Dialog dismissed when user clicks on the background overlay [example](https://www.radix-ui.com/docs/primitives/components/dialog).
Alert does not [example](https://www.radix-ui.com/docs/primitives/components/alert-dialog).

### Who does this impact? Who is this for?

The users feel the my product which uses both Alert and Dialogs does not have a consistent UX.
The two by being very similar dialogs should have the same UX. Even more so because they already have the same behaviour on ESC key press.

**Comment by benoitgrelard** [comment]
Hey @clacladev,

This is by design because the `AlertDialog` should be used in more considered cases where an answer from the user is really necessary, therefore a dismissal by mistake could be an issue.

**Comment by atulmy** [comment]
@benoitgrelard having an option to enable this would be still useful. Certain cases, we need simplicity of Alert vs Dialog but still want user to dismiss.
Currently migrating from Reach UI to Radix and https://reach.tech/alert-dialog allows you to dismiss when clicked outside if needed.

**Comment by ejirocodes** [comment]
@atulmy, if you really want that functionality you can make use of  [dialog component](https://www.radix-ui.com/primitives/docs/components/dialog)

**Comment by benoitgrelard** [comment]
> @atulmy, if you really want that functionality you can make use of [dialog component](https://www.radix-ui.com/primitives/docs/components/dialog)

I was about to comment exactly that.

**Comment by imMatheus** [comment]
> @atulmy, if you really want that functionality you can make use of [dialog component](https://www.radix-ui.com/primitives/docs/components/dialog)

What you say is a good rule of thumb for using alert-dialog vs dialog would you say?
