### ISSUE TITLE
Add `disabled` to `ContextMenu`

### ISSUE THREAD

**Issue by Andarist** [radix-ui/primitives#1745]
## Feature request

It would be nice if `ContextMenu` could be disabled. We have a situation in which we conditionally want to disable the context menu - we can do that by conditionally rendering the `ContextMenu` wrapper but that remounts the wrapped tree.

**Comment by Andarist** [comment]
This also prevents the native context menu. I think that this is usually not something that you want. I'd be surprised, as a user, if my right click would not invoke anything at all.

**Comment by abbazabacto** [comment]
You are right, this is a case where I do want to prevent the native context menu.
Understand this is my solution than instead of the coming `disabled` feature. Thanks for your input!
