### ISSUE TITLE
[AlertDialog] Fails to close after async operation

### ISSUE THREAD

**Issue by sam-potter** [radix-ui/primitives#1747]
### Current Behavior

Alert dialog closes immediately

### Expected behavior

Should wait for the onSubmit handler to resolve before closing

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/practical-knuth-yhgrjl?file=/App.js)

**Comment by benoitgrelard** [comment]
Hey @sam-potter, this is by design and expected. If you need to close asynchronously you can control the `open` state like in this example:

https://www.radix-ui.com/docs/primitives/components/dialog#close-after-asynchronous-form-submission

**Comment by yudyananda** [comment]
> Hey @sam-potter, this is by design and expected. If you need to close asynchronously you can control the `open` state like in this example:
> 
> https://www.radix-ui.com/docs/primitives/components/dialog#close-after-asynchronous-form-submission

Copy the same code from the example but the alert dialog seems to ignore setTimeout and close instantly 

```
const mockPromise = async () =>
  await new Promise(() =>
    setTimeout(() => resolve, 10000000000)
  );
```

**Comment by benoitgrelard** [comment]
Looks like the examples aren't quite right, I'll fix them.
It's missing `event.preventDefault()` in the `onSubmit` to prevent full browser reload when submitting the form

**Comment by yudyananda** [comment]
I'm afraid it's not the case

```js
import React from 'react';
import * as AlertDialog from '@radix-ui/react-alert-dialog';

export default function Alert() {
  const [open, setOpen] = React.useState(false);
  return (
    <AlertDialog.Root open={open} onOpenChange={setOpen}>
      <AlertDialog.Trigger>Alert</AlertDialog.Trigger>
      <AlertDialog.Portal>
        <AlertDialog.Overlay>
          <AlertDialog.Content>
            <form
              onSubmit={(e) => {
                e.preventDefault();
                // eslint-disable-next-line no-console
                console.log('Action');
              }}
            >
              {/** some inputs */}
              <AlertDialog.Action type="submit">Submit</AlertDialog.Action>
            </form>
          </AlertDialog.Content>
        </AlertDialog.Overlay>
      </AlertDialog.Portal>
    </AlertDialog.Root>
  );
}
```
there was no output in my console except warning each time the submit get clicked

![alert-radix](https://user-images.githubusercontent.com/29258979/199700262-6ec3e830-8812-44a6-87e8-80221feaba54.png)

**Comment by benoitgrelard** [comment]
It does work, but here you're using `Action` which will close either way as it's wired that way internally.
You should use your own `button type="submit"` if you don't want to close when clicking the button directly.

**Comment by yudyananda** [comment]
@benoitgrelard awesome! thank's for your time

**Comment by benoitgrelard** [comment]
Update: I've fixed the examples: https://github.com/radix-ui/website/pull/544
