### ISSUE TITLE
Modal Crashing in NextJS when opening it in a smartphone

### ISSUE THREAD

**Issue by RamboGj** [radix-ui/primitives#1783]
I'm having a trouble when opening a Radix UI dialog with my smartphone and other people had the same trouble that me. When opening a dialog on a smartphone, the app freezes, Idk why.

**Comment by andy-hook** [comment]
Hi @RamboGj would you mind providing a list of all Radix packages you're using and their versions? are you also able to provide a minimal reproduction on codesandbox for us to validate? many thanks 🙏

**Comment by RamboGj** [comment]
These are the Radix packages I'm using
`   "@radix-ui/react-dialog": "^1.0.2",
        "@radix-ui/react-dropdown-menu": "^1.0.0",
        "@radix-ui/react-progress": "^1.0.0",
        "@radix-ui/react-scroll-area": "^1.0.0",
        "@radix-ui/react-tabs": "^1.0.0",
        "@radix-ui/react-toggle-group": "^1.0.0",
        "@radix-ui/react-tooltip": "^1.0.2",`
        
  The "crash"(between " because sometimes it's possible to make the login with the dialog on mobile, but it's really, really slow to interact with the component) happens when opening Dialogs.
  `<Dialog.Root>
              <Dialog.Trigger className="hover:text-gray500 transition duration-500 cursor-pointer">
                Acessar sua conta
              </Dialog.Trigger>
              <DynamicAccessAccountModal
                passwordVisibility={passwordInputReveal}
                onConnectWithMetamask={handleConnectWithMetamask}
                onChangePasswordVisibility={handleChangePasswordVisibility}
              />
            </Dialog.Root>`
            
            
    The dialog itself:
    `import * as Dialog from '@radix-ui/react-dialog'

import * as zod from 'zod'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'

import nookies, { setCookie } from 'nookies'

import { toast, Toaster } from 'react-hot-toast'

import Image from 'next/image'
import metamaskLogo from '../../assets/metamask-logo.svg'

import { X, EyeSlash, Eye } from 'phosphor-react'
import { api } from '../../services/api'
import { useContext } from 'react'
import { AccountContext } from '../../contexts/AccountContext'
import { RecoverPasswordModal } from './RecoverPasswordModal'
import { LOGIN_STEPS } from '../../utils/constants'

interface AccessAccountModalProps {
  passwordVisibility: string
  onChangePasswordVisibility: () => void
  onConnectWithMetamask: () => void
}

const AccessAccountSchema = zod.object({
  email: zod.string().email(),
  password: zod.string().min(8, 'Senha inválida').max(59),
})

type AccessAccountData = zod.infer<typeof AccessAccountSchema>

export default function AccessAccountModal({
  onChangePasswordVisibility,
  passwordVisibility,
  onConnectWithMetamask,
}: AccessAccountModalProps) {
  const isPasswordHidden = passwordVisibility.includes('hidden')

  const AccessAccountForm = useForm<AccessAccountData>({
    resolver: zodResolver(AccessAccountSchema),
    defaultValues: {
      email: '',
      password: '',
    },
  })

  const { register, handleSubmit, reset } = AccessAccountForm

  const { setUser, loginStep, setLoginStep } = useContext(AccountContext)

  async function handleAccessAccount(data: AccessAccountData) {
    const body = JSON.stringify({
      email: data.email,
      password: data.password,
    })
    const config = {
      method: 'post',
      url: '/login',
      headers: {
        'X-Parse-Application-Id': 'Zfi3XMh1U6nPS3tnqy2r2uVzp78W8eHCYBLAjgzD',
        'X-Parse-REST-API-Key': 'wsEBmrPVPZ6ABsvX09MIa0n9Gb1CUR7n2GiItd2U',
        'Content-Type': 'application/json',
      },
      data: body,
    }
    try {
      await api(config).then((res) => {
        console.log('LOGIN =>', res.data)

        setUser(res.data.result)
        nookies.set(null, 'userAddress', res.data.result.address, {
          maxAge: 60 * 60 * 24,
        })
        nookies.set(null, 'userSessionToken', res.data.result.sessionToken)
        setCookie(null, 'userAddress', res.data.result.address, {
          maxAge: 60 * 60 * 24,
        })
        setCookie(null, 'userSessionToken', res.data.result.sessionToken)
        reset()
      })
    } catch (err) {
      console.log(err)
      toast.error('E-mail ou senha incorretos!')
    }
  }

  return (
    <>
      {loginStep === LOGIN_STEPS.Login ? (
        <Dialog.Portal>
          <Dialog.Overlay className="bg-gray700/70 inset-0 fixed">
            <Dialog.Content className="fixed max-w-[411px] lg:max-w-[525px] w-full bg-white p-8 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 rounded-[15px] shadow-black/25 font-rubik  font-bold text-gray900">
              <div className="flex items-center justify-between">
                <Dialog.Title className="text-lg lg:text-2xl">
                  Acesse sua conta
                </Dialog.Title>
                <Dialog.Close onClick={() => setLoginStep(LOGIN_STEPS.Login)}>
                  <X size={32} weight="bold" />
                </Dialog.Close>
              </div>
              <form onSubmit={handleSubmit(handleAccessAccount)}>
                <div className="mt-8 flex flex-col gap-4 text-sm lg:text-lg">
                  <div className="w-full flex flex-col">
                    <label htmlFor="email">E-mail</label>
                    <input
                      placeholder="meuemail@mail.com"
                      type="text"
                      id="email"
                      className="focus:outline-none font-regular text-gray500 border-b-2 border-b-gray400  focus:border-b-blue300 transition duration-300"
                      {...register('email')}
                    />
                  </div>
                  <div className="w-full flex flex-col">
                    <label htmlFor="password">Senha</label>
                    <div className="flex w-full">
                      <input
                        maxLength={59}
                        type={isPasswordHidden ? 'password' : 'text'}
                        placeholder="Minhasenha123!"
                        id="password"
                        className="relative w-full focus:outline-none font-regular text-gray500 border-b-2 border-b-gray400  focus:border-b-blue300 transition duration-300"
                        {...register('password')}
                      />
                      {isPasswordHidden ? (
                        <EyeSlash
                          className="absolute right-12 cursor-pointer"
                          onClick={onChangePasswordVisibility}
                        />
                      ) : (
                        <Eye
                          className="absolute right-12 cursor-pointer"
                          onClick={onChangePasswordVisibility}
                        />
                      )}
                    </div>
                  </div>
                </div>
                <div className="mt-8 flex flex-col gap-5">
                  <button
                    onClick={() => setLoginStep(LOGIN_STEPS.RecoverPassword)}
                    className="text-blue500/80 underline text-center cursor-pointer hover:text-blue200 transition duration-500"
                  >
                    Esqueci a minha senha
                  </button>
                  <button
                    type="submit"
                    className="w-full bg-blue500/80 text-white font-medium py-4 rounded-[10px] hover:bg-blue900 transition duration-500"
                  >
                    Entrar
                  </button>
                  <p className="text-black font-regular flex justify-center text-sm lg:text-base">
                    Já possui sua carteira cripto? Faça seu login
                  </p>
                  <button
                    type="button"
                    onClick={onConnectWithMetamask}
                    className="w-full hidden lg:flex items-center justify-center bg-white border border-gray400 text-white font-medium shadow-lg py-3 rounded-[10px] hover:bg-gray300 transtion duration-500"
                  >
                    <Image src={metamaskLogo} alt="" />
                  </button>
                </div>
              </form>
            </Dialog.Content>
          </Dialog.Overlay>
        </Dialog.Portal>
      ) : (
        <RecoverPasswordModal />
      )}

      <Toaster position="top-right" />
    </>
  )
}
`

**Comment by Sahmok** [comment]
I am going through the same issue, when nesting radix components, the app crashes without any error message, a two much recursion issue would be logic but I can't see it, could you please tell me how have you solved your issue ?

**Comment by Sahmok** [comment]
@RamboGj
