### ISSUE TITLE
NextJS 13 createContext is not a function issue with Radix avatar

### ISSUE THREAD

**Issue by DarkAbhi** [radix-ui/primitives#1784]
### Current Behavior

I'm trying to use Radix UI in my NextJS 13 app and it errors with this 
My code looks like this, straight from the docs.

![image](https://user-images.githubusercontent.com/22658573/201742437-fd19a24d-685a-4470-99ac-aa8f642387f3.png)

### Expected behavior

To be able to see the avatar.

### Reproducible example

[Github Repo](https://github.com/DarkAbhi/portfolio)

### Additional Info
Other users have reported same on NextJS discord server.
[Post 1](https://discord.com/channels/752553802359505017/1040392283637432391)
[Post 2](https://discord.com/channels/752553802359505017/752647196419031042/1038910809553776753)

### Your environment

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by andy-hook** [comment]
@DarkAbhi Radix hasn't yet been updated to support RSC / the beta app directory out of the box. I took a look at your linked project but couldn't find Radix listed in the deps. In the meantime I'd suggest following the [third-party package recommendations](https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages), please follow up if you're still having issues after following that guidance.

**Comment by erickriva** [comment]
@andy-hook There are plans to support RSC soon? There is an E.T.A?

**Comment by andy-hook** [comment]
> @andy-hook There are plans to support RSC soon? There is an E.T.A?

No plans yet, wrapping your own client directive is still our recommendation.

**Comment by marnauortega** [comment]
Sorry if this is a silly question, but how would we go about following the third party recommendations with a radix primitive?

In a file:

```
DialogRadixClient.js

"use client";

import * as Dialog from "@radix-ui/react-dialog";

export default Dialog;
```

And then

```
SomeComponent.js

import Dialog from "./DialogRadixClient";

const SomeComponent = async ({ children }) => {
  const stuff = await fetchSomeStuff();

  return (
    <Dialog.Root>
    </Dialog.Root>
)}

```
This isn't working, it complains that:

````
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
Thank you!

**Comment by benoitgrelard** [comment]
I think this bit is wrong:

```tsx
import * as Dialog from "@radix-ui/react-dialog";

export default Dialog;
```

and instead you want:

```tsx
export * from "@radix-ui/react-dialog";
```

**Comment by marnauortega** [comment]
You are totally right! Thank you : )

**Comment by SalahAdDin** [comment]
I'm getting the same issue for **NextJS 14**.

**Comment by SalahAdDin** [comment]
> > @andy-hook There are plans to support RSC soon? There is an E.T.A?
> 
> @erickriva No plans yet, wrapping your client directive is still our recommendation.

Not yet for **NextJS 14**, so, it means we will have to move to an SSR compatible library, so bad.

**Comment by andy-hook** [comment]
It doesn't use context internally, depending on your project structure you may be accidentally importing other primitives code in your server component without marking them `use client`. If you're using barrel files for exports check what is resolving in there.

**Comment by SalahAdDin** [comment]
@andy-hook It inherits from primitive wich uses context :')

**Comment by andy-hook** [comment]
@SalahAdDin Are you running into issues? if you can describe your problem perhaps we can help.

**Comment by SalahAdDin** [comment]
> @SalahAdDin Are you running into issues? if you can describe your problem perhaps we can help.

Yeah, I'm using Separator in a server component, a page, and it breaks the building.
