### ISSUE TITLE
[Tooltip] It is possible to break out of focus-trap

### ISSUE THREAD

**Issue by snacksncode** [radix-ui/primitives#1797]
### Current Behavior
When content is focused, tooltip is shown and can be dismissed by pressing `Esc` (focus remains on the content to which tooltip is applied). However if focus was stolen from the tooltip, in my cause the content is a button and after pressing it, another ui is rendered which steals focus from the tooltip, then if `Esc` is pressed it will cause the focus to go back to the tooltip and open a tooltip again (because it got refocused). In my case stealing of focus is caused by `focus-trap-react`. In other words tooltip allows me to escape from trap focus.

Gif showcasing the issue:
![focus-trap-issue](https://user-images.githubusercontent.com/50829382/202873554-30003bc1-8ff2-4d72-9d7c-38e02dfa2924.gif)

### Expected behavior
Pressing `Esc` in this situation doesn't cause the focus to go back to the tooltip and doesn't "escape" from the focus trap

### Reproducible example
[CodeSandbox Minimal Showcase](https://codesandbox.io/s/dazzling-butterfly-ztso85)

### Suggested solution
Is there a possibility of detecting when a focus was stolen by a focus-trap from the tooltip and ignore `Esc` call?

### Additional context
I tried adding
```js
onEscapeKeyDown={(e) => e.preventDefault()}
```
to the `<Tooltip.Content>`, which prevented tooltip from closing when pressing `Esc` whilst focus was on Tooltip content, that is disabling `Esc` functionality but the bug is still there even after that addition. Also I'm not sure if this is an issue with `focus-trap-react` or radix but I'm suspecting it's some edge case on radix's part, hence this issue. I didn't test any other focus-trap libraries as this one is the most popular. If you guys want me to test this bug with different react focus-libraries please let me know.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |@radix-ui/react-tooltip, focus-trap-react|1.0.2, 10.0.1|
| React            |react, react-dom|18.2.0|
| Browser          |Chrome|107.0.5304.110|
| Assistive tech   |None|-|
| Node             |Latest|19.0.1|
| npm/yarn         |yarn|1.22.19|
| Operating System |Linux|6.0.7-arch1-1|

**Comment by snacksncode** [comment]
I'm almost sure this is the issue with `focus-trap-react`

**Comment by benoitgrelard** [comment]
Hey @snacksncode,

I'm not entirely sure I follow exactly what your use-case is.
That being said, I can perhaps bring some clarity in the fact that our `Tooltip` doesn't contain any focus trapping.
So if you're having issues with focus trapping, then it's certainly from the other library.

If I misunderstood then let me know!

**Comment by snacksncode** [comment]
Yup, I've actually just confirmed that it's the issue with `focus-trap-react` library and React 18. They don't play well with strict mode. Sorry to take up your time. This issue can be closed. It has nothing to do with radix-ui primitives.

If anyone stumbles upon this issue here's some info. `focus-trap-react` is a wrapper for `focus-trap` library and its trap can be deactivated by pressing `Esc`. With Strict mode though you're not supposed to handle trap's state with events like `onDeactivate` so you can't unmount the trap component when `Esc` is pressed. Thus focus is returned to the triggering element - escaping the trap. Just disable option that enables that functionality.
