### ISSUE TITLE
[NavigationMenu] - Trigger does not close sublist with more than 2 levels 

### ISSUE THREAD

**Issue by orenatodos** [radix-ui/primitives#1806]
### Current Behavior

Create a navigation menu with 2 display levels.

Trigger 1
  - Item 1
  - Item 2
  - Item 3
  - Trigger 2
    - Item 1
    - Item 2
    - Item 3

When hovering the mouse over (trigger 2) it opens normally and displays its children, but when moving the mouse outside it no longer closes, even when clicking on the trigger

### Expected behavior

When moving the mouse out or clicking trigger 2 it should close causing it not to display its children

### Reproducible example

[CodeSandbox Example showing the bug](https://codesandbox.io/s/async-shadow-4j8eyc?file=/src/App.tsx:0-2794)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Navigation Menu | ^1.1.1 |
| React            | n/a     | ^18.2.0 |
| Browser          | Microsoft Edge | 107.0.1418.62 |
| Assistive tech   |         |         |
| Node             | n/a     | v18.12.1 |
| npm/yarn         | npm | (9.1.2) |
| Operating System | macOS Ventura | 13.0.1 |

**Comment by Elvaleryn** [comment]
I think this is the intended way, because when you check the storybook example of submenus this behaviour makes sense

**Comment by benoitgrelard** [comment]
Yes that is the expected behaviour, here's the story @Elvaleryn is referring to: https://601857eb614bae0021c9b9dd-cdefwoyzog.chromatic.com/?path=/story/components-navigationmenu--submenus
