### ISSUE TITLE
Select issue with reset react hook form.

### ISSUE THREAD

**Issue by whydea** [radix-ui/primitives#1808]
I have a select that starts with the undefined value to show the placeholder, but when using the reset method of the react hook form in the button submit, the select does not return to the initial state (nothing happens).

If I start with the initial value with the value of an item that exists in the select, when I do the reset everything works correctly, which leads me to believe that there is a problem when resetting the select to undefined.

I don't know if the problem is related to the react hook form, but I can't reset the select to undefined

Here's an example of what I'm trying to explain:

const registerUserSchema = yup.object({
  name: yup.string().required('O nome é obrigatório'),  
  institutionId: yup.string().required('A instituição é obrigatória'),
});

const {
    handleSubmit, reset, formState, control,
  } = useForm<NewUserFormData>({
    resolver: yupResolver(registerUserSchema),
    defaultValues: {
      name: '',      
      institutionId: undefined,
    },
  });

<Controller
        placeholder="Instituição"
        name="institutionId"
        control={control}
        name={name}
        render={({ field }) => (
          <Select.Root
            {...props}
            value={field.value}
            defaultValue={undefined}
            onValueChange={field.onChange}
            placeholder={placeholder}
          >
            {children}
          </Select.Root>
        )}
      />

I need to start the institutionId: undefined field because if it starts "" the placeholder does not appear, however using undefined the value of the select is not reset (it remains the same value that was selected by the user)

This https://github.com/radix-ui/primitives/issues/1569 is probably a problem similar to mine

**Comment by grctest** [comment]
I'm also still getting this, I'm using shadcn select which uses radix-ui, I've tried both undefined and "" select values, it shows blank instead of the placeholder.

Updating the select component's key is a valid workaround though :)

**Comment by joaom00** [comment]
> I'm also still getting this, I'm using shadcn select which uses radix-ui, I've tried both undefined and "" select values, it shows blank instead of the placeholder.
> 
> Updating the select component's key is a valid workaround though :)

Are you using the [RC version](https://www.npmjs.com/package/@radix-ui/react-select/v/2.0.0-rc.10)?

**Comment by grctest** [comment]
I think this is the location of the Select component in shadcn: https://github.com/shadcn-ui/ui/blob/4f8d768e59445013d65de082bae525011b4807d4/apps/www/package.json#L40C5-L40C40

` "@radix-ui/react-select": "^1.2.2"`

So no, not using the RC version with the fix yet, looks like this is where the issue resides for me. I'll wait for shadcn to uplift to the latest version, the key workaround works for now.

Cheers :)

**Comment by stoykotolev** [comment]
> I think this is the location of the Select component in shadcn: https://github.com/shadcn-ui/ui/blob/4f8d768e59445013d65de082bae525011b4807d4/apps/www/package.json#L40C5-L40C40
> 
> ` "@radix-ui/react-select": "^1.2.2"`
> 
> So no, not using the RC version with the fix yet, looks like this is where the issue resides for me. I'll wait for shadcn to uplift to the latest version, the key workaround works for now.
> 
> Cheers :)

You don't have to wait for shad to update anything. You can go in your `package.json` and manually bump your version and install. Shadcn is just a style on top of RadixUI and you are then free to modify as much as you'd like.

**Comment by M-Samoht** [comment]
still not working with the current 2.0.0

**Comment by M-Samoht** [comment]
i used defaultValue instead of value my bad. thanks for the answer.
