### ISSUE TITLE
[Popover] Does not work with SSR hydration (Next 13) 

### ISSUE THREAD

**Issue by rortan134** [radix-ui/primitives#1817]
### Current Behavior

Popover is currently not suitable for SSR with the latest version of Next 13 because it uses useEffect

![image](https://user-images.githubusercontent.com/37253958/205626583-4d3292d9-6701-4e34-9420-360dc99f07fa.png)

### Expected behavior

According to the [docs](https://www.radix-ui.com/docs/primitives/overview/server-side-rendering), we should be able to use every primitive component with SSR

### Reproducible example

https://stackblitz.com/edit/nextjs-zbdg68?file=app/page.js

### Environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-popover     |    ^1.0.2     |
| React            | n/a     |    ^18.2.0     |
| Next            | n/a     |    ^13.0.6     |
| Browser          |    Chrome     |    n/a     |
| Node             | n/a     |     16.18.0    |
| npm/yarn         |    yarn     |    1.22.19     |
| Operating System |     Windows    |    21H2     |

**Comment by andy-hook** [comment]
Please see here https://github.com/radix-ui/primitives/issues/1784#issuecomment-1314947715
