### ISSUE TITLE
[Select] Unable to open select with @testing-library/react 

### ISSUE THREAD

**Issue by wnadurski** [radix-ui/primitives#1822]
### Current Behavior

The library cannot open the select when writing unit tests with `@testing-library/react` against the `Select` component. 
This happens in all three cases:
- using `fireEvent.click` on the trigger element,
- using `userEvent.click` on the trigger element
- using `userEvent.click` with the pointer type set to `touch` on the trigger element (as per suggestion in https://github.com/radix-ui/primitives/issues/1220)
### Expected behavior

The Select component can be opened in jest unit tests.

### Reproducible example

https://codesandbox.io/s/elated-gagarin-18cpyl?file=/select.test.jsx

### Additional context

When using `fireEvent.click`, the Select component simply doesn't open, and the testing library can't find any of the items.
In other cases, an exception is thrown: `The provided value is not of type 'Element'.`.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     react-select    |  1.1.2        |
| React            | n/a     |    18.2.0     |
| Browser          |    n/a     |     n/a    |
| Assistive tech   |     n/a    |    n/a     |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |     macOS   |  Monterey        |

**Comment by jmcdl** [comment]
@GuipsT Same for me. Unfortunately the workaround shared by @sylvainDNS doesn't seem to get it working in my case.

**Comment by joaom00** [comment]
@GuipsT @jmcdl Are both using vitest? no error appears in the console?

**Comment by GuipsT** [comment]
@joaom00 Nope, no errors are thrown. I've tried passing some more parameters for vitest to log more stuff for me, but nothing happens. 
The only log in the console is this:
```
<body>
  <div>
    <h1>Something went wrong</h1>
  </div>
</body>
```

Which stops showing if I add the code @sylvainDNS provided.
But the test still fails to trigger the button element.
I'm using the radix-ui select component.

**Comment by joaom00** [comment]
Here is a [setup with vitest](https://github.com/joaom00/radix-select-vitest/blob/main/src/Select.test.tsx) and it seems to work. I hope it helps.

**Comment by mattwongasimov** [comment]
# Stand alone React App
I offer you my `jest` testing file for a custom component that incorporates the `radix-ui` `Select` component
## package.json excerpt
```json
{
"dependencies": {
"@radix-ui/react-select": "^1.0.0",
"@testing-library/jest-dom": "^5.16.5",
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^14.4.3",
"@types/jest": "^27.0.1",
"@types/react": "^18.0.0",
}
```
## setupTests.ts
### This file can be copy pasted into the test file if you are not using a test runner.
```ts
// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';

/**
 * JSDOM doesn't implement PointerEvent so we need to mock our own implementation
 * Default to mouse left click interaction
 * https://github.com/radix-ui/primitives/issues/1822
 * https://github.com/jsdom/jsdom/pull/2666
 */
class MockPointerEvent extends Event {
  button: number;
  ctrlKey: boolean;
  pointerType: string;

  constructor(type: string, props: PointerEventInit) {
    super(type, props);
    this.button = props.button || 0;
    this.ctrlKey = props.ctrlKey || false;
    this.pointerType = props.pointerType || 'mouse';
  }
}

window.PointerEvent = MockPointerEvent as any;
window.HTMLElement.prototype.scrollIntoView = jest.fn();
window.HTMLElement.prototype.releasePointerCapture = jest.fn();
window.HTMLElement.prototype.hasPointerCapture = jest.fn();
```
## select-component.test.tsx
```jsx
// Test for SelectComponent component
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import SelectComponent from '@components/SelectComponent';

const mockOnChange = jest.fn();

describe('SelectComponent', () => {
  afterEach(() => {
    cleanup();
    jest.clearAllMocks();
  });
  it('should render', () => {
    render(
      <SelectComponent value={'option-1'} onChange={mockOnChange} />
    );
    expect(screen.getByText('option-1')).toBeInTheDocument();
  });

  it('should render placeholder', () => {
    render(
      <SelectComponent placeholder="Select a status" onChange={mockOnChange} />
    );
    // This should match your placeholder default if you dont pass one in
    expect(screen.getByText('Select a status')).toBeInTheDocument();
  });

  it('should render options', async () => {
    const user = userEvent.setup();
    render(
      <SelectComponent value={'option-2'} onChange={mockOnChange} />
    );
    const optionSelect = screen.getByRole('combobox', {
      name: 'Select an option',
    });
    expect(optionSelect).toBeInTheDocument();
    await user.click(optionSelect);

    expect(
      screen.getByRole('option', { name: 'option-1' })
    ).toBeInTheDocument();
    expect(
      screen.getByRole('option', { name: 'option-2' })
    ).toBeInTheDocument();
    // Add in however many options you have
  });

  it('should render disabled options', async () => {
    const user = userEvent.setup();
    render(
      <SelectComponent
        value={'option-2'}
        onChange={mockOnChange}
        // Callback to determine if an option should be disabled
        isDisabled={(option) =>
          option === 'option-2' 
        }
      />
    );
    const optionSelect = screen.getByRole('combobox', {
      name: 'Select an option',
    });
    expect(optionSelect).toBeInTheDocument();
    await user.click(optionSelect);
    const option2 = screen.getByRole('option', { name: 'option-2' });
    expect(option2).toHaveAttribute('aria-disabled', 'true');
  });

  it('should call onChange', async () => {
    const user = userEvent.setup();
    render(
      <SelectComponent value={'option-1'} onChange={mockOnChange} />
    );
    const optionSelect = screen.getByRole('combobox', {
      name: 'Select an option',
    });
    expect(optionSelect).toBeInTheDocument();
    await user.click(optionSelect);
    const option2 = screen.getByRole('option', { name: 'option-2' });
    expect(option2).toBeInTheDocument();
    await user.click(option2);
    expect(mockOnChange).toHaveBeenCalledWith('option-2');
  });
});

```

**Comment by mattwongasimov** [comment]
The issue for me it seems was that targeting the userEvent to a `getByText` was being blocked by that element's `pointer-events: none` CSS. So using a `getByRole` target seems to do the trick to get the `combobox`

**Comment by ricardocosta** [comment]
I had the same issue with Select.

I tried using the mock approach, but that breaks Form submission in my tests, so I ended up using `pnpm patch` to make sure the `hasPointerCapture` and `scrollIntoView` are only used if they are available (since JSDOM doesn't provide them). 

This is the patch I applied:
```ts
diff --git a/dist/index.mjs b/dist/index.mjs
index aeef9c893bee072b9c31d5458593bdd2d5e04c9d..9787e92b54ded6c0dcdb7d3076c6a5c2be003649 100644
--- a/dist/index.mjs
+++ b/dist/index.mjs
@@ -199,7 +199,7 @@ const $cc7e05a45900e73f$export$3ac1e88a1c0b9f1 = /*#__PURE__*/ $01b9c$forwardRef
             // prevent implicit pointer capture
             // https://www.w3.org/TR/pointerevents3/#implicit-pointer-capture
             const target = event.target;
-            if (target.hasPointerCapture(event.pointerId)) target.releasePointerCapture(event.pointerId);
+            if (target.hasPointerCapture && target.hasPointerCapture(event.pointerId)) target.releasePointerCapture(event.pointerId);
              // only call handler if it's the left button (mousedown gets triggered by all mouse buttons)
             // but not when the control key is pressed (avoiding MacOS right click)
             if (event.button === 0 && event.ctrlKey === false) {
@@ -337,9 +337,9 @@ const $cc7e05a45900e73f$var$SelectContentImpl = /*#__PURE__*/ $01b9c$forwardRef(
         for (const candidate of candidates){
             // if focus is already where we want to go, we don't want to keep going through the candidates
             if (candidate === PREVIOUSLY_FOCUSED_ELEMENT) return;
-            candidate === null || candidate === void 0 || candidate.scrollIntoView({
+            candidate === null || candidate === void 0 || (candidate.scrollIntoView && candidate.scrollIntoView({
                 block: 'nearest'
-            }); // viewport might have padding so scroll to its edges when focusing first/last items.
+            })); // viewport might have padding so scroll to its edges when focusing first/last items.
             if (candidate === firstItem && viewport) viewport.scrollTop = 0;
             if (candidate === lastItem && viewport) viewport.scrollTop = viewport.scrollHeight;
             candidate === null || candidate === void 0 || candidate.focus();
```

Do you feel this is something that could be applied to the Select component? In theory, it's not a breaking change but I'm not  100% sure of the possible side effects.

**Comment by Effanuel** [comment]
Here is the solution without any mocking:
```ts
const element = screen.getByTestId(...);
await userEvent.click(element, { pointerState: await userEvent.pointer({ target: element }) });
```

**Comment by jomardiago** [comment]
> Here is the solution without any mocking:
> 
> ```ts
> const element = screen.getByTestId(...);
> await userEvent.click(element, { pointerState: await userEvent.pointer({ target: element }) });
> ```

This actually worked for me. Thanks!

**Comment by benoitgrelard** [comment]
Solution provided: https://github.com/radix-ui/primitives/issues/1822#issuecomment-1820797668

**Comment by ttizze** [comment]
`const element = screen.getByTestId(...);
await userEvent.click(element, { pointerState: await userEvent.pointer({ target: element }) });`

don't work for me

**Comment by opswiz** [comment]
Same, the solution doesn't work for me either. Using vitest and happy-dom.

**Comment by fernandortec** [comment]
> ```
> > const element = screen.getByTestId(...);
> > await userEvent.click(element, { pointerState: await userEvent.pointer({ target: element }) });
> ```
> 
> don't work for me
> 
> this is my code
> 
> ```
> <SelectTrigger className='w-full focus:ring-1 focus:ring-gray-300' data-testid= 'select-style-to-edit'>
>    <SelectValue placeholder='Select style to edit' />
> </SelectTrigger>
> ```
> 
> ```
> const element = screen.getByTestId('select-style-to-edit')
> await userEvent.click(element, {pointerState: await userEvent.pointer({ target: element }),})
> ```
> 
> `TypeError: target.hasPointerCapture is not a function. (In 'target.hasPointerCapture(event.pointerId)', 'target.hasPointerCapture' is undefined)`

Same

**Comment by BorysShulyak** [comment]
The same, the solution doesn’t work for me(

**Comment by ethanjdiamond** [comment]
FWIW, I was accidentally doing `userEvent.click()` instead of `await userEvent.click()`. Awaiting fixed the problem.

**Comment by algoORgoal** [comment]
Still not working

**Comment by Erod-star** [comment]
> Here is a [setup with vitest](https://github.com/joaom00/radix-select-vitest/blob/main/src/Select.test.tsx) and it seems to work. I hope it helps.

That worked for me, thanks a lot man!

**Comment by ValentinH** [comment]
While migrating from  `react-select` to Radix's Select component, I faced the same issue. It turns out that I was able to reuse the same test helper I was using for  `react-select`: 

```ts
// ./react-select-event.ts

/**
 * Utility for opening the select's dropdown menu.
 * @param {HTMLElement} input The input field (eg. `getByLabelText('The label')`)
 */
export const openMenu = async (input: HTMLElement) => {
  act(() => input.focus());
  await userEvent.keyboard('{arrowDown}');
};

/**
 * Utility for selecting a value in a `react-select` dropdown.
 * @param {HTMLElement} input The input field (eg. `getByLabelText('The label')`)
 * @param {Matcher|Matcher[]} optionOrOptions The display name(s) for the option(s) to select
 * @param {Object} config Optional config options
 * @param {HTMLElement | (() => HTMLElement)} config.container A container for the react-select and its dropdown (defaults to the react-select container)
 *            Useful when rending the dropdown to a portal using react-select's `menuPortalTarget`.
 *            Can be specified as a function if it needs to be lazily evaluated.
 */
export const select = async (input: HTMLElement, optionOrOptions: Matcher | Array<Matcher>) => {
  const options = Array.isArray(optionOrOptions) ? optionOrOptions : [optionOrOptions];

  // Select the items we care about
  for (const option of options) {
    await openMenu(input);

    // only consider visible, interactive elements
    const matchingElements = await screen.findAllByText(option, {
      ignore: "[aria-live] *,[style*='visibility: hidden']",
    });

    // When the target option is already selected, the react-select display text
    // will also match the selector. In this case, the actual dropdown element is
    // positioned last in the DOM tree.
    const optionElement = matchingElements[matchingElements.length - 1];
    if (optionElement) {
      await userEvent.click(optionElement);
    }
  }
};

const selectEvent = { select, openMenu };
export default selectEvent;
```

Then in your tests:
```ts
import selectEvent from './react-select-event';
// ... later
const frequencySelect = screen.getByRole('combobox', { name: /my select input label/i });
await selectEvent.select(frequencySelect, 'my option label');
```

**Comment by cbix** [comment]
@benoitgrelard the provided solution doesn't work for me either, using vitest + react testing-library (jsdom) with the same `hasPointerCapture` error. The mocks mentioned above will break other code and I'm getting vitest to hang due to them.

**Comment by cbix** [comment]
What worked for me instead of testing pointer interaction was to use `user.selectOptions` on the hidden `<select>` rendered by radix. Unfortunately this is not considered an accessible element so we have to use `querySelector`:
```ts
// get some container element in order to use querySelector
const dialog = screen.getByRole('dialog');

// pass the name prop to radix <Select>
const select = dialog.querySelector('select[name="spark"]');

// this helps with typescript
assert(select !== null);

await user.selectOptions(select, 'test-spark');
expect(select).toHaveValue('spark-1');
```
