### ISSUE TITLE
Checkbox not focusable in Safari

### ISSUE THREAD

**Issue by tortilaman** [radix-ui/primitives#1831]
### Current Behavior

Currently it is not possible to focus on the Checkbox component in Safari when going through the tab order. This behavior works as expected with other browsers.

https://user-images.githubusercontent.com/5018268/207136799-478d85b6-2ac6-4170-8f5e-dcfe7be09942.mov

### Expected behavior

When tabbing through the page, you should be able to focus on the Radix-UI Checkbox component out of the box.

### Reproducible example

This is reproducible on the Checkbox documentation page, including the [Codesandbox example](https://codesandbox.io/s/13v457?module=App.js) contained there

### Suggested solution

Unfortunately, It's not clear to me what the solution is here, as aria roles are being set correctly, and this works well in other browsers.

### Your environment

A minimal reproduction is possible using the Codesandbox linked above, so I don't think it's specific to my environment. That being said, if it's helpful, my environment for my application is as follows:

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-checkbox | 1.0.1 |
| React            | n/a     | 17.0.1 |
| Browser          | Safari | 15.4 |
| Assistive tech   | n/a |         |
| Node             | n/a     | 16.14.2 |
| npm/yarn         | npm | 8.5.0 |
| Operating System | macOS | 12.3 |

**Comment by benoitgrelard** [comment]
Hey @tortilaman,

Are you sure you have this turned on?
![CleanShot 2022-12-12 at 23 23 22@2x](https://user-images.githubusercontent.com/1539897/207181007-b63f87d2-1fe5-4c41-a123-a79a5b06fecc.png)

**Comment by tortilaman** [comment]
Oh gosh! I'm super happy that's all it was 😅, cheers!
