### ISSUE TITLE
Import error: Radix primitives are not properly exported as ES Modules

### ISSUE THREAD

**Issue by ted-palmer** [radix-ui/primitives#1835]
### Current Behavior

When converting a package from CommonJs to ESM, Nextjs is now failing to import the ESM version of Radix primitives. I am getting a number of these errors:

```
SyntaxError: Named export 'Arrow' not found. The requested module '@radix-ui/react-popover' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@radix-ui/react-popover';
const {Arrow: $TBcmg$Arrow, Content: $TBcmg$Content1, Root: $TBcmg$Root2, Trigger: $TBcmg$Trigger1, Portal: $TBcmg$Portal1} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
  page: '/'
}
```

### Expected behavior

Radix primitives should be imported as ES Modules. 

### Suggested solution

1. Primitives should be exported as ES Modules by default by adding `"type":"module"` to the package.json.
2. The 'exports' field should be used to define export files with the 'import' and 'require' types like so: 
```
{
  "exports": {
    "import": "./index-module.js",
    "require": "./index-require.cjs"
  },
  "type": "module"
}
  ```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            |     |    ^18.0.0     |
| Node             |      |   18.2.0      |
| npm/yarn         |    yarn     |   3.2.3      |
| Operating System |   MacOs      |  13.0.1       |

**Comment by benoitgrelard** [comment]
Hey @ted-palmer,

This might be an issue with your environment. There are lots of apps out there consuming Radix primitives as ESM without issues, including ours.

Every package has this setup in `package.json`, which correctly exposes both version AFAIK:

```
"main": "dist/index.js",
"module": "dist/index.module.js",
"types": "dist/index.d.ts",
```

**Comment by ted-palmer** [comment]
We were to able to find a solution using nextjs's transpile packages. Thanks!

**Comment by Veraprot** [comment]
> We were to able to find a solution using nextjs's transpile packages. Thanks!

@ted-palmer  what was your solution for fixing nextjs environment? I'm running into the same issue and can't sort out the solution.

**Comment by pyplacca** [comment]
> We were to able to find a solution using nextjs's transpile packages. Thanks!

Hi, what was your solution? We're currently experiencing a similar issue with one of the primitives (radix ui react-presence). I'd be glad if you can share your solution. 

![image](https://github.com/radix-ui/primitives/assets/36242450/f741351e-80db-4e86-a18a-41cbe6e9e4da)

**Comment by guilhermefmotta** [comment]
@pyplacca if you are using nextjs, just add @radix-ui in the transpilePackages

**Comment by francistogram** [comment]
Thanks for the advice @guilhermefmotta. [transpilePackages](https://nextjs.org/docs/architecture/nextjs-compiler#module-transpilation) worked for me

For posterity in your `next.config.js`
```javascript
{
   // or whichever package is giving you issues
    transpilePackages: ["@radix-ui/react-dialog"],
}
```

**Comment by suryarajendhran** [comment]
I'm still having this issue with Remix.js. Any ideas on how to fix this?
