### ISSUE TITLE
[DropdownMenu] Is there a way to override the css applied on the root dropdown menu?

### ISSUE THREAD

**Issue by YutaMoriJP** [radix-ui/primitives#1839]
## Question:

Currently, it seems that the Root element of `DropdownMenu` has by default applied the following style:

Is there a way to opt-out of this behavior or override the CSS? I want to have greater control of the dropdown menu and let it behave like a block element and have control over how I render it.

```css
    position: fixed;
    left: 0px;
    top: 0px;
    transform: translate3d(292px, 8px, 0px);
    min-width: max-content;
    z-index: auto;
    --radix-popper-transform-origin: 50% 254px;
```

**Comment by Talent30** [comment]
Not a very good solution
`[data-radix-popper-content-wrapper] {
  transform: none !important;
}
`

**Comment by YutaMoriJP** [comment]
Thanks! Will give it a try 🙏

**Comment by mpereira** [comment]
+1 on this, considering https://www.radix-ui.com/docs/primitives/overview/introduction#unstyled

> Components ship with zero styles, giving you complete control over styling. Components can be styled with any styling solution (vanilla CSS, CSS preprocessors, CSS-in-JS libraries). Learn more in our [styling](https://www.radix-ui.com/docs/primitives/overview/styling) guide.

**Comment by pravinfostretch** [comment]
Is there a way to update the min-width property here as well?

**Comment by mrsiclorena12** [comment]
@joaom00  thank you very much

**Comment by tkodev** [comment]
My popper content has box shadows and I cannot set `overflow-visible` tailwind class (or any class) for the radix-popper-content-wrapper div. Any fixes?

**Comment by JoaomdvFerreira** [comment]
> @mrsiclorena12 You can set `z-index` in the `Content` part and it will be set in the `[data-radix-popper-content-wrapper]`

legend

**Comment by RewriteH** [comment]
> @mrsiclorena12 You can set `z-index` in the `Content` part and it will be set in the `[data-radix-popper-content-wrapper]`

Thank you, bro

**Comment by mgomez-tubs** [comment]
If anyone else is confused by what the Content part means, it is the styling of the DropdownMenu.Content Component. It does also work with the DropdownMenu.SubContent

**Comment by pepew-le-boss** [comment]
up

**Comment by neha-ziffi** [comment]
I want to set the left property of data-radix-popper-content-wrapper but I am not able to figure out how to do that?

**Comment by isabella-riquetti** [comment]
> Is there any way to prevent content rendering inside `[data-radix-popper-content-wrapper]` or atleast have control

awesome!

**Comment by AdamZaczek** [comment]
This is beyond confusing. I'm also stuck here, considering dropping Radix as the only reasonable solution is reading the source code and maybe modifying the package in node_modules? Not sure what the solution will end up being but it isn't good.

**Comment by christian-reichart** [comment]
why is this issue marked as completed? I'm still having the issue of not being able to style [data-radix-popper-content-wrapper] properly. Any hints?

**Comment by ashwinchandran13** [comment]
Alright I got a solution for this (workaround). I'm still testing the coverage of effect of this solution but to minimize the effect of it I had to introduce a class: 
```js 
// css
 .DropdownTbody 
[data-radix-popper-content-wrapper] { 
   position: absolute !important;
} 
// jsx 
<tbody className='relative DropdownTbody'>  {/* placing class here /*} 
  <DropdownMenu open={filterMenuOpen} onOpenChange={setFilterMenuOpen}> 
      <DropdownMenuContent 
           className="DropdownMenuContent outline-none drop-shadow-2xl shadow-2xl bg-[#1A1A1A] z-50"
           alignOffset={9} 
           sideOffset={10} 
           align="end" 
           side='bottom' 
  > 
        <DropdownMenuItem className="outline-none"> 
            <div className="flex gap-2 text-xs items-center p-4 bg-[#1A1A1A] text-white hover:cursor-pointer hover:bg-[#333] absolute z-50 min-w-fit w-[250px]" > 
                Filter menu 
            </div> {/* making this div absolute to the tbody of a table which is now relative /*}
        </DropdownMenuItem> 
     </DropdownMenuContent> 
  </DropdownMenu> 
</tbody> 
```

**Comment by lukasjsk** [comment]
I had also problem with the placement of the popper - page without any padding/margin, dropdown content not aligned with the field. In my case solution was to set  `collisionPadding` on the Content to 0.
