### ISSUE TITLE
Not able to interact with DropdownMenu.Trigger when the Dropdown is open

### ISSUE THREAD

**Issue by toto1384** [radix-ui/primitives#1842]
### Current Behavior

https://user-images.githubusercontent.com/35605914/208173460-98c8c0ac-d448-470a-96b3-6790a322d9cd.mov

### Expected behavior

To be able to interact with that textfield (I am building a combobox)

### Reproducible example
```
<DropdownMenu.Root modal={false} open={open} defaultOpen={true} onOpenChange={setOpen}>
			<DropdownMenu.Trigger asChild={false}>
				<div className="cursor-pointer left-0 w-fit" onClick={(event) => {
					event.stopPropagation();
					event.currentTarget.focus()
					// if (React.isValidElement(props.dropdown) && !(props.disableShowOnClick ?? false)) setOpen(!open)
				}}>{(props.dropdown instanceof Function) ? props.dropdown(setOpen) : props.dropdown}</div>
			</DropdownMenu.Trigger>

			<DropdownMenu.Portal >
				<DropdownMenu.Content className="rounded bg-white shadow-2xl z-50 max-h-96 max-w-[100vw] overflow-y-scroll" sideOffset={5}>
					{(props.children instanceof Function) ? props.children(setOpen) : props.children}
					{props.arrow && <DropdownMenu.Arrow className="fill-white" />}
				</DropdownMenu.Content>
			</DropdownMenu.Portal>
		</DropdownMenu.Root>
```

### Suggested solution

Have a property to enable interacting with the  DropdownMenu.Trigger (similar to how `modal` property performs)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |    		"@radix-ui/react-dropdown-menu": "^2.0.1",     |
| React            | n/a     |   		"react": "^18.2.0",      |
| Browser          |    Chrome     |         |
| Node             | n/a     |         |
| npm/yarn         |     pnpm    |         |
| Operating System |       Macos  |         |

**Comment by benoitgrelard** [comment]
`DropdownMenu` isn't intended to be used to build a combobox. Trying to shoe-horn it won't work unless you rebuilt a ton of functionality yourself. This is due to how focus is currently managed as well as layering.

I will close the issue as it's not really the intended use of the package.
