### ISSUE TITLE
[Select] Select with a Portal in a Dialog fails to lay itself out

### ISSUE THREAD

**Issue by PatrikTheDev** [radix-ui/primitives#1854]
## Bug report
A Select (with a Portal) wrapped in a Dialog positions itself in the middle of the screen on the left side

### Current Behavior

<img width="972" alt="image" src="https://user-images.githubusercontent.com/25883885/209110608-cbf9c83a-1201-45db-af81-e7fde761e6a3.png">

### Expected behavior
(really rough CSS but you get the idea)
<img width="972" alt="image" src="https://user-images.githubusercontent.com/25883885/209110865-3a9d9a4f-8c6c-4b4b-8b29-a87197ef5311.png">

Note: this is what happens if you remove `<SelectPortal>` currently, but adding it back breaks the behavior (as seen under _Current Behavior_)

**Comment by benoitgrelard** [comment]
I believe this was fixed a long time ago when we updated to floating UI.
See an example I just wired quickly in our storybook:

https://github.com/radix-ui/primitives/assets/1539897/5d38cb05-fed9-4b0f-b890-278a3c5bcf25
