### ISSUE TITLE
Hovering on Tooltip is hard in some situations

### ISSUE THREAD

**Issue by istarkov** [radix-ui/primitives#1855]
### Overview

Currently, it's hard to hover on some tooltips because of the graceArea building algorithm.
Example:
When I move the mouse out of the text-box, a grace area is built using the mouse leaving point (ypos - 5)
And it works fine in the following example.

<img width="158" alt="image" src="https://user-images.githubusercontent.com/5077042/209281403-3bc2f5e2-69f7-41fe-9ca1-2ecc3066596b.png">

but when I try to move the mouse from the corners of text-box this doesn't work, impossible to hold the mouse inside  graceArea

<img width="141" alt="image" src="https://user-images.githubusercontent.com/5077042/209281708-b1a3dc03-436c-4e5c-a605-3b29e5ad8f60.png">

Probably would be better to add a small rect around leaving point here, instead of the start point calculation
 
https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.tsx#L423

```js
getHull([
    {x: event.clientX+5, y: event.clientY+5},
    {x: event.clientX+5, y: event.clientY-5},
    {x: event.clientX-5, y: event.clientY+5},
    {x: event.clientX-5, y: event.clientY-5},
    ...hoverTargetPoints
]);
```

That gives the following graceArea and solves the issue above

<img width="145" alt="image" src="https://user-images.githubusercontent.com/5077042/209282448-8a760977-cd2f-40b4-baa0-66c1351087f3.png">

**Comment by benoitgrelard** [comment]
Hey @istarkov,

Thanks for reporting this, can you post a reproduction in a codesandbox?
You can use this demo as a stater: https://www.radix-ui.com/docs/primitives/components/tooltip

🙏

**Comment by sandgraham** [comment]
I think this sandbox reproduces the issue: https://codesandbox.io/s/radix-tooltip-grace-2l89x5.

https://user-images.githubusercontent.com/1939257/213818949-8c32e305-b809-47f3-bf95-f10379f2fc22.mp4
