### ISSUE TITLE
[Tooltip] TooltipContent doesn't render custom font

### ISSUE THREAD

**Issue by AugusDogus** [radix-ui/primitives#1872]
### Current Behavior

To demonstrate the issue I've set the font to wingdings so the bug is more easily recognized. You can see that for the text in white and red, the font is respected. However, for the text in the Tooltip, the font is not respected and it falls back to a system font.

![image](https://user-images.githubusercontent.com/9794679/210918777-04d957dc-1580-4b3f-81ad-fa3a8121e6e6.png)

### Expected behavior

The text in the TooltipContent should render with the correct font, wingdings in this case.

### Reproducible example

https://radix-font-issue-reproduction.vercel.app/

https://github.com/AugusDogus/radix-font-issue-reproduction

### Additional context

Possibly related to #1612 and #1567

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-tooltip    |     1.0.2    |
| React            | n/a     |   18.2.0      |
| Browser          |   Chrome      |         108.0.5359.125 |
| Assistive tech   |  n/a       |   n/a      |
| Node             | n/a     |   16.14.2      |
| npm/yarn/pnpm         |     pnpm    |    7.14.0     |
| Operating System |    Windows  11 Pro   |  22H2 Build 22621.963       |

**Comment by andy-hook** [comment]
@AugusDogus as you're using `Tooltip.Portal` the content will be appended to the `body`, you need to lift your wingdings variable and font assignment to respect this and have the font apply:

![image](https://user-images.githubusercontent.com/11708259/210961122-3691b223-87c0-46ea-b36a-6f9280b71f98.png)

Be aware that you also have a `font-sans` class applied to your content that will override this as well unless removed.

Hope this helps!

**Comment by AugusDogus** [comment]
Thanks for digging into this Andy! 

I've updated [my repository](https://github.com/AugusDogus/radix-font-issue-reproduction) with the fix in case anyone else runs into something similar and comes across this issue. 

I also found [this article](https://blog.logrocket.com/next-js-font-optimization/) was a great resource detailing the best practices for handling fonts with `@next/font` and Tailwind.

**Comment by andy-hook** [comment]
Note that you can also change the target node [`container` of the portal](https://www.radix-ui.com/docs/primitives/components/tooltip#portal) if you wish to change it's portalled position in the dom (for example to a wrapper in your app file)
