### ISSUE TITLE
Can't close opened menu || branch.contains is not a function

### ISSUE THREAD

**Issue by suren-avagyan** [radix-ui/primitives#1882]
### Current Behavior
When I open the menu, everything works perfectly, but when I click outside of the menu, an error message appears and states that the branch is undefined and cannot be called with contains? How to fix this issue? What exactly about my side is incorrect?

### Expected behavior

Upon clicking outside of a menu, to be closed

### Additional context

![image](https://user-images.githubusercontent.com/112713578/211648082-31dab890-85b1-40b8-a5ef-7d7290a5297f.png)
![image](https://user-images.githubusercontent.com/112713578/211648264-33aa0a64-26dc-4765-91e1-73f6fb5c69a8.png)

`Primitive.tsx`
![image](https://user-images.githubusercontent.com/112713578/211650180-fb24b272-0fc4-4f6a-97ee-60525324e288.png)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     "@radix-ui/react-dropdown-menu": "^2.0.1",     |         |
| React            | n/a     |  "react": "^16.14.0",   "react-dom": "^16.14.0",     |
| Browser          |   Chrome      |         |
| Assistive tech   |         |         |
| Node             | n/a     |    v17.16.1    |
| npm/yarn         |    npm     |         |
| Operating System |  Windows11|  Linux  |

**Comment by adamw-af** [comment]
@suren-avagyan did you come to a conclusion on why this happened? I am also seeing this.

**Comment by joao-venue** [comment]
Can someone tell how to solve this one? I'm having the same issue

**Comment by iceleo-com** [comment]
Hi,

It takes me half of day to find out what cause this problem.

If you use babel, please make sure that you the `loose` option of `@babel/preset-env` or `@babel/plugin-transform-spread` plugin is set to FALSE
