### ISSUE TITLE
Callback fired after a dialog is unmounted

### ISSUE THREAD

**Issue by marceloclp** [radix-ui/primitives#1886]
### Overview

For the Dialog component, we have `onAutoCloseFocus`, which allows us to fire a callback after the modal is closed. This is not particularly useful because we can always simply control the open state ourselves.

But there is no way to listen to the underlying presence component that listens to animations, so we can't fire a callback after the dialog has been unmounted, unless we align the animation duration with a `setTimeout`:

```tsx
const ANIMATION_DURATION = 500;

const Example = () => {
  const onClose = () => {
    setTimeout(() => {}, ANIMATION_DURATION);
  }
  
  return (
    <Dialog.Content onCloseAutoFocus={onClose} />
  )
}
```

While this would work, it's hacky and can break easily. I guess if you are using CSS-in-JS this is useless, but for the cases where you are not, this would be incredibly helpful.

**Comment by andy-hook** [comment]
> This is not particularly useful because we can always simply control the open state ourselves.

I'm afraid I'm not following on this point, are you able to provide an example of why this doesn't work for your use case?

**Comment by marceloclp** [comment]
> This is exactly how onCloseAutoFocus functions

From the documentation I would think this is the correct behaviour, but this seems to not be the case.

From my tests. `onCloseAutoFocus` is fired right after the open status is set to `false`, it does not wait for the animation to finish and for the element to be unmounted.

Could this be because it's controlled state?

I will try and write a codepen or smth to showcase this.

**Comment by marceloclp** [comment]
https://codesandbox.io/s/affectionate-roentgen-fkqvv9?file=/src/App.tsx

Here is an example of `onCloseAutoFocus` firing instantaneously instead of waiting for the animation to finish and for the component to be unmounted.

Could this perhaps be because I am not using `Dialog.Trigger`?

**Comment by andy-hook** [comment]
It's because you haven't applied the animation to `Content` so it unmounts immediately:

https://codesandbox.io/s/crimson-moon-z7ypst?file=/src/App.tsx
