### ISSUE TITLE
Select Placeholder not working using ForwardRef like in the documentation example

### ISSUE THREAD

**Issue by ZeroPie** [radix-ui/primitives#1889]
### Current Behavior

![CleanShot 2023-01-13 at 06 54 58](https://user-images.githubusercontent.com/8741666/212324976-75dfec2a-a088-499e-8de9-7faa7b8dce40.png)
Using the code from the documentation the select placeholder does not show.

[CodeSandbox Template](https://codesandbox.io/p/sandbox/misty-shape-pv0qft?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D)

### Expected behavior

The Placeholder text should be visible

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/misty-shape-pv0qft?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D)

### Your environment

[](https://codesandbox.io/p/sandbox/misty-shape-pv0qft?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D)

[CodeSandbox Template](https://codesandbox.io/p/sandbox/misty-shape-pv0qft?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A8%7D%5D)

**Comment by andy-hook** [comment]
@ZeroPie `placeholder` should be applied to `Select.Value` rather than `Trigger`. The `value` should also initialise to `undefined` for it to appear:

https://codesandbox.io/p/sandbox/blue-worker-k0f8np
