### ISSUE TITLE
Focus seems to stay trapped once dialog is unmounted

### ISSUE THREAD

**Issue by jvanbaarsen** [radix-ui/primitives#1891]
## Bug report

We are experiencing an issue with the Dialog box when not using triggers, in combination with trying to implement keyboard shortcuts.

## Our use case
In our app all our dialog boxes should be linkable, so when you share an URL with a colleague the page should be in the same state for the person that opens the link as it was for you (Including opened dialog boxes).

We managed to implement the dialog boxes without using the Trigger component, as for us the URL is the trigger. We do this by only including the component in the page if a certain param is present:

```
{params.overlay === "someOverlayName" && <OurOverlayComponent />}
```

All of this was working great, until we tried to implement keyboard shortcuts, here we ran into problems.

## The problem
We are able to open the modal without problems by navigating to a URL with the certain overlay keyword when the user presses a hotkey, but once the uses closes the dialog, they first have to click somewhere in the dom to make the hotkeys work again. After they clicked somewhere there is a delay of around .5s - 1s and when they then press the hotkey things work as expected.

We think we managed to debug this back to the way Radix is doing their focusTrapping, since this problem is only present when we set `modal=true` for the `Dialog.Root`. Once `modal` is set to false everything works as expected.

So I guess my questions are:
1) Is there a way to disable focusTrapping in the modal version of the dialog?
2) Are we even doing things correctly?
3) If needed, what can I provide more to explain this issue?

### Current Behavior

Once the dialog box is closed, it is not possible to re-open it again until you click anywhere in the dom so focus is "untrapped" from Radix Dialog

### Expected behavior

Once the dialog box get's unmounted, all focus is returned, and no keys are being trapped by Radix.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  Dialog       |  1.0.2       |
| React            | n/a     |  17.0.2        |
| Browser          |  Arc        |  Version 0.85.0 (36742); Chromium Engine Version 109.0.5414.87        |
| Node             | n/a     |    16.18.1     |
| npm/yarn         |   yarn      |  1.22.19        |
| Operating System |   MacOs      | 12.6        |

**Comment by joaom00** [comment]
Have you tried using `onCloseAutoFocus={event => event.preventDefault()}`?

**Comment by jvanbaarsen** [comment]
Actually yeah, I even tried passing the body dom element, and focussing the body on that callback:
```
        onCloseAutoFocus={(event) => {
          event.preventDefault()
          bodyElement.focus()
        }}
```

**Comment by jvanbaarsen** [comment]
Update on this:

I have the Click Outside, and Escape working without any delay, and it reopens the modal without problems, the only thing that I can;t get to work is the `Dialog.Close` button. I don't have any events attached to it, it looks like this:

```
      <Dialog.Close className="ignore-old-css c-overlay__close">
        <i className="align-middle fa fa-times"></i>
      </Dialog.Close>

```

**Comment by cheslip** [comment]
This may be related - https://github.com/radix-ui/primitives/issues/1546

**Comment by jvanbaarsen** [comment]
In the end we managed to fix this with using [flushSync](https://beta.reactjs.org/reference/react-dom/flushSync).

This is the code snippet:
```jsx
<Dialog.Root
      open={isOpen}
      onOpenChange={async (newIsOpen) => {
        /*
          Ensure the state is persisted (and the modal focusTrap is cleaned up)
          before we call the `onClose` callback to close the modal in the URL
        */
        flushSync(() => {
          setIsOpen(newIsOpen)
        })
        if (newIsOpen === false) {
          onClose()
        }
      }}
    >
....
</Dialog.Root>
```
