### ISSUE TITLE
[DropdownMenu] Using mozilla firefox, Dropdown cannot position itself when the trigger element disappears

### ISSUE THREAD

**Issue by joseBasso** [radix-ui/primitives#1894]
### Current Behavior
Using mozilla firefox, when a DropdownMenu trigger is rendered conditionally and disappears when we click it, the dropdown does not position itself correctly
![On mozilla](https://user-images.githubusercontent.com/25537426/213420254-4967f9cf-fec0-4062-ba8c-d6c2e17cb24a.png)

### Expected behavior
It should behave like chrome and position itself where the trigger was before it is gone
![On chrome](https://user-images.githubusercontent.com/25537426/213420400-9e42cf85-dd43-4092-b408-bbe37d538e07.png)

### Reproducible example

[CodeSandbox Template - Replicable on firefox](https://codesandbox.io/s/radix-ui-firefox-problem-gds511)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dropdown-menu | 2.0.2 |
| React            | n/a     |    18.2.0     |
| Browser          |    Mozilla firefox    |   109.0 (64-bit)    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |    MacOS     |   12.2   |

**Comment by joaom00** [comment]
Hi @joseBasso,

What are you trying to achieve?

**Comment by joseBasso** [comment]
Hi @joaom00 and @benoitgrelard. My intention was to include a dropdown menu and have its trigger visible only while hovering something, to avoid polluting our UI too much. The end goal was something like this: 


![hovering portal context](https://user-images.githubusercontent.com/25537426/213583685-f228592f-af60-4be5-9c14-02fe0c6d6d22.png)

I understand that this feels off but because it worked with Chrome, I assumed it was the intended behaviour. 
I'll work around it. Thank you for the work with the primitives 🥇

**Comment by joaom00** [comment]
@joseBasso I believe that the best UX for this case is to keep the `Trigger` visible when:

- Container is hovered or focused
- `Trigger` is focused
- `Content` is `open`

so when `Content` is closed, the `Trigger` will receive focus and keyboard users can keep browsing where they left off.

I made an [example](https://codesandbox.io/s/muddy-resonance-yvioxi?file=/App.js).

**Comment by benoitgrelard** [comment]
@joseBasso I see, the example @joaom00 suggested is great. They key mostly to avoid your issue is to ensure that when the menu is open, the trigger is always visible. You can rely on the `data-state="open"` attribute for that.
