### ISSUE TITLE
@radix-ui packages cause compiler errors due to phantom dependency on @types/react

### ISSUE THREAD

**Issue by octogonz** [radix-ui/primitives#1896]
### Current Behavior

This problem applies to all the `@radix-ui` packages. As one example, consider this type declaration:

**@radix-ui/react-checkbox/dist/index.d.ts**
```typescript
import * as React from "react";
import * as Radix from "@radix-ui/react-primitive";
import { Primitive } from "@radix-ui/react-primitive";
. . .
```

When I import `@radix-ui/react-checkbox`, my app fails to compile:

```
[typescript] Encountered 326 TypeScript issues:
[typescript] Error: node_modules\.pnpm\@radix-ui+react-checkbox@1.0.1_5owmthsvj5ictknaj3ev736ofq\node_modules\@radix-ui\react-checkbox\dist\index.d.ts:1:24 - (TS7016) Could not find a declaration file for module 'react'. 'node_modules/.pnpm/react@16.13.1/node_modules/react/index.js' implicitly has an 'any' type.
  If the 'react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react'
```

### Why does it fail to compile? 

The package has peer dependencies on React, but not its types:

**@radix-ui/react-checkbox/package.json**
```ts
{
  "name": "@radix-ui/react-checkbox",
  "version": "1.0.1",
  . . .
  "dependencies": {
    "@babel/runtime": "^7.13.10",
    "@radix-ui/primitive": "1.0.0",
    "@radix-ui/react-compose-refs": "1.0.0",
    "@radix-ui/react-context": "1.0.0",
    "@radix-ui/react-presence": "1.0.0",
    "@radix-ui/react-primitive": "1.0.1",
    "@radix-ui/react-use-controllable-state": "1.0.0",
    "@radix-ui/react-use-previous": "1.0.0",
    "@radix-ui/react-use-size": "1.0.0"
  },
  "peerDependencies": { // 👈👈👈
    "react": "^16.8 || ^17.0 || ^18.0",
    "react-dom": "^16.8 || ^17.0 || ^18.0"
  },
```

### Suggested fix

To fix the phantom dependency without bothering non-TypeScript users, the typings could be added as an optional peer:

```ts
  "peerDependencies": {
    "react": "^16.8 || ^17.0 || ^18.0",
    "react-dom": "^16.8 || ^17.0 || ^18.0",
    "@types/react": "*",
    "@types/react-dom": "*"
  },
  "peerDependenciesMeta": {
    "@types/react": {
      "optional": true
    },
    "@types/react-dom": {
      "optional": true
    }
  }
```

#### Possible reason 1: skipLibCheck

Some projects disable compiler error checking for external declarations, by enabling this setting:

**my-project/tsconfig.json**
```ts
{
  . . .
  "compilerOptions": {
    . . .
    "skipLibCheck": true
  }
}
```

This practice has a couple advantages: (1) it compiles faster, (2) it avoids the effort require to report GitHub issues to open source projects with broken declarations.  Any syntax error in the package's .d.ts files can be conveniently ignored.

This is not a good practice.  For professional software engineering, it is important that the type declarations for external APIs do not contain any mistakes, and that an application's API calls are correctly validated by the TypeScript compiler.  The compiler cannot function correctly when its analysis includes 326 compiler errors.

#### Possible reason 2: legacy node_modules hoisting

Yarn 1.0 and NPM install packages using a "hoisting" strategy that makes it possible for a package to import another NPM package that is not declared as a dependency.  This allows the compiler to find `@types/react` even though it's missing from **@radix-ui/react-checkbox/package.json**.  This is called a "phantom dependency."  Phantom dependencies are bad, because the consumer has no say about what version of `@types/react` it will get.  In a simplistic app, there's only one version, so it doesn't matter too much. But in a complex install (as commonly encountered in monorepos), there are likely to be multiple versions.  (For example, suppose our app uses Radix UI but it also has a dev depedency on a development tool that also depends on Radix UI, but an unrelated version.)

Yarn Plug'n'Play and the PNPM package manager both implement a stricter installation algorithm that can eliminate such hoisting (and its associated problems).  So this issue may be less noticeable by projects that use classic Yarn or NPM.

**Comment by benoitgrelard** [comment]
Hey @octogonz, thanks for reporting this!

> **Why didn't many other people encounter this problem?**
> Possible reason 1: skipLibCheck
> Possible reason 2: legacy node_modules hoisting

This is indeed the first time we hear from this! One thing I am wondering then:
Wouldn't the reason be rather that if you use Radix in a TS app, you will have installed the React types anyway?
When you show your error, doesn't that mean you didn't install the React types for your app?
I feel that would be a weird thing to do no?

I guess that's what you're trying to explain in reason 2?

> In a simplistic app, there's only one version, so it doesn't matter too much.

You can't have more than 1 version of React though also right?

**Comment by octogonz** [comment]
> This is indeed the first time we hear from this! One thing I am wondering then: Wouldn't the reason be rather that if you use Radix in a TS app, you will have installed the React types anyway? When you show your error, doesn't that mean you didn't install the React types for your app? 

Our app does indeed have React types installed.  Here's the **package.json** from https://github.com/william2958/rushstack/commit/1c94a71f858eef097b4204921d5d0138b34d7329:

[rush-themed-ui/package.json](https://github.com/william2958/rushstack/blob/1c94a71f858eef097b4204921d5d0138b34d7329/libraries/rush-themed-ui/package.json#L26)
```js
  . . .
  "dependencies": {
    "react": "~16.13.1",
    "react-dom": "~16.13.1"
  },
  "devDependencies": {
    "@rushstack/eslint-config": "workspace:*",
    "@rushstack/heft-web-rig": "workspace:*",
    "@rushstack/heft": "workspace:*",
    "@types/heft-jest": "1.0.1",
    "@types/react-dom": "16.9.14",
    "@types/react": "16.14.23",
    "@types/webpack-env": "1.13.0",
    "@radix-ui/react-scroll-area": "~1.0.2",
    "@radix-ui/colors": "~0.1.8",
    "@radix-ui/react-tabs": "~1.0.1",
    "@radix-ui/react-checkbox": "~1.0.1",
    "@radix-ui/react-icons": "~1.1.1"
  }
  . . .
```

> I guess that's what you're trying to explain in reason 2?

To be very clear: If we were to move our project into ***your GitHub repo,*** then the problem would not happen, because you are using Yarn Classic.  Yarn Classic creates [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/) through a technique called "hoisting". It's an unfortunate algorithm inherited from NPM and later fixed by Yarn Plug'n'Play (and also PNPM, in our setup).  [This doc](https://lfx.rushstack.io/pages/concepts/install_models/) gives a little more detail about the different installation models available for Node.js.

> You can't have more than 1 version of React though also right?

Sure you can.  Here's a random example (mentioned already above, but here's some more details):

- Hypothetically, let's imagine a package `awesome-build-tool` that gets installed from NPM
- For some reason (e.g. it shows a web page prompting for user input), `awesome-build-tool` happens to depend on `@radix-ui/react-tabs` with React 16
- And let's say `my-app` is a totally unrelated local project in my workspace
- `my-app/package.json` has a dev dependency on `awesome-build-tool`
- `my-app` also has a regular dependency on `@radix-ui/react-tabs` with React 18; this is totally unrelated to `awesome-build-tool` (except that dependencies and dev dependencies must share the same `node_modules` folder)

For a hoisted install this situation is a hopeless trainwreck. Coming from that world, the intuition will be that it's too complicated and there must be some shortcut to simplify it. But such complicated requirements do arise regularly in large code bases, which is why big companies use alternative package managers like PNPM and Yarn Plug'n'Play. Their installation models give well-defined semantics for side-by-side versions, and things work pretty well EXCEPT for various external packages that neglect to declare their dependencies properly. There's a few ways we deal with that:

- Asking the package maintainer to fix it (what I'm doing here), or
- Patching it locally (what I did in https://github.com/william2958/rushstack/commit/1c94a71f858eef097b4204921d5d0138b34d7329), or
- Importing a big database of community hacks: https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-extensions/sources/index.ts

Hope that gives some more context for this issue. 😅

**Comment by octogonz** [comment]
You could try to add a SemVer range, but since radix-ui already supports three different major versions of React, it is already the app developer's responsibility to solve the problem of finding a combination of typings that compile together without errors. Version constraints probably won't help too much with that.

**Comment by octogonz** [comment]
Yes, and if you look at `@types` packages from DefinitelyTyped that depend on other `@types` packages, most of them just use `*` as their range.

**Comment by octogonz** [comment]
(Also, just to clarify, the whole premise of peer dependencies is that the dependent project determines the version; when the `peerDependencies` specify a SemVer range, that is mainly a constraint for the app project. Whereas regular SemVer ranges are mainly a constraint for the package manager's version solver.)

**Comment by benoitgrelard** [comment]
Ok. I've created a PR for it: #2147

**Comment by relferreira** [comment]
I fixed this problem using `resolutions` from yarn for anyone still having this problem.

package.json
```json
"resolutions": {
  "@types/react": "^17"
}
```

**Comment by ruchernchong** [comment]
> I fixed this problem using `resolutions` from yarn for anyone still having this problem.
> 
> package.json
> 
> ```json
> "resolutions": {
>   "@types/react": "^17"
> }
> ```

As of time of this comment, it is solved in v18 now and do not cause breaking problems on newer Radix packages.
