### ISSUE TITLE
[Select] Multi-Select (replace react-select)

### ISSUE THREAD

**Issue by PeerRich** [radix-ui/primitives#1898]
> Select search: allows to use an input as a trigger and type some text to filter or select an item
> Select multi: allows to select multiple elements and display them as tags
> Select creatable: allows to type text in an input even if not available in the items list and commit it
>
> These three specifically would be very important for us.

_Originally posted by @billsaysthis in https://github.com/radix-ui/primitives/issues/1193#issuecomment-1146372633_
            
            
hey radix team, we are currently using react-select for multi select but it's really hard to use with tailwind and it would be awesome to get a native radix component for this.            
            
https://github.com/calcom/cal.com/issues/6593

**Comment by benoitgrelard** [comment]
This would be covered by #1342.
