### ISSUE TITLE
Select-component only sets `aria-selected=true` if the item is both selected and highlighted

### ISSUE THREAD

**Issue by jakst** [radix-ui/primitives#1907]
### Current Behavior

Select-component only sets `aria-selected=true` on an item if it is both selected and highlighted.

### Expected behavior

The selected item should always have `aria-selected=true`, even if it is not currently highlighted.

### Reproducible example

* Go into your own codesandbox example for react-select: https://codesandbox.io/s/3s9uzn?module=App.js
* Set `open={true}` on the `Select.Root` element, so that you can inspect it while it's open
* Inspect the `aria-selected` values of the different list elements
* `aria-selected` is only set to true when the selected element is also highlighted.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    react-select     |     1.2.0    |
| React            | n/a     |         |
| Browser          |     Chrome    |     108    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hey @jakst is this causing you an actual issue?
We are doing this on purpose to get around a stuttering issue with in VoiceOver.

See here:

https://github.com/radix-ui/primitives/blob/21a7c97dc8efa79fecca36428eec49f187294085/packages/react/select/src/Select.tsx#L1222-L1223

**Comment by jakst** [comment]
Well I was trying to write tests based on aria attributes. I would have preferred that rather than going on the `data-highlighted` attribute, as I am ensuring that the component is accessible in my test.

But in the end, using `data-highlighted` works. It just doesn't feel right :)
