### ISSUE TITLE
Accessibility issues with different popups

### ISSUE THREAD

**Issue by JakobsenF-ELS** [radix-ui/primitives#1909]
### Current Behavior
When running axe DevTools on my application, I'm getting these errors:
![axeDevTools_Radix-Issue-1](https://user-images.githubusercontent.com/64136913/215060187-ac73a371-6f46-42f6-a339-d78ca9160f4e.png)
![axeDevTools_Radix-Issue-2](https://user-images.githubusercontent.com/64136913/215060193-5072f84b-67f6-4b5e-a4ac-224d0549b3c2.png)

### Expected behavior
Radix components will pass the analysis with no accessibility issues

### Reproducible example
Try to run [axe DevTools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) on a page with e.g. a Radix dialog

### Suggested solution
Suggestion from axe DevTools:

> To solve this problem, you need to fix the following: _ARIA attribute is not allowed: aria-expanded="false"_

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |        "@radix-ui/react-dialog": "0.1.7", "@radix-ui/react-dropdown-menu": "0.1.6", "@radix-ui/react-popover": "1.0.0", "@radix-ui/react-toast": "0.1.1", "@radix-ui/react-tooltip": "0.1.7",     |
| React            | n/a     |    ">=16.8.5"     |
| Browser          |    Chrome     |    109.0.5414.74     |
| Assistive tech   |    axe DevTools     |     4.6.2    |
| Node             | n/a     |     ">=8.5.5"    |
| npm/yarn         |    node     |    ">=16.15.0"     |
| Operating System |     Ubuntu    |    20.04.5     |

**Comment by benoitgrelard** [comment]
It looks like you have converted your trigger from a button to a div. That would probably be why you are seeing this.

**Comment by Devanjan954** [comment]
did you find the solution

**Comment by benoitgrelard** [comment]
Closing as stale as I believe I provided the reason over a year ago.
