### ISSUE TITLE
[Tooltip] tooltips are shown for disabled buttons but documentation says it shouldn't happen

### ISSUE THREAD

**Issue by MikeYermolayev** [radix-ui/primitives#1914]
## Documentation
The documentation of tooltip has this section https://www.radix-ui.com/docs/primitives/components/tooltip#displaying-a-tooltip-from-a-disabled-button which suggests us that some extra actions should be made to display tooltips for disabled buttons.

As we can see in this [sandbox](https://codesandbox.io/s/pedantic-curie-eojbiv?file=/App.js) this is not true and tooltips are shown for disabled buttons by default. 

The issue is a follow-up to the [discussion in discord](https://discord.com/channels/752614004387610674/803656530259738674/1067059191140843540) @benoitgrelard found the PR #1358 that caused the change in behaviour

It will be good to update the documentation to reflect those changes

### Relevant Radix Component(s)

https://www.radix-ui.com/docs/primitives/components/tooltip

**Comment by mattandryc** [comment]
https://github.com/radix-ui/website/pull/714

**Comment by adaptive-shield-matrix** [comment]
The sandbox example throws an error for me
`Path must be a string. Received null`

I tried adding a Tooltip with a Button as a direct descendant myself and the Tooltip did not show for me.

Following the instructions in the official docs worked for me
https://www.radix-ui.com/primitives/docs/components/tooltip#displaying-a-tooltip-from-a-disabled-button

**Comment by MikeYermolayev** [comment]
fixed the sandbox

**Comment by adaptive-shield-matrix** [comment]
I did some testing
* your sandbox example works only with the default `button`
* but does not work with `Button` provided by https://ui.shadcn.com/docs/components/button

Since I do not want to replicate the styling I'l keep the Version from the docs for now.
So I guess the docs are still helpful / needed.

**Comment by benoitgrelard** [comment]
Closed via https://github.com/radix-ui/website/pull/714

**Comment by MildTomato** [comment]
Hey folks, it seems like Tooltip does now respect the `disabled` attr of the trigger
Anyone else seeing the same?

**Comment by joaom00** [comment]
> Hey folks, it seems like Tooltip does now respect the `disabled` attr of the trigger Anyone else seeing the same?

maybe you have `pointer-events: none` when disabled is true

**Comment by nicpz0** [comment]
> > Hey folks, it seems like Tooltip does now respect the `disabled` attr of the trigger Anyone else seeing the same?
> 
> maybe you have `pointer-events: none` when disabled is true

Indeed, setting `pointer-events: auto !important` (`!pointer-events-auto` in Tailwind) allows to show the tooltip even when disabled is true

**Comment by Kokleng-Dev** [comment]
+1
