### ISSUE TITLE
Popover container has zIndex auto?

### ISSUE THREAD

**Issue by rohitbelsare** [radix-ui/primitives#1916]
## Bug report
Popover container has zIndex auto?
Which makes it go behind other elements
### Current Behavior
We have no control on the Popover Container (Portal)

### Expected behavior
We should be allowed to apply style to container (Portal;)

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |       @radix-ui/react-popover  |      1.0.3   |
| React            | n/a     |   17.x.x      |

**Comment by joaom00** [comment]
When the `Portal` part is used the content is transported as the last child of the body, so generally you wouldn't have problems with z-index.

You can set a different container with `container` prop to portals the content part

**Comment by benoitgrelard** [comment]
You also do have control over the `z-index`, you can set it on your `Content` part and it will be copied automatically on the positioning wrapper.

**Comment by bodinsamuel** [comment]
@benoitgrelard Thanks for the answer, it should probably be documented that the Portal inherit the css 👍🏻 ☺️

**Comment by dgknca** [comment]
> You also do have control over the `z-index`, you can set it on your `Content` part and it will be copied automatically on the positioning wrapper.

but if you use `asChild` on `<Content>`, z-index is not copying.
