### ISSUE TITLE
[DialogContent] 'ref' callback is cleared and re-executed on every render

### ISSUE THREAD

**Issue by jeffberry** [radix-ui/primitives#1917]
### Current Behavior

When providing a ref to the `DialogContent` component, the ref gets cleared and then re-executed on every render of the component. 

```
<DialogContent
  ref={(el) => {
    console.log("RENDER CONTENT", el);
  }}
>
```

With every state change, this repeatedly logs: 
```
RENDER CONTENT <div role=​"dialog" [...]>​…​</div>​
RENDER CONTENT null
RENDER CONTENT <div role=​"dialog" [...]>​…​</div>​
RENDER CONTENT null
RENDER CONTENT <div role=​"dialog"[...]>​…​</div>​
```

### Expected behavior
The ref callback should only be executed when the component mounts and unmounts. 

From React documentation:
> React will call the ref callback with the DOM element when the component mounts, and call it with null when it unmounts. Refs are guaranteed to be up-to-date before componentDidMount or componentDidUpdate fires.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/hardcore-julien-n5brmw?file=/App.js)

### Suggested solution

I am worried that the `DialogContent` component is re-mounting with each state change which could cause performance issues. I poked around a little bit, but I have not set the Radix codebase up locally in order to do thorough debugging. I'm curious to see if this is an issue with other components as well, and if so, perhaps it is an issue with the `compose-refs` utility?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    [@radix-ui/react-dialog](https://codesandbox.io/examples/package/@radix-ui/react-dialog)     |    1.0.2     |
| React            | n/a     |    18.2.0     |
| Browser          |    Brave     |     [Version 1.47.186](https://brave.com/latest/)    |
| Assistive tech   |     n/a    |         |
| Node             | n/a     |         |
| npm/yarn         |     n/a    |         |
| Operating System |    OS X Ventura    |     13.2 (22D49)    |

**Comment by benoitgrelard** [comment]
Hey @jeffberry, what you are seeing here is correct and has nothing to do with Radix.
In Strict mode (in dev), React renders your component twice.
