### ISSUE TITLE
Tooltip Portals do not pass along additional props like className

### ISSUE THREAD

**Issue by izhan** [radix-ui/primitives#1918]
### Current / Expected Behavior

I expect
```tsx
<Tooltip.Portal className="foo">...</Tooltip.Portal>
```
to have the className `foo` applied to the positioning div. It does not apply any classNames today. Is this intentional?

My use case is adding in a className to control the z-index of the rendered tooltip.

### Suggested solution

Destructure `...portalProps` in https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.tsx#L336 and pass to the Portal instance

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Tooltip     |     1.0.3    |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
`Portal` parts don't render any DOM. You can control the `z-index` on the `Content` part.

**Comment by benoitgrelard** [comment]
Please note also that using portal should really negate the need for having to use z-index in the first place too.

**Comment by izhan** [comment]
@benoitgrelard Thanks for correcting. My mental model of this was incorrect, but I think there is still a feature gap / bug here that might warrant reopening this.

I tried adding a className to `<Tooltip.Contents>` but it is still rendering an extra div that does not have my contents className.

See
![Screenshot 2023-01-31 at 12 34 09 PM](https://user-images.githubusercontent.com/4621962/215876606-577063aa-f594-43a4-a5f4-edd75539aa92.png)

The selected outer wrapper div is the one that needs the className, but the className `tooltip_content__11xQM` I passed to `<Tooltip.Contents>` is only being applied to the inner div.

Dug in some more: issue is that there is no props that lets us configure the outermost div of `Popper.Contents` (see [here](https://github.com/radix-ui/primitives/blob/main/packages/react/popper/src/Popper.tsx#L272)). Any className or other props are passed to the [inner div](https://github.com/radix-ui/primitives/blob/main/packages/react/popper/src/Popper.tsx#L308)

Agreed that portals negate the need for z-index most of the time, but I think it's reasonable to expect edge cases that do require it. Any thoughts on exposing a way to pass props to that outer div in Popper.Contents?

**Comment by benoitgrelard** [comment]
Yes that's the positioning wrapper from popper.

> Agreed that portals negate the need for z-index most of the time, but I think it's reasonable to expect edge cases that do require it. Any thoughts on exposing a way to pass props to that outer div in Popper.Contents?

We have thought of that, and if you add `z-index` to the content part, it will be automatically copied over to the positioning wrapper so your `z-index` stacking is respected.

**Comment by dgknca** [comment]
> Yes that's the positioning wrapper from popper.
> 
> > Agreed that portals negate the need for z-index most of the time, but I think it's reasonable to expect edge cases that do require it. Any thoughts on exposing a way to pass props to that outer div in Popper.Contents?
> 
> We have thought of that, and if you add `z-index` to the content part, it will be automatically copied over to the positioning wrapper so your `z-index` stacking is respected.

no. it doesn't work. the wrapper's z-index is still `auto`.

**Comment by joaom00** [comment]
@dgknca In this sandbox works https://codesandbox.io/p/sandbox/zen-jang-bf2w8c

**Comment by dgknca** [comment]
@joaom00 it seems to be working in Tooltip. but doesn't work with Dropdown Menu component in the same way.

**Comment by joaom00** [comment]
@dgknca Seems to be working too https://codesandbox.io/p/sandbox/nice-gates-qyygc7

**Comment by ADTC** [comment]
> We have thought of that, and if you add `z-index` to the content part, it will be automatically copied over to the positioning wrapper so your `z-index` stacking is respected.

Can we document this in [the Tooltip documentation](https://www.radix-ui.com/primitives/docs/components/tooltip) (and others where relevant)? Seems like an important bit of information to have in the docs.

**Comment by coldshower** [comment]
> > Yes that's the positioning wrapper from popper.
> > > Agreed that portals negate the need for z-index most of the time, but I think it's reasonable to expect edge cases that do require it. Any thoughts on exposing a way to pass props to that outer div in Popper.Contents?
> > 
> > 
> > We have thought of that, and if you add `z-index` to the content part, it will be automatically copied over to the positioning wrapper so your `z-index` stacking is respected.
> 
> no. it doesn't work. the wrapper's z-index is still `auto`.

In case you are using tailwind, if className `z-50` doesn't work, try using an inline style, like `style={{zIndex: 50}}` which worked for me. I wonder if tailwind is doing something special under the hood which makes it so that the transfer doesn't happen properly.
