### ISSUE TITLE
[DropdownMenu]: using Button component inside Trigger

### ISSUE THREAD

**Issue by iair2750** [radix-ui/primitives#1924]
### Current Behavior
When I used html button inside the Trigger everything works fine, but when I used my Button component for some reason the Content will have `transform: translate3d(0px, -200%, 0px)`

### Expected behavior
It should be the same behavior if I use the html button or my Button component

### Reproducible example
[CodeSandbox Template](https://codesandbox.io/s/dark-waterfall-cg8njr?file=/src/App.tsx)

### Additional context
This is happening only if I used Trigger with `asChild`. In this case it is mandatory to be used like this because I can't have 2 buttons for the Trigger.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dropdown-menu  | 2.0.2        |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  Windows  |         |

**Comment by benoitgrelard** [comment]
You need to ensure your `Button` forwards ref using `React.forwardRef`. This is so that your button can be measured in order to position the content.
