### ISSUE TITLE
[Separator] Separator component in vertical orientation do not take up any height in the DOM when contained in flex containers

### ISSUE THREAD

**Issue by scottwarren** [radix-ui/primitives#1926]
### Current Behavior

Vertical separators within flex containers don't show up (they don't take any height in the DOM) and therefore don't show up. Horizontal works as expected

![image](https://user-images.githubusercontent.com/2718494/216570044-dcbec746-8683-4f71-a21b-d7b5b52be4e5.png)

### Expected behavior

Vertical divider should take up 100% of the height

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

Example: https://codesandbox.io/s/reverent-dust-pl1b5j?file=/App.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | -------   | ------- |
| Radix Package(s) | Separator | 1.0.1 |
| React            | n/a       | 17.0.2 |
| Browser          | Chrome |  109.0.5414.119  |
| Assistive tech   |           |         |
| Node             | n/a       |         |
| npm/yarn         | npm | 8.3.1  |
| Operating System | Mac OS X  | 12.6  |

**Comment by scottwarren** [comment]
FWIW I've tried fixing this exact issue in an "in-house" UI component, before trying to move to Radix for the separator component, but wasn't able to figure out the solution

**Comment by andy-hook** [comment]
@scottwarren You need to drop the `height: 100%`, with that property the separators are attempting to size to the parent of which is not explicitly provided.

https://codesandbox.io/s/vertical-separator-fill-parent-f1ysyt?file=/App.js

**Comment by andy-hook** [comment]
Let me know if that solution works for you, I'm going to close this out as it's more of a styling consideration than an issue with the library.

**Comment by scottwarren** [comment]
Thank you very much!
