### ISSUE TITLE
Floating UI's Virtual Elements not respected in collisionBoundary

### ISSUE THREAD

**Issue by jamiebuilds** [radix-ui/primitives#1937]
### Current Behavior

```ts
<HoverCard.Content
  collisionBoundary={{
    getBoundingClientRect() {
      return scrollerRef.current!.getBoundingClientRect();
    }
  } as Element}
>
```

This is ignored somewhere, it doesn't affect the floating behavior

### Expected behavior

[Virtual elements](https://floating-ui.com/docs/virtual-elements) should work the same as having a real element

### Reproducible example

[[CodeSandbox Template](https://codesandbox.io/s/2r30e)](https://codesandbox.io/s/radix-hovermenu-collisionboundary-with-virtual-elements-gh-issue-oodfsh?file=/src/App.tsx)

### Additional context

Passing refs down through React context in order to provide collision boundaries generically within other design system components.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | `@radix-ui/react-hover-card`        | `1.0.3`        |
| React            | n/a     | `18.0.0`        |
| Browser          | Chrome/Safari       |  109/16       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | macOS        | Monteray        |

**Comment by benoitgrelard** [comment]
Hey @jamiebuilds,

I know we constrain the type of boundary to only `Element | Element[]` but regardless, it doesn't seem like Floating UI support virtual elements as boundaries.

https://floating-ui.com/docs/detectOverflow#boundary

**Comment by atomiks** [comment]
Support for "virtual" boundaries (relative to the viewport) was added a couple of days ago (`1.2.0`), the type now includes `Rect`.

But this particular case looks like the element should be stored in state, assuming this is only because you don't want to read the ref in render?

```js
const [scroller, setScroller] = useState<HTMLElement | null>(null);

<HoverCard.Content
  collisionBoundary={scroller}
>

<div ref={setScroller} />
```

**Comment by benoitgrelard** [comment]
> But this particular case looks like the element should be stored in state, assuming this is only because you don't want to read the ref in render?

Yes that makes sense to me too.

**Comment by jamiebuilds** [comment]
I don't believe it's a good idea to be calling `setState` inside of render

**Comment by benoitgrelard** [comment]
What do you mean?

Are you referring to this: `<div ref={setScroller} />`?

If so that's perfectly valid, we use this all over Radix, it makes use of legacy callback refs, and because the state setters from `useState` are referentially transparent, the ref callback is stable.

**Comment by jamiebuilds** [comment]
Yes it's a valid type, and it does work, but I don't think it's a very good pattern to use because it will inherently have to re-render, when you can just setup effects/etc to run at the right times

**Comment by benoitgrelard** [comment]
Yeah most times refs are enough if all you need are effects, but there are definitely cases where you need the node available in render.

**Comment by atomiks** [comment]
The most valid use case for it is conditional rendering where the elements themselves change and the library doesn't know what piece of state caused it to change, and "informing" it any other way is impractical. 

e.g. if the collision boundary element changed, this setter technique will always give Radix the right node, whereas if you used a non-reactive ref, it's not going to know if it changed unless you tell it by passing some state which isn't really practical.

**Comment by jamiebuilds** [comment]
The specific thing I'm doing is building a `<CollisionBoundary>` component:

```tsx
<CollisionBoundary>
  <Scroller>
    ...
  </Scroller>
</CollisionBoundary>
```

This would, through context, provide a ref for any floating component that should stay within the boundary.

This lets components further down the tree be a bit more abstract and resilient against changes in the UI.

**Comment by benoitgrelard** [comment]
Given this comment: https://github.com/radix-ui/primitives/issues/1937#issuecomment-1422085442 and the fact we recently updated to latest floating-ui, this should now be supported.

Please re-open if something isn't working as you'd expect.
