### ISSUE TITLE
Pressing 'esc' while Select is open inside Dialog closes entire Dialog

### ISSUE THREAD

**Issue by ScottSavarie** [radix-ui/primitives#1951]
### Current Behavior
Currently if you use open a Select component inside of a `Dialog`, the keyboard handling is such that when you press `escape` to close the `Select`, it closes the entire `Dialog`.

### Expected behavior
- `Escape` should close the `Select`
- Once closed, pressing `Escape` again should close the dialog

### Reproducible example
Not my Codesandbox, just one I found while searching the issue: 
[CodeSandbox Template](https://codesandbox.io/s/radix-select-inside-radix-dialog-5lwgym)

### Suggested solution
Check if the focused element is a Select, or a Native select, and prevent closing the dialog. 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-dialog, react-select       | 1.0.0  |
| React            | n/a     |  18.2.0       |
| Browser          |  Chrome / Safari       |    latest     |
| Assistive tech   |         |         |
| Node             | n/a     |  16.8.1   |
| npm/yarn         |         |         |
| Operating System |   Mac   |    12.5     |

**Comment by joaom00** [comment]
Are you using the latest version of these packages? `Dialog` and `Select` use `DismissableLayer` package internally and if they are using different versions of it then the layering breaks. It's a known issue https://github.com/radix-ui/primitives/issues/1088.

In the CodeSandbox you pointed out, if you update `Select` to the latest version everything seems to work.

**Comment by benoitgrelard** [comment]
Closing as @joaom00 already reported the correct answer.

**Comment by ScottSavarie** [comment]
This, worked thank you both! 🙌
