### ISSUE TITLE
AccordionItemTriggers only triggers with an in-line reference

### ISSUE THREAD

**Issue by myxoh** [radix-ui/primitives#1972]
### Current Behavior

I cannot get the AccordionItemTrigger to trigger unless there's a parent level component defined in-line on the accordion

### Expected behavior

I should be able to delegate to a trigger entirely

### Reproducible example

[[CodeSandbox Template](https://codesandbox.io/s/2r30e)](https://codesandbox.io/s/ancient-darkness-t434e1?file=/src/App.tsx)

### Suggested solution

Either of the examples should work?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi @myxoh,

There are a few issues with your example:
- You are entirely missing the `Accordion.Header` part
- If you want to use `asChild` for the trigger, you need ensure a few things:
  - forward all props
  - forward ref
  - the element rendered should really be a `button` which is what `Accordion.Trigger` renders (you could do with a div, but you'll have to re-implement all of the default behaviour/accessibility of a button).

Hope that makes sense!

✌️

**Comment by myxoh** [comment]
Hi - in case someone is encountering this - it seems the forwarding the props did the trick. TIL about that - as I assumed there were no props here (not sure where the props are coming from as I'm not setting it - but something for me to discover)😅.

Thank you @benoitgrelard
