### ISSUE TITLE
Wrong type for checked in DropdownMenu.CheckboxItem onCheckedChange

### ISSUE THREAD

**Issue by its-monotype** [radix-ui/primitives#1996]
## Bug report

With the latest updates, I noticed a problem. The checked state should be typed as CheckedState and not boolean, isn't it?

"@radix-ui/react-dropdown-menu": "^2.0.3",

### Current Behavior

![image](https://user-images.githubusercontent.com/79363260/223095248-1b569927-cce6-4d60-a0e7-7ae6b25edbfe.png)

![image](https://user-images.githubusercontent.com/79363260/223094821-5ec48630-4b1c-4210-9a2c-504a9ae221b3.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/79363260/223095159-595857b5-3aaf-417e-a10c-b6a5ec12c333.png)

![image](https://user-images.githubusercontent.com/79363260/223094856-fd892df4-6867-4266-9428-9a9937dd3891.png)

**Comment by benoitgrelard** [comment]
Hey @its-monotype,

The new type is actually correct because `onCheckedChange` can never call you with `"indeterminate"` as that is something you control via `checked`, the component itself cannot guess when you'd want it to be indeterminate.

The type was fixed here: #1778 in case you want more background understanding about it.

**Comment by its-monotype** [comment]
> Hey @its-monotype,
> 
> The new type is actually correct because `onCheckedChange` can never call you with `"indeterminate"` as that is something you control via `checked`, the component itself cannot guess when you'd want it to be indeterminate.
> 
> The type was fixed here: #1778 in case you want more background understanding about it.

Thanks for the clarification! I was a bit lost before, but your explanation really helped me grasp the concept better.
