### ISSUE TITLE
Non-button popover trigger doesn't close popover when in a modal dialog

### ISSUE THREAD

**Issue by uiii** [radix-ui/primitives#2000]
### Current Behavior

When the non-button (div, span) popover trigger is in a modal dialog, first click will open the popover but the second click doesn't close it. For button triggers or outside of the modal it works fine.

https://user-images.githubusercontent.com/179219/223143464-1f0b3093-8c1d-431c-80c2-5e26e4ca01d6.mp4

### Expected behavior

Second click to any popover trigger should close the popover even if it is in the modal dialog.

### Reproducible example

https://codesandbox.io/p/sandbox/agitated-leakey-ztzp4f?file=%2FApp.jsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-dialog        | 1.0.2        |
| | @radix-ui/react-popover | 1.0.4 |

**Comment by joaom00** [comment]
I don't know why the behavior is different in dialog but why you want the trigger to be a div? it must be a button otherwise  it isn't possible to navigate with tabs, open with `Space` or `Enter`

**Comment by uiii** [comment]
> I don't know why the behavior is different in dialog but why you want the trigger to be a div?

@joaom00 I'd like to have o popover over highlighted word in a text, so actually over `span`.

**Comment by joaom00** [comment]
What you can do (I don't know why this works :sweat_smile:) is set `tabIndex="0"` in the div and it seems to work

**Comment by benoitgrelard** [comment]
As @joaom00 pointed out I think that's outside of the scope given it should be a `button` anyway.
