### ISSUE TITLE
asChild breaks when passing a Text Node as the child.

### ISSUE THREAD

**Issue by AdamLeBlanc** [radix-ui/primitives#2007]
### Current Behavior

When you pass a Text Node to a primitive that has the `asChild` prop, nothing is rendered.

### Expected behavior

It should render the Text Node without any of its default DOM elements.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

https://codesandbox.io/s/zealous-julien-ek3c7o?file=/src/App.tsx

```javascript
import * as React from "react";
import * as Label from "@radix-ui/react-label";

// If you aren't working in TypeScript, feel free to rename
// this file to `App.js` and reproduce your issue without
// types.

export function App() {
  return (
    <>
      <Label.Root>Working</Label.Root>
      <Label.Root asChild>Not Working</Label.Root>
      <Label.Root asChild>
        <>Working</>
      </Label.Root>
      <Label.Root asChild>
        <div>Working</div>
      </Label.Root>
    </>
  );
}
```

### Suggested solution

The `Primitive` function in `Primitive.tsx` probably needs updated, but I'm not sure what the best approach to take there is off the top of my head. 

Alternatively, if the current functionality is intentional, update the documentation to say that if you pass `asChild` you need to wrap text nodes in a fragment. 

### Additional context

This is particularly problematic with the new nextjs Link component. 

```typescript
const NavigationMenuNextLink = React.forwardRef<
  HTMLAnchorElement,
  NavigationMenuNextLinkProps
>(({ href, children, ...props }, forwardRef) => {
  const pathName = usePathname();
  const isActive = pathName === href;

  return (
    <NextLink href={href} passHref>
      <NavigationMenu.Link
        active={isActive}
        {...props}
        ref={forwardRef}
        asChild
      >
        {children}
      </NavigationMenu.Link>
    </NextLink>
  );
});

NavigationMenuNextLink.displayName = "NavigationMenuNextLink";
```

You need to use the `asChild` prop here because the next link provides its own `a` tag. Without it, you will have nested `a` tags. There are many cases where you would just want to pass a regular 'ol TextNode to a component like this.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-navigation-menu, react-label       |   1.1.1, 2.0.0      |
| React            | n/a     |      18.0.28   |
| Browser          |    Chrome, Firefox     |   110.0.5481.178,   110.0.1     |
| Assistive tech   |         |         |
| Node             | n/a     |    v18.12.1     |
| npm/yarn         |   yarn      |     1.22.19    |
| Operating System |   Windows 11      |   22621.1265      |

**Comment by benoitgrelard** [comment]
Hey @AdamLeBlanc, that is expected.
`asChild` clones the first child so it has to be an element so it can receive the necessary props.
There is no reason to use `asChild` with a text node as a child, it wouldn't make sense.

> You need to use the asChild prop here because the next link provides its own a tag. Without it, you will have nested a tags.

That is the whole point of `asChild`, so you don't end up with nested `a`, you use `asChild` to say, use the one that's the first child, not yourself.

So with your Nextjs example, it should be flipped around so you are targetting their `a`, something like:

```jsx
<NavigationMenu.Link asChild>
  <NextLink>
    {children}
  </NextLink>
</NavigationMenu.Link>
```
