### ISSUE TITLE
`Slot` in server component gives error

### ISSUE THREAD

**Issue by kuus** [radix-ui/primitives#2011]
## Bug report
Not sure if this is to be considered a bug actually, but trying to use `Slot` from `import { Slot } from "@radix-ui/react-slot";` in a server component (within next@13.2 framework) you get an error.

### Current Behavior

You get an error: `Error: Refs cannot be used in Server Components, nor passed to Client Components.`

### Expected behavior

Can `Slot` work in a server component?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |   1      |
| React            | n/a     |    18.2     |

**Comment by benoitgrelard** [comment]
Hey @kuus, I don't believe it could given the error message.

From my understanding with server components, you are restricted in terms of what features of React can be used, for example `useState` cannot be used, etc.

It sounds like refs can't be used either so that means `Slot` cannot be used in a server component because it needs to attach a ref to the cloned element.

Hope that makes sense.

✌️

**Comment by benoitgrelard** [comment]
Pretty much all Radix components are client components though, what is your use case for `asChild` in server components?

**Comment by kuus** [comment]
I think is pretty common, in the footer I have some social media links, they are styled as buttons but they are links,
my `Button` component implementation uses `asChild` prop with `Slot` component so that it can be used to style both HTML links `<a>` and `<button>` or even `<span>` if needed, etc.

Pseudo code:
```js
<Button asChild>
  <a href="https://example.com>An icon</a>
</Button>
```
This is defnitely a good candidate for a server component as it is just a plain `<a>` element with some style...
Hope you see what I mean, to sum up: `Slot`table components are often good candidates to be server components

**Comment by kuus** [comment]
hi @benoitgrelard , I just tried to remove the refs usage and that is enough to make the `Slot` component play nice as RSC.
Regarding the general attempt of making the Slot component usable as RSC I don't know yet if there is an "illegal" way to conditionally use `useRef` (maybe in a `try catch..`?), and I am also very unsure that is a viable path...but I will post here if I find anything useful.

Meanwhile here is a playground:
https://codesandbox.io/p/sandbox/next-13-slot-imd6ft

cheers

**Comment by benoitgrelard** [comment]
That makes sense, removing the illegal bit. But now you wouldn't be able to attach a ref to it, so I'm kinda confused how this would be useful.

btw, I don't have much knowledge of RSC yet so I'm probably talking rubbish.
