### ISSUE TITLE
[Dialog] Element with tabIndex -1 is not automatically focused

### ISSUE THREAD

**Issue by joeporpeglia** [radix-ui/primitives#2030]
## Bug report

The [Dialog ARIA](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) pattern linked from the radix docs recommends setting `tabIndex="-1"` on static elements in some scenarios. For example:

> If content is large enough that focusing the first interactive element could cause the beginning of content to scroll out of view, it is advisable to add `tabindex="-1"` to a static element at the top of the dialog, such as the dialog title or first paragraph, and initially focus that element.

However, the autofocus behavior of the dialog component excludes elements with `tabindex="-1"`.

### Current Behavior

The first **_keyboard focusable_** element receives focus on dialog open.

### Expected behavior

The first focusable element receives focus on dialog open, including those with `tabIndex={-1}`.

### Reproducible example

https://codesandbox.io/s/strange-paper-pxoh8l?file=/src/App.tsx

### Suggested solution

Update [`FocusScope`](https://github.com/radix-ui/primitives/blob/1b05a8e35cf35f3020484979086d70aefbaf4095/packages/react/focus-scope/src/FocusScope.tsx#L226) to allow elements with `tabindex="-1"` for this use case.

### Additional context

Overriding this behavior via `onOpenAutoFocus` isn't ideal because it disables the default focus behavior, which may still be desired for some instances. The override may be simple enough when using radix dialog directly in an app, but it adds some complexity when using radix dialog in a shared component library.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |    1.0.3     |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |   111.0.5563.64      |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |   yarn      |     1.22.19    |
| Operating System |     Mac OS    |     12.6    |

**Comment by benoitgrelard** [comment]
> If content is large enough that focusing the first interactive element could cause the beginning of content to scroll out of view, it is advisable to add tabindex="-1" to a static element at the top of the dialog, such as the dialog title or first paragraph, and initially focus that element.

This is a suggestions made for authors in general, and isn't something that can be achieved at the library level, because it requires case-by-case attention.

The reason they advise `tabIndex="-1"` is specifically so it's not "tabbable" but is "focusable" programatically for the purpose of accessibility.

Hence, what Radix does by default is the expected behaviour.

Overriding on a case by case basis using `onOpenAutoFocus` is the correct solution here.
