### ISSUE TITLE
Dialog description is never read by screen reader

### ISSUE THREAD

**Issue by Kinbaum** [radix-ui/primitives#2038]
## Bug report

The `aria-describedby` attribute is not read by the screen reader. 

### Current Behavior

<img width="1392" alt="Screen Shot 2023-03-21 at 11 41 35 AM" src="https://user-images.githubusercontent.com/6590356/226660141-9f49a3f0-760f-4ddc-8ddf-62d132ca9d03.png">

<img width="1279" alt="Screen Shot 2023-03-21 at 11 42 35 AM" src="https://user-images.githubusercontent.com/6590356/226660596-0fc7a239-59fd-427e-8f87-bd23f5ee06d1.png">

### Expected behavior

I expect the if the description is provided either through the component or using `aria-describedby`, that the screen reader will announce it.

### Reproducible example

[Radix Website](https://www.radix-ui.com/docs/primitives/components/dialog)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |     1.0.3    |
| React            | n/a     |    18.0.2     |
| Browser          |    Edge     |    111.0.1661.44    |
| Assistive tech   |    Voiceover     |        |
| Node             | n/a     |    16.15.1     |
| npm/yarn         |         |    3.4.1     |
| Operating System |    MacOS     |    12.6.1     |

**Comment by ricci2511** [comment]
Seems to be fixed already.

<img width="1728" alt="Screenshot 2023-04-02 at 13 02 25" src="https://user-images.githubusercontent.com/80476005/229349044-a53191e4-aba0-4263-bd1f-50f8bb91329f.png">

**Comment by Kinbaum** [comment]
@ricci2511 What version of macOS are you running? Wonder if this is a voiceover bug

**Comment by ricci2511** [comment]
> @ricci2511 What version of macOS are you running? Wonder if this is a voiceover bug

Im running macOS Ventura version 13.1, I tested both on the radix website and locally.

**Comment by Kinbaum** [comment]
Ok good to know. I’m using 12.6.1 and this issue persists there
