### ISSUE TITLE
Can't interact with other DOM elements while menus are open

### ISSUE THREAD

**Issue by noah-wardlow** [radix-ui/primitives#2040]
### Current Behavior

When popover or dropdown menus are open, other DOM elements don't respond to clicks

### Expected behavior

Open menus shouldn't block other events
### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment]
It's because of the `modal={true}`, you can disable

**Comment by noah-wardlow** [comment]
Thank you @joaom00
