### ISSUE TITLE
Popover when hover

### ISSUE THREAD

**Issue by talatkuyuk** [radix-ui/primitives#2051]
## Feature request

Is it possible to show `popover` when hover on the trigger component? 

Could be there an option to choose either : `when click` or `when hover` for showing the popover?

**Comment by joaom00** [comment]
You can control the state to achieve this

**Comment by boompikachu** [comment]
To prevent clicking
```jsx
<Popover.Trigger
  onMouseEnter={handleMouseEnter}
  onMouseLeave={handleMouseLeave}
  onClick={e => {
    e.preventDefault();
   }}
>
  Hover me
</Popover.Trigger>
```

**Comment by MurkyMeow** [comment]
I suggest using a `useHover` hook for this (e. g. https://gist.github.com/MurkyMeow/2d0f3cdd1a9034dcc1d9b8348799a6e2)

**Comment by ThePiyushAggarwal** [comment]
@MurkyMeow Thanks! Looks better using the hook. Is there any other conceptual difference between using `onMouseEnter` prop and using event listeners?

**Comment by ThePiyushAggarwal** [comment]
> I suggest using a `useHover` hook for this (e. g. https://gist.github.com/MurkyMeow/2d0f3cdd1a9034dcc1d9b8348799a6e2)


I observed that the PopoverContent will hide once you leave the PopoverTrigger. So, you need to get a hovering state for the PopoverContent as well.

**Comment by keshavm1802** [comment]
> > I suggest using a `useHover` hook for this (e. g. https://gist.github.com/MurkyMeow/2d0f3cdd1a9034dcc1d9b8348799a6e2)
> 
> I observed that the PopoverContent will hide once you leave the PopoverTrigger. So, you need to get a hovering state for the PopoverContent as well.

Did you managed to implement that?

**Comment by zeroliu** [comment]
Tooltip component is meant for trigger popup on hover. Can it be considered?

**Comment by chambaz** [comment]
it works nice with a debounce as well, to prevent jumping when hovering between trigger / content. I used `@uidotdev/usehooks`

to build on @williamisnotdefined example...

```
import React, { useState } from "react";
import * as Popover from "@radix-ui/react-popover";
import { useDebounce } from "@uidotdev/usehooks";

const HoverPopover = () => {
  const [open, setOpen] = useState(false);
  const debouncedOpen = useDebounce(open, 200);

  const handleMouseEnter = () => {
    setOpen(true);
  };

  const handleMouseLeave = () => {
    setOpen(false);
  };

  return (
    <Popover.Root open={debouncedOpen} onOpenChange={setOpen}>
      <Popover.Trigger
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        Hover me
      </Popover.Trigger>
      <Popover.Content
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        Popover content
      </Popover.Content>
      <Popover.Arrow />
    </Popover.Root>
  );
};

export default HoverPopover;

```

**Comment by Dmitry-Titov-K** [comment]
If you try the options suggested above , don’t forget to put ` <Popover.Arrow />` inside ` <Popover.Content>`

```js

 <Popover.Content/>
   // ...your content
  <Popover.Arrow />
 </Popover.Content>

```

**Comment by hallucinogenizer** [comment]
Use tooltips instead

**Comment by ThePiyushAggarwal** [comment]
For my use case, I ended up using [Hover Card](https://www.radix-ui.com/primitives/docs/components/hover-card) and it works great.

**Comment by omattman** [comment]
Note that the proposal suggested by @ThePiyushAggarwal is only applicable when you want the entire card to be a link. If a link is not provided you will receive a `Links are not crawable` warning that will impact your SEO score. Best suggestion is to build a Popover component with hover functionality similarly to the suggestion provided by @chambaz. One may also be tempted to use the Tooltip component, however, keep in mind that any interactive elements inside a tooltip is against its WAI-ARIA rules:

> Because the tooltip itself never receives focus and is not in the tabbing order, a tooltip can not contain interactive elements like links, inputs, or buttons.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role

**Comment by talonops** [comment]
> Note that the proposal suggested by [@ThePiyushAggarwal](https://github.com/ThePiyushAggarwal) is only applicable when you want the trigger to be a link. If a link is not provided you will receive a `Links are not crawable` warning that will impact your SEO score. Best suggestion is to build a Popover component with hover functionality similarly to the suggestion provided by [@chambaz](https://github.com/chambaz) if you are to add interactive elements or nested links. One may also be tempted to use the Tooltip component, as suggested by [@hallucinogenizer](https://github.com/hallucinogenizer), however, keep in mind that any interactive elements inside a tooltip is the wrong practice of WCAG:
> 
> > Because the tooltip itself never receives focus and is not in the tabbing order, a tooltip can not contain interactive elements like links, inputs, or buttons.
> 
> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role

W!
