### ISSUE TITLE
Calling e.preventDefault() on a Popover.Trigger, without disabling the popover altogether

### ISSUE THREAD

**Issue by izhan** [radix-ui/primitives#2056]
### Current Behavior

I have a link today that on click redirects the user to another page. Inside the link, there is various elements, including a `<button>` with a Radix popover.

```jsx
<Link to="somewhere.com">
  <span>Something else</span>
  <Popover.Root>
    <Popover.Trigger asChild><button>Button</button></Popover.Trigger>
    <Popover.Content asChild><div>Popover Contents</div></Popover.Content>
  </Popover.Root>
</Link>
```

When that button is clicked, I want to show the popover and not redirect. I'd expect this to work when adding `onClick={e => e.preventDefault()}` to the button. However due to `composeEventHandlers`'s behavior today, this actually makes the popover not  show at all.

### Expected behavior

I expect the popover to still show when calling e.preventDefault() on the button. If not, are there any workarounds?

### Reproducible example

[CodeSandbox with this issue](https://codesandbox.io/s/async-wildflower-qozife?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment]
I would say it's weird to have a button inside an anchor so moving the button outside the link would solve your problem but if that's not possible you can check if the `target` and `currentTarget` are different and then prevent opening the link or you can call `preventDefault` in `Popover.Trigger` and control the open state yourself.

https://codesandbox.io/s/agitated-jones-0q7ceo?file=/src/App.tsx

**Comment by izhan** [comment]
@joaom00 thanks! making it controlled could work for our case

What was the reason we check for `defaultPrevented` in `composeEventHandlers`? Is it an intentional escape hatch for users or an internal detail?

**Comment by joaom00** [comment]
It's an intentional escape hatch for users
