### ISSUE TITLE
ScrollArea does not elastic band in Chrome

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#2058]
### Current Behavior

Scrolling "past the edge" of a ScrollArea does not rubber band on Google Chrome (tested on Version 111.0.5563.146) or Brave (Version 1.49.132/111.0.5563.147)

https://user-images.githubusercontent.com/34928425/228990794-53dca7b9-2dad-43f7-b29b-4dee06a46fd6.mp4

### Expected behavior

It correctly rubber bands on Firefox:

https://user-images.githubusercontent.com/34928425/228990979-2b890526-9b5f-457a-ac6f-9b038e2d3cfd.mp4

and on Safari:

https://user-images.githubusercontent.com/34928425/228991018-c018b899-8c89-472e-91a3-a559c2467ba2.mp4

### Reproducible example

The ScrollArea documentation example was used for the recordings above:
https://codesandbox.io/p/sandbox/bnoymn

### Suggested solution

None. Not sure why it's only affecting Chrome.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-scroll-area       |     1.0.3    |
| React            | n/a     |  18.2.0       |
| Browser          |         |  Mentioned above       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by atomiks** [comment]
This is a problem with native Chrome's scroll views.

I [wrote a polyfill for it](https://github.com/atomiks/elastic-scroll-polyfill) years ago, but it wasn't perfect due to a lack of `scrollend` event. Now that the event is in Chrome 114, I think we _can_ polyfill it properly, but of course, I wish Chrome would just implement it natively like Firefox did 😄

**Comment by benoitgrelard** [comment]
> This is a problem with Chrome's native scroll views. In Firefox, it got implemented only in mid-2021 (_including_ on the `<body>`/window, which Chrome has implemented for over a decade now.)
> 
> [I wrote a polyfill for it](https://github.com/atomiks/elastic-scroll-polyfill) years ago, but it wasn't perfect due to a lack of `scrollend` event. Now that the event is in Chrome 114, I think we _can_ polyfill it properly, but of course, I wish Chrome would just implement it natively like Firefox did 😄

Yes, Radix doesn't do anything around that, `ScrollArea` is a regular scrolling container with the ability to style the scrollbars. With that in mind, this isn't something we will be implementing.

**Comment by atomiks** [comment]
Yeah it's definitely not something Radix should do internally. I might try to write a new polyfill using the `scrollend` event that you can add in your projects separately.
