### ISSUE TITLE
ScrollArea event-based scrolling does not work with `scroll-behavior: smooth`

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#2064]
## Bug report

I'm setting `scroll-behavior: smooth` so that my custom `.scrollTo` calls are smoothly scrolled into view. However, it breaks the ScrollArea dragging and trackpad (`wheel` event) behavior.

### Current Behavior

https://user-images.githubusercontent.com/34928425/229560733-d6d9d109-c148-43ae-a793-38000fa6d270.mp4

### Expected behavior

https://user-images.githubusercontent.com/34928425/229560654-163cce91-3953-4db4-bf62-3f5e8c761691.mp4

### Reproducible example

https://codesandbox.io/p/sandbox/sparkling-waterfall-6pibz1

### Suggested solution

ScrollArea should manually set `viewport.style.scrollBehavior = 'auto'` when the scroll position (`.scrollTop` and `.scrollLeft`) is manually set from JS events.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | ScrollArea        |   1.0.3      |
| React            | n/a     |   18.2.0      |
| Browser          | Chrome, Brave, Safari        |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Fixed in #2175
