### ISSUE TITLE
Unable to use anchor element as Popover Trigger

### ISSUE THREAD

**Issue by SudoCat** [radix-ui/primitives#2068]
### Current Behavior

Currently, it is difficult to use an anchor element as the trigger for a Popover component.

If you use a Popover.Trigger element with the asChild prop enabled, and the children containing an anchor element, clicking the anchor will open the Popover, and trigger the link navigation to the href. Code example displays the setup in question.

```jsx
function ExamplePopover() {
  return (
    <Popover.Root>
      <Popover.Trigger asChild>
        <a href="https://google.com/">Open</a>
      </Popover.Trigger>
    </Popover.Root>
  )
}
```

Attempts to sidestep this problem, such as passing a callback function to the onClick prop on the anchor and calling preventDefault within it, successfully prevent the navigation, but also prevent the Popover content from displaying.

### Expected behavior

It should be simple to use an anchor as the trigger element for a popover. This is a common pattern which can be seen on many ecommerce websites. e.g. A menu link for the cart page, which opens a mini basket when clicked, or a link for the Account page, which opens a menulist when clicked. 

Both of these options provide sensible fallbacks for clients browsing with javascript disabled, or for multi-tasking users who wish to be able to open the links in a new tab, either by right clicking, using middle mouse or ctrl/cmd+click.

It should be possible for the developer to pass an onClick handler that calls `event.preventDefault()` without this disabling the Popover handler. It appears the code currently disables the handler if `event.defaultPrevented` is true - this seems confusing; preventing the default browser behaviour should not disable additional functionality; that is what `event.stopImmediatePropagation()` is for. Of course, stopPropagation/stopImmediatePropagation do not flag whether they've been called, so some additional handling would be required to use it.

### Reproducible example

[CodeSandbox Test Case](https://codesandbox.io/s/adoring-lucy-enzp4j?file=/src/App.tsx)

### Suggested solution

Sadly the previous decisions made leave few options exist that wouldn't risk breaking changes.
- Change composeEventHandlers to track stopPropagation instead (could break existing implementations)
- Always call preventDefault on popover trigger callback (likely has undesirable consequences)
- Expose an additional prop (safe but messies up the API)

Not sure of many better options at this point.

### Additional context

Currently evaluating different accessible react UI libraries on behalf of a client by building some of their common existing UI patterns in different libraries to test their limitations. Sadly, Radix fell at the first hurdle.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    popover     |     latest    |
| React            | n/a     |  18       |
| Browser          |  firefox       |      112   |
| Assistive tech   |         |         |
| Node             | n/a     |     18    |
| npm/yarn         | pnpm        |    7.27.1     |
| Operating System |   MacOS Monterey      |   12.4      |

**Comment by benoitgrelard** [comment]
Hi @SudoCat,

Whilst it's technically possible to use `asChild` to make the trigger a link, I don't think it is a sensible option.
What you are describing makes sense because a link takes you somewhere (navigates away), whereas a button executes an action and keeps you where you are. That is the reason `Popover.Trigger` default to a `button`.

> This is a common pattern which can be seen on many ecommerce websites. e.g. A menu link for the cart page, which opens a mini basket when clicked, or a link for the Account page, which opens a menulist when clicked.

The pattern being common isn't the same as saying it is "correct". Largely, these all result in bad UX.

> Both of these options provide sensible fallbacks for clients browsing with javascript disabled, or for multi-tasking users who wish to be able to open the links in a new tab, either by right clicking, using middle mouse or ctrl/cmd+click.

For the progressive enhancement story, you could have a link to the page, and then replace it with the popover (with a button trigger) when JS kicks in, that would be a better UX as the user would know what's about to happen (buttons look like buttons an links look like links). The multi-tasking thing is arguably also bad UX as mostly unexpected.

For all those reasons, I do not believe Radix should make this any easier as we don't want to support bad UX.
