### ISSUE TITLE
[Dropdown Menu] Render an auto-focused input when a menu-item is selected

### ISSUE THREAD

**Issue by jpqx** [radix-ui/primitives#2073]
## Bug report

I have an input element, people can toggle its visibility by a dropdown-menu item. When the input element is rendered, I would like it to get auto-focused.

### Current Behavior

When we click a menu item, the trigger element gets focused by default. If we prevent this default in `onCloseAutoFocus`, the trigger element doesn't get focused, but neither does the newly-rendered input element.

### Expected behavior

When we click a menu item, if the default is prevented in `onCloseAutoFocus`, the newly-rendered input element should get auto-focused (if it is rendered with the `autofocus` attribute).

### Reproducible example

https://stackblitz.com/edit/react-ts-s7tmkp?file=App.tsx

In this example, besides the dropdown-menu item (labeled "Toggle input from menu-item"), I also added an inline toggle button (labeled "Toggle input from inline button"), for comparison.

It works fine with the inline button, the input gets auto-focused. But with the dropdown-menu item, it doesn't.

### Suggested solution

Is there some logic in the RadixUI Dropdown Menu that says _"We unconditionally call `preventDefault` on the native event, and conditionally put focus on the trigger element - if not prevented in the `onCloseAutoFocus` callback."_?

If so, do you know of any downside of changing it to _"We conditionally `preventDefault` on the native event and put focus on the trigger element - if not prevented in the `onCloseAutoFocus` callback."_?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  [@radix-ui/react-dropdown-menu](https://www.npmjs.com/package/@radix-ui/react-dropdown-menu)  | 2.0.4 |
| React            |   | 18.2.0 |
| Browser 1         | Firefox | 111.0.1 |
| Browser 2         | Safari | 16.0 (17614.1.25.9.10, 17614) |
| Assistive tech   | n/a |         |
| Node             | n/a     |         |
| npm/yarn         | n/a |         |
| Operating System | macOS Monterey | 12.5.1 |

**Comment by joaom00** [comment]
You should call `onToggleInput` inside the `onCloseAutoFocus`. Since the focus is trapped on `DropdownMenu.Content` it's too early to move focus to the input if you call inside the `onSelect` callback.

https://stackblitz.com/edit/react-ts-yrp8yf?file=App.tsx

**Comment by jpqx** [comment]
Thank you, João, for your quick reply and explanation. I'll take your advice.
