### ISSUE TITLE
NavigationMenu.Link should not dismiss Content when clicked with metaKey held

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#2074]
### Current Behavior

Clicking a `NavigationMenu.Link` [automatically closes the root content](https://github.com/radix-ui/primitives/blob/1b05a8e35cf35f3020484979086d70aefbaf4095/packages/react/navigation-menu/src/NavigationMenu.tsx#L615-L622).

This is annoying when trying to open many links at once through the use of the `metaKey` (which opens the link in a new tab on all major browsers). You open one, the menu closes, you re-hover the trigger, click another, repeat. Ugh.

https://user-images.githubusercontent.com/34928425/231052016-557b0541-7b99-4388-b19d-62a627be6c81.mp4

### Expected behavior

Each link can be clicked without closing the root menu if the `metaKey` is held.

https://user-images.githubusercontent.com/34928425/231052360-b91f48c9-4233-4206-a62d-c73e62c93346.mp4

### Reproducible example

Here's an example with a hacky workaround I'm using to support holding `metaKey` when clicking links.

https://codesandbox.io/p/sandbox/silent-pond-bwvukv

### Suggested solution

Check for `event.metaKey` before firing this event:

https://github.com/radix-ui/primitives/blob/1b05a8e35cf35f3020484979086d70aefbaf4095/packages/react/navigation-menu/src/NavigationMenu.tsx#L615-L622

### Additional context

Would be great if the custom Radix events included some properties from the original event, like `.metaKey`, `.altKey`, `.currentTarget`, etc.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-navigation-menu       | latest        |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hey Paco!

I can see where you're coming from for sure, I think it makes sense and caveating for `event.metaKey` is easy enough.

> Would be great if the custom Radix events included some properties from the original event, like .metaKey, .altKey, .currentTarget, etc.

We have other places where we do this (`onPointerDownOutside` we relay the original event from the custom event on `event.detail.originalEvent`) maybe in the future we can try and standardise it.

For now I believe `onRootContentClose` isn't exposed anyway.

**Comment by multiwebinc** [comment]
The browser defaults for Firefox and Chrome on Linux is to open links in the same tab with Meta pressed, however a new tab if Ctrl is pressed.
