### ISSUE TITLE
$9g4ps$react.createContext is not a function

### ISSUE THREAD

**Issue by RobinRuf** [radix-ui/primitives#2076]
### Current Behavior

<img width="881" alt="Screenshot 2023-04-11 at 18 28 13" src="https://user-images.githubusercontent.com/39103327/231228530-9052e0f3-d582-4ab5-880f-090925e4a882.png">
<img width="933" alt="Screenshot 2023-04-11 at 18 28 22" src="https://user-images.githubusercontent.com/39103327/231228547-5fcb704e-da2a-4ba3-8751-9134998d1635.png">
<img width="363" alt="Screenshot 2023-04-11 at 18 40 32" src="https://user-images.githubusercontent.com/39103327/231230978-b79b729f-7af6-4e01-a2f9-cab365dbbf5e.png">

### Reproducible example

`npm install @radix-ui/react-tabs`

`tailwind.config.js like https://www.radix-ui.com/docs/primitives/components/tabs`

`index.jsx like https://www.radix-ui.com/docs/primitives/components/tabs - but in TypeScript-Project`

### Suggested solution

I am prety sure, that I did something wrong. But I cannot explain where and how - I found Radix-UI through an youtube video. The person there also used a TypeScript Project and also copy/pasted the start code to get a Form and the Tabs. Does someone got the same problem sometimes and can help me find out what is wrong?

### Your environment

I am using the latest Version of Next13.

**Comment by joaom00** [comment]
If you are using Next.js 13 with `app/` dir, you should use `use client` directive in the first line of the file

https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages

**Comment by RobinRuf** [comment]
> 

Wow, now that's really embarrassing that I made such a rookie mistake. Already used several times, but just forgot... Used Next12 for too long...

Well, thank you haha
