### ISSUE TITLE
Close (X) button to close popup

### ISSUE THREAD

**Issue by dwikurniawan91** [radix-ui/primitives#2077]
### Overview

Please add Close (X) button to close popup

**Comment by QzCurious** [comment]
If you mean [`Popover`](https://www.radix-ui.com/docs/primitives/components/popover), it does support [close](https://www.radix-ui.com/docs/primitives/components/popover#close) button.

And the example also implements it:

![image](https://user-images.githubusercontent.com/38932402/231689611-dc8a2a88-0234-4769-b2ab-561c4cb6e619.png)
