### ISSUE TITLE
React nodes passed as value in AccordionItemProps

### ISSUE THREAD

**Issue by snk-js** [radix-ui/primitives#2084]
Hi, I wanted to know if I am doing right: puting a component inside the 'string' value of a Accordion Item, like an adornment or badge within the accordion trigger buttons

![image](https://user-images.githubusercontent.com/34718184/232253091-b48fd604-f642-4fe3-87fe-3d59b66ab2b5.png)

```
 const accordionItems = [
    {
      value: AccordionItemWithAdorment('/learn/knight.png', 'Pieces'),
      content: <div>here goes pieces list tutorial components</div>,
      id: 'Pieces',
    },
    ...
   ]
```
AccordionItemWithAdorment: 
```
const AccordionItemWithAdorment = (path: string, title: string) => {
  return (
    <div className="flex items-center">
      <Image src={path} alt="knight piece" width={32} height={32} />
      <div className="mx-3">{title}</div>
    </div>
  );
};
```

but, this causes a type error, it requires a string in item value (because that string will act like a title to the Item, but also a unique value?)

there's no way of doing that already?

```
<Accordion.Root
      className="my-6 w-auto rounded-md bg-transparent lg:my-0"
      type="single"
      defaultValue={'empty'}
      collapsible
    >
      <div className="smooth-shadow">
        {accordionItems.map((item, index) => (
          <AccordionItem key={item.id} value={item.value}>
            <AccordionTrigger>{item.value}</AccordionTrigger>
            <AccordionContent>{item.content}</AccordionContent>
          </AccordionItem>
        ))}
      </div>
    </Accordion.Root>
```

value can only be a string here

https://github.com/radix-ui/primitives/blob/49996635ab5a57167dbf8a300fa13cd30cd4497c/packages/react/accordion/src/Accordion.tsx#L368

**Comment by joaom00** [comment]
> because that string will act like a title to the Item, but also a unique value?

Just as a unique value. Why would you want it to be a component?

**Comment by snk-js** [comment]
> > because that string will act like a title to the Item, but also a unique value?
> 
> Just as a unique value. Why would you want it to be a component?

Why not? But the question initially asked is there an easier or best practices way of doing it?
the only way I can attach some component within the Item is through the value? Why value couldn't be a component too and separated it's responsibility of being an `id` ?

**Comment by joaom00** [comment]
> But the question initially asked is there an easier or best practices way of doing it?

Similar to what you are doing but the `value` prop needs to be a single value to know which content to render. You can render whatever you want inside the `Trigger` part.
