### ISSUE TITLE
Select demo code typo

### ISSUE THREAD

**Issue by jamesjlyons** [radix-ui/primitives#2090]
### Relevant Radix Component(s)

Select

### Problem found

In the demo code for the Select component, the items are wrapped in `<SelectItem>` instead of `<Select.Item>`.

**Comment by joaom00** [comment]
Hey @jamesjlyons, it's not a typo. `SelectItem` is a wrapper of some parts which is just below in the example :grin:

**Comment by jamesjlyons** [comment]
Ah, my bad! Missed the component below 🤦‍♂️
