### ISSUE TITLE
Dialog Primitive: Invalid hook call. Cannot read properties of null (useRef)

### ISSUE THREAD

**Issue by sipkoepp** [radix-ui/primitives#2091]
### Current Behavior
When importing the Dialog.Root Primitive anywhere inside the React App, I'm getting the following errors:

<img width="924" alt="error" src="https://user-images.githubusercontent.com/98806318/232980847-2caea4bf-43b3-4a8d-a589-0d9042b21afb.png">

### Expected behavior

No runtime error.

### Reproducible example

Freshly generated Vite (React) + TypeScript project using:
`
"react": "^18.2.0",
"react-dom": "^18.2.0",
`

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | x    |         | 18.2.0
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |     npm    |         |
| Operating System |         |         |

**Comment by ZelCloud** [comment]
How did you fix this?
