### ISSUE TITLE
data-state conflicts

### ISSUE THREAD

**Issue by jamiebuilds** [radix-ui/primitives#2096]
### Overview

It would be great if the data props added by Radix were unique across all primitives so that conflicts like this didn't exist:

```tsx
<ContextMenu.Trigger asChild>
  <Tabs.Trigger/> {/* Both Trigger's try to add data-state */}
</ContextMenu.Trigger>
```

Example: https://codesandbox.io/s/ecstatic-grass-dppjq7?file=/src/App.tsx

### Examples in other libraries

Yeah probably

### Who does this impact? Who is this for?

![Me](https://user-images.githubusercontent.com/113370520/233533584-284c2bd6-1853-4055-a0ce-777b6e9d0e1a.gif)

### Additional context

Love ya

**Comment by andy-hook** [comment]
Totally, though this is being tracked via https://github.com/radix-ui/primitives/issues/602 so will close in favour.
