### ISSUE TITLE
Property 'sideOffset' does not exist on type 'IntrinsicAttributes & ContextMenuContentProps & RefAttributes<HTMLDivElement>'

### ISSUE THREAD

**Issue by LupuC** [radix-ui/primitives#2099]
## Question

I'm using ContextMenu with typescript, and I get this error on using sideOffset={5} on ContextMenu.Content

```
Type '{ children: Element[]; className: string; sideOffset: number; align: string; }' is not assignable to type 'IntrinsicAttributes & ContextMenuContentProps & RefAttributes<HTMLDivElement>'.
  Property 'sideOffset' does not exist on type 'IntrinsicAttributes & ContextMenuContentProps & RefAttributes<HTMLDivElement>'.ts(2322)
```
  
  I'm kinda new to typescript too, but I can't find a solution...

**Comment by benoitgrelard** [comment]
That is correct, `ContextMenu.Content` doesn't support `sideOffset` as it will always show next to where your cursor was.

**Comment by mjfwebb** [comment]
@benoitgrelard The example code in the documentation on https://www.radix-ui.com/docs/primitives/components/context-menu has `sideOffset` being used with `ContextMenu.Content`

**Comment by LupuC** [comment]
Forgot to check this topic again 😅. Yeah, I just copied the code from docs, and with js worked fine, but with ts i got that error. I just deleted it because "sideOffset isn't supported".. kinda weird
