### ISSUE TITLE
[NavigationMenu] - reducing `--radix-navigation-menu-viewport-width` when opened

### ISSUE THREAD

**Issue by alexcarpenter** [radix-ui/primitives#2107]
### Current Behavior

When using the `--radix-navigation-menu-viewport-width` CSS variable, the content width is reducing when visible.

https://user-images.githubusercontent.com/825855/234072867-b2cadfe8-a01a-4ab9-a3fe-f684876eab1b.mp4

### Expected behavior

The content width does not change when hovering an item.

### Reproducible example

[CodeSanbox](https://codesandbox.io/s/practical-shape-rcl63p?file=/src/navigation-menu.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-navigation-menu        | latest        |
| React            | n/a     | latest        |
| Browser          |         |          |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by roniaxe** [comment]
I had that issue, after removing `absolute` and `w-auto` from NavigationMenuContent component. check if you have those css properties set.

**Comment by benoitgrelard** [comment]
Hi @alexcarpenter, this looks like an issue with your CSS.
Please refer to the working Tailwind example here: https://www.radix-ui.com/docs/primitives/components/navigation-menu
