### ISSUE TITLE
undefined --radix-collapsible-content-height on first render

### ISSUE THREAD

**Issue by hgodinho** [radix-ui/primitives#2109]
### Current Behavior

the css var `--radix-collapsible-content-height` is not defined on first render
![image](https://user-images.githubusercontent.com/4079201/234109901-c1670e48-7c5c-4b53-88f5-8a950c202a9e.png)

it only appers after click the trigger
![image](https://user-images.githubusercontent.com/4079201/234110065-d26f55b4-673d-4774-b576-e4e372bfa271.png)

### Expected behavior

since width is defined I believe height should also be defined on first render

### Suggested solution

add height to first render

### Additional context

Im getting the css property value from a created ref to pass the same height to a overlay image that will respond to collapsible height

first render closed:
![image](https://user-images.githubusercontent.com/4079201/234110633-c2e4715b-1265-49f9-8f5c-f462816ca765.png)

first render open:
![image](https://user-images.githubusercontent.com/4079201/234110723-2dcfa320-f297-4b75-94e7-3b940eccd973.png)

second render open:
![image](https://user-images.githubusercontent.com/4079201/234110796-fe72d27b-c8aa-43b2-9725-0e287adc9758.png)

I'm using stitches to style:

```typescript
export const header__image_overlay: CSS = {
    position: 'relative',
    height: 500,
    overflow: 'hidden',

    variants: {
        state: {
            open: {
                height: 'calc(var(--radix-collapsible-content-height) + 500px)',
            },
            closed: {
                // top: 0,
            },
        }
    }
}
```

and getting the css property from menuBody ref:

```typescript
    const menuBodyHeight = menuBody?.current?.style.getPropertyValue(
        '--radix-collapsible-content-height',
    );
    const menuBodyWidth = menuBody?.current?.style.getPropertyValue(
        '--radix-collapsible-content-width',
    );
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-collapsible  |  ^1.0.1       |
| React            | n/a     |  ^18.2.0       |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
The dimensions (especially height) can only be calculated once you've opened it because the content isn't there when closed so I think that's expected.
