### ISSUE TITLE
Ability for Select to accessibly contain non-selectable, action-triggering items within its popover

### ISSUE THREAD

**Issue by kiastorm** [radix-ui/primitives#2120]
### Overview

Sometimes, I want to have a mixture of options and buttons in the `SelectContent`. The most common usecase for this I've seen is "Select an X or create an X"

Below is an example in GitLab - "Select a recent search (option) or clear recent searches (button?)"

![image](https://user-images.githubusercontent.com/63059016/235357149-59a5e687-21c7-408c-83b6-5618819fd29c.png)

(I've got to go, but I'll return and add more context here if needed)

**Comment by benoitgrelard** [comment]
Hey @kiastorm I don't think this is a select, as you are not really selecting a value it seems, that example looks more like a dropdown menu.

Or if it was in the context of a selectable list, it would probably be a combobox pattern instead as you have noticed already.
I will close this issue as #1342 is a better place for the suggestion (as you did).

**Comment by kiastorm** [comment]
@benoitgrelard 

I understand that the example in the screenshot is not great. 

I suppose a better example would be something like

```
<Select>
  <SelectTrigger>
    <SelectValue placeholder="Select a project" />
  </SelectTrigger>
  <SelectContent>
    <SelectItem value="project-1">Project 1</SelectItem>
    <SelectItem value="project-2">Project 1</SelectItem>
    <SelectNonSelectableItem onClick={onCreateAProject}>Create a project</SelectNonSelectableItem>
  </SelectContent>
</Select>
```

Say I'm filling out a form to create a database - I give it a name and other properties, one of those properties being the "project" it should belong to. The user might be brand new, and a project has not been created yet. Or maybe an existing user just wants to create a new project to attach it to.

Perhaps at that point, yeah, it is a ComboBox - just wanted to give a better example.
