### ISSUE TITLE
Popover - invalid value for --radix-popper-available-width

### ISSUE THREAD

**Issue by Powerplex** [radix-ui/primitives#2128]
### Current Behavior

Hey :) 

I am trying to create a design system Popover using radix Popover primitives.
We were trying to use `collisionBoundary` to force the Popover to stay in a given container. 

From what I understand, Radix is using [Floating UI](https://floating-ui.com/) to get the positionning data, and set them in css custom properties that we should use to apply the styles.

**For some reason `--radix-popper-available-height` calculation is correct, but `--radix-popper-available-width:-495px; ` it not.**. For it we have huge negative values (ex: `-495px`).

![Capture d’écran 2023-05-05 à 14 40 30](https://user-images.githubusercontent.com/2033710/236460744-fee00710-2e98-4b77-b84b-83b06145c3fa.png)

### Expected behavior

I need the popover to stay in its `collisionBoundary` element.

![Capture d’écran 2023-05-05 à 14 45 33](https://user-images.githubusercontent.com/2033710/236461050-f3b0349a-3d6e-48fc-9463-64c07ba4d650.png)

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/react-tailwind-starter-forked-3uyqqv?file=/src/PopoverDemo.js:602-619)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-popover    |     1.0.5    |
| React            | n/a     |    18.2.0     |
| Browser          |   Chrome      |    112.0.5615.137     |

**Comment by lesha1201** [comment]
Should be fixed in https://github.com/radix-ui/primitives/pull/2032

**Comment by Powerplex** [comment]
@lesha1201 I was using `"@radix-ui/react-popover": "^1.0.5"` when I experienced the bug and I see no new version have been published yet. Do you know when it will be released ? :)

**Comment by benoitgrelard** [comment]
There is a new version with the fix, but it's a release candidate: https://www.npmjs.com/package/@radix-ui/react-popover/v/1.0.6-rc.13

I don't have a date yet, but we'll run a public release soon.

**Comment by Powerplex** [comment]
Thanks @benoitgrelard I can confirm that the RC fixes our issue ✅ 

<img width="1111" alt="Capture d’écran 2023-05-22 à 16 40 00" src="https://github.com/radix-ui/primitives/assets/2033710/059641f2-ef76-406b-a924-2dc5d90de450">

We started deploying our design system: [Spark](https://sparkui.vercel.app/?path=/docs/getting-started--docs) (open source). It's combining Radix with TailwindCSS mainly. Radix is SUPER helpful and help us a lot to push for accessibility in our project, which is great.

When we grow more mature I hope we can eventually contribute on Radix issues.
