### ISSUE TITLE
[DropdownMenu] DropdownMenu.Arrow will missing when set maxHeight for DropdownMenu.Content

### ISSUE THREAD

**Issue by laozhu** [radix-ui/primitives#2129]
### Current Behavior

For DropdownMenu component, when I set `maxHeight: 600px` and `overflowY: auto` for content together, the Arrow will be hidden

### Expected behavior

I want to set a fixed height for dropdown menu, and working together with Arrow.

**Comment by benoitgrelard** [comment]
Hey @laozhu,

If you want to keep the arrow visible, you can hide an extra element (I called it viewport) to contain the scroll.
Here's a demo I made by updating the example from the docs:

https://codesandbox.io/p/sandbox/dropdownmenu-constrain-height-and-keep-arrow-visible-6bign4?file=%2Fstyles.css%3A1%2C1

The only changes I made are:
- added a `<div className="DropdownMenuViewport">` under each `Dropdown.Content`, `Dropdown.SubContent`
- added this CSS to `.DropdownMenuContent, .DropdownMenuSubContent`:
  ```css
    display: flex;
    flex-direction: column;
    max-height: var(--radix-dropdown-menu-content-available-height);
  ```

- added this CSS for the new `.DropdownMenuViewport`:
  ```css
    .DropdownMenuViewport {
      overflow: auto;
      flex: 1;
    }
  ```

Admittedly we should bring in new parts to handle a little bit of this automatically like we do with `Select`. This will probably be handled as part of #657 to bring a bit more parity there.

**Comment by laozhu** [comment]
@benoitgrelard Your solution is very helpful and solved my issue, thanks very much 👍
