### ISSUE TITLE
[Dialog] Asynchronously rendered DialogClose causes high CPU usage in Google Chrome

### ISSUE THREAD

**Issue by dzucconi** [radix-ui/primitives#2149]
### Current Behavior

This is admittedly a bit of an odd one. If you're using a dialog, and hide and show it in a controlled manner, and you use any kind of button that's been rendered asynchronously to close it (this includes links that might change a route to close it), CPU usage will hit 100% and stay there until the dialog is completely removed from the component tree. Stranger still: this doesn't appear to occur in Safari or Firefox, only Google Chrome.

Here's a video demonstrating the problem. Closing the dialog using anything that's been rendered synchronously is fine (so clicking on the overlay or clicking the 'Save Changes' button). But I've set a close button to render after a second and once that is clicked, CPU usage creeps up to 100% and stays there until the page is refreshed.

https://github.com/radix-ui/primitives/assets/112297/f3d3c4fd-c815-4a3a-93bd-78db47c0b657

### Reproducible example

[Reproduction in Codesandbox](https://codesandbox.io/s/strange-glade-pxc51q)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `@radix-ui/react-dialog`    |        1.0.3 |
| React            | n/a     |  18.2.0       |
| Browser          |   Chrome      | 113.0.5672.126        |
| Operating System |      macOS Monterey   |      12.6.5   |

**Comment by joaom00** [comment]
Probably related to https://github.com/radix-ui/primitives/issues/1605. Can you test whether `1.0.4-rc.4` fixes the issue?

**Comment by dzucconi** [comment]
Ah, yep that does indeed fix the issue. Thanks @joaom00 (and @benoitgrelard)!

**Comment by dzucconi** [comment]
However: the release candidate does cause a regression with Select inheriting `pointer-events: none` and preventing `data-highlighted` from working.

**Comment by joaom00** [comment]
Try update `Select` to `1.2.2-rc.8`

**Comment by dzucconi** [comment]
@joaom00 unfortunately still an issue.

Here's a repro: https://codesandbox.io/s/friendly-sutherland-xx2q1f

(Happy to file this as a separate issue)

**Comment by joaom00** [comment]
Ohh sorry,

You need to update to `1.2.2-rc.12` :sweat_smile:. It's an old issue https://github.com/radix-ui/primitives/issues/1088

https://codesandbox.io/s/nostalgic-bhaskara-qym4it

**Comment by dzucconi** [comment]
Thank you!
