### ISSUE TITLE
"Maximum update depth exceeded" error when using Popover component

### ISSUE THREAD

**Issue by rodgobbi** [radix-ui/primitives#2152]
### Current Behavior

In the application I'm working on, there's a specific action that always trigger a infinite loop of updates in a component that uses the `Popover` component, the error shown is:  
<img width="985" alt="image" src="https://github.com/radix-ui/primitives/assets/3410227/d27e6a31-261d-43ca-baea-213592625529"> 
Inspecting the `FocusScope` in the stack trace, it shows exactly this line of code:  
https://github.com/radix-ui/primitives/blob/c7d458ce05ea88a5ae31721e12f3cd64b59a932f/packages/react/focus-scope/src/FocusScope.tsx#LL62C84-L62C84

I think this line may be causing the issue and I elaborate more in the sections below.

### Expected behavior

The component renders without any errors.

### Reproducible example

I'm not able to provide a repro because the repo I work on is private and the bug is caused in a very specific step of the application, but in the `Suggested solution` below I give a one line change that might fix the issue.

### Suggested solution

In the line found here:  
https://github.com/radix-ui/primitives/blob/c7d458ce05ea88a5ae31721e12f3cd64b59a932f/packages/react/focus-scope/src/FocusScope.tsx#LL62C84-L62C84   
We have the following code:   
`const composedRefs = useComposedRefs(forwardedRef, (node) => setContainer(node));`  
I think the fix is simple and we should rewrite it as:   
`const composedRefs = useComposedRefs(forwardedRef, setContainer);`  
`setContainer` always has the same reference and we prevent the `FocusScope` component from entering an infinite loop of setting the reference to `null` then `node`, because with the current implementation, a new function reference is created on every render and passed to `useComposedRefs`.  
[This section of the React docs](https://legacy.reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs) explains why the line I mentioned may be causing the issue I'm facing.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-popover      |    1.0.0     |
| React            | n/a     |    18.0.21     |
| Browser          |    Chrome     |     113.0.5672.126    |
| Node             | n/a     |    v16.16.0     |
| npm/yarn         |         |         |
| Operating System |   MacOS Monterey      |  12.5       |

**Comment by benoitgrelard** [comment]
Hi @rodgobbi,

Have you verified that the suggestion does indeed fix your issue?

I would still like to see a repro if possible because off the bat it's unclear to me what you are highlighting would cause an infinite loop, seeing as this is the first time this issue is reported even though this component is heavily used in many of our most used primitives.

**Comment by rodgobbi** [comment]
Hi @benoitgrelard,

My bad, the `Radix` component doesn't have any issue actually, I changed the source code of the `FocusScope` in my local repo with the suggestion I made and the issue still continued happening.  I should have verifying this better before opening the issue, sorry about that.  

The issue looks like is coming from [Downshift](https://github.com/downshift-js/downshift), which I use together with the `Popover` from `Radix` to implement a custom Combobox.

There's a lot of composing of refs that works most of the time but on a very specific scenario it causes this infinite loop of updates, I'd say that having the same reference for the `ref` callbacks is safer overall, but right it doesn't look like the source of the issue.

I'll close this issue, thanks for the very quick support!

**Comment by equal-matt** [comment]
@rodgobbi I have the same specific set of things that's causing me the same issue... Can you save me any time understanding what's happening here and what the fix is? 🤞

**Comment by resthedev** [comment]
> @rodgobbi I have the same specific set of things that's causing me the same issue... Can you save me any time understanding what's happening here and what the fix is? 🤞

I am having this issue on pages where I am needing to render many of the hover cards (50+). 
It especially happens when I switch between rendering skeleton components to rendering the actual component (with the hover card inside) after my queries have completed (using react-query).

Any ideas on how to fix?

**Comment by rodgobbi** [comment]
@equal-matt so sorry I didn't see the notification for the message.
For anyone having this issue in the future like @resthedev :
The context for my use case was:
I had a logic that would pass a reference callback to the trigger element of the combobox to get the width of element and save to a React state, for the same trigger element I used `downshift` and the Radix `Popover` together to be their "trigger" respectively.
Both lib would pass their own `ref` prop and compose with other existing `ref` prop that the trigger element/component received.
I made sure to wrap the reference callback with a `useCallback` to keep the reference the same across different renders.
But internally the logic of the callback was causing the issue, it was always setting the React state to the width value, even if it was the same value stored in the React state.
In theory this shouldn't be an issue because the state was being set to the same value and React would bail out the re-render of the component.
But this was actually causing the infinite loop.
I suspected that the reference composition I mentioned above was causing the infinite loop, I didn't dive deep into details but the re-render that was supposed to be bailed out was resulting in a real render due to the internal logic of `downshift`, which then would call the reference callback and start again, in a infinite loop.

I'd recommend as a general approach to prevent as much as you possible to trigger the render flow of the React component, even though in theory it would be bailed out.
For my use case, I added a `ref` object to store the current width value that was stored also in the React state, just to compare with the value I'd receive in the reference callback and only ever calling the "setState" if the value actually changed.

**Comment by resthedev** [comment]
> @equal-matt so sorry I didn't see the notification for the message.
> 
> For anyone having this issue in the future like @resthedev :
> 
> The context for my use case was:
> 
> I had a logic that would pass a reference callback to the trigger element of the combobox to get the width of element and save to a React state, for the same trigger element I used `downshift` and the Radix `Popover` together to be their "trigger" respectively.
> 
> Both lib would pass their own `ref` prop and compose with other existing `ref` prop that the trigger element/component received.
> 
> I made sure to wrap the reference callback with a `useCallback` to keep the reference the same across different renders.
> 
> But internally the logic of the callback was causing the issue, it was always setting the React state to the width value, even if it was the same value stored in the React state.
> 
> In theory this shouldn't be an issue because the state was being set to the same value and React would bail out the re-render of the component.
> 
> But this was actually causing the infinite loop.
> 
> I suspected that the reference composition I mentioned above was causing the infinite loop, I didn't dive deep into details but the re-render that was supposed to be bailed out was resulting in a real render due to the internal logic of `downshift`, which then would call the reference callback and start again, in a infinite loop.
> 
> 
> 
> I'd recommend as a general approach to prevent as much as you possible to trigger the render flow of the React component, even though in theory it would be bailed out.
> 
> For my use case, I added a `ref` object to store the current width value that was stored also in the React state, just to compare with the value I'd receive in the reference callback and only ever calling the "setState" if the value actually changed.

Thanks for taking the time to share more context about your case. I ended up making a new issue with a reproducible example here: https://github.com/radix-ui/primitives/issues/2717

I'm not handling any complexities with refs as you are but I'm getting the issue when rerendering a large number of hover cards occurs. Hopefully will get a reply from the team.
