### ISSUE TITLE
Radix-ui React component fails to hydrate in astro SSG

### ISSUE THREAD

**Issue by Oudwins** [radix-ui/primitives#2164]
### Current Behavior

When using astro with a react component with radix ui primitive inside it

If you specify client:load (this allows for hydration) -> website works perfectly in development mode but fails to build for SSG
If you specify client:only (this disables hydration & makes component only render in browser)-> everything works
### Expected behavior

If you specify client:load -> build does not fail. Page is hydrated as normal

### Reproducible example
Check the index.astro file in the stackblitz
https://stackblitz.com/edit/withastro-astro-7ufrrz?file=src%2Fpages%2Findex.astro

### Suggested solution
?

### Additional context

I have no idea why this works like it does.
I am not sure if this is a problem with radix-ui or astro so I apologize if this issue should be placed else where :(
Might be related to this? https://github.com/radix-ui/primitives/issues/1386

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-accordion      |      "^1.1.1   |
| React            | n/a     |    ^18.0.0     |
| Assistive tech   |         |         |
| Node             | n/a     |   v19.9.0      |
| pnpm         |         |         |
| Operating System |    linux     |         |

**Comment by benoitgrelard** [comment]
Hi @Oudwins, that doesn't sound like a Radix issue, so that's probably an issue with your astro setup. I would suggest to open an issue there.

**Comment by Oudwins** [comment]
@benoitgrelard To be clear, this is 100% Radix-ui issue. The components error out when being pregenerated on the server side to allow for hydration.

As per -> https://github.com/radix-ui/primitives/issues/1386
