### ISSUE TITLE
Bug: Miss-aligned positioning of Select portal content for RTL direction

### ISSUE THREAD

**Issue by JiriPavlik** [radix-ui/primitives#2172]
### Current Behavior

Content of select portal has wrong translation calculation when using --radix-select-trigger-width property for set width of Select.Content for RTL direction.

![image](https://github.com/radix-ui/primitives/assets/30430133/9c7ba8e6-4204-46eb-b1fb-e15f7b5c0826)

### Expected behavior

Should be same as for LTR direction

![image](https://github.com/radix-ui/primitives/assets/30430133/8ad10b4a-1dd8-4a4e-8f10-90740d7d5b03)

### Reproducible example 
Sadly i cant provide full example, i tried to setup core of issue with pseudo elements

<Select.Portal>
   <Select.Content
            className={`w-[--radix-select-trigger-width]>
              <Select.Item>
                ....
         </Select.Content>
        </Select.Portal>

### Additional info

Is there any other way how to use full with of trigger without using that custom property? Seem that initial transform: translate3d of content wrapper is calculated without content width and then is  miss-aligned by this value.

<div
  data-radix-popper-content-wrapper=""
  dir="rtl"
  style="
    position: fixed;
    left: 0px;
    top: 0px;
    transform: translate3d(336px, 258px, 0px);
    min-width: max-content;
    z-index: auto;
    --radix-popper-anchor-width: 191.98863220214844px;
    --radix-popper-anchor-height: 17.8125px;
    --radix-popper-available-width: 429.8295440673828px;
    --radix-popper-available-height: 602.8266754150391px;
    --radix-popper-transform-origin: 0% 0px;
  "
>

### Your environment
radix package
Google Chrome - Version 113.0.5672.92 (Official Build) (x86_64)
npm v9.5.1
Node v18.16.0
macOS Monterey 12.6.3

**Comment by benoitgrelard** [comment]
Hi @JiriPavlik,

This has been fixed in the latest release. Try upgrading to the latest version. 🙏
