### ISSUE TITLE
non-submit buttons triggering form validation

### ISSUE THREAD

**Issue by brettinternet** [radix-ui/primitives#2179]
### Current Behavior

Non-submit buttons inside `Form.Root` trigger form validation messages.

### Expected behavior

Buttons not wrapped in `Form.Submit` should not trigger the form validation.

### Reproducible example

https://codesandbox.io/s/radix-form-validation-button-issue-d4s7np

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-form     |   0.0.2      |

**Comment by joaom00** [comment]
I think this is how HTML works

https://codesandbox.io/s/radix-form-validation-button-issue-forked-e263tp?file=/src/App.tsx

**Comment by benoitgrelard** [comment]
Yep, that's correct, in HTML a `button` without an explicit `type="button"` will be promoted to a `type="submit"`, that's in the spec.

![CleanShot 2023-06-01 at 18 35 17@2x](https://github.com/radix-ui/primitives/assets/1539897/5041fed6-1a8b-469c-949c-e470ab6fecf1)

Source: https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type

**Comment by brettinternet** [comment]
My apologies, thank you for the correction.
