### ISSUE TITLE
Popover still visible outside of parent element while scrolling

### ISSUE THREAD

**Issue by donsn** [radix-ui/primitives#2184]
## Bug report
The popover stays in place and is still visible even when the page scrolls past the parent element
### Current Behavior

https://github.com/radix-ui/primitives/assets/31552644/f5e840bf-c59e-4f71-9227-62f269e3aee3

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-popover    |   ^1.0.6      |
| React            | n/a     |   18.2.0      |
| Browser          |      Chrome   |      113.0.5672.126   |
| Assistive tech   |         |         |
| Node             | n/a     |     20    |
| npm/yarn         |    yarn     |      3.4.1   |
| Operating System |      macOS   |     13.4    |

**Comment by joaom00** [comment]
You can use `hideWhenDetached` prop to achieve that behavior

**Comment by benoitgrelard** [comment]
That's expected because it is portalled in this demo so is always above.
You could not portal it, or could use `hideWhenDetached` in combination with `collisionPadding` if you don't want that behaviour.

However, you have just made me realise that we don't pass in the `detectOverflowOptions` to the `hide` modifier, so there's a bug currently preventing from doing that.

I will fix that now!

**Comment by benoitgrelard** [comment]
Here's how it would work/look:

<img width="833" alt="CleanShot 2023-06-02 at 16 42 30@2x" src="https://github.com/radix-ui/primitives/assets/1539897/3237dac4-f9d9-4071-8746-fd6d7f24eef0">

https://github.com/radix-ui/primitives/assets/1539897/9c44cf6e-d9d0-40af-aa4f-84bbaf4eab2d

**Comment by benoitgrelard** [comment]
#2185

**Comment by atomiks** [comment]
Here's a PR for a future feature to incorporate "obstacles" into Floating UI - elements that the floating element shares its top layer with: https://github.com/floating-ui/floating-ui/pull/2348

While `padding` in `detectOverflowOptions` solves the fixed navbar problem, the above feature in theory adds collision detection to avoid other elements anywhere on the page, not just the surrounding boundary. Another use case is when multiple floating elements are open simultaneously and should avoid each other. I'm still kind of working out how useful this feature is though

**Comment by benoitgrelard** [comment]
That's interesting!
