### ISSUE TITLE
Popover - arrow disappears when overflow: auto

### ISSUE THREAD

**Issue by RabbitShare** [radix-ui/primitives#2189]
### Current Behavior

<img width="590" alt="image" src="https://github.com/radix-ui/primitives/assets/49274725/b9f9dc73-a647-46b8-a67d-14b781c18199">

### Expected behavior

When i set  `overflow: "auto"` the arrow **doesn't** disappears

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/nice-dubinsky-oowrs6?file=/src/App.js:597-616)

**Comment by benoitgrelard** [comment]
Yes, that's because the arrow lives inside the `Content` part. To mitigate this, add your own wrapper inside `Content` and set the overflow on this instead.
