### ISSUE TITLE
Cannot import * as Select or * as DropdownMenu

### ISSUE THREAD

**Issue by jmtimko5** [radix-ui/primitives#2192]
## Bug report
I cannot use the react-select component. It fails to compile the import from the documentation. We use other radix components in our app, so I do suspect we are setup for imports correct.

### Current Behavior
```
import * as Select from "@radix-ui/react-select";
import * as DropdownMenu from "@radix-ui/dropdown-menu";

```
Results in the following error
```
error - ./node_modules/@radix-ui/react-select/dist/index.mjs
Can't import the named export 'Anchor' from non EcmaScript module (only default export is available)
```

### Expected behavior

I'd expect this to work, other `* as XYZ` radix imports worked just fine in our when we were on dropdown version 2.0.1 and select version 1.1.1.
 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-select / @radix-ui/dropdown-menu  |  1.2.2 / 2.0.5  |
| React            | n/a     | 17.0.4        |
| Node             | n/a     |  14.18.1  |
| npm/yarn         |  yarn  |  1.22.4 |
| Operating System |    macOS Monterey   |   12.2.1   |

**Comment by nathanielrindlaub** [comment]
I just started experiencing this as well when attempting to import and use the '@radix-ui/react-scroll-area' primitive for the first time: 

```
import * as ScrollArea from '@radix-ui/react-scroll-area';
```

produces the following error: 

```
./node_modules/@radix-ui/react-scroll-area/node_modules/@radix-ui/react-slot/dist/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

I also use other Radix primitives import in the same way throughout the app and they don't seem to be causing issues.

**Comment by benoitgrelard** [comment]
This looks like your setup isn't configured correctly for esm.
Newer setups usually work out of the box but older versions of webpack for example aren't setup quite right.

We had that issue with our own docs.

This is what all it takes in general: https://github.com/radix-ui/website/pull/641/commits/a7bbd13093072f7c56b60765b1790f82a720e4a4

> **Note**: This is for an older version of Next where they let you update the webpack config. I imagine similar is possible with other frameworks.

**Comment by jmtimko5** [comment]
This worked @benoitgrelard thanks so much for the guidance!

**Comment by Siihyun** [comment]
This same  when attempting to import and use "@radix-ui/react-switch" package.

![image](https://github.com/radix-ui/primitives/assets/44644821/c2c9f21a-f800-4e01-af2d-8a1681245c3e)

Is there any workaround for this? Now I'm using just React. Not With NextJs

**Comment by craigpryde** [comment]
Hey Folks, I managed to fix this for plain react with extending my Craco config. 

I added a webpack rule into `craco.config.js`, Here's a condensed version with only the change i made:

```
module.exports = {
  webpack: {
    configure: {
      module: {
        rules: [
          {
            test: /\.mjs/,
            include: /node_modules/,
            type: 'javascript/auto',
          },
        ],
      },
    },
  },
};
```

I found the answer i was looking for with this thread: https://github.com/dilanx/craco/issues/429 and it worked for this issue too. Credit to a combo of the above craco issue and the solution provided above by @benoitgrelard 😄 

Hopefully this helps someone.

**Comment by ThabisoMagwaza** [comment]
I had the same issue with the dialog component. I resolved it by upgrading to v5 of `react-scripts`

**Comment by cxrod** [comment]
> Hey Folks, I managed to fix this for plain react with extending my Craco config.
> 
> I added a webpack rule into `craco.config.js`, Here's a condensed version with only the change i made:
> 
> ```
> module.exports = {
>   webpack: {
>     configure: {
>       module: {
>         rules: [
>           {
>             test: /\.mjs/,
>             include: /node_modules/,
>             type: 'javascript/auto',
>           },
>         ],
>       },
>     },
>   },
> };
> ```
> 
> I found the answer i was looking for with this thread: [dilanx/craco#429](https://github.com/dilanx/craco/issues/429) and it worked for this issue too. Credit to a combo of the above craco issue and the solution provided above by @benoitgrelard 😄
> 
> Hopefully this helps someone.

The project I working on throw a million errors after the react-script update to v5. I quick solution was add craco and add this config.
