### ISSUE TITLE
Select Content is misaligned when using popper to position

### ISSUE THREAD

**Issue by stdavis** [radix-ui/primitives#2194]
### Current Behavior

I'm struggling to make the content align with the trigger.

<img width="131" alt="image" src="https://github.com/radix-ui/primitives/assets/1326248/90743dd6-20f6-40f1-8972-fab81748300b">

### Expected behavior

I expected that the content/dropdown would be left-justified with the trigger/button and that the width would be precisely the same.

### Reproducible example

https://codesandbox.io/s/radix-select-alignment-issue-forked-4wk7cp?file=/src/App.js

### Suggested solution

I feel like it is related to the react-remove-scroll package setting CSS props on the body of the document but not positive. I can work around it to a degree by applying margin and padding to the body like this:
https://codesandbox.io/s/radix-select-alignment-issue-workaround-jggdgc?file=/public/index.html

But that's not ideal because it doesn't work if I set the padding to 0. Having padding on the body is a pain for a single-page app.

### Additional context

Thanks for the awesome library!

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-select    |    1.2.2     |
| React            | n/a     |    18.2.0     |
| Browser          |   Chrome      |     114.0.5735.106    |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   macOS      |    13.4     |

**Comment by joaom00** [comment]
There are some small problems in your example. 

1. The `Viewport` doesn't have a `box-sizing: border-box`, making the placement calculation wrong.
2. As the content is close to the edges, the `Select` comes with a `collisiondPadding` of 10 by default, making it not touch the edges. If you move the trigger to the middle of the screen the `collisionPadding` is not applied.

https://codesandbox.io/s/radix-select-alignment-issue-forked-6dfgs5?file=/src/App.js

**Comment by stdavis** [comment]
@joaom00 Thank you SO much for the quick response! Your tips solved my issue.
