### ISSUE TITLE
iOS: Slider not responding unless tooltip is triggered first

### ISSUE THREAD

**Issue by riccardolardi** [radix-ui/primitives#2196]
### Current Behavior

On my app www.dekarechner.ch I am experiencing a somewhat strange behaviour on iOS using the slider primitive: they do not respond to user action unless a tooltip is triggered first (little "i" buttons).

### Expected behavior

Should react from the beginning.

### Reproducible example

www.dekarechner.ch

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Slider        | latest        |
| React            | yes     | latest        |
| Browser          | iOS Safari        | latest         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | iOS         | latest         |

**Comment by benoitgrelard** [comment]
Hi @riccardolardi,

The issue you describe seems highly specific to your app, so I'd think it's unlikely to be an issue with Radix but rather with the specific setup.

In any case, it's literally impossible for us to do anything about it without a simple reproduction.

I will close the issue, but feel free to re-open if you can reproduce this issue in a simplified codesandbox.
