### ISSUE TITLE
Open a modal `Popover` from inside a modal `DropdownMenu`

### ISSUE THREAD

**Issue by ciampo** [radix-ui/primitives#2209]
## Bug report

I'm trying to open `Popover` when clicking a `DropdownMenu.Item`. Both the `DropdownMenu`and the `Popover` should be `modal`.

### Current Behavior

I haven't been able to achieve the desired behaviour:

- not sure about the order in which the different React components should be nested
- Pointer/Keyboard focus behaviour doesn't seem to be working as expected:
  - by default, clicking on the popover contents triggers the dropdownmenu to close, which also closes the popover
  - adding `onSelect` with `preventDefault()` on the menu item seems to fix the above, but then I'm unable to open the popover using the keyboard (pressing enter/spacebar on the popover trigger doesn't open the popover)
  - additionally, focus doesn't seem to be moved correctly to the popover when it's opened, and pressing tab doesn't cycle through the focusable elements inside the popover.

### Expected behavior

- Dropdown menu can be interacted with with as usual, including its modal features (focus trap, disabled pointer events on the rest of the page, etc)
- I should be able to specify a `DropdownMenu.Item` also as a `Popover.Trigger`
- Clicking or pressing enter/space on the item causes the popover to open
- Focus is moved and trapped to the popover correctly
- Closing the popover (including pressing ESC) closes the popover, but leaves the dropdown open
- 

### Reproducible example

https://codesandbox.io/p/sandbox/vigilant-leaf-55gmxj

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | `@radix-ui/react-dropdown-menu`, `@radix-ui/react-popover` |  2.0.5, 1.0.6       |
| React            | n/a     |  18.2.0        |
| Browser          | Chrome        |    114     |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
@ciampo these are `DropdownMenu` + `Dialog` composition examples, but it's the same for `DropdownMenu` + `Popover`: https://codesandbox.io/s/dropdownmenu-dialog-items-r9sq1q
