### ISSUE TITLE
[Dropdown] Dropdown menu in modal immediately closes

### ISSUE THREAD

**Issue by kieranm** [radix-ui/primitives#2215]
## Bug report
I have a `<Dialog>` open. In the body of the dialog there is a button acting as a trigger for a `<DropdownMenu>`. Clicking this button causes the dropdown menu to open and then immediately close again, so the dropdown menu never actually appears. This behaviour only started happening with 2.0.5, downgrading to 2.0.4 fixes the problem and it works again as expected.

### Current Behavior
The dropdown menu opens and immediately closes, so the button appears to be unresponsive.

https://github.com/radix-ui/primitives/assets/232283/c520c154-2a67-4af4-9dba-11b3087b85e8

### Expected behavior

The dropdown menu should open normally, like in 2.0.4, and the behaviour should be the same regardless of whether or not the trigger is in the body of a dialog. See video for 2.0.4 behaviour.

https://github.com/radix-ui/primitives/assets/232283/23885e53-93ec-4139-aacb-89ac6148ec9b

### Reproducible example

Unhelpfully, I wasn't able to reproduce this bug myself even using a similar component structure and all the same package versions, so I'm really at a loss. You can see it working as intended here:

https://codesandbox.io/s/strange-dawn-ln86wr

I would appreciate any guidance on what changed between these versions to help me debug this further.

### Suggested solution

Downgrading the version of `@radix-ui/react-dropdown-menu` to 2.0.4 works.

### Additional context
I am using `<Portal>`s for both the dialog and dropdown menu.
Removing the `<Portal>` from the `<DropdownMenu/>` will cause this to work again, suggesting this is some sort of focus trap or portaling problem.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    `@radix-ui/react-dropdown-menu`     |   2.0.5      |
| Radix Package(s) |    `@radix-ui/react-dialog`     |   1.0.4      |
| Radix Package(s) |    `@radix-ui/react-portal`     |  1.0.3      |
| React            | n/a     |     18.2.0    |
| Browser          |    Chrome     |         |
| Assistive tech   |    N/A     |         |
| Node             | n/a     |   18      |
| npm/yarn         |    pnpm     |     8.6.2    |
| Operating System |    MacOS     |    Ventura 13.4     |

**Comment by kieranm** [comment]
Closing this issue while I investigate further, because I now can't even get this to work on 2.0.4 🤦

**Comment by alexandreespejo** [comment]
Some update on this bug ? im having the same problem

**Comment by alexandreespejo** [comment]
> Closing this issue while I investigate further, because I now can't even get this to work on 2.0.4 🤦

Some update on this bug ? im having the same problem

**Comment by kieranm** [comment]
I was able to resolve this by making sure the versions of all three packages were on latest. Also make sure the actual correct versions are being installed by the package manager in the lockfile.
