### ISSUE TITLE
[Regression] Select component trigs Popover closing inside Popover 

### ISSUE THREAD

**Issue by aboveyunhai** [radix-ui/primitives#2224]
### Current Behavior
For version `2.0.0-rc.5+` (I didn't check other rc version below `2.0.0-rc.5`), When we have a `Select` inside `Popover`, if we open the select and then click outside without making a selection, both Select and Popover close 

### Expected behavior
For lastest version 1.2.2, the unselect behavior only closes the `Select`, `Popover` stays open.

### Reproducible example

[CodeSandbox with 2.0.0-rc.7](https://codesandbox.io/p/sandbox/bold-joana-pd5srf?file=%2Fpackage.json%3A1%2C2)

### Your environment

Radix Package

    "@radix-ui/react-popover": "latest",
    "@radix-ui/react-select": "^2.0.0-rc.7",

**Comment by joaom00** [comment]
Upgrade `Popover` to `v1.0.7-rc.5` and should work fine

**Comment by aboveyunhai** [comment]
> Upgrade `Popover` to `v1.0.7-rc.5` and should work fine

The issue still persist in `next.js`.
I install fresh next.js `typescript` and `tailwindcss` from their official command line. And then install the following and copy paste the exact `PopoverDemo`(basically the `app.tsx` file) from my stackblitz code above.

```
"@radix-ui/react-popover": "1.0.7-rc.5",
"@radix-ui/react-select": "2.0.0-rc.7",
```


https://github.com/radix-ui/primitives/assets/35160613/97e702fc-0b87-4521-86f5-21e084338e4d

**Comment by joaom00** [comment]
it's working here

Make sure you have one version only of `DismissableLayer` installed. Probably you are hitting #1088 


https://github.com/radix-ui/primitives/assets/48808846/27e12aef-5847-4680-be8c-b7a7d0a4ee82

**Comment by aboveyunhai** [comment]
@joaom00 , thx for your suggestion,  I check there is only one version of `DismissableLayer`, and I'm using page directory instead of app directory based on your video, I tried out the linked issue solution but none of them appears to be working.
For the sake of experiment, I create a new repo with the problematic code so you can check it out.
https://github.com/aboveyunhai/radix-popover-test

**Comment by joaom00** [comment]
Yeah, there are two versions of `DismissableLayer` in your `package-lock.json`. I deleted the `node_modules` and `package-lock.json` and installed again. It's working fine now

**Comment by aboveyunhai** [comment]
@joaom00  thx for your help, can confirm it has something to do with the minimal version of `dismissable-layer`, previously I was using the incompatible version.
since delete `node_modules` is not a direct approach for remote hosting.
At least for the version I was listing above, using the `overrides` is probably the way to go.
```ts
 "overrides": {
		"@radix-ui/react-dismissable-layer": "1.0.4"
	}
```

**Comment by yhaggai** [comment]
I've updated '@radix-ui/react-select' to 2.1.2 and it solved the issue.
Not overrides were needed.
