### ISSUE TITLE
[New Primitive] Button Group

### ISSUE THREAD

**Issue by Zyr0nX** [radix-ui/primitives#2225]
### Overview

A <ButtonGroup /> component that allow user to click 1 button in a group

### Examples in other libraries

[MUI - Button Group](https://mui.com/material-ui/react-button-group/)

### Who does this impact? Who is this for?

All user

**Comment by greenskybluephish** [comment]
This is already implemented. https://www.radix-ui.com/docs/primitives/components/toggle-group

**Comment by psai-terwin** [comment]
not really...that's a toggle group, not a button group

**Comment by Morriz** [comment]
@ddwalias why was this closed? explain plz

**Comment by Morriz** [comment]
and @greenskybluephish can you provide a working example showing this? I am quite sure that the UX for button group and toggle is not the same...
