### ISSUE TITLE
Unnecessary rerenders in @radix-ui/react-dialog

### ISSUE THREAD

**Issue by call007** [radix-ui/primitives#2229]
### Current Behavior

This is all about the Dialog component. I am unsure if this is a bug, but when I wrap `Dialog.Content` into a new React Component and use it as a child of `Dialog.Portal` it shows unnecessary rerenders (two when the modal is opening, and three when closing). Nevertheless, if use the usual structure: all Dialog primitives in one component – it works fine (without unnecessary rerenders).

### Expected behavior

I expect that when the modal is opening, only one render appears. And for the closing state the same behavior.

### Reproducible example

[CodeSandbox Demo](https://codesandbox.io/p/sandbox/hopeful-hoover-ltht45?file=%2FApp.jsx%3A9%2C39) (check the console)

### Suggested solution

No idea how to fix it.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |    1.0.4     |
| React            | n/a     |    18.2.0     |
| Browser          |   Chrome   |     114.0.5735.133 arm64    |
| Assistive tech   |         |         |
| Node             |  n/a    |    ^18     |
| npm/yarn         |    yarn     |    ^3     |
| Operating System |    macOS     |    Ventura 13.4.1     |

**Comment by hafijAsadMVN** [comment]
![image](https://github.com/radix-ui/primitives/assets/140306963/34a3f86c-6c65-47f6-b7f9-b0399162dda7)
Same issue, how to fix? Same dialog rendering twice at a time.

**Comment by call007** [comment]
> ![image](https://private-user-images.githubusercontent.com/140306963/294848685-34a3f86c-6c65-47f6-b7f9-b0399162dda7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDc3MjEsIm5iZiI6MTcwNDcwNzQyMSwicGF0aCI6Ii8xNDAzMDY5NjMvMjk0ODQ4Njg1LTM0YTNmODZjLTZjNjUtNDdmNi1iN2Y5LWIwMzk5MTYyZGRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwOTUwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODc1OThmNDkzYzIxOGMwNTE1ODU0NTNjMDBmYWU5NDEzNmZlODk1ZTQ3NzllNjJhOThlN2VlZjBjYzU3NzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0hA0DLRFQ39748aZzFE1BVScjzT181RvVttUqDw0mwg) Same issue, how to fix? Same dialog rendering twice at a time.

This thread is not about the same problem as you have :)
I didn't mean the DOM mutations. I meant the React re renders...

**Comment by benoitgrelard** [comment]
> I am unsure if this is a bug

You are right, that isn't a bug, the number of renders will depend based on a few things, parts used, animations, etc. This is an implementation detail and nothing to worry about unless you are having performance issues.
