### ISSUE TITLE
[Popover] dynamically update popover position depending on Trigger/Anchor position

### ISSUE THREAD

**Issue by nik-webdevelop** [radix-ui/primitives#2237]
## Is there a way to dynamically update popover position depending on `Trigger/Anchor` position.

As of right now, after popover gets opened, it won't change its position on page, despite `Toggle/Anchor` position changes (for example in result of `position: absolute` properties change)

[codesandbox](https://codesandbox.io/p/sandbox/bold-feather-rznj6z?file=%2FApp.jsx%3A13%2C30)

**Comment by joaom00** [comment]
You can update the Popover to the latest RC where a new tag `updatePositionStrategy` is added and you can use the value as `always`. [Check this thread](https://github.com/radix-ui/primitives/pull/2092) for more info.

https://codesandbox.io/p/sandbox/pedantic-vaughan-zd43f6?file=%2FApp.jsx%3A33%2C1-33%2C44

**Comment by nik-webdevelop** [comment]
@joaom00 thanks a lot, works like a charm )

**Comment by atomiks** [comment]
You don't need to use that option anymore if you re-install Radix packages to latest - except in very rare cases with animations or when it relocates with transforms. The default now handles handles trigger/anchor movements.

**Comment by kyrylolvov** [comment]
Is there still a way to implement behaviour when popover doesn't change it's position depending on anchor position?

**Comment by fergy-os** [comment]
Is there a way to keep the original behavior where the popover floats while the trigger moves to a different position?

**Comment by carlosbensant** [comment]
We need a way to disable this behavior easily.
