### ISSUE TITLE
[Dropdown Menu] - Add a way to differenciate onCloseAutoFocus event generated by keyboard or mouse

### ISSUE THREAD

**Issue by FilipePfluck** [radix-ui/primitives#2238]
Hi guys. I'm trying to make a dropdown menu, and something is bottering me. When I close the dropdown in anyway, it focus the trigger. And yes, I know this is intended behaviour. However, even if I close it via mouse, it still focus the trigger. I think this should only happen when closing it via keyboard. The reason is because it displays the focus indicator, and I don't want to display it when clicking with the mouse. And it is displayed even using focus-visible.

I'm checking the docs and it seems that the DropdownMenu.Content receives a prop onCloseAutoFocus 
(https://www.radix-ui.com/docs/primitives/components/dropdown-menu)

I'm logging this event and it seems it doesn't have any way to distinguish events generated by keyboard or mouse. 
![Screenshot from 2023-06-30 11-34-32](https://github.com/radix-ui/primitives/assets/62773200/a5cff728-5904-4bf7-bc79-d151f936accd)
Maybe it's possible to add some prop to this event? 
 
Thanks for your amazing work!

**Comment by FilipePfluck** [comment]
It's worth mentioning that the Dialog trigger has a behaviour similar to this. It only gives focus to the trigger when closed by keyboard. Maybe you can take a look at it and replicate a similar behaviour on the dropdown, select, and other components

**Comment by FilipePfluck** [comment]
Just in case someone stops here and is having the same issue, this is the workaround I did to quick fix it:

Add this on your _app.tsx or layout.tsx:
`
useEffect(() => {
    document.body.classList.add('using-mouse');
    document.body.addEventListener('mousedown', function () {
      document.body.classList.add('using-mouse');
    });

    const keys = [
      'Tab', 
      'ArrowDown', 
      'ArrowUp', 
      'ArrowLeft', 
      'ArrowRight', 
      'Space', 
      'Enter', 
      'Escape'
    ]

    const onKeyDown = (e: KeyboardEvent) => {
      if (keys.includes(e.key)) {
        document.body.classList.remove('using-mouse');
      }
    };

    // Re-enable focus styling when a key is pressed
    document.body.addEventListener('keydown', onKeyDown);
    return () => {
      document.body.removeEventListener('keydown', onKeyDown);
      document.body.removeEventListener('mousedown', function () {
        document.body.classList.add('using-mouse');
      })
    };
  }, []);
`
this useEffect will add a className 'using-mouse' to the body whenever the user clicks with the mouse, and remove it whenever it presses tab, space, enter, arrows, or esc. 

Then you can style like this:
`
'&:focus-visible': {
            outline: 'none',
          },
          'body:not(.using-mouse) &': {
            '&:focus-visible': {
              outlineWidth: value,
              outlineStyle: 'solid',
              outlineColor: 'token(colors.blue.500)',
            },
          },
`
I'm using pandacss to style, but you can adapt this to whatever styling solution you're using. 

I don't think this issue should be closed, tho. This is probably something that needs to be properly addressed

**Comment by QingyuChai** [comment]
Hi @FilipePfluck, I'm interested in the same feature addition, but it looks like this issue is gonna go stale. Any chance you can recreate this issue, using the issue templates?
https://github.com/radix-ui/primitives/tree/main/.github/ISSUE_TEMPLATE

If not, I can give that a try and open a new issue, referencing your current issue.

**Comment by benoitgrelard** [comment]
We wouldn't be able to tell in `onCloseAutoFocus` because the component at this point has no idea what produced the focus. You can check the event in `onInteractOutside` which will be one of these:

```tsx
type PointerDownOutsideEvent = CustomEvent<{ originalEvent: PointerEvent }>;
type FocusOutsideEvent = CustomEvent<{ originalEvent: FocusEvent }>;
```

You even have access to the original underlying event in case you need to check specific targets.

Note that this is something we already automate based on modality (`modal` prop), when non modal, and you click outside to discard, we won't auto focus the trigger and will let natural focus happen as expected.
