### ISSUE TITLE
A unique attribute for each type of element (makes styling easy)

### ISSUE THREAD

**Issue by piscopancer** [radix-ui/primitives#2239]
### Overview
I do not like this at all
```jsx
<Dialog.Content className="GlobalDialog">...</Dialog.Content>
```
Currently, popovers, dialogs and tooltips (maybe smth else) are not different from each other when their appear as html.
Trying to address a `Tooltip` like so will also affect a popover (what a nice surprise 😐)
```css
[data-radix-popper-content-wrapper] > * {
  @apply py-1 px-2 rounded-lg bg-slate-800 text-white text-sm;
  @include smoothAppear();
}
```
What I want you to do is to give **every** component in your docs (popover, dialog, radio buttons, tooltip etc) a specific attribute, so that they appear in the html inspector as such:
#### <Dialog.Content>...</Dialog.Content>
```jsx
<div dialog-content data-side="bottom" data-state="open">...</div>
```
#### <Popover.Content>...</Popover.Content>
```html
<div popover-content data-side="bottom" data-state="open">...</div>
```
### Benefits
* Easier global styling, no chance to make a class typo.
```css
[tooltip-content] {
  ...
}
[popover-content] {
  ...
}
```
* Better distinction in the html inspector (still divs, but quickly recognized by attributes)

### Who does this impact? Who is this for?

This addition will be a **time saver** for those who want to style these elements globally by referencing their attributes and stop specifying their classes (as you do it on the docs) every time they add a component.

please guys 🥺

**Comment by benoitgrelard** [comment]
This is something we used to have but backtracked on because we didn't want to encourage styling as we saw lots of people have issues with CSS. I don't believe we will change this back unfortunately.
