### ISSUE TITLE
Tooltip won't trigger when it contains a Popover

### ISSUE THREAD

**Issue by painty** [radix-ui/primitives#2243]
### Current Behavior

If a Popover is inside a Tooltip, the tooltip will not trigger after the popover open and close(by Popover.Close), untill a second hover.

Steps:
1. Make the Popover inside a Tooltip
2. click on the trigger to open the Popover
3. close the Popover by clicking the "x" button
4. hover on the trigger, but no tooltip, until mouse leave and mouse enter the trigger.

### Expected behavior

After the Popover close, the first time hover on the trigger, a tooltip should be shown.

### Reproducible example

https://codesandbox.io/s/friendly-dijkstra-2ymfmh?file=/src/App.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-tooltip        |   1.0.6      |
| Radix Package(s) | @radix-ui/react-popover        |   1.0.6      |
| React            | n/a     |   17.0.1      |
| Browser          |  chrome       |   114.0.5735.198      |
| Operating System |   Macos      |    13.4.1     |

**Comment by joaom00** [comment]
the correct way to compose the two primitives https://codesandbox.io/s/happy-voice-tnd3yl?file=/src/App.tsx
