### ISSUE TITLE
[Menubar] Open Content on Hover instead of On-Click

### ISSUE THREAD

**Issue by mbaldas** [radix-ui/primitives#2244]
## Question

Hello everyone,
I'm currently building a "topbar" menu using the [`Menubar`](https://www.npmjs.com/package/@radix-ui/react-menubar) component.

## Behavior

I have all the menu items and I need to **click** in one of them to open the content box for the first time and then on the other interactions they all can be opened by hovering.

## Expected Behavior

I have all the menu items and they don't need to be clicked to open on the first time, all of them can be opened direclty through a hover action

_Is there any way of doing this? By default having the menubar to be opened hovering instead of clicking?_

Appreciate any sort of help,
Thank you :)

**Comment by troymcginnis** [comment]
@mbaldas What did you end up using as a solution for this?
