### ISSUE TITLE
Tabs: mobile support

### ISSUE THREAD

**Issue by monolithed** [radix-ui/primitives#2249]
### Overview

It's a great idea that your components can be downloaded separately, but they are not optimized for mobile platforms and do not support theming through design tokens. 
I tried adding more tabs than in your example, and they didn't collapse into a dropdown menu or scroll if they didn't fit within the screen width.

### Examples in other libraries

I don't understand Ant's philosophy and their attitude towards users, but at least their tabs are adaptive.

http://ant.design/components/tabs/

**Comment by joaom00** [comment]
> I tried adding more tabs than in your example, and they didn't collapse into a dropdown menu or scroll if they didn't fit within the screen width.

as radix is unstyled this decision is completely up to you
