### ISSUE TITLE
Make `disableOutsidePointerEvents` Configurable for Select Component

### ISSUE THREAD

**Issue by Khongchai** [radix-ui/primitives#2260]
### Overview

Inside the `Select` component, you have this

<img width="1016" alt="image" src="https://github.com/radix-ui/primitives/assets/56601823/ed486211-3e90-4a1e-bb44-5b627ef00bbb">

https://github.com/radix-ui/primitives/blob/eca6babd188df465f64f23f3584738b85dba610e/packages/react/select/src/Select.tsx#L699C19-L699C19

Rather than forcing it to true all the time, might it be possible to make this optional? For example, in my case, I would like to display the select component alongside other components in my storybook. The `pointerEvent: none` implicitly called by the `Dismissable` component means I have to hack up a solution with more  javascript.

The `Select` component already has an `open` property. I can then use that with the `disableOutsidePointerEvents` set to false to get the desired result.

### Examples in other libraries

This WCAG example does not block other stuff on the same page. Clicking on the background, naturally, dismisses it, but you can hover (not exactly my case, but just an example of a select component that does not block background interaction 100%)

https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/

### Who does this impact? Who is this for?

For people who are using your primitives as a foundation for their internal component libraries. In my case, I need to display all internal components in storybook. Would be nice to be able to have it open all the time without blocking other interactions.

Thanks!

**Comment by joaom00** [comment]
This will probably be addressed by #2253 by allowing non modal mode but it will only be for the `popper` position. However, non modal mode can also be added to the `item-aligned` position but most likely the Select will be closed when scrolling.

**Comment by Khongchai** [comment]
@joaom00  Great! Then I'll close this issue for now. Thank you.
