### ISSUE TITLE
[Tabs] Orientation prop does not change the orientation

### ISSUE THREAD

**Issue by Kyzegs** [radix-ui/primitives#2261]
## Bug report

The orientation prop (vertical) does not do anything.

### Expected behavior

Expected the tabs to be vertical.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/vibrant-lake-j6rrw8?file=%2FApp.jsx%3A5%2C1-14%2C15)

**Comment by joaom00** [comment]
The orientation prop does nothing visually. It modifies the navigation behavior i.e. horizontally: arrow left and arrow right, vertically: arrow up and arrow down

**Comment by Kyzegs** [comment]
Got it, thank you.
