### ISSUE TITLE
OnClick is not trigger when using asChild props with DropdownMenu.Trigger

### ISSUE THREAD

**Issue by ladislasdellinger** [radix-ui/primitives#2267]
### Current Behavior

When using the DropdownMenu.Trigger with the `asChild` props, the `onClick` handler of my child doesn't seems to be triggered.

### Expected behavior

The `onClick` should also be triggered.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/muddy-platform-3hr9gn)

### Suggested solution

?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    react-dropdown-menu     |   2.0.5      |
| React            | n/a     |     17.0.2    |
| Browser          |  Chrome       |   Version 114.0.5735.198 (Official Build) (arm64)      |
| Assistive tech   |         |         |
| Node             | n/a     |    v16.14.0     |
| npm/yarn         |    yarn     |     1.22.19    |
| Operating System |    macOS     |     Ventura    |

**Comment by joaom00** [comment]
It's because of the default modal mode which adds `pointer-events: none` in the body and prevents the click event from happening

**Comment by ladislasdellinger** [comment]
Okay found it ! This is the modal mode on the dropdown.

However, I don't understand why it prevents the click event from happening even if the DropdownMenu is not opened.

**Comment by ladislasdellinger** [comment]
> Oh sorry for not specifying 😄

No worries at all, I'm just getting started with this library, so there's a whole new world for me to explore 😅

> The dropdown opens in onPointerDown so when you release the mouse pointer the pointer-events: none will already be in the body

Ah, I see! That makes perfect sense now. I'll proceed with the modal mode disabled then.

Thank you so much for you prompt answer 😀
