### ISSUE TITLE
Select is not keyboard navigable inside a dialog

### ISSUE THREAD

**Issue by equal-matt** [radix-ui/primitives#2275]
### Current Behavior
Steps:
* Nest a select inside a dialog.
* Open the dialog.
* Open the select.
* Use keyboard interactions.

You'll find that focus isn't trapped inside the select viewport, so all interactions affect the dialog, rather than the select.

### Expected behavior

Focus is trapped inside the select and keyboard navigation works.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/goofy-monad-zk6cls?file=/src/App.tsx)

### Your environment

Packages
[@radix-ui/react-accessible-icon](https://codesandbox.io/examples/package/@radix-ui/react-accessible-icon)
latest (1.0.3)
[@radix-ui/react-accordion](https://codesandbox.io/examples/package/@radix-ui/react-accordion)
latest (1.1.2)
[@radix-ui/react-alert-dialog](https://codesandbox.io/examples/package/@radix-ui/react-alert-dialog)
latest (1.0.4)
[@radix-ui/react-announce](https://codesandbox.io/examples/package/@radix-ui/react-announce)
latest (0.1.8)
[@radix-ui/react-arrow](https://codesandbox.io/examples/package/@radix-ui/react-arrow)
0.0.1
[@radix-ui/react-aspect-ratio](https://codesandbox.io/examples/package/@radix-ui/react-aspect-ratio)
latest (1.0.3)
[@radix-ui/react-avatar](https://codesandbox.io/examples/package/@radix-ui/react-avatar)
latest (1.0.3)
[@radix-ui/react-collapsible](https://codesandbox.io/examples/package/@radix-ui/react-collapsible)
latest (1.0.3)
[@radix-ui/react-context-menu](https://codesandbox.io/examples/package/@radix-ui/react-context-menu)
latest (2.1.4)
[@radix-ui/react-dialog](https://codesandbox.io/examples/package/@radix-ui/react-dialog)
latest (1.0.4)
[@radix-ui/react-dropdown-menu](https://codesandbox.io/examples/package/@radix-ui/react-dropdown-menu)
latest (2.0.5)
[@radix-ui/react-label](https://codesandbox.io/examples/package/@radix-ui/react-label)
latest (2.0.2)
[@radix-ui/react-popover](https://codesandbox.io/examples/package/@radix-ui/react-popover)
latest (1.0.6)
[@radix-ui/react-portal](https://codesandbox.io/examples/package/@radix-ui/react-portal)
latest (1.0.3)
[@radix-ui/react-progress](https://codesandbox.io/examples/package/@radix-ui/react-progress)
latest (1.0.3)
[@radix-ui/react-radio-group](https://codesandbox.io/examples/package/@radix-ui/react-radio-group)
latest (1.1.3)
[@radix-ui/react-scroll-area](https://codesandbox.io/examples/package/@radix-ui/react-scroll-area)
latest (1.0.4)
[@radix-ui/react-select](https://codesandbox.io/examples/package/@radix-ui/react-select)
1.2.1
[@radix-ui/react-separator](https://codesandbox.io/examples/package/@radix-ui/react-separator)
latest (1.0.3)
[@radix-ui/react-slider](https://codesandbox.io/examples/package/@radix-ui/react-slider)
latest (1.1.2)
[@radix-ui/react-switch](https://codesandbox.io/examples/package/@radix-ui/react-switch)
latest (1.0.3)
[@radix-ui/react-tabs](https://codesandbox.io/examples/package/@radix-ui/react-tabs)
latest (1.0.4)
[@radix-ui/react-toggle-button](https://codesandbox.io/examples/package/@radix-ui/react-toggle-button)
latest (0.0.6)
[@radix-ui/react-tooltip](https://codesandbox.io/examples/package/@radix-ui/react-tooltip)
latest (1.0.6)
[@radix-ui/react-visually-hidden](https://codesandbox.io/examples/package/@radix-ui/react-visually-hidden)
latest (1.0.3)
[react](https://codesandbox.io/examples/package/react)
17.0.1
[react-dom](https://codesandbox.io/examples/package/react-dom)
17.0.1
[react-scripts](https://codesandbox.io/examples/package/react-scripts)
3.3.0

**Comment by cetchebarne** [comment]
I'm seeing the same issue using the Select inside the NavigationMenu as well. Works with Tab, but not using arrow navigation.

**Comment by joaom00** [comment]
You are hitting https://github.com/radix-ui/primitives/issues/1088. Upgrade `Select` to latest version should fix

**Comment by equal-matt** [comment]
> You are hitting #1088. Upgrade `Select` to latest version should fix

Tried in the CodeSandbox and it worked. Thanks @joaom00 👍

**Comment by equal-matt** [comment]
Actually, this reproduction doesn't match my local environment and that's what I'm trying to fix here really... Would appreciate some tips on resolving!

## Packages
"@radix-ui/react-accordion": "^1.1.2",
"@radix-ui/react-alert-dialog": "^1.0.4",
"@radix-ui/react-avatar": "^1.0.3",
"@radix-ui/react-checkbox": "^1.0.4",
"@radix-ui/react-collapsible": "^1.0.3",
"@radix-ui/react-dialog": "^1.0.4",
"@radix-ui/react-dropdown-menu": "^2.0.5",
"@radix-ui/react-label": "^2.0.2",
"@radix-ui/react-navigation-menu": "^1.1.3",
"@radix-ui/react-popover": "^1.0.6",
"@radix-ui/react-radio-group": "^1.1.3",
"@radix-ui/react-select": "^1.2.2",
"@radix-ui/react-slider": "^1.1.2",
"@radix-ui/react-slot": "^1.0.2",
"@radix-ui/react-switch": "^1.0.3",
"@radix-ui/react-tabs": "^1.0.4",
"@radix-ui/react-toggle-group": "^1.0.4",

Here's what I get from trying to understand any dismissable layer compat issues, as you linked (I checked this before raising this issue).
```
➜  next-ui git:(main) npm why @radix-ui/react-dismissable-layer
@radix-ui/react-dismissable-layer@1.0.4
node_modules/@radix-ui/react-dismissable-layer
  @radix-ui/react-dismissable-layer@"1.0.4" from @radix-ui/react-dialog@1.0.4
  node_modules/@radix-ui/react-dialog
    @radix-ui/react-dialog@"^1.0.4" from the root project
    @radix-ui/react-dialog@"1.0.4" from @radix-ui/react-alert-dialog@1.0.4
    node_modules/@radix-ui/react-alert-dialog
      @radix-ui/react-alert-dialog@"^1.0.4" from the root project
  @radix-ui/react-dismissable-layer@"1.0.4" from @radix-ui/react-menu@2.0.5
  node_modules/@radix-ui/react-menu
    @radix-ui/react-menu@"2.0.5" from @radix-ui/react-dropdown-menu@2.0.5
    node_modules/@radix-ui/react-dropdown-menu
      @radix-ui/react-dropdown-menu@"^2.0.5" from the root project
  @radix-ui/react-dismissable-layer@"1.0.4" from @radix-ui/react-navigation-menu@1.1.3
  node_modules/@radix-ui/react-navigation-menu
    @radix-ui/react-navigation-menu@"^1.1.3" from the root project
  @radix-ui/react-dismissable-layer@"1.0.4" from @radix-ui/react-popover@1.0.6
  node_modules/@radix-ui/react-popover
    @radix-ui/react-popover@"^1.0.6" from the root project
  @radix-ui/react-dismissable-layer@"1.0.4" from @radix-ui/react-select@1.2.2
  node_modules/@radix-ui/react-select
    @radix-ui/react-select@"^1.2.2" from the root project
```

All of that suggests to me that it should be fixed locally, but that's not what I'm seeing - is there anything else I can do to investigate?
