### ISSUE TITLE
Tooltip and HoverCard Content won't show on Mobile Device

### ISSUE THREAD

**Issue by gidgudgod** [radix-ui/primitives#2278]
### Current Behavior
On desktop everything goes fine, but when I change the screen to mobile and try to touch the Trigger, the Content won't show.
Instead it throws this ``error`` in console: ``react-dom.development.js:27791 Unable to preventDefault inside passive event listener invocation.`` But this console error only comes up when I touch each of my component which is a Tooltip inside a HoverCard. Error won't show on Tooltip/HoverCard only component, but still the main problem is that the Content won't show on mobile device.

### Expected behavior
Tooltip/HoverCard Content shows up when I touch its Trigger on Mobile Device.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-tooltip, @radix-ui/react-hover-card    |    ^1.0.6     |
| React            | n/a     |    18.2.0     |
| Browser          |     Chrome    |    114.0.5735.199     |
| Assistive tech   |         |         |
| Node             | n/a     |    18.16.1     |
| npm/yarn         |    pnpm     |    8.6.3     |
| Operating System |    Windows     |     11    |

**Comment by joaom00** [comment]
Hi @gidgudgod, this is by design https://github.com/radix-ui/primitives/issues/955#issuecomment-960610209. The same can be applied to `HoverCard`

**Comment by gidgudgod** [comment]
so whats the alternative if I still want to show the Content of the Tooltip/HoverCard on mobile device? using Popover?

**Comment by joaom00** [comment]
Yeah, it's an option
