### ISSUE TITLE
Alert Dialog blurring content inside of it.

### ISSUE THREAD

**Issue by Cafezinho** [radix-ui/primitives#2284]
### Current Behavior

When I use AlertDialog, my components inside my modal sometimes has a blurred appearence. It is a very weird behaviour because certain css properties trigger this blur. I have checked border-radius, background color in a options list and translate-x and translate-y.

### Expected behavior

Components inside my AlertDialog modal should not be blurred unless told to or applied any css class to blur appearence.

### Reproducible example

Still very difficult to reproduce, as it is inside a complex project. Will share some printscreens. Would love some ideias on how to fix it.

### Additional context

When I remove some css properties used inside my modal, the blur appearence disappears.

Bugged behavior:
![image](https://github.com/radix-ui/primitives/assets/16946896/542afd60-eef5-497c-82e3-ddc84d90ab00)

![image](https://github.com/radix-ui/primitives/assets/16946896/0cf2867a-34a7-4ee9-a474-d2fb82ee3d07)

Applying border-radius 0:
![image](https://github.com/radix-ui/primitives/assets/16946896/a8705de7-2a7f-454f-a31b-aace651af5ea)

Applying translate-x and translate-y 0
![image](https://github.com/radix-ui/primitives/assets/16946896/7d78de35-abd9-46bc-8ddd-4a66027ce923)

Applying background color transparent to ul:
![image](https://github.com/radix-ui/primitives/assets/16946896/e649e229-cd04-4dc1-9e0c-95219c141760)

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |     1.0.2    |
| React            |  |  v18        |
| Browser          |   Edge      |         |
| Assistive tech   |         |         |
| Node             |       |    16.18   |
| npm/yarn         |         |     x   |
| Operating System |   Windows WSL      |         |

**Comment by caiodutra08** [comment]
Not only transform can cause this bug, but other than `overflow` and many other css properties.

**Comment by hqw567** [comment]
I have the same problem, especially on Windows devices with 1920 (low) resolution screens

**Comment by benoitgrelard** [comment]
This can definitely happen on low resolution screens when sub-pixels are involved.
This isn't really anything to do with the primitive as it comes unstyled.
The solution provided by @atulmy is one way to get around it.
