### ISSUE TITLE
Endless rerendering when Checkbox is used with react-select multi select

### ISSUE THREAD

**Issue by bzhu-yara** [radix-ui/primitives#2291]
### Current Behavior

https://github.com/radix-ui/primitives/assets/117262402/70d652d7-17b5-4b5b-8911-fa20633befcf

White screen is shown because of endless rerendering

### Expected behavior

Should not trigger endless rerendering

### Reproducible example

https://codesandbox.io/p/sandbox/thirsty-hill-2rl4qx?file=%2Fpackage.json%3A16%2C23

### Suggested solution

The issue is because that the BubbleInput inside the Checkbox dispatches a click event whenever the `checked` prop changes. 

Event sequence is:

1. user clicks an option
2. option is now selected
3. `checked` prop of Checkbox updates to true
4. BubbleInput dispatches a click event and bubbles up
5. option is now unselected
6. `checked` prop of Checkbox updates to false
7. goes to 4

Suggestion would be: Bubble input inside the Checkbox only dispatches click event when user really clicks on the checkbox or the label.

### Current workaround

Wrap the checkbox with a div

```
<div onClick={ev => ev.stopPropagation()} style={{pointerEvents: 'none'}} >
 <Checkbox checked={isSelected} />
</div>
```

### Your environment

see code sandbox

**Comment by benoitgrelard** [comment]
You shouldn't use a checkbox inside a select, the select already provides a part for the indicator, it doesn't need to be an actual checkbox.
