### ISSUE TITLE
[HoverCard] SEO warning `links are not crawlable`

### ISSUE THREAD

**Issue by Zwyx** [radix-ui/primitives#2293]
### Current Behavior

The [HoverCardTrigger](https://github.com/radix-ui/primitives/blob/main/packages/react/hover-card/src/HoverCard.tsx) component renders an `a` tag without a `href` attribute.

Chrome dev tools' Lighthouse reports this as an SEO issue:

![Screenshot from 2023-07-21 22-18-24](https://github.com/radix-ui/primitives/assets/29386932/f246e71d-5e2d-436e-8a65-31414ec12875)

It significantly lowers the SEO score in Lighthouse (89 instead of 100 for 5 hover cards, in my case).

### Expected behavior

No SEO warning. However, it's worth noting that Lighthouse's behaviour with this [is not unanimous](https://github.com/GoogleChrome/lighthouse/issues/12030).

### Reproducible example

I believe this is self-explanatory, but I'd be happy to make a demo repo if asked.

### Suggested solution

I don't have any suggestion. I have a workaround:

```tsx
<HoverCardTrigger asChild>
	<div />
</HoverCardTrigger>
```

This works well for me, but note that I only display my hover cards programmatically. So this exact workaround might not be suitable in all cases.

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-hover-card    |      1.0.6   |
| React            | n/a     |     18.2.0    |
| Browser          |   Chrome      |      114.0.5735.198   |
| Assistive tech   |     n/a    |       n/a  |
| Node             | n/a     |       18.14.0  |
| npm/yarn         |     npm    |      9.3.1   |
| Operating System |     Linux    |     Ubuntu 22.04.2 LTS    |

**Comment by benoitgrelard** [comment]
That is because `HoverCard.Trigger` is supposed to be a link to a page, it's up to you to provide that link, we cannot guess where you want your users to navigate to. The whole point is an enhancement to quickly preview the content that lives on another page behind that link.

```tsx
<HoverCardTrigger asChild>
	<div />
</HoverCardTrigger>
```

That isn't a solution because you're breaking focus, and basically going against the whole point of the component.
