### ISSUE TITLE
Unable to programmatically open multiple accordion items.

### ISSUE THREAD

**Issue by atreya2011** [radix-ui/primitives#2294]
### Current Behavior

Unable to programmatically open multiple accordion items.

### Expected behavior

Ability to programmatically open multiple accordion items.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/musing-wind-v97lkw?file=%2FApp.jsx%3A7%2C67)
Clicking on the button `Open item-1 & item-2` should open both item-1 and item-2 but it is not doing it.

### Suggested solution

I followed the advice in this discussion thread, but it doesn't seem to work.
https://github.com/radix-ui/primitives/discussions/824#discussioncomment-1194231

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |@radix-ui/react-accordion|latest|
| React            | n/a     |         |
| Browser          |Chrome|Version 114.0.5735.198 (Official Build) (64-bit)|
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |npm|v8.19.2|
| Operating System |Ubuntu WLS|22.04|

**Comment by rothsandro** [comment]
You use the `defaultValue` which is for uncontrolled mode.
It works if you replace with `value` for controlled mode.

```diff
      <Accordion.Root
        className="bg-mauve6 w-[300px] rounded-md shadow-[0_2px_10px] shadow-black/5"
        type="multiple"
-       defaultValue={rootDefaultValue}
+       value={rootDefaultValue}
        onValueChange={setRootDefaultValue}
      >
```

**Comment by atreya2011** [comment]
@rothsandro Oh wow, I feel really stupid now! Thanks for pointing that out 🙇🏼 It works 🙏🏼
