### ISSUE TITLE
TypeScript errors when attempting to use multiple items in accordion

### ISSUE THREAD

**Issue by JHunnicutt** [radix-ui/primitives#2299]
### Current Behavior

When using the Accordion component in a TypeScript environment, adding`"multiple"` to the property `type` results in the TypeScript error:

`
Type '{ children: Element[]; type: "multiple"; defaultValue: string; collapsible: true; }' is not assignable to type 'IntrinsicAttributes & ((AccordionSingleProps | AccordionMultipleProps) & RefAttributes<HTMLDivElement>)'.
  Types of property 'defaultValue' are incompatible.
`

This error does not show when `"single"` is used in that property.

### Expected behavior

The ability to use either `"single"` or `"multiple"` in the `type` property as dictated by the [API reference](https://www.radix-ui.com/docs/primitives/components/accordion#api-reference).

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-accordion-ts-n4vn7v?file=/src/Accordion.tsx)

Error is found on line 51 of `Accordion.tsx`.

Note: The `Accordion.tsx` file shows a TypeScript error but the component appears to be operable. In fact, you are still able to open multiple tabs at once. However, if a user clicks the first button upon load, the site will crash with the error `prevValue.filter is not a function`. If the user opens other tabs other than the first, they can open and close any other tab with no error.

### Suggested solution

I am unable to provide a suggestion. 

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-accordion     |    ^1.1.2     |
| Next            | n/a     |      ^13.4.2   |
| Browser          |   Chrome      |     114.0.5735.198    |
| Assistive tech   |         |         |
| Node             | n/a     |      v18.8.0   |
| npm/yarn         |     yarn    |   1.22.19     |
| Operating System |    Mac     |    13.4     |

**Comment by joaom00** [comment]
When you set `type="multiple"`, `defaultValue` and `value` is an array of strings
```tsx
<accordion.Root type={"multiple"} defaultValue={["item-1"]}>
...
</accordion.Root>
```

**Comment by JHunnicutt** [comment]
Oh, I see now, thanks! Should the type of `defaultValue` be changed to `string | string[]` in the docs for better clarity?

**Comment by joaom00** [comment]
actually already have 😄. Maybe it's not so clear?

![IMG_20230726_171148](https://github.com/radix-ui/primitives/assets/48808846/a7effdca-c06f-4a00-bc06-ddd31f27df41)

**Comment by JHunnicutt** [comment]
Oh, I think I see where I got confused. It's listed twice. I gotcha, I gotcha.
