### ISSUE TITLE
Scroll Area doesn't work with css max-height

### ISSUE THREAD

**Issue by stonix26** [radix-ui/primitives#2307]
## Bug report
Scroll Area doesn't work with css `max-height`

### Current Behavior
Scroll Area only works with fix css height

### Expected behavior
Should also work with `max-height`

When used together with Dropdown Menu, I want to only show scroll-bar when items overflow the maximum height of the Scroll Area.

### Reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/cool-kirch-lzlsnj?file=%2Fstyles.css%3A6%2C16)

**Comment by joaom00** [comment]
The `max-height` should be set on `Viewport`

**Comment by stonix26** [comment]
> The `max-height` should be set on `Viewport`

Still not working. I also tried making a custom wrapper `div` and sets a `max-height` on it`. Still not working.

I've made a work around

![carbon](https://github.com/radix-ui/primitives/assets/15176029/ffe249cb-f3f0-4722-bd51-133f679e3bda)

**Comment by joaom00** [comment]
Here is working though https://codesandbox.io/p/sandbox/zen-mclaren-v3wj6t?file=%2Fstyles.css%3A9%2C22

**Comment by stonix26** [comment]
> Here is working though https://codesandbox.io/p/sandbox/zen-mclaren-v3wj6t?file=%2Fstyles.css%3A9%2C22

Wow, thanks
I thought, you mean the viewport from the dropdown 😄 
My bad haha

Thanks again @joaom00

**Comment by Asandolo** [comment]
> Here is working though https://codesandbox.io/p/sandbox/zen-mclaren-v3wj6t?file=%2Fstyles.css%3A9%2C22

Hello you repository have no credits, can't oppen it :(

**Comment by jad-eljerdy** [comment]
> > Here is working though https://codesandbox.io/p/sandbox/zen-mclaren-v3wj6t?file=%2Fstyles.css%3A9%2C22
> 
> Hello you repository have no credits, can't oppen it :(

@Asandolo You can sign in and fork it and run it on your account.

**Comment by Asandolo** [comment]
> > > Here is working though https://codesandbox.io/p/sandbox/zen-mclaren-v3wj6t?file=%2Fstyles.css%3A9%2C22
> > 
> > 
> > Hello you repository have no credits, can't oppen it :(
> 
> @Asandolo You can sign in and fork it and run it on your account.

unfortunalty i have a 401 : 

`Failed to fork: (401) You don't have the needed authorization for this workspace (joaom00).`

**Comment by elliotsayes** [comment]
Everything wrong with OSS in one thread

**Comment by KasperiP** [comment]
For me this works worked fine for dynamic height:
```ts
<CommandList>
  <CommandEmpty>{t('general.no_property_found')}</CommandEmpty>
  <CommandGroup>
    <ScrollArea className="flex max-h-40 flex-col overflow-y-auto">
      {frameworks.map((framework) => (
        <CommandItem
          key={framework.value}
          value={framework.value}
          onSelect={(currentValue) => {
            setValue(currentValue === value ? '' : currentValue);
            setOpen(false);
          }}
        >
          <Check
            className={cn(
              'mr-2 h-4 w-4',
              value === framework.value ? 'opacity-100' : 'opacity-0',
            )}
          />
          {framework.label}
        </CommandItem>
      ))}
    </ScrollArea>
  </CommandGroup>
</CommandList>
```

**Comment by 5war00p** [comment]
@KasperiP Solution works, but we don't need `overflow-y-auto` as its already `flex`. 
Additionally for horizontal scroll one can use `flex max-w-30` should work to obtain same behaviour

**Comment by RanitManik** [comment]
> ```ts
> flex max-h-40 flex-col overflow-y-auto
> ```

This works just fine. Thank you very much

**Comment by luckydevboy** [comment]
> > ```ts
> > flex max-h-40 flex-col overflow-y-auto
> > ```
> 
> This works just fine. Thank you very much

Tnx this works for me too.

**Comment by Agros-Hokhy** [comment]
> > ```ts
> > flex max-h-40 flex-col overflow-y-auto
> > ```
> 
> This works just fine. Thank you very much

This works very well. Can someone explain why and how does it work?

**Comment by usmangurowa** [comment]
`max-h-40 overflow-y-auto` 
This works but does not use the ScrollView properties like custom scrollbar etc.
It just as much as adding same class names to a `div`.
So ideally this does not solve the issue.

**Comment by maxchu92** [comment]
> `max-h-40 overflow-y-auto` This works but does not use the ScrollView properties like custom scrollbar etc. It just as much as adding same class names to a `div`. So ideally this does not solve the issue.

Agree with @usmangurowa . I am seeing the same behavior in my project.

**Comment by issam-seghir** [comment]
`flex max-h-40 flex-col overflow-y-auto`


Finally, this is what  work for me without `overflow-y-auto`, which case double scrollbar

**Comment by ss-joy-dviz** [comment]
`flex max-h-40 flex-col overflow-y-auto` is not the solution. You dont get the nice scroll bar thumb

**Comment by viyic** [comment]
I tried using selector to target the Viewport and it works for me.
```tsx
<ScrollArea className="[&_[data-slot=scroll-area-viewport]]:max-h-40">
...
</ScrollArea>
```
