### ISSUE TITLE
react-router-dom Link doesn't work inside Dialog

### ISSUE THREAD

**Issue by benlieb** [radix-ui/primitives#2308]
It seems `<Link>` cannot get the context it needs. 

```
Cannot destructure property 'basename' of 'react__WEBPACK_IMPORTED_MODULE_0__.useContext(...)' as it is null.
```

We tried setting the `id` on the root element for the routes, and using that as the `container` prop for `Portal`, but no effect: 

```
const routes: RouteObject[] = [
  {
    path: '/',
    element: <Layout />,
    children: [

```

Not really sure how to get past this and would rather not abandon the components...

**Comment by joaom00** [comment]
Do you have a minimal sandbox?

**Comment by benlieb** [comment]
As it turns out, I think this is because one of the parent components is being rendered in its own react dom root. Should probably close. Thanks!
