### ISSUE TITLE
[DropdownMenu]: scroll jump issue

### ISSUE THREAD

**Issue by PavelZhuravlev** [radix-ui/primitives#2331]
### Current Behavior
If the `DropdownMenu` is located within a parent container that has the transform property (regardless of the specific value), when the menu is opened, the scroll position jumps to the beginning of the page, and the menu remains off-screen.

https://github.com/radix-ui/primitives/assets/14184094/7e85d9c8-d7d0-44e6-bbbe-26eeacb31293

### Expected behavior
Regardless of the parent's properties, the menu should function correctly

https://github.com/radix-ui/primitives/assets/14184094/0ef756cd-55d6-48b6-9c74-effcc544c3bb

### Reproducible example

[Demo](https://codesandbox.io/p/sandbox/hardcore-elion-lsyf22?file=%2FApp.jsx%3A1%2C1)

### Additional context

The issue persists even with modal={true}, which should prevent scrolling. The scroll still jumps to the beginning of the page and then becomes locked.

<DropdownMenu.Portal/> hides the issue, but I don't think it's appropriate to consider this as a solution. I believe the menu should function correctly even without a portal.

relates to: https://github.com/radix-ui/primitives/issues/1688

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |        "@radix-ui/react-dropdown-menu":    |      "^2.0.5",    |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by GheorgheP** [comment]
@PavelZhuravlev, having the same issue. 

And I confirm that the `<DropdownMenu.Portal/>` does hide the problem, but in my case the portal sgould bound to a specific container and it got in is trapped in the `transform` too.

**Comment by devjones** [comment]
I was able to solve this by setting `modal={false}` on the root DropdownMenu component.  The default is true.

**Comment by ZaymonFC** [comment]
I'm also experiencing this issue with the latest RC of the `Popover` component.

**Comment by leo-paz** [comment]
> I was able to solve this by setting `modal={false}` on the root DropdownMenu component. The default is true.

In my case my dropdown menu was in an absolutely positioned element that was causing the portal to not render in the proper place. Using `modal={false}` fixed it for me

**Comment by brunocabral88** [comment]
I was having the same issue but it was fixed when I upgraded to `2.0.7-rc.10` 🎉

**Comment by jackhkmatthewsBB** [comment]
For me this was being caused by `overflow-y: scroll` on `body`

**Comment by ybarakhovskyi** [comment]
> For me this was being caused by `overflow-y: scroll` on `body`

thanks @jackhkmatthewsBB, this was a real life-saving advice 👏

**Comment by duhaime** [comment]
It seems pretty crazy that this should cause page scrolls at all...
