### ISSUE TITLE
Compose popover with focus on input instead of button

### ISSUE THREAD

**Issue by minedun6** [radix-ui/primitives#2333]
Is it possible to have an input text act as the trigger of the popover ?
I'm looking to build a custom search input with some custom focus behaviour, the focus trigger the popover to show and the blur closes it out.

this is the end result I'm looking for
![Capture d’écran 2023-08-10 à 15 47 01](https://github.com/radix-ui/primitives/assets/4510058/446f63df-632e-4da0-876b-282bab92dd3b)

Is it possible to achieve such interaction ?

**Comment by cpotey** [comment]
Agree with this, would be a really great addition. It doesn't need to be full autocomplete or anything, just a input/focus as a trigger, into a keyboard-navigable list of items

**Comment by Takesizmail** [comment]
+ 1

**Comment by Babailan** [comment]
Did you find a way to do this?

**Comment by benoitgrelard** [comment]
That's because this is the wrong component for this.
You would be looking for #1342.
