### ISSUE TITLE
The import path @radix-ui/react-compose-refs resolves to multiple files in the bundle

### ISSUE THREAD

**Issue by pmbanugo** [radix-ui/primitives#2334]
## Question

I get that warning when I analyse my bundle using esbuild. Is this a known issue? How can I fix this?

![Screenshot 2023-08-10 at 17 18 07](https://github.com/radix-ui/primitives/assets/4036118/3fb1beab-1fb9-407e-87e0-89b03dd41513)

**Comment by benoitgrelard** [comment]
Hi @pmbanugo It is impossible for us to do anything based on these logs and could be due to so many things in your setup.
If you want us to be able to help, you need to provide an example repository showing the symptoms.
I will close the issue in the meantime.
