### ISSUE TITLE
Tabs: Wrapped Tab.Trigger used inside the same export as the Controlled Tabs.Root breaks focus

### ISSUE THREAD

**Issue by adamdiestelkamp** [radix-ui/primitives#2335]
### Should be active like this
<img width="341" alt="image" src="https://github.com/radix-ui/primitives/assets/4571734/2a1451c0-b302-46a9-adba-24a2de010194">

### Tab 1 loses focus after click/navigating
<img width="368" alt="image" src="https://github.com/radix-ui/primitives/assets/4571734/4c3ed834-525f-4d41-ae74-852b335c8a21">

https://codesandbox.io/p/sandbox/hungry-sara-4drlmw?file=%2FApp.jsx%3A1%2C1-55%2C1

### Current Behavior
When used like this `Tab1` will break focus and cause focus to move out of the `Tabs.Root`

- Click or use arrow keys to navigate to `Tab1`. 
- Will no longer be able to navigate to other tabs, focus has moved outside.

```
const TabsFocusIssue = () => {
  const [value, setValue] = React.useState('tab2')

  // Breaks focus
  const Tab1 = () => {
    return <Tabs.Trigger className="TabsTrigger" value="tab1">1
  </Tabs.Trigger>
  }
  
  // Works fine.
  const tab3 = <Tabs.Trigger className="TabsTrigger" value="tab3">3</Tabs.Trigger>
 
  return (
  <Tabs.Root className="TabsRoot" value={value} onValueChange={(value)=>setValue(value)}>
    <Tabs.List className="TabsList" aria-label="Manage your account">
      {/* In a controlled tabs component, when clicking or navigating to this initially, 
      it will move the focus out of the tabs and break keyboard navigation.
      Have to click it again in this case to get focus back in tabs.  */}
      <Tab1/>
      {/* If I use one from out side this function it works fine... */}
      <Tab2/>
      {/* If I use one declared like tab3=<...> works fine... */}
      {tab3}
      <Tabs.Trigger className="TabsTrigger" value="tab4">
        4
      </Tabs.Trigger>
    </Tabs.List>
)
};
```

### Expected behavior

Expect focus to remain on the activated tab.

### Reproducible example

[Focus Issue Demo](https://codesandbox.io/s/focused-bash-wmtvjr?file=/src/App.js)

### Suggested solution

...

### Additional context

In the code sample I document two other ways that work.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  Tabs       |   1.0.4      |
| React            | n/a     |   17.0.1      |
| Browser          |     Chrome    |     115.0.5790.170     |
| Assistive tech   |         |         |
| Node             | n/a     |    16.20.0     |
| npm/yarn         |   npm      |    8.19.4     |
| Operating System |   OSX      |     12.6.7    |

**Comment by benoitgrelard** [comment]
That's because you are not forwarding props or and ref.

You would need to update your example to something like:

```tsx
const Tab1 = React.forwardRef((props, ref) => {
    return <Tabs.Trigger className="TabsTrigger" value="tab1" ref={ref} {...props}>1
  </Tabs.Trigger>
  });
```

**Comment by adamdiestelkamp** [comment]
Hey thanks for the reply!

Updating it to use `forwardRef` does not appear to fix it—[code here](https://codesandbox.io/p/devbox/hungry-sara-4drlmw?file=%2FApp.jsx%3A1%2C1-55%2C1)

It does work for `Tab2` that doesn't forward it's ref BUT is defined outside of the function. Seems like there's something breaking when it's defined within the other component—but that's probably a bad idea and would get re-created on each render—probably needs to be refactored out of the component.
