### ISSUE TITLE
ContextMenu.Content type problem

### ISSUE THREAD

**Issue by lyuly** [radix-ui/primitives#2341]
### Current Behavior
`Content` type `sideOffset` has problem,show in picture

![a6871229dd0db57742356e7dde3cd62e.png](https://ice.frostsky.com/2023/08/16/a6871229dd0db57742356e7dde3cd62e.png)

### Expected behavior
![f8496d28b45afa9f198f6ad425456e55.png](https://ice.frostsky.com/2023/08/16/f8496d28b45afa9f198f6ad425456e55.png)

### Reproducible example

[official context-menu](https://www.radix-ui.com/primitives/docs/components/context-menu)

### Suggested solution
`export interface ContextMenuContentProps extends Omit<MenuContentProps, 'onEntryFocus' | 'side' | 'sideOffset' | 'align'>`

change to 

`export interface ContextMenuContentProps extends Omit<MenuContentProps, 'onEntryFocus' | 'side' | 'align'>`

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    react-context-menu     |  2.1.4       |
| React            | n/a     | 18.2.0        |
| Browser          |   chrome      |  116       |
| Assistive tech   |         |         |
| Node             | n/a     |    v18.17.0     |
| npm/yarn         |    pnpm     |   8.6.12      |
| Operating System |   windows      |   11      |

**Comment by benoitgrelard** [comment]
This is intended, the prop isn't supported for `ContextMenu` as it should open next to where you've right-clicked.
