### ISSUE TITLE
Conditionally Rendered Component with ToolTip produces react warning

### ISSUE THREAD

**Issue by iamterryclark** [radix-ui/primitives#2342]
## Bug report
I have a conditionally rendered component, which has a Radix ToolTip inside, I noticed that on the console I see this when showing the conditional component, which points to line 95 of the Tooltip Provider

![image](https://github.com/radix-ui/primitives/assets/8614976/4ce63a0f-f357-430b-8026-b193e4db100b)
![image](https://github.com/radix-ui/primitives/assets/8614976/36055ce1-b72d-4ec7-9c9f-463e51219c08)

Is there something I need to do on my tooltip in order to handle this?

Version of radix I am using
React : 17.0.2
 "@radix-ui/react-tooltip": "^1.0.6",
  "@radix-ui/react-context-menu": "^2.1.4",
  "@radix-ui/react-dropdown-menu": "^2.0.5",

**Comment by cssinate** [comment]
If you figured out an answer to this, consider putting the solution in the comments so anyone searching in the future can benefit from your investigation :)
