### ISSUE TITLE
Add `onOpenChange` to `<NavigationMenu.Content>`

### ISSUE THREAD

**Issue by benface** [radix-ui/primitives#2344]
### Overview

Would be useful and consistent with other components!

### Examples in other libraries

N/A

### Who does this impact? Who is this for?

Me. :)

### Additional context

Thank you!

**Comment by benface** [comment]
And while I'm at it, `open` would be nice as well, so we can control the "open" state as needed.

**Comment by LimeWub** [comment]
@benface 

Hey - I think that's what `onValueChange`, `defaultValue`, `value` value on the `Root` (and `Sub`?) element do. Try these out cause they may be covering your use case.

ie. with this code:
```
<NavigationMenu.Root onValueChange={onOpenChange}>
    <NavigationMenu.Item value="SOME_ID">
      <NavigationMenu.Trigger>Item trigger</NavigationMenu.Trigger>
      <NavigationMenu.Content>Item content</NavigationMenu.Content>
    </NavigationMenu.Item>
</NavigationMenu.Root>
```

when you open the content you get `onOpenChange` called with `"SOME_ID"`

**Comment by benface** [comment]
@LimeWub – Welp, you are totally right. :) Not sure how I missed this. This covers my use case perfectly. Thank you!
