### ISSUE TITLE
Primitive Tabs Issue

### ISSUE THREAD

**Issue by brain1401** [radix-ui/primitives#2345]
### Current Behavior
When you navigate through the tabs using the Tab key on your keyboard and encounter Tabs.Trigger, the tab behaves as if it has been clicked, switching to that tab.

### Expected behavior
When using the Tab key on the keyboard to move focus, encountering Tabs.Trigger should not cause the tab to switch.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/cranky-montalcini-ls4r3s)

### Additional context
I implemented logic to reset the content held in the Content of the tab before switching through the onClick event when the tab is switched (when the tab is clicked). Therefore, 'disabled' was necessary. This is because it prevents the content in the current tab from being reset when the current tab is clicked.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Tabs     |    1.0.4     |
| React            | n/a  |  18.2       |
| Browser          |    Chrome     |  115.0.5790.171     |
| Assistive tech   |         |         |
| Node             | n/a     |     18.16    |
| npm/yarn         |         |         |
| Operating System |   Windows    |    10     |

**Comment by rothsandro** [comment]
You can change the behavior via `activationMode` prop:

```jsx
<Tabs.Root activationMode="manual">...</Tabs.Root>
```

**Comment by brain1401** [comment]
> You can change the behavior via `activationMode` prop:
> 
> ```js
> <Tabs.Root activationMode="manual">...</Tabs.Root>
> ```

Thanks, It works

**Comment by brain1401** [comment]
> You can change the behavior via `activationMode` prop:
> 
> ```js
> <Tabs.Root activationMode="manual">...</Tabs.Root>
> ```

Thanks, it works
