### ISSUE TITLE
Accordion  data-state="open" not working 

### ISSUE THREAD

**Issue by mweel1** [radix-ui/primitives#2353]
### Current Behavior

The accordion isn't open when I set data-state="open" on the AccordionItem

<img width="632" alt="image" src="https://github.com/radix-ui/primitives/assets/77025147/87191582-7b73-4836-ab16-77fcd687cd0b">

### Expected behavior

I expect it to be open

### Reproducible example

[[CodeSandbox Template](https://codesandbox.io/s/2r30e)](https://codesandbox.io/s/xenodochial-lamarr-z4zr6h?file=/src/App.tsx)

@radix-ui/react-accordion": "^1.1.2

**Comment by joaom00** [comment]
To control the accordion you can use `value` and `onValueChange` props. Would be like this

```jsx
const [value, setValue] = React.useState([]) // note that I'm using an array because you defined `type=multiple` otherwise it would just be a string

<Accordion.Root value={value} onValueChange={setValue}>
  { ... }
</Accordion.Root>
```

**Comment by mweel1** [comment]
Ok thanks, might want to update the documentation as this is where I got this approach from?

**Comment by joaom00** [comment]
It's already there :smile:  but I agree that it should be more direct. maybe with an example showing how to control the component
