### ISSUE TITLE
Components (Dropdown, Dialog, etc) are too slow due to Passive effects.

### ISSUE THREAD

**Issue by hywook4** [radix-ui/primitives#2356]
Hi 

When the page size is big (many DOMs), components such as Dropdown/Dialog becomes very slow.

I've used React profiler to dive deep into this issue and found that it's due to long Passive effects.

Below is the screenshot of the profiler result
<img width="913" alt="Screen Shot 2023-08-22 at 5 16 07 PM" src="https://github.com/radix-ui/primitives/assets/14287937/0225bd9a-6c56-4032-a6d5-281ed0a6b50b">

I've found that in the case of the Dropdown component, the issue was fixed when I gave modal={false} props. 

Also seems like the "Presence" component is the main cause for the passive effects.

Thank you,

**Comment by hywook4** [comment]
This is just a guess, but 
Presence key=".0" seems like the one causing the problem while I have no idea where it came from.

**Comment by recurrence** [comment]
Does anyone have a patch for this?  Radix SCREAMS in comparison with modal false but it has other unintended consequences.

**Comment by hariangr** [comment]
Anyone have any lead on this?

**Comment by tangye1234** [comment]
This issue basically is the biggest flaw in this project at present, and no one has come forward to resolve it yet.

**Comment by taoliujun** [comment]
When modal is enabled, popover calls the react-remove-scroll component, which iterates through every element in the page, and when there are enough elements, there are performance issues.

But I don't know how to solve it.

**Comment by benoitgrelard** [comment]
Let's concentrate on a single issue rather than have lots of duplicates for the same thing: #1634

**Comment by ibanlopez** [comment]
> Let's concentrate on a single issue rather than have lots of duplicates for the same thing: #1634

How is the concentration going?

**Comment by martinsirbe** [comment]
> > Let's concentrate on a single issue rather than have lots of duplicates for the same thing: [#1634](https://github.com/radix-ui/primitives/issues/1634)
> 
> How is the concentration going?

I find this very concentrating.
