### ISSUE TITLE
[Select] A version without dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by elisehein** [radix-ui/primitives#2360]
## Feature request

We cannot use `Select` in production because the use of `dangerouslySetInnerHTML` in [SelectViewport](https://github.com/radix-ui/primitives/blob/ea6376900d54af536dbb7b71b4fefd6ec2ce9dc0/packages/react/select/src/Select.tsx#L1053C11-L1053C34)
 (and ScrollArea).

### Overview

It would be great to have Select updated to not use `dangerouslySetInnerHTML` internally, or to provide options to use it in a way that avoids this.

**Comment by TylerK** [comment]
Bumping this. I've also run into this issue whereby the `dangerouslySetInnerHTML` block is injected into the DOM leading to needing to hide the `style` tag with CSS. 

Any guidance on why this happening or how to fix it would be great.

**Comment by SSifantus** [comment]
+ 1️⃣

**Comment by benoitgrelard** [comment]
We've just added a `nounce` prop to aleviate these issues. You can try it in the latest release candidate.
