### ISSUE TITLE
Cannot click dropdown menu button using DOM method click()

### ISSUE THREAD

**Issue by truongtrongtin** [radix-ui/primitives#2362]
### Current Behavior

Cannot open dropdown menu by querying the button and call `click()`

### Expected behavior

Should open the menu.

### Reproducible example
- Go to: https://www.radix-ui.com/primitives/docs/components/dropdown-menu
- Open browser console
- Run:
```JS
document.querySelector('button[aria-label="Customise options"]').click()
```

This works for Popover.

**Comment by ayaniv** [comment]
Any workaround on this?
