### ISSUE TITLE
Not close the Dropdown menu content when Item, Checkbox, Radio is clicked in it.

### ISSUE THREAD

**Issue by arpitdalal** [radix-ui/primitives#2366]
## Feature request
I think this is a feature request unless I'm somehow missing how to handle this.

### Overview
I'd like if dropdown menu content doesn't close when dropdown menu item is clicked in it. I've tried `event.stopPropogation()` onClick on dropdown menu item but that didn't help.

### Who does this impact? Who is this for?

This behaviour would be expected if using Checkboxes in the dropdown as multiple checkboxes can be selected at once and if dropdown menu content closes on every selection, it's not a great user experience.

### Additional context
codesandbox: https://codesandbox.io/p/sandbox/peaceful-hertz-sqxlr5

**Comment by imri29** [comment]
Use`event.preventDefault()` in `onSelect`.

**Comment by arpitdalal** [comment]
@imri29 Thanks for the answer! Didn't think of this solution before 👍

**Comment by scamden** [comment]
@imri29 when using a Link within a dropdown menu item this solution prevents the link from navigating (at least with react-router ~~haven't tried plain <a> tag~~ Edit: it does prevent even standard anchor elements from working). The use case I have is a dropdown menu with many links. I want to allow the user to cmd+click more than one of them without closing the drop down so they can open a few quickly. 

Any other way to prevent the close?

Update: Nope. I just misread and was preventing the click event, not the select event. onSelect works perfectly.
