### ISSUE TITLE
Toast Dismissal Direction is stuck on LTR 

### ISSUE THREAD

**Issue by TheMikeyRoss** [radix-ui/primitives#2368]
### Current Behavior

The Toast component I have is not dismissing to the left of the screen when the direction is RTL
![radix-toast-issue-1](https://github.com/radix-ui/primitives/assets/97709651/caf608b4-be7f-4f4a-a30a-e175bf01075a)

### Expected behavior

It's expected to disappear by swiping to the left of the screen when the direction is set to RTL (either after the duration or when I swipe it out)

### Reproducible example

https://codesandbox.io/p/sandbox/tender-murdock-m7s7xt?file=%2FApp.jsx%3A14%2C41

### Additional context

As you can see in the sandbox example, I change the `swipeDirection` to `left` in the `Toast.Provider` component and I also stylized the `Toast.Viewport` component to be on the left side of the screen. 
And on top of that I wrapped the whole thing with `DirectionProvider` component but it's still 

### Suggested solution

I tried to go through the code in [Toast.tsx](https://github.com/radix-ui/primitives/blob/main/packages/react/toast/src/Toast.tsx) but I had a hard time deciphering it. 

However I think it's better if there could be a prop for the direction of which the toast will disappear to. Or it can inherit the same direction as the `swipeDirection` prop

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   "@radix-ui/react-direction"      |     "^1.0.1"    |
| Radix Package(s) |   "@radix-ui/react-toast"     |     "^1.1.4"    |
| React            | n/a     |   "^18.2.0"      |
| Browser          |    Chrome     |     v116.0.5845.110    |
| Assistive tech   |         |         |
| Node             | n/a     |     v16.14.2    |
| npm/yarn         |         |     v8.5.0    |
| Operating System |       Windows |     10    |

**Comment by joaom00** [comment]
You need to adjust the `slideIn` and `swipeOut` animations

[Codesandbox](https://codesandbox.io/p/sandbox/zealous-mahavira-rcvm67?file=/tailwind.config.js:20,1-31,11)

**Comment by TheMikeyRoss** [comment]
Yup you're totally right. Thank you @joaom00 

I fixed it by making the animation conditional based on direction (using tailwind-animate)

```
   <ToastPrimitives.Root
      ref={ref}
      className={cn(
        toastVariants({ variant, severity }),
        className,
        props.direction === "rtl"
          ? "data-[state=closed]:slide-out-to-left-full"
          : "data-[state=closed]:slide-out-to-right-full"
      )}
      {...props}
    />
```
