### ISSUE TITLE
[FocusScope] Allow links/anchors to get focus

### ISSUE THREAD

**Issue by simonrelet** [radix-ui/primitives#2373]
### Overview

[It looks like](https://github.com/radix-ui/primitives/pull/925) links/anchors are not allowed to receive focus in some components.
Maybe I'm doing something wrong but I have a [Popover](https://www.radix-ui.com/primitives/docs/components/popover) component rendering content, a link and a button. I would need the link to be focused when the popover opens as it's the first visible user action, and I expect the user to be able to cmd/ctrl-click, or right click it to open a new tab. So I can't replace the link by a button.

An alternative could be to be able to focus the popover element itself by default so the user can then tab through the content.

### Examples in other libraries

It looks like [MUI](https://github.com/mui/material-ui/blob/v5.14.7/packages/mui-base/src/FocusTrap/FocusTrap.tsx#L18) and [tabbable](https://github.com/focus-trap/tabbable/blob/v6.2.0/src/index.js#L10) support it.

### Who does this impact? Who is this for?

I think all users.

### Additional context

Thank you for for the hard work on this library 🙏

**Comment by simonrelet** [comment]
As _workaround_, I added as child of `Popover.Content` a wapping `<div tabIndex={0} />` to be sure the entire content always gets focused by default, then the user can tab through the content.

**Comment by lucassarcanjo** [comment]
I ran into the same issue today, and `onOpenAutoFocus` really helped me out. To tweak my menu, I made a custom focus function:

```tsx
onOpenAutoFocus={(e) => {
  e.preventDefault();

  const firstInteractiveElement = e.currentTarget.querySelector('button, a');
  firstInteractiveElement.focus();
}}
```
