### ISSUE TITLE
Dropdown Menu - Force Content to stay mounted in DOM

### ISSUE THREAD

**Issue by srowe0091** [radix-ui/primitives#2385]
### Overview

Have the ability to keep DropdownContent mounted even when the Dropdown is closed.

The use case for this is if you have a Menu item that opens a Dialog, the Dialog immediately closes because the Menu has closed on click of an item which then removes the Content from the DOM.

There is an option to keep the Menu dropdown open by utilizing the onSelect like this
`onSelect={e => e.preventDefault()}`
But then the Dropdown remains open the whole time, and when the Dialog is finished and closed, the Menu is still open causing the user to click again elsewhere to close it, which is not ideal.

I thought the `forceMount` prop on the Content component would work, but it's not keeping the Content mounted in the DOM.

### Examples in other libraries

Chakra-UI has this implementation but in an opposite format. Chakra keep menu items mounted by default. They provide a prop to unmount when the menu is closed
https://chakra-ui.com/docs/components/menu/props#menu-props

### Who does this impact? Who is this for?
This could be for all users, and additional prop that keeps Content mounted would still be backwards compatible so it shouldn't break current functionality.

### Additional context

Here's an example of how it is implemented
https://codesandbox.io/s/rough-rain-j2dflx?file=/src/Dropdown.jsx

**Comment by ckkz-it** [comment]
What if you make it controlled Dialog and move it outside of the dropdown menu item?

```typescript
import React from "react";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import * as Dialog from "@radix-ui/react-dialog";

const DropdownMenuDemo = () => {
  const [open, setOpen] = React.useState(false);
  const openDialog = () => {
    setOpen(true);
  };

  return (
    <React.Fragment>
      <Dialog.Root open={open}>
        <Dialog.Portal>
          <Dialog.Content className="DialogContent">
            Dialog Content
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>

      <DropdownMenu.Root>
        <DropdownMenu.Trigger asChild>
          <button aria-label="Customise options">Dropdown Menu</button>
        </DropdownMenu.Trigger>
        <DropdownMenu.Content className="DropdownMenuContent" sideOffset={5}>
          <DropdownMenu.Item className="DropdownMenuItem" onClick={openDialog}>
            Open Dialog (broken)
          </DropdownMenu.Item>
        </DropdownMenu.Content>
      </DropdownMenu.Root>
    </React.Fragment>
  );
};

export default DropdownMenuDemo;
```

**Comment by srowe0091** [comment]
Hmm, this approach can work, but it'll make the implementation messy because this dropdown has about 4-5 different options that opens its own modal. but since it doesn't seem like theres another way, i think this would be the best option for now.

**Comment by benoitgrelard** [comment]
What you want is achievable by composing dropdown and dialog and adding a little bit of focus management code.
In this sandbox, you will find 2 examples, the first being what you are talking about above (when it stays open behind), the second being a little more advanced where it all appears as you expect for the user.

https://codesandbox.io/p/sandbox/dropdownmenu-dialog-items-r9sq1q?file=%2Fsrc%2Findex.js

**Comment by benoitgrelard** [comment]
Worth noting, we also discuss options to keep the content mounted in general over in #1155.
