### ISSUE TITLE
Popover slows down and blinks the bigger the page is when modal is true

### ISSUE THREAD

**Issue by cleytoncarvalho** [radix-ui/primitives#2386]
Popover slows down and blinks the bigger the page is when modal is set to true. The problem happens in Safari but not in Google Chrome.

### Current Behavior

https://github.com/radix-ui/primitives/assets/7952866/45a66efa-ada9-4162-bfc2-b45e617b1f72

### Expected behavior

Popover performance should not be impacted by the height of the page when in modal mode.

### Additional context

Remix app.

### Environment

Radix: @radix-ui/react-popover@1.0.6
React: react@18.2.0
Browser: Safari
Node: 18.17.1
Npm: 9.6.7
Operating System: MacOS Ventura 13.5.1

**Comment by cleytoncarvalho** [comment]
Sorry. The problem was with my code.

**Comment by taoliujun** [comment]
@cleytoncarvalho Why is it a problem with your own code? How did you solve it?

I found that when modal is enabled, popover will call the react-remove-scroll component, it will iterate through every element in the page, and when there are enough elements, there will be performance issues.
