### ISSUE TITLE
Tooltip content doesn't render as expected

### ISSUE THREAD

**Issue by salieflewis** [radix-ui/primitives#2389]
I'm implementing the Tooltip primitive, as seen below and I'm curious as to why the positioning of the content is specifically offset when passing `right` as a prop to `side`. I was also forced to wrap my Tooltip components in an absolutely positioned div in order for them (every variant but the `side={'right`}`) to render right next to their trigger. If anyone could provide any clarity, or general comments onto this API, that would be greatly appreciated. Thank you.

```
'use client';

import * as React from 'react';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';

interface TooltipProps {
  side?: 'top' | 'right' | 'bottom' | 'left';
  align?: 'start' | 'center' | 'end';
  children: React.ReactNode;
  content: React.ReactNode;
}

const TooltipProvider = TooltipPrimitive.Provider;

const TooltipRoot = TooltipPrimitive.Root;

const TooltipTrigger = TooltipPrimitive.Trigger;

const TooltipContent = TooltipPrimitive.Content;

const TooltipPortal = TooltipPrimitive.Portal;

export function Tooltip({ side, align, children, content }: TooltipProps) {
  return (
    <TooltipProvider>
      <TooltipRoot>
        <TooltipTrigger asChild className='cursor-pointer'>
          {children}
        </TooltipTrigger>
        <TooltipPortal>
          <TooltipContent
            className='bg-base border-[0.5px] border-base-border px-5 py-4 rounded-[10px] shadow-sm'
            sideOffset={4}
            side={side}
            align={align}
          >
            {content}
          </TooltipContent>
        </TooltipPortal>
      </TooltipRoot>
    </TooltipProvider>
  );
}
```

**Comment by benoitgrelard** [comment]
Closing this as this is likely a CSS issue, not a primitive issue.
You can see an example of all positioning in our storybook here: https://601857eb614bae0021c9b9dd-evgfcrkbbq.chromatic.com/?path=/story/components-tooltip--positions
