### ISSUE TITLE
React-select is putting margin-right: 13px !important in body

### ISSUE THREAD

**Issue by jordisantamaria** [radix-ui/primitives#2409]
### Current Behavior

When open select, it's including margin-right: 13px !important on body, so all my website is moving.

### Expected behavior

Not including margin-right on body.

### Additional context

In documentation it says about it's doing it because using <ScrollArea> component, but it should be able to work properly also even if you don't use scrollArea.
Still, there is not any example in documentation about how to use <ScrollArea> with full body of the page and I can't manage how to use it properly like that.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     "@radix-ui/react-select": ""    |   ^1.2.2      |
| React            | n/a     |     ^18.2.0    |
| Browser          |    chrome     |         |
| Assistive tech   |         |         |
| Node             | n/a     |    v18.16.0     |
| npm/yarn         |   npm      |    9.5.1     |
| Operating System |   Linux mint      |         |

**Comment by jordisantamaria** [comment]
For now fixed the issue of scrolling content when opening select by including css

html {
  overflow: visible !important 
}

**Comment by benoitgrelard** [comment]
This is due to how the library we use to prevent scrolling works.
If you have fixed elements, or full width element, there's a bit of extra code that is needed per use-case.
See this: https://github.com/radix-ui/primitives/issues/1925#issuecomment-1568657251
