### ISSUE TITLE
react-popover doesn't position content correctly in a container with a new positioning context

### ISSUE THREAD

**Issue by attaboy** [radix-ui/primitives#2411]
### Current Behavior

With @radix-ui/react-popover v1.0.6, the popover content is not positioned correctly when the popover is inside of an element that introduces a new positioning context, like one that sets `container-type: inline-size` or uses `filter`.

### Expected behavior

Popover should position relative to the container with positioning context, instead of always to the page.

### Reproducible example

https://codesandbox.io/s/radix-popover-inside-container-test-7h2t7l?file=/src/App.tsx

### Suggested solution

Although installing v1.0.7 seems to fix this problem in a sandbox, in practice on my repo, it does not, and I believe that is because the underlying `@floating-ui/react-dom` dependency hasn't been upgraded to a version that requires a new enough `@floating-ui/dom`. As far as I can tell, the bug was fixed with `@floating-ui/dom@1.4.3`.

https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Fdom%401.4.3

The only obvious way I can find to fix this is to blow away my package-lock.json file, which is obviously not ideal. 😞 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-popover | 1.0.6 and 1.0.7 |
| React            | n/a     | 16.14 |
| Browser          | Chrome |         |
| Node             | n/a     | 18.16 |
| npm/yarn         | npm | 9.5.1 |
| Operating System | Mac | 13.5.2 |

**Comment by atomiks** [comment]
> The only obvious way I can find to fix this is to blow away my package-lock.json file, which is obviously not ideal. 😞

You can uninstall and reinstall the popover package, then it should pick up the new transitive deps.

**Comment by attaboy** [comment]
Thank you. This is the solution I settled on as well, but I had to uninstall _all_ of the Radix components we are using that use react-popper under the hood (react-popover, react-dropdown-menu, and react-tooltip), before the old dependencies were wiped.
