### ISSUE TITLE
How suppress DropdownMenu closes when click on CheckboxItem

### ISSUE THREAD

**Issue by AdsonCicilioti** [radix-ui/primitives#2414]
## Expectation
A `DropdownMenu` with multiple `CheckboxItem`(s) where the idea is to select more than one item without closing the menu.  The DropdownMenu in this case should close after losing focus, clicking away or pressing the ESC key.

## Behavior
The `DropdownMenu` closes after clicking any item.  This takes the user on a long journey to compose their selection of items.

## Question
Is there a way to change this behavior?

**Comment by joaom00** [comment]
You can use `onSelect={event => event.preventDefault()}` on `CheckboxItem`

**Comment by AdsonCicilioti** [comment]
> You can use `onSelect={event => event.preventDefault()}` on `CheckboxItem`

I came here to let you know that I found a way and it is very similar to yours, but I put my logic in the `onClick` event.  I tested it with `onSelect` and it also works.  Now I'm unsure which one would be the most suitable.

Thx @joaom00 ! :brazil: :heart:

**Comment by Trex-Hub** [comment]
> You can use `onSelect={event => event.preventDefault()}` on `CheckboxItem`

Thanks Man. This helped.
