### ISSUE TITLE
Update `Releases` page to include latest release

### ISSUE THREAD

**Issue by snelsi** [radix-ui/primitives#2415]
[New release](https://github.com/radix-ui/primitives/commit/c31c97274ff357aea99afe6c01c1c8c58b6356e0) was published 2 days ago. 

Assuming, a major version bump for `@radix-ui/react-select` includes a breaking change, please update [Releases](https://www.radix-ui.com/primitives/docs/overview/releases) section of the docs to include migration guide and release notes.

**Comment by ajdiyassin** [comment]
Also [select docs](https://www.radix-ui.com/primitives/docs/components/select) still showing for 1.2.2 version

**Comment by snelsi** [comment]
@Flickwire 
https://github.com/radix-ui/primitives/pull/2174

**Comment by itsmingjie** [comment]
Looks like `@radix-ui/react-dialog` also has breaking changes in latest release 1.0.5 (see #2423, related issue https://github.com/shadcn-ui/ui/issues/1644). Would greatly appreciate updated logs and breaking change notice.

**Comment by benoitgrelard** [comment]
Apologies, it looks like we missed the changelog for that latest public release, I will fix this now.
Thanks for raising!
