### ISSUE TITLE
'className' type on dialog seems to have been broken in 1.0.5

### ISSUE THREAD

**Issue by 0xk3v** [radix-ui/primitives#2423]
### Current Behavior
className property has type error in 1.0.5 of  `@radix-ui/react-dialog`

![image](https://github.com/radix-ui/primitives/assets/94931973/205a881e-03cc-49bc-a951-63b89db080e8)

### Expected behavior

no errors on className property

### Reproducible example

install latest version of `@radix-ui/react-dialog`

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   react-dialog      |     1.0.5   |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |    pnpm    |         |
| Operating System |     Linux    |         |

**Comment by itsmingjie** [comment]
Given 1.0.5 is a patch release, I'm assuming this was a bug and the type was dropped. Gonna help recovering it. This is the commit in question: https://github.com/radix-ui/primitives/commit/f873591ac32c31df9e860d3b6fc65be3cb910ba4.

**Comment by 0xk3v** [comment]
The issue has been fixed with latest shadcn update. Thanks everyone who gave suggestions.!

**Comment by 0xk3v** [comment]
closing issue

**Comment by mtalha218** [comment]
I am using Button from @radix-ui/themes simply like this

`<Button className="rounded-none text3">Upload Documents</Button>`

But my custom CSS class "text3" is not applied, nor did my TailwindCss class "rounded-none. Only inline style is working. Why is that?

**Comment by 0xk3v** [comment]
Hi @mtalha218 

I've never used radix-ui/themes before (I always use primitives with shadcn) but from what I'm seeing in docs they might not be using tailwind classes? (I may be wrong though)

take a look:

![image](https://github.com/radix-ui/primitives/assets/94931973/4f497f61-59ff-457f-be27-5c08b5bc9267)

if somebody knows what's going, they can help you! Good luck : )
