### ISSUE TITLE
[Select] Missing typeahead documentation

### ISSUE THREAD

**Issue by angelod1as** [radix-ui/primitives#2456]
### Relevant Radix Component(s)

[Select](https://www.radix-ui.com/primitives/docs/components/select)

### Description

The Select component has `supports typeahead` in the features list but doesn't properly show how to implement such a feature. A simple example in the docs should be enough.

**Comment by nguyen-michael** [comment]
I believe this just works. Even in the example, you can open the select, then start typing and it will highlight options that match what you're typing. This works on native selects as well.

**Comment by angelod1as** [comment]
Oh, I had completely misunderstood "typeahead" then. I though it would work like an autocomplete or similar. Thanks.

**Comment by akd-io** [comment]
Aah, I misunderstood too, thanks for the PR. I thought it would allow me to type in an input field, with search results narrowing down underneath.

**Comment by chiptus** [comment]
@nguyen-michael any idea how to implement something with a search field?

**Comment by joeyfigaro** [comment]
Typeahead support suggests that the component supports typing *into* `Select.Value` to search through the available items. Using the keyboard to automatically highlight options that match letters typed is included under `Full keyboard navigation.`

**Comment by xeger** [comment]
Agree, @joeyfigaro; "typeahead" implies, to me, that I can type a string of characters to filter the options that are displayed (and potentially to ask the application to search for new options).

**Comment by siyaoxie-pixieset** [comment]
i also cannot find documentation on how to disable this feature. its causing conflicts with my other hotkeys in the app
