### ISSUE TITLE
Use "position: absolute" instead "transform" (or any ideas how i can fix blurred menus in chrome)?

### ISSUE THREAD

**Issue by yudinvictor** [radix-ui/primitives#2458]
Hi all, I noticed this problem: on some resolutions in chrome all radix menus have blurring after opening.

On the first screen the tooltip (this problem is not only in tooltips, but in all menus) is blurred after opening, on the second screenshot this tooltip is opened after some other one (i.e. there is no animation)
![image](https://github.com/radix-ui/primitives/assets/43467675/8dfde8a7-f46b-4a42-93f9-ae0b51627277)
![image](https://github.com/radix-ui/primitives/assets/43467675/cf04234d-1de8-4019-aa99-be4481381de6)

I found out that this problem is related to the transform property in chrome. I tried many hacks like "translateZ()" but nothing helped. 

Has anyone experienced this problem? 

As a solution I see the option to use position: absolute instead of transform everywhere in radix primitives. 

Does anyone know how to do this? (Other than forking)

**Comment by kotAPI** [comment]
seems like this is a rendering issue on some browsers - not radix, but I've seen such weird behaviors related to transitions. I tried applying anti aliasing, but looks like it only works on text

**Comment by yudinvictor** [comment]
This has been fixed in version 2.0.6! Thanks to the radix team!

P.S. The problem was in the application of translateZna level of DropdownMenu.Root (previously transalte passed (x, y, 0) now only (x, y)). (If you are interested, you can google what translateZ(0) does in chrome to better understand why this was happening).
