### ISSUE TITLE
Dropdown Menu [aria-hidden="true"] elements contain focusable descendents

### ISSUE THREAD

**Issue by otomatik** [radix-ui/primitives#2459]
### Current Behavior
When running Lighthouse accessibility test on an open Dropdown Menu (note you need to force `open` state) we encounter this `[aria-hidden="true"] elements contain focusable descendents` error (see screenshot below).

<img width="914" alt="Screenshot 2023-10-17 at 10 34 07" src="https://github.com/radix-ui/primitives/assets/198545/4f943fc5-74d9-46b9-8247-6f0f8b605cc8">

### Expected behavior

No more error when running this accessibility test.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/sad-chaum-sszd46?file=%2FApp.jsx%3A13%2C55)

### Additional context

Note you need to force `open` state before running the test.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `@radix-ui/react-dropdown-menu`    |   `2.0.5`      |
| React            | n/a     |    `18.2`     |
| Browser          |    chrome     |   `118.0.5993.70`      |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
That is correct though as the trigger isn't part of the new open layer and therefore should be considered non-interactive (in modal mode).
