### ISSUE TITLE
[Form] Cannot read properties of undefined (reading 'defaultPrevented')

### ISSUE THREAD

**Issue by alexandergottlieb** [radix-ui/primitives#2464]
### Current Behavior

`<Form.Control asChild>` does not support custom inputs that call `onChange(undefined)` instead of passing an `Event`.

<img width="1027" alt="Screenshot 2023-10-18 at 12 12 06" src="https://github.com/radix-ui/primitives/assets/17096321/c6609b1c-5910-4b31-a758-89c62c43c8ac">

### Expected behavior

Do not throw

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/hungry-goodall-7wrkl4?file=/src/App.tsx:0-819)

<details>
  <summary>Code</summary>

  ```
  import { ComponentPropsWithoutRef, forwardRef } from "react";
  import * as Form from "@radix-ui/react-form";
  
  export function App() {
    return (
      <Form.Root>
        <p>Type a character, then delete it</p>
        <Form.Field name="">
          <Form.Control asChild>
            <MyInput />
          </Form.Control>
        </Form.Field>
      </Form.Root>
    );
  }
  
  interface Props extends Omit<ComponentPropsWithoutRef<"input">, "onChange"> {
    onChange?: (newValue: string | undefined) => void;
  }
  
  const MyInput = forwardRef<HTMLInputElement, Props>(function MyInput(
    props,
    ref
  ) {
    return (
      <input
        ref={ref}
        {...props}
        onChange={(e) => {
          if (e.target.value) {
            props.onChange(e.target.value);
          } else {
            props.onChange(undefined);
          }
        }}
      />
    );
  });
  ```

</details>

### Suggested solution

`onChange` is a standard name, used by lots of thirdparty components (and a preferred name in firstparty components for this reason!)

`<Form.Control asChild>` should not expect that a prop called `onChange` is always passed an `Event` object.

### Additional context

This came up in trying to use `ToggleGroup` as a form input.

When a selected item is clicked we want to deselect it by passing undefined or null to clear the current value.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-form    |     0.0.3    |
| React            | n/a     |     18.2.0    |
| Browser          |    Chrome     |     118.0.5993.70    |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |         |
| npm/yarn         |     pnpm    |     8.6.12    |
| Operating System |    macOS     |     14.0    |

**Comment by amir-beheshty** [comment]
I observed the same bug when adding a [custom input](https://catamphetamine.gitlab.io/react-phone-number-input/) inside `<Form.Control asChild>`.

**Comment by benoitgrelard** [comment]
`Form` is designed to operate with native events so it can properly use form features, such as validation, etc
