### ISSUE TITLE
Tooltip's arrow is separated from the tooltip's body on Windows

### ISSUE THREAD

**Issue by NoriSte** [radix-ui/primitives#2466]
### Current Behavior

The following screenshot comes directly from the [Radix UI docs first example](https://www.radix-ui.com/primitives/docs/components/tooltip) while visiting the page with Firefox on Windows.

the same problem has been reported internally (in [Preply](https://preply.com/)) also for Edge but always on Windows machines and this does not happen every time.

![unnamed](https://github.com/radix-ui/primitives/assets/173663/796023be-bc78-4928-baff-65e7231568e2)

<img width="135" alt="image" src="https://github.com/radix-ui/primitives/assets/173663/e576962a-016f-458b-afdc-69060a6548ea">

It seems quite related to #2458.

### Expected behavior

No space between the arrow and the body.

### Reproducible example

I don't have clues to reproduce it systematically, unfortunately. Like #2458, it's something random (I just tried using Browserstack to help you but I'm out of luck, I can't reproduce it there).

### Suggested solution

I don't have one, I also think it's a matter of `transform` like maybe happens for #2458 but I'm not sure.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Tooltip        | 1.0.6 (currently used in the docs)        |
| React            | n/a     | 18.2.0 (currently used in the docs)        |
| Browser          | Firefox        |  118.0.2       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | Windows        | 10.0.22621 build 22621        |

### Praise

Thank you for the hard work, we love Radix UI ❤️

**Comment by benoitgrelard** [comment]
This is probably due to some sub-pixel alignment or similar. It isn't an issue with the primitive per-se, but rather with the styling. If you want to make sure this really doesn't happen, you can probably move that arrow a tiny bit backwards so it's hidden behind by 1px.

**Comment by NoriSte** [comment]
Got it, thanks for the feedback ❤️
