### ISSUE TITLE
Dialog: Add Support multiple Triggers

### ISSUE THREAD

**Issue by henryStelle** [radix-ui/primitives#2469]
### Overview

Right now, if a Dialog contains multiple triggers, when the dialog is closed, the focus will return to the last trigger, not necessarily the trigger used. It would be nice if this was not the case and the dialog context tracked the *active* trigger as opposed to the *last* trigger.

### Example

```tsx
const [option, setOption] = useState()

return <Dialog.Root>
  <Dialog.Trigger onClick={() => setOption(1)}>Edit 1</Dialog.Trigger>
  <Dialog.Trigger onClick={() => setOption(2)}>Edit 2</Dialog.Trigger>

  {/* in the content, do something with `option` */}
</Dialog.Root>
```

### Who does this impact? Who is this for?

Not everyone, but triggering a dialog from instead a loop seems like a common use case.

### Additional context

Happy to contribute a PR!

**Comment by joaom00** [comment]
You can reuse the component instead of the instance

```tsx
const DialogContent = () => {
  return (
    <Dialog.Content>
      { ... }
    </Dialog.Content>
  )
}

const App = () => {
  return (
    <Dialog.Root>
      <Dialog.Trigger>Edit 1</Dialog.Trigger>
      <DialogContent />
    </Dialog.Root>

    <Dialog.Root>
      <Dialog.Trigger>Edit 2</Dialog.Trigger>
      <DialogContent />
    </Dialog.Root>
  )
}
```

> Not everyone, but triggering a dialog from instead a loop seems like a common use case.

Personally, I prefer the approach of reusing a component instead of the instance in a loop

**Comment by benface** [comment]
I was just going to create an issue for this. +1

**Comment by henryStelle** [comment]
> You can reuse the component instead of the instance
> 
> ```tsx
> const DialogContent = () => {
>   return (
>     <Dialog.Content>
>       { ... }
>     </Dialog.Content>
>   )
> }
> 
> const App = () => {
>   return (
>     <Dialog.Root>
>       <Dialog.Trigger>Edit 1</Dialog.Trigger>
>       <DialogContent />
>     </Dialog.Root>
> 
>     <Dialog.Root>
>       <Dialog.Trigger>Edit 2</Dialog.Trigger>
>       <DialogContent />
>     </Dialog.Root>
>   )
> }
> ```
> 
> > Not everyone, but triggering a dialog from instead a loop seems like a common use case.
> 
> Personally, I prefer the approach of reusing a component instead of the instance in a loop

This works and it moves code further down the tree, which is also helpful.

**Comment by benface** [comment]
@henryStelle – I think this feature request is still valid! 🥲 Especially if `forceMount` is used, the workaround above will render the content as many times as there needs to be triggers for it (which in my case is 50+). Supporting multiple triggers in the same `Dialog.Root` would be much better for performance.

**Comment by mbcod3** [comment]
+1

**Comment by benoitgrelard** [comment]
@benface this isn't something we will implement as it isn't compatible with the patterns the library uses.

**Comment by benface** [comment]
Understood @benoitgrelard, I handled it myself quite easily with:

```tsx
<Dialog.Trigger
  onClick={(event) => {
    setSelectedOption(option.id)
    selectedOptionTrigger.current = event.currentTarget
  }}
```
and
```tsx
<Dialog.Content
  onCloseAutoFocus={(event) => {
    if (selectedOptionTrigger.current) {
      event.preventDefault()
      selectedOptionTrigger.current.focus()
    }
  }}
```
