### ISSUE TITLE
Expose Collapsible Context

### ISSUE THREAD

**Issue by zhouzi** [radix-ui/primitives#2473]
### Overview

There are scenarios where you want to create a custom CollapsibleTrigger and need to access the open state. For example:

```jsx
import * as CollapsiblePrimitive from "@radix-ui/react-collapsible";
import { ChevronUp, ChevronDown } from "lucide-react";

export const CollapsibleTrigger = ({ children, ...props }) => {
  return (
    <CollapsiblePrimitive.Trigger {...props}>
      {children}
      {open ? <ChevronUp /> : <ChevronDown />}
    </CollapsiblePrimitive.Trigger>
  );
};
```

In the example above we would need to access the `open` state of the collapsible. Ideally that could be done by accessing the Collapsible's Context, e.g via a `useCollapsibleContext()`.

### Who does this impact? Who is this for?

It impacts users that are building design systems on top of radix ui.

**Comment by henryStelle** [comment]
As shown in the [demo](https://www.radix-ui.com/primitives/docs/components/collapsible), you can move the `open` state control outside of the Collapsible primitive.

**Comment by zhouzi** [comment]
> As shown in the [demo](https://www.radix-ui.com/primitives/docs/components/collapsible), you can move the `open` state control outside of the Collapsible primitive.

This is not possible if you have a design system that exports `CollapsibleTrigger` as a standalone component.

**Comment by benoitgrelard** [comment]
@henryStelle is correct, we encourage the use of controlled components instead.

**Comment by zhouzi** [comment]
So the solution is to pass down `open` to all the components?

```jsx
<CustomCollapsibleRoot open={open} onOpenChange={setOpen}>
    <CustomCollapsibleTrigger open={open} />
    <CustomCollapsibleContent>
        Content
    </CustomCollapsibleContent>
</CustomCollapsibleRoot>
```

That's inconsistent with the rest of Radix's API and introduces a level of duplication that can lead to undesired behavior.

**Comment by benoitgrelard** [comment]
Only the root accepts an `open` prop, why would you need to pass it to the trigger?

**Comment by zhouzi** [comment]
Imagine I have a design system based on Radix that exports three components:

```tsx
import * as CollapsiblePrimitive from https://github.com/radix-ui/primitives;
import { ChevronUp, ChevronDown } from https://github.com/lucide-icons/lucide/tree/master/packages/lucide-react;

export const CollapsibleTrigger = ({ children, ...props }) => {
  return (
    <CollapsiblePrimitive.Trigger {...props}>
      {children}
      {open ? <ChevronUp /> : <ChevronDown />}
       ^^^^ the component needs to access the open state
    </CollapsiblePrimitive.Trigger>
  );
};

// The following is simplified for the sake of the example but they could be customized as well
export const CollapsibleRoot = CollapsiblePrimitive.Root;
export const CollapsibleContent = CollapsiblePrimitive.Content;
```

Those components would be then used elsewhere in the codebase.

**Comment by benoitgrelard** [comment]
We expose data attributes to help with this, so you would be able to either:
- rotate your icon based on that state
- or show/hide a pair of icons based on that state
