### ISSUE TITLE
Can't import type PointerDownOutsideEvent

### ISSUE THREAD

**Issue by benlieb** [radix-ui/primitives#2490]
This type seems needed for `onPointerDownOutside` methods, but it is not exported in 

`@radix-ui/react-dismissable-layer/dist/index.d.ts`

`"@radix-ui/react-dismissable-layer": "1.0.4"`

I solved it by creating my own type just as it was created in the file above...

**Comment by joaom00** [comment]
You can type `onPointerDownOutside` like

```tsx
type ContentProps = React.ComponentProps<typeof SomeContentPrimitive>
type Props = {
  onPointerDownOutside: ContentProps['onPointerDownOutside']
}
```

**Comment by gregoryPacific** [comment]
This worked for me:

`type PointerDownOutsideEvent = CustomEvent<{
  originalEvent: PointerEvent;
}>;
`
