### ISSUE TITLE
Improvement proposal for Checkbox "indeterminate" example

### ISSUE THREAD

**Issue by ladislasdellinger** [radix-ui/primitives#2494]
### Relevant Radix Component(s)

[Checkbox component - Indeterminate state example](https://www.radix-ui.com/primitives/docs/components/checkbox#indeterminate)

### Examples from other doc sites

In the example for the indeterminate state of the `Checkbox` component, there is the following code:

```jsx
<Checkbox.Indicator>
  {checked === 'indeterminate' && <DividerHorizontalIcon />}
  {checked === true && <CheckIcon />}
</Checkbox.Indicator>
```

The `checked === true` breaks the component when using it as uncontrolled, because `checked` as no value.
However, as the `Indicator` is already rendered when the checkbox is in a checked or indeterminate state, using a ternary would fix this issue:

```jsx
<Checkbox.Indicator>
  {checked === 'indeterminate' ? <DividerHorizontalIcon /> : <CheckIcon />}
</Checkbox.Indicator>
```

**Comment by benoitgrelard** [comment]
You can't use an indeterminate checkbox in an uncontrolled way.
