### ISSUE TITLE
Toast + (NextJS) SSR / Static Generation

### ISSUE THREAD

**Issue by DanielRoeven-Intunio** [radix-ui/primitives#2514]
### Relevant Radix Component(s) / Documentation

[Toast - Radix Primitives](https://www.radix-ui.com/primitives/docs/components/toast#root)
[Server side rendering](https://www.radix-ui.com/primitives/docs/guides/server-side-rendering)

The server side rendering docs page states that both SSR and Static Generation should be able to be used with all primitives.

I've tried to implement the Toast primitive on a NextJS site with statically generated pages. As the Toast documentation states, the `<Toast.Provider/>` typically wraps the application. This doesn't work with static generation, however. It's to be expected that it doesn't work, as the Toast Provider uses `useState` internally, which can only be used in `use client` components.

The Toast primitive works flawlessly as long as you include the provider in a `use client` component. Maybe the docs should be updated to reflect this? It's not a big deal, but it led me astray for a little while trying to reconcile the contradictory statements 🙂

**Comment by joaom00** [comment]
Hey, thanks for opening but Server side rendering != React Server Components. As all components have interactivity they need the 'use client' directive but even so I think it would be interesting to support RSC by default (adding 'use client' at the top of the file?) [There is already an open PR to add this](https://github.com/radix-ui/primitives/pull/2188)

**Comment by DanielRoeven-Intunio** [comment]
Hi! Happy to close if question irrelevant or create a PR for the docs (are they hosted in this repo?). Very open to the idea of me misunderstanding! 🙂 

Not sure what you mean by SSR != RSC. I think I understand the difference, but what I don't understand is how the `<Toast.Provider>` should be used on a statically rendered page at the root of the application. (Which the docs imply is possible?)

If you add the `<Toast.Provider>` component to a statically rendered page or layout, it won't compile and throw errors instead. If you add the `<Toast.Provider>` component to a component with the `use client` directive, it all works fine. This is confusing, because the docs also (reasonably) state that the `<Toast.Provider>` should wrap the application. This seems contradictory?

Also not sure what the PR you linked helps with my issue. I suppose it would make the error I'm experiencing more clear, in any case!

I might be missing a light-bulb moment — what am I misunderstanding? 🙂

**Comment by joaom00** [comment]
My knowledge is not very deep but I will try to explain what I know :smile: 

By default in Next, all components are server components and therefore components cannot use any client features like `Context`, which is used in `Toast.Provider`. But even if the [component has 'use client' it can still get SSR'd to HTML](https://github.com/reactwg/server-components/discussions/4). [Using composition patterns you can interleave SC into CC](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers).

> Also not sure what the PR you linked helps with my issue. I suppose it would make the error I'm experiencing more clear, in any case!

The PR will just add 'use client' directive to the components so you don't have to

**Comment by DanielRoeven-Intunio** [comment]
Thanks for the reply and explanation, I think I follow!

To sum up my misunderstanding:
1. ‘use client’ components can in fact be used near the root / wrap the application. 
2. It happens to be ‘createContext’ rather than ‘useState’ that’s causing the error. But this is less important, because ‘useState’ would just as well have caused an error (at least until the linked PR would be in place).

I’ll have a go ant it and see if I succeed in implementing the Toast Provider, while maintaining Static Generation. If I succeed I’ll try to formulate a succinct description of necessary steps that could be added to Radix’ Server Side Rendering docs, if that would be appreciated?

Otherwise, happy to close the issue as you see fit. Thanks for the help!

**Comment by joaom00** [comment]
> ‘use client’ components can in fact be used near the root / wrap the application.

You can, but I don't know if it's the best strategy.

> It happens to be ‘createContext’ rather than ‘useState’ that’s causing the error. But this is less important, because ‘useState’ would just as well have caused an error (at least until the linked PR would be in place).

Yeah, actually `Toast.Provider` uses `createContext`, `useState` and `useRef` (all client features)

> I’ll have a go at it and see if I succeed in implementing the Toast Provider, while maintaining Static Generation.

In the Next.js docs I linked, there is the recommended approach to use third-party context providers in RSC. You can do the following:

```tsx
// toast-provider.tsx
'use client'

export const ToastProvider = ({ children }: { children: React.ReactNode }) => {
  return <Toast.Provider>{children}</Toast.Provider>
}

// layout.jsx
import { ToastProvider } from './toast-provider'
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <ToastProvider>
          // Now you can render RSC here...
          {children}
        </ToastProvider>
      </body>
    </html>
  )
}
```

> I’ll try to formulate a succinct description of necessary steps that could be added to Radix’ Server Side Rendering docs, if that would be appreciated?

You are very welcome to suggest improvements to the Radix Primitives documentation. I believe that the documentation about SSR is not wrong because in fact, the Radix primitives support SSR, what it does not support is RSC out-of-box, that is, you have to re-export the components with 'use client'. Maybe adding a little warning about RSC and linking to the Next.js documentation on composition patterns?

[This is the repository](https://github.com/radix-ui/website) that contains the documentation. Feel free to open an issue there so we can continue discussing this :slightly_smiling_face:

**Comment by vladmoroz** [comment]
All components that need `'use client'` now have that in the latest RC versions
