### ISSUE TITLE
Z index on scrollable content with switch

### ISSUE THREAD

**Issue by jscastanos** [radix-ui/primitives#2516]
### Current Behavior
Using Switch in a scrollable container gets into a weird z-index order against a sticky element. 

![image](https://github.com/radix-ui/primitives/assets/37854603/7b081830-7c6e-450b-b811-fdc2de1188fa)

### Expected behavior
The switcher should be behind the sticky element

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/switch-z-index-425thk)

### Suggested solution

n/a

### Additional context

I tried adding a `z-index: 10 ` to the sticky container and it works. but the hover card that I got will also render behind the sticky div.

![image](https://github.com/radix-ui/primitives/assets/37854603/9cefabc0-62c4-4a4e-a23c-b82dd32f37c0)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-hover-card   |   1.0.7      |
| Radix Package(s) |     @radix-ui/react-switch |    1.0.3    |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by IdoBouskila** [comment]
Hi! Its not about the `Switch` component, it's about the `position: relative;` & `position: sticky` properties.
The `sticky` element creates a stacking context, so all elements inside can't be placed relative to elements outside it. You have to adjust the z-index of the sticky container so it's above the `relative` element container (The `Switch` Component).

**Comment by jscastanos** [comment]
> Hi! Its not about the `Switch` component, it's about the `position: relative;` & `position: sticky` properties. The `sticky` element creates a stacking context, so all elements inside can't be placed relative to elements outside it. You have to adjust the z-index of the sticky container so it's above the `relative` element container (The `Switch` Component).

Yeah I added a z-index to the sticky which fixes the switch. but then I have a HoverCard on the sticky column which makes the HoverCard  behind the sticky column. I'm not sure where to add the z-index to the HoverCard. 

Did I missed something here?

**Comment by jscastanos** [comment]
> Hi! Its not about the `Switch` component, it's about the `position: relative;` & `position: sticky` properties. The `sticky` element creates a stacking context, so all elements inside can't be placed relative to elements outside it. You have to adjust the z-index of the sticky container so it's above the `relative` element container (The `Switch` Component).

I have another go and I figured it out. So yup, z-index it is. So the missing piece is making sure that the `HoverCard.Content` is set to `asChild` so you can set the `z-index` to your children

![image](https://github.com/radix-ui/primitives/assets/37854603/6eb27251-dfec-4201-83e7-7ca0b9ecbc69)
