### ISSUE TITLE
<tbody> cannot appear as a child of <div> and <div> cannot appear as a child of <table>

### ISSUE THREAD

**Issue by pavelgromyko** [radix-ui/primitives#2517]
Please take a look at the schematic structure of my table. I removed all unnecessary stuff for ease of reading. As you can see, there is a header and there is a body. Only the body is wrapped in ScrollArea      

    <table>
        <thead>
          <tr>
            <th></th>
            <th></th>
          </tr>
        </thead>
            <ScrollArea.Root>
              <ScrollArea.Viewport>
                <tbody>
                    <tr>
                      <td></td>
                      <td></td>
                    </tr>
                </tbody>
              </ScrollArea.Viewport>
              <ScrollArea.Scrollbar/>
            </ScrollArea.Root>
      </table>

And so, when I go to the page with this table, I receive two warnings in the console:

1. Warning: validateDOMNesting(...): div cant appear as a child of table.
2. Warning: validateDOMNesting(...): tbody cannot appear as a child of div.

If I remove ScrollArea from the table, then the warnings disappear. But ScrollArea is very important to me for moving through long tables.

Tell me how can I get rid of these warnings?

**Comment by IdoBouskila** [comment]
Hi! Those warnings appears because you are trying to render a non-valid HTML.
The `ScrollArea` component (from `Radix-UI`) is an element typed `div`.
1. Nesting divs (which is what `<ScrollArea />` transpiles to) inside `table` element is forbidden in HTML.
2. Same here, `tbody` cannot be directly inside `div` (`<ScrollArea />` ).

**Comment by pavelgromyko** [comment]
@IdoBouskila Thanks, but tell me, how can I avoid these warnings?

**Comment by IdoBouskila** [comment]
> @IdoBouskila Thanks, but tell me, how can I avoid these warnings?

Hm, you can use `asChild` prop to change the default rendered element (`div`) for the one passed as a child.
but I don't think that you can use this in both `ScrollArea.Viewport` and `ScrollArea.Root`, because react expect to receive as **single** element.
So I don't really see how to get rid of those both warning with this JSX structure.
Can you explain what you are trying to achieve? maybe there is a better structure to achieve what you're trying.

**Comment by pavelgromyko** [comment]
@IdoBouskila I have a table with a header and a body (without footer). The table has exactly the same structure that I indicated in the code above, I just removed the styles and map. As you can see from the code, I wrap only the body of the table in <ScrollArea.Root> and <ScrollArea.Viewport>, so that the user can scroll only the body (and the header should remain in place).

Yes, I can make a scroll without using <ScrollArea.Root> and <ScrollArea.Viewport> , and using pure CSS, but the site already has several places where ScrollArea is used (without tables, just a list) and I would like everything to be in one style

**Comment by IdoBouskila** [comment]
@pavelgromyko  I'm pretty sure that it's impossible to do this with the structure you mentioned. I would use a pure CSS for this scenario.

**Comment by pavelgromyko** [comment]
@IdoBouskila You can share the code with pure css that will help solve this problem?

**Comment by IdoBouskila** [comment]
[](url)

> @IdoBouskila You can share the code with pure css that will help solve this problem?

If you want the header to remain in place, you can structure your code like this:
```JSX
export default () => (
  <ScrollArea.Root>
     { /* Place your header here (before `ScrollArea.ViewPort`) */ }
    <ScrollArea.Viewport />
    <ScrollArea.Scrollbar orientation="horizontal">
      <ScrollArea.Thumb />
    </ScrollArea.Scrollbar>
    <ScrollArea.Scrollbar orientation="vertical">
      <ScrollArea.Thumb />
    </ScrollArea.Scrollbar>
    <ScrollArea.Corner />
  </ScrollArea.Root>
);

```
Here is an example:
https://codesandbox.io/p/devbox/recursing-meninsky-fgy6kz?file=%2FApp.jsx%3A15%2C1

**Comment by IdoBouskila** [comment]
> @IdoBouskila Thank you, but as you can see, the scroll is located along the entire height of the table (including the header). But I need the scroll to be located only within the height of the body

Ah, I understand. The Idea of the `ScrollArea` component is to augment native scroll functionality for custom styling, so if you don't want the scrollbar to be located on some element, place it outside.

I updated the CSB, see bellow:
https://codesandbox.io/p/devbox/recursing-meninsky-fgy6kz?file=%2Fstyles.css%3A12%2C17

**Comment by pavelgromyko** [comment]
@IdoBouskila  The thing is, if I try to add thead to the place where you designated "Put Your Header Here", then I still get the same warnings in the console. Could you demonstrate your approach with the code that I have in my first message?
