### ISSUE TITLE
Add params to control state of Accordion

### ISSUE THREAD

**Issue by nexusprime-here** [radix-ui/primitives#2520]
### Overview
I would like to request the addition of parameters to control the state of the Accordion in the `@radix-ui/react-accordion` package. Currently, the AccordionTrigger is the only way to toggle the state of an AccordionItem. It would be helpful to have the ability to control the state externally, allowing for more flexibility in managing the accordion's behavior.

### Who does this impact? Who is this for?
This feature would benefit developers who are using the `@radix-ui/react-accordion` package and need more control over the state of the accordion. It would allow them to programmatically open or close accordion items based on specific conditions or user interactions.

Thank you for considering this feature request!

### Example
```tsx
<Accordion.Item onStateChange={(state) => setAccordionState(state)} state={accordionState}>
     ...
</Accordion.Item>
```

**Comment by joaom00** [comment]
You can control `Accordion` with `value` and `onValueChange` props
