### ISSUE TITLE
manually setting sideOffset is a pain if my dropdown menu items length is unknown

### ISSUE THREAD

**Issue by ming2024** [radix-ui/primitives#2526]
## Question

I used sideOffset to adjust the left position of DropdownMenu.Content, but it's not a long term solution as the item list is from the api. Why radix don't force the DropdownMenu start from left: 0?

<img width="469" alt="image" src="https://github.com/radix-ui/primitives/assets/111698568/cf37b388-b48d-4759-8533-84b6612c7cf8">

**Comment by joaom00** [comment]
You can use the `align=start` prop on `Content`
