### ISSUE TITLE
Open DropdownMenu with two different buttons

### ISSUE THREAD

**Issue by pavelgromyko** [radix-ui/primitives#2531]
I have a very simple dropdown menu. By clicking on the NewIcon button, the user sees a drop-down menu. Everything is simple here.        

        <DropdownMenu.Root open={isOpen} onOpenChange={setIsOpen}>
          <DropdownMenu.Trigger>
              <NewIcon/>
          </DropdownMenu.Trigger>

          <DropdownMenu.Portal forceMount>
                  <DropdownMenu.Content>
                 ........here some components
                  </DropdownMenu.Content>
          </DropdownMenu.Portal>
        </DropdownMenu.Root>

However, I would like to also call this dropdown menu with another button (which is located in another component) on the same page.
For example, below is another component that renders the "Edit information" button. Tell me how to click on this button to open the dropdown menu

       <div>           
        <Button>
           Edit information
        </Button>
      <div>

**Comment by joaom00** [comment]
You can create a content component to reuse across multiple buttons

```tsx
const SomeDropdownContent = () => {
              <DropdownMenu.Content>
             ........here some components
              </DropdownMenu.Content>
}

//

    <DropdownMenu.Root open={isOpen} onOpenChange={setIsOpen}>
      <DropdownMenu.Trigger>
          <NewIcon/>
      </DropdownMenu.Trigger>

      <DropdownMenu.Portal forceMount>
          <SomeDropdownContent />
      </DropdownMenu.Portal>
    </DropdownMenu.Root>

//

    <DropdownMenu.Root>
      <DropdownMenu.Trigger asChild>
          <Button>
             Edit information
          </Button>
      </DropdownMenu.Trigger>

      <DropdownMenu.Portal forceMount>
          <SomeDropdownContent />
      </DropdownMenu.Portal>
    </DropdownMenu.Root>
```
