### ISSUE TITLE
Component height depending on content length

### ISSUE THREAD

**Issue by pavelgromyko** [radix-ui/primitives#2534]
My goal: adjust the height of the element depending on the content.

As we see in the example below, the height of ScrollArea.Root is h-[225px] and everything works fine if the length of the Array === 50. But if we change the length of the Array === 1, then we will see how the height of the ScrollArea.Root does not change (lots of useless white background).

https://codesandbox.io/p/sandbox/nervous-mopsa-vnr7nt

Tell me how in this case you can change the height depending on the length of the Array. That is, yes, I am happy with a height of 225px if the Array has many elements (50 by default), but if the number of elements in the Array is made 1 or 2, then you can see that there is white space left, which I would like to get rid of.

**Comment by joaom00** [comment]
You can set `max-h-[225px]` on Viewport and `h-full` on Root

**Comment by pavelgromyko** [comment]
@joaom00 Yes, its work,  thank you
