### ISSUE TITLE
[Select] `ref` to collection is undefined

### ISSUE THREAD

**Issue by pawelshopstory** [radix-ui/primitives#2535]
## Bug report

I've tried to replicate behaviour in our app as much as possible. We've select built using `@radix-ui/react-select` which allows to select an option that makes an input control visible which allows user to enter custom value. When user leaves the input, we run function which adjust entered text value. It works perfectly fine until `ScrollUp/DownButton` is starting to be visible because of smaller viewport or list being rendered near the top or bottom of the viewport.

### Current Behavior

If you focus the input and right after you try to open the select and the `ScrollUp/DownButton` can be rendered it's going to throw because the ref to collection's container is `undefined`.

### Expected behavior

I expect the component to not throw.

### Reproducible example

https://codesandbox.io/s/crazy-dream-mlrwc2

1. Select option between 40-50 to make sure the scroll up button will be rendered.
2. Focus the input
3. Click on the select's trigger.

### Suggested solution

I didn't dig into your source code so can't tell right now.

### Additional context

[N/A]

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    `@radix-ui/react-select`     |  `2.0.0`   |
| React            | n/a     |     `18.3.0-canary-9377e1010-20230712` (Next.js app)    |
| Browser          |    Brave     |     `v1.60.118`    |
| Assistive tech   |         |         |
| Node             | n/a     |     `v16.20.0`    |
| npm/yarn         |    `pnpm`     |    `8.8.0`    |
| Operating System |    MacOS    |    Sonoma  (14.1.1 (23B81))   |

**Comment by benj-dobs** [comment]
I believe this is the same underlying issue as #1795

**Comment by pawelshopstory** [comment]
@benj-dobs Yes, that definitely is the same problem. I will close my issue in favour of that one.
