### ISSUE TITLE
Slider in form prevents form onSubmit

### ISSUE THREAD

**Issue by themre** [radix-ui/primitives#2541]
### Current Behavior

If I have a form with input and slider, it prevents form submission (hit ENTER in input):

https://codesandbox.io/s/radix-ui-slider-abstracted-example-forked-3tjdsm?file=/src/App.js

### Expected behavior

Form should fire `submit` on input enter key.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-ui-slider-abstracted-example-forked-3tjdsm?file=/src/App.js)

### Your environment

MacOS, Chrome

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-slider     |     1.1.2    |

**Comment by benoitgrelard** [comment]
Going to group this with #1993 as it relates to the same thing, namely we should see if we can add compatibility with "implicit form submission".
