### ISSUE TITLE
[Collapsible] Collapsible.Content forceMount with animations shows content when default closed

### ISSUE THREAD

**Issue by longzheng** [radix-ui/primitives#2546]
### Current Behavior

I need to use the `<Collapsible.Content>` with `forceMount` because the children contains some form input fields that need to be submitted as part of a `<form>` to the server.

I am also trying to animate the `Collapsible.Content` opening and closing using the slide up/down animation ([as recommended by the documentation](https://www.radix-ui.com/primitives/docs/components/collapsible#animating-content-size)).

However when I apply `forceMount` with a default closed state `defaultOpen={false}`, the initial state rendered is not right. It will show all the contents.

https://github.com/radix-ui/primitives/assets/484912/b9d48e00-c21e-489a-8e14-55b302bcea16

I tried fixing this by adding `height: 0` to the CSS `data-state="closed"`

```css
.CollapsibleContent[data-state="closed"] {
  animation: slideUp 300ms ease-out both;
  height: 0;
}
```

Whilst this works, the opening animation then does not work. I assume because the library cannot measure the height of the content and so `--radix-collapsible-content-height` is not set.

https://github.com/radix-ui/primitives/assets/484912/e8da55a0-c3db-4cdd-bf8f-f2a648612d24

### Expected behavior

When using `forceMount` with animations, it should not show content when default closed.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/vigilant-jones-rj67x2?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-collapsible       |  1.0.3       |
| React            | n/a     |    18.2.0     |
| Browser          |   Chrome      |  119.0.6045.159       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by joaom00** [comment]
Hey @longzheng, `forceMount` prop should only be used to delegate animations to third-party libraries. Using `forceMount` Radix will not handle the animations so it doesn't work very well

It seems like you need to control how the `Content` is mounted/unmounted, which has been previously proposed/discussed [here](https://github.com/radix-ui/primitives/issues/1155) and [here](https://github.com/radix-ui/primitives/discussions/855).

**Comment by longzheng** [comment]
@joaom00 Thanks, that makes sense. Will look into a custom `Content` component.
