### ISSUE TITLE
Select primitive freezes page with preact

### ISSUE THREAD

**Issue by hapaxlife** [radix-ui/primitives#2557]
## Bug report

I try to port Radix UI to [preact](https://preactjs.com/) & Fresh. All primitive work except **Select**

See :

[Repo](https://github.com/hapaxlife/test-fresh-radix-ui)
[Live page](https://radixui.hapaxlife.com/test)

### Current Behavior

Every components work except Select which freezes the page (getItems has no element => error)

### Expected behavior

No freeze

### Reproducible example

The code with React
https://codesandbox.io/p/sandbox/select-radixui-react-klhjfn

The code with Preact : I have only change React.forwardRef to import { forwardRef } from "preact/compat";
In Fresh, I made alias/external to react
The repo to test
https://github.com/hapaxlife/select-radixui-preact

### Suggested solution

@andrewiggins offers a solution to make it compatible with preact. The change will also improve performance of the primitive.

See :
https://github.com/preactjs/preact/issues/4222#issuecomment-1835386361

**Comment by palpfiction** [comment]
Hello @hapaxlife! Is this working now?

**Comment by hapaxlife** [comment]
Hi,

No it is not working. As I have no comment,  I cleaned the issue
