### ISSUE TITLE
Dialog fails to close upon multiple touch or scrolling in mobile screen

### ISSUE THREAD

**Issue by Efrana23** [radix-ui/primitives#2574]
### Current Behavior
When the dialog is open on a mobile screen, it fails to close upon multiple touches or scrolling outside of the dialog.

### Expected behavior
When dialog is open on mobile screen it should close upon multiple touch or scrolling outside of the dialog.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |     1.0.2    |
| React            | n/a     |       18.2.0  |
| Browser          |      Chrome   |      Version 119.0.6045.199 (Official Build) (arm64)   |
| Assistive tech   |         |         |
| Node             | n/a     |    18.11.11     |
| npm/yarn         |    yarn     |   1.22.19      |
| Operating System |     Mac    |         |

**Comment by Efrana23** [comment]
Uploading Screen Recording 2023-12-13 at 1.28.10 PM.mov…

**Comment by Efrana23** [comment]
https://github.com/radix-ui/primitives/assets/152844396/a59805e5-6fbd-4744-97cc-774d6c6fd1b1

**Comment by benoitgrelard** [comment]
I can't reproduce this using the dialog example on our website directly on my iPhone, it closes after just one tap, nor with the emulator in Chrome.
