### ISSUE TITLE
Tooltip doesn't react on touch

### ISSUE THREAD

**Issue by tomasfrancisco** [radix-ui/primitives#2589]
### Current Behavior

Tooltip doesn't open on mobile when on touch.

### Expected behavior

Tooltip should open on touch when in mobile

### Reproducible example

[CodeSandbox - Tooltip Demo](https://codesandbox.io/p/sandbox/focused-glade-dzgqt5?file=%2Fsrc%2FApp.tsx%3A6%2C10)

### Suggested solution

Perhaps tooltip should be aware of touch event in the event of being used in a touch device.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          | Edge        |   120.0.2210.61      |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   MacOS      |    14.1.1     |

**Comment by benoitgrelard** [comment]
This is by design. See https://github.com/radix-ui/primitives/issues/955#issuecomment-960610209

**Comment by szamanr** [comment]
that's a bad design. when implementing a custom tooltip using CSS ("invisible" + "visible" on hover), it works fine on mobile. i was expecting the same from this component and thus missed a bug.

i understand that it's problematic for buttons, where clicking is supposed to trigger an action, not show the tooltip. but tooltips are not only used on buttons.
