### ISSUE TITLE
Tooltip: add features and address bugs

### ISSUE THREAD

**Issue by chaance** [radix-ui/primitives#26]
From Colm's notes in Notion:

- Support multi-line + children. Max-width prop?
- Prevent opening on focus when focus comes from clicks on other elements)

- Also the bug Jenna mentioned where it triggers on click sometime

**Comment by kylemh** [comment]
One request I would add is the ability to have the tooltip render immediately on hover or the ability to control the delay in milliseconds!

**Comment by benoitgrelard** [comment]
Closing in favour of #543
