### ISSUE TITLE
[Scroll Area] Ability to pin scrolling to bottom

### ISSUE THREAD

**Issue by KingMatrix1989** [radix-ui/primitives#2610]
## Feature request
Somewhere like a chat list, it is required to pin the scroll to the bottom by default (when the page loads).

### Overview

Currently, seems the **Scroll Area** component wraps the scrollable content with a **DIV** and the developer does not have any access to customize it.

```
<div style"min-width: 100%; display: table;"> // adds automatically by the Primitive component
///
</div>
```

### Who does this impact? Who is this for?
All users

### Additional context

It would be great if one of the following features were provided:
A - Ability to access the mentioned DIV (something like **ScrollArea.Content**)
B - Providing a new boolean property named "pinToBottom".

In case B we can use the following CSS trick:

![image](https://github.com/radix-ui/primitives/assets/12100097/c9db2d87-74c7-45d2-a5f5-b795dfe68e5d)

**Comment by oyal** [comment]
Hello, how did you solve it in the end?

**Comment by alex-kim-dev** [comment]
[This comment](https://github.com/radix-ui/primitives/issues/926#issuecomment-1015279283) shows an example of how to apply styling to that `div`, so adding 100% height like this:

```css
.viewport {
  /* ... */

  > div[style] {
    block-size: 100%;
  }
}
```

with a flex container inside that pins the items to the bottom did the job.
