### ISSUE TITLE
[Menu] How to implement an Inline Menu?

### ISSUE THREAD

**Issue by theo-staizen** [radix-ui/primitives#2622]
## Question

Is there a way to use one of the menu components (ContextMenu, DropdownMenu) as an inline menu, e.g in a sidebar or in a dialog or any container we want? Trying to use the *MenuContent component of one of the above, just ends up in an error.

I know there is an internal [Menu component](https://github.com/radix-ui/primitives/blob/main/packages/react/menu/src/Menu.tsx) which implements a lot of the common functionality of those 2 components, but it is internal therefore not for public use and it still needs to be positioned using popper, so we cannot use it inline.

If we can separate the positioning logic from the menu logic (i.e keyboard navigation, focus, hover, checkbox/radio items, separator, etc) , we can cater for an inline menu use case at the same time.

Submenus might prove a bit more challenging, because instead of being automatically positioned, they are most likely rendered inline, like an accordion of menu items.

**Comment by benoitgrelard** [comment]
This isn't something we currently cater for.
