### ISSUE TITLE
[HELP] Select component fires onValueChange twice (second event had value '')

### ISSUE THREAD

**Issue by mad-raccoon** [radix-ui/primitives#2624]
## Question
Hello guys, 

I just noticed that using the Select component inside a `<form>` is causing the `onValueChange` of the select to be fired twice:
1. fires with the correct value
2. fires with an empty value ('')

This causes the component to no be update, since the second event is cleaning the correct value ... 

How can i fix this issue ?

Here is a [sandbox](https://codesandbox.io/p/sandbox/agitated-sky-rxjvdl?file=%2Fsrc%2FApp.js%3A13%2C21&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqpakqv200063b6m24j4u02w%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqpakqv200023b6mcdrh104q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqpakqv200033b6ma2sannpq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqpakqv200053b6m4hf7a1ue%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqpakqv200023b6mcdrh104q%2522%253A%257B%2522id%2522%253A%2522clqpakqv200023b6mcdrh104q%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxyqbq400023b6msza6lvq7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqxyqbq400023b6msza6lvq7%2522%257D%252C%2522clqpakqv200053b6m4hf7a1ue%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqpakqv200043b6mdd1h3hzj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqpakqv200053b6m4hf7a1ue%2522%252C%2522activeTabId%2522%253A%2522clqpakqv200043b6mdd1h3hzj%2522%257D%252C%2522clqpakqv200033b6ma2sannpq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqpakqv200033b6ma2sannpq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.941915227629508%257D) with both scenarios

**Comment by mad-raccoon** [comment]
posting the problem for whoever comes after:

we need to use the <Select.ItemText> inside the <Select.Item> for this to work

**Comment by mad-zephyr** [comment]
OMG, I spent for this all my day! Thanks for solution!
