### ISSUE TITLE
Force dropdown sub menu to open on left

### ISSUE THREAD

**Issue by github-org-account** [radix-ui/primitives#2628]
We have a Radix nested dropdown and we want the submenus to always open to the left. The default seems to be to the right. I have tried, amongst other things, [data-side] but haven't gotten it to work. Is there a Radix-based way to do this? I also need this to be accessible, and so the left arrow key must open the menu as well.

**Comment by benoitgrelard** [comment]
@joaom00 is correct here. Whilst we could allow users to choose the "side" to open on, it would completely mess with user's expectations of how dropdown submenus are supposed to work as it is inherently linked to the reading-direction and is learnt behaviour from operating systems. For this reason, I don't think we will make any changes here.

If someone has a compelling example that I can't debunk, I'm happy to reconsider but at the moment, I think this would make it too easy to completely destroy user expactations.

**Comment by jmisur** [comment]
For example, Slack has full width content and all dropdown submenus on the right therefore open to the left. In no way is such behavior destroying user expectations, it's just the way it is.
![Screenshot 2024-10-18 111057](https://github.com/user-attachments/assets/1f492380-b411-46d7-98f8-e5915fb58e0f)

Let's say I don't have full-width content, however I want similar menu always stay inside the content and don't go out of borders to the right. 
Imo this should be the choice of the developer.
