### ISSUE TITLE
Open Tooltip when TooltipTrigger is clicked

### ISSUE THREAD

**Issue by huzaifahj** [radix-ui/primitives#2632]
It was mentioned here (https://github.com/radix-ui/primitives/issues/2029#issuecomment-1811656201) a way to open tooltips when the trigger is clicked. This should ideally be implemented into the API as an option.

Also, currently if the user clicks on a tooltip immediately, the tooltip isn't even shown after the expected delay.

**Comment by joaom00** [comment]
> Also, currently if the user clicks on a tooltip immediately, the tooltip isn't even shown after the expected delay.
When the tooltip trigger is clicked the tooltip is closed

> It was mentioned here (https://github.com/radix-ui/primitives/issues/2029#issuecomment-1811656201) a way to open tooltips when the trigger is clicked. This should ideally be implemented into the API as an option.

What's your usecase?

**Comment by mikkelwf** [comment]
> > Also, currently if the user clicks on a tooltip immediately, the tooltip isn't even shown after the expected delay.
> 
> When the tooltip trigger is clicked the tooltip is closed
> 
> > It was mentioned here ([#2029 (comment)](https://github.com/radix-ui/primitives/issues/2029#issuecomment-1811656201)) a way to open tooltips when the trigger is clicked. This should ideally be implemented into the API as an option.
> 
> What's your usecase?

I have a usecase where the trigger button should be able to be clicked individually of the visibility og the tooltip.

* trigger click: does not influence tooltip visibility
* trigger hover/focus: opens tooltip
* trigger unhover/blur: closes tooltip

**Comment by benoitgrelard** [comment]
This is achievable with the current API.

We have an example in our storybook: https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.stories.tsx#L659-L687

I will add an example in the docs as this question comes up once in a while.
