### ISSUE TITLE
Add Backspace Key Functionality in Type-Ahead Support

### ISSUE THREAD

**Issue by anatolzak** [radix-ui/primitives#2636]
### Overview

When using typeahead in native macOS select menus, you can start typing to highlight an item that begins with the typeahead input. This is what Radix has implemented as well. 

However, in native macOS select menus, you can press the backspace key to reset the typeahead input. The Radix Select component doesn't support this.

Since Radix's mission is to build high quality and fully accessible components, I believe Radix should mirror the native typeahead functionality of native macOS select menus, which includes the backspace key functionality. This is what users relying on keyboard navigation expect since this is the precedent in native select menus.

Here is the backspace key functionality demonstrated on macOS Chrome select menu

https://github.com/radix-ui/primitives/assets/53095479/0691ca12-0db5-4a4b-ab8a-93e46bd233fb

And here is the backspace key functionality not implemented with Radix Select

https://github.com/radix-ui/primitives/assets/53095479/d4987443-3dde-4b4c-bfbf-459251283321

### Who does this impact? Who is this for?

This impacts anyone who uses their keyboard to navigate select menus.

**Comment by anatolzak** [comment]
I opened a pull request adding this feature here https://github.com/radix-ui/primitives/pull/2637

**Comment by anatolzak** [comment]
I opened a pull request adding delete key functionality to the Menu component https://github.com/radix-ui/primitives/pull/2638

**Comment by benoitgrelard** [comment]
Hi @anatolzak, I don't believe this is a feature in the native macOS select or at least I can't get it to behave as you suggest.
Are you sure this is not just a timing thing with how you're testing it? ie. with both native and ours the buffer resets after some time.

The only thing I notice that the macOS one seems to do is when you press backspace before anything else has been typed, it will move the highlight from the current to the first item in the list.

**Comment by anatolzak** [comment]
@benoitgrelard it seems like this was the behavior in macOS Ventura, but was changed in macOS Sonoma.

**Comment by benoitgrelard** [comment]
Ok, I think we can drop it then.
