### ISSUE TITLE
Cannot find module '@radix-ui/react-accordion' or its corresponding type declarations.

### ISSUE THREAD

**Issue by LauratHaaga** [radix-ui/primitives#2639]
Hi,

I'm currently using shadcn component lib and I'm having this issue "Cannot find module '@radix-ui/react-accordion' or its corresponding type declarations.".

The setup of course is done by shadcn via CLI, I only imported it. 

I tried to remove *@radix-ui/react-accordion* and add it again but it didn't work,
can someone please suggest any fix!

Thanks.

I'm using:
- yarn
- @radix-ui/react-accordion - 1.1.2
- TypeScript: 4.9.5

**Comment by DeanLabrysTech** [comment]
+1

**Comment by Samy572** [comment]
Hi,
to solve this problem, just install the missing module, with yarn, npm or pnpm 
(npm i @radix-ui/react-accordion)

**Comment by benoitgrelard** [comment]
This isn't an issue with the primitives library.

**Comment by alexandre-kakal** [comment]
if you setup with shadcn CLI, you need to manually install the radix component (faced the same issue with react-toast)

`npm i @radix-ui/whateverComponentYouWant`
