### ISSUE TITLE
[Tooltip] Extra horizontal whitespace when using `text-wrap: balance`

### ISSUE THREAD

**Issue by bengry** [radix-ui/primitives#2647]
## Bug report

When `text-wrap: balance` is used inside a `Tooltip`, there's lots of extra white-space on the right.

### Current Behavior

Lots of extra whitespace to the right of the text.

![CleanShot 2024-01-10 at 19 44 09@2x](https://github.com/radix-ui/primitives/assets/260431/d2c8a85c-57e9-4026-b0c5-4246bff4156f)

### Expected behavior

The text should be (nearly) stuck to the edge of the tooltip content, with padding etc. as defined by the `<Tooltip.Content>`'s style. No weird extra whitespace.

### Reproducible example

https://codesandbox.io/p/sandbox/thirsty-snow-93gqm5

### Additional context

This might be a bug with the underlying [Floating UI](https://floating-ui.com/) library, but I'm not entirely sure. Regardless, maybe some changes could be made on Radix's side to fix it.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `@radix-ui/react-tooltip`    |      v1.0.7   |
| React            | n/a     |    18.2.0     |
| Browser          |   Brave      |   v1.61.114 (Chromium: 120.0.6099.199)      |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |      20.10.0   |
| npm/yarn         |     yarn     |      v4.0.2   |
| Operating System |     macOS    |    14.2.1     |

**Comment by bengry** [comment]
> this isn't a bug witch the tooltip component but this is juste how text-wrap work since you will get the same render with any html element like div, p, span ... I think you wanted to use text-align: justify; instead

Got it, thanks.
`text-align: justify` isn't what I want, since it spreads the text to fit the available area. I want the inverse. i.e. something like this:
![CleanShot 2024-01-27 at 12 29 50@2x](https://github.com/radix-ui/primitives/assets/260431/de0c6ecf-8819-4622-8d45-6cc254f215fd)

**Comment by benoitgrelard** [comment]
I believe @kal07 is correct, this is just how this CSS property works.
