### ISSUE TITLE
Checkbox shadcn i want to event native from checkbox ? how to get it

### ISSUE THREAD

**Issue by phongvudz** [radix-ui/primitives#2658]
### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
This issue is basically empty.
