### ISSUE TITLE
`Popover` don't open when combined with `Tooltip`

### ISSUE THREAD

**Issue by piszczu4** [radix-ui/primitives#2663]
I tried to make `TooltipButton` and `PopoverButton` components to nicely nest them. However, Popover won't open when doing it. Here is my demo: https://codesandbox.io/p/sandbox/tooltip-popover-forked-dh3zq3?file=%2Fsrc%2FApp.tsx%3A58%2C40

While tooltip works fine, popover won't open. If I nest popover inside tooltip, then popover works but tooltip doesnt. What should I change? I would really like to have separate components for `Tooltip` and `Popover`.

**Comment by benoitgrelard** [comment]
You should not create components in render, move the definitions outside.
Also, you need to ensure you always forward all props and ref.
