### ISSUE TITLE
Add Sidebar

### ISSUE THREAD

**Issue by SilvianAchim** [radix-ui/primitives#2664]
### Overview

A sidebar, exactly like YouTube. On the desktop, it should be on either the left or right. On mobile it should be on the bottom or the top of the screen, containing a menu icon which when opened, should display the content of the sidebar.

### Examples in other libraries

[https://www.youtube.com/](url)

### Who does this impact? Who is this for?

Everyone who needs to build a vertical nav bar.

### Additional context

-

**Comment by benoitgrelard** [comment]
This is something that can be covered with `Dialog` and/or `NavigationMenu`.

**Comment by wdews** [comment]
Can you at least explain that recommendation, @benoitgrelard? :/

**Comment by BrianHung** [comment]
You can use this to make a sidebar:
- Dialog Portal with custom container
- Dialog Content with modal=false

**Comment by wdews** [comment]
Thanks @BrianHung, will give this a try.

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/radix-ui/primitives/discussions/2748
