### ISSUE TITLE
Add barClassName in Progress component so we can add styles to the bar

### ISSUE THREAD

**Issue by Judge-Paul** [radix-ui/primitives#2669]
### Overview

I would like to add a barClassName property to the [Progress](https://github.com/radix-ui/primitives/blob/main/packages/react/progress/src/Progress.tsx) component so we can style the bar in the progress. E.g change the bar color, make it rounded on both sides e.t.c

I have already done this in my local version like:
``` javascript
export interface ProgressProps extends PrimitiveDivProps {
    barClassName?: string;
    value?: number | null | undefined;
    max?: number;
    getValueLabel?(value: number, max: number): string;
}
```
This allows me to do
``` javascript
<ProgressPrimitive.Indicator
  className={cn(
    "h-full w-full flex-1 bg-black transition-all",
    barClassName,
  )}
  style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
/>
```
``` javascript
<Progress
  className="mt-6 fill-current"
  barClassName="bg-[#6160DC]"
  value={50}
/>
```
And get:
![image](https://github.com/radix-ui/primitives/assets/110723341/4b112a2e-8672-4b0a-8c09-0442039772c5)

**Comment by benoitgrelard** [comment]
Hi @Judge-Paul, that doesn't quite make sense, primitives are low-level and unstyled. We provide each part on purpose so you can attach things like `className` to them. So this is all already possible.

You can then create whatever API on top as you wish (like your `Progress` component there).
