### ISSUE TITLE
[Select] Native OS webview select dialog on mobile

### ISSUE THREAD

**Issue by mattickx** [radix-ui/primitives#2673]
## Feature request

Is it possible to enable the native webview dialog for `<Select>` on Android/iOS?

## Goal
The goal is to provide users with an experience they are already familiar with on their mobile operating systems while maintaining the current (custom) desktop experience. 

This would improve accessibility by the effects of familiarity in my opinion.

## Overview

Ideally, this feature could be enabled by passing a prop, ensuring it doesn't break anything and remains an optional choice.

### How to:
I have successfully implemented this for custom selects in other projects by incorporating a hidden native select on mobile
and simulating a click on it when interacting with a customized `<Select>` trigger. 

However, I'm not familiar enough with the inner workings of the radix-ui codebase to open a PR.

### Android example:
Here's an example of the native select dialog on Android:
![image](https://github.com/radix-ui/primitives/assets/9006731/11a922dc-59b0-4bc2-829c-9904133ba9d0)

## Who does this impact? Who is this for?

This primarily impacts mobile users.

**Comment by benoitgrelard** [comment]
This isn't something we would implement in the primitive as the primitive is here to offer a more customisable version of the native select.

You could achieve this on your side by swapping the implementation of your select depending on criterias you determine for mobile (screen size, UA, touch, …).
