### ISSUE TITLE
Scroll Area component - can expose a data attribute when scroll bar is visible?

### ISSUE THREAD

**Issue by Roeefl** [radix-ui/primitives#2675]
### Overview

Currently we've implemented a custom solution to achieve that knowledge, would be great if it would be possible to assess without it.

### Who does this impact? Who is this for?

We believe this would be useful for many consumers...

**Comment by Danny-Duck** [comment]
It's exposed via the `type` prop. [See](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/scroll-area/src/ScrollArea.tsx#L39) for options

**Comment by Roeefl** [comment]
@Danny-Duck Thank you, but I'm not sure we're relating to the same thing. I don't want to set the scroll bar behaviour, but rather to be able just to know whether it's displayed or not, not by having it always display.

**Comment by benoitgrelard** [comment]
@Roeefl there is a `data-state` attribute for that already:
![CleanShot 2024-03-01 at 21 03 35@2x](https://github.com/radix-ui/primitives/assets/1539897/a8370a3d-a4ea-42e7-839b-235dafbce9e7)
