### ISSUE TITLE
Copying a value to clipboard when clicking item in DropdownMenu isn't working

### ISSUE THREAD

**Issue by andreasmcdermott** [radix-ui/primitives#2676]
### Current Behavior

We have a dropdown menu in React that offers certain functions like "Copy URL". We recently migrated our custom one to the Radix DropdownMenu and we realized that our code for copying is no longer working.

I have not been able to figure out why the Radix Dropdown prevents the copy, but I have verified that the same copy-code works in other places. 

The copy-code also works within the dropdown if I wrap it in `setTimeout` like so: `setTimeout(copy, 0)`.

### Expected behavior

I would expect that the function triggered when clicking an item in the dropdown menu to work the same as if called outside the dropdown menu.

### Reproducible example

[CodeSandbox](https://codesandbox.io/p/devbox/winter-smoke-fn4rkf)

### Suggested solution

I don't know yet.

### Additional context

I don't think so

### Your environment

This is based on the versions used in the reproduction linked above (the version of React is older in our actual app, but everything else is the same):

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-dropdown-menu       |    2.0.6     |
| React            | n/a     |  18.2.0       |
| Browser          |     Chrome    |    121.0.6167.85 (Official Build) (arm64)     |
| Assistive tech   |     No    |         |
| Node             | n/a     |         |
| npm/yarn         |    npm     |    9.8.1     |
| Operating System |     MacOs    |     13.5.2    |

**Comment by benoitgrelard** [comment]
HI @andreasmcdermott,

Given your current code, it makes sense why it doesn't work as you expect, and why it works within a `setTimeout`.
The way you are copying in the clipboard uses an old technique:
- create an input
- append it to the body
- set its value
- **focus** it and select it
- execute a command to copy the text

`DropdownMenu` is modal by default, therefore focus is trapped within it, meaning it's not possible to focus anywhere outside. So when you select that item to copy, your implementation attempts to focus that input but it won't work.

You have a few options to solve your issue:
1. You could try making the menu non-modal by passing `modal={false}` to the `Root`
2. You could try and update your code to use more modern techniques to copy (like the clipboard API).

**Comment by dragonman225** [comment]
I encountered this issue with Radix Dialog while implementing a screen like this:

![Image](https://github.com/user-attachments/assets/023e9ad7-aa7b-42c8-9497-67a5c3d99544)

I ended up switching to a newer library called Base UI (https://base-ui.com/react/components/dialog), whose Dialog has almost the same API but works with the select-and-`document.execCommand('copy')` technique (even when `modal={true}`).
