### ISSUE TITLE
Disable "Component" must be used withing "Compnent" 

### ISSUE THREAD

**Issue by maxpaleo** [radix-ui/primitives#2678]
## Feature request

Hi! We're using Radix within a block-based project, where UI elements are based on JSON block data. 
The UI can be moved around so that the user can put a navigation menu item within a different navbar, for example. 

Now, we keep on running into issues where, as soon as a component is "In transit," it triggers the error of the component having to be within a separate component. So when the user drags a component into another one, it immediately shows this error. 

Is there a way to disable these errors? 

<img width="839" alt="Screenshot 2024-02-01 at 7 51 33 PM" src="https://github.com/radix-ui/primitives/assets/91980500/8cac02d2-e752-4e11-8553-15a7c18a2025">

**Comment by feder240516** [comment]
I think what you need is to omit the `NavigationMenuTrigger` from the "moving around" component

Checking inside [radix code](https://github.com/radix-ui/primitives/blob/8b1162c472c197e464d64ce0ec0913cfffa734c2/packages/react/navigation-menu/src/NavigationMenu.tsx#L477) `NavigationMenu` creates a (not exported) context provider that will be consumed by the `NavigationMenuTrigger`. This means that there is no way to render that specific component outside the `NavigationMenu`.

So, you will need to use a different element inside your static `NavigationMenu` than the one that is dragged around. I don't know what library are you using for this moving around behaviour, but for example dnd-kit does this using a [DragOverlay](https://docs.dndkit.com/api-documentation/draggable/drag-overlay)
