### ISSUE TITLE
[Drowdown menu] 

### ISSUE THREAD

**Issue by zhoumo01** [radix-ui/primitives#2684]
Sure! Here's a bug report template based on the information you provided:

### Current Behavior
When clicking on any dropdown menu within a page, the browser's vertical scroll bar is hidden.

### Expected behavior
The vertical scroll bar should remain visible when a dropdown menu is clicked.

### Reproducible example
You can reproduce the issue at radix document page [Dropdown Menu](https://www.radix-ui.com/primitives/docs/components/dropdown-menu)

![QQ截图20240204173747](https://github.com/radix-ui/primitives/assets/4645808/75ac95d4-c6d1-4262-9de8-3ec81ec5def5)

**Comment by Golubkov-P** [comment]
Hi! There is prop called modal on [Root element](https://www.radix-ui.com/primitives/docs/components/dropdown-menu#root), you can achieve desired behaviour by setting it as false

**Comment by benoitgrelard** [comment]
That is the correct intent.
