### ISSUE TITLE
Tooltip example not working radix-ui.com/primitives/docs/components/tooltip

### ISSUE THREAD

**Issue by selmetwa** [radix-ui/primitives#2694]
## Bug report
Tooltip example doesn't seem to be working
https://www.radix-ui.com/primitives/docs/components/tooltip

### Current Behavior
Clicking the trigger doesn't do anything, an element appears to quickly get added to the DOM but it vanishes almost instantly.

https://github.com/radix-ui/primitives/assets/46908343/c9d25015-954f-41d8-97e4-a1274a1fa2a4

### Expected behavior
tooltip to open

### Reproducible example
https://www.radix-ui.com/primitives/docs/components/tooltip

### Your environment
| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Browser          |  Chrome 121.0.6167.139, firefox 122.0.1, safari Version 16.5 (18615.2.9.11.4)

**Comment by bsolca** [comment]
The tooltip is triggered only if you hover with your mouse. If you do an click action you have to go out and back again with the mouse and wait the tooltip to come.

**Comment by selmetwa** [comment]
> The tooltip is triggered only if you hover with your mouse. If you do an click action you have to go out and back again with the mouse and wait the tooltip to come.

I was hovering in the video, but tabbing over the element briefly triggers the tooltip

**Comment by benoitgrelard** [comment]
The tooltip works on hover/focus.

In your video I believe your issue is that as you opened the devtools, so the document itself didn't have focus.
Hence why when you tried clicking the button, you briefly saw something in the DOM (because it gained focus, but then clicking the trigger hides the tooltip).

**Comment by selmetwa** [comment]
> The tooltip works on hover/focus.
> 
> In your video I believe your issue is that as you opened the devtools, so the document itself didn't have focus. Hence why when you tried clicking the button, you briefly saw something in the DOM (because it gained focus, but then clicking the trigger hides the tooltip).

It happens even when the devtools is closed.
