### ISSUE TITLE
Documentation latest listed version is incorrect.

### ISSUE THREAD

**Issue by ncoughlin** [radix-ui/primitives#2695]
### Current Behavior

![radix](https://github.com/radix-ui/primitives/assets/3167700/e756bc1d-7cbd-45b3-a2d5-7e908326d95a)

I have not checked all the primitives, but for the Select element at least the latest listed version on the documentation is incorrect. npm shows latest version @2.0

### Expected behavior
Show latest stable version

**Comment by benoitgrelard** [comment]
duplicate of #2415
