### ISSUE TITLE
Detect page direction automatically on text direction primitives

### ISSUE THREAD

**Issue by SalahAdDin** [radix-ui/primitives#2703]
### Overview
For testing the direction on many of the primitives, like `NavigationMenu` we need to pass the text direction as a property (`dir`).

It is a problem cause we need to use the `DirectionProvider` primitive to handle it, especially in [Storybook](https://github.com/radix-ui/primitives/blob/main/packages/react/navigation-menu/src/NavigationMenu.stories.tsx#L389).

We are using a **storybook** [addon](https://www.npmjs.com/package/storybook-addon-rtl) to toggle between directions and it works well for `html` code, but unfortunately, it does not work with radix primitives.

### Who does this impact? Who is this for?

It would be useful for juniors and mid to have such automatic direction detection since implementing the whole decorator for getting this feature working on the storybook.

**Comment by benoitgrelard** [comment]
We used to try and automatically respond to the html dir changes, but it caused a lot of performance issues which a lot of users complained about. Hence why we moved to a more explicit solution using the provider. Unfortunately this isn't something we will be changing back.
