### ISSUE TITLE
How to enable scroll outside Select component when the select dropdown is open?

### ISSUE THREAD

**Issue by Himanshu-Roxiler** [radix-ui/primitives#2708]
## Question

I have a use case where I want to enable scroll on the screen when the dropdown on the Select component is open. I have gone through the documentation and various posts and gathered that this is not the native behaviour when the dropdown is open (ie I cannot scroll outside anywhere on the screen as long as the dropdown is open)

Is there a way in which I can enable the scroll behaviour on the screen outside the dropdown, have I missed something in the documentation that will allow me to do so?
Is there any work around that I can implement as a solution?

**Comment by StephenHaney** [comment]
Hey there – that's how the Select component works. If you want a menu that allows page scroll while it's open, you can build something using the DropdownMenu.
