### ISSUE TITLE
Select Component Scrollbar Behavior Issue in Chrome on Ubuntu  #2730

### ISSUE THREAD

**Issue by tarifalhasan** [radix-ui/primitives#2710]
![image](https://github.com/radix-ui/primitives/assets/92237522/d7712359-f54e-46ee-af52-3f41915fe7ae)

![image](https://github.com/radix-ui/primitives/assets/92237522/0cc99b7f-5a5b-46f9-b7d3-54fea5979621)

**Comment by StephenHaney** [comment]
Hey – can you share what you're seeing and what you're expecting?

**Comment by Rowee13** [comment]
any updates regarding this matter? you can also see the issue in the docs preview of the Select component. When you open the Select component, the scrollbar is hiding resulting in UI behavior issues when applied to apps. You can see the issue either in firefox or google chrome.

**Comment by benoitgrelard** [comment]
I will close the issue for now as it lacks enough information to get by with.
@tarifalhasan feel free to re-open it with more information.
