### ISSUE TITLE
Accordion not opening smoothly

### ISSUE THREAD

**Issue by atlasdoconhecimento** [radix-ui/primitives#2713]
## Bug report
I'm using the shadcn accordion: https://ui.shadcn.com/docs/components/accordion
The one at the website opens smoothly. If I use the same code, it will open instantly (not animated). It closes smoothly, like the example on the website.

### Expected behavior

Open smoothly.

### Reproducible example

```
<Accordion type="single" collapsible className="w-full">
    {terms.map((term) => {
      return (
        <AccordionItem key={term.name} value={term.name}>
          <AccordionTrigger>{term.name}</AccordionTrigger>
          <AccordionContent>{term.meaning}</AccordionContent>
        </AccordionItem>
      )
    })}
</Accordion>
```

### Suggested solution

--radix-accordion-content-height should be computed before opening the accodrion.

### Additional context

If I replace `to: { height: 'var(--radix-accordion-content-height)' }` by` to: { height: 50 }`, it works. My guess is that `--radix-accordion-content-height` is only computed correctly when it's opened. That's why closing works smoothly, but opening doesn't.

I've inspected my element:
`<div data-state="open" id="radix-:R43auuekq:" role="region" aria-labelledby="radix-:R3auuekq:" data-orientation="vertical" class="overflow-hidden text-sm transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" style="--radix-accordion-content-height: var(--radix-collapsible-content-height); --radix-accordion-content-width: var(--radix-collapsible-content-width); --radix-collapsible-content-width: 783.71875px;"><div class="pb-4 pt-0">Some content</div></div>`

Then, I've inspected ShadCN website:
`<div data-state="open" id="radix-:r6t:" role="region" aria-labelledby="radix-:r6s:" data-orientation="vertical" class="overflow-hidden text-sm transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" style="--radix-accordion-content-height: var(--radix-collapsible-content-height); --radix-accordion-content-width: var(--radix-collapsible-content-width); --radix-collapsible-content-height: 36px; --radix-collapsible-content-width: 443.796875px;"><div class="pb-4 pt-0"></div></div>`

Mine doesn't have --radix-collapsible-content-height: 36px;

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   shadcn      |   1.1.2      |
| React            | n/a     |    18     |
| Browser          |         |      Brave and Opera   |
| Next.js             | n/a     |    14.1.0     |
| Operating System |     Windows    |   10      |

**Comment by atlasdoconhecimento** [comment]
Found out what the problem was, although I didn't understand it. If I remove `important: true` from tailwind.config.ts, then it works. Why's that?

**Comment by StephenHaney** [comment]
I'm glad you found a solution. I'm going to close this as it doesn't seem like something that is controlled by the Radix.
