### ISSUE TITLE
Is it possible to interact with trigger while portal is open?

### ISSUE THREAD

**Issue by gt-tm-3310** [radix-ui/primitives#2721]
Hi, I want to be able to interact with trigger while portal is open like on this video(antd select). Could you please let me know if this is possible? Thanks

https://github.com/radix-ui/primitives/assets/146180997/eccb3aa2-ac6c-4aa8-aa02-bf78255bab61

**Comment by benoitgrelard** [comment]
Did you post the issue in the wrong library? This doesn't look like a Radix primitive.
