### ISSUE TITLE
Change tooltip text on click

### ISSUE THREAD

**Issue by strafe** [radix-ui/primitives#2725]
### Overview

This is quite similar to the requests #2029 and #2632, but neither mentions keeping the same tooltip open but changing the text on click.

### Examples in other libraries

[Tippy.js](https://atomiks.github.io/tippyjs/#triggers) has the ability to use click as a trigger rather than hover.

[Bootstrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/)'s own website uses this exact behaviour. You can click as many times as you want to re-perform the action and the tooltip will only disappear once unhovered.
![Screen Recording 2024-02-25 at 16 17 38](https://github.com/radix-ui/primitives/assets/15663890/34ad6882-efef-45d8-b3cf-ec3f7a533c6d)

### Who does this impact? Who is this for?

The use case here would be something I've seen fairly often, you hover over an element and see a tooltip saying "Click to copy" once you click that element the tooltip persists but now says "Copied!" to assure the user it worked.

### Additional context

N/A

**Comment by benoitgrelard** [comment]
This is achievable with the current API.

We have an example in our storybook: https://github.com/radix-ui/primitives/blob/main/packages/react/tooltip/src/Tooltip.stories.tsx#L659-L687

I will add an example in the docs as this question comes up once in a while.

**Comment by strafe** [comment]
@benoitgrelard thank you for the example, although I notice it doesn't really show how to change the text on click. I did have a go but wasn't able to achieve the behaviour seen on the Bootstrap site, it was always a bit buggy.
