### ISSUE TITLE
Popover on top of Dialog

### ISSUE THREAD

**Issue by abisao1** [radix-ui/primitives#2729]
Is it possible to open a Popover on top of dialog box?

I have a dialog and Popover inside the it that opens on button click. The popover is opening but the problem is that it hides behind the dialog box. I cant bring it in front of the dialog. I am using primitives.

**Comment by benoitgrelard** [comment]
Yes it is possible, here is an old sandbox showing it:

https://codesandbox.io/p/sandbox/popover-dialog-1y0rt?file=%2Fsrc%2Findex.js

It is the other way around here (`Dialog` from `Popover`) but it makes no difference which way around.

**Comment by benoitgrelard** [comment]
That shouldn't be an issue, especially if you use the portal parts for each and don't mingle with `z-index`, out of the box they would stack naturally.

**Comment by abisao1** [comment]
It worked after removing <Popover.Portal>  otherwise the popover was being rendereed behind the dialog.

From: Benoît Grélard ***@***.***>
Date: Wednesday, 28 February 2024 at 1:31 PM
To: radix-ui/primitives ***@***.***>
Cc: abisao1 ***@***.***>, Author ***@***.***>
Subject: Re: [radix-ui/primitives] Popover on top of Dialog (Issue #2729)

That shouldn't be an issue, especially if you use the portal parts for each and don't mingle with z-index, out of the box they would stack naturally.

**Comment by benoitgrelard** [comment]
That makes me think your dialog wasn't using the portal part either?
If they both use their own portal parts, it should all work fine out of the box.
