### ISSUE TITLE
Add visual/interactive examples for all component examples

### ISSUE THREAD

**Issue by jamesl1001** [radix-ui/primitives#2730]
## Documentation

I've found that it would be super useful to have more interactive examples for each component.

There is one interactive example at the top of each component's documentation, but it would be useful to be able to visualise and play with the code examples further down the page.

### Relevant Radix Component(s)

All primitive components.

**Comment by benoitgrelard** [comment]
Hi @jamesl1001, this is something we used to have, but we have purposefully gone to a single fully fledged example instead as it became too much of a maintenance burden for us. So unfortunately we are unlikely to change this back.

Hope this answers your question.
