### ISSUE TITLE
Accordion uses <details> and <summary> markup

### ISSUE THREAD

**Issue by maxkarkowski** [radix-ui/primitives#2738]
## Feature request

Would it be possible to use the correct semantic markup for accordion as a default?
As of now the Trigger is a button-Element wrapped in an h3-Element.  

so instead of this 
```
<div data-state="open" data-orientation="vertical" class="c-iMREiE">
  <h3 data-orientation="vertical" data-state="open">
    <button
      type="button"
      aria-controls="radix-:r18:"
      aria-expanded="true"
      data-state="open"
      data-orientation="vertical"
      id="radix-:r17:"
      class="c-ccIjVi"
      data-radix-collection-item=""
    >
      Trigger<svg>...</svg>
     </button>
  </h3>
  <div
    data-state="open"
    id="radix-:r18:"
    role="region"
    aria-labelledby="radix-:r17:"
    data-orientation="vertical"
  >
    <div class="c-bMyySE">Content</div>
  </div>
</div>

```

maybe more like this

```
<details data-state="open" data-orientation="vertical" class="c-iMREiE" open>
  <summary data-orientation="vertical" data-state="open">
      Trigger<svg>...</svg>
  </summary>
  <div
    data-state="open"
    id="radix-:r18:"
    role="region"
    aria-labelledby="radix-:r17:"
    data-orientation="vertical"
  >
    <div class="c-bMyySE">Content</div>
  </div>
</details>


```

**Comment by benoitgrelard** [comment]
`Accordion` follow the the [Accordion pattern from WAI-ARIA](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/). You can see an example here with the same markup: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/

The goal of the primitives library is to be more flexible in terms of styling, adding icons, animations, etc whilst remaining accessible.

**Comment by jamesarosen** [comment]
An `<h3>` is not a safe root element to use for the header. There are lots of contexts in which one might use an accordion, but in which an `<h3>` is invalid:

* inside any inline element
* inside a table cell
* in regular flow, when the preceding header element was anything other than an `<h2>`

The W3 WAI-ARIA examples are _examples_. The example you linked to says

> The example uses heading level 3 so it fits correctly within the outline of the page; the example is contained in a section titled with a level 2 heading.

The `details/summary` pair has the correct semantics and already has accessibility baked in.

But at minimum, this needs to be configurable in order for accessibility. Having it as an `<h3>` makes table-of-contents navigation impossible. This implementation _hurts_ accessibility in the name of improving accessibility.
