### ISSUE TITLE
The distance from the anchor is not same when passed "4" and 4

### ISSUE THREAD

**Issue by AayushKarki714** [radix-ui/primitives#2750]
### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi, the issue and sandbox are empty. Regardless, the prop accepts a number, not a string, hence why you might see a discrepency. JavaScript is forgiving and will accept a string, but TypeScript won't. in JavaScript I'm guessing the `+` operation will try and concatenate the `"4`", resulting in something unexpected.
