### ISSUE TITLE
controlled select - changing value to undefined doesn't show placeholder 

### ISSUE THREAD

**Issue by alissawix** [radix-ui/primitives#2752]
### Current Behavior
when you first render the select with an undefined value it's ok
but if you change the value to something and then back to undefined you can't see the placeholder.

it either shows nothing of the selected item text content.

### Expected behavior
either remove undefined from possible select values or show placeholder when the value is changed to undefined.

### Reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/cool-perlman-w23mct?file=%2Fsrc%2FApp.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-select    |   2.0.0      |
| React            | n/a     |      ^18   |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
You can't change the `value` to `undefined` and expect it to pick it up because of how controlled/uncontrolled components work. If you want to reset it to show the placeholder, set the `value` to `""` instead.
