### ISSUE TITLE
[ContextMenu] Select on right click

### ISSUE THREAD

**Issue by odeyal0** [radix-ui/primitives#2756]
### Current Behavior
Select menu element on fast rightclick

https://github.com/radix-ui/primitives/assets/46008279/c73f6d7f-97f0-4be2-be60-dce02bf6fcea

### Reproducible example
https://codesandbox.io/p/devbox/radix-context-menu-bug-zlqgfp

### Your environment
Check sandbox

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Browser          |   google chrome|     |
| Operating System | windows         | 11  |

**Comment by odeyal0** [comment]
The context menu item is selected by right click, which should not happen.
In this example, the problem does not appear to be critical. But in my real application, when I select a context menu item, a radix modal window opens. The modal window also uses the portal. A bug occurs, after which the context menu cannot be opened.

I tried to make a minimal example, because looks like the problem is in the right-click selection.
If necessary, I can make an example with a modal window.

**Comment by benoitgrelard** [comment]
I still don't see what you mean in the video or when I try with the sandbox.

> The context menu item is selected by right click, which should not happen.

What do you mean here?

**Comment by odeyal0** [comment]
Function "onSelect" should be called only on left mouse click, but in the video it's called on right mouse click.

**Comment by benoitgrelard** [comment]
Yeah I see, I can't seem to reproduce it using your sandbox though…

**Comment by odeyal0** [comment]
You need to quickly right-click and move the mouse to the right and down.

**Comment by benoitgrelard** [comment]
I see, the speed doesn't matter though.

What you are doing is what I do here in the video but just super fast, so it feels like a bug but isn't really one:

- right-click but keep holding (`pointerdown`)
- move cursor over an item (`pointermove`)
- release cursor (`pointerup`)

https://github.com/radix-ui/primitives/assets/1539897/defd3cbe-20d5-4894-816d-2423d46ce25f

I can do exactly the same thing with the native menu going fast too.

**Comment by odeyal0** [comment]
Yes it is.
Then it's probably worth closing the issue. I’ll create a new issue for a context menu with modal window bug later.

**Comment by benoitgrelard** [comment]
It would be the same thing though right?

**Comment by odeyal0** [comment]
Need to check.

**Comment by odeyal0** [comment]
I won't create issue "context menu + modal dialog bug" because it was fixed by updating @radix-ui/react-dialog from 1.0.4 to 1.0.5 in my project)
