### ISSUE TITLE
No [data-state] and [data-motion] attributes on NavigationMenu.Content

### ISSUE THREAD

**Issue by shota-f** [radix-ui/primitives#2759]
## Bug report
There are [data-state] and [data-motion] attributes on the document(https://www.radix-ui.com/primitives/docs/components/navigation-menu#content).
But NavigationMenu.Content doesn't seem to have them.

### Current Behavior
[data-state] no
[data-motion] no
[data-orientation] ok

### Screenshot of chrome dev tool
Focused node is the NavigationMenu.Content.
And logs on console.

![nav-menu-content-bug](https://github.com/radix-ui/primitives/assets/46377697/015911d6-4f4d-466c-be23-0920ea3e46ad)

### Expected behavior
[data-state](important when forceMount is true)
and [data-motion]

### Reproducible example
1. Copy the first codes(index.jsx and styles.css) on the document.
2. Past them.
3. Add "item-1" to value prop for NavigationMenu.Root and first NavigationMenu.Item for debug.
4. Check the NavigationMenu.Content under the NavigationMenu.Viewport.

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-navigation-menu        |   1.1.4      |
| React            | n/a     |   18.2.20      |
| Browser          |     Google Chrome    |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
These attributes are present, that's what enables those animations you see in the demo here: https://www.radix-ui.com/primitives/docs/components/navigation-menu or in our storybook here: https://601857eb614bae0021c9b9dd-evgfcrkbbq.chromatic.com/?path=/story/components-navigationmenu--submenus

I will close this as I cannot reproduce your issue, but feel free to send a sandbox demonstrating your issue.

**Comment by Kulsgam** [comment]
![{81482DD8-D39B-4358-BD0D-69F957F7A23C}](https://github.com/user-attachments/assets/f6f573ff-af32-422c-b84d-30fb60c1c13b)
This issue is present in the original [https://codesandbox.io/p/devbox/strange-james-h7q2zs](codesandbox) present in the docs

[https://h7q2zs-5173.csb.app/](Here) is the direct link

**Comment by andrea-budel-remedia** [comment]
@benoitgrelard it happens when you try to use the Viewport component.

**Comment by connorwarme** [comment]
@benoitgrelard I was also able to replicate this issue.

**Comment by albin-grebban** [comment]
+1 here, when using the Viewport we are missing the `data-state` attribute in Content.

**Comment by kecoliva** [comment]
+1
