### ISSUE TITLE
DropMenu And AlertDialog Portal Colliding

### ISSUE THREAD

**Issue by sarojghalan** [radix-ui/primitives#2760]
### Current Behavior
When i click on my action button it opens , drop menu : using `@radix-ui/react-dropdown-menu`
![image](https://github.com/radix-ui/primitives/assets/88360959/ada81f17-f74b-4686-8558-929cf4ebfe5f)

And after that i need to click `approve` or `reject` list to approve and reject request, 
So when i click on that list it open `dialog` : using `@radix-ui/react-alert-dialog`
![image](https://github.com/radix-ui/primitives/assets/88360959/c77786d7-d39a-4ec2-ac75-d4c7970a5f51)

Now here comes my issue, when i click on `back` button instead of `Approve` it cancel the `ALertDialog` but one of the overlay stills remains there and i can't navigate to `anywhere`, even when i inspect element its behavior looks like this 

i can't even select element only below layer is shown and it point to `html` as shown in figure

![image](https://github.com/radix-ui/primitives/assets/88360959/538f3ad2-241c-49ec-89b7-4fe349384aa5)

### Expected behavior
I would expect to navigate all `navs` and `tabs` , `actions` and `button`

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     `@radix-ui/react-dropdown-menu`   `@radix-ui/react-alert-dialog`  | `^2.0.5`  `^1.0.5`         |
| React            | n/a     |         |
| Browser          |     Chrome    |         |
| Assistive tech   |         |         |
| Node             |     |      20.11.1  |
| npm/yarn         |   npm      |   10.2.4      |
| Operating System |   ubuntu      |   Ubuntu 22.04.4 LTS      |

**Comment by benoitgrelard** [comment]
This is probably due to how you are composing the 2 components together.
You can find a working demo here which doesn't have any of the flaws you describe: https://codesandbox.io/p/sandbox/dropdownmenu-dialog-items-r9sq1q

**Comment by sarojghalan** [comment]
Thank you for you time your solution was clean , but my above scenario uses `@radix-ui/react-alert-dialog` not `dialog` any way i have solved it using `popover` instead of `DropdownMenu` @benoitgrelard :rose:
