### ISSUE TITLE
Expose props for configuring floating-ui `autoUpdate` options like `layoutShift`

### ISSUE THREAD

**Issue by samjust2ok** [radix-ui/primitives#2767]
### Overview

Currently, all components depending on radix ui `Popper` component has its `PopperContent` position recomputed on layout shift due to the the use of `floating-ui` autoUpdate function with its default `layoutShift` option being `true`. Allowing customisation of these options might be a _simple_ change that could further enhance the flexibility of `Popper` use cases and its dependants.

### Examples in other libraries
react-aria `Popover` component uses the `shouldUpdatePosition` prop to control auto re-computing of popover position
https://react-spectrum.adobe.com/react-aria/Popover.html#props

### Who does this impact? Who is this for?
Currently I am building an advanced filter component similar to the one used in the https://linear.app/ dashboard (SEE screenshot below). 

<img width="1050" alt="Screenshot 2024-03-08 at 13 28 52" src="https://github.com/radix-ui/primitives/assets/32585895/505b4157-9a32-407d-bbb3-849bf45c68ac">

Selections made in the popup reflects in the filter list and thus causes a layout shift in the position of the popover anchor. The current implementation of radix popper component causes the auto recomputing of its position on layout change and thus makes the UX inefficient

See behaviour below

https://github.com/radix-ui/primitives/assets/32585895/068bd3eb-802c-4e3c-95fc-dfe86e68d7a8

**Comment by fergy-os** [comment]
@samjust2ok were you able to work around this limitation and still achieve what you wanted?
