### ISSUE TITLE
[Select] Select content not showing in Dialog due to z-index

### ISSUE THREAD

**Issue by lucasriondel** [radix-ui/primitives#2773]
### Current Behavior

My problem is that I have a Dialog, which `DialogContent` have to have a `z-index` property set, because some elements in my page **that I cannot control** have a `z-index` set. I won't have this issue if the `z-index` property of my `DialogContent` was not set.

https://codesandbox.io/p/devbox/select-dialog-radix-zindex-issue-y4wnqh

As you can see in my codesandbox, you can trigger my modal and see a `Select` in it. The issue is that the content of the select is not showing. However, if I set the z-index of the `RadixSelect.Portal`'s `container`, it works. 

![CleanShot 2024-03-12 at 10 41 00](https://github.com/radix-ui/primitives/assets/7773454/c8d876b5-0bba-4890-8d91-9ab69bd5f5be)

My first solution was to set the `container` prop of `RadixSelect.Portal` to a `div` in the `body` of my page, using my index.html, and then set it's `z-index`. If I do that, it's working. 
But now, I'm exporting those components inside an UI kit, and having to tell my users to create a div inside their body and then use css to change its z-index feels bad. 

Is there a way to do this properly ? 

### Expected behavior

I would like to have a way to make my `Select` options visible in my `Dialog` easily.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/devbox/select-dialog-radix-zindex-issue-y4wnqh)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Dialog        | 1.0.5        |
| Radix Package(s) | Select        | 2.0.0        |
| React            | n/a     | 18.2.0        |
| Browser          | Arc        | 1.33.0        |
| Node             | n/a     | 18.17.0        |
| pnpm         |         | 8.15.4        |
| Operating System | macOS        | 13.6        |

**Comment by benoitgrelard** [comment]
> which DialogContent have to have a z-index property set, because some elements in my page that I cannot control have a z-index set.

Having the dialog content in a portal should ensure it's always on top. What you might be missing is a new stacking context at the root of your app. If you do this properly, there should be no need for any specific `z-index` on any of the overlaid contents (dialog, select, popovers, etc) and they should stack naturally.

Have a look at how we do it in Radix Themes: https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/index.css#L53-L55

The idea is to ensure your app root (typically a div somewhere close to `body`) creates a new stacking context, thus encapsulating everything that has z-index into it, and ensuring that anything portalled in `body` will always be guaranteed to be on top.

**Comment by lucasriondel** [comment]
@benoitgrelard thank you for your fast answer Benoît ! I never thought I could do this. This is really clever. 

But I would never have figured this out myself. Shouldn't this be on the documentation somewhere ? I know radix has for main purpose to be unstyled, but is the layer system explained at some point ?

**Comment by benoitgrelard** [comment]
Yeah it's difficult to find the balance in places. With Radix Themes being styled, we can just do it for users which is great, in primitives it's a bit more difficult as we don't own any of the styling/application.

I agree some hint in the docs might be nice, although in practice, we find a lot of people will still ask questions instead of reading the docs 😉

Would you mind adding a new issue on the website repo for it (referencing this one)?

Thanks!

**Comment by lucasriondel** [comment]
@benoitgrelard sure, i'll do it right away. keep up the good work ❤️
