### ISSUE TITLE
Wrapping Select items with a form gives different html - harder to test in RTL

### ISSUE THREAD

**Issue by roelandwyns** [radix-ui/primitives#2820]
## Question

When writing a Select component in React like this: 
```
import React from "react";
import {Select, SelectContent, SelectItem, SelectTrigger} from "@/components/ui/Select";


export type RadixSelectWithItemsProps = {
    items: { name: string, id: string }[]
    currentSelection: { name: string }
} & React.HTMLAttributes<HTMLDivElement>;

export default function RadixSelectWithItems({
                                           currentSelection,
                                           items,
                                       }: RadixSelectWithItemsProps) {
    return (
        <Select
            value={currentSelection.name}
        >
            <SelectTrigger
            >
                {currentSelection.name}
            </SelectTrigger>
            <SelectContent>
                {items?.map(item => (
                    <SelectItem
                        key={item.id}
                        value={item.name}
                    >
                        {item.name}
                    </SelectItem>
                ))}
            </SelectContent>
        </Select>
    );
}
```

If you write a React testing library test for it: it renders as follows:
[    https://testing-playground.com/#markup=DwEwlgbgfMBGCuAXRB7AdgAkQTwA4FMBeAIgWXWIwCcUAbI4gYxQFtYV2APSgQyrB4BaZmkQ1aAZxJUe4ToIBcVAAwLe-Ifk64eaEPhAkAZj0n51AwTyQpmLXPUQM06cxnBUStMZRA9EQhIBTiSMtCgSBpRhPBJSxEb0nBhG6IiCLAZg8CxYWum4-Cx82IIAnMrKGAAWggCMAEwYAO6CRvC0tBhgTiwSwvii+FQYAFbwQWBGpbD4iM34g9Qo8HoGgg2cXbAA5oI7VPildZUYuPIALGelTfxoeyhGRpEFRSWCAKynDjyM+NV0fRUBROTjpFhIdapQ4HFZ6FK2CYKFaIWhgND4QQuDEIxhI9hUIG4-EoQnDQSFMDFKilL5VcASHiweggBR4qgSUlYlDpUzhBYgdxgRnMgzInSMHq0qoAagwBKJCvJByOG1OAIgwwUSqoFLeNMEAGZTmJdBIemB0MI6KSJO54DJEJa0GqqqD0hIWMQoE4ggA5HiZOrACQQHYYTgsWhoeLVZC4BQAekTzVTADpmoa06SdomGpVlInQztKM0wCBENUSA0LpRqvgwDs49XaxgIGB8M0AEIoTgkKpVGsYGuUIxgTokbFuII0ADWDHZh1EAGEbVRKDOUPPBGWK1XiA0N2It5i0RjGDxcNI4SAj3PT+j8KMUOjr6tbxgYnESOaAF6Yq4UAlKVPmUCwhGqct9DQEgxHgcwYB0St3BIFgADYMDKDAMJwwQ0O9YBEyQ6oYCLMNSLIVA0EQz9aFiWNBCud1BE9PIwUEYYaF1OkCKI0jwGgIA
](url)

This makes it easy to search for the items as follows:
```  const allTestName1 = screen.getAllByText(testName1);
        expect(allTestName1).toHaveLength(1);
        expect(screen.getByText(testName1)).toBeInTheDocument();
        expect(screen.queryByText(testName2)).not.toBeInTheDocument();
```
It finds the testName once with the following props passed to it ``` items: [
        {name: testName1, id: "123"},
        {name: testName2, id: "456"},
        {name: testName3, id: "789"},
    ],
    currentSelection: {name: testName1}```
    
        
This all works as expected. 

But when you wrap this component with a <form> around it, it starts to render it differently. 

[    https://testing-playground.com/#markup=DwEwlgbgfMBmD2AnAtjARgVwC5fgOwAIsBPABwFMBeAIkx32oMXgBsrqBjeZNeXgD0YBDRGCEBaLnizMWAZxqIh4fuIBciAAxrhoieX6kheEORA1YQ+eV1jxQ7PC7JSbLOzz4bBcIhosZRhAhLAk5UPcaDhZ4OTNGaKE5BWpYNn4CBGlxZDMwDGQiAyxxUlFkEWJxAE5NTQIAC3EARgAmAgB3cVgMFhYCMHdkOUlyaXJEAgArDHCwWCq0ciwO8jGmeAwTM3FW-n60AHNxQ8RyKua6glJVABZrqvbRPGP4WFg4krKwCsQqgFYrq4hBxyA1WKZEGp3PwSshsDsEGdTpsTJknLM1JssCwwHhyOJPPj0RxMbxEJCSWSkJDSuVKuJAfVwHIhGg2CA1KTEHIkIT4CUrDFViAfGBWeyzFijBxBgD6gBqAjkykqiYnM6PK7giATNRqxB0n4MgDMVxkxjkgzA+EkrCQch8GCUWBteF25uK4jkyGoUHc4QAckJcs1gHIIIcCPxkCw8CkGjhSGoAPQpjoZgB0HRNmaQhxTrTqmhTEcOjA6YBAWAaNFat0YDXIYEOibrDYIEDA5A6ACF4PwaPV6vWCPXGLAwH0aETvOFmABrdjcs7SADC9sQjHn8CX4kr1dr1Fa25ku4JuPxHCEpEUqJAp8XF7x5Cm8Dxd62D4IiWSNCtABeBL3PAMpyoymi2BIDRVqYeA0DIGA2DARg1j4NDIAAbAQ1QENh+HiJhfrACmqENDApaRhRdC4HgKE-iwSQJuI9wwiUPpFLC4gTMwhpMsRpEwHEbAcFgBAiHYMEgHBCGIEhjChGgeKmIO1AtKexBsDQpCxNa+BqOJaC8iwCIANzKjSeoEJoNzmQeNYGc0tmNM2rZYI5zlGNJeKHAZNn8OZvyHHiBktM58C6ogaTwB0BlSXB5nRGAyZMOQokABT+QANNZNw5dluX8AAlHZMHuN6MrkAZngdEopB2TS+51dVSAVCwpnEaBrr4J2VhIQh5BBiG5DNNu5Aie45jUH6AZYMGoYkV1bowEtPUQH17CzfN5Anv6g1zcNrSLaQ3V0cAq2EOtJmbft20mjNt3DSax2nRRwlpVgFFIqgJHgNAQA
](url)       

As you can see, now it adds the <option> fields for all the different items that are under the select. This means that if you do a getByText(testName1) that you get 2 values back (the current one in the comboBox and the one in the option). 

Why is this? And any idea how to write a nice test for it then? 

Currently we do use the `screen.getByRole('combobox', {name: testName1})` and then also the 'option' to differentiate. 

Thank you! :)

**Comment by febeling** [comment]
It looks very intentional:

https://github.com/radix-ui/primitives/blob/b32a93318cdfce383c2eec095710d35ffbd33a1c/packages/react/select/src/Select.tsx#L181-L197

Possibly the idea is that a native control is not unnecessary, unless the form-submit mechanism should work, but that's speculation.
