### ISSUE TITLE
Tabs set orientation="vertical" not working

### ISSUE THREAD

**Issue by qianmoQ** [radix-ui/primitives#2837]
<img width="1612" alt="image" src="https://github.com/radix-ui/primitives/assets/20521442/6a81ac88-c726-4127-9fd5-d0503984dc62">

**Comment by benoitgrelard** [comment]
Primitives are unstyled, so it won't affect the look and feel (that'd be up to you). It affect accessibility/functionality, in this case keyboard bindings.
