### ISSUE TITLE
Slot component causes a warning in React 19 about accessing `.ref` directly

### ISSUE THREAD

**Issue by OriginalEXE** [radix-ui/primitives#2890]
### Current Behavior

The `Slot` component accesses `.ref` on the element, which seems to be a no-no in React 19. The problematic line seems to be this one:
https://github.com/radix-ui/primitives/blob/main/packages/react/slot/src/Slot.tsx#L66

This results in the following warning:
> Warning: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

### Expected behavior

No warnings

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/sandbox/dreamy-kapitsa-m9q7q8?file=%2Fsrc%2Findex.js%3A22%2C1)

### Suggested solution

I haven't tried it, but maybe something like
```
ref: forwardedRef ? composeRefs(forwardedRef, (children as any).props.ref ?? (children as any).ref) : (children as any).props.ref ?? (children as any).ref,
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Any using Slot     |  latest       |
| React                   |  n/a     |  19.0.0-beta-6946ebe620-20240508       |

**Comment by bzmillerboy** [comment]
A PR is open to address this. https://github.com/radix-ui/primitives/pull/2811

**Comment by fokkerone** [comment]
Got the same issue in a 
React 18.3.1 ??!!!
NextJs 15.0.3. 
App ..


```
Console Error

Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

Call Stack
Next.js
SlotClone
node_modules/@volta/select/node_modules/@radix-ui/react-slot/dist/index.mjs (40:47)
Next.js
react-stack-bottom-frame
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
renderWithHooks
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
updateForwardRef
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
beginWork
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
runWithFiberInDEV
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
performUnitOfWork
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
workLoopConcurrent
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
renderRootConcurrent
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
performWorkOnRoot
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
performWorkOnRootViaSchedulerTask
./node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js
MessagePort.performWorkUntilDeadline
./node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js
```
