### ISSUE TITLE
React 19 compatibility

### ISSUE THREAD

**Issue by dalist1** [radix-ui/primitives#2900]
Recently React 19 was released, and I keep getting this warning about element.ref, since it's going to be removed in a future release, are you guys going to adjust this?

`Warning: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release. `

**Comment by nicksrandall** [comment]
React & ReactDom v19 is in "release candidate phase" and will be released shortly.

**Comment by DarioLopes** [comment]
April 2025, still can't update the type version of `react` and `react-dom` due to Radix.

Stuck at :

```json
"devDependencies": {
   "@types/react": "19.0.10",
   "@types/react-dom": "19.0.4",
}
````

Good to know for people that have to follow the crazy pace development of Next.js

**Comment by benedyktdryl** [comment]
Why is it closed @nicksrandall? I don't want to make it sound offensive - I'd be more than happy to try to fix it myself, but I'm not sure why it's marked as closed. I can see that `@types/react` and `@types/react-dom` in the latest versions are not compatible with RadixUI for now. I tried fixing it in multiple ways, but I ended up with an ugly `any` casting.

**Comment by cyyyu** [comment]
@nicksrandall why is this closed?

**Comment by nicksrandall** [comment]
I didn't close this ticket so I don't know. 

I will say that my projects are using Radix-UI with React 19 with no issues.

**Comment by cyyyu** [comment]
@nicksrandall oops. sorry for the wrong '@'. 
since you mentioned it's working fine for you, do you mind sharing the specific radix-ui versions and react versions you are using? `@types/react` and `@types/react-dom` too. 🙏🏼

**Comment by dalist1** [comment]
@cyyyu would be great if you could share precisely what's not working for you, everything's working well on my end, hence I closed the ticket. The issue was resolved a few days after the ticket was created.
