### ISSUE TITLE
Getting `(0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function`  Error when using Radix Scroll Area

### ISSUE THREAD

**Issue by Senbonzakura1234** [radix-ui/primitives#2920]
### Current Behavior
Getting this error when adding [Scroll Area](https://www.radix-ui.com/primitives/docs/components/scroll-area) to next@14 application

![image](https://github.com/radix-ui/primitives/assets/43206347/8f4fdf99-373d-4db7-a7a1-c32e9010d9a7)

### Expected behavior
The error shouldn't happen.

### Reproducible example
[repo example](https://github.com/Senbonzakura1234/debug-radix-scroll)

### Suggested solution
This error could be solved by adding `'use client'` directive, however this was never mention in [Scroll Area Docs](https://www.radix-ui.com/primitives/docs/components/scroll-area), the docs code snippet doesn't help either when the component of the code snippet doesn't have any interactives hooks, which mildly suggest user doesn't need `'use client'` when using the radix components.

Solutions:
- Update the documents to tell users need to add `'use client'` when using radix components,
- Or Fix the component itself so no need to add `'use client'`.

### Additional context
This possibly happenning with many radix components as well, including `dropdownmenu` that mentioned in [this issue](https://github.com/radix-ui/primitives/issues/2814)

### Your environment

| Software         | Name(s)            | Version |
| ---------------- | ------------------ | ------- |
| Radix Package(s) | scroll-area        | ^1.0.5  |
| React            | n/a                | ^18     |
| Browser          | all common browser | n/a     |
| Assistive tech   | n/a                | n/a     |
| Node             | n/a                | 20.11.0 |
| npm/yarn         | pnpm               | 9.0.6   |
| Operating System | windows            | 11      |

**Comment by vladmoroz** [comment]
All components that need `'use client'` now have that built-in in the latest RC versions
