### ISSUE TITLE
Text-decoration, hover and transition on Accordion on Safari not working

### ISSUE THREAD

**Issue by georgibakken** [radix-ui/primitives#2951]
### Current Behavior
Using text-decoration, hover and transition with Safari does not work as intended on the accordion, and the hover effect seems to be triggered when the item is not hovered.

Note that the background-color can update on hover as expected.

https://github.com/radix-ui/primitives/assets/16558100/ca414516-974b-454f-b438-d3e0bb15a707

Removing 
```css
text-decoration: underline;
text-decoration-color: transparent;
```
from `.AccordionTrigger` and adding `text-decoration: underline;` to `.AccordionTrigger:hover` makes the hover work, however for the transition to work, I need to have them defined in `.AccordionTrigger`. 

### Expected behavior

Screen recording of the expected behaviour, on Chrome

https://github.com/radix-ui/primitives/assets/16558100/ed408c4e-6f09-4da8-bbc6-4b449520e407

[Here](https://developer.mozilla.org/en-US/play?id=%2FRXFdVyPLb%2BQ9vlLJiTlNR1tyrVfGYBUjTcZdb%2FXX5aIbD0GnmrpW2Z4BuJezvk6bmT9f5XWoWYp87b1) is a simple html/css code example to show that text-decoration, transition and hover works with Safari

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/p/devbox/lucid-lumiere-2w24mt)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   radix-ui/react-accordion      |      1.1.2   |
| React            | n/a     |  18.2.0       |
| Browser          |    Safari     |     Version 17.5     |
| Assistive tech   |         |         |
| Node             | n/a     |      v22.2.0   |
| npm/yarn         |    pnpm     |     8.9.0    |
| Operating System |  macOS       |  14.5 (23F79)       |

**Comment by vladmoroz** [comment]
This is a bug with `<button>` styling in Safari and has nothing to do with the Accordion component itself

**Comment by georgibakken** [comment]
Thanks for looking at it. Do you have any reference to this bug so I know where to look ?

**Comment by vladmoroz** [comment]
No idea, I just swapped `p` for `button` in [your basic example](https://developer.mozilla.org/en-US/play?id=%2FRXFdVyPLb%2BQ9vlLJiTlNR1tyrVfGYBUjTcZdb%2FXX5aIbD0GnmrpW2Z4BuJezvk6bmT9f5XWoWYp87b1) to confirm it's a browser bug
