### ISSUE TITLE
No CHANGELOG provided for latest minor updates

### ISSUE THREAD

**Issue by NicoToff** [radix-ui/primitives#2962]
## Documentation

When running a package upgrade, I noticed all my radix dependencies had received a minor version update.

![image](https://github.com/radix-ui/primitives/assets/16281707/f6264087-1da9-4d89-b004-3f7c5ab45659)

I cannot find any release notes for what was achieved through this version bump. The only source for release notes from Radix seems to be this page, but it is not up to date: https://www.radix-ui.com/primitives/docs/overview/releases

Your lastest commit message simply says "New version" and I can't see any meaningful changes in there: https://github.com/radix-ui/primitives/commit/55f9189a4b3e1a525c89297d5f337c03b2a44f61#diff-1d4a374c4426c4f8a28833f6d0dbc797de781360e82a3c9ca2284accc893c54b

Could you please make it clear to users? Maybe provide a simple CHANGELOG file inside this repo, or use the "release" tab on GitHub as most other libraries do.

Thanks in advance.

**Comment by vladmoroz** [comment]
This is in the works, we'll have a the change log out today 🙂

**Comment by Sparticuz** [comment]
Where will that be posted?
