### ISSUE TITLE
Radix Checkbox - CheckedState is not exported

### ISSUE THREAD

**Issue by manchaary** [radix-ui/primitives#2973]
@radix-ui/react-checkbox **v1.1.0**

'CheckedState' is declared locally, but it is not exported.
![image](https://github.com/radix-ui/primitives/assets/4933317/91df410f-b047-41d1-8c84-d504a7857381)

Is it by design if yes what's the reasoning behind it?

**Comment by aphofstede** [comment]
Also getting this when @radix-ui/react-checkbox was bumped from 1.0.4 to 1.1.0

**Comment by vladmoroz** [comment]
Released 1.1.1
