### ISSUE TITLE
TooltipProviderProps no longer exported after update to @radix-ui/react-tooltip v1.1.1

### ISSUE THREAD

**Issue by ivy-lli** [radix-ui/primitives#2978]
## TooltipProviderProps no longer exported after update to @radix-ui/react-tooltip v1.1.1

Using shadcn/ui Tooltip component: https://ui.shadcn.com/docs/components/tooltip

### Current Behavior

![image](https://github.com/radix-ui/primitives/assets/42733123/71e6eef3-b2c9-49e6-b787-0aade3b679ad)

### Expected behavior

![image](https://github.com/radix-ui/primitives/assets/42733123/e1542d0d-02ce-4a28-af10-132290ec87fe)

### Reproducible example

Try to reexport the TooltipProvider

### Suggested solution

Not sure but maybe this change causes this problem? https://github.com/radix-ui/primitives/pull/2934/files#diff-da7e63370e718104438e4866d2cd43b3390689aa2c030321312c0be78602f544

### Additional context

I think this is also related to other issues like: https://github.com/radix-ui/primitives/issues/2973

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-tooltip | v1.1.1 |
| React            | n/a | v18.3.1 |
| TypeScript | n/a | v5.4.5 |
| Node             | n/a     | v20.10.0        |
| npm/yarn         | npm        | v10.2.3        |
| Operating System | macOs        | 14.5        |

**Comment by vladmoroz** [comment]
Released 1.1.2
