### ISSUE TITLE
Searchable Select Component 

### ISSUE THREAD

**Issue by MR-Mostafa** [radix-ui/primitives#3017]
### Current Behavior
When utilizing the Select component, we have integrated an Input field within it to allow users to search for Select items by entering a phrase. Our expectation is that upon entering a phrase, the Select items will dynamically update and display the desired list accordingly. However, we occasionally encounter the following unexpected error during this process.

```js
TypeError
Cannot read properties of null (reading 'focus')
```

[screen-capture.webm](https://github.com/user-attachments/assets/c1e77691-fc97-4a71-b24c-4ef7503dc0b2)

### Expected behavior
There should be no errors, and users should be able to search within the items.

### Reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/searchable-radixui-select-2l4xc3)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     react-select    |    2.1.1     |
| React            | n/a     |    18.2.0     |
| Browser          |    Chrome     |    126.0.6478.127 |
| Assistive tech   |         |         |
| Node             | n/a     |   20.15.1      |
| npm/yarn         |    yarn     |    1.22.19     |
| Operating System |    Windows 11 Pro |     22631.3296 |

**Comment by pohui0712** [comment]
I had faced same problem.

**Comment by sheikhaaliya** [comment]
I tried using this but this is causing issues with the select viewport as the search field width and select field is getting overlapped.
