### ISSUE TITLE
Possible bug using radix-select with react-hook-form

### ISSUE THREAD

**Issue by Canfus** [radix-ui/primitives#3068]
### Current Behavior

While using `radix-select` component with `react-hook-form` library and pick a some value, your picked value will overrided by empty string

If we log new value `./components/select-field/select-field.tsx:37`

![image](https://github.com/user-attachments/assets/044953ca-9594-4bea-a945-5479057ff1f9)

We can see logs look like this

![image](https://github.com/user-attachments/assets/a149e18f-0dbb-442b-a0e5-2ea40fdd7e03)

### Reproducible example

[Link to reproduce](https://codesandbox.io/p/sandbox/naughty-paper-qgym6l)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-select | ^2.1.1 |
| React            | n/a     | ^18.3.1 |
| Browser          | Google Chrome dev | 129.0.6628.3 |
| Assistive tech   |         |         |
| Node             | n/a     | 20.14.0 |
| npm/yarn         | pnpm | 9.3.0 |
| Operating System | Windows 10 | 19045.4529 |

**Comment by fxckdead** [comment]
I faced a similar issue today on my custom Select component, it's not really a bug.

the `onChange` is expecting an event `React.ChangeEvent<HTMLSelectElement>` (or any event from an input) so the value you must pass down needs to have at least `name`, `value` and `type`.

I use something like this:

```ts
function createFakeEvent<T>({
  name,
  value,
  type,
}: {
  name: string;
  value: string;
  type: "change" | "blur";
}) {
  // Create a synthetic change event
  const fakeEvent = new Event(type, {
    bubbles: true,
    cancelable: true,
  }) as unknown as React.ChangeEvent<T>;

  // Manually set the target with the desired value
  const eventTarget = { value, name } as T;

  Object.defineProperty(fakeEvent, "target", {
    writable: true,
    value: eventTarget,
  });
  Object.defineProperty(fakeEvent, "currentTarget", {
    writable: true,
    value: eventTarget,
  });

  return fakeEvent;
}
```

So later when I need to call it:

```tsx
    const onChangeHandler = React.useCallback(
      (value: string) => {
        // default radix change handler
        onValueChange?.(value);

        const targetName = rootProps.name || "";

        onChange?.(
          createFakeEvent<HTMLSelectElement>({
            name: targetName,
            value,
            type: "change",
          }),
        );
      },
      [onChange, onValueChange, rootProps.name],
    );
```

**Comment by Greg-Freeman** [comment]
@Canfus  did you resolve this? I'm having the exact same issue.

**Comment by Canfus** [comment]
> [@Canfus](https://github.com/Canfus) did you resolve this? I'm having the exact same issue.

Yes, i have a fast solution, you need just override `onChange` function in your controlled by `react-hook-form` component and avoid changing values with empty string

```tsx
const SelectField = (props) => {
  const { field } = useController({ ... })
  const { onChange, ...restField } = field

  const handleChange = (value: string) => {
    if (isStringEmpty(value)) return
    onChange(value)
  }

  return (
    <Select {...props} {...restField} onChange={handleChange} />
  )
}
```

**Comment by feidaZhang** [comment]
+1
