### ISSUE TITLE
```Popover```  is not clickable inside the ```Dialog```

### ISSUE THREAD

**Issue by Ssalvador221** [radix-ui/primitives#3079]
### Current Behavior
When the user opens the ```Dialog``` and tries to select an option in the ```Popover```, the click options are underneath the ```Dialog```, making the user unable to click.

https://github.com/user-attachments/assets/25d9984e-e204-4bb2-a118-44ce354b2e51

### Expected behavior
```Popover``` should be focused when is open.

**Comment by ricardolmsilva** [comment]
This will solve your issue 😊

https://github.com/radix-ui/primitives/issues/2121

**Comment by Ssalvador221** [comment]
Solution here.
https://github.com/radix-ui/primitives/issues/2121#issuecomment-2297459311

**Comment by mohammadazeemwani** [comment]
> This will solve your issue 😊
> 
> [#2121](https://github.com/radix-ui/primitives/issues/2121)

Saviour

**Comment by sefasenturk95** [comment]
This problem, at least for me is in regression when upgrading @radix-ui/react-dialog to 1.1.15
