### ISSUE TITLE
[Dropdown Menu] Support for `onOpenAutoFocus`

### ISSUE THREAD

**Issue by sekeidesign** [radix-ui/primitives#3125]
### Overview
We recently replaced our own `Popover` component to be built on top of `react-dropdown-menu` instead of `react-popover` since the two are almost identical, but the `DropdownMenu` also supports Submenus which is definitely something we want. 

The migration was essentially free since both of these components share the vast majority of functionality and props, with the exception of `onOpenAutoFocus`.

We use `onOpenAutoFocus` to prevent the `Popover` from grabbing focus in our `Combobox` which then uses the `Input` trigger's `onBlur` event to close the `Popover`.

Example:

https://github.com/user-attachments/assets/ea4400f0-90d0-464b-a064-dea95d8b0380

```
import * as RadixPopover from '@radix-ui/react-popover'
...
<RadixPopover.Content 
    onOpenAutoFocus={event => {
        if (preventAutoFocus) {
            event.preventDefault()
        }
    }}
...
>
```

**Compared with dropdown-menu**

https://github.com/user-attachments/assets/24228728-552d-45d3-9774-413292c4b150

```
import * as RadixPopover from '@radix-ui/react-dropdown-menu'
...
<RadixPopover.Content 
    // onOpenAutoFocus not supported!
...
>
```

Everything else is exactly the same and fully supported without any changes anywhere in our codebase.

### Examples in other libraries

Radix already supports this in other "popover" style components:
https://www.radix-ui.com/primitives/docs/components/popover#content

### Who does this impact? Who is this for?

It's a helpful event for managing focus that right now prevents us from using this component for our combobox.

**Comment by ilkiri23** [comment]
We were faced with a similar situation. It'd be very useful to have an `onOpenAutoFocus` prop

**Comment by sekeidesign** [comment]
> We were faced with a similar problem. It'd be very useful to have an `onOpenAutoFocus` prop

I tried forking and taking a stab at it, but it started causing some intensely buggy behaviour. I suspect the reason the prop isn't there is because managing the focus is critical to how the dropdown menu functions :(

I'll close this and open a new PR for adding a `Sub` item to the Popover, which might be a better solution

**Comment by sekeidesign** [comment]
> We were faced with a similar problem. It'd be very useful to have an `onOpenAutoFocus` prop

I tried forking and taking a stab at it, but it started causing some intensely buggy behaviour. I suspect the reason the prop isn't there is because managing the focus is critical to how the dropdown menu functions :(

I'll close this and open a new PR for adding a `Sub` item to the Popover, which might be a better solution

**Comment by sekeidesign** [comment]
Changed to this, since I think it may be a better solution
https://github.com/radix-ui/primitives/issues/3140
