### ISSUE TITLE
ScrollArea display: table issue not fixed

### ISSUE THREAD

**Issue by molvqingtai** [radix-ui/primitives#3129]
## Bug report
   * @see https://github.com/radix-ui/primitives/issues/926
   * @see https://github.com/radix-ui/primitives/pull/2945
   * @see https://github.com/radix-ui/primitives/issues/2722
   
   
I see that the fixed https://github.com/radix-ui/primitives/pull/2945 has been merged, but I installed the latest version "@radix-ui/react-scroll-area": ​​"^1.1.0" and the problem still exists

**Comment by Sh031224** [comment]
You should use version 1.2.0-rc.7, not 1.1.0.

**Comment by jose-costa-frontify** [comment]
I'm on version 1.2.0 and still have this issue, except previously I used the `display: block` fix, now I'm applying `min-width: 0` to the same element to achieve the same result. For me it's happening when elements within the scroll area contain text with ellipsis.

**Comment by tjx666** [comment]
Also still has this issue on @radix-ui/react-scroll-area v1.2.1

**Comment by nacho-villanueva** [comment]
I'm on @radix-ui/react-scroll-area v1.2.2 and I still have this issue

**Comment by anis-dr** [comment]
`display: table` is making the width of elements inside the scroll are bigger than it should.
Any solution for this please?

**Comment by eso8086** [comment]
> `display: table` is making the width of elements inside the scroll are bigger than it should. Any solution for this please?

ugly but just works

```css
[data-radix-scroll-area-viewport] > div{
  display: block !important;
}
```

**Comment by iranzithierry** [comment]
FIXED: <ScrollArea className="[&>div>div]:!block"> ....</ScrollArea/>
