### ISSUE TITLE
Unable to reset value in controlled mode in `useControllableState` 

### ISSUE THREAD

**Issue by flex-hyuntae** [radix-ui/primitives#3156]
## Bug report
1. Use controlled state in useControllableState hook
```
const [value, setValue] = useControllableState({
  prop: valueFromProps,
  defaultProp: valueFromDefaultProps,
  onChange: onChangeValueFromProps
})
```
2. but `valueFromProps` is undefindable like `valueFromProps?: string`
3. First `valueFromProps` is undefined
4. Second i will change value use `setValue` and call `onChangeValueFromProps` 
5. After 4, `valueFromProps` changed some value like `abc`
6. After 5, i want clear value. so i changed `valueFromProps` to `abc` to `undefined
7. but `value` from `useControllableState` is `abc`

I debug this issue. The cause is step 3.
when step 3, `useControllableState` work like uncontrolled state.
because in `useControllableState` check controlled or not like `prop === undefined`.
but this is bug because i want use controlled `useControllableState`

### Current Behavior
- `useControllableState` prop changed undefined to value. And init to undefined not work

### Expected behavior
- `useControllableState` prop changed undefined to value. And init to undefined work well

### Reproducible example

[CodeSandbox](https://codesandbox.io/p/sandbox/priceless-danilo-g3vlq4?workspaceId=78021ced-56d6-42ef-833f-3082d0c64b8a)

### Suggested solution
- `useControllableState`  check controlled or not like `prop in params`

### Additional context
- Maybe this issue is related
  - https://github.com/radix-ui/primitives/issues/1588 
  - https://github.com/radix-ui/primitives/issues/1569

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by chaance** [comment]
Works as intended. See the reply in the linked PR.
