### ISSUE TITLE
can't scroll react/select(2.1.2)

### ISSUE THREAD

**Issue by k70suK3-k06a7ash1** [radix-ui/primitives#3219]
### Current Behavior
can't scroll 

### Expected behavior
enable scroll

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by k70suK3-k06a7ash1** [comment]
https://github.com/shadcn-ui/ui/issues/1175

I have found a solution to the problem
Thank you for closing the Issue!

**Comment by daniellesuper** [comment]
@k70suK3-k06a7ash1 what was your solution?
