### ISSUE TITLE
react-scroll-area 1.2.1 introduces a breaking change by adding a new element

### ISSUE THREAD

**Issue by yspreen** [radix-ui/primitives#3247]
When updating between 1.2.0 and 1.2.1 a new element gets introduced in the DOM, breaking styling for child elements' height

<img width="331" alt="image" src="https://github.com/user-attachments/assets/24271d0e-54fc-4917-a3ea-2e6a13ef3d28">

h-full flex-grow no longer has any effect.

is there a solution for this?

**Comment by yspreen** [comment]
okay honestly I have no clue what's going on here but the change in the package was not was caused this I don't think

**Comment by FredrikMWold** [comment]
I was able to reproduce this, had to delete node_modules and run npm install while upgrading and downgrading. @yspreen

**Comment by yspreen** [comment]
@FredrikMWold I'm not sure I follow. deleting the node modules folder is a way to repro, or to fix the issue? or both?

**Comment by FredrikMWold** [comment]
Deleting the node_modules after upgrading or downgrading to reproduce the issue.

**Comment by vanquishkuso** [comment]
I spent too long trying to figure out what happened and to fix it until i found this issue. Downgrading works fine.
