### ISSUE TITLE
[Tooltip] Update to use `@xstate/fsm`

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#328]

**Comment by jjenzz** [comment]
I'm not sure about this anymore. While building Carousel I've realised that xstate really over-eagerly re-renders. I'm not usually bothered by this but triggering an event that gets swallowed by the machine still causes a re-render even tho state hasn't changed so, if you're triggering lots of events in an irrelevant state your component re-renders like crazy regardless.

This seems to defeat the point of using a state machine for me. If I want to take advantage of the swallowing, the swallowing should effectively behave as if nothing happened. I don't want perf to be impacted by swallowed events 😬

**Comment by benoitgrelard** [comment]
Gonna close this one for now then @jjenzz, reopen if you think we still need to keep it around.
