### ISSUE TITLE
[ContextMenu] Fix `pointer-event` conflicts

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#330]
When `ContextMenu` is open with `disabledOutsidePointerEvents`, you cannot right-click another `ContextMenuTrigger` to activate its menu. This makes sense logically, but this is not the UX expectation. 

Users should be able to right-click to open another context menu, regardless of whether one is open.

This should only be possible for triggers that are not below another layer (e.g. from `Dialog`) that disables pointer events.

**Comment by benoitgrelard** [comment]
Involuntary fix 😀
