### ISSUE TITLE
DropdownMenu changes padding / margin on document body.

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#346]
### Current Behavior

When active, the DropdownMenu component adds the following CSS to the document body.

```css
  body {
    overflow: hidden !important;
    position: relative !important;
    padding-left: 8px;
    padding-top: 8px;
    padding-right: 8px;
    margin-left:0;
    margin-top:0;
    margin-right: 0px !important;
  }
```

This can cause layout shift on layouts that have set padding / margin on the body.

### Expected behavior

Opening the dropdown should not cause the layout to shift.

### Reproducible example

[Codesandbox](https://codesandbox.io/s/bold-kepler-l8npc?file=/src/styles.css).

### Suggested solution

I'm guessing that the margins / padding have a function, though it isn't clear to me what that is. As long as that part of the CSS may be removed without breaking the component, I would suggest removing the padding / margins.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   Dropdown      |       0.0.1  |
| React            | n/a     |    17.0.0     |
| Browser          |     Chrome    |         |
| Assistive tech   | n/a         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  Mac        |         |

**Comment by raunofreiberg** [comment]
I'm fairly certain that this comes from the `@radix/react-menu` package using [`react-remove-scroll`](https://www.npmjs.com/package/react-remove-scroll) which removes the document scrollbar (as a result of an overlay being open) while maintaining its space.

As a workaround, don't place your padding or margin on the `body` element.

**Comment by steveruizok** [comment]
Noted, though even with a project where the body has no padding / margin, this will add padding and cause a layout shift.

**Comment by chaance** [comment]
It shouldn't cause a layout shift, in fact it's designed to prevent it. But you do need to set `margin: 0` on the body, and as @raunofreiberg mentioned it's generally a good idea to avoid adding margin and padding directly to the body and instead using an inner element for that. Here's a fork of your sandbox showing that in action: https://codesandbox.io/s/damp-snow-ev0rd?file=/src/App.tsx

That said, we probably need to add documentation to clear this up if we don't have it already. If you still have layout shift after making those adjustment, let me know and we can definitely investigate further.

**Comment by steveruizok** [comment]
Right on, so to boost that for anyone coming here in the future, adding `margin: 0;` to body fixes the problem. 👍 

```css
body {
  margin: 0;
}
```

**Comment by pacocoursey** [comment]
Just me or has this broken again? I'm seeing weird behavior – either the Dropdown (or Context) menus are wayy too low from the trigger, or opening/closing the Menu causes the entire page to jump.

I bumped all the packages in Chance's example above and you can see the offset problem: https://codesandbox.io/s/admiring-brown-dn7e7?file=/src/App.tsx

Could this be re-opened?

**Comment by pacocoursey** [comment]
Ping @benoitgrelard and @jjenzz since you may not be following this issue alreaddy

**Comment by benoitgrelard** [comment]
@pacocoursey yes this is such a frustrating issue.

It's kinda like a compound issue:

- as @raunofreiberg mentioned, we use `react-remove-scroll` which does a bunch of things we can't control. One of these is it sets `position: relative` on the `body`.
- our popper solution doesn't support parent static contexts as we mostly rely on portalling
- with a basic setup like in your sandbox (even though you have `padding: 0`, `margin: 0` on `body`), `body` will not start at `top: 0` because of collapsing margins

So the extra gap you're seeing is because of all that.
There are a few ways to get around it but the gist of it is you want to get rid of the collapsing margins on that parent.

The easiest way would be to add `style={{ margin: -1, padding: 1 }}` to your top-level app like so:
https://codesandbox.io/s/dropdownmenu-corrected-collapsing-margins-iiop9

**Comment by steveruizok** [comment]
> * as @raunofreiberg mentioned, we use `react-remove-scroll` which does a bunch of things we can't control. One of these is it sets `position: relative` on the `body` (We're hoping to soon take control of this by creating our own solution which hopefully would give us more control)

Hey, coming back to this as it's causing a strange layout issue for me. Any element with an `absolute` position that is taking its height as a percentage of the `body` will be thrown off once the `body`'s position changes to `relative`.

Here's a repro: https://codesandbox.io/s/body-relative-issue-zz4q3?file=/App.js

In my case, I'm able to set the size as `fixed`, which solves the problem, but I can imagine cases where it would cause issues.

**Comment by upq** [comment]
It adds a `margin-right: 17px !important` to the body, so unless you override that using important inline styles it will never work .. I don't know why is this closed anyway ..

**Comment by jjenzz** [comment]
adding the following styles to your `body` should prevent issues i believe:

```jsx
body {
  display: flow-root;
  min-height: 100vh;
}
```

**Comment by benoitgrelard** [comment]
Or the solution provided above: https://github.com/radix-ui/primitives/issues/346#issuecomment-817690787

**Comment by jjenzz** [comment]
@benoitgrelard that doesn't solve @steveruizok's example unfortunately. the snippet i posted should work for everyone i believe.

**Comment by mithleshjs** [comment]
> ```css
> flow-root
> ```

It is not working as ```display: flow-root;```  gets replaced by ```display: relative !important;```
None of the above solution is working right now.

**Comment by mithleshjs** [comment]
> adding the following styles to your `body` should prevent issues i believe:
> 
> ```css
> body {
>   display: flow-root;
>   min-height: 100vh;
> }
> ```

@jjenzz It is not working as ```display: flow-root;```  gets replaced by ```display: relative !important;```
None of the above solutions is working right now.

**Comment by benoitgrelard** [comment]
@mithleshjs I'm confused, `display: relative` isn't a thing. Are you talking about `position: relative`?
Regardless, I don't believe `display` is set so you shouldn't have any issue with overrides.

**Comment by mithleshjs** [comment]
> @mithleshjs I'm confused, `display: relative` isn't a thing. Are you talking about `position: relative`? Regardless, I don't believe `display` is set so you shouldn't have any issue with overrides.

@benoitgrelard Sorry, it was a typo and badly explained. What I meant was even if you set `display: flow-root;`, the problem still persists due to this style ```position: relative !important;``` being applied by the library on the body. The solution that worked for me (using Tailwind):

```html 
<body>
   <div className='fixed w-full top-0 bottom-0 overflow-x-auto'>
       content...
   </div>
</body>
```

**Comment by rayjasson98** [comment]
As mentioned by @upq:
> It adds a `margin-right: 17px !important` to the body, so unless you override that using important inline styles it will never work .. I don't know why is this closed anyway ..

**Added body styles in Radix UI website**
```css
body {
    overflow: hidden !important;
    position: relative !important;
    padding-left: 0px;
    padding-top: 0px;
    padding-right: 0px;
    margin-left: 0;
    margin-top: 0;
    margin-right: 17px !important;
}
```

**Added body styles in my web project**
```css
body {
    overflow: hidden !important;
    position: relative !important;
    padding-left: 0px;
    padding-top: 0px;
    padding-right: 17px; /* main culprit */
    margin-left: 0;
    margin-top: 0;
    margin-right: 17px !important;
}
```

`margin-right: 17px` is unlikely the root cause of this problem. From my observation, I have an additional `padding-right: 17px` which is the main culprit of this layout shift issue. I really wonder from where I get this additional padding.

By the way, thanks @mithleshjs! Your solution works. I am using Tailwind too. May I know why adding these classes will help solve the issue?

**Comment by hedysnike** [comment]
how do i keep the radix from resizing thou

**Comment by aryanas159** [comment]
Putting modal={false} on the root dropdown element fixed it for me.

**Comment by Apsysikal** [comment]
> > @mithleshjs I'm confused, `display: relative` isn't a thing. Are you talking about `position: relative`? Regardless, I don't believe `display` is set so you shouldn't have any issue with overrides.
> 
> @benoitgrelard Sorry, it was a typo and badly explained. What I meant was even if you set `display: flow-root;`, the problem still persists due to this style `position: relative !important;` being applied by the library on the body. The solution that worked for me (using Tailwind):
> 
> ```
> <body>
>    <div className='fixed w-full top-0 bottom-0 overflow-x-auto'>
>        content...
>    </div>
> </body>
> ```

This worked for me, thanks

**Comment by efremovag** [comment]
In NextJS: 
add `<body style={{ margin: '0px !important' }}>`

**Comment by dvnrsn** [comment]
This was a problem for me because we had
```css
html {
  overflow-x: hidden;
}
```

**Comment by alexRicc2** [comment]
> Putting modal={false} on the root dropdown element fixed it for me.

it works! the only downfall is that now the page is scrollable while the dropdownmenu is open
