### ISSUE TITLE
Tooltip position incorrect when portalled = false inside positioned parent container

### ISSUE THREAD

**Issue by mattaningram** [radix-ui/primitives#367]
### Current Behavior

With the default `portalled` behavior the tooltip appears in the correct position:

<img width="425" alt="Screen Shot 2020-12-23 at 11 21 24 AM" src="https://user-images.githubusercontent.com/955092/103017096-1c826400-4511-11eb-969a-4e6ded41d392.png">

With `portalled` set to `false` the tooltip wrapping div does appear in the correct place in the DOM, but it has a large `translate3d` value set to it meaning it is not visible. This `translate3d` value is the same as the portalled version meaning its calculating from the corner of the screen.

<img width="909" alt="Screen Shot 2020-12-23 at 11 24 11 AM" src="https://user-images.githubusercontent.com/955092/103017425-974b7f00-4511-11eb-8a26-f325bfe7ce86.png">

If I remove the `translate3d` from the wrapper, the tooltip is visible, but still in the wrong position:

<img width="442" alt="Screen Shot 2020-12-23 at 11 27 00 AM" src="https://user-images.githubusercontent.com/955092/103017627-e2fe2880-4511-11eb-8a46-da9ead076ff6.png">

### Expected behavior

Visual position of tooltip should be the same for both portalled and not portalled. The tooltip being positioned needs to know if positioning is relative to screen or a parent container with a position set.

### Reproducible example

[CodeSandbox Example](https://codesandbox.io/s/radix-primitives-tailwind-forked-ie4xb?file=/src/App.tsx)

### Suggested solution

Update positioning logic to take into account parent containers which change 0, 0 position.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Tooltip | 0.01 |
| React            | n/a     | 16.12  |
| Browser          |  Chrome, FF, Safari, Edge       | Latest |
| Assistive tech   | n/a        |         |
| Node             | n/a     |  10.17       |
| npm/yarn         | Yarn | 1.22.10 |
| Operating System | Mac + Windows | Latest |

**Comment by benoitgrelard** [comment]
Hi @mattaningram, thanks for reporting this.

Historically we were really focused on portal’ed content, so our current positioning solution isn't really an issue for this.
However, if we are to support non-portal’ed content (albeit less common and useful IMO) we probably will need to upgrade our positioning solution to account for various parent positioning/scroll offsets, etc.

This is not something we have had the time to do before the launch at xmas, but I'll add an issue to track it.

In the meantime, I hope it's not a dealbreaker for you and you are still able to use our components.

**Comment by benoitgrelard** [comment]
Tracking here: #370

**Comment by mattaningram** [comment]
I can only use the portalled version if we can control the z-index of the content in the `radix-portal`, otherwise the tooltips appear behind my modals and overlays which are also portalled but have a z-index that we can't remove yet: https://github.com/radix-ui/primitives/issues/368

**Comment by tarngerine** [comment]
hi, ran into the same issue, wanted to share a use case

building something like figma, with a `position: fixed` navigation bar (where we have the dropdown menus), and an open scrolling DOM canvas

i originally started with the portalled option, but we want people to be able to scroll when our menus are open, but portalled content currently scrolls away, and disabling scroll also causes the UI to jump for users with scrollbars shown on macOS

so, i wanted to try a non-portalled option, and this still doesn't work, because unless the user is at scroll 0,0, the menu renders out of position

it seems like a case where a typical absolute positioning without JS calculations would be fine — is there a way to just disable the fancy calculation?

e.g.
 
```
  <Root style={{position: 'relative'}}>
    <Trigger>...</Trigger>
    <Content style={{position: 'absolute', top: '100%', ...}}>...</Content>
  </Root>
```

**Comment by benoitgrelard** [comment]
Hey @tarngerine, we've always known that the positioning logic, whilst very useful, might not always fit every single use case. So we did discuss in the past that we should allow a custom function to be passed in to override the positioning logic. It would mean that from then on you would be entirely on your own (ie. no collision handling, etc), but it would probably enable some of these use cases.

This is something we will be adding pretty soon I think.

**Comment by tarngerine** [comment]
yea, i think in the case of a fixed UI, we generally know where the button will be, so we can use `right: 0` or `left: 0` to handle positions on the left and the right

is there some reading i can do on why portalling is the preferred method? im running into a few issues with it, some of which i can work around, but it's increasingly feeling hacky

one example is that `pointer-events: none` is applied to the body whenever a menu is opened — why is this necessary? i can fix it by applying a `poitner-events: auto` somewhere in the react root, but feels like applying duct tape

**Comment by benoitgrelard** [comment]
The pointer-events thing can be controlled via a prop: `disableOutsidePointerEvents`. You can turn that off if you don't want/need it. It is there to block interactions when clicking outside do dismiss the menu.

**Comment by benoitgrelard** [comment]
Closing this issue as it's been captured here: https://github.com/radix-ui/primitives/issues/370
