### ISSUE TITLE
New component: Submenu

### ISSUE THREAD

**Issue by chaance** [radix-ui/primitives#383]
See https://github.com/radix-ui/primitives/discussions/375

**Comment by andy-hook** [comment]
Some research from earlier this week

## MacOS

https://user-images.githubusercontent.com/11708259/115904712-0358d800-a45d-11eb-874b-a2fedfb8e9c9.mov

Notable interactions
- Closes entire menu on `Esc` press

## Chrome

https://user-images.githubusercontent.com/11708259/115904775-179cd500-a45d-11eb-865d-b2e10c786273.mov

Notable interactions
- Closes individual sub menus with each `Esc` press
- Provides a debounced, timer based closing mechanism when browsing the parent menu. After interacting with the sub menu it will remain open until moving back to the parent.

## Figma

https://user-images.githubusercontent.com/11708259/115904831-2be0d200-a45d-11eb-89c3-92670fcff9de.mov

Notable interactions
- Closes individual sub menus with each `Esc` press
- Menus remain open until interacting with the parent menu

### Baseline requirements

- Must be keyboard navigable
- Must be able to open and close sub menus with `ArrowLeft` / `ArrowRight` and `Esc` / `Enter`
- Must focus first in list when opening via keyboard (saves a keypress)
- Must support multiple levels ("infinitely" nest-able)
- Must highlight item in parent list from which the sub menu originates
- Must close entire menu when clicking outside

### Additional thoughts for our implementation

- Should close sub menus individually for each `Esc` press per the chrome / figma example
- Should offer some amount of pointer grace at the contact edge for easier motor control (will need to test if this is necessary on average)

### Initial api thoughts

I'm thinking we add a couple more primitives to our [base Menu](https://github.com/radix-ui/primitives/blob/main/packages/react/menu/src/Menu.tsx) which provide uniform behaviour for the keyboard and pointer interactions. How that is exposed publicly will depend on the component, but they will likely be [name spaced and exported verbatim](https://github.com/radix-ui/primitives/blob/b2807bc610e04fe4088a36a279ffd9c1b2fb3a6c/packages/react/dropdown-menu/src/DropdownMenu.tsx#L176-L200)

Will follow up with an api proposal shortly.
