### ISSUE TITLE
New component: Toast

### ISSUE THREAD

**Issue by chaance** [radix-ui/primitives#386]
See https://github.com/radix-ui/primitives/discussions/375

**Comment by chaance** [comment]
Some preliminary research on the `Toast`:

- [Google's proposed `<std-toast>` element](https://github.com/jackbsteinberg/std-toast) is the most comprehensive existing overview of popular `Toast` implementations in the wild I could find.
- Lots of discussion on `<std-toast>` exists, with many noting accessibility issues in the concept itself. There are many potential problems we can attempt to mitigate, but the fact is that the very nature of messages that disappear after a set amount of time ensures that some users will likely miss those messages. [This is a good overview of the potential WCAG issues and mitigation strategies by Adrian Roselli.](https://adrianroselli.com/2020/01/defining-toast-messages.html)
- Based on Adrian's article and pattern's that exist in native environments, I believe the best thing we can do for a generic `toast` package is to provide not only the `Toast` message and its top-level container (`ToastEmitter`?), but also a separate container that contains all toasts that haven't been manually dismissed by the user. This is similar to the MacOS notification center.

I really like some of the implementations in [`react-hot-toast`](https://react-hot-toast.com/docs/use-toaster). I'd like to take some heavy inspiration from there and build on it to design our API.

Here's an initial rough sketch of what I'm envisioning as far as the API goes:

```js
function App() {
  // expose ToastProvider to manage all global toast state
  return (
    <ToastProvider>
      <AppInner />
    </ToastProvider>
  );
}

function AppInner() {
  const [notificationsVisible, setNotificationsVisible] = React.useState(false);
  return (
    <div>
      <header>
        <MainNav />
        <button onClick={() => setNotificationsVisible(!notificationsVisible)}>
          Notifications
        </button>
        {notificationsVisible ? (
          <div>
            {/* Space for all active toasts to appear until user dismisses */}
            <ToastCenter>{({ toasts }) => toasts.map((toast) => <Toast {...toast} />)}</ToastCenter>
          </div>
        ) : null}
      </header>
      <main>
        <Content />
      </main>
      <aside>
        <Sidebar />
      </aside>
      {/* Space for current active toasts to appear */}
      <ToastEmitter>{({ toasts }) => toasts.map((toast) => <Toast {...toast} />)}</ToastEmitter>
    </div>
  );
}

```

Similar to `Announce`, messages are read globally from an `aria-live` container. A key difference for `Toast` I think is that we will actually need to do some global state management, as we'll have at least a few key pieces of stateful global data to deal with:
- Current active toasts (toasts that appear until either the user dismisses them or their timer runs out)
- All active toasts (all toasts that haven't been dismissed manually by the user)
- A timer for each toast, as well as the ability to pause/resume the timer based on a user's interaction with it

More reading:
- https://www.scottohara.me/blog/2019/07/08/a-toast-to-a11y-toasts.html

**Comment by jjenzz** [comment]
Oooo, I like the notification center idea. I'm not sure about the "emit" proposal though. That's all starting to feel a bit like we're supplying imperative application code. I would favour a more declarative component-based approach with the help of portals. Plus, I would expect that when a `Toast` is rendered, that would implicitly be the emitter. 

Something along the lines of:

```jsx
function App() {
	return (
		<ToastProvider>
			<header>
				<button>Notifications</button>
				{isNotificationCenterOpen && <ToastCenter />}
			</header>
			<main>
				<Profile />
				<ToastPortal />
			</main>
		</ToastProvider>
	);
}

function Profile() {
	// whatever declarative data management thing consumer uses (or just state)
	const [{ error, success }, saveProfile] = useSaveProfile();

	return (
		<form>
			{/* ... */}
			<button onClick={() => saveProfile()}>Save</button>
			{success && <Toast message="Whoop! It worked!" />}
		</form>
	);
}
```

My thinking here is that:

- `ToastProvider` provides the necessary context.
- `ToastCenter` renders a container that `Toast`s get **copied** into.
- `ToastPortal` (not sure on name here) renders a container that timed `Toast`s get **portalled** into.
- `Toast` portals into `ToastPortal` and gets cloned into `ToastCenter`.

I like this approach because:

- The `Toast` can be consumed where it is needed alongside the code that triggers it and its styles/events/props will apply in both contexts (center and portal). 
- It will work completely uncontrolled without the consumer needing to map out the toasts in two separate contexts manually.

Since I'm so terrible at explaining things, I've thrown together a quick sandbox to demonstrate my thinking for further discussion. There may be issues with this approach that we would need to flesh out, I've literally just built it on the spot so wouldn't know unless we investigated it further https://codesandbox.io/s/relaxed-worker-6m27d?file=/src/App.js

**Comment by chaance** [comment]
@jjenzz appreciate the example, I quite like that approach as well! I'm going to start by mapping out a state chart and then start working on the API with your alternative as a starting point 👍

**Comment by benoitgrelard** [comment]
@jjenzz I can't seem to be able to load that sandbox, is it just me?

**Comment by jjenzz** [comment]
@benoitgrelard I must have broken the link by mistake, sorry. Edited and it's working now

**Comment by chaance** [comment]
Expanding on the API design a bit. @colmtuite would love your input here as well!

This is intended to showcase different possible APIs I'm imagining. Real implementation would probably be a lot simpler in practice, but a few thoughts to explain what I'm thinking here:
- An individual `Toast` will be rendered alongside the component that triggers it, which is far away from the portal where they appear. This raises the question: which component is responsible for composing the various parts?
  - In my mind, it generally makes sense for toasts to be composed where they show up visually, which is either in the `ToastCenter` (all toasts) or the `ToastWarmer` (visually active toasts). This is because they generally appear differently in these contexts, and all toasts within each contexts generally share similar style attributes.
  - That said, in some cases it may be desirable to compose a toast where it is rendered. In those cases, the API below uses children as a render prop that would be used in lieu of the composition dictated in the `ToastWarmer`. This would be entirely left up to the consumer to decide how to deal with this, but this exposes a mechanism for overriding any rendering done in either visual container.
- As we will need to manage some state for this component, we also need to expose it to the various parts. I like to expose it via hooks and render props and let consumers decide which works best in a given context, but we can stick with just hooks for simplicity if everyone else prefers. Examples below show both.
- Potential names for the area where toasts show up visually as they are triggered:
  - `ToastWarmer` (kind of silly, but so is the name `Toast` so 🤷‍♂️)
  - `ToastPortal` (more technically accurate but not really reflective of the fact that we're only rendering the ephemeral toasts vs. all toasts like in `ToastCenter`, which could also be a portal!
  - `ToastActivePortal` (longer names are blah but it's a bit more specific?)
  - [your brilliant idea here!]

```js
function App() {
  // expose ToastProvider to manage all global toast state
  return (
    <ToastProvider>
      <AppInner />
    </ToastProvider>
  );
}

function NotificationCenter() {
  // all toasts manageged by the state machine in ToastProvider
  // so they could be accessible here via a hook, or...
  const { allToasts, dismiss } = useToasts();

  // Not doing anything magic! Lets consumers build the notification
  // center however they'd like.
  const toastsByDate = allToasts.reduce(someCoolReducer);

  <ToastCenter>
    {({ toasts: allToasts, dismiss }) => {
      // ...as a render children prop
      const toastsByDate = allToasts.reduce(someCoolReducer);

      return toastsByDate.map(({ date, toasts }) => (
        <Box>
          <Flex>
            <Title>{date.fullDateText}</Title>
            {/* Toasts can be dismissed imperatively by id or array of ids */}
            <Button onClick={() => dismiss(toasts.reduce(getToastIds))}>
              Dismiss All
            </Button>
          </Flex>
          {toasts.map((toast) => (
            <ToastCenterItem id={toast.id} as="div" type={toast.type}>
              {/* Toasts can be dismissed declaratively */}
              <ToastDismiss aria-label="Dismiss notification" />
              <Box>
                <Heading>{toast.label}</Heading>
                <Text>{toast.message}</Text>
              </Box>
            </ToastCenterItem>
          ))}
        </Box>
      ));
    }}
  </ToastCenter>;
}

function NotificationArea() {
  const { activeToasts, dissmiss } = useToasts();
  return (
    <ToastWarmer
      duration={5000} // Duration for all toasts to show unless overridden
      as="div"
    >
      {/* render props API here too? maybe? */}
      {({ activeToasts }) => {
        return activeToasts.map((toast, i, arr) => (
          <>
            <ToastWarmerItem
              id={toast.id}
              as="div"
              // Declarative type prop for common toast types for better
              // internal aria-live handling. "error" or "success" might be
              // "assertive", whereas "loading" or "basic" might be polite.
              type={toast.type} // "loading" | "success" | "error" | "basic"
              // Aria can be overridden as well
              role={toast.role}
              role="alert"
              aria-live={toast["aria-live"]}
              aria-live="off"
              // Individual toast duration could override ToastWarmer duration
              duration={toast.duration} // number
              // This could be set on individual toasts as they are rendered, or
              // in ToastWarmerItem for general overrides
              duration={toast.type === "error" && 10000} // number
              // For some active toasts, maybe the duration is dictated by state
              // somewhere, and we can control it with a progress prop.
              progress={toast.progress} // number
              // This could be set on individual toasts as they are rendered, or
              // in ToastWarmerItem for general overrides
              progress={toast.type === "loading" && getProgress(toast.id)} // number
            >
              {toast.children ? toast.children(toast) : (
                <>
                  <ToastDismiss aria-label="Dismiss notification" />
                  <Box>
                    <Heading>{toast.label}</Heading>
                    <Text>{toast.message}</Text>
                  </Box>
                </>
              )}
            </ToastWarmerItem>
            {i !== arr.length - 1 ? <Spacer /> : null}
          </>
        ));
      }}
    </ToastWarmer>
  );
}

function SaveButton() {
  // whatever declarative data management thing consumer uses (or just state)
  const [state, saveProfile] = useSaveProfile();

  let toast = null;

  if (state.value === "loading") {
    toast = (
      <Toast
        label="Saving"
        message={`File is saving, currently at ${Math.round(
          state.context.progress * 100
        )}%`}
        progress={state.context.progress}
        type="loading"
      />
    );
  }

  if (state.value === "error") {
    return (
      <Toast
        label="Save error"
        message={state.context.error.message}
        progress={state.context.progress}
        type="error"
      />
    );
  }

  if (state.value === "success") {
    return (
      <Toast
        label="File saved"
        message="Yay, your file has been saved!"
        type="success"
      >
        {({ label, message }) => (
          <>
            <ToastDismiss aria-label="Dismiss notification" />
            <Box>
              <Heading>{toast.label}</Heading>
              <Text>{toast.message}</Text>
              <SuccessAnimationIcon />
            </Box>
          </>
        )}
      </Toast>
    );
  }

  return (
    <>
      <Button onClick={() => saveProfile()}>
        <Text>Save</Text>
      </Button>
      {toast}
    </>
  );
}
```

**Comment by benoitgrelard** [comment]
This is cool!

A few questions/suggestions:

- re. the notifications center idea thing. Is this something that users "have" to do, ie. for accessibility reasons, or is it just us proposing that it might be useful? Seems quite prescriptive to me for now.
- will this use our `Announce` component somehow under the hood?
- re. `ToastWarmer`, `ToastPortal`, `ToastActivePortal` naming. How about just `ActiveToasts`?
- there are quite a few concepts in the `Toast`, like label, message, type, etc. Are these standardised? It feels again quite prescriptive to me for now. Ie. what if someone needs the message to be formatted somehow and therefore needs JSX, can't be just a string, etc.
- if we're going to do declarative `Toast` at the point of render to raise them, how are we ensuring that they don't re-trigger if the parent re-renders? I can't see the id so I'm assuming we generate it, in which case how do we distinguish already raised toasts?

Not a huge fan of the render prop for the `Toast` but again, this comes as an issue we have because we have this notifications center thing, so will depend on that I guess.

**Comment by chaance** [comment]
> * re. the notifications center idea thing. Is this something that users "have" to do, ie. for accessibility reasons, or is it just us proposing that it might be useful? Seems quite prescriptive to me for now.

It certainly is prescriptive, but the problem is that without it or something like it, it's essentially impossible to make a toast that doesn't violate WCAG. [This article outlines several problems with the core design of the toast](https://adrianroselli.com/2020/01/defining-toast-messages.html#1.3.2) that I'm not sure can be overcome without it.

> * will this use our `Announce` component somehow under the hood?

I believe so, but that will require some screen reader testing to be sure. The potential concern is timing -- you need to ensure a toast is visible long enough for both a user and a screen reader to read it, which is ultimately something consumers will have to consider in their designs. This could be particularly tricky when `aria-live` is set to `"polite"`, as the SR may be reading something else that eats into the `Toast`'s time on screen.

> * there are quite a few concepts in the `Toast`, like label, message, type, etc. Are these standardised? It feels again quite prescriptive to me for now. Ie. what if someone needs the message to be formatted somehow and therefore needs JSX, can't be just a string, etc.

`label` I'm not 100% sure we will need. `message` would be the simplest interface because the SR announcement should always be test. We should support any kind of composition in `Toast` and use `element.innerText`if there is no `message`, but that's potentially troublesome if the inner HTML has a composition that doesn't make sense when read as a single sentence. I envision `message` could be used in lieu of composition if the toast is simple, or alongside composition as a simplified supplement for better SR support.

Consider:

```jsx
<Toast>
  <header>
    <Heading>Warning: Error</Heading>
    <ToastDismiss>
      <VisuallyHidden>Dismiss error</VisuallyHidden>
      <CloseIcon />
    </ToastDismiss>
  </header>
  <div>
    <Text>Oh no! You have a major problem!</Text>
    <ToastDismiss>Dismiss error</ToastDismiss>
  </div>
</Toast>
```

Using the HTML inner text here would be needlessly verbose, repetitive, and would read like a run-on sentence. The way `Announce` works is that it needs to mirror some text into a visually hidden live-region. It's quite a bit different than `aria-describedby` or `aria-label`, so this is what I imagine the `message` prop can solve.

```jsx
<Toast message="Oh no! You have a major problem!">
  {/* compose whatever you'd like */}
</Toast>
```

As for `type`, this too is probably a bit prescriptive, but I think it can be helpful for users for a few reasons.
- I think the vast majority of needs will fit into one of these categories, so for most people they don't need to think about anything else other than whether or not a toast is an error message, success message, etc.
- We can use this type to handle ARIA for them. For example, an error or success message *probably* make the most sense with `role="alert" aria-live="assertive"`, while other types of messages *probably* shouldn't interrupt the user, so we'd use `role="status" aria-live="polite"` (or possibly `role="log"`).

> * if we're going to do declarative `Toast` at the point of render to raise them, how are we ensuring that they don't re-trigger if the parent re-renders? I can't see the id so I'm assuming we generate it, in which case how do we distinguish already raised toasts?

No differently really than rendering anything else, really. They should always be conditionally rendered by the consumer based on some state, but we'll also be managing them internally via context where we will need to generate IDs for those. This does raise an interesting question though.

```jsx
function Profile() {
  const [status, saveProfile] = useSaveProfile();
  return (
    <form>
      {/* ... */}
      <button onClick={() => saveProfile()}>Save</button>
      {status === 'success' && <Toast message="Whoop! It worked!" />}
    </form>
  );
}
```

In Jenna's example above, `Toast` renders when status is success, but of course when it times out in our app-level toast context `status` may still be `success`, so we'd just return `null` internally if the timer for that toast ID has run its course or if the user has dismissed that message.

Now, what happens when the user clicks the `Save` button again? `status` presumably changes to `loading` or something, but when it returns back to `success` we are still rendering the same toast based on the generated id, so presumably it wouldn't appear for the second save action 🧐

The consumer could do something like...

```jsx
function Profile() {
  const [status, saveProfile] = useSaveProfile();
  const [toastId, setToastId] = React.useState(1);
  React.useEffect(() => {
    if (status === 'success') {
      setToastId(i => i++)
    }
  }, [status]);
  return (
    <form>
      {/* ... */}
      <button onClick={() => saveProfile()}>Save</button>
      {status === 'success' && <Toast id={`save-${toastId}`} message="Whoop! It worked!" />}
    </form>
  );
}
```

The consumer uses their own ID to signal that the toast is new on each `success` status. But now we have a new problem -- what if the previous toast is still on screen when this happens? It would go away because the ID of the toast we're rendering in this component has changed. Now it might get a little funkier.

```jsx
function Profile() {
  const [status, saveProfile] = useSaveProfile();
  const [toastIds, setToastIds] = React.useState([]);
  React.useEffect(() => {
    if (status === 'success') {
      setToastIds(t => [...t, t[t.length - 1] + 1])
    }
  }, [status]);
  return (
    <form>
      {/* ... */}
      <button onClick={() => saveProfile()}>Save</button>
      {toastIds.map((id) => <Toast key={id} id={`save-${id}`} message="Whoop! It worked!" />)}
    </form>
  );
}
```

This probably works a little better but feels awkward that we're kind of offloading React complexity to work around what is probably unexpected behavior, but I think this ends up being a potentially common scenario. Kind of wondering if the originally proposed "imperative" API doesn't actually become a bit simpler here.

```jsx
import { emitToast, Toast } from '@radix-ui/react-toast';

function Profile() {
  const [status, saveProfile] = useSaveProfile();
  React.useEffect(() => {
    if (status === 'success') {
      emitToast(() => (
        <Toast message="Whoop! It worked!" />
      ))
    }
  }, [status]);
  return (
    <form>
      <button onClick={() => saveProfile()}>Save</button>
    </form>
  );
}
```

We could provide a hook to simplify this somewhat:

```jsx
import { useToastEmit, Toast } from '@radix-ui/react-toast';

function Profile() {
  const [status, saveProfile] = useSaveProfile();
  useToastEmit(
    // condition
    status === 'success',
    // callback to render the toast
    () => <Toast message="Whoop! It worked!" />
  );
  return (
    <form>
      <button onClick={() => saveProfile()}>Save</button>
    </form>
  );
}
```

**Comment by benoitgrelard** [comment]
> > * re. the notifications center idea thing. Is this something that users "have" to do, ie. for accessibility reasons, or is it just us proposing that it might be useful? Seems quite prescriptive to me for now.
> 
> It certainly is prescriptive, but the problem is that without it or something like it, it's essentially impossible to make a toast that doesn't violate WCAG. [This article outlines several problems with the core design of the toast](https://adrianroselli.com/2020/01/defining-toast-messages.html#1.3.2) that I'm not sure can be overcome without it.

I see. Does that mean if someone doesn't include a notification center in their app, they won't be accessible then?

> > * will this use our `Announce` component somehow under the hood?
> 
> I believe so, but that will require some screen reader testing to be sure. The potential concern is timing -- you need to ensure a toast is visible long enough for both a user and a screen reader to read it, which is ultimately something consumers will have to consider in their designs. This could be particularly tricky when `aria-live` is set to `"polite"`, as the SR may be reading something else that eats into the `Toast`'s time on screen.

Yeah, tricky for sure…

> 
> > * there are quite a few concepts in the `Toast`, like label, message, type, etc. Are these standardised? It feels again quite prescriptive to me for now. Ie. what if someone needs the message to be formatted somehow and therefore needs JSX, can't be just a string, etc.
> 
> `label` I'm not 100% sure we will need. `message` would be the simplest interface because the SR announcement should always be test. We should support any kind of composition in `Toast` and use `element.innerText`if there is no `message`, but that's potentially troublesome if the inner HTML has a composition that doesn't make sense when read as a single sentence. I envision `message` could be used in lieu of composition if the toast is simple, or alongside composition as a simplified supplement for better SR support.
> 
> Consider:
> 
> ```js-jsx
> <Toast>
>   <header>
>     <Heading>Warning: Error</Heading>
>     <ToastDismiss>
>       <VisuallyHidden>Dismiss error</VisuallyHidden>
>       <CloseIcon />
>     </ToastDismiss>
>   </header>
>   <div>
>     <Text>Oh no! You have a major problem!</Text>
>     <ToastDismiss>Dismiss error</ToastDismiss>
>   </div>
> </Toast>
> ```
> 
> Using the HTML inner text here would be needlessly verbose, repetitive, and would read like a run-on sentence. The way `Announce` works is that it needs to mirror some text into a visually hidden live-region. It's quite a bit different than `aria-describedby` or `aria-label`, so this is what I imagine the `message` prop can solve.
> 
> ```js-jsx
> <Toast message="Oh no! You have a major problem!">
>   {/* compose whatever you'd like */}
> </Toast>
> ```

I see, yeah makes sense to at least have a way to provide an override text to announce.

> 
> As for `type`, this too is probably a bit prescriptive, but I think it can be helpful for users for a few reasons.
> 
> * I think the vast majority of needs will fit into one of these categories, so for most people they don't need to think about anything else other than whether or not a toast is an error message, success message, etc.
> * We can use this type to handle ARIA for them. For example, an error or success message _probably_ make the most sense with `role="alert" aria-live="assertive"`, while other types of messages _probably_ shouldn't interrupt the user, so we'd use `role="status" aria-live="polite"` (or possibly `role="log"`).

Ah yes that makes a lot of sense.

> > * if we're going to do declarative `Toast` at the point of render to raise them, how are we ensuring that they don't re-trigger if the parent re-renders? I can't see the id so I'm assuming we generate it, in which case how do we distinguish already raised toasts?
> 
> No differently really than rendering anything else, really. They should always be conditionally rendered by the consumer based on some state, but we'll also be managing them internally via context where we will need to generate IDs for those. This does raise an interesting question though.
> 
> ```js-jsx
> function Profile() {
>   const [status, saveProfile] = useSaveProfile();
>   return (
>     <form>
>       {/* ... */}
>       <button onClick={() => saveProfile()}>Save</button>
>       {status === 'success' && <Toast message="Whoop! It worked!" />}
>     </form>
>   );
> }
> ```
> 
> In Jenna's example above, `Toast` renders when status is success, but of course when it times out in our app-level toast context `status` may still be `success`, so we'd just return `null` internally if the timer for that toast ID has run its course or if the user has dismissed that message.

Ohhh that's the bit I wasn't sure about how we would do it. That makes sense, we would have an id internally in a ref so we'd know if it's the same or not, and we'd know if it's done or not.

> 
> Now, what happens when the user clicks the `Save` button again? `status` presumably changes to `loading` or something, but when it returns back to `success` we are still rendering the same toast based on the generated id, so presumably it wouldn't appear for the second save action 🧐
> 
> The consumer could do something like...
> 
> ```js-jsx
> function Profile() {
>   const [status, saveProfile] = useSaveProfile();
>   const [toastId, setToastId] = React.useState(1);
>   React.useEffect(() => {
>     if (status === 'success') {
>       setToastId(i => i++)
>     }
>   }, [status]);
>   return (
>     <form>
>       {/* ... */}
>       <button onClick={() => saveProfile()}>Save</button>
>       {status === 'success' && <Toast id={`save-${toastId}`} message="Whoop! It worked!" />}
>     </form>
>   );
> }
> ```
> 
> The consumer uses their own ID to signal that the toast is new on each `success` status. But now we have a new problem -- what if the previous toast is still on screen when this happens? It would go away because the ID of the toast we're rendering in this component has changed. Now it might get a little funkier.
> 
> ```js-jsx
> function Profile() {
>   const [status, saveProfile] = useSaveProfile();
>   const [toastIds, setToastIds] = React.useState([]);
>   React.useEffect(() => {
>     if (status === 'success') {
>       setToastIds(t => [...t, t[t.length - 1] + 1])
>     }
>   }, [status]);
>   return (
>     <form>
>       {/* ... */}
>       <button onClick={() => saveProfile()}>Save</button>
>       {toastIds.map((id) => <Toast key={id} id={`save-${id}`} message="Whoop! It worked!" />)}
>     </form>
>   );
> }
> ```
> 
> This probably works a little better but feels awkward that we're kind of offloading React complexity to work around what is probably unexpected behavior, but I think this ends up being a potentially common scenario. Kind of wondering if the originally proposed "imperative" API doesn't actually become a bit simpler here.
> 
> ```js-jsx
> import { emitToast, Toast } from '@radix-ui/react-toast';
> 
> function Profile() {
>   const [status, saveProfile] = useSaveProfile();
>   React.useEffect(() => {
>     if (status === 'success') {
>       emitToast(() => (
>         <Toast message="Whoop! It worked!" />
>       ))
>     }
>   }, [status]);
>   return (
>     <form>
>       <button onClick={() => saveProfile()}>Save</button>
>     </form>
>   );
> }
> ```
> 
> We could provide a hook to simplify this somewhat:
> 
> ```js-jsx
> import { useToastEmit, Toast } from '@radix-ui/react-toast';
> 
> function Profile() {
>   const [status, saveProfile] = useSaveProfile();
>   useToastEmit(
>     // condition
>     status === 'success',
>     // callback to render the toast
>     () => <Toast message="Whoop! It worked!" />
>   );
>   return (
>     <form>
>       <button onClick={() => saveProfile()}>Save</button>
>     </form>
>   );
> }
> ```

For all this, it seems to me we don't need to do anything specific, just use react and pass a different `key` to the `Toast` when it needs to be a new one.

**Comment by chaance** [comment]
> I see. Does that mean if someone doesn't include a notification center in their app, they won't be accessible then?

Yes, unless they design some other interface to satisfy WCAG criteria where the toasts fail.

> For all this, it seems to me we don't need to do anything specific, just use react and pass a different key to the `Toast` when it needs to be a new one.

Yeah good point on `key`, we might be able to make that work. I'm not abandoning Jenna's API idea just yet, just wanted to note some cases where it might present a challenge. We should test these out for sure, but it might not be a problem.

**Comment by benoitgrelard** [comment]
I think that's what I would expect to have to do from React's standpoint at least.

**Comment by martonlanga** [comment]
Just wanted to chime in that I'd love a hooks api for this one but see that it's already being discussed. So +1 for that 👍 

Thanks for all your work!

**Comment by DanielBailey-web** [comment]
Since it is a common occurrence (In my opinion... 😉 ) to have dialog (modals) open and toasts providing information at the same time. It would be nice if there was a very easy to implement way to not have the dialog close when dismissing the toast. Preferably as an option for all toasts, not one toast at a time. 

But that might be outside the scope of this project.

**Comment by jjenzz** [comment]
@DanielBailey-web Thanks for raising that, it's highlighted an issue with our current implementation that I'm looking into now 🙂

**Comment by sikanhe** [comment]
@jjenzz  Not sure if this is the right place to ask this - Is there a suggested way to prevent modal closing if we are using 3rd party toast implementations? (e.stopPropagation()  on toast dismiss event doesn't help)

**Comment by DanielBailey-web** [comment]
> @jjenzz Not sure if this is the right place to ask this - Is there a suggested way to prevent modal closing if we are using 3rd party toast implementations? (e.stopPropagation() on toast dismiss event doesn't help)
@sikanhe 
You need to do this:
```
const reference = useRef<HTMLDivElement>(null);
useEffect(() => {
    function mousedown(e: Event) {
      e.stopImmediatePropagation();
      e.stopPropagation();
      e.preventDefault();
    }
    if (reference.current) {
      reference.current.addEventListener("pointerdown", mousedown);
    }
    return () => {
      if (reference.current) {
        reference.current.removeEventListener("pointerdown", mousedown);
      }
    };
  }, []);
```
and the reference needs to be on an html element surrounding your toast container.

**Comment by sikanhe** [comment]
Forgot to say this: @jjenzz  @DanielBailey-web  thank you both so much for helping!. Also can't wait to see how the Toast component come out

**Comment by benoitgrelard** [comment]
was released
