### ISSUE TITLE
Ensure touch support is good across all primitives

### ISSUE THREAD

**Issue by chaance** [radix-ui/primitives#390]
Referred in https://github.com/radix-ui/primitives/discussions/375

I know @jjenzz had mentioned `Slider`, but it might be helpful to identify other components that we feel could benefit from additional testing. 

`ScrollArea` for sure. Immediate thought it, what if the user tries to scroll on both axes simultaneously with a track press on one and a button press on another? Should we consider built-in drag-scroll support?

**Comment by benoitgrelard** [comment]
We've done the work by relying more often on pointer events, we can close this as specific issues come up and get addressed.
