### ISSUE TITLE
Feedback: Access to internal component state inside jsx

### ISSUE THREAD

**Issue by marekzelinka** [radix-ui/primitives#391]
### Overview

Is there a way to get access to internal component state, like in the example of the `<Tabs />` component:

```javascript
      <Tabs.Root defaultValue="tab1">
        {({activeIndex}) => ( // <-- access to  active index
          <>
            <Tabs.List aria-label="tabs example">
              <Tabs.Tab 
                value="tab1"
                className={
                    activeIndex === 0 ? 'bg-red-500' : "" // <-- dynamically style the element based on active index
                }
              >
                One
              </Tabs.Tab>
              <Tabs.Tab value="tab2">Two</Tabs.Tab>
              <Tabs.Tab value="tab3">Three</Tabs.Tab>
            </Tabs.List>
            <Tabs.Panel 
              value="tab1"
            > 
              Tab one content
             </Tabs.Panel>
            <Tabs.Panel value="tab2">Tab two content</Tabs.Panel>
            <Tabs.Panel value="tab3">Tab three content</Tabs.Panel>
          </>
        )}
      </Tabs.Root>
```

Right now the only way to get access to the state is trough data attributes, that are not usable in the context of a utility library like [tailwindcss](https://tailwindcss.com/docs/utility-first)

### Examples in other libraries

from [Headless UI &lt;Menu /&gt;](https://github.com/tailwindlabs/headlessui/tree/develop/packages/%40headlessui-react#basic-example-1):

```javascript
import { Menu } from '@headlessui/react'

function MyDropdown() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          {({ active }) => ( // <-- access to internal component state
            <a className={`${active && 'bg-blue-500'}`} href="/account-settings">
              Account settings
            </a>
          )}
        </Menu.Item>
        <Menu.Item>
          {({ active }) => (
            <a className={`${active && 'bg-blue-500'}`} href="/account-settings">
              Documentation
            </a>
          )}
        </Menu.Item>
        <Menu.Item disabled>
          <span className="opacity-75">Invite a friend (coming soon!)</span>
        </Menu.Item>
      </Menu.Items>
    </Menu>
  )
}
```

from [Reach UI &lt;Tabs/&gt;](https://reach.tech/tabs):

```javascript
function Example() {
  return (
    <Tabs keyboardActivation="manual">
      {({ selectedIndex, focusedIndex }) => {
        let getTabStyle = (index) => ({
          borderBottom: `4px solid ${
            selectedIndex === index
              ? "red"
              : focusedIndex === index
              ? "blue"
              : "black"
          }`,
        });
        return (
          <React.Fragment>
            <TabList>
              <Tab style={getTabStyle(0)}>Uno</Tab>
              <Tab style={getTabStyle(1)}>Dos</Tab>
              <Tab style={getTabStyle(2)}>Tres</Tab>
            </TabList>
            <TabPanels>
              <TabPanel>Uno</TabPanel>
              <TabPanel>Dos</TabPanel>
              <TabPanel>Tres</TabPanel>
            </TabPanels>
          </React.Fragment>
        );
      }}
    </Tabs>
  );
}
```

### Who does this impact? Who is this for?

This would help a growing number of developer that choose to use [tailwindcss ](https://tailwindcss.com/) for styling purposes!

**Comment by benoitgrelard** [comment]
Hi @marekzelinka, for now we have decided to stay away from this to keep the API surface as small as possible. The reason is that all of these use cases are still achievable by controlling the state.

So for example with tabs:

```tsx
<Tabs.Root value={value} onValueChange={setValue}>
  <Tabs.List aria-label="tabs example">
    <Tabs.Tab value="tab1" className={value === 'tab1' ? 'bg-red-500' : undefined}>
      One
    </Tabs.Tab>
    <Tabs.Tab value="tab2">Two</Tabs.Tab>
    <Tabs.Tab value="tab3">Three</Tabs.Tab>
  </Tabs.List>
  <Tabs.Panel value="tab1">Tab one content</Tabs.Panel>
  <Tabs.Panel value="tab2">Tab two content</Tabs.Panel>
  <Tabs.Panel value="tab3">Tab three content</Tabs.Panel>
</Tabs.Root>
```

**Comment by marekzelinka** [comment]
Well, that's a bummer, anyway, thanks for the answer!

**Comment by jjenzz** [comment]
> Well, that's a bummer

@marekzelinka If you wouldn't mind, I'd love if you could elaborate on why child as function pattern is preferable to managing some state? This will help us to make future API decisions. 

Currently, our library is purposefully low level with the intent that you would create a component to wrap ours. You would apply your styles/functionality to it as you see fit and re-expose that as the component your app would use.

Is the children as function just a personal preference or are you struggling to figure out how to massage our API into your requirements?

**Comment by marekzelinka** [comment]
hey @jjenzz, its just a personal preference, coming from other similar libraries, I just expected to be able to pass a function as a child and get the state.

This is definitely not a big deal, and I've already used some components in my project!

Thank you and your team for this project! ❤
