### ISSUE TITLE
[DropdownMenu] Opening focus and arrow keys does not work

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#402]
### Current Behavior

**Version 0.0.2 only**. When opening a menu and pressing the down arrow, the focus is not moved to the first item.

### Expected behavior

Opening a menu dropdown and immediately pressing the down arrow should move focus to the first non-disabled item.

### Reproducible example

https://codesandbox.io/s/great-shannon-d6smv?file=/src/App.tsx

### Suggested solution

Arrow down should focus the first non-disabled item in the menu.

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   `@radix-ui/react-dropdown-menu`      |  0.0.2       | 
| React            | n/a     |         |
| Browser          |   All      |         |
| Assistive tech   |   n/a      |         |
| Node             | n/a     |         |
| npm/yarn         |   n/a      |         |
| Operating System |   n/a      |         |

**Comment by benoitgrelard** [comment]
Hey @pacocoursey, thanks for spotting this and opening an issue quickly!
I've found what the issue is, we'll have a fix out shortly.

**Comment by benoitgrelard** [comment]
Version 0.0.3 was published with a fix.
