### ISSUE TITLE
Type Error: "selector" not a valid prop for ReactArrow

### ISSUE THREAD

**Issue by kylemh** [radix-ui/primitives#406]
### Current Behavior

[This documentation](https://radix-ui.com/primitives/docs/components/tooltip#arrow) suggests that "selector" is an exposed prop, but the TypeScript compiler says it's not an expected prop when attempting to define it.

### Expected behavior

I can define "selector" as a string without TypeScript giving me complaints.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/great-darkness-owvq9?file=/src/Tooltip.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| @radix-ui/react-tooltip | Arrow module | 0.0.2 |

**Comment by benoitgrelard** [comment]
Hey @kylemh, thanks for reporting this quickly.
We've identified the issue now which turned out to be a caching issue when building the packages with parcel.
We are going to have to re-publish all the packages now.

**Comment by benoitgrelard** [comment]
This has now been released.
