### ISSUE TITLE
Children are omitted from `MenuImpl` in #409, how can I add `MenuItem`s?

### ISSUE THREAD

**Issue by Nazeh** [radix-ui/primitives#411]
## Bug report

I was working on an unsolicited PR for Toolbar :D, and after pulling the latest upstream changes I noticed that `MenuItem` does not render in stories as it did before #409, I guess removing `{children}` from the `MenuImpl` has something to do with it :)

I am sure there is a reason for that change, but I don't see how can I adapt stories accordingly?

https://github.com/radix-ui/primitives/blob/f3de622e944785d01eb6041249ca1645f79ce102/packages/react/menu/src/Menu.tsx#L312

### Current Behavior

`MenuItem`s are not rendered in `Menu`

![localhost_9009__path=_story_components-menu--styled (1)](https://user-images.githubusercontent.com/40009100/106364685-f20e9c80-6341-11eb-9d0f-0c433cfbca84.png)

### Expected behavior
![localhost_9009__path=_story_components-menu--styled (2)](https://user-images.githubusercontent.com/40009100/106364675-e4591700-6341-11eb-9c94-35b1c55db96c.png)

### Suggested solution

If this was a mistake then add `{children}` back do fix the issue, but it is probably not so I don't know.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-menu    |  0.0.4       |
| React            | n/a     |         |
| Browser          |    Brave     |         |
| Assistive tech   |         |         |
| Node             | n/a     |   14.15.0      |
| npm/yarn         |    yarn     |    2.1.1     |
| Operating System |     PopOS    |         |

**Comment by Nazeh** [comment]
Edit: after examining #409 more, it appears that `children` was not removed from components that is expected to have children as a part of its default use case, for example : `CollapsibleContent`, `CollapsibleContent`, `Popover`, `Popper` (through `          {...popperProps}`), etc..

So I think `Menu` should have `children` too, as well as similar components like `Toolbar` #412

**Comment by jjenzz** [comment]
@Nazeh Thanks for looking into this. `Menu` should indeed have children. We'll hopefully avoid issues like this once we get some more tests in place before v1 😅 apologies.
