### ISSUE TITLE
[Dropdown Menu] Problems when testing with Jest+RTL

### ISSUE THREAD

**Issue by rubenmoya** [radix-ui/primitives#420]
Hello!

We're trying to test a wrapper we made around the Dropdown Menu component but we found out that it's not rendering when the trigger is clicked. This only happens in the tests, the UI works like a charm.

We thought it could be related to the portal, so we used `portalled={false}` and got the same results.

I tried to create a reproduction on codesandbox but now I'm getting a different error, which makes me think that maybe we have ResizeObserver mocked, I'll have to take a look.

> Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

[Here is the codesandbox](https://codesandbox.io/s/radix-dropdown-tests-wp96j?file=/src/App.spec.tsx) reproducing the error.

**Comment by benoitgrelard** [comment]
Hey @rubenmoya,

Thanks for reaching out. I believe this is an issue with the test environment (jest/jsdom) not having `ResizeObserver`.
That's why you don't see an issue in your app.
The test environment is not a real browser/DOM so you don't necessarily have all the APIs available.

I believe what you'd have to do is mock these bits within your testing environment of choice.

We're currently in alpha so we don't have tests for all packages yet, but eventually you should be able to take a look at how we did it ourselves for the same purpose.

In the meantime, I've had a very quick go in our codebase with the same test you were trying to run, and I've had to mock a couple pieces for it to work:

```js
global.ResizeObserver = class ResizeObserver {
  constructor(cb) {
    this.cb = cb;
  }
  observe(cb) {
    this.cb([{ borderBoxSize: { inlineSize: 0, blockSize: 0 } }]);
  }
  unobserve() {}
};

global.DOMRect = {
  fromRect: () => ({ top: 0, left: 0, bottom: 0, right: 0, width: 0, height: 0 }),
};
```

I hope that helps, if so, feel free to close the issue if this is satisfactory.

**Comment by rubenmoya** [comment]
Thank you for your time @benoitgrelard!

After some more research we found out that it is working in one of our projects, but it's not working in the other one, so it has to do with the configuration of that project in particular.

Thank you for taking the time to answer!

**Comment by Avizura** [comment]
Hi @benoitgrelard, what about browsers which don't support ResizeOberver? Should I use polyfill?

**Comment by benoitgrelard** [comment]
@Avizura I believe all the browsers we officially support do have support for `ResizeObserver`.

`browsers: 'Chrome >= 74, Safari >= 13.1, iOS >= 13.3, Firefox >= 78, Edge >= 79',`
https://github.com/radix-ui/primitives/blob/main/babel.config.js#L30

You can try to add a polyfill for older browsers, but at this point we can't guarantee that there may be other issues with any other APIs we'd be using.

**Comment by Avizura** [comment]
@benoitgrelard I see, thanks!

**Comment by ItzaMi** [comment]
@benoitgrelard , this also worked for me on #1036  🤘 Thank you!

However, I have an extra issue created by the fact that I'm using `TypeScript` and it doesn't appear to be very fond of the solution.
I'm battling with it and will leave a solution here (if I find one) 😄

**Comment by dkapanidis** [comment]
> @benoitgrelard , this also worked for me on #1036 🤘 Thank you!
> 
> However, I have an extra issue created by the fact that I'm using `TypeScript` and it doesn't appear to be very fond of the solution. I'm battling with it and will leave a solution here (if I find one) 😄

For anyone looking to a typescript format of the same solution:

```typescript
(global as any).ResizeObserver = class ResizeObserver {
  constructor(cb: any) {
    (this as any).cb = cb;
  }

  observe() {
    (this as any).cb([{ borderBoxSize: { inlineSize: 0, blockSize: 0 } }]);
  }
  
  unobserve() { }
};

(global as any).DOMRect = {
  fromRect: () => ({ top: 0, left: 0, bottom: 0, right: 0, width: 0, height: 0 }),
};
```

**Comment by onyedikachi23** [comment]
You also need to mock the `disconnect` property if your code or any library you depend on is using it:


```ts
global.ResizeObserver = class ResizeObserver {
		constructor(cb: any) {
			(this as any).cb = cb;
		}

		observe() {
			(this as any).cb([
				{ borderBoxSize: { inlineSize: 0, blockSize: 0 } },
			]);
		}

		unobserve() {}

		disconnect() {} // the mock
	};

```
