### ISSUE TITLE
[Popover] Controlled version mounts twice when opened externally

### ISSUE THREAD

**Issue by pacocoursey** [radix-ui/primitives#446]
## Bug report

When using a controlled popover and you open it externally, for example via a keybind, it mounts twice.

### Current Behavior

Opening via the Trigger works well, but opening via global listener mounts it twice:

https://user-images.githubusercontent.com/34928425/107096395-ebf84000-67c7-11eb-9276-ed1c3be2f5f1.mov

### Expected behavior

It should only mount once, and be positioned to the trigger (unless anchorRef is provided)

### Reproducible example

https://codesandbox.io/s/naughty-wright-l8mn0?file=/src/App.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |    Brave: 1.19.92 Chromium: 88.0.4324.152 (Official Build) (x86_64)  |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  macOS Version 11.1 (Build 20C69)       |         |

**Comment by benoitgrelard** [comment]
Hi @pacocoursey, I'm not sure what's going on here but I cannot replicate the issue at all (using your sandbox or ours).
I even tried this specific version of Brave you mention and I do not see the issue.

**Comment by jjenzz** [comment]
Are you still experiencing this issue @pacocoursey? We are both struggling to reproduce here. Are there any additional steps you can provide to guide us in the right direction?

**Comment by pacocoursey** [comment]
Really weird, I'm no longer able to reproduce either! Glad I caught it on video at least once. I'll re-open this issue if I run into it again, sorry for the confusion
