### ISSUE TITLE
[Popper] Measurements of refs aren't always working properly

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#447]
I discovered this whilst writing some more chromatic visual regression tests.
We have a `anchorRef` prop on `Popover` which can override the default internal `context.triggerRef`.
I noticed that in some situations (like when controlling and `open` by default) the popover wouldn't show.
It seems to be because our hooks `useRect`, `useSize` etc, aren't really aware of refs reassignment.
Therefore in some situations, we may end up with an initial `null` ref.

I then realised also, that the same thing happens by simply reordering `<Popover.Trigger>` and `<Popover.Content>`.

> Note: once we fix that issue, let's add back some more of these visual regression tests I have had to skip for now because of that.

**Comment by jjenzz** [comment]
We realised most common libraries out there have the same issues we are having with `ref`s so we were unable to get inspiration from these libs on a solution :disappointed:

The issues we are seeing are when components receive a consumer’s `ref` as a prop (e.g. `anchorRef`) or a hook receives a `ref` as a parameter:

- The order in which component parts are rendered can break their functionality (ouch).
- If the node the `ref` is attached to changes or mounts after first render, necessary functionality isn’t instantiated correctly.

We have components like `Popover` that receive an `anchorRef` prop. That ref has been created and attached to an element out of our control, by the consumer, and then passed to our prop. This approach meant we had modelled our `useSize` and `useRect` hooks (that these components use internally) to receive this ref as a parameter (`const size = useSize(anchorRef)`).

Unfortunately, as we know, refs are not recreated… they are **mutated**. So when our hooks depend on the received ref, they do not re-execute if the node changes or mounts after first render. Necessary logic is not instantiated correctly in these scenarios and things break. Furthermore, when using `useLayoutEffect` (in an attempt to avoid UI flashing) the stability of the functionality is entirely dependent on the `ref` element being rendered first :grimacing:

So, we know the solution here is to `useEffect` with callback refs which we do for `Presence` and others, but this means changing our `useSize` and `useRect` APIs to **give us** the ref which the consumer would attach where necessary (`const [size, ref] = useSize()`).

That is fine for internal use but how do we give the consumer this ref from inside to attach to their component? People usually solve this sort of problem with render props:

```jsx
<Popover>
  {({ anchorRef }) => (
    <div ref={anchorRef} />
  )} 
</Popover>
```

However, we’re not a fan of this pattern at all so try to avoid it unless we cannot find an alternative. We’ve discussed educating consumers on callback refs in our code examples and changing our popover-like APIs to receive a node instead:

```jsx
const [anchor, setAnchor] = React.useState(null);
render(
  <Popover anchor={anchor}>
    <div ref={setAnchor}>
      Anchor to row
      <Popover.Trigger>Open</Popover.Trigger>
    </div>
  </Popover>
);
```

But, this just isn’t something people are used to and doesn’t really fit our approach of making sure things Just Work:tm: without wiring.

We paired to try make sure we’re not worsening the issue by doing something that could potentially be avoided (not that we could see) and investigated several permutations of a solution. We’ve settled on one that means exposing an additional (optional) `Anchor` part, e.g. `Popover.Anchor`. 

I’m going to implement this today.
