### ISSUE TITLE
[DropdownMenu] dropdown doesn't close when adding animations

### ISSUE THREAD

**Issue by rubenmoya** [radix-ui/primitives#449]
### Current Behavior

We've been using the dropdown menu for a while with success (we love it!), this morning we wanted to improve it by adding some animations, we copied the example from the documentation and we found out that we couldn't close the component, either clicking outside or pressing `Esc`.

### Expected behavior

The component should close the same way it does without animations.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-dropdown-animation-6ml0i)

### Additional context

It only happens after adding the animations.

We're using Stitches `0.0.3-canary.4`

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dropdown-menu      |   0.0.6      |
| React            | n/a     |    17.0.1     |
| Browser          |    Google Chrome     |    88.0.4324.146     |
| Assistive tech   |         |         |
| Node             |    |     14.15.0     |
| npm/yarn         |    yarn     |     1.22.5    |
| Operating System |    MacOS     |    10.15.7     |

**Comment by jjenzz** [comment]
@rubenmoya Thanks for reporting this. We have a fix for this in `main` already so should work after the next release.

**Comment by benoitgrelard** [comment]
Hey, I've just cut a new release of all primitives.
Can you try updating to `@radix-ui/react-dropdown-menu@0.0.7`?
That should resolve your issue.

**Comment by rubenmoya** [comment]
It's working in both, the codesandbox reproduction and our project, thank you so much! Radix is awesome 👏
