### ISSUE TITLE
DropdownMenu.Trigger doesn't allow `as={CustomComponent}`

### ISSUE THREAD

**Issue by tarngerine** [radix-ui/primitives#452]
### Current Behavior
<img width="288" alt="image" src="https://user-images.githubusercontent.com/1629901/107604732-958b6700-6bf6-11eb-9203-56aa96d11974.png">

This menu opens as expected
`        <DropdownMenu.Trigger as="button">Open dropdown</DropdownMenu.Trigger>`

This menu will never open, even if you set `open` prop on the Root
`        <DropdownMenu.Trigger as={TestButton}></DropdownMenu.Trigger>`

where TestButton is some simple FC
`const TestButton = () => <button>Open dropdown (broken)</button>;`

### Expected behavior

It should work~

### Reproducible example

https://codesandbox.io/s/epic-swanson-qw8lx?file=/src/App.js:828-834

### Suggested solution

it should work similarly to other triggers, like <Dialog.Trigger as={TestButton}> works fine

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   react-dropdown-menu      |      0.0.6   |
| React            | n/a     |    17.0.1     |
| Browser          |      Safari   |    14.0.2    |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |  idk, csb node v       |
| npm/yarn         |     n/a    |         |
| Operating System |    macOs     |  10.15.7       |

**Comment by tarngerine** [comment]
needed to use forwardRef here 

```
const TestButton = React.forwardRef((props, ref) => (
  <button {...props} ref={ref}></button>
));
```

**Comment by benoitgrelard** [comment]
Yep, it's a good rule of thumb to always forward ref for these kinds of components.
