### ISSUE TITLE
Radix breaks type validation in our project with `Cannot find name 'ResizeObserverEntry'`

### ISSUE THREAD

**Issue by hollg** [radix-ui/primitives#454]
### Current Behavior

When I run type validation (`tsc --noEmit`) in a project where I'm using the Radix checkbox, the following error is thrown:
```
node_modules/@radix-ui/utils/dist/index.d.ts:16:60 - error TS2304: Cannot find name 'ResizeObserverEntry'.

16 export function getResizeObserverEntryBorderBoxSize(entry: ResizeObserverEntry): ResizeObserverSize;
                                                              ~~~~~~~~~~~~~~~~~~~

node_modules/@radix-ui/utils/dist/index.d.ts:16:82 - error TS2304: Cannot find name 'ResizeObserverSize'.

16 export function getResizeObserverEntryBorderBoxSize(entry: ResizeObserverEntry): ResizeObserverSize;
                                                                                    ~~~~~~~~~~~~~~~~~~
```
### Expected behavior

No error to be thrown.

### Reproducible example

You can run `yarn validate:types` in the `main` branch of this project: https://github.com/Atom-Learning/components

### Suggested solution

I am no TypeScript expert, so maybe this isn't the issue at all, but the only place I can see `ResizeObserverEntry` in the source code is in [the file where the error is being thrown](https://github.com/radix-ui/primitives/blob/310499b6f6dc9389e396eebc3ab911888a814dd2/packages/core/utils/src/domUtils.ts). I can't see it being defined anywhere. Maybe it's defined globally in some related package but an import of the type has been removed along the way?

### Additional context
N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-checkbox      |  0.0.4       |
|                               |   @radix-ui/react-icons            |   1.0.1       |  
| React            | n/a     |     17.0.1    |
| Browser          |   n/a      |   n/a      |
| Assistive tech   |    n/a     |   n/a      |
| Node             | n/a     |     14.4.0    |
| npm/yarn         |    yarn     |   1.22.5      |
| Operating System |   macOS BigSur      |     11.1    |

Thanks in advance for any help, and for the great library!

**Comment by hollg** [comment]
This problem was solved by adding `/// <reference types="resize-observer-browser" />` to our `global.d.ts`. This feels like a workaround, though — presumably we should be getting the type with the Radix component, if it's required?

**Comment by benoitgrelard** [comment]
Yes, we have the same thing internally, it seems we need to somehow bundle these types in our types but we haven't yet figured out how to do that.
