### ISSUE TITLE
Slider doesn't support step < 1

### ISSUE THREAD

**Issue by paulbellamy** [radix-ui/primitives#462]
### Current Behavior

Minimum step size seems to be 1, even when `step` is smaller than 1. With the below code the slider value is either 0 or 1.

### Expected behavior

I expect the slider to have smooth steps of 0.1, so the values can be from `0, 0.1, 0.2, ..., 0.9, 1`

### Reproducible example

```js
import * as S from "@radix-ui/react-slider";

 <Slider.Root defaultValue={[0.5]} min={0} max={1} step={0.1}>
    <Slider.Track>
      <Slider.Thumb />
    </Slider.Track>
    <Slider.Range />
  </Slider.Root>
```

### Suggested solution

Support any step size?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-slider | 0.0.5 |
| React            | n/a     |   16.13.1      |
| Browser          |   Brave      |  Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)   |
| Assistive tech   |         |         |
| Node             | n/a     |   v10.20.1      |
| npm/yarn         |   npm      |  6.14.4       |
| Operating System |    OSX     |  Big Sur 11.2.1       |

**Comment by benoitgrelard** [comment]
Hey Paul! Thanks for reporting this, we actually had this as a limitation on purpose in the code, but we'll fix that.

**Comment by benoitgrelard** [comment]
This was released yesterday btw Paul. Enjoy!

**Comment by paulbellamy** [comment]
The slider of my excitement has reached 11.
