### ISSUE TITLE
[FocusScope] Dialog resets focus when leaving & returning to browser tab/window 

### ISSUE THREAD

**Issue by tigranpetrossian** [radix-ui/primitives#499]
### Current Behavior

Dialog resets focus to first focusable element when browser tab is blurred.

![Gif with reproduction](https://user-images.githubusercontent.com/3755268/109269136-7bbc6780-7825-11eb-91f4-684b346635ea.gif)

### Expected behavior

Focus should be retained when leaving browser window/tab and returning to it.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/radix-ui-dialog-focus-issue-fddwi)

### Suggested solution

This might be because of `trapFocus` re-initializing on document focus, but I'm not 100% sure:
https://github.com/radix-ui/primitives/blob/main/packages/react/focus-scope/src/createFocusScope.tsx#L30

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | Dialog  | 0.06    |
| React            |         | 17.0.1  |
| Browser          | Chrome  | 88.0    |
| Assistive tech   | n/a     |         |
| Node             | n/a     |         |
| npm/yarn         | n/a     |         |
| Operating System | MacOs   | 10.15.6 |

Reproducible pretty much everywhere except Safari (13.1.2).

**Comment by benoitgrelard** [comment]
Hi @tigranpetrossian, that behaviour should now be fixed in the latest published release.
https://radix-ui.com/primitives/docs/overview/releases#03052021

**Comment by tigranpetrossian** [comment]
You're the best.
