### ISSUE TITLE
[ScrollArea] Uses feature not present in Safari 13 — browser support (general)

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#500]
We have had [reports](https://twitter.com/emplums/status/1364681789227196422) of the documentation website breaking (because we use ScrollArea for the nav and other).
`ScrollArea` uses the media query list change event which isn't supported in Safari 13.

```tsx
export function onPrefersReducedMotionChange(
  callback: (prefers: boolean) => any,
  globalWindow: Window & typeof globalThis = window
) {
  try {
    const mediaQueryList = globalWindow.matchMedia(QUERY);
    mediaQueryList.addEventListener('change', listener);
    return function () {
      mediaQueryList.removeEventListener('change', listener);
    };
  } catch (e) {}

  return function () {};

  function listener(event: MediaQueryListEvent) {
    callback(!event.matches);
  }
}
```

Generally, we need to address how we're going to deal with the fact we don't include polyfills. What should the experience be, etc.

**Comment by jjenzz** [comment]
A solution worth exploring might be to add a `browserlist` to our `package.json` files which should allow Parcel to handle bundling the necessary polyfills and transforms for us via `@babel/preset-env`:

https://babeljs.io/docs/en/babel-preset-env.html

**Comment by braposo** [comment]
Hey! I was adding `ScrollArea` to one of our components and was getting some issue when testing with Safari 13.1 on Catalina through BrowserStack, which led me here.

Are there any news about the fix for this issue?

In case you need more info, this is the error I'm seeing in the console (page is blank).

![image](https://user-images.githubusercontent.com/38172/114110018-71829400-98ce-11eb-9b6d-1ee35a6e7ac7.png)

**Comment by benoitgrelard** [comment]
@braposo I answered on Discord already but I'll put it here in case other people happen to read this:

- We technically don't officially support anything below Safari 13.3
- We are currently reworking `ScrollArea` so that bug will be dealt with anyway soon

**Comment by jjenzz** [comment]
Just to clarify, we do support Safari 13.1 on MacOS but Safari 13.3 on iOS. As @benoitgrelard has mentioned, we're currently reworking the component to solve the `13.1` issues.

**Comment by braposo** [comment]
Thanks for the explanation @jjenzz @benoitgrelard! 

I wasn't able to find a way to use a polyfill just for the `change` event so ended up taking a different approach and reverting to the native scrollbar whenever `ScrollArea` isn't supported.

This was done using an error boundary that injects the `unstable_forceNative` prop whenever the `ScrollArea` component breaks (which is this case):

```tsx
export class ScrollAreaErrorBoundary extends React.Component<
    ErrorProps,
    ErrorState
> {
    state = { hasError: false };

    static getDerivedStateFromError() {
        return { hasError: true };
    }

    render() {
        if (this.state.hasError) {
            return React.cloneElement(this.props.children, {
                unstable_forceNative: true,
            });
        }

        return this.props.children;
    }
}
```

**Comment by benoitgrelard** [comment]
That's pretty cool!

**Comment by jjenzz** [comment]
I had actually suggested we create a `Supports` component when the `ScrollArea` was originally created that would use error boundaries to do something similar to that 🙂  

@benoitgrelard The new version of the `ScrollArea` I am working on will not have the `forceNative` prop so might be a good chance to revisit this `Supports` component discussion.

Original discussion here for reference: https://github.com/radix-ui/primitives/pull/203#discussion_r501156851

**Comment by braposo** [comment]
That's very interesting @jjenzz, thanks for sharing! I kind of like this solution and can see how supporting that internally could make sense for these types of primitives that augment the native experience.

From my understanding of the current implementation, it can also make sense to not have the support for monitoring changes in the `prefers-reduced-motion` media query. That might be a better incremental degradation for browsers that won't support this listener, although the error boundary would probably be a safer mechanism against any kind of error in the scroll area.

**Comment by benoitgrelard** [comment]
@braposo, this has now been fixed and released.
https://radix-ui.com/primitives/docs/components/scroll-area
