### ISSUE TITLE
[Checkbox] Inconsistent behavior with plain label

### ISSUE THREAD

**Issue by nderscore** [radix-ui/primitives#512]
### Current Behavior

When the `Checkbox` primitive is used with controlled state, is wrapped in a plain `<label>`, and has an `Indicator` with conditionally-rendered children, the checkbox's click handler competes with the label's native browser behavior and eventually becomes "stuck" when interacting with the indicator. 

### Expected behavior

Checkbox should not get stuck when interacting with the indicator.

### Reproducible example

https://codesandbox.io/s/crazy-sutherland-vxqoj?file=/src/App.js

### Suggested solution

N/A

### Additional context

This doesn't happen when using the `Label` primitive from radix-ui.

### Your environment

(any)

**Comment by jjenzz** [comment]
@nderscore Thanks for reporting. We've just merged a fix for this which should be available in our next release.

**Comment by benoitgrelard** [comment]
Hey @nderscore, this fix has now been released.
