### ISSUE TITLE
ReferenceError: globalThis is not defined when using DropdownMenu

### ISSUE THREAD

**Issue by mglavall** [radix-ui/primitives#549]
### Current Behavior
I get this exception when using DropdownMenu, (doesn't happen every time, and only happens to one of my coworkers, even thought we use the same env throught docker)
![image](https://user-images.githubusercontent.com/23035545/110765438-75ca7b80-8254-11eb-866e-dd7d1c5e6554.png)
I'm using Nextjs with SSR.

### Expected behavior
Should not throw any error

### Reproducible example

Couldn't reproduce in a codesandbox

### Suggested solution

Check that globalThis exists and is not undefined.

### Additional context
I'm sorry for not being able to provide more info on this. But thought it might be better than not reporting at all.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |      DropdownMenu  |   0.0.9      |
| React            | n/a     |    17.0.1     |
| Browser          |   Chrome      |    66.0.3359.181     |
| Assistive tech   |      N/A   |         |
| Node             |  n/a     |   12      |
| npm/yarn         |   yarn      |   1.8.21p2      |
| Operating System | Linux        |    5.4.5     |

**Comment by benoitgrelard** [comment]
Are you able to see any differences in your colleague's setup compared to yours?
That would help us try and track the issue.

**Comment by mglavall** [comment]
Hey, thank you for answering. My colleague updated Node and yarn to a newer version and she is not getting the error anymore.
She is now using Node v14.16 and yarn 1.22. So it might be related to this.

**Comment by benoitgrelard** [comment]
You mentioned before node 12, so yeah that might be that.
But you said you were both using the same env with docker, so wouldn't it have been both the same version of node too?

**Comment by mglavall** [comment]
Yes you are actually right. We are using the same env through docker, so I don't really know what fixed this. 
I thought it was related to it because she was using zsh with an older version of node, and when she switched to bash and updated yarn and node it didn't happen anymore. Could be a coincidence thought.

Sorry for not being able to throw more light on this

**Comment by benoitgrelard** [comment]
Do you know which version of Node 12 it was?
I've got Node 12.20.2 locally and it seems fine

![image](https://user-images.githubusercontent.com/1539897/112121923-aba62300-8bb7-11eb-8919-c4657bf9cf17.png)

**Comment by vdjurdjevic** [comment]
I had this issue with Node v10.. Switched to v12, everything works fine
