### ISSUE TITLE
RadioItem types issue: Property 'value' is missing

### ISSUE THREAD

**Issue by tarngerine** [radix-ui/primitives#552]
### Current Behavior

RadioItem complains when I try to destructure "value" out of its OwnProps

<img width="697" alt="image" src="https://user-images.githubusercontent.com/1629901/110869455-1f7b2e00-8290-11eb-8c89-8cbe0c5ea75d.png">

### Expected behavior

should allow me to

### Reproducible example

https://codesandbox.io/s/great-euler-24p0b?file=/src/App.tsx

### Suggested solution

Fix the types

**Comment by benoitgrelard** [comment]
Hi @tarngerine,

That seems correct to me, you are destructuring `vallue` from the item to render it visually inside it, but you are not passing it back on the item. When you spread the remaining `...props` they don't contain `value` but `value` is required.

**Comment by tarngerine** [comment]
Ahh thank you!
