### ISSUE TITLE
How should I use Tooltip when wrapping a disabled button

### ISSUE THREAD

**Issue by kylemh** [radix-ui/primitives#555]
### Relevant Radix Component(s)

Tooltip

### Examples from other doc sites

I tried following [Material UI's Tooltip's instructions](https://material-ui.com/components/tooltips/#disabled-elements) about wrapping the button in an element with `display: block`; however, once rendered it won't go away:

https://air-core-e6pf3a13i-air-inc.vercel.app/?path=/docs/zephyr-tooltip--default#disabled-button

**Comment by benoitgrelard** [comment]
Hey @kylemh!

Thanks for reaching out.
What Material UI suggests should work with ours too.
I think the only thing you're missing is the `pointerEvents: none` styles on the button when disabled.

Here's a quick sandbox: https://codesandbox.io/s/tooltip-on-disabled-button-ysbhn?file=/src/App.js
