### ISSUE TITLE
[CheckBox] Allow passing id to hidden checkbox input

### ISSUE THREAD

**Issue by Guardiadelcastro** [radix-ui/primitives#562]
### Overview

This issue is to consider allowing passing an id to the hidden checkbox the same as name, required, disabled, readonly, etc. With we can associate a label easier. 

### Who does this impact? Who is this for?

I would need this feature to avoid using a parent label with my label component like this.

```jsx
<label className="my-checkbox-container">
  <Checkbox name={name} ref={register(options)} {...rest} />
  <Label as="span" position="right" colon={colon} required={isRequired} help={help}>
    {label}
  </Label>
</label>
```

I think this feature could also be useful for other people.

### Additional context

I think this would be an easy improvement to implement, let me know if I need to provide more information.

Thanks and I love this project, great job!

**Comment by jjenzz** [comment]
Hey @Guardiadelcastro. Thank you, glad you're enjoying things so far 🙂 

I'm curious what issue you are experiencing with passing an `id` to the `Checkbox` currently?

With our implementation, the checkbox is actually a `button` so your id will be on the `button` and the label is labelling the `button`. Clicking the label will check the checkbox as expected.

The `input` is just an implementation detail to allow event bubbling in forms. If it wasn't for forms, we wouldn't have used an `input` at all.

I've created a sandbox to demonstrate a separate label and everything appears to be working okay. Please do let me know if there is a problem I'm overlooking though: https://codesandbox.io/s/objective-bassi-5yjxp?file=/src/App.tsx

I should also mention while we're on the topic... you will get better accessibility and improved DX if you use our `Label` component https://codesandbox.io/s/busy-spence-64mmj?file=/src/App.tsx


```jsx
import * as Checkbox from '@radix-ui/react-checkbox';
import { Label } from '@radix-ui/react-label';

render(
	<div>
		<Checkbox.Root id="checkbox-id"><Checkbox.Indicator /></Checkbox.Root>
		<Label htmlFor="checkbox-id">{label}</Label>
	</div>
);
```

Our `Label` prevents text from highlighting when someone clicks the label multiple times and the accessibility improvements are described in detail here https://discord.com/channels/752614004387610674/803656831704629298/816758848865435698

**Comment by Guardiadelcastro** [comment]
Hi @jjenzz, thanks for the response.

I wasn't sure about accessibility and the label & button interaction. I thought that the label has to be for the input itself, thanks for the explanation. 
I ended up setting everything like in the sandbox, so thanks for that also.

I´ll  also check out the label component and the discord discussion, to see if I can merge it my own.

Thanks again!
