### ISSUE TITLE
[ScrollArea] Scrollbar may show up when scroll is disabled

### ISSUE THREAD

**Issue by vladmoroz** [radix-ui/primitives#567]
## Bug report

When a dropdown menu is nested in ScrollArea, hovering a dropdown item shows ScrollArea scrollbar, although scroll is disabled at that moment:
https://codesandbox.io/s/intelligent-water-hhbn8?file=/src/App.tsx

https://user-images.githubusercontent.com/8441036/111670289-59b07680-8820-11eb-9951-14a7e09cad1e.mov

**Comment by benoitgrelard** [comment]
Hey @vladmoroz, this has now been fixed and released.
https://radix-ui.com/primitives/docs/components/scroll-area
