### ISSUE TITLE
Popover does not close when an animation is present

### ISSUE THREAD

**Issue by vassbence** [radix-ui/primitives#568]
## Bug report

The popover (v0.0.8) does not close when clicking away if the `Popover.Content` element has some css animation.

I've tested and it works fine in v0.0.7 and v0.0.6.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/exciting-lederberg-s0mfj?file=/src/App.js:0-415)

### Your environment

MacOS, latest Chrome

**Comment by jjenzz** [comment]
I've PRed a fix for this here https://github.com/radix-ui/primitives/pull/571. We'll hopefully be able to get a release out for you this week 🙂

**Comment by mglavall** [comment]
Probably same bug. It also happens to me with the DropdownMenu. I've added an example to the codesandbox in case it's useful:
[CodeSandbox](https://codesandbox.io/s/confident-pascal-mxh03?file=/package.json)

**Comment by benoitgrelard** [comment]
@mglavall yes that's the same bug.

**Comment by jjenzz** [comment]
This is now released 🎉
