### ISSUE TITLE
Flickering when using Popover primitive

### ISSUE THREAD

**Issue by vdjurdjevic** [radix-ui/primitives#578]
### Current Behavior
Hi. I am getting some weird flickering with popover primitive (v0.0.15) (tooltip, the dropdown menu also).
It happens only the first time popover is shown, and after that works as expected. Below is a video to demonstrate.
Notice how the id column in the table flickers only the first time I click on the delete button, and after that, it works fine. Also, I did
a full page refresh after that, to show that it is always reproducible. 

https://user-images.githubusercontent.com/17208031/112705831-ba832300-8ea0-11eb-9a15-179fb80dfadf.mp4

### Expected behavior

No flickering on first open.

### Reproducible example

I can provide temporary access to my repo if needed.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-popover      |   0.0.15      |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |    89     |
| Assistive tech   |         |         |
| Node             | n/a     |    12.19.1     |
| npm/yarn         |     npm    |         |
| Operating System |    Linux Mint    |         |

**Comment by benoitgrelard** [comment]
Are you able to reproduce this in a codesandbox for us to take a look?

**Comment by vdjurdjevic** [comment]
You can close it, my bad.. It's font faces issue..

**Comment by benoitgrelard** [comment]
Thanks for letting me know @vdjurdjevic!

**Comment by OlegWock** [comment]
@vdjurdjevic how did you solve that?
