### ISSUE TITLE
[DropdownMenu] Items that are invisible cause focus issues

### ISSUE THREAD

**Issue by jportela** [radix-ui/primitives#581]
### Current Behavior

When navigating with the arrow keys through a DropdownMenu that has hidden items (ie: with `display: none`), the focus selection stops when reaching the hidden item, and as such doesn't focus all items.

### Expected behavior

The visible items are focused when pressing the arrow keys, even if there are hidden items.

### Reproducible example

1. Open the Dropdown
2. Press the arrow down key repeatedly
3. Verify that the last element doesn't get focused

[CodeSandbox Example](https://codesandbox.io/s/relaxed-mestorf-ru0rd?file=/src/App.tsx)

### Suggested solution

Filter out the invisible items. I already have a PR ready for it (that includes a Storybook example).

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   `@radix-ui/react-dropdown-menu`      |   0.0.17    |
| React            | n/a     |   17      |
| Browser          |         |     Brave    |
| Assistive tech   |         |         |
| Node             | n/a     |     14    |
| npm/yarn         |         |     yarn 1.x    |
| Operating System |         |    MacOS     |

**Comment by benoitgrelard** [comment]
hi @jportela thanks for reporting this.
It does look like a bug.
Can I ask you what you are trying to do here though?

**Comment by jportela** [comment]
Hey @benoitgrelard , I'm hiding certain items using media queries, so they are not displayed in mobile viewports, using `display: none` (they should not "exist" for those viewports).

**Comment by jportela** [comment]
An alternative would be to render two dropdown menus, one hidden depending on the viewport, which could be a working interim solution.

**Comment by benoitgrelard** [comment]
Another alternative would be to simply not render the items when on smaller viewports. All you would need would be a `useMediaQuery` hook (I'm sure there are some out there already) and you'd conditionally render the items. This is probably how I chose to do it.

**Comment by jportela** [comment]
that's a good alternative @benoitgrelard, thanks! Since the menu dropdown is rendered closed on the first render (server-side), there wouldn't be a noticeable diference for users.

**Comment by benoitgrelard** [comment]
Hey @jportela, the latest version has now been published and contain changes to take hidden items.
https://radix-ui.com/primitives/docs/overview/releases#03052021

**Comment by jportela** [comment]
Awesome! Thanks!
