### ISSUE TITLE
[Dialog] Consider adding `disableOutsidePointerEvents`

### ISSUE THREAD

**Issue by Avizura** [radix-ui/primitives#585]
### Overview

I need to remove `disableOutsidePointerEvents` feature in `Dialog` component but it seems impossible  https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L241. 

### Additional context

Such option is already exists in DropdownMenu.Content component, would be useful to have it in Dialog as well.

**Comment by benoitgrelard** [comment]
Hi @Avizura,

I don't think it would make sense to allow that for our `Dialog` primitive as it's a modal dialog.
What is your use case?

**Comment by Avizura** [comment]
Hi @benoitgrelard !
I need to able to click on other cards while dialog with details of current card is opened. But now I have doubts that sidebar on the right is actually a dialog 😅
![image](https://user-images.githubusercontent.com/11854101/113599710-d8186100-95f3-11eb-829b-5c5878fff712.png)

**Comment by benoitgrelard** [comment]
Yeah so if you need to be able to interact with what's behind, that would probably be considered a non-modal dialog.
I don't think our `Dialog` primitive currently supports this well so there may be something there.

`Popover` lets you create non-modal things, but then here it's not really what you need as you don't need the whole positioning thing.

I'm currently re-writing bits of our focus scope logic so it's kinda good timing actually haha.
Let me consider your use case a little bit and discuss with @jjenzz as well and we'll figure something out.

**Comment by Avizura** [comment]
I see, thanks a lot for this lib guys

**Comment by benoitgrelard** [comment]
Hi @Avizura I just wanted to come back to you to say that we think we will be making changes to our components such as `Dialog`, `Popover`, etc to add the concept of modality. This should then resolve your issue here.

Not sure what timeframe that will be released but I will update you once that's done.

**Comment by Avizura** [comment]
@benoitgrelard Hi, cool, thanks!

**Comment by jjenzz** [comment]
@Avizura Sorry for the delay on an update here. 

We're hoping to release this week with a new `modal` prop for `Dialog`. Setting it to `false` would allow you to achieve the UI you posted 🙂

**Comment by Avizura** [comment]
I see, thanks again for your amazing work @jjenzz

**Comment by jjenzz** [comment]
@Avizura thanks but it was @benoitgrelard and @andy-hook who did this work so I cannot take credit I'm afraid 🙂
