### ISSUE TITLE
[Checkbox] The `readOnly` prop doesn't appear to be working

### ISSUE THREAD

**Issue by acc-nicholas** [radix-ui/primitives#596]
### Current Behavior
When setting the `readOnly prop on the Checkbox component, the checkbox still changes state when clicked.

### Expected behavior
I expect the the state will not change when clicked.

### Reproducible example
https://codesandbox.io/s/tender-galileo-0v3gc?file=/src/App.tsx
[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Suggested solution
Based on the MDN docs this attribute shouldn't work on checkboxes. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly
> Note: Only text controls can be made read-only, since for other controls (such as checkboxes and buttons) there is no useful distinction between being read-only and being disabled, so the readonly attribute does not apply.

So perhaps this prop should be removed from certain input types to align with the supported list on MDN.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-checkbox       |    0.0.13     |
| React            | n/a     |  17.0.2       |
| Browser          |  Chrome       | 89.0.4389.114        |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  Mac       |     10.15.7    |

**Comment by benoitgrelard** [comment]
Yeah good point, we can probably remove it.

**Comment by benoitgrelard** [comment]
@acc-nicholas I've opened a PR to remove the `readOnly` prop from relevant components #600
