### ISSUE TITLE
[DropdownMenu] Item onSelectAutoFocus preventDefault

### ISSUE THREAD

**Issue by okry** [radix-ui/primitives#598]
### Overview

In the `DropdownMenu.Item` component, have a prop that can be passed called `onSelectAutoFocus` that is an event function similar to the `DropdownMenu.Content` component's `onCloseAutoFocus` function. When this function's event is `defaultPrevented`, prevent auto-focus from firing.

### Who does this impact? Who is this for?

This would impact users who would use the `DropdownMenu` as a navigation component with `react-router-dom` to change pages when selecting an item. With this prop, users can simulate a page change without the `DropdownMenu.Trigger` from stealing focus.

This would also allow users to send focus anywhere in the document on a selection if they need to.

### Additional context

The reason why using this would be better than just `defaultPreventing` the `onSelectAutoFocus` event is that users would be able to opt-out of focusing the trigger on selection instead of having to opt-into focusing the trigger for everything but their selection.

**Comment by benoitgrelard** [comment]
Hi @okry,

I am not sure I am really following what you are requesting here, or what the issue you're having in the first place is.
It would really help us a lot if you could post here a codesandbox instead demonstrating what you are trying to do with our component but is causing you an issue.

**Comment by okry** [comment]
Here's a CodeSandbox: https://codesandbox.io/s/epic-ives-5v9by?file=/src/App.js
It shows two examples: the first one doesn't quite work, but is close to what I'm trying to achieve, and the second example shows what I need to do to work around it.

**Comment by benoitgrelard** [comment]
Hi @okry,

Thanks for providing the sandbox.
The second example is overly verbose because you have prevented the autofocus on close "all the time".
You absolutely can do that only when you need to.

Here I've forked your sandbox to show a potential way of achieving what you are trying to do without having to be overly verbose for all the other items.

https://codesandbox.io/s/focus-from-menu-item-hjvbl

That said (and that's probably a separate issue) I am still unclear why the next tick is needed for the focus to work (even after preventing the autofocus).

**Comment by okry** [comment]
I'm not sure about the `nextTick` part, but it won't work without it. It's probably due to some sort of focus trap that is removed after the tick that that code is executed.

The example you provided will work for me and it seems like it works with any mutable boolean, not just `skipCloseAutoFocusRef.current`. Regardless, it would still be nice if there was a more graceful way to achieve this, but now that I see that there is a way to address this without a lot of verbosity I can understand if this is a lower priority.

**Comment by benoitgrelard** [comment]
I will leave this issue open as a potential enhancement and open another one to investigate the next tick thing.
Thanks @okry! 🙏

**Comment by benoitgrelard** [comment]
Hi @okry,

I have an update for you.

If you're interesting in the background discussion, we discussed over in #622. It may help you understand our decision to keep things as is.

In doing so, @jjenzz came up with an even more elegant solution for what you're trying to do which built on top of what I had done.

The gist is:
- it doesn't require next tick
- it doesn't require fiddling with props

https://codesandbox.io/s/focus-from-menu-item-forked-g9zc8

What I really love about this is that it ties in the need to prevent default to the custom focus need in one fell swoop.
I will close this issue now as we think this is a good resolution.

**Comment by okry** [comment]
Awesome, yeah, that should work. Thanks for the help!
