### ISSUE TITLE
[Dialog] Possibility to set containerRef

### ISSUE THREAD

**Issue by henrikbak** [radix-ui/primitives#601]
The contents of the Dialog component is appended to document.body be default. I would like to be able to set a different conainerRef so the dialog is appened to a different container. This is already possible in the Portal component. https://radix-ui.com/primitives/docs/utilities/portal (I am not sure if the Dialog component uses the Portal component).

Would this be a feature you would consider adding?

**Comment by jjenzz** [comment]
I'm curious of your use-case here. Why do you need to portal it to a different container?

**Comment by henrikbak** [comment]
I'm using Stitches and if I apply a custom theme (https://stitches.dev/docs/theming#apply-the-theme) to a specific container inside my application like so:

```
<div className={darkTheme}>
  <Box>Content nested in dark theme.</Box>
</div>
```

Only elements inside the container will get the theme variables applied. The Dialog won't get the styles applied, because it's inserted further up the DOM. I hope this makes sense?

Another use case is this - I run my application as a sidebar widget which is embedded on a website. If I use a Dialog component inside the widget it will appear as a modal over the entire website. Instead I would like to be able to append it just inside the widget wrapper.

I know these are properly edge cases.

**Comment by benoitgrelard** [comment]
- For the first use-case, you should be able to add your theme `className` onto the dialog's content, no?
- For the second use-case, I'm not sure I fully get it, if you were trying to append the dialog inside the widget wrapper (ie. the sidebar, kinda like an iframe), then the Dialog would have almost no space to open in there right?

**Comment by henrikbak** [comment]
1. You are probably right - I will try it out. For all other purposes setting the theme className on the wrapper of the entire application is enough.
2. Yes, the Dialog would fill up most of the space in the widget. I agree that dialogs maybe not are suited for that specific use case.

**Comment by jjenzz** [comment]
@henrikbak You can also apply the class imperatively to the `body` I believe https://codesandbox.io/s/dazzling-brook-rg0y9?file=/src/App.js

**Comment by henrikbak** [comment]
@jjenzz Nice! I haven't thought of that. I guess that solves my first use case. 

As for the second one (widget), I guess another component would be better suited.
