### ISSUE TITLE
[DropdownMenu] Jumps on mobile

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#603]
Reported here https://twitter.com/yeukang/status/1382357272718893059

Looks like collision detection isn't working quite right perhaps?

**Comment by benoitgrelard** [comment]
Note: cannot reproduce on iOS Safari, user said it was on iOS Chrome (which is weird because all browsers are Safari on iOS I thought)

**Comment by jjenzz** [comment]
I was able to reproduce this just now 

https://user-images.githubusercontent.com/175330/122190048-5cefe880-ce89-11eb-84b6-4e3a58e4def6.MOV

**Comment by benoitgrelard** [comment]
I imagine it's something to do with the remove scroll thing
