### ISSUE TITLE
[Presence] Add `animation-direction` support

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#608]
Benoit and I spoke about this before but just wanted to get it written down.

For enter and exit animations to work currently, the animation `name` must be changed. This forces consumers to hardcode the reverse of their animation as a new set of keyframes.

It would be great if consumers could do something like:

```jsx
const fade = keyframes({
	from: { opacity: 0 },
	to: { opacity: 1 },
});

const DropdownMenuContent = styled(DropdownMenu.Content, {
	animation: `${fade} 100ms`,
	'&[data-state="open"]': {
		animationDirection: 'normal',
	},
	'&[data-state="closed"]': {
		animationDirection: 'reverse',
	},
});
```

instead of:

```jsx
const fadeIn = keyframes({
	from: { opacity: 0 },
	to: { opacity: 1 },
});

const fadeOut = keyframes({
	from: { opacity: 1 },
	to: { opacity: 0 },
});

const DropdownMenuContent = styled(DropdownMenu.Content, {
	'&[data-state="open"]': {
		animation: `${fadeIn} 100ms`,
	},
	'&[data-state="closed"]': {
		animation: `${fadeOut} 100ms`,
	},
});
```

**Comment by benoitgrelard** [comment]
There is a caveat when using animation direction with easing, as it will literally play the animation backwards, including its easing. This is most likely not what you're after in general.

With all that said, I agree it's probably a good idea to support it, but probably not a huge priority given the caveat.

**Comment by colmtuite** [comment]
Sounds like a good argument for `transition` support 😃

**Comment by benoitgrelard** [comment]
I remember trying that when we looked at it and I don't think it worked as expected, but we should try again.

**Comment by jjenzz** [comment]
Yes it didn't work because `Presence` doesn't listen for change to `animationDirection`, that's what this ticket is for 😛  

I'm saying that when we add that support, wouldn't adding `animationTimingFuction` to each state solve the problem you described above of it reversing the easing?

**Comment by benoitgrelard** [comment]
Yeah perhaps that would you're right. We'll have to try!

**Comment by benoitgrelard** [comment]
We've decided to de-prioritise this as the current solution works fine.
