### ISSUE TITLE
[Label] `onClick` `stopPropagation()` not working inside `Label`

### ISSUE THREAD

**Issue by rafgraph** [radix-ui/primitives#609]
### Current Behavior

Calling `stopPropagation()` on an `onClick` event on a child of a `Label` still clicks the label and toggles the associated `Checkbox`.
EDIT: this also applies to calling `preventDefault()` on the `click` event.

### Expected behavior

For the `Label` to not receive a click event when a child stops propagation.

### Reproducible example

https://codesandbox.io/s/radix-label-stop-propagation-bug-2loxf

### Suggested solution

It seems like `Label` is not using the React event system for click events, so using the React event system should fix this issue.

### Additional context

Use case: a Label that contains an info link. When the link is clicked I want to stop propagation so the Checkbox isn't toggled.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     Label    |     0.0.11    |
| React            | n/a     |     17    |

**Comment by ksandin** [comment]
I found a similar issue with react-checkbox: https://codesandbox.io/s/checkbox-stoppropagation-doesnt-work-7xn4u?file=/src/App.js

**Comment by jjenzz** [comment]
Fixed in [0.1.1-rc.2](https://www.npmjs.com/package/@radix-ui/react-label/v/0.1.1-rc.2)
