### ISSUE TITLE
Dropdown menu closes on pointerup when placed over trigger

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#610]
### Current Behavior

If the DropdownMenu content is placed above the trigger, then a click will open and dismiss the menu.

![Kapture 2021-04-20 at 13 02 14](https://user-images.githubusercontent.com/23072548/115392601-a8af4a00-a1d8-11eb-9196-3ef10e5ac7f3.gif)

### Expected behavior

There are two interactions that I think are clashing here. 

The first is when a user start a click, then moves their pointer over an item that they want to select, and then stops the click to select it. 

The second is when a user clicks once to open the menu, then moves to an item that they want to select, and clicks again to select it.

The menu normally makes a good distinction between the two, however when the menu is located on top of the trigger, the interactions clash.

### Reproducible example

https://codesandbox.io/s/thirsty-mestorf-6478j

### Suggested solution

Enter a maybe-clicking state on pointer down. Require a movement of some length to enter a drag-selecting state, in which any pointer-up will close the menu and select a hovered item, if any. If the pointer-up occurs while the user is still in the maybe-clicking state, then ignore it.

**Comment by benoitgrelard** [comment]
Hi @steveruizok,

Can I ask where you are going with this?
I don't think it makes much sense to put the menu over the trigger as part of a dropdown menu.

**Comment by steveruizok** [comment]
You know, I'm probably reaching more for a select here than a dropdown menu.

![Kapture 2021-04-20 at 13 51 12](https://user-images.githubusercontent.com/23072548/115398864-7fde8300-a1df-11eb-9f9c-a2dfea6eeb4f.gif)

![Kapture 2021-04-20 at 13 49 11](https://user-images.githubusercontent.com/23072548/115398581-35f59d00-a1df-11eb-85a8-0e9d31f10a78.gif)

**Comment by benoitgrelard** [comment]
Yes, that's what I was thinking you'd say 🙂 
We will have a `Select` primitive soon.
