### ISSUE TITLE
[DropdownMenu] TypeScript errors when copying doc's example

### ISSUE THREAD

**Issue by paulintrognon** [radix-ui/primitives#619]
### Current Behavior

Within a React TypeScript project, with `@radix-ui/react-dropdown-menu` installed, I copied the **implementation** section of the [documentation for custom implementation](https://radix-ui.com/primitives/docs/components/dropdown-menu#abstract-the-arrow-and-item-indicators).
Without making any changes, I have a lot of TypeScript errors:
```
No overload matches this call.
  Overload 1 of 3, '(props: MergeProps<"div", Omit<Omit<MenuOwnProps, "trapFocus" | "onOpenAutoFocus" | "onDismiss">, "anchorRef"> & { anchorRef?: RefObject<Measurable> | undefined; } & { ...; }>): ReactElement<...> | null', gave the following error.
    Type 'ForwardedRef<unknown>' is not assignable to type '((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
      Type 'MutableRefObject<unknown>' is not assignable to type '((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
        Type 'MutableRefObject<unknown>' is not assignable to type 'RefObject<HTMLDivElement>'.
          Types of property 'current' are incompatible.
            Type 'unknown' is not assignable to type 'HTMLDivElement | null'.
              Type 'unknown' is not assignable to type 'HTMLDivElement'.
  Overload 2 of 3, '(props: MergeProps<ElementType<any>, Omit<Omit<MenuOwnProps, "trapFocus" | "onOpenAutoFocus" | "onDismiss">, "anchorRef"> & { anchorRef?: RefObject<Measurable> | undefined; } & { ...; }>): ReactElement<...> | null', gave the following error.
    Property 'as' is missing in type '{ children: (ReactNode | Element)[]; ref: ForwardedRef<unknown>; }' but required in type '{ as: ElementType<any>; }'.
  Overload 3 of 3, '(props: MergeProps<"div", Omit<Omit<MenuOwnProps, "trapFocus" | "onOpenAutoFocus" | "onDismiss">, "anchorRef"> & { anchorRef?: RefObject<Measurable> | undefined; } & { ...; }>): ReactElement<...> | null', gave the following error.
    Type 'ForwardedRef<unknown>' is not assignable to type '((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.ts(2769)
index.d.ts(815, 46): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & Omit<Omit<MenuOwnProps, "trapFocus" | "onOpenAutoFocus" | "onDismiss">, "anchorRef"> & { anchorRef?: RefObject<...> | undefined; } & { ...; } & Omit<...>'
index.d.ts(41, 9): 'as' is declared here.
index.d.ts(815, 46): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & Omit<Omit<MenuOwnProps, "trapFocus" | "onOpenAutoFocus" | "onDismiss">, "anchorRef"> & { anchorRef?: RefObject<...> | undefined; } & { ...; } & Omit<...>'
```

### Expected behavior

I believe we should not have errors when trying to reproce documenation's example, or maybe explain that it won't work in TypeScript?

### Reproducible example

https://codesandbox.io/s/damp-wood-lle2p?file=/src/Dropdown.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-dropdown-menu    |    0.0.17     |
| React            | n/a     |    17.0.2     |
| Node             | n/a     |   14.0.4      |
| npm/yarn         |    yarn     |    1.22.5     |
| Operating System |     Debian    |         |

**Comment by benoitgrelard** [comment]
Hi @paulintrognon,

The examples in the docs are in JavaScript, not Typescript.

The error you are getting `Type 'unknown' is not assignable to type 'HTMLDivElement'.` makes sense because you haven't typed the `ref` (nor the `props`) when you called `React.forwardRef`.

There's a couple places in our docs where you can learn more about how to extend components and type them correctly:

- https://radix-ui.com/primitives/docs/overview/styling#styling-a-part: This section shows 2 examples, depending on whether you care about keeping polymorphic types or not
- https://radix-ui.com/primitives/docs/utilities/polymorphic#extending-a-polymorphic-component: this is another section going in more details with regards to extending with polymorphic types

Let us know if it helps!

**Comment by jjenzz** [comment]
Closing as stale.

**Comment by hansdaemon** [comment]
@nuthinking https://typescripts.space/questions/the-data-type-unknown-cannot-be-directly-converted-to-a-number-type-in-typescript
