### ISSUE TITLE
Cannot find name 'FocusScopeProps'.

### ISSUE THREAD

**Issue by kaisermann** [radix-ui/primitives#636]
### Current Behavior

When I try to build the types for my component library that uses `@radix-ui`, the TypeScript compiler screams that it can't find the `FocusScopeProps`:

![image](https://user-images.githubusercontent.com/12702016/117136594-f605ec80-ad7e-11eb-9728-5b241f579c5a.png)

https://github.com/kaisermann/radix-repro-1

### Expected behavior

Build the types without an issue 🙈 

### Reproducible example

https://github.com/kaisermann/radix-repro-1

```shell
$ npm install
$ npm run build
```

### Suggested solution

Didn't investigate it yet, but it seems that it's just missing an import on the generated typing file:

![image](https://user-images.githubusercontent.com/12702016/117136666-10d86100-ad7f-11eb-977f-5d22edaee334.png)

## System:
 - OS: macOS 11.2.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 189.97 MB / 16.00 GB
 - Shell: 3.1.2 - /usr/local/bin/fish
## Binaries:
 - Node: 14.15.4 - ~/.volta/tools/image/node/14.15.4/bin/node
 - Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
 - npm: 7.5.4 - ~/.volta/tools/image/npm/7.5.4/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @radix-ui/react-dialog: ^0.0.16 => 0.0.16

**Comment by benoitgrelard** [comment]
Hey @kaisermann, thanks for reporting this, it does seem that the props disappeared from our output between previous and latest:

- https://unpkg.com/browse/@radix-ui/react-focus-scope@0.0.11/dist/index.d.ts
- https://unpkg.com/browse/@radix-ui/react-focus-scope@0.0.12/dist/index.d.ts

I'm investigating and hopefully we can publish a fix soon.

**Comment by kaisermann** [comment]
Hey, @benoitgrelard 👋 Thanks for the quick response! If this is somewhat related, I also started to get this one:

![image](https://user-images.githubusercontent.com/12702016/117145415-85180200-ad89-11eb-8f2d-baa51fd037cd.png)

It seems the `react-menu` package has some typing references to the original source file. If this is an unrelated problem, I can create another issue.

**Comment by benoitgrelard** [comment]
Thanks, I have a fix for the original issue, but I'll take a look at this one now too.

**Comment by benoitgrelard** [comment]
Hi @kaisermann, I've split the second issue and sent it to #640 as it's quite a bit more involved than the original issue for which I'll send a PR now.
