### ISSUE TITLE
[Popover] using `event.preventDefault` within `onInteractOutside` prevents focus

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#646]
Using the following composition:

```jsx
<div>
  <Popover.Root>
    <Popover.Trigger>Open</Popover.Trigger>
    <Popover.Content
      trapFocus={false}
      disableOutsidePointerEvents={false}
      onInteractOutside={(event) => event.preventDefault()}
    >
      Content
    </Popover.Content>
  </Popover.Root>
  <label>
    label <input />
  </label>
</div>
```

https://codesandbox.io/s/peaceful-brook-lwykw?file=/src/App.js

We should be able to focus the input when the Popover is open but can't.

It seems our `usePointerDown` hook within `DismissableLayer` binds to native `mousedown` so when a consumer calls `event.preventDefault()` it prevents `mousedown` too, which in turn prevents focus.

**Comment by benoitgrelard** [comment]
I'm taking this one as the modality work is requiring me to fix it anyway 👍
