### ISSUE TITLE
[Checkbox] An invalid form control with name='' is not focusable

### ISSUE THREAD

**Issue by henrikbak** [radix-ui/primitives#649]
### Current Behavior

Adding Checkbox.Root with required prop inside a form and submitting the form results in `An invalid form control with name='' is not focusable`.

### Expected behavior

A default browser validation alert should appear near the checkbox e.g. "Please tick this box if you want to proceed". No errors in the log.

### Reproducible example

https://codesandbox.io/s/recursing-mendel-vios3?file=/src/App.js

**Comment by benoitgrelard** [comment]
Hi @henrikbak,

Thanks for reporting an issue.
Where do you see this error?
> An invalid form control with name='' is not focusable

I don't see any logs or anything in the sandbox.

**Comment by henrikbak** [comment]
Hi @benoitgrelard 

I see the error in the devtools console in Chrome - for some reason the error does not appear in the CodeSandbox console. The error appears when I press the submit button without checking the required checkbox.

<img width="457" alt="Screenshot 2021-05-12 at 10 59 58" src="https://user-images.githubusercontent.com/1537650/117948455-709bb280-b311-11eb-8b73-05a7ed2c0205.png">

**Comment by benoitgrelard** [comment]
Ah yeah, thanks.

**Comment by benoitgrelard** [comment]
Hey @henrikbak, this has now been fixed and released.
