### ISSUE TITLE
Limit polymorphic intrinsic elements 

### ISSUE THREAD

**Issue by smhmd** [radix-ui/primitives#653]
### Overview

The idea behind this is to only be able to pass a limited number of elements as the `as` prop. For instance, a polymorphic input that can be either an input, a textarea, or another specific custom component (as opposed to anything that the user wants.)

### Examples in other libraries

❌ 

### Who does this impact? Who is this for?

Polymorphic components usually are not really meant to be used with every intrinsic element out there or any component in a given component library of a project, but the option to be explicit about what can be used and what can not offer better documentation and type safety.  

### Additional context

I would imagine the the union could be passed as a third argument for the `ForwardRefComponent` generic:
```scala
ForwardRefComponent<"input", {}, "input" | "textarea" | ThirdPartyInputComponent>
```

**Comment by jjenzz** [comment]
Closing this issue because polymorphism has been removed in favour of [the `asChild` prop](https://www.radix-ui.com/docs/primitives/overview/styling#changing-the-rendered-element).
