### ISSUE TITLE
[RadioGroup] Name property of RadioGroupItem is not passed down to the input

### ISSUE THREAD

**Issue by Guardiadelcastro** [radix-ui/primitives#655]
### Current Behavior

The name property is not passed down to the radio group item. If I try to pass it down it shows an error that the type for name is never or undefined and inspecting the types it shows as such.

![image](https://user-images.githubusercontent.com/24862447/118959339-242c2480-b95a-11eb-8dd7-d60620e0a818.png)

error:
```text
(JSX attribute) name?: never
No overload matches this call.
  Overload 1 of 2, '(props: Merge<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, Omit<...> & { ...; } & { ...; }>): ReactElement<...>', gave the following error.
    Type 'string' is not assignable to type 'never'.
  Overload 2 of 2, '(props: Merge<Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "key" | keyof ButtonHTMLAttributes<...>> & { ...; }, Omit<...> & ... 1 more ... & { ...; }>): ReactElement<...>', gave the following error.
    Type 'string' is not assignable to type 'never'.ts(2769)
index.d.ts(27, 5): The expected type comes from property 'name' which is declared here on type 'IntrinsicAttributes & Omit<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "as" | ... 5 more ... | "onCheckedChange"> & Omit<...> & { ...; } & { ...; }'
index.d.ts(27, 5): The expected type comes from property 'name' which is declared here on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "key" | keyof ButtonHTMLAttributes<...>> & { ...; }, "as" | ... 5 more ... | "onCheckedChange"> & Omit<...> & { ...; } & { ...; }'
```

```html
<input type="radio" style="display: none;" value="cat">
```

```ts
type RadioGroupItemOwnProps = Polymorphic.Merge<Polymorphic.OwnProps<typeof Radio>, {
    value: string;
    name?: never;
}>;
```
### Expected behavior

The name property type is a string and is passed down to the RadioGroupItem

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radixui-radio-group-1p8cw)

### Suggested solution

I don't know if this could be the solution. In the Radio.tsx file, for the RadioOwnProps specify the name property:

```ts
type RadioOwnProps = Polymorphic.Merge<
  Polymorphic.OwnProps<typeof Primitive>,
  {
    name?: string;
    checked?: boolean;
    defaultChecked?: boolean;
    required?: InputDOMProps['required'];
    onCheckedChange?: InputDOMProps['onChange'];
  }
>;
```

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-radio-group | 0.0.16 |
| React            | n/a     | 17.0.1 |
| Browser          |  firefox | 6.14.13 |
| Assistive tech   |         |         |
| Node             | n/a     | 14.17.0 |
| npm/yarn         |  npm  | 6.14.13 |
| Operating System | Windows 10 |  2004  |

**Comment by benoitgrelard** [comment]
Hi @Guardiadelcastro,

This is by design and the reason it's not a prop on `Item` is because it's a prop on the top-level `Root`.
Internally we will propagate it on each input seeing as a group of radios should all have the same `name` for it to work as a group. This is also better DX as you don't need to repeat it on each item.

If that is satisfactory, then feel free to close the issue.

**Comment by Guardiadelcastro** [comment]
Thanks for the quick response. 

I tried setting the name in the root element and it worked, also with react-hook form, so I will close the issue.

The only thing is that the docs still say that name is a prop of Item.
