### ISSUE TITLE
[ContextMenu] immediately closes when there's no padding or on `Content`

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#656]
## Bug report

Reported on Discord: https://discord.com/channels/752614004387610674/803656530259738674/844486103720656897

### Reproducible example

https://codesandbox.io/s/funny-jennings-li8s9?file=/src/App.js:413-487

**Comment by benoitgrelard** [comment]
Hey @horacioh, this has now been released.

**Comment by horacioh** [comment]
awesome! thanks!!

_
Horacio Herrera
https://horacioh.com
