### ISSUE TITLE
[Checkbox] onClick stopPropagation() not working inside Checkbox

### ISSUE THREAD

**Issue by ksandin** [radix-ui/primitives#667]
### Current Behavior

Calling stopPropagation() on an onClick event on a Checkbox element does not actually stop event propagation.

### Expected behavior

Calling stopPropagation() should stop event propagation.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/checkbox-stoppropagation-doesnt-work-7xn4u?file=/src/App.js)

### Your environment

react 17.0.2 and @radix-ui/react-checkbox 0.0.15

**Comment by benoitgrelard** [comment]
Done some quick testing on this.
Stopping propagation actually works correctly from the standpoint of the Checkbox (button).
What seems to be happening is that the events are duplicated and so what you see is the one bubbling from the input.
You can verify this by not stopping propagation, you see duplicate click events on the li.

**Comment by jjenzz** [comment]
@ksandin Thanks for reporting. We've just merged a fix for this which will be available in our next release.

**Comment by benoitgrelard** [comment]
Hey @ksandin, this fix has now been released.
