### ISSUE TITLE
[Tooltip] Icon button labelling for the Lighthouse/Axe-core reports

### ISSUE THREAD

**Issue by blvdmitry** [radix-ui/primitives#697]
## Bug report

Accessibility report tooling reports can't find any label associated with them for the icon buttons using Tooltip component. This happens because aria-labelledby and id attributes are added dynamically during the user interaction. This means that they're correctly pronounced by screen readers but can't be validated by the tooling working with the accessibility tree.

### Current Behavior

https://radix-ui.com/primitives/docs/components/tooltip#basic-example

Running Lighthouse report against this Basic example will show that Button has no label assigned.

### Expected behavior

Lighthouse report should pass on this example.

### Reproducible example

https://radix-ui.com/primitives/docs/components/tooltip#basic-example

### Suggested solution

I would expect the example either to:
1. Have an aria-label assigned to the button. That's also what react-spectrum does. However, this means that aria-labelled by will also be pronounced, so if the label is the same it will be read twice.
2. Have a placeholder aria-label or a placeholder element with a temporary id just to satisfy the accessibility reports. I'm not a fan of this approach but it sounds like something that won't cause users to come up with 2 different labels for the component.

### Your environment

Any environment

**Comment by jjenzz** [comment]
Hi @blvdmitry, thanks for raising this. 

I wouldn't say this is a bug as our focus is accessibility which you've said works fine.

Unfortunately, pleasing test tooling with workarounds in our code (that aren't required for accessibility) isn't a priority of ours atm, sorry about that. 

If you have any resources on how this impacts accessibility then please do share, we'd love to take a look and reconsider if so 🙏
