### ISSUE TITLE
[ContextMenu] iOS and iPadOS touch support

### ISSUE THREAD

**Issue by rafgraph** [radix-ui/primitives#701]
## Bug report

I'm not sure of the right way to classify this issue: is it a bug report, feature request, or discussion? The `contextmenu` event doesn't fire on iOS and iPadOS when using touch input (it does on iPad OS when using a mouse), but my general belief is that all components should work cross browser and cross device (latest versions only) even if some browser and device specific workarounds are required.

### Current Behavior

The Radix context menu never appears on iOS and iPadOS when using touch input.

### Expected behavior

To be able to access the Radix context menu on iOS and iPadOS when using touch input.

### Reproducible example

Use the doc page demos on an iOS or iPadOS device: https://radix-ui.com/primitives/docs/components/context-menu

### Suggested solution

Android fires the `contextmenu` event on long press, so maybe implement a long press trigger on iOS and iPadOS?

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Context Menu     |    v0.0.19     |
| React            | n/a     |    v17    |
| Operating System |    iOS and iPadOS     |    v14     |

**Comment by benoitgrelard** [comment]
This is a really interesting one to me.
I can certainly see where you're coming from but I'm not sure this would be the right direction to go.

Some patterns make sense on some platforms but don't necessarily carry over to others.
There's probably a reason why `onContextMenu` doesn't fire on things like iOS or iPadOS?
Having to know you need to do a long press on something to bring up a menu seems very hidden and not really discoverable.

You could argue the same about right-click on desktop (which I mostly would agree with), but it's still IMO a much more known pattern by way more people (although I'd still in general encourage most capabilities to be exposed another way than just right-click anyway…)

I feel like in most cases, on a touch device, you'd probably be better off using `DropdownMenu` with a nice trigger at the end of a row for example in a list view.

Would love to discuss this further though, it's a very blurry area.

**Comment by rafgraph** [comment]
I agree that it’s not easily discoverable and in most cases there is probably a better way to design the UX. But there’s a big difference between not intuitive and not available, and it would be nice to have the option when designing a UX, especially when feature parity across all devices is a requirement. The `contextmenu` Is implemented in all Android browsers (AFAIK), so it’s use on touch devices is not unprecedented. 

Here’s an example where I think the UX could make sense. In a text messaging app, long press a message to bring up the context menu to edit/delete/forward the message.

I’m not sure why Apple didn’t implement it in iOS. iOS still has a long press “context menu” with limited control using `-webkit-touch-callout`, but it doesn’t fire the `contextmenu` event.

**Comment by rafgraph** [comment]
Enhancement makes sense 👍

Also, I think the importance of discoverability depends on the type of app. For a public app used by lots of people infrequently, discoverability is very important. For an internal company app used by trained employees frequently, discoverability is less important (everything's a tradeoff).

**Comment by benoitgrelard** [comment]
@rafgraph, I have opened a PR (#743) with the added support. Let me know if this is what you expected or if you have any feedback 🙏

**Comment by rafgraph** [comment]
Thanks @benoitgrelard, that was quick!!

**Comment by benoitgrelard** [comment]
@rafgraph this has now been released.
