### ISSUE TITLE
[ToggleGroup] Weird focus behavior in Safari (MacOS, iOS and iPadOS)

### ISSUE THREAD

**Issue by rafgraph** [radix-ui/primitives#703]
## Bug report

EDIT: this applies to Safari on all platforms (iOS, iPadOS, and MacOS).

### Current Behavior

MacOS Safari using mouse input:

https://user-images.githubusercontent.com/11911299/121565598-95f00f00-c9ea-11eb-81ae-011e90734253.mov

iOS iPhone using touch input:
https://user-images.githubusercontent.com/11911299/121562868-e154ee00-c9e7-11eb-9cc6-993c47243bc7.MP4

iPadOS iPad using mouse input:
https://user-images.githubusercontent.com/11911299/121562878-e3b74800-c9e7-11eb-933e-d6988fe93477.MP4

### Expected behavior

Focus should match the selected toggle, or not be called (by default Safari doesn't call focus on buttons from touch and mouse input).

### Reproducible example

Use the demo on the docs page with Safari (MacOS, iOS, iPadOS): https://radix-ui.com/primitives/docs/components/toggle-group

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Toggle Group     |    v0.0.8     |
| React            | n/a     |    v17     |
| Browser          |    MacOS, iOS and iPadOS  Safari   |    v14     |

**Comment by benoitgrelard** [comment]
Wow, that is a weird one! Thanks for reporting it! We'll take a look. 🙏

**Comment by benoitgrelard** [comment]
@rafgraph this has now been fixed and released.
