### ISSUE TITLE
[Tooltip] Reappears when switching tabs/apps

### ISSUE THREAD

**Issue by rafgraph** [radix-ui/primitives#705]
## Bug report

Branched from related issue: https://github.com/radix-ui/primitives/issues/617

### Current Behavior

When switching tabs or applications, the tooltip can reappear. This happens when the tooltip trigger still has focus (but the tooltip is not shown). When switching tabs/apps, the browser calls focus on the tooltip trigger when switching back, causing the tooltip to show again. Note that this happens on Chrome v91 MacOS, but not Safari MacOS as Safari doesn't blur-and-re-focus on tab/app switching.

### Expected behavior

The tooltip should not show when switching tabs/apps (unless it is shown when leaving the tab/app).

### Reproducible example

https://user-images.githubusercontent.com/11911299/121581809-49153400-c9fc-11eb-9119-fa5b48cf4def.mov

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Tooltip     |    0.0.18     |
| React            | n/a     |    17     |
| Browser          |    Chrome     |     91    |

**Comment by andy-hook** [comment]
Hey! thanks for breaking this out into a separate issue. As mentioned there are a few things going on here and we'll try to address this visual quirk when we have time 🙏

**Comment by Clee681** [comment]
I think I'm seeing the same issue, but for a different scenario. I have a button that opens a `Dialog`, and that button also uses the `Tooltip` component. Anytime I close the `Dialog` (e.g. via the `esc` key or a click outside the dialog's content) the tooltip is re-shown.

**Comment by benoitgrelard** [comment]
Yes that's the same "issue".

**Comment by GrandChieftain** [comment]
Check my recent comment on the original issue, pretty sure this issue can worked around using the same logic: https://github.com/radix-ui/primitives/issues/617#issuecomment-1680845097.
