### ISSUE TITLE
`Slot` not working with `React.useImperativeHandle`

### ISSUE THREAD

**Issue by Kerumen** [radix-ui/primitives#711]
### Current Behavior

I'm creating a custom tooltip following the [docs here](https://radix-ui.com/primitives/docs/components/tooltip#custom-apis). Everything works well with DOM elements but when I'm using a custom component with `React.useImperativeHandle` it throws with

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

I narrowed it down to the `useImperativeHandle` call. If I remove it it works fine, but I need it to forward the `.focus()` function.

### Expected behavior

It should work and not throw.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/gallant-rgb-ebzy8)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix-ui/react-polymorphic        | v0.0.11        |
|                  | @radix-ui/react-slot | v0.0.10 |
|                  | @radix-ui/react-tooltip | v0.0.18 |
| React            | n/a     | v17.0.1 |
| Browser          | Chrome        | v91.0.4472.101        |
| Node             | n/a     | v12.20.0        |
| yarn             | n/a        | v1.22.10        |
| Operating System | macOS        | v10.15.7        |

**Comment by benoitgrelard** [comment]
Hey @Kerumen,

Thanks for reporting an issue.
Can I ask what you're trying to achieve with `useFocusableRef`?

**Comment by Kerumen** [comment]
@benoitgrelard I'm forwarding the `.focus()` handler. If a parent component call `.focus()` on my `Button`, it should be forwarded to the `.focus` on the `button` DOM element.

**Comment by benoitgrelard** [comment]
I assumed this wasn't the real use-case, as you don't need this to achieve what you want.

This is enough:

```tsx
const Button = React.forwardRef<HTMLButtonElement>((props, ref) => {
  return <button ref={ref} {...props} />;
});
```

Am I missing something?

**Comment by Kerumen** [comment]
Indeed, this is sufficient for my usage. I re-used an old code without challenging it 😄 

Anyway, is it a valid bug for Radix? I think it is, it should not throw the React error. What do you think?

**Comment by benoitgrelard** [comment]
Potentially, I haven't really looked into it yet. `useImperativeHandle` is also so rare that it is probably safe to ignore for now.
Especially given the fact that `Slot` is to be used around an element, and by using `useImperativeHandle` you'd lose the actual DOM ref.

**Comment by Kerumen** [comment]
Makes sense. Feel free to close the issue if you like :)
