### ISSUE TITLE
PageUp/PageDown are backward on Slider (don't match ArrowUp/ArrowDown)

### ISSUE THREAD

**Issue by tjcrowder** [radix-ui/primitives#715]
## Bug report

The effects of <kbd>PageUp</kbd> and <kbd>PageDown</kbd> on the Slider are backward (don't match <kbd>ArrowUp</kbd> and <kbd>ArrowDown</kbd>).

### Current Behavior

Using <kbd>PageUp</kbd> on the [Slider demo page](https://radix-ui.com/primitives/docs/components/slider#basic-example) *decreases* the value rather than increasing it (it goes the opposite direction to <kbd>Up</kbd>).

Using <kbd>PageDown</kbd> *increases* the value rather than decreasing it.

At first I thought this was a not-obvious-to-me design choice, but the (truly wonderful) documentation says

> <kbd>ArrowUp</kbd> Increases the value by the `step` amount.
> ...
> <kbd>PageUp</kbd> Increases the value by a larger `step`.

So they're clearly meant to match (whew).

This is consistent on Chromium-bsed browsers and Firefox.

### Expected behavior

<kbd>PageUp</kbd> should increase the amount by a larger `step`, and <kbd>PageDown</kbd> should decrease the value by a larger `step`, so they match the direction of <kbd>ArrowUp</kbd> and <kbd>ArrowDown</kbd> and the documentation.

### Reproducible example

The [basic example in the docs](https://radix-ui.com/primitives/docs/components/slider#basic-example) demonstrates the bevhavior.

### Suggested solution

In `packages/react/slider/src/Slider.tsx`, change what's currently lines 21-24:

```js
const BACK_KEYS: Record<Direction, string[]> = {
  ltr: ['ArrowDown', 'Home', 'ArrowLeft', 'PageUp'],
  rtl: ['ArrowDown', 'Home', 'ArrowRight', 'PageDown'],
};
```

to

```js
const BACK_KEYS: Record<Direction, string[]> = {
  ltr: ['ArrowDown', 'Home', 'ArrowLeft', 'PageDown'],
  rtl: ['ArrowDown', 'Home', 'ArrowRight', 'PageUp'],
};
```

### Your environment

Just the documentation's demo in Brave 1.25.68 (built on Chromium: 91.0.4472.77) on Linux, Firefox v89 on Linus, and Chrome v91.0.4472.106 on Windows.

**Comment by tjcrowder** [comment]
(I'd do a PR but I've never even used the lib, I just happened to notice the behavior when looking at whether to use it. [It looks great!] In fact, I did fork the repo and make the tiny change above and the tests are all green, but I couldn't get a test setup working to actually try it in the browser in the time I had avaialble.)

**Comment by benoitgrelard** [comment]
Fixed here #718. In fact it wasn't inverted, pageDown should always go down, and pageUp should always go up so only one of them was wrong.

Thanks for spotting it! 🙏

**Comment by tjcrowder** [comment]
@benoitgrelard - Doh! Of course. Fast work!

**Comment by benoitgrelard** [comment]
That's now been released @tjcrowder.
