### ISSUE TITLE
[Tooltip] Export TooltipArrowOwnProps

### ISSUE THREAD

**Issue by mjoyce** [radix-ui/primitives#717]
### Current Behavior

Currently the `TooltipContentOwnProps` and `TooltipTriggerOwnProps` are exported, which is handy when typing exposed props that a custom implementation can override. However, it is necessary to "hand type" the Arrow props (i.e width, height, offset) because they are not exported.

### Expected behavior

`TooltipArrowOwnProps` are exported to expose a consistent typing of the underlying primitive.

### Suggested solution

Export `TooltipArrowOwnProps`

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-tooltip | 0.0.18 |

**Comment by mjoyce** [comment]
I was grabbing the `TooltipContentOwnProps` off of the 'root' export... I now see that it is not explicity exported from the package. Thanks for the additional tip. However in my case it is not the styling, but the actual API props of the underlying Arrow/Content/Trigger primitives I am looking to expose through my interface. And I was thinking rather than build a facade to the primitive API, why not just reference the underlying types directly as I am doing below with `contentProps`:

```
import * as TooltipPrimitive from '@radix-ui/react-tooltip';

export interface TooltipProps {
  text: string;
  arrowProps?: {
    width?: number;
    height?: number;
    offset?: number;
  };
  contentProps?: TooltipPrimitive.TooltipContentOwnProps;
}
```

**Comment by benoitgrelard** [comment]
I had no idea you could even grab them like that, that's kinda weird considering they're not exported haha.

Can you show me a fuller example of what you're doing?
That will help us understand and decide whether we should consider exposing them or having the capability to grab them somehow.

Thanks!

**Comment by mjoyce** [comment]
Actually rethinking my approach, I forgot about `extends`... this is my latest below. I basically want to seamlessly expose as many underlying primitive props as makes sense for my implemenation.

```
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import React from 'react';

export interface TooltipProps
  extends TooltipPrimitive.TooltipOwnProps,
    TooltipPrimitive.TooltipContentOwnProps {
  text: string;
  arrowOffset?: number;
}

const Tooltip = (props: TooltipProps): JSX.Element => {
  return (
    <TooltipPrimitive.Root delayDuration={props.delayDuration}>
      <TooltipPrimitive.Trigger>
        Some Trigger
      </TooltipPrimitive.Trigger>
      <TooltipPrimitive.Content
        align={props.align}
        alignOffset={props.alignOffset}
        side={props.side}
        sideOffset={props.sideOffset}
      >
        {props.text}
        <TooltipPrimitive.Arrow width={16} height={6} offset={props.arrowOffset} />
      </TooltipPrimitive.Content>
    </TooltipPrimitive.Root>
  );
};

Tooltip.defaultProps = {
  align: 'start',
  alignOffset: -8,
  arrowOffset: 8,
  delayDuration: 500,
  side: 'top',
  sideOffset: 4,
};

export default Tooltip;
```

**Comment by benoitgrelard** [comment]
@mjoyce thanks for the example! 🙏 

If what you're after is getting the "own" props for each part (not including the DOM attributes) then you should be able to use `Polymorphic.OwnProps<typeof TooltipPrimitive.Content>`, `Polymorphic.OwnProps<typeof TooltipPrimitive.Arrow>`, etc

This is the same utility we use internally ourselves. You can see on that link I posted earlier how it's used.

**Comment by mjoyce** [comment]
Thanks for the help @benoitgrelard ! Taking a deeper look at the Polymorphic stuff. Awesome lib, thanks again!
