### ISSUE TITLE
[ToggleGroup] Unpressing an item in a type="single" controlled `ToggleGroup` requires 2 clicks

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#721]
Exactly the same problem we had in #593 and treated in  #594

**Comment by andy-hook** [comment]
Just for my benefit and anyone in the future, this is the issue we're describing right?

https://user-images.githubusercontent.com/11708259/122410134-9143d180-cf7b-11eb-8d72-0cd9476e1cb0.mp4

**Comment by benoitgrelard** [comment]
Yes, but even just unselecting the same one would need 2 clicks, the other one where it selects another one is a side effect of it.
