### ISSUE TITLE
[ToggleGroup.Item] Value type too restrictive

### ISSUE THREAD

**Issue by Faithfinder** [radix-ui/primitives#726]
### Overview

Topic is self-explanatory

### Additional context

I've just started playing around with radix and tried out the toggle group. It seems to me that the `value` type of the item is too restrictive - right now it's just `string`. At the very least it should accept numbers, but from my playing around objects work as well (I guess objects would break in actual use cases cause of equality rules?). `null` should probably be accepted as well, it works fine.

I imagine this might be true for other components?

**Comment by benoitgrelard** [comment]
Hi @Faithfinder, thanks for raising an issue.

I am unsure what value we would bring by expanding the type? The only one that "could" make sense would be `number` but I honestly struggle to see any value in adding this, if anything it makes the API and docs seem more complicated.

Do you have a particular use-case in mind where you found it limiting?

**Comment by Faithfinder** [comment]
Not a specific one, no, I just spent an hour playing around and that's it, haven't tried real-world applications.

But from general experience (YMMV), entries in lists usually represent objects, which usually have ids and those ids are what I would put in the `value`. It's quite common for the id to be a number, and I wouldn't want to add conversion to and from string just to appease radix's type definitions.

```ts
const options = [
    { id: 1, name: "One" },
    { id: 2, name: "Two" },
    { id: 3, name: "Three" }
  ];

//...
{options.map((el) => (
    <ToggleGroup.Item
       key={el.id} 
       value={el.id} // Right now this gives a typerror, but works. Just let me use it!
    >
      {el.name}
    </ToggleGroup.Item>
))}
```

The typing for React's `value` prop on `option` tag (which seems like this case is closest to) is `value?: string | ReadonlyArray<string> | number;`

I could also find value in `null` for `null objects`, for example if I'm implementing a filter, for entry of "The filterable field is empty".
```ts
const noneEntry = {
  id: null,
  name: "Empty"
}
```

As for docs, I really don't know how showing that any kind of primitive works is in any way complicated.
For prior art I can point to [Material UI Select](https://material-ui.com/api/select/#props), they allow `any` in `value`.

**Comment by Faithfinder** [comment]
Well, if I have a numeric id than I still have the burden? I'd need to either put `value.id as string` into the prop, or do actual type conversions when I assign values and then use them `onChange`.

**Comment by benoitgrelard** [comment]
> Well, if I have a numeric id than I still have the burden? I'd need to either put `value.id as string` into the prop, or do actual type conversions when I assign values and then use them `onChange`.

No you'd just do `value={String(value.id)}`…

**Comment by Faithfinder** [comment]
You missed the second part.

At this point an example is large enough for a sandbox, so there:
https://codesandbox.io/s/ecstatic-pare-tj8b8?file=/src/App.tsx

Notice that there are 2 type coercions now, which aren't needed in practice - it works if you remove them, only typescript complains.

Ideally `onValueChange` should be a generic of the same type as `value` of the option, but I'm not sure how possible that is.

**Comment by benoitgrelard** [comment]
Yes, sorry I missed when you said
> …or do actual type conversions when I assign value

> Ideally onValueChange should be a generic of the same type as value of the option, but I'm not sure how possible that is.

That's the main issue though, typescript is not powerful enough to infer this.

Especially considering that in your example, you're only using `onValueChange` so there isn't even a `value` to infer from anyway (which is a completely valid use-case too obviously). Typescript can't magically infer from the `value` prop on the items.

I do understand what you're saying, but I'm not sure what's best honestly at this point. Each way is just its own set of tradeoffs.

I would say for your example here, what you have is ok.
In a JS world, like you say, things would just work without the type conversions.
In TS, if for some reason you're not happy with having to pay for the cost of the conversions at runtime (although I really can't imagine it makes any difference whatsoever) you can just as easily type cast with TS instead.

**Comment by Faithfinder** [comment]
Yeah, it's not really about performance. It's not a critical issue or anything, I'm just annoyed that the typings prohibit me from doing something that works. In my book that means that types are wrong and I don't like when things are wrong.

That's about it for useful things I could say :)

**Comment by benoitgrelard** [comment]
Haha I get you. Unfortunately Typescript is not perfect and there are many patterns that we are limiting, especially when it comes to compound components in React, we've hit our fair share of them for sure.

At this point, the only one that would bring us closer to what you want I think would be to type value as `any` I think, but then I do worry about the fact that we need to explain about referential equality because some of our users are not super experienced and might shoved objects in there etc and not know that it won't necessarily work as they expect…

**Comment by Faithfinder** [comment]
Well, referential equality is something new people will encounter sooner rather than later, probably.
Also, I wouldn't think that inexperienced users are your target audience. I'd expect that you need some experience to understand what's the benefit of radix's approach.

I guess this discussion is quite relevant right now because you're working on the `Select` component that's quite similar?

There might be an alternative by making it a generic with default? This way the majority of people can use the defaults, but "advanced" users can have all the control they could want, for the price of manually specifying the type every time.

I can't at a glance understand understand what's going on in the "official" typings to make an example out of them, but in the wild it would look like this.

```ts
interface Props<T> {
  onValueChange: (value: T) => void
}

const ToggleGroupRoot = <ValueType extends any = string>(
  props: PropsWithChildren<Props<ValueType>>
) => {
// implementation
}

// usage
<ToggleGroupRoot<number> onValueChange={/*typed*/}>
// same for each item

**Comment by benoitgrelard** [comment]
Yeah I'm aware you can make React component generics too but unfortunately with our polymorphism type requirements, AFAIK it is not possible.

**Comment by jjenzz** [comment]
Just catching up with all this.

Unfortunately generics are not possible with `React.forwardRef` and we use that heavily. We would need to override the `React.forwardRef` type to make it work and that is not something we have had time to look into.

Regardless though, the fundamental issue with what is being asked here is what @benoitgrelard raised very early on:

> but it's kinda not really relevant because `select` always gives you back a string anyway.

When working with the DOM your value usually ends up in the DOM, and so something like this would always give you back a string:

```jsx
<input 
  value={1} 
  onChange={event => {
    // will log a string
    console.log(event.value);
  }}
/>
```

if we were doing something like this under the hood, your input and output types would be inconsistent and that's when bugs arise. The fact that "it works" right now is just because of the current implementation we have chosen but that could very well change. The types we provide are the types you should follow if you wish to protect yourself from potential inconsistencies like this in future.

I'll close this for now but if there is anything else we can help with here, please do let use know 🙂
