### ISSUE TITLE
[ScrollArea] ScrollArea.Scrollbar loses types after being put through a Stitches styled call

### ISSUE THREAD

**Issue by Darko** [radix-ui/primitives#728]
### Current Behavior
When styling the Scrollbar of ScrollArea like this:
```
const StyledScrollbar = styled(ScrollArea.Scrollbar, {
...
});
```

Where styled is a stitches styled, and if `forceMount` is passed on or any of the primitive props to it, there are Typescript errors:

![image](https://user-images.githubusercontent.com/10568927/122594517-6636ac00-d067-11eb-8fee-d9ef425e8ca0.png)

### Expected behaviour

Types are preserved even after putting the component through a JSS styling function.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/jovial-payne-j2dqg?file=/src/App.tsx)

### Additional context

The bug occurs after wrapping a Radix component in a Stitches `styled` function. None of the props exposed and documented in the docs are then recognized by typescript.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    ScrollArea     |     0.0.14    |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |    92.0.4515.51     |
| Assistive tech   |         |         |
| Node             | n/a     |     15    |
| npm/yarn         |    yarn     |    1.22.5     |
| Operating System |    MacOS     |    Big Sur 11.3.1     |

**Comment by jjenzz** [comment]
I initially wondered if this might be something to do with Stitches but tried the same with styled-components and it also has errors for this particular part.

**Comment by benoitgrelard** [comment]
I wonder if it is related to the big union we're doing in types for that part?

**Comment by benoitgrelard** [comment]
@Darko this has now been released.
