### ISSUE TITLE
[Dialog] Consider adding optional `Title` and `Description` parts like in `AlertDialog`

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#729]
This stemmed from some user feedback on Discord where someone realised that labelling a dialog via `aria-label` or `aria-labelledby` was necessary (they found it in WAI-ARIA docs).

https://discord.com/channels/752614004387610674/803656530259738674/856455668754808832

I explained that some labelling is left to the user, but that we added `Title`/`Description` parts to `AlertDialog` as it was a more specific pattern. But I honestly can't see any reason against exposing those as optional parts for `Dialog` if it can simplify labelling for most people without having to faff around too much.

Let me know what you think and if we agree I can take a look.

cc  @jjenzz @andy-hook

**Comment by andy-hook** [comment]
I'd be on board with this, I understand the original decision to omit them on the generic `Dialog` but if users find them useful I think it's worth it.

I guess the only overhead would be making sure the docs correctly frame the use of one vs the other? the docs already do this but as their apis would be converging slightly perhaps it's a little more important than before? 🤷‍♂️

**Comment by benoitgrelard** [comment]
That's a great point about the fact that the would become closer than ever.
I would imagine then yes we'd need to explain even more what the differences are.
One difference I can see coming also since the work i've done in #699 is that `AlertDialog` should never be non-modal.
