### ISSUE TITLE
[Checkbox] Pass the native event as second argument of onCheckedChange

### ISSUE THREAD

**Issue by jgoux** [radix-ui/primitives#734]
Hello all,

## Feature request
`onCheckedChange` used to pass the native `event`, and is now passing a custom state for convenience (and the "indeterminate" state).

In our case we rely on react-hook-form to handle our forms lifecycle and validation, and it's using the native events by default in order to synchronise the inputs values with the form's global state : https://react-hook-form.com/api/useform/register

Not having access to the native event anymore will force us to pass a custom `onChange` functions to our checkboxes implemented with radix : 

```jsx
// Checkbox is our own implementation over Radix primitives
// setValue is also from react-hook-form
<Checkbox {...register("is_happy")} onChange={(checked) => { setValue("is_happy", checked); }} />
```

### Overview

Passing the native event as a second argument of `onCheckedChange` would be helpful for interoperability.

**Comment by andy-hook** [comment]
Hey @jgoux, thanks for your feedback here. We'll look into it and get back to you 🙏

**Comment by benoitgrelard** [comment]
@jgoux one question regarding this, how was it working for you before because although our previous implementation was backed by the native event, it wasn't called `onChange` but still `onCheckedChange`.

**Comment by jgoux** [comment]
@benoitgrelard `Checkbox` here is our own abstraction built on radix primitive so we expose a`onChange` prop and pass it to `Checkbox.Root` `onCheckedChange` callback.

**Comment by gpeto91** [comment]
Hey guys, sorry to revive this but do we have any news on this? I'm having similar problem but with a Select component built on top of SelectPrimitive and I can't get it to work with react hook form at all. OnValueChange expect a string and react-hook-form has onChange with native event and I couldn't find a way to react hook form gets the selected value.

**Comment by jjenzz** [comment]
@gpeto91 check out their [Controller](https://react-hook-form.com/api/usecontroller/controller/) component.

Here's a working example https://codesandbox.io/s/weathered-worker-huynj?file=/src/App.js

**Comment by gpeto91** [comment]
Hi @jjenzz! Thanks for this example :) unfortunately I still can't get it to work with React Hook Form even with the Controller.

I made [this example](https://codesandbox.io/s/hardcore-breeze-4mme07?file=/src/App.js) to show you what I'm trying to accomplish. I'm using the Custom API from Radix to build the Select component. In this example the value is always undefined when submitted. 

Not sure what I'm missing, tried several aproaches :( can you tell me what I'm doing wrong pls?

I'm trying to build a component lib for my company, so I want the components to be as independent and flexible as possible from any tool. Like using react-hook-form or formik for example.

Thanks once again!

**Comment by lukvermeulen** [comment]
Hi @gpeto91,  currently I connect my select like the following, and the checkbox in a similar fashion.

Next to the other react-hook-form things, I use the [setValue](https://react-hook-form.com/api/useform/setvalue) function.
```javascript
const {
        register,
        handleSubmit,
        formState: { errors },
        setValue,
        reset,
    } = useForm<ITileFormOne>({ defaultValues });
```
That, I call in the onValueChange option.
```javascript
<Fieldset>
    <Label htmlFor="category">Kategorie</Label>
    <Select
        {...(register("category"),
        {
            onValueChange: (value) => {
                setValue("category", value);
            },
            defaultValue: "none",
        })}
    >
        <SelectGroup>
            <SelectLabel>Kategorie</SelectLabel>
            <SelectItem value="none">None</SelectItem>
        </SelectGroup>
    </Select>
</Fieldset>
```
It works for me, but doesn't feel like the most elegant aproach and it is quite a pity, that one has to connect simple UI components with that much logic, compared to the standard html inputs. 
Maybe someone else from the community or radix team has a slightly more elegant solution :)

**Comment by gpeto91** [comment]
@lukvermeulen wow! that's exactly what I was looking for... if it's the most elegant way or not I can't tell but I'm glad to see it working after a couple of days on it hahaha You're the best, thanks!

Also, here is a sandbox with a working example following your implementation: https://codesandbox.io/s/dry-night-hfo954?file=/src/App.js

I wrote the onValueChange slightly different, you may wanna check. Well, I can move on with my life now hahahaha Thanks guys!

**Comment by benoitgrelard** [comment]
Closing this issue as a solution has been provided for the checkbox: https://github.com/radix-ui/primitives/issues/734#issuecomment-1072972191

@gpeto91, @lukvermeulen if you are still having issues with `Select` please re-open another issue regarding `Select` specifically and provide your use case/sandbox.

**Comment by ThomasAlbrt** [comment]
> Hi @gpeto91, currently I connect my select like the following, and the checkbox in a similar fashion.
> 
> Next to the other react-hook-form things, I use the [setValue](https://react-hook-form.com/api/useform/setvalue) function.
> 
> ```js
> const {
>         register,
>         handleSubmit,
>         formState: { errors },
>         setValue,
>         reset,
>     } = useForm<ITileFormOne>({ defaultValues });
> ```
> 
> That, I call in the onValueChange option.
> 
> ```js
> <Fieldset>
>     <Label htmlFor="category">Kategorie</Label>
>     <Select
>         {...(register("category"),
>         {
>             onValueChange: (value) => {
>                 setValue("category", value);
>             },
>             defaultValue: "none",
>         })}
>     >
>         <SelectGroup>
>             <SelectLabel>Kategorie</SelectLabel>
>             <SelectItem value="none">None</SelectItem>
>         </SelectGroup>
>     </Select>
> </Fieldset>
> ```
> 
> It works for me, but doesn't feel like the most elegant aproach and it is quite a pity, that one has to connect simple UI components with that much logic, compared to the standard html inputs. Maybe someone else from the community or radix team has a slightly more elegant solution :)



@lukvermeulen I can't thank you enough for this. 
I was getting mad seeing `undefined` values using the `register` function without `setValue`.
