### ISSUE TITLE
[Popover] content positioned incorrectly on Safari when combined with Framer Motion scale

### ISSUE THREAD

**Issue by samuelkraft** [radix-ui/primitives#740]
## Bug report
When using the Popover component with it's Popover.Content set to `align="end"` and animating its scale with Framer Motion it's positioned incorrectly on the x-axis on Safari. 

### Current Behavior
The popover content is offset to the right.

<img width="281" alt="Screenshot 2021-06-22 at 20 47 58" src="https://user-images.githubusercontent.com/2223418/122982420-22131680-d39b-11eb-8a90-e14574a077d7.png">

### Expected behavior
The popover content should be aligned to the trigger. This works in Chrome/FF.

### Reproducible example

https://codesandbox.io/s/radix-framer-bug-myc5h

### Additional context

Very specific bug for my use-case ( opening a right-aligned popover and animating it's scale with framer motion), and not sure if fixable but it works as expected in Chrome/FF

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-popover     |    0.0.18     |
| React            | n/a     |    17.0.2     |
| Browser          |    Safari     |     14.1    |
| Assistive tech   |         |         |
| Node             | n/a     |    16.0.0     |
| npm/yarn         |    yarn     |     1.22.10    |
| Operating System |    MacOS     |    11.3.1     |

**Comment by apollonian** [comment]
I just ran into the same issue with scale using Stitches in Safari. https://codesandbox.io/s/radix-popover-animation-2w1p0?file=/src/App.js 

<img width="211" alt="Screenshot 2021-07-26 at 7 51 02 PM" src="https://user-images.githubusercontent.com/2150306/127004679-83051aad-7d2e-4627-b380-cb8fe5b303ec.png">

**Comment by benoitgrelard** [comment]
@apollonian I don't think this is the same issue, yours looks like it's just the arrow that is off-center. Would you mind opening a separate issue for that one?

**Comment by apollonian** [comment]
@benoitgrelard Opened an issue here! https://github.com/radix-ui/primitives/issues/800

**Comment by benoitgrelard** [comment]
Just a note that I cannot reproduce it in Safari 15.4

**Comment by samuelkraft** [comment]
> Just a note that I cannot reproduce it in Safari 15.4

Great news, same here!
