### ISSUE TITLE
[DropdownMenu] Item as anchor does not navigate to the expected destination

### ISSUE THREAD

**Issue by AlvinLing** [radix-ui/primitives#745]
### Current Behavior

When a DropdownMenu.Item is rendered as an anchor, clicking the item closes the menu.

`<DropdownMenu.Item as="a" href="/foo">Click Me</DropdownMenu.Item>`

### Expected behavior

When a DropdownMenu.Item is rendered as an anchor, the user should be navigated to the provided href value.

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/loving-star-29eqk?file=/pages/index.js)

### Suggested solution

Adding `onSelect={ (e) => { e.preventDefault() } }` fixes the issue but it would be nice if that was not required.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dropdown-menu     |   0.0.22      |
| React            | n/a     |    17.0.2     |
| Browser          |   Chrome      |     91.0.4472.106 (Official Build) (x86_64)    |
| Node             | n/a     |    14.15.4     |
| npm/yarn         |   npm      |   7.6.1      |
| Operating System |   MacOS      |    11.4     |

**Comment by jjenzz** [comment]
This was fixed by #818 and will be in the next release.
