### ISSUE TITLE
[Radio] Radio package prevents consumer applications from compiling without disabling ts checks of libraries

### ISSUE THREAD

**Issue by hsbacot** [radix-ui/primitives#746]
## Bug report
`index.d.ts` has an error linking to `"Radio"` that prevents consumer applications from compiling rith `tsc` unless all library checks are disabled with `skipLibCheck` in the `tsconfig` file.

```
npx tsc --noEmit
node_modules/@radix-ui/react-radio-group/dist/index.d.ts:30:96 - error TS2307: Cannot find module 'Radio' or its corresponding type declarations.

30 export const RadioGroupIndicator: import("@radix-ui/react-primitive").ExtendedPrimitive<import("Radio").RadioIndicatorPrimitive, "span">;

node_modules/@radix-ui/react-radio-group/dist/index.d.ts:33:91 - error TS2694: Namespace '"/Users/hsbacot/dev/portal/node_modules/@radix-ui/react-radio-group/dist/index"' has no exported member 'RadioIndicatorPrimitive'.

33 export const Indicator: import("@radix-ui/react-primitive").ExtendedPrimitive<import(".").RadioIndicatorPrimitive, "span">;
```

### Current Behavior

<img width="1389" alt="Screen Shot 2021-06-24 at 1 36 29 PM" src="https://user-images.githubusercontent.com/1270494/123329720-fa829200-d4f1-11eb-967d-0bc3b6bce031.png">

### Expected behavior

`tsc` compiles projects using `@radix-ui/react-radio-group` successfully

### Reproducible example
Not sure how to reproduce `tsc` in codesandbox

### Suggested solution
[This line](https://github.com/radix-ui/primitives/blob/main/packages/react/radio-group/src/RadioGroup.tsx#L139) produces
```.jsx
const RadioGroupIndicator = extendPrimitive(RadioIndicator, { displayName: 'RadioGroupIndicator' });
```
the following in `index.d.ts`
```.jsx
export const RadioGroupIndicator: import("@radix-ui/react-primitive").ExtendedPrimitive<import("Radio").RadioIndicatorPrimitive, "span">;
```
where "Radio" is not able to be found. I'd suggest looking into how the import for radio is inferred in the TS definition file

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-radio-group       |     0.0.17    |
| React            | n/a     |         |
| Browser          | n/a        |         |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |         |
| npm/yarn         |      14.16.1   |         |
| Operating System |    macOS catalina     |   10.15.7      |

**Comment by jjenzz** [comment]
@hsbacot Are you able to reproduce this in the latest versions of the primitives? We have since removed the `extendPrimitive` utility and improved types.

**Comment by hsbacot** [comment]
I'll update and test this in the morning! TY @jjenzz

**Comment by hsbacot** [comment]
This is now fixed when compiled 😄 Thank you @jjenzz & team

**Comment by jjenzz** [comment]
whoop 🙌
