### ISSUE TITLE
[ContextMenu] Menu not focusable when using a pen

### ISSUE THREAD

**Issue by dabbott** [radix-ui/primitives#747]
### Current Behavior

With `@radix-ui/react-context-menu@0.0.20` and later, context menus aren't focusable when using a pen (they focus correctly with mouse and trackpad). By "not focusable", I mean I can still click to activate a menu item, but hovering the pen doesn't highlight the item (no `:focus` state) and I can't use arrow keys to navigate. This issue affects Chrome/FF/Edge, but not Safari 🤔. Edit: Occasionally, it does focus correctly... but I haven't figured out why.

| Expected behavior (`0.0.19`) | Current behavior (`0.0.20+`) |
| --- | --- |
| ![Screen Shot 2021-06-26 at 9 43 13 AM](https://user-images.githubusercontent.com/1198882/123520068-b6af9a00-d663-11eb-9fb9-6e3e1eca27c6.png) | ![Screen Shot 2021-06-26 at 9 42 02 AM](https://user-images.githubusercontent.com/1198882/123520076-c929d380-d663-11eb-8032-b8639e93a0bd.png) |

### Reproducible example

https://codesandbox.io/s/radix-context-menu-focus-snpem?file=/src/ContextMenu.tsx

This problem is also visible on the radix primitives docs: https://www.radix-ui.com/primitives/docs/components/context-menu

### Suggested solution

I didn't dig into this, but if I had to guess, maybe there's some code targeting iOS or Safari specifically that should also trigger for pointers more generally.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | @radix/react-context-menu | 0.0.23 |
| React            | n/a     | 17.0.2 |
| Browser          | Chrome | 91.0.4472.114 |
| Assistive tech   | Wacom Tablet | Intuos Pro M |
| Node             | n/a     |         |
| npm/yarn         | n/a | |
| Operating System | macOS | 11.1 |

**Comment by benoitgrelard** [comment]
We have some improvements coming regarding touch/pen support, specifically around this.

**Comment by dabbott** [comment]
Awesome! Looking forward to it.

**Comment by benoitgrelard** [comment]
Closing this as, tracked in #657
