### ISSUE TITLE
[ContextMenu] Opt-in/out of new long-press-to-open behavior

### ISSUE THREAD

**Issue by dabbott** [radix-ui/primitives#748]
### Overview

I'd like to upgrade my `@radix-ui/react-context-menu`, but I noticed that there's a new behavior in the latest version (`0.0.23`), where a long press will open the context menu. This breaks my use case, where the element that supports a context menu also supports other pointer interactions, e.g. left-click-and-drag. For this reason, I'd like the long-press-to-open behavior to be opt-in or opt-out via a prop, or a mobile-only feature.

### Who does this impact? Who is this for?

I think this impacts anybody using a pen. I noticed that this only happens with a pen, but not a trackpad or mouse. I didn't test on mobile, so I'm not sure what happens there... but I'm assuming this behavior mainly exists for mobile.

### Additional context

I think it's incredibly awesome that radix-ui has great pen support generally. I use a pen almost all the time, and it's rare that apps actually work perfectly - usually they're slightly frustrating in obscure ways. I hope more apps start using radix-ui 🙌

FWIW, this long press behavior feels somewhat nonstandard to me. My pen has a dedicated button which I can use to right click, so that's how I normally open context menus. I think most tablets/operating systems support a system-wide long-press-to-right-click setting for people who want that. For that reason, I'd suggest long-press-to-open be opt-in or mobile-only, since otherwise it'll conflict with the user's tablet/system settings

**Comment by benoitgrelard** [comment]
Hey @dabbott, thanks for opening this issue!
This is really interesting actually, we introduced this mostly because of touch input. I didn't know some pens have a button to bring up context menus. In terms of opting out, you can always prevent our handlers by doing `event.preventDefault` so here you could prevent only for pen by doing:

```
<ContextMenu.Trigger onPointerDown={event => {
  if (event.pointerType === 'pen') event.preventDefault();
}} />
```

Would be good to understand more about pen support though, for example I'm not sure if Apple Pencil/iOS would support what you're talking about?

**Comment by dabbott** [comment]
Excellent! Overriding `onPointerDown` works for me, thanks for the quick response.

I use a [Wacom Intuos Pro](https://www.wacom.com/en-us/products/pen-tablets/wacom-intuos-pro), and there's a lot of customizability:

![Screen Shot 2021-06-28 at 2 16 38 PM](https://user-images.githubusercontent.com/1198882/123705182-76931780-d81b-11eb-932c-84eaca339db5.png)

I haven't used Windows in years, but I know Windows also [has something for this](https://www.top-password.com/blog/turn-on-off-press-and-hold-for-right-clicking-in-windows-10/) in their pen settings:

![image](https://user-images.githubusercontent.com/1198882/123705505-e6a19d80-d81b-11eb-8122-ac54864d3330.png)

I don't use an Apple Pencil regularly and I don't have one handy today, but I can check it out tomorrow.
