### ISSUE TITLE
[Popover] Re-opens on trigger click

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#763]
After some investigation into https://github.com/radix-ui/primitives/issues/631 I realised this cannot be fixed as easily as `DropdownMenu` so I've split these issues for individual investigation.

**Comment by mwx27** [comment]
Trigger still re-openes popover in Safari. The same code works fine in Chrome or Firefox.

**Comment by benoitgrelard** [comment]
> Trigger still re-opens popover in Safari. The same code works fine in Chrome or Firefox.

I don't see the issue here: https://www.radix-ui.com/docs/primitives/components/popover
