### ISSUE TITLE
How to test a component with a Popover inside

### ISSUE THREAD

**Issue by MaximeConan** [radix-ui/primitives#765]
Hi everyone,

I'm actually trying to add unit tests on a component which contains de `Popover` inside and if I simulate a click on the `Trigger`, I have the following error : `DOMRect is not defined`

The test implementation is really basic, I use `jest` and `react-testing-library` and I simulate my click like this : 

```js
 const trigger = getByTestId('__protected-input-trigger__')
 fireEvent.click(trigger)
```

The trigger : 

```js
<PopoverTrigger
  data-testid="__protected-input-trigger__"
  as={Button}
  tabIndex={0}
  state="tertiary"
  size="small"
>
    <Pencil1Icon />
</PopoverTrigger>
```

Has someone the same behaviour ?

Thanks by advance !

**Comment by benoitgrelard** [comment]
Hi @MaximeConan,

It sounds like you'd need to mock that class as it's not a real DOM environment.
Have a look at this comment here: https://github.com/radix-ui/primitives/issues/420#issuecomment-771615182

I'll close your issue for now, but feel free to keep discussing or reopen it if this doesn't fix your issues.

**Comment by MaximeConan** [comment]
You are awesome, thank you ! 🎉
