### ISSUE TITLE
[Dialog][AlertDialog] Encapsulation issue when nesting them

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#769]
### Current Behavior

When nesting `AlertDialog` and `Dialog` they control each other.

### Expected behavior

They should only control their own respective content.

### Reproducible example

https://codesandbox.io/s/tender-smoke-4rz00?file=/src/App.js

### Suggested solution

Isolate different contexts should do the trick.

### Additional context

This is similar to #681, same exact problem I think.

**Comment by jjenzz** [comment]
Closing as duplicate of https://github.com/radix-ui/primitives/issues/681

**Comment by benoitgrelard** [comment]
Oh yeah good point, that's another problematic combination.
