### ISSUE TITLE
React-Radio-Group Item click event firing twice/click firing after navigating away

### ISSUE THREAD

**Issue by anchung333** [radix-ui/primitives#770]
### Current Behavior

I am currently using the ```Item``` primitive from ```react-radio-group``` to behave as a checkbox. After clicking on an ```Item```, then navigating away and coming back, the ```onClick``` event fires again:

https://user-images.githubusercontent.com/57578761/124640316-7a8ded80-de4a-11eb-8b35-0580b6e546b0.mov

I noticed there seems to be an ```onClick``` handler on two elements within ```Item```:  

![Screen Shot 2021-07-06 at 11 10 07 AM](https://user-images.githubusercontent.com/57578761/124640513-c0e34c80-de4a-11eb-8122-7755c86a6870.png)

### Expected behavior

I expect when I assign an ```onClick``` handler to an ```Item``` for it not to fire twice and/or fire again upon mounting/after navigating away from the page and navigating back. 

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Suggested solution

If I use a ```onMouseDown``` event handler instead of an ```onClick``` handler, the problem goes away. Wondering if perhaps not passing down the onClick handler to both the button and its children is the answer here. We would ideally want to use ```onClick``` instead of ```onMouseDown``` for uniformity across our app and ease of testing. If this is some simple HTML/React problem I have overlooked, apologies in advance. 

### Additional context

N/A

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   react-radio-group     |    ^0.0.14     |
| React            | n/a     |    17.0.1    |
| Browser          |     Chrome    |     91.0.4472.114    |
| Assistive tech   |         |         |
| Node             | n/a     |    n/a     |
| npm/yarn         |         |         |
| Operating System |    macOS     |    Big Sur     |

**Comment by benoitgrelard** [comment]
Hi @anchung333,

> I am currently using the Item primitive from react-radio-group to behave as a checkbox.

Can I ask why you're not just using the `Checkbox` primitive if that's what you're after?

**Comment by jjenzz** [comment]
@anchung333 I agree with Benoit that it looks like `Checkbox` is what you need but have you tried upgrading to the latest version? We made some changes recently which may have fixed this in [`Checkbox`](https://github.com/radix-ui/primitives/pull/672) and [`RadioGroup`](https://github.com/radix-ui/primitives/pull/685).

**Comment by anchung333** [comment]
@benoitgrelard @jjenzz Yes I ended up using the ```Checkbox``` primitive, as there was a miscommunication on the packages we should have employed for this feature. Thanks for all of your help and assistance; I will close this issue for now.
