### ISSUE TITLE
[Slider] Not working in Next.js when reactStrictMode is enabled

### ISSUE THREAD

**Issue by domosedov** [radix-ui/primitives#773]
## Bug report

Hello,
I copy [basic example](https://www.radix-ui.com/docs/primitives/components/slider#basic-example) with stitches from official docs.
I use it in Next.js app with enabled [react strict mode](https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode) in next.config.js

### Current Behavior

Server warning `Did not expect server HTML to contain a <span> in <span>`...
Can't change value with thumb.

### Expected behavior

When `reactStrictMode: false` it work as expected.

### Reproducible example

[StackBlitz](https://stackblitz.com/edit/nextjs-fcxaig)

**Comment by benoitgrelard** [comment]
Hi @domosedov,

That StackBlitz example you linked to seems to work for me.
Am I missing something?

**Comment by domosedov** [comment]
> Hi @domosedov,
> 
> That StackBlitz example you linked to seems to work for me.
> Am I missing something?

Hello, try with `reactStrictMode: true` in `next.config.js`

**Comment by benoitgrelard** [comment]
Ha thanks, I assumed it was already the case as you linked as a reproducible example.
I can see the issue now seems to be a focus issue, as the focus gets lost. 🙏
