### ISSUE TITLE
[Tooltip] JSX Content

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#780]
### Overview

I'd like to add a keyboard shortcut to my Tooltips. At the moment the Tooltip component can only accept text content (via the `label`) prop. This would likely mean putting some markup as the tooltip's content, rather than just the label.

### Who does this impact? Who is this for?

Intermediate. Many apps with tooltips also include keyboard shortcuts; and these are styled differently than the accompanying text.

A few examples from Linear.app:

![image](https://user-images.githubusercontent.com/23072548/125618212-c37d8abb-8832-4978-96de-e1accaec06aa.png)

![image](https://user-images.githubusercontent.com/23072548/125618249-ae03eff3-e189-42c2-b149-d75872cf0e82.png)

**Comment by benoitgrelard** [comment]
The tooltip content accepts anything. You obviously have to make sure the stuff inside is minimal and accessible though.

Here's an example from our stories:

![image](https://user-images.githubusercontent.com/1539897/125622302-9d11ee08-fd26-418f-a2d1-c5b491d35b1b.png)

```
<Tooltip>
      <TooltipTrigger>Mini layout</TooltipTrigger>
      <TooltipContent className={contentClass} sideOffset={5}>
        <p
          style={{
            margin: 0,
            textAlign: 'center',
            fontFamily: 'apple-system, BlinkMacSystemFont, helvetica, arial, sans-serif',
            fontSize: 14,
          }}
        >
          Start video call
          <span style={{ display: 'block', color: '#999' }}>
            press{' '}
            <kbd
              style={{
                fontFamily: 'apple-system, BlinkMacSystemFont, helvetica, arial, sans-serif',
                fontWeight: 'bold',
                color: 'white',
              }}
              aria-label="c key"
            >
              c
            </kbd>
          </span>
        </p>
        <TooltipArrow className={arrowClass} offset={10} />
      </TooltipContent>
    </Tooltip>
```

**Comment by steveruizok** [comment]
Oops, looks like I've been confused by my own Tooltip component (that wraps yours). Excellent work as always, happy to close this.

**Comment by benoitgrelard** [comment]
Right back at you @steveruizok!
