### ISSUE TITLE
[Popper] Issue when trigger is position fixed?

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/primitives#781]
### Current Behavior

![CleanShot 2021-07-13 at 15 22 59](https://user-images.githubusercontent.com/1539897/125749552-ec79b497-63d6-44f6-97d9-c20aeb31daa1.gif)

**Comment by makezi** [comment]
I have experienced the same issue when a `Popover` is placed in a fixed header. I have a [codesandbox repro here](https://codesandbox.io/s/sleepy-meninsky-2mie6?file=/App.js) which uses the codesandbox taken from the [Popover demo](https://www.radix-ui.com/docs/primitives/components/popover) from the docs as the base.

![2021-08-30 14 23 50](https://user-images.githubusercontent.com/3255371/131284993-d8553652-c644-4809-b11c-894148ec6322.gif)

**Comment by andy-hook** [comment]
There is a related issue when using non portalled content with a fixed or sticky trigger, I think the relative positions are not being calculated correctly.


https://user-images.githubusercontent.com/11708259/131830155-08fcb47d-7c59-4b0b-a1cc-4aa06670ffd3.mp4

**Comment by omgovich** [comment]
Having the same problem with my application since it has a floating button/trigger. Is there any solution for that?
![image](https://user-images.githubusercontent.com/206567/132521503-2c01357e-00b5-41c5-85ef-f9ca70281a9c.png)

**Comment by andy-hook** [comment]
> Having the same problem with my application since it has a floating button/trigger. Is there any solution for that?

One workaround could be to render the `content` inline by setting `portalled={false}` and forcing an override of the popper positioning styles:

https://codesandbox.io/s/sharp-shadow-o714d?file=/src/App.js

It's hacky though.. but would that work in the short term?

**Comment by omgovich** [comment]
Feels like we should use not `popover`, but `dialog` for our tasks. It doesn't have a positioning that we will have to override.

**Comment by benoitgrelard** [comment]
Yeah that's a good option too as it's mostly statically positioned in your case.

**Comment by CristoNavarro** [comment]
We were having the same issue. In our case, we have a Dialog that uses a Portal and inside it we render the Popover. We could solve it following the advice of @andy-hook, but we needed it with a fixed position so we added the following to the styles of the Popover's wrapper:

```javascript
'[data-radix-popper-content-wrapper]': {
   translate3d: 'none !important',
   position: 'fixed !important',
},
```

**Comment by tesseralis** [comment]
Hi, I've been running into this issue as well. The Popper.js docs mention using `strategy: fixed` in `createPopper` in order to do this. Would it be possible to expose this option somehow?

**Comment by benoitgrelard** [comment]
We don’t use popperjs as a dependency.

**Comment by colepeters** [comment]
I'm also experiencing this, though unfortunately none of the presented fixes are working for me. My situation is functionally similar to [@makezi's repro](https://github.com/radix-ui/primitives/issues/781#issuecomment-908011395), with the added complication that I'm rendering my non-portalled Popover within a portalled Dialog.

So, when initially loading the page and then my opening my Dialog, the popover appears in the correct position — but if I close the Dialog, scroll the document body, reopen the Dialog, and then trigger the Popover again, it will now be out of position. This sounds very similar to @CristoNavarro's setup as well, but his fix doesn't work for me — when applying that fix, the popover always renders in the top left of the viewport.

**Comment by ryparker** [comment]
Just ran into this using `position: sticky;` and the following does fix the popover from sliding away when scrolled:

```css
[data-radix-popper-content-wrapper] {
    position: relative !important;
    transform: none !important;
  }
```

However this does break collision detection. Any idea on when this will be fixed or an explanation as to why this is broken? I might be able to contribute a fix if I get a good idea as to why this is occurring.

**Comment by aquibbaig** [comment]
Hey guys, any fix on this yet? I have a custom nav which has `position: sticky, top: 100px` with a popover but it scrolls away when I scroll outside of the popover

**Comment by andy-hook** [comment]
@aquibbaig Not yet, if your popover doesn't need collision detection then perhaps try the [workaround](https://github.com/radix-ui/primitives/issues/781#issuecomment-915976878) posted previously until we can get to this.

**Comment by aquibbaig** [comment]
thanks for the suggestion @andy-hook, but it doesn't help my use case it seems, posting an example here:

https://user-images.githubusercontent.com/26324376/161518191-0b180aaa-626f-4805-95dd-8d309fcf1abd.mov

**Comment by ryparker** [comment]
Here's another demo. This is currently live on [congress.wiki](https://congress.wiki). If it's helpful I can put together a codesandbox demo.

https://user-images.githubusercontent.com/17558268/166624499-ce81ef78-1853-4fa3-92f5-0d6425fcaff8.mp4

**Comment by sicarius97** [comment]
@benoitgrelard @ryparker So I was having this same issue with a navbar that had dropdowns where the navbar was `position: sticky` . The above workarounds didn't quite do it for me, so here is what I ended up coming up with:

Created a useEffect hook that updates position state when the open state changes: 
![image](https://user-images.githubusercontent.com/73046273/174346314-915db0de-3fac-49d9-9c5f-488c63747850.png)

Then in my actual dropdown components, I use it like this: 
![image](https://user-images.githubusercontent.com/73046273/174346729-af5476cd-2d22-48e0-8def-9e3db36bb9af.png)

It only updates the position state when the dropdown opens, so there aren't any unnecessary rerenders when the user scrolls the page and it isn't open
