### ISSUE TITLE
[Dialog] Autofocused inputs inside Dialog.Content break focus control

### ISSUE THREAD

**Issue by LexSwed** [radix-ui/primitives#786]
### Current Behavior

When there's an element with `autoFocus` attribute, it doesn't get the focus when the dialog content is shown. When the dialog is closed, focus is not returned to the trigger element.

### Expected behavior

The element with `autoFocus={true}` should have focus on dialog open and then the focus is returned to the trigger when the dialog is closed.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/old-butterfly-npznd?file=/src/App.tsx)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-dialog     |   0.0.19 (latest)      |
| React            | n/a     |   17.0.1      |
| Browser          |   Microsoft Edge      |    92.0     |
| npm/yarn         |   yarn      |    1     |
| Operating System |    MacOS     |   Big Sur      |

**Comment by andy-hook** [comment]
Hey @LexSwed, we have a fix for this coming in the next release https://github.com/radix-ui/primitives/pull/739.

**Comment by andy-hook** [comment]
@LexSwed this has now [been released](https://www.radix-ui.com/docs/primitives/overview/releases#04082021)

**Comment by LexSwed** [comment]
@andy-hook, you are stars! ❤️
