### ISSUE TITLE
[Dialog] Inputs are not focused when first opening a dialog on iOS Safari

### ISSUE THREAD

**Issue by sandgraham** [radix-ui/primitives#790]
### Current Behavior

I've only seen this on iOS Safari, but the first time opening a dialog, if the first focusable element is a text input it will not receive focus. Closing and opening the dialog again will correctly focus the text input.

### Expected behavior

Ideally focus would transfer to text inputs (if they are the first focusable element) when first opening a dialog.

### Reproducible example

The default dialog example exhibits this behavior on iOS Safari: https://codesandbox.io/s/9x16d?module=App.js

1. Open the dialog, notice the input isn't focused- the iOS keyboard does not pull up
2. Close the dialog
3. Reopen the dialog, notice the input is correctly focused

### Suggested solution

This is probably some unfortunate oddness with Safari so it may or may not be worth solving within the library. I wish I could at least find a decent workaround.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    `react-dialog`     |    `0.0.18`     |
| React            | n/a     |    `17.0.2`     |
| Browser          |    iOS Safari     |    `14.6`     |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by sandgraham** [comment]
Actually it looks like focus is on the input but the iOS keyboard does not appear. From some googling it appears that you can't programmatically focus an input on iOS unless it is part of a user initiated event. Curious why this works on subsequent openings of the dialog though...

**Comment by sandgraham** [comment]
A little more research/working on this and I have a workaround where I use an `onClick` handler on the `Dialog.Trigger` to create a temporary hidden input, focus that to bring up the keyboard, and then remove it once focus has transferred to my actual input (via normal Dialog autofocus). I'm not sure if this is something that can (or should) be incorporated into the library.

**Comment by andy-hook** [comment]
Thanks for following up with your research. It seems like there's some type of internal criteria for when iOS provides this behaviour? I haven't done a ton of my own research recently but I'm pretty sure it's changed a couple of times between iOS releases.

Given that this does work on subsequent reopens I would expect this to at least be consistent.

**Comment by jjenzz** [comment]
I wasn't able to replicate this on `main` and stepping back through the commits, I was able to find [the PR](https://github.com/radix-ui/primitives/pull/776) that fixed it.

Seems it was breaking due to `Presence` 🤷 

Closing as it should be solved in our next release.

**Comment by sandgraham** [comment]
Awesome - look forward to the next release. Thank you 🎉

**Comment by andy-hook** [comment]
Hey @sandgraham this was shipped in the [latest release](https://www.radix-ui.com/docs/primitives/overview/releases#04082021). Let us know if you have any issues.

**Comment by sandgraham** [comment]
Just updated and can confirm the issue has been solved. Thank you!
