### ISSUE TITLE
Consider developing against `StrictMode` in StoryBook

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/primitives#793]
We should consider developing against `StrictMode` in our storybook environment to better prepare us for future React changes and better align with common consumer configurations.

**Comment by jjenzz** [comment]
I can't think of a reason why we shouldn't :+1:

**Comment by jjenzz** [comment]
I've wrapped `React.StrictMode` around a `Slider` story to prove a bunch of bugs were fixed. When this ticket is picked up, we can remove it from the story.

**Comment by benoitgrelard** [comment]
Love this idea @andy-hook ♥️
