### ISSUE TITLE
Make Tabs swipable

### ISSUE THREAD

**Issue by andredaniel** [radix-ui/primitives#797]
### Overview

Mobile device users are used to using drag gestures to switch between tabs. When these tabs are at the top of the screen, moving your finger over them is more difficult than just swiping anywhere on the screen.

### Examples in other libraries

(Use your phone or enable your dev tools to test the swipe feature)
[https://react-swipeable-views.com/demos/demos/#tabs](https://react-swipeable-views.com/demos/demos/#tabs)

**Comment by benoitgrelard** [comment]
Hey @andredaniel thanks for opening this.

This looks more like a carousel, which is a different component all-together accessibility-wise. We have started development on a `Carousel` primitive but it's been paused at the moment to make way for other primitives that are higher priority.

**Comment by jjenzz** [comment]
I'm not sure whether the `Carousel` pattern would be correct here or not, especially given `Carousel`s can be implemented as scrolling divs with hidden scrollbars.

I think it's worth considering if we think this might be a common use-case.

In the meantime, all of our components are completely open to allow people to implement things like this if they control it: https://codesandbox.io/s/wild-resonance-rxbu7?file=/src/App.js. That's really rough code (doesn't cover all cases and has issues in Safari) but just showing how it's possible to piece parts of the API together to achieve what you need.
