### ISSUE TITLE
Dismissible Layer: Tapping outside triggers buttons and links

### ISSUE THREAD

**Issue by jkempff** [radix-ui/primitives#809]
## Bug report

When I close a Dialog or an Alert Dialog by tapping outside of it, a click is triggered on buttons or links that were behind the overlay.

### Current Behavior

The dialog closes, and the link behind the overlay is opened.

https://user-images.githubusercontent.com/927556/127837008-45a21bcd-0081-41f5-a2f3-ff48e096c05b.mov

### Expected behavior

The dialog closes and the link is not opened.

### Reproducible example

Both, Dialog and Alert Dialog behave like this.
https://www.radix-ui.com/docs/primitives/components/dialog

### Suggested solution

I have only briefly looked into the dismissible layer implementation and I'm not an expert on pointer events, but I have a feeling this might get hacky..

Somehow we should prevent the default on one following `pointerup` event, after `onDismiss`. Maybe by adding a pointerup event handler on the body or app root? Or introduce a hidden layer that prevents pointerup events outside the dialog? …doesn't sound very elegant to me.
You folks probably have an idea for a more clean solution?

### Your environment

I tested this on an iPhone with iOS 14 and on a Mac with Chrome 92.0.4515.107 (touch events emulated).

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |@radix-ui/dialog, @radix-ui/alert-dialog|0.0.19|
| React            | n/a     |16,17|
| Browser          |Chrome|92.0.4515.107|
| Assistive tech   |n/a|         |
| Node             | n/a     |         |
| npm/yarn         |npm|7.5.3|
| Operating System |iOS,macOS|14,11.4|

**Comment by andy-hook** [comment]
Hey @jkempff, thanks for reporting. This was fixed in https://github.com/radix-ui/primitives/pull/767 and will be available in our next release.

**Comment by jkempff** [comment]
Awesome, thanks! Sorry I missed the issue being already fixed. Going to study how the solution is implemented 😊

**Comment by andy-hook** [comment]
Hey @jkempff the [latest release](https://www.radix-ui.com/docs/primitives/overview/releases#04082021) should resolve this for you. Let us know if you have any issues.

**Comment by jkempff** [comment]
Hey there, thanks for coming back to this. I can confirm, the issue has been resolved with v0.0.20. Good job to everyone involved! 😊
