### ISSUE TITLE
Mount / Unmount of blurred tabs

### ISSUE THREAD

**Issue by andrevenancio** [radix-ui/primitives#813]
Feature request 
--------

I've been using tabs to load 2 different components. Both the components have a keyboard event listener. The tab that is blurred is still detecting the keyboard events even though the tab is not focused. I wonder if the tabs should unmount or should have a `focus` property. There are pro's and con's for both but I personal prefer the unmount version.

**Comment by jjenzz** [comment]
I believe we should be able to unmount okay but it is unusual that we do this everywhere else and not for tabs. I'm concerned there may have been good reason for the decision so will need to check with the rest of the team and get back to you (some of the team is on holiday atm).

**Comment by jjenzz** [comment]
This has been added to [0.1.1-rc.6](https://www.npmjs.com/package/@radix-ui/react-tabs/v/0.1.1-rc.6)
