### ISSUE TITLE
How do I unit test a Slider component?

### ISSUE THREAD

**Issue by ksandin** [radix-ui/primitives#815]
## Question

I'd like to know the recommended way to unit test a slider component, given these scenarios:

- Observing a sliders current value
- Changing a sliders current value

> Take into consideration that multiple thumbs may or may not be used.

## Example test
Here's a few test examples that currently fail, using `@radix-ui/react-slider 0.0.17` and `@testing-library/react 12.0.0`. They are fairly idiomatic, based on how regular html `<input type="range"/>` elements can be tested (see this [codesandbox example](https://codesandbox.io/s/html-input-range-unit-test-bk3e6?file=/src/__tests__/tests.js)). I think radix sliders should be able to be tested like this as well, or at least something like this.

```jsx
import * as RadixSlider from '@radix-ui/react-slider';
import { fireEvent, render, screen } from '@testing-library/react';

describe('radix slider', () => {
  it('can observe default values', () => {
    render(
      <RadixSlider.Root defaultValue={[1, 4]} min={0} max={10}>
        <RadixSlider.Track>
          <RadixSlider.Range/>
        </RadixSlider.Track>
        <RadixSlider.Thumb/>
        <RadixSlider.Thumb/>
      </RadixSlider.Root>
    );

    // This will select the two thumbs since they identify as sliders using aria attributes
    const [first, second] = screen.getAllByRole('slider');

    // But they don't integrate well with the toHaveValue matchers from @testing-library
    // These will fail (see error messages below)
    expect(first).toHaveValue('1');
    expect(second).toHaveValue('4');
  });

  it('can change values', () => {
    render(
      <RadixSlider.Root defaultValue={[1, 4]} min={0} max={10}>
        <RadixSlider.Track>
          <RadixSlider.Range/>
        </RadixSlider.Track>
        <RadixSlider.Thumb/>
        <RadixSlider.Thumb/>
      </RadixSlider.Root>
    );

    // Again, this will select the two thumbs since they identify as sliders using aria attributes
    const [first, second] = screen.getAllByRole('slider');

    // But they don't integrate well with the fireEvent.change from @testing-library
    // These will fail (see error messages below)
    fireEvent.change(first, {target: {value: 5}});
    fireEvent.change(second, {target: {value: 8}});
    expect(first).toHaveValue('5');
    expect(second).toHaveValue('8');
  });
});
```

```
  ● radix slider test › can observe default values

    expect(element).toHaveValue(1)

    Expected the element to have value:
      1
    Received:
      undefined

      19 |
      20 |     const [first, second] = screen.getAllByRole('slider');
    > 21 |     expect(first).toHaveValue('1');
         |                   ^
      22 |     expect(second).toHaveValue('4');
      23 |   });

  ● radix slider test › can change values

    The given element does not have a value setter

      37 |
      38 |     const [first, second] = screen.getAllByRole('slider');
    > 39 |     fireEvent.change(first, {target: {value: 5}});
         |               ^
      40 |     fireEvent.change(second, {target: {value: 8}});
      41 |     expect(first).toHaveValue('5');
      42 |     expect(second).toHaveValue('8');
```

**Comment by jjenzz** [comment]
For some backstory here, @ksandin is trying to write e2e tests for a form that contains a `Slider`. 

How can we change the value of the `Slider` for the e2e test?

The `Slider` renders `input`s when in a form so I initially suggested manually changing their values at the absence of a more user based approach but we have added `display: none` to these inputs which prevents testing lib from being able to find them.

**Comment by jjenzz** [comment]
@ksandin I've been thinking some more about this. My original suggestion was going to be that you should always just interface with the component API itself (so change the value prop) but I wasn't sure if that was possible at the time.

Today though, I learned.... https://testing-library.com/docs/react-testing-library/api/#rerender

This would be my recommended approach because you should never really hook onto the underlying implementation of a third party library. The props API is meant as the layer you would interface with.

For your example though, it looks like you are trying to test if the `Slider` actually works. That is like testing if `React.cloneElement` actually gives you a clone from `React`. These are not things your code should need to cover as the libraries would test those things.

**Comment by ksandin** [comment]
@jjenzz Thank you for your response! I agree that it's not valuable for me to write tests that prove the functionality of the Slider component, or any radix component for that matter. That responsebility lies with the library itself, indeed. Like you said, what I'm doing is testing a form composition. 

First of all, good idea of using the form data. I can indeed observe the form data in my integration test, to make sure the form gets filled in properly. 

However, I disagree with this approach for e2e tests. A user doesn't know about form tags and their data. They just interact with UI, and optimally I'd like my e2e tests to do the same. Interact with the individual UI components, press the submit button, and then I instruct my e2e test to observe that the right data got added to the system by observing the UI, not observing form data.

So while I'm satisfied with your suggested approach regarding integration tests, I'm still curious to know if it's possible to test a radix slider from a purist e2e test perspective.

**Comment by jjenzz** [comment]
> A user doesn't know about form tags and their data. They just interact with UI, and optimally I'd like my e2e tests to do the same

Totally agree with this approach. The only way a user can interact is to drag or use their keyboard so you could focus the thumb and trigger an `ArrowRight` keydown on it several times like a keyboard user would.

**Comment by Kikketer** [comment]
Sorry zombie here.  Using vitest and testing-library to create a simple unit test that would respond to clicks and drags of the slider component.
The slider exists within a component and I'm simply checking that the callback props of this wrapping component are called properly when the user either clicks or drags the slider.  This results in an error:

```
target.hasPointerCapture is not a function
```

This lead me down a whole rabbit hole of attempting to mock that but I came up empty handed.  The component modifies the results so it's not just simply "don't test the library".
Simple example:

psudo code
```
export const SimpleComponent = ({ onAdjusted, onStartClick }) => {
  const adjust = (val) => {
    onAdjusted(val + 3)
  }

  return (
        <Slider.Root onValueChange={adjust}>
            <Slider.Track>
              <Slider.Range />
            </Slider.Track>

            <Slider.Thumb onClick={() => onStartClick()} />
      </Slider.Root>
  )
}
```

And the tests would be something like:
```
it('should add 3 to the value when the user drags the slider', () => {
  const onAdjusted = vi.fn()
  const user = userEvent.setup()
  const { getByRole } = render(<SimpleComponent onAdjusted={onAdjusted} />

  const startThumb = getByRole('slider')

  // Fire events to drag
   fireEvent.pointerDown(startThumb, { clientX: 0, clientY: 0 });
   fireEvent.pointerMove(startThumb, { clientX: 100, clientY: 0 });
   fireEvent.pointerUp(startThumb);

  expect(onAdjust).toHaveBeenCalled()
})
```
