### ISSUE TITLE
Setting min="1" in the @radix-ui/react-slider props breaks the slider

### ISSUE THREAD

**Issue by alishaz-polymath** [radix-ui/primitives#821]
### Current Behavior
If we add min prop in the slider and set it to anything essentially (even 0), it breaks. 

### Expected behavior
The slider should range from min to max, but that doesn't happen and it isn't functional anymore

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/radix-ui-slider-abstracted-example-forked-sz1b8)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-slider       |      0.0.17   |
| React            | n/a     |    17.0.1     |
| Browser          | Chrome, Firefox, MSEdge      |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         | yarn        |         |
| Operating System |  Win10       |         |

**Comment by jjenzz** [comment]
Oh wow, that's not great 😅 thanks for the report. I'll take a look 👍

**Comment by andy-hook** [comment]
Just wondering about the use case for passing a `string` rather than `number`? `min={1}` should work fine.

**Comment by alishaz-polymath** [comment]
A simple type check should probably sort this out, I suppose.

**Comment by jjenzz** [comment]
Ah good spot @andy-hook, I hadn't noticed that 👀 :+1:
