### ISSUE TITLE
New component: HoverMenu

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/primitives#823]
# HoverMenu

An easy to use website navigation pattern with out of the box accessibility and flexible, open components to support a variety of layouts. Useful for large website navigation styles and list or feature heavy marketing.

## Examples

https://user-images.githubusercontent.com/11708259/129596534-5bf460cf-0817-418c-b1f5-495c78924970.mp4

https://user-images.githubusercontent.com/11708259/132385616-37bc6618-d489-4480-b317-4fde35767a76.mp4

https://user-images.githubusercontent.com/11708259/132385755-56ed5c2d-a8fb-44cd-8b3c-8095e0a0c5a8.mp4

https://user-images.githubusercontent.com/11708259/129596571-3027a2af-8d4a-464f-81b2-747fe7acdc2c.mp4

## Requirements

- Support single links alongside hoverable "menus" in top level nav list
- Support pointer grace when moving from item to menu
- Full keyboard control, close on escape, tab to move between menus, arrow up / down to navigate items within
- Full touch support
- Support "tiered" menus, either via nesting or additional part
- Provides `data-state` helper hooks for animating content from left to right / right to left, depending on cursor origin, visibility etc.
- Provide an active item "highlight" part that can be easily animated to move between items
- Provide custom properties with useful values to assist with animation

## Differences to `MenuBar`
`MenuBar` is a [defined pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) and its usage is primarily for application functionality. `HoverMenu` is intended for use as website navigation which among other things, brings with it the need for additional presentation flexibility.

While accessibility needs are similar, most websites have slightly different styles of layout depending on branding, marketing goals and target audience, because of this we can’t be too prescriptive on how this primitive lays out the content and we need a way to provide solid accessibility without compromising the types of layouts consumers may want to achieve.

## Multi tier menu support
Modern UX best practice for site structure is to [favour flatter hierarchies where possible](https://www.nngroup.com/articles/flat-vs-deep-hierarchy/) however, there are cases where it's useful to provide another tier of Hoverable menus.

https://user-images.githubusercontent.com/11708259/132385956-e2bb2818-d9c6-44c6-b413-638007d80af3.mp4

https://user-images.githubusercontent.com/11708259/132385867-e6fca6de-202e-4a65-834f-80bcef5349e8.mp4

For these cases it will be useful to be able to either nest these menus within eachother, or provide an additional part.

## Complex animation
https://user-images.githubusercontent.com/11708259/129596764-6c0214b0-03bd-416d-86c0-47d7bbc9679f.mp4

This is quite a custom solution but the aim with `HoverMenu` is to expose enough key states via `data-state` and custom properties to make something like the stripe example possible without too much trouble.

## Mobile support
Mobile navigation can diverge wildly from its desktop counterpart depending on the needs of the website or marketing objectives. There’s also a question of imposing responsive implementation opinions and how to correctly manage that. In our view there’s enough to consider here that we suggest providing a separate primitive to handle it as a common mobile nav pattern.

This allows us to: 
- Handover conditional rendering concerns to consumers so that they can use whatever approach they prefer
- Keep the base `HoverMenu` implementation scoped and easier to test
- Provide more flexibility to consumers who want a significantly different mobile experience from the desktop counterpart

For example – [Clerk](https://clerk.dev/) choose to handle user journeys differently depending on whether you are using the mobile menu, or the desktop.

I think it’ll be important for us to consider these cases as we provide more mobile specific solutions in the future as well.

**Comment by rafgraph** [comment]
I think this should also support touch input so it works with tablets and hybrid desktops/laptops that have both a mouse and a touch screen.

I agree that small screen navigation is different than large screen navigation (and this is a large screen pattern), but just because the device has a large screen doesn’t mean the user isn’t using touch input that can’t hover.

**Comment by andy-hook** [comment]
> just because the device has a large screen doesn’t mean the user isn’t using touch input that can’t hover.

Fully agree, I think it's all too common to see touch input improvements only at smaller viewports. The device landscape is broad and includes large screens with varying input options as you say so it's an incorrect assumption to couple the two.

**Comment by charkour** [comment]
Very excited about this component!

**Comment by benoitgrelard** [comment]
@charkour, not sure if you realised but it has been released, just under a different name: `NavigationMenu`: https://www.radix-ui.com/docs/primitives/components/navigation-menu

In fact I will close this now 😀

**Comment by charkour** [comment]
Thanks! Big fan. The NavigationMenu is great. 

Cheers!
