### ISSUE TITLE
I want to implement Radix UI components, using Tailwind CSS as a framework

### ISSUE THREAD

**Issue by sbutler-gh** [radix-ui/primitives#829]
## Feature request

I want to implement Radix UI components, using Tailwind CSS as a framework

### Overview

An implementation of Radix UI components, in the Tailwind CSS framework.

For example, on the [Tailwind UI page](https://tailwindui.com/preview), you can see pre-configured UI components, with the code to create them using Tailwind CSS.

I would love to see the same thing for Radix.  You can see the Radix primitives UI components, with the code to create them using Tailwind CSS.

With Radix's focus on developer workflows and configurability, this could fit nicely with projects that are already using Tailwind CSS as a framework.

And it fits nicely with Tailwind's values as a framework — all about configuration and improving the dev workflow.

### Examples in other libraries

[Tailwind UI page](https://tailwindui.com/preview)

### Who does this impact? Who is this for?

This is for all of the developers, projects, and teams which are already using Tailwind CSS as a framework.

### Additional context

A personal piece of context – I'm doing a lot of building with SvelteKit lately.  Tailwind CSS plays well with SvelteKit, but SvelteKit is early-stage and a but temperamental.

So I'd love to incorporate Radix UI — both for accessibility, and dev workflow reasons — into some projects I'm working on.  I just don't want to switch from Tailwind, out of the concern that things will probably break.

**Comment by andy-hook** [comment]
Hey @sbutler-gh, I’m little unclear on your request, all of our components are open and can be styled using any library of your choice. In the case of Tailwind you can use `className` to apply your classes as needed.

Is your request specifically regarding a Tailwind UI style library of pre-designed components?

**Comment by DanielBailey-web** [comment]
@sbutler-gh  I made an example using tailwind CSS in discussions based on the radix-ui alert 

See: #1099
