### ISSUE TITLE
TooltipTrigger adds a type="button" attribute to the rendered element regardless of the value of the "as" prop

### ISSUE THREAD

**Issue by AndrewPrifer** [radix-ui/primitives#830]
### Current Behavior

TooltipTrigger adds a type="button" attribute to the rendered element regardless of the value of the "as" prop.

### Expected behavior

The type="button" attribute is only added when the "as" prop is not specified.

### Reproducible example

https://codesandbox.io/s/friendly-hooks-vokbj?file=/src/App.tsx

### Suggested solution

The type attribute shouldn't be applied automatically when the "as" prop is specified.

### Additional context

The way I bumped into this issue is that the type="button" attribute, in interaction with some other circumstances, prevented the VisuallyHidden styles from doing their job in Safari (where else lol). Explicitly setting the attribute to null solved it. Mind you, I couldn't reproduce the styling issue specifically in the minimal repro above, but the added type attribute is reproduced.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     Tooltip    |     0.0.21    |
| React            | n/a     |     17.0.1    |
| Browser          |     Safari    |      14.1.1   |
| Assistive tech   |     N/A    |      N/A   |
| Operating System |     MacOS    |     Big Sur    |

**Comment by jjenzz** [comment]
@AndrewPrifer Thanks for reporting this although we are aware of this and have left it this way on purpose. With Radix Primitives we ship with the elements and logic you should need most of the time but if you decide to break away from that then it is up to you to ensure the correct accessibility/markup. 

Unfortunately, it would add bloat and an additional re-render if we were to do it our side (which wouldn't work for SSR) just to determine what element you are rendering which seems unnecessarily complex given most people probably wouldn't ever need to change the node.

We would need to do something like this:

```jsx
const Comp = props.as || 'button';
const ref = React.useRef();
const [type, setType] = React.useState('button');

React.useEffect(() => {
	if (ref.current?.tagName !== 'button') setType(undefined);
}, []);

return <Comp type={type} />;
```

Our stance it to try to keep our bundles as small as possible while providing escape hatches instead. So, in your case you would do:

```jsx
<TooltipTrigger as={MyLink} type={undefined} />
```

Something potentially worth discussing instead would be for us to remove the `type="button"` attribute entirely and leave it to consumers to add that attribute if they happen to use these triggers within a form. Not sure how I feel about that though... 

cc: @andy-hook @benoitgrelard ☝️

**Comment by jjenzz** [comment]
Closing as intentional but please feel free to re-open @AndrewPrifer if anything isn't clear or you have other ideas 🙂
