### ISSUE TITLE
Dropdown menu with animation won't close when clicking outside.

### ISSUE THREAD

**Issue by norman-ags** [radix-ui/primitives#849]
### Current Behavior

Dropdown menu with animation won't close when clicking outside. 

### Expected behavior

Dropdown menu should close when clicking outside. 

### Reproducible example

https://codesandbox.io/s/laughing-violet-oq7d1?file=/src/App.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    DropdownMenu     |  0.1.0       |
| React            | n/a     |    17.0.2     |
| Browser          |     Microsoft Edge   |    93.0.961.38     |

**Comment by andy-hook** [comment]
Hey @norman-ags, I can't see the issue from the sandbox you posted. I tested an adjusted example and it works as expected https://codesandbox.io/s/gracious-mendeleev-ulmez?file=/src/App.js

Let me know if i'm missing something!

**Comment by norman-ags** [comment]
> Hey @norman-ags, I can't see the issue from the sandbox you posted. I tested an adjusted example and it works as expected https://codesandbox.io/s/gracious-mendeleev-ulmez?file=/src/App.js
> 
> Let me know if i'm missing something!

Sorry, I forgot to save it while editing. I updated the sandbox now and added this:
```
// Added scaleIn 
animation: `${scaleIn} 0.5s ease-out`
```

**Comment by andy-hook** [comment]
> I updated the sandbox now

Great, thanks. For animation we recommend using the `date-state` attributes per my example so that the presence logic can track and correctly mount/unmount. If you only want to animate in you can simply use `data-state="open”`.  

https://www.radix-ui.com/docs/primitives/overview/animation

Is that helpful? or was there a reason why these wouldn't work for you?

**Comment by norman-ags** [comment]
> Is that helpful? or was there a reason why these wouldn't work for you?

Actually I was just following the example in the [docs](https://www.radix-ui.com/docs/primitives/components/dropdown-menu#origin-aware-animations)

**Comment by andy-hook** [comment]
> Actually, I was just following the example in the [docs](https://www.radix-ui.com/docs/primitives/components/dropdown-menu#origin-aware-animations)

Doh I see the issue now, yes this should be working so looks like a regression. Thanks for the report 👍

**Comment by MildTomato** [comment]
@andy-hook also seeing the same issue. also following [docs](https://www.radix-ui.com/docs/primitives/components/dropdown-menu#origin-aware-animations)

funnily enough, if you click 'outside' the dropdown menu as the animation is still animating, it will close as normal, but the dropdown will not close once animation has completed.

**Comment by MildTomato** [comment]
@andy-hook it's possible that Popover also has the same issue.

**Comment by andy-hook** [comment]
> @andy-hook it's possible that Popover also has the same issue.

Thanks @MildTomato I reckon that's almost certainly the case as the problem stems from some shared code. https://github.com/radix-ui/primitives/pull/851 should resolve it for all affected primitives.

**Comment by andy-hook** [comment]
@norman-ags @MildTomato fixed in [0.1.1-rc.4](https://www.npmjs.com/package/@radix-ui/react-dropdown-menu/v/0.1.1-rc.4)

**Comment by MildTomato** [comment]
@andy-hook lovely!
