### ISSUE TITLE
"asChild" not working on Tooltip

### ISSUE THREAD

**Issue by PeerRich** [radix-ui/primitives#857]
### Current Behavior

recently `as={Slot}` has been deprecated and `asChild` was proposed as the successor, however, asChild throws an error using `"@radix-ui/react-tooltip": "^0.0.21",`

![image](https://user-images.githubusercontent.com/8019099/133113526-ec88f2b1-b68d-4ea8-bd6f-9c710b602b7d.png)

also, visually it breaks:

![image](https://user-images.githubusercontent.com/8019099/133113756-3ac3384d-fd8b-426f-b305-4ebb8ca06bbc.png)

vs

![image](https://user-images.githubusercontent.com/8019099/133113855-41f93cf5-0712-47f5-a202-541441bc2223.png)
(using `as={Slot}`)

### Expected behavior

not throw a type error

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   tooltip      | ^0.0.21     |
| React            | n/a     |  17.0.2   |
| Browser          |  on all |   --      |
| Assistive tech   |   n/a      |       n/a  |
| Node             | n/a     |   14      |
| npm/yarn         | yarn | latest |
| Operating System | macOS|   big sur  |

**Comment by PeerRich** [comment]
not sure when `Slot` is being deprecated. It still works with Slot, so I'll keep it vs using asChild :) 

btw. I think the asChild is a great improvement of the API!

**Comment by jjenzz** [comment]
The `asChild` prop was released in version `0.1.0` and not `0.0.21` ... have you tried with that version? It appears to be working fine here https://codesandbox.io/s/distracted-roentgen-t5him?file=/src/App.tsx

**Comment by PeerRich** [comment]
oh let me try!

**Comment by PeerRich** [comment]
yes that worked. Closing

**Comment by jjenzz** [comment]
Whoop 🙌
