### ISSUE TITLE
[Dialog] Error: Element type is invalid: expected a string but got: object.

### ISSUE THREAD

**Issue by zomars** [radix-ui/primitives#862]
### Expected behavior

Following the [custom APIs implementation](https://www.radix-ui.com/docs/primitives/components/dialog#custom-apis) example in the docs triggers the following error:

![image](https://user-images.githubusercontent.com/3504472/133328621-7fdc4944-86c4-4f3b-ab32-382093cdb50a.png)

### Reproducible example

https://codesandbox.io/s/jolly-matsumoto-v4whe?file=/src/App.tsx

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   @radix-ui/react-dialog      |      latest   |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by jjenzz** [comment]
I can't see an error in the sandbox you have provided and I am unable to replicate here https://codesandbox.io/s/keen-keller-o1kvc?file=/src/App.tsx

Do you have an example of the issue you have described?

**Comment by zomars** [comment]
@jjenzz I think it was the previous version prior to '1.0.1'

I've solved it by upgrading it

**Comment by jjenzz** [comment]
No worries.
