### ISSUE TITLE
[Dialog] Opening dialog causes the app to freeze when using Preact

### ISSUE THREAD

**Issue by MrPumpking** [radix-ui/primitives#863]
### Current Behavior
Dialog opens fine when using React, but after switching to Preact it causes the app to freeze on open.

### Expected behavior
Should not freeze the application. From what I've found, Dialog worked fine with Preact up to the version 0.0.15. It would be great if this library also supported Preact, but I imagine it's not the priority right now. 

### Reproducible example

- [React version](https://codesandbox.io/s/radix-ui-dialog-react-v0xsd)
- [Preact version](https://codesandbox.io/s/radix-ui-dialog-preact-m9gp8) (@radix-ui/dialog 0.1.0) - freezes
- [Preact version](https://codesandbox.io/s/radix-ui-dialog-0-0-15-preact-forked-7h5lo) (@radix-ui/dialog 0.0.15) - works

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |   dialog      |  0.1.0       |
| React            | n/a     |         |
| Browser          |   chrome      |  93       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |   windows      |         |

**Comment by jjenzz** [comment]
Radix Primitives are React only I'm afraid. Unfortunately Preact doesn't support some features in React that we take advantage of quite heavily.

**Comment by dominik-sfl** [comment]
What features are those @jjenzz, if you don't mind me asking? Is there any way to overcome this? Would love to use radix!

**Comment by jjenzz** [comment]
@dominik-sfl They don't have SyntheticEvents which means events don't bubble through portals 😢

**Comment by dominik-sfl** [comment]
Thanks a lot. That's also the answer to [my question here](https://github.com/radix-ui/primitives/discussions/807) about it freezing in production - as I swap out React for Preact when building 😔

**Comment by jjenzz** [comment]
Ah yes, that would make sense 👍

**Comment by nikuda** [comment]
This is now fixed on Preact side with `v10.10.1`

> Fix infinite loop in radix-ui which enqueues multiple state updates in the same tick (https://github.com/preactjs/preact/pull/3645, thanks @JoviDeCroock )

Release notes: https://github.com/preactjs/preact/releases
Demo here: https://stackblitz.com/edit/nextjs-preact-webpack5-dmpk3a

I'm able to use the Slider component now, the page doesn't freeze though there's an issue with `Thumb` components not receiving any positional updates, demo here https://stackblitz.com/edit/nextjs-preact-webpack5-pjoxwh
