### ISSUE TITLE
[Slider] zero values do not display correctly when min is less than zero

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#865]
### Current Behavior

The Slider component does not display zero values correctly when the min value is set to less than zero. A component with the props `value={[0]} min={-100} max={100}` should display the knob at the center, however it instead displays it at the left side. 

![image](https://user-images.githubusercontent.com/23072548/133491343-5c8c3acc-bf6e-4713-abe4-03b887a386c6.png)

Other values, including negative values, display correctly. A slider with the props `value={[-50]} min={-100} max={100}` would correctly display at 25% from left. 

### Expected behavior

when  zero value should display at the center of the slider.

### Reproducible example

https://codesandbox.io/s/determined-ellis-yc2zk?file=/App.js

### Your environment

"@radix-ui/react-slider": "^0.1.0",

**Comment by benoitgrelard** [comment]
Hey Steve, thanks for reporting that one, definitely looks like some dodgy math somewhere for the 0 case. We'll dig in.

**Comment by benoitgrelard** [comment]
That's fixed in #866, wasn't too hard 😀
Btw, thanks a lot for the great styled repro!

**Comment by benoitgrelard** [comment]
Hey @steveruizok this is now fixed in [0.1.1-rc.3](https://www.npmjs.com/package/@radix-ui/react-slider/v/0.1.1-rc.3)

**Comment by steveruizok** [comment]
> Btw, thanks a lot for the great styled repro!

Cheers, this button makes it easy!

![image](https://user-images.githubusercontent.com/23072548/133756004-88df1bcc-bb01-4fd0-822c-0c61545e35fc.png)
