### ISSUE TITLE
[Checkbox][RadioGroup][Switch] Incorrect BubbleInput positioning in flex layouts

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#867]
We tried to position the hidden `BubbleInput` on top of the control we render so that native validation is positioned correctly but it gets moved into the wrong position if someone uses flex or grid layout:

https://user-images.githubusercontent.com/175330/133586363-413471a7-5f19-44c9-a2a6-ef81a7544c2b.mp4

**Comment by benoitgrelard** [comment]
Given it is possible to address user-side by targeting with a CSS fix, we won't make any change.
