### ISSUE TITLE
[Popover] - doesn't open when not controlled and inside Material UI modal

### ISSUE THREAD

**Issue by nirbenya** [radix-ui/primitives#871]
### Current Behavior

Cant open popover on click when inside material ui modal

### Expected behavior

It should open :)

### Reproducible example

https://codesandbox.io/s/lingering-cdn-ex2v7?file=/src/App.js

### Suggested solution

I'm looking into the issue, the problem is with the DismissableLayer component. The onDismiss callback is getting called, when it's commented out it works fine. it calls setOpen with false value and makes the popover not being opened (or more accurate: opens and immediately closes)
```
  // Dismiss on focus outside
  const { onBlurCapture: handleBlurCapture, onFocusCapture: handleFocusCapture } = useFocusOutside(
    (event) => {
      onFocusOutside?.(event);
      onInteractOutside?.(event);
      if (!event.defaultPrevented) {
        //onDismiss?.();
      }
    }
  );
```

Probably some focus wars with material modal, posting this issue anyway because it might take me long to fix.

**Comment by jjenzz** [comment]
@nirbenya This looks like Material UI's focus trapping is assuming that the Popover is outside of the modal and stealing focus back to the modal container. However, components can be in the same **React tree** while not in the same **DOM tree** and shouldn't really trigger focus trapping logic in that case.

Our [Dialog](https://www.npmjs.com/package/@radix-ui/react-dialog) handles this case but if you have to use the Material UI one then you can [set `portalled={false}` on the `PoppoverContent`](https://codesandbox.io/s/cranky-bose-9e7qd?file=/src/App.js) to keep its DOM inside the dialog.

Having said that, I believe there are some outstanding positioning bugs related to `portalled={false}` so there is a chance you might stumble across those.
