### ISSUE TITLE
Investigate outdated typedefs with `0.1.0` packages

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/primitives#872]
Original report was that there were outdated type issues when using `0.1.0` packages.

Initially the problem seemed to be cache related on the code sandbox side. When using the `latest` tag the typedefs being pulled were outdated, this could be remedied by pinning `0.1.0`.

(At time of writing)
Works: https://codesandbox.io/s/compassionate-thunder-0i38b?file=/src/App.tsx
 Errors: https://codesandbox.io/s/amazing-surf-smzs4?file=/src/App.tsx

We've since had a report that this is a problem in a local [rushjs.io](https://rushjs.io/) project even when pinning.

https://discord.com/channels/752614004387610674/888281145983246367/888461160444231681

> we run `rush add -p radix-package-name --exact`

We should investigate further to understand the issue.

**Comment by benoitgrelard** [comment]
Looking at what's published 👇 , I still can't see how it can be an issue with our side of things so far:

https://unpkg.com/browse/@radix-ui/react-alert-dialog@0.1.0/dist/index.d.ts

These definitely are the latest types as far as I know.
This is really strange…  🤔

**Comment by jjenzz** [comment]
Yep and even if you go to `@latest` it redirects correctly: http://unpkg.com/browse/@radix-ui/react-alert-dialog@latest/dist/index.d.ts

Agree we could look into this but if unpkg can resolve it okay then I'm really struggling to think of ways our distribution could be impacting these projects 🙈

**Comment by andy-hook** [comment]
It seems like there could be some package resolution issues in [pnpm](https://pnpm.io/) projects.

> Because we have older versions of @radix-ui/react-dropdown-menu and @radix-ui/react-tooltip, it's resolving an older version of @radix-ui/react-primitive that doesn't have the asChild prop.

> upgrading the react-dropdown-menu and react-tooltip to v0.1.0 fixed the issue with alert dialog.

Would need to look into it further when there is time, we suspect a bug in pnpm.
