### ISSUE TITLE
Accordion.Root: Typescript error when assign a boolean to collapsible prop

### ISSUE THREAD

**Issue by MichaelDM** [radix-ui/primitives#876]
### Current Behavior

I am using the Accordion component, and seeking to specify a boolean value to the collapsible prop such as for example: `<Accordion.Root collapsible={true} />`. I have a typescript error on `collapsible`
<img width="1374" alt="Screen Shot 2021-09-22 at 1 41 16 PM" src="https://user-images.githubusercontent.com/12537128/134337305-e7b529c1-28b7-4120-9abb-0e17ce324f9b.png">

### Expected behavior

I should be able to write `<Accordion.Root collapsible={true} />` with no typescript error. I expect this to work as shown in the documentation example: https://github.com/radix-ui/primitives/issues/876. 

### Reproducible example

https://codesandbox.io/s/lucid-jennings-om3cf?file=/src/Accordion.tsx

### Additional context

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  @radix-ui/react-accordion  |  0.1.0  |
| React            | n/a     |   17.0.2      |
| typescript    | typescript | 4.4.3

**Comment by benoitgrelard** [comment]
HI @MichaelDM, it's because the `collapsible` prop is only valid for single `type`.
So from a TS standpoint it can't exist on `type` multiple.
Something like this should satisfy it:

```ts
<AccordionRoot type={type} {...(type === "single" ? { collapsible: true } : {})}>
```

**Comment by MichaelDM** [comment]
Ok @benoitgrelard, noted, thank you for your response!
