### ISSUE TITLE
Add content-height CSS custom property to Collapsible

### ISSUE THREAD

**Issue by imtiazmangerah** [radix-ui/primitives#878]
### Overview

The `Collapsible` primitive currently exposes a CSS custom property `--radix-collapsible-content-height` that can be used to animate content when it opens/closes. The feature request is for the addition of `--radix-collapsible-content-width`. This can enhance the utility of this primitive, allowing animating both width and height, or enabling support for animations when the orientation of the collapsible is changed.

### Examples in other libraries

[Bootstrap](https://getbootstrap.com/docs/5.1/components/collapse/#horizontal)

### Who does this impact? Who is this for?

Enhancement for all users to support more use cases. My use case is to support an animated horizontal Collapsible

**Comment by benoitgrelard** [comment]
Closed via #882

**Comment by benoitgrelard** [comment]
The fix is now available in [0.1.1-rc.10](https://www.npmjs.com/package/@radix-ui/react-collapsible/v/0.1.1-rc.10)
