### ISSUE TITLE
ScrollArea - Display scollbar on focus

### ISSUE THREAD

**Issue by matthova** [radix-ui/primitives#880]
### Overview

Would like to see the scrollbar display on focus of any of its children elements. This behavior could be surfaced via a new ScrollArea `type` prop. 

### Examples in other libraries

tbh not sure 🤷‍♂️
I'd imagine you'd have to do some sort of `scrollArea.contains(event.target)` logic

### Who does this impact? Who is this for?

This is important for accessibility as well as keyboard power-users to know that the area they are navigating is scrollable.

### Additional context

Love this library! Thanks for all the work y'all do 🎉

**Comment by jjenzz** [comment]
We tend to match native MacOS behaviour which will only show the scrollbar when you focus something that was off screen. Ours will do the same if you change the `type` to `scroll`.

@andy-hook @benoitgrelard  The `hover` type doesn't do that but we could probably add it there too?

**Comment by benoitgrelard** [comment]
I didn't realise the "or any of its children elements" thing, not sure if that makes sense.
Originally when we discussed on Discord (where the question came from) I was more thinking that we could potentially reveal the scrollbar when the scrollarea itself gets focused. So we could simply add the listeners for it, and if people want that behaviour they'd have to make the scrollarea tababble by adding a tabindex.

I can see how if you're only using keyboard, it might make sense.

**Comment by jjenzz** [comment]
> I was more thinking that we could potentially reveal the scrollbar when the scrollarea itself gets focused.

That is not something scrollbars do natively so sounds more like a use-case for controlling the component to me. The example I gave above would just need to be updated to ensure that the focused thing was the viewport and not an element inside of it.
