### ISSUE TITLE
[DropdownMenu] Portal not displaying when parent element is fullscreen [Chrome]

### ISSUE THREAD

**Issue by leoafarias** [radix-ui/primitives#885]
### Current Behavior
The following issue happens on Brave(Chrome), however, it works correctly in Safari.

When using the code snippet above. The dropdown demo does not display its content, the same happens for tooltips, which are not displayed if the parent element is in full screen.
 
Using `react-full-screen` to make the demo code shorter, however, the issue happens when using low-level browser APIs.

### Expected behavior

Components that are dependent on Portals should display correctly in the parent is a fullscreen element.

### Reproducible example

Example code : https://codesandbox.io/s/romantic-violet-rl55j

To run the test in full screen you have to open in a separate window.
Here is the link: https://rl55j.csb.app (Open on Chrome)

### Suggested solution

Portal elements should display correctly on the browser.

### Your environment

Brave browser (Chrome)

**Comment by jjenzz** [comment]
Looks like you may have discovered a bug in React or the full screen APIs. Portalling renders the element (I can inspect it) but doesn't show it visually 🤔 

https://codesandbox.io/s/fullscreen-chrome-portal-bug-forked-h7t28?file=/src/App.tsx
Separate window link: https://h7t28.csb.app/

I'd suggest raising this issue with the React team perhaps?

**Comment by jjenzz** [comment]
Oh wait, scrap that... I see what's happening now, sorry. It's because the element you are making full screen isn't the `body` 🙈 

Looks like you need this issue to be resolved so you can configure where the dropdown gets portalled? https://github.com/radix-ui/primitives/issues/760

**Comment by leoafarias** [comment]
@jjenzz I tried this based on the docs, however, this adds a lot of complexity on implementation, because my layout is positioned `absolute`, I believe what you suggested to set the element is the ideal solution, which is used by some popular popper libraries. 

I could not figure out why Safari works correctly though.

**Comment by benoitgrelard** [comment]
Will be closed when #1303 is closed.

**Comment by dcheglakov** [comment]
Hey, any updates here? I've the same issue with fullscreen and absolute positioning. portalled={false} positions the popover incorrectly.

**Comment by benoitgrelard** [comment]
Hye @dcheglakov you can follow the progress of the current milestone here: https://github.com/radix-ui/primitives/milestones

✌️

**Comment by benoitgrelard** [comment]
@leoafarias, sorry we forgot to update this issue, but we can close it now because #1303 has been merged. You can test it out in the latest release candidate for now. The gist is now you have a `DropdownMenu.Portal` part on which you can give a custom `container` to inject the portal into (rather than body) so if you make that container part of what you are full-screening it would then be visible in fullscreen mode.
