### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by viniciushvc** [radix-ui/primitives#886]
## Feature request
 Pagination primitive component
 
### Overview

Component that shows the next 3-4 pages, next and previous button and some way to go to last and first quickly

### Examples in other libraries

![image](https://user-images.githubusercontent.com/16567830/135657669-941fd913-a201-4a64-9778-606f56d07136.png)
https://mui.com/pt/components/pagination/

### Who does this impact? Who is this for?

For all users, to be easy to create item listings

**Comment by benoitgrelard** [comment]
Closing as duplicate as there's already an open discussion here: #831
