### ISSUE TITLE
VoiceOver prepends "1" to every checked menu item

### ISSUE THREAD

**Issue by vladmoroz** [radix-ui/primitives#889]
### Current Behavior

When using dropdown menu primitive with macOS VoiceOver, it prepends "1" when announcing ticked items like so:

<img width="661" alt="Screenshot 2021-10-04 at 16 35 43" src="https://user-images.githubusercontent.com/8441036/135861352-a32ed57e-431b-44d1-8005-e80b476931e9.png">

This happens with ticked radio and checkbox items only, regardless of whether they are in a group.

### Expected behavior

Expected to announce just the item text contents and its functional description.

### Reproducible example

https://codesandbox.io/s/0tr78?module=App.js

### Your environment

macOS Big Sur 11.4, any browser

**Comment by jjenzz** [comment]
This is a VoiceOver bug I believe https://github.com/microsoft/fluentui/issues/14064

Not really sure what we can do here. The same thing happens in the WAI ARIA demo here :( https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-2/menubar-2.html

**Comment by vladmoroz** [comment]
Oh OK, nothing we can do about it I guess. Thanks for checking it out, Jenna.
