### ISSUE TITLE
[Id][Tooltip] Multiple sibling `IdProviders` cause mirrored interactions

### ISSUE THREAD

**Issue by andy-hook** [radix-ui/primitives#899]
This is quite specific to storybook configurations because you wouldn't typically render more than one `IdProvider` inside an app.

Because of the crossover with storybook and snapshot testing, it makes sense to wrap a provider per story via decorators to stabilise the `id`, however that causes an interesting visual side effect when rendered inline with the [docs addon](https://storybook.js.org/docs/react/writing-docs/docs-page).

The problem is that multiple instances of `IdProvider` increment in sync so there are duplicate identifiers on the page and the global machine just rolls with it.

https://user-images.githubusercontent.com/11708259/136595395-0705ed61-6fba-4804-a2a4-5dcd8c586780.mp4

**Comment by oeduardoal** [comment]
Hey @andy-hook May be caused by these issues
![image](https://user-images.githubusercontent.com/12778450/142917417-c403b2bd-6c1e-4fe1-91c1-7124f19460d9.png)

https://discord.com/channels/752614004387610674/803656530259738674/911279133617688587

@jjenzz right?

**Comment by jjenzz** [comment]
Yeah, from @andy-hook:

>This is quite specific to storybook configurations because you wouldn't typically render more than one `IdProvider` inside an app.

There should only be one `IdProvider` (to ensure uniqueness) but this issue was raised to see if there is a way we can improve this  storybook experience. 

I will look into all of this during this week 🙏
