### ISSUE TITLE
[Presence] Using longhand animation properties prevent unmount

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#911]
Originally reported on [twitter](https://twitter.com/JensdeRond/status/1447638834028728321?s=20). 

https://codesandbox.io/s/stitches-radix-bug-0ul6n

**Comment by Jensderond** [comment]
Thanks for the effort!

**Comment by jjenzz** [comment]
> If you install popover using the `@next` tag you should see the issue resolved:

Oh weird, when I tried that last night it wasn't working for me. Perhaps I didn't reload sandbox properly with the upgrade 🙈
