### ISSUE TITLE
Hover Card Content can't be focused inside Dialog

### ISSUE THREAD

**Issue by bogdansoare** [radix-ui/primitives#920]
## Bug report
The Hover Card content closes inside the Dialog even though is hovered.

### Current Behavior

https://user-images.githubusercontent.com/2750170/137478803-315976ce-ba27-4329-80ba-153631263160.mov

### Expected behavior

The hover card content should remain open when hovered

### Reproducible example

https://codesandbox.io/s/confident-albattani-ckgqr?file=/App.js

### Suggested solution

<img width="567" alt="Screenshot 2021-10-15 at 14 20 09" src="https://user-images.githubusercontent.com/2750170/137479236-33a08945-03aa-4a3a-9ed3-65973efde7cf.png">

The dialog and the hover card are in 2 different portals, so maybe there needs to be a way to specify that the hover card portal should be on top.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-dialog, react-hover-card       |    0.1.1     |
| React            | n/a     | 17        |
| Browser          | Chrome        | 94       |
| Operating System |  mac  OS     |  Big Sur       |

**Comment by kmlrmdhn** [comment]
{catalog?.map((item, i) => (
                          <DropdownMenuItem
                            onClick={() => handleDownload(item)}
                            key={i}
                          >
                            {item?.name}
                          </DropdownMenuItem>
                        ))}
                    </HoverCardContent>
                    
                    on, still doesnt work.
                    
                    can anyoone help me?
                    
                    @andy-hook 
                    @bogdansoare
