### ISSUE TITLE
Input in Portal can't be focused inside Dialog

### ISSUE THREAD

**Issue by yyz945947732** [radix-ui/primitives#922]
https://codesandbox.io/s/focused-platform-2itl5?file=/App.js

A element which use Portal inside Dialog will cant't be focused and have style with 'pointer-events : none'. What can i do to solve it?

```js
<Dialog.Root>
  <Dialog.Content>
    <Portal>
      <input />
    </Portal>
  </Dialog.Content>
</Dialog.Root>
```

**Comment by yyz945947732** [comment]
I do plan to refactor this component with radix, but it will take time, so I want to find a temporary solution. So is it appropriate to say that it is not the best practice to use radix with other component libraries, because it may cause some weird problems? At present, to solve this problem can only use radix's popover?

**Comment by yyz945947732** [comment]
Thank you so much.

And I have seen similar problems with other libraries recently, I don't know if these can give some help:

https://github.com/theKashey/react-focus-lock/blob/master/src/Trap.js#L144-L156
https://github.com/mui-org/material-ui/pull/21610/files

There may be an solution here is **if `<FocusScope />` children's React event's `currentTarget` does not contain `target`, then it can be treated as a portal.**

But I know that the way radix manages focus is more complicated, because it supports more features than other libraries. So I don’t know if these can help a bit.

**Comment by fysherman** [comment]
> > I'm sorry. Set modal={true} is necessary in my case.
> > BTW, thank you for the fast response and for taking a deeper look at this issue.
> 
> No worries. I'm not sure of an alternative workaround in the meantime in that case so we can look into React tree support when we have some time. Thanks for taking the time to help us understand the issue 🙂
> 
> EDIT: I just thought though, you could use our `FocusScope` and `DismissableLayer` components to get this working manually yourself in the meantime: https://codesandbox.io/s/thirsty-jang-quxe4?file=/src/App.js
> 
> The `FocusScope` is the component that allows the focus to escape and the `DismissableLayer` enables escape keypress to close, along with pointer down outside etc. while maintaining correct layering. So, escape key once will close your popover and escape key again will close the dialog.

Exactly what i want. thanks

**Comment by zeroliu** [comment]
For my case, I have the following nested tree
```
<Dialog>
  <Popover>
    <Input>
  </Popover>
</Dialog>
```
The input cannot gain focus as @jjenzz explained. Adding FocusScope between Popover.Portal and Popover.Content fixes the issue for me. I don't need DismissableLayer.

Thanks @jjenzz for the explanation and the working demo.

**Comment by pycraft114** [comment]
input in popover that is inside modal can not be focused in safari still
