### ISSUE TITLE
[RadioGroup] Focusing a radio item causes the radio group value to change as if that item was clicked

### ISSUE THREAD

**Issue by mrdavidjcole** [radix-ui/primitives#938]
First things first: Radix is **wonderful**. Thank you for creating it!

---

### Current Behavior

Programmatically focusing an `Item` in a Radix radio group causes that `Item` to become checked.

### Expected behavior

Programmatically focusing an `Item` should not cause it to become checked.

### Reproducible example

https://codesandbox.io/s/festive-goldstine-sjt3o?file=/App.js

To repro: Click the button and see that the checked `Item` changes (unexpectedly... I'm pretty sure).

### Suggested solution

I'm not sure

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    @radix-ui/react-radio-group     |     0.1.1    |
| React            | n/a     |    17.0.2     |
| Browser          |    Chrome     |     Version 96.0.4664.18 (Official Build) beta (arm64)    |
| Assistive tech   |    n/a     |         |
| Node             | n/a     |         |
| npm/yarn         |    whatever codesandbox is using     |         |
| Operating System |    macOS     |     12.0.1    |

**Comment by benoitgrelard** [comment]
Hey @davidkhayutin,

This was fixed by this PR a long time ago and I can't see any regression so it works as intended.
What issue are you referring to?

**Comment by davidkhayutin** [comment]
The issue I am referring to is that when I use the up/down arrows on the radio they become checked - I would expect them here to be focused but not checked - I am never using my mouse in this interaction but using tab to reach the first radio and then using the up and down arrows

**Comment by benoitgrelard** [comment]
> Update: a bit more research in aria shows that arrow movement should in fact change the state from checked/unchecked

Yes that is the correct behaviour.
Just to clarify, the original issue fixed here was that an unchecked radio would get checked when focusing it via tab key.
