### ISSUE TITLE
Any chance supporting Vue will ever be a thing?

### ISSUE THREAD

**Issue by vesper8** [radix-ui/primitives#947]
Really interested in using this on a client's project, specifically the ScrollArea, but the project is already deep into development and made using Vue. I know this is a React project but, do you think it would be possible to use it in a Vue project?

Thanks

**Comment by jjenzz** [comment]
There are no short term plans to add Vue support as far as I know. We would like to support it (and others) in the future but that could be a good while away I'm afraid.
