### ISSUE TITLE
[ToggleGroup] Use `role=radio` when `type=single`

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/primitives#951]
Originally spotted here https://github.com/radix-ui/primitives/issues/949

The WAI ARIA toolbar example shows the expectation https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html

**Comment by benoitgrelard** [comment]
Is that only when used in a toolbar or by itself too?
I'm confused why we're talking about toolbar, when we're talking about toggle group too.
I know we're re-exporting it there, but just want to understand where the issue lies.

**Comment by jjenzz** [comment]
I assumed both as the current implementation seems it wouldn't make it clear to SRs that only **one** item can be selected.
