### ISSUE TITLE
The `asChild` does not work with regular React components.

### ISSUE THREAD

**Issue by steveruizok** [radix-ui/primitives#953]
## Bug report

The `asChild` prop for Radix primitives does not seem to work regular components, only inline markup or components created with `@stitches/react`. This makes it difficult to use with `@stitches/core`.

### Current Behavior

Let's say I have a regular IconButton.

```js
const iconButton = css({ ... });

const MenuButton = React.forwardRef((props, ref) => {
  return (
    <button ref={ref} aria-label="Customise options" className={iconButton()}>
      <HamburgerMenuIcon />
    </button>
  );
});
```

...and I want a `DropdownMenu.Trigger` to display this component.

```js
export const Menu = () => {
  return (
      <DropdownMenu.Root>
        <DropdownMenu.Trigger asChild>
          <MenuButton />
        </DropdownMenu.Trigger>

        <DropdownMenu.Content>
          ... 
        </DropdownMenu.Content>
      </DropdownMenu.Root>
  );
};
```

This does not work.

However, if I move the markup into the DropdownMenu:

```js
export const Menu = () => {
  return (
      <DropdownMenu.Root>
        <DropdownMenu.Trigger asChild>
          <button ref={ref} aria-label="Customise options" className={iconButton()}>
            <HamburgerMenuIcon />
          </button>
        </DropdownMenu.Trigger>

        <DropdownMenu.Content>
          ... 
        </DropdownMenu.Content>
      </DropdownMenu.Root>
  );
};
```

Then it does work.

### Expected behavior

I would expect the `asChild` prop to work with regular components in the same way as it does with those created via `@stitches/react`'s `styled` function. If there's something special there, I'd love to know it!

### Reproducible example

https://codesandbox.io/s/summer-wood-irmnr?file=/App.js:3996-4050

### Your environment

See CodeSandbox, should be latest of everything.

**Comment by jjenzz** [comment]
I believe this is happening because you're asking `asChild` to use a component that doesn't spread DOM props. This should solve it:

```jsx
const MenuButton = React.forwardRef((props, ref) => {
  return (
    <button {...props} ref={ref} aria-label="Customise options" className={iconButton()}>
      <HamburgerMenuIcon />
    </button>
  );
});
```

https://codesandbox.io/s/determined-fast-rifc6?file=/App.js

**Comment by steveruizok** [comment]
Ah, nice! Could be a good one for the docs, I couldn't figure it out.

**Comment by jjenzz** [comment]
I agree. It's interesting how this also wouldn't have worked with the `as` prop but for some reason the `asChild` API seems to be highlighting these issues more for people.

**Comment by jjenzz** [comment]
@steveruizok I've added an [issue to the website repo](https://github.com/radix-ui/website/issues/269) to add some docs on all of this. I'll close this for now but let me know if there is anything else you think warrants keeping this open.

**Comment by jordanlesich** [comment]
Hey, just a bit of feedback. 

Many people are going to want to use their own components as a trigger. It would be really useful to put a blurb about this, and possibly also a blurb about forwarding refs in the docs. 

Also, I'm using styled-components. Is there a list of other considerations and challenges that I could review? Would be really helpful.
