### ISSUE TITLE
Accordion with CSS animation doesn't close when `forceMount` is applied

### ISSUE THREAD

**Issue by a-type** [radix-ui/primitives#957]
### Current Behavior

When adding the `forceMount` prop to an AccordionContent which has a CSS animated open and close (using `animation`),  the accordion returns to an open state after closing.

### Expected behavior

I expect the content to remain mounted in DOM, but be constrained to 0-height. Ideally I'd also like this mounted content to be treated as invisible from an a11y perspective.

### Reproducible example

[CodeSandbox](https://codesandbox.io/s/charming-bush-4ds1p?file=/App.js)

Copied from Accordion demo, the only change is to add `forceMount` to the last item.

### Suggested solution

I'm not sure after a cursory tour of the code, but I'm guessing this has to do with how Collapsible interrupts animations for measurement, or some bug in how that measurement is achieved with a force-mounted element. Perhaps the element is simply measured back to the original height because of the mounted content, despite closed?

I've also noticed that the height CSS custom property doesn't appear to be applied to the component when it's closed at all. I can't fathom why that would be the case by looking at the logic.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |  react-accordion       |0.1.1         |
| React            | n/a     | 17.0.2        |
| Browser          |  Chrome       |  95       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System | MacOS        |   11.6      |

**Comment by a-type** [comment]
Thanks to @jjenzz for the help on Discord, a few tweaks to the CSS appropriately closes the accordion and applies `display: none` to make it hidden! See the changes in this [CodeSandbox](https://codesandbox.io/s/sweet-zeh-z46ch).

Relevant changes from the example styling:

- Add `forwards` animation mode to the `slideUp` animation on the Content
- Add `display: none` to the `to` animation keyframe in the `slideUp` animation.

**Comment by a-type** [comment]
Ok, I think I resolved the visibility portion. I added a transition on visibility with `0ms` duration and `300ms` delay (to match the duration of the animation). I set `visibility: hidden` in the `closed` state.

That should appropriately hide it from screen readers once the content has fully disappeared from view.

**Comment by JanderSilv** [comment]
Hello @a-type , the CodeSandbox has expired. Do you still have this code example?
