### ISSUE TITLE
[Accordion] TypeError when defaultValue isn't an array

### ISSUE THREAD

**Issue by hoop71** [radix-ui/primitives#958]
### Current Behavior

Passing a string to `defaultValue` when `type='multiple'` throws a TypeError when that items is closed. 

Corresponding code: https://github.com/radix-ui/primitives/blob/main/packages/react/accordion/src/Accordion.tsx#L166

https://www.loom.com/share/fba9c67b7b2e4008b06420c9509150f9

![image](https://user-images.githubusercontent.com/25015764/140594712-df0b0e0b-edf2-48da-9e04-88dba769d103.png)

### Expected behavior

Code is resilient enough to handle this type of user error, or prevents the mistake altogether.

### Reproducible example

[CodeSandbox Repro](https://codesandbox.io/s/radix-accordion-bug-c505z?file=/App.js:3002-3010)

### Suggested solution

**Quick solution**: Check for the type of the prop and make sure it doesn't get passed.  
```
diff --git a/packages/react/accordion/src/Accordion.tsx b/packages/react/accordion/src/Accordion.tsx
index 89101cdf..8c56d9b8 100644
--- a/packages/react/accordion/src/Accordion.tsx
+++ b/packages/react/accordion/src/Accordion.tsx
@@ -42,7 +42,12 @@ const Accordion = React.forwardRef<AccordionElement, AccordionSingleProps | Acco
     }
 
     if (type === 'multiple') {
-      const multipleProps = accordionProps as AccordionImplMultipleProps;
+      const multipleProps = (
+        Array.isArray(accordionProps?.defaultValue)
+          ? accordionProps
+          : { ...accordionProps, defaultValue: [] }
+      ) as AccordionMultipleProps;
+
       return <AccordionImplMultiple {...multipleProps} ref={forwardedRef} />;
     }
```

Would also be nice to give the user feedback on what the problem is. It's not immediately obvious what the problem is.

### Additional context

This library is awesome! Keep up the great work. 🚀 

- Can the `single` and `multiple` share an API where `defaultValue: string[]`. This would allow some simplification of logic and doesn't require the user to make a decision and can remove duplicative-ish props.

<img width="759" alt="Screen Shot 2021-11-05 at 8 43 22 PM" src="https://user-images.githubusercontent.com/25015764/140595285-1765fa3c-fd00-4b4f-8aa4-f28365d7272f.png">

- Is there a way to remove the `defaultValue` prop all together? Seems like if the user passes `value` without an `onValueChange` function, the `<Accordion />` could be assumed to be uncontrolled. Passing an `onValueChange` function makes it controlled. 

I understand these would be breaking changes...

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |    @latest     |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by benoitgrelard** [comment]
Hi @hoop71, thanks for raising this.

This happens as the passed defaultValue type is incorrect as I'm sure you've understood.
When using typescript, this is obvious, but I understand that when using JavaScript it may not be.
That said, it's a fine line as to what we warn about, etc. We could check the type and throw a better error, but we typically haven't done that anywhere else, and I would then keep wondering where we should do it, and where we don't?

Generally we feel like the docs should be enough to circle back to if you have an error.

That said:

> Can the single and multiple share an API where defaultValue: string[]. This would allow some simplification of logic and doesn't require the user to make a decision and can remove duplicative-ish props.
Screen Shot 2021-11-05 at 8 43 22 PM

We are aware that this presentation is not very obvious, as it looks like duplicated props. We have been talking about improving how we would show such scenarios. Additionally, having values always be an array regarding of single/multiple is also something we considered very early on, and as much as it would simplify things for us internally too, we don't feel this is good DX for users as it's confusing to have to pass a single item in an array, it just doesn't make much sense.

Definitely happy to discuss solutions though.

> Is there a way to remove the defaultValue prop all together? Seems like if the user passes value without an onValueChange function, the <Accordion /> could be assumed to be uncontrolled. Passing an onValueChange function makes it controlled.

This wouldn't make sense either as it goes against the principles of controlled/uncontrolled components in React. For example if you pass a `value` to an `input` in React, it is now controlled, meaning that `value` needs to be updated (either via the `onChange`, or anything else) or the input value will never ever change. Our primitives follow the exact same principles.

**Comment by jjenzz** [comment]
Perhaps we should invest some time adding more `propTypes` to our comps to help with this.

**Comment by benoitgrelard** [comment]
Yeah propTypes would be the obvious solution, I remember we discussed it at some point but we weren't sure if we should do it for all props or just for contentious cases like these.

We also need to make sure they get treeshaken as well.

**Comment by hoop71** [comment]
> Hi @hoop71, thanks for raising this.
> 
> This happens as the passed defaultValue type is incorrect as I'm sure you've understood. When using typescript, this is obvious, but I understand that when using JavaScript it may not be. That said, it's a fine line as to what we warn about, etc. We could check the type and throw a better error, but we typically haven't done that anywhere else, and I would then keep wondering where we should do it, and where we don't?
> 
> Generally we feel like the docs should be enough to circle back to if you have an error.
> 
> That said:
> 
> > Can the single and multiple share an API where defaultValue: string[]. This would allow some simplification of logic and doesn't require the user to make a decision and can remove duplicative-ish props.
> > Screen Shot 2021-11-05 at 8 43 22 PM
> 
> We are aware that this presentation is not very obvious, as it looks like duplicated props. We have been talking about improving how we would show such scenarios. Additionally, having values always be an array regarding of single/multiple is also something we considered very early on, and as much as it would simplify things for us internally too, we don't feel this is good DX for users as it's confusing to have to pass a single item in an array, it just doesn't make much sense.
> 
> Definitely happy to discuss solutions though.
> 
> > Is there a way to remove the defaultValue prop all together? Seems like if the user passes value without an onValueChange function, the  could be assumed to be uncontrolled. Passing an onValueChange function makes it controlled.
> 
> This wouldn't make sense either as it goes against the principles of controlled/uncontrolled components in React. For example if you pass a `value` to an `input` in React, it is now controlled, meaning that `value` needs to be updated (either via the `onChange`, or anything else) or the input value will never ever change. Our primitives follow the exact same principles.

Thanks for sharing these thought. Helpful to understand you thinking. Grateful for this library and your efforts. ❤️
