### ISSUE TITLE
AvatarFallback Error in Next.js

### ISSUE THREAD

**Issue by mtergel** [radix-ui/primitives#962]
### Current Behavior
Throwing Error: `AvatarFallback` must be used within `Avatar` even though I am not using the component in my project.

```
pages/_document.tsx (11:31) @ Function.getInitialProps

   9 | class MyDocument extends Document {
  10 |   static async getInitialProps(ctx: DocumentContext) {
> 11 |     const initialProps = await Document.getInitialProps(ctx);
     |                               ^
  12 | 
  13 |     return initialProps;
  14 |   }
```
### Expected behavior

Not throw error.

### Reproducible example

[CodeSandbox Demo](https://codesandbox.io/s/awesome-sunset-474uq)

### Additional context
The avatar component is only in my package.json.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) | react-avatar        |  0.1.1       |
| React            | n/a     |    17.0.2     |
| Browser          |    Mozila     |     91.0    |
| Assistive tech   |   Nextjs      |    12.0.3     |
| Node             | n/a     |         |
| npm/yarn         |    yarn     |  v1.22.10        |
| Operating System |  Mac       |    11.6     |

**Comment by jjenzz** [comment]
I'm assuming you managed to get this all figured out?

**Comment by mtergel** [comment]
no i just don't know what is exactly causing it.
didn't want to bother you

**Comment by benoitgrelard** [comment]
FWIW I don't see any error in the provided sandbox.

**Comment by mtergel** [comment]
Yes I aware trying to reproduce the error
sorry

**Comment by mtergel** [comment]
I apologize for any inconvenience I imported the wrong <Fallback /> component they had the same name. Whoops

**Comment by benoitgrelard** [comment]
No problems! 🙂

**Comment by jjenzz** [comment]
Glad you got it figure out 🎉
