### ISSUE TITLE
[IdProvider] Provide context in terminal warning

### ISSUE THREAD

**Issue by Aratramba** [radix-ui/primitives#968]
When running `next build` this warning came up:

> When server rendering, you must wrap your application in an <IdProvider> to ensure consistent ids are generated between the client and server.

To me it wasn't clear this was a Radix warning. Maybe add a link to the documentation here?

> When server rendering, you must wrap your application in an <IdProvider> to ensure consistent ids are generated between the client and server. Learn more here: https://www.radix-ui.com/docs/primitives/utilities/id-provider

### Relevant Radix Component(s)
https://www.radix-ui.com/docs/primitives/utilities/id-provider

### Example from Next.js
![image](https://user-images.githubusercontent.com/580312/141082669-17d7dd7d-db40-4817-b1f3-2ee062792722.png)

**Comment by benoitgrelard** [comment]
That's a great idea for the link to the docs. Thanks!

**Comment by Mnigos** [comment]
yup I got the same problem.

**Comment by StephenHaney** [comment]
Just looping around: the IdProvider is now deprecated and no longer required with the latest versions of the primitives, so this issue no longer applies. Thank you for the report and idea!
