### ISSUE TITLE
Drawer Component

### ISSUE THREAD

**Issue by kaushalyap** [radix-ui/primitives#986]
### Overview

Drawer component which opens panel  from edge of window when clicked on the menu button.

### Examples in other libraries

https://mui.com/components/drawers/

### Who does this impact? Who is this for?

Beginners and anyone want to save time.

### Additional context

Similar to sheet [here](https://design-system.modulz-deploys.com/#sheet)

**Comment by jjenzz** [comment]
I believe this is just a `Dialog` that is positioned at the side of the screen with CSS. 

@benoitgrelard @andy-hook I wonder if it is worth us adding a `Drawer` / `Sheet` component though that just re-composes `Dialog` to make things more explicit for people.

It seems to fit our ethos of providing components for common patterns rather than low level things that consumers are expected to compose themselves into their use-cases. Also, if we ever discover that `role=dialog` is not the correct pattern for this (I see MUI don't use that role), we can reflect that knowledge in a new release for them without changes to their implementation.

**Comment by benoitgrelard** [comment]
@colmtuite probably also has an opinion here too seeing as he created one in our design system: https://github.com/radix-ui/design-system/blob/master/components/Sheet.tsx.

I think I tend to agree with @jjenzz regarding our ethos.

**Comment by afnar** [comment]
Hey @colmtuite. I was thinking now about the mobile support for the Drawer implemented with a `Dialog` and would be cool to have a swipeable feature (for reference I see MUI does it: https://mui.com/components/drawers/#swipeable).
Would this be something Radix would do or is on charge of the consumer (us developers)?

**Comment by psirenny** [comment]
> I was thinking now about the mobile support for the Drawer implemented with a Dialog and would be cool to have a swipeable feature (for reference I see MUI does it: https://mui.com/components/drawers/#swipeable).

Yea, it's the swipeable interaction with Drawers and Sheets that make implementing those components non-trivial.

**Comment by eastack** [comment]
Any update?

**Comment by thuuupx** [comment]
I'm looking for it too 🧐

**Comment by mohamedamara1** [comment]
> > I'm looking for it too 🧐
> 
> Guys, I just found in this library: https://ui.shadcn.com/docs/components/sheet

Drawer has been added too in the library : https://ui.shadcn.com/docs/components/drawer

**Comment by jordan-sussman** [comment]
If you're looking to still leverage Radix, here's a drawer component built with Radix's `Dialog` primitive - https://github.com/jordan-sussman/open-sesame

**Comment by subhranshudas** [comment]
Guys/Gals, 

 Following is my setup
- Next JS - 14
- UI lib - https://ui.shadcn.com/docs/components/drawer (from vaul)

I have a responsive navbar, on desktop sizes show the navlinks in the middle, and on smaller/mobile sizes show them on the drawer when clicked on the hamburger menu icon.

Now my navlinks when clicked takes the user to a fragment on the same page. (<a href> with #fragmentID)

**The issue I am facing is**
In the Mobile Nav Drawer, I am wrapping the <a> with `DrawerClose` to trigger a close. When i click on a link the Drawer closes but the hyperlink section is not getting scrolled to.

I feel the hyperlink click event is somehow getting hijacked by Vaul Drawer. This issue doesn't happen in https://ui.shadcn.com/docs/components/sheet

Any help is appreciated!

Regards.

**Comment by anarkrypto** [comment]
MUI drawer has a Persistent Drawer which sits on the same surface elevation as the content and forces other content to change size and adapt to the viewport.

[Screencast from 17-04-2024 11:48:03.webm](https://github.com/radix-ui/primitives/assets/32111208/04261b85-2521-4260-b2e0-9650d25aa88b)

**Comment by rafaelsinosak** [comment]
any updates?

**Comment by isaachinman** [comment]
Hi all. It's trivial to make a non-swipeable drawer, with or without Radix. Has anyone implemented a _swipeable_ drawer with Radix? Would love to see an example if so!
